### ISSUE TITLE
Cannot deploy website solution in the marketplace dashboard

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/js-sdk#1004]
**Commit_ID** 3f1666f351edca360a152a3bfb853a341c078955 , **Branch** development

**Repository URL**
https://github.com/threefoldfoundation/www_tffoundation

**Branch**
master

![ff](https://user-images.githubusercontent.com/21218053/92323787-d970b380-f03b-11ea-8d4c-fffe0bde6bc2.png)

![ff1](https://user-images.githubusercontent.com/21218053/92323984-91eb2700-f03d-11ea-8434-66597270e25e.png)
![ff2](https://user-images.githubusercontent.com/21218053/92323986-931c5400-f03d-11ea-9d72-3678381b734c.png)

**Comment by AhmedHanafy725** [comment]
the reason for this failure #1017

**Comment by AhmedHanafy725** [comment]
should be fixed in https://github.com/threefoldtech/tf-images/commit/c05e7bb3eb97dba8b5ffa997cb538929dfb290ec

**Comment by Dina-Abd-Elrahman** [comment]
The same error still exists.

**Comment by xmonader** [comment]
this is not a valid website, website should be in the layout of repo like https://github.com/xmonader/www_incubaid content in src dir

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_D** 81773bf8ca5e948f05dcee61a7daf16d164c0809 , **Branch**  development

## Verification steps:

- when a deployment fails on a node

![ff](https://user-images.githubusercontent.com/21218053/92450306-90476d80-f1bb-11ea-9c1d-f9b58ce0c528.png)


 - that node should be blocked for some times and not used again

![ff](https://user-images.githubusercontent.com/21218053/92450404-b10fc300-f1bb-11ea-93c2-b29d00f91785.png)

![photo_٢٠٢٠-٠٩-٠٧_١٧-٤٤-٤٤](https://user-images.githubusercontent.com/21218053/92450482-c97fdd80-f1bb-11ea-9476-4ce60abdf5d7.jpg)

**Comment by xmonader** [comment]
@Dina-Abd-Elrahman  why reopening?

**Comment by mhost39** [comment]
Verified
commit : 76248c9ed0b398ccb1aa384293bdc917dd609bf6
branch: development

![image](https://user-images.githubusercontent.com/31102305/92465757-52ecdb00-f1cf-11ea-81aa-2799fc193142.png)
![image](https://user-images.githubusercontent.com/31102305/92465950-a19a7500-f1cf-11ea-9be5-94a380f7f025.png)
