### ISSUE TITLE
Small extensions for a 3Bot instance waits for payment forever.

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/js-sdk#1009]
### Description

The setup is as follows: I deploy a new 3Bot instance. This instance expires at 9:30 PM today. The chatflow creates a new pool with a suitable amount of cus and sus to keep the instance alive until that time. Since the workload is actives, the pool cloud units (cus and sus) decrease at a fixed rate. If I extend the instance to expire at 9:31 PM, the increase in cloud units is very small and before reaching the "waiting for payment" step, the cloud units drops back to a value less than they were before extension. This prevents the chatflow from seeing that the pool was extended.

### Steps to reproduce

1. Make a 3Bot instance that expires at 9:30 PM.
2. Extend it to expire at 9:31 PM.

**Comment by xmonader** [comment]
Requires min value for datetime to be at least 1 day or validation against the payment itself on stellar

**Comment by xmonader** [comment]
Shouldn't be an issue anymore because we don't check on trigger cus/sus but on payment info that got recently exposed #2151
