### ISSUE TITLE
Deployment starts at 2 minutes and it shows that it takes around 2 to 3 minutes to deploy

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/js-sdk#1010]
# Description

During ubuntu deployment: (it started with 2 minutes)
![Screenshot from 2020-09-03 15-55-02](https://user-images.githubusercontent.com/13040543/92326373-e9938d80-f051-11ea-96c1-12c9ce4fe481.png)

**Comment by xmonader** [comment]
@OmarElawady fix it as you see fit

**Comment by OmarElawady** [comment]
it's now hardcoded to 10, no inconsistencies now.

**Comment by MElborolossy** [comment]
Verifying
