### ISSUE TITLE
Identity should not be added if it has error in admin dashboard

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#1011]
### Version information

* OS: docker Ubuntu 20.04
* Branch: development
* commit: c3fe796303c612a8c035009ddbc1e8130e67a672
* Browser: Version 84.0.4147.125 (Official Build) (64-bit)
* explorer: testnet

### Steps to reproduce
1- Go to settings in admin dashboard.
2- Add identity with wrong details.
![image](https://user-images.githubusercontent.com/41957921/92326194-aab10800-f050-11ea-887f-06407a256473.png)
3- Then close it.
4- I found that the the identity is added, although it has a problem.
![image](https://user-images.githubusercontent.com/41957921/92326270-3165e500-f051-11ea-8b28-be0d1e9b2830.png)

**Comment by mhost39** [comment]
Verified
commit : 881f1904e00ba187ecf254cd8ba4857949767d38
branch: development

![image](https://user-images.githubusercontent.com/31102305/92400272-fbe1fa00-f12b-11ea-9580-46991dd6df38.png)
![image](https://user-images.githubusercontent.com/31102305/92400401-2a5fd500-f12c-11ea-84f7-7a3244b97ad8.png)
