### ISSUE TITLE
the last two steps in network chatflow have finish button 

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/js-sdk#1012]
![Screenshot from 2020-09-06 15-18-29](https://user-images.githubusercontent.com/26298009/92326671-2ceefb80-f054-11ea-8c22-ffb202099a49.png)
![Screenshot from 2020-09-06 15-18-38](https://user-images.githubusercontent.com/26298009/92326673-2f515580-f054-11ea-80b8-e06f12617aa8.png)

**Comment by mhost39** [comment]
Verified
commit :  881f1904e00ba187ecf254cd8ba4857949767d38
branch: development

![image](https://user-images.githubusercontent.com/31102305/92363899-8574d600-f0f2-11ea-9d9c-0e67d6486457.png)
![image](https://user-images.githubusercontent.com/31102305/92363940-9a516980-f0f2-11ea-9248-855c28eb525b.png)
