### ISSUE TITLE
minio success message is broken

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1016]
![image](https://user-images.githubusercontent.com/64129/92327590-054f6180-f05b-11ea-8c31-27c93303ac90.png)

**Comment by hossnys** [comment]
verified

![Screenshot from 2020-09-07 14-09-38](https://user-images.githubusercontent.com/26298009/92386113-6a668e00-f113-11ea-8bd4-77887573cbd4.png)
