### ISSUE TITLE
Check wallet balance before doing the transaction for creating/extending a pool

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/js-sdk#1018]
I can choose a wallet while extending the pool even if this wallet is empty. 

![ff](https://user-images.githubusercontent.com/21218053/92329980-cd044f00-f06b-11ea-8fd5-978782c4f301.png)
![ff1](https://user-images.githubusercontent.com/21218053/92329982-ce357c00-f06b-11ea-88fe-7ff719f735a6.png)
![image](https://user-images.githubusercontent.com/41957921/92330383-cc20ec80-f06e-11ea-86fa-b124cc64d404.png)

**Comment by xmonader** [comment]
fillter out the wallets without enough balance

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 8996cfa597aecfa66fb8c405779c43e921da6e3e, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/96888781-432b0c80-1486-11eb-8791-63f77d77af15.png)

![ff](https://user-images.githubusercontent.com/21218053/96889191-a87efd80-1486-11eb-9175-566339421f49.png)
