### ISSUE TITLE
TF GRID DEMO - payment - Rewrite instruction

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#1026]
<img width="992" alt="Screenshot 2020-09-07 at 10 49 41" src="https://user-images.githubusercontent.com/43240801/92368401-f9fe4380-f0f7-11ea-95d7-2e437fef7c51.png">

Please scan the QR Code below for the payment details if you missed it from the previous screen

**Comment by BolaNasr** [comment]
Fixed:
### Branch 
development_payment_qr_code
### commit id 
56fa99988f78d62380c8ecc3b36c09f61fe35cea

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID**  a35fb9f8b278a8ed396b24d725e3f78d7024270f, **Branch** development_payment_qr_code

![ff](https://user-images.githubusercontent.com/21218053/92480539-52f7d580-f1e5-11ea-9626-9673d433bde0.png)
