### ISSUE TITLE
TF GRID DEMO - payment - qr code details need rework

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#1027]
at the moment if qr code is scanned its only giving users the wallet address, not the amount of tft or the memo text.
<img width="1440" alt="Screenshot 2020-09-07 at 10 52 19" src="https://user-images.githubusercontent.com/43240801/92368743-68430600-f0f8-11ea-99e5-f48f69410b6d.png">

all is important if you missed the payment screen.  because i wont know how much i should send, and what my memo text should be
<img width="971" alt="Screenshot 2020-09-07 at 10 48 28" src="https://user-images.githubusercontent.com/43240801/92368849-8b6db580-f0f8-11ea-91f6-4f9f7981e4ca.png">

**Comment by RafyAmgadBenjamin** [comment]
Fixed:
### Branch 
development_payment_qr_code
### commit id 
56fa99988f78d62380c8ecc3b36c09f61fe35cea

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID**  a35fb9f8b278a8ed396b24d725e3f78d7024270f, **Branch** development_payment_qr_code

![ff](https://user-images.githubusercontent.com/21218053/92480539-52f7d580-f1e5-11ea-9626-9673d433bde0.png)
