### ISSUE TITLE
TF GRID DEMO - WIKI DEPLOY ISSUES

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#1028]
- [x]   wiki is failed to deploy, and but it is listed at ‘my workload’ ....? sashaastiadi-wiki-sasha.tfgw-testnet-01.3x0.me
<img width="692" alt="Screenshot 2020-09-07 at 11 08 59" src="https://user-images.githubusercontent.com/43240801/92370455-99243a80-f0fa-11ea-92d7-ec1395951484.png">
<img width="822" alt="Screenshot 2020-09-07 at 11 10 01" src="https://user-images.githubusercontent.com/43240801/92370535-b5c07280-f0fa-11ea-978b-3521bb4d5d40.png">

- [x] On my workload, when wiki domain is clicked, it should open a new tab instead of in the same tab. 

- [x] users get reminded on unsafe connection, can we resolve / remove this?
<img width="719" alt="Screenshot 2020-09-07 at 11 01 50" src="https://user-images.githubusercontent.com/43240801/92370610-ce308d00-f0fa-11ea-8a8e-aa6dcc579138.png">

- Domain doesn’t work/ wiki is not displayed successfully
<img width="597" alt="Screenshot 2020-09-07 at 11 02 02" src="https://user-images.githubusercontent.com/43240801/92370637-d688c800-f0fa-11ea-95cc-627e2ab08f00.png">

- Where can I access my wiki repo?

**Comment by xmonader** [comment]
> wiki is failed to deploy, and but it is listed at ‘my workload’ ....? sashaastiadi-wiki-sasha.tfgw-testnet-01.3x0.me

fixed already (TODO: link where)

> On my workload, when wiki domain is clicked, it should open a new tab instead of in the same tab. 
@abom please link ur commit id

> users get reminded on unsafe connection, can we resolve / remove this?
No, staging env used will use self signed certs, and we won't consume llet's encrypt certs for staging envs. 

> Domain doesn’t work/ wiki is not displayed successfully
validation been done on the urls to be in the form of the https/git URLs

> Where can I access my wiki repo?
Don't understand what you mean here.

**Comment by xmonader** [comment]
removed the first item to be able to verify that issue alone

**Comment by Pishoy** [comment]
verified 
- URL is opened on a new tab
- the token amount, message is shown on scan QR
