### ISSUE TITLE
Uncaught TypeError: Cannot read property 'naturalHeight' of undefined at license page

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#1029]
### Version information

* OS: e.g. Ubuntu 20.04
* project commit/version: e.g. js-ng 11.0.0a3
* Browser: e.g. chrome 84

### Steps to reproduce

just visit https://deploy3bot.grid.tf/threebot_deployer/#/license

### Traceback/Logs/Alerts

![Screenshot from 2020-09-07 11-12-58](https://user-images.githubusercontent.com/10658229/92370954-4bf49880-f0fb-11ea-9179-2ca0923d5ab5.png)

**Comment by AhmedSa-mir** [comment]
Problem is with v-parallax component in vuetify. See https://github.com/vuetifyjs/vuetify/issues/1029#issuecomment-395559808
