### ISSUE TITLE
Harden the publishing chatflows

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1033]
- Add description for what is title, repo url, branch
- Validated the repo url

**Comment by xmonader** [comment]
done in 4114d99ba587d2978ebeafb28c01959968b5841f

![image](https://user-images.githubusercontent.com/64129/92379936-93355600-f108-11ea-9fda-c37676bec4c8.png)

**Comment by Pishoy** [comment]
verified
![image](https://user-images.githubusercontent.com/21987477/92462584-f38ccc00-f1ca-11ea-9c8f-de147179c356.png)
