### ISSUE TITLE
TF GRID DEMO - WIKI - add screen for wiki repo initialize instruction

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#1035]
before starting to ask the user to name their repo, we need a screen to ask them if they have initialize a repo on github.

You would need to first create a github repo for your wiki files before you deploy a hosted wiki. Have you created a wiki repo on your github? If not, please  go to [Initialize a Wiki Repo on Github](https://manual2.threefold.io/#/wiki_prework.md) and click next once it's completed.

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/92453217-4791b380-f1bf-11ea-82e2-edb047a3685c.png)

All info will be shown on this screen and the user can follow the manual to prepare his repo
