### ISSUE TITLE
disable functionality of 3bot if the user doesn't agree on T&C

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1037]
if the user doesn't agree on T&C don't let them into the 3bot

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** ee9750bfc45e14d3c81eea7a77edd1bb5d166095 , **Branch** development

If you press cancel for T&C you will logout from the admin dashboard and forward again to the login page 
![ff](https://user-images.githubusercontent.com/21218053/92454447-cfc48880-f1c0-11ea-9f50-2aaf5ebb2d58.png)
