### ISSUE TITLE
custom domain message to create cname is broken 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#1041]
### Version information

* OS: docker Ubuntu 20.04
* Branch: development
* commit: 59ff07cf80c61c273b067abce18704f0a8542f1d
* Browser: Version 84.0.4147.125 (Official Build) (64-bit)
* explorer: testnet

![image](https://user-images.githubusercontent.com/41957921/92390842-f11f6900-f11b-11ea-9c4f-e06f0cd0c66f.png)

**Comment by waleedhammam** [comment]
![Screenshot from 2020-09-08 11-38-48](https://user-images.githubusercontent.com/10658229/92460314-1cf82880-f1c8-11ea-8563-6cf4e816e787.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** b66bb44f5f640eaa2414ca2a0902cada139b6a56 , **Branch**  development

![ff](https://user-images.githubusercontent.com/21218053/92463601-503cb680-f1cc-11ea-912f-0ba66424e047.png)
