### ISSUE TITLE
Failed hosted threebot deployment does not refund

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#1045]
Paid for a hosted 3bot deployment which eventually failed. Never got a refund..

Seems like a hosted 3bot deployment will fail if you already have one running with the same name?

https://stellar.expert/explorer/testnet/tx/f3d5c6979d9662671aafa75feab512a1b46e21172102c1f33997e8df61adbc64

**Comment by xmonader** [comment]
resources will remain held in your provisioned capacity pool for future use. message improved in https://github.com/threefoldtech/js-sdk/pull/1049

> Seems like a hosted 3bot deployment will fail if you already have one running with the same name?
requires further investigation

**Comment by waleedhammam** [comment]
Regarding

> Seems like a hosted 3bot deployment will fail if you already have one running with the same name?

- Deploying an instance with same name with a running one is not possible, it must be unique
![Screenshot from 2020-09-08 11-47-30](https://user-images.githubusercontent.com/10658229/92461092-174f1280-f1c9-11ea-99bc-c79d068100c9.png)


- Deploying an instance with an old name will deploy and restore the latest backup (but you have to remember the secret)

![Screenshot from 2020-09-08 11-48-12](https://user-images.githubusercontent.com/10658229/92461150-2fbf2d00-f1c9-11ea-8a06-f4330040c8c6.png)



- If you don't want the backups and want to start fresh you can delete them

![Screenshot from 2020-09-08 11-46-36](https://user-images.githubusercontent.com/10658229/92460998-f8e91700-f1c8-11ea-83db-08b639a6f961.png)
