### ISSUE TITLE
Hosted 3Bot deployment: message is it succeeded but nothing found

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#1051]
#802 # Description

I deployed a hosted 3Bot and the chatflow said all worked out well.
However, nothing seen in the list of deployed 3Bots 
<img width="1235" alt="Screenshot 2020-09-08 at 08 17 05" src="https://user-images.githubusercontent.com/30384423/92440797-553e3d80-f1ad-11ea-88ee-9a3fb99e8bb5.png">

### Version information

* OS: MacOS
* Version hosted 3Bot: deploy3bot-2.grid.tf
* Browser: Chrome 85

**Comment by Pishoy** [comment]
verified 


![image](https://user-images.githubusercontent.com/21987477/92468169-06a39a00-f1d3-11ea-9b23-37d23e62cbd0.png)
