### ISSUE TITLE
Hosted 3Bot deployment: succeeded but can't be shown

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#1052]
### Description

I deployed a hosted 3Bot, and the chatflow said it all went well, but Google Chrome gives an error, saying it can't be shown due to 'scrambled credentials'. 
<img width="1235" alt="Screenshot 2020-09-08 at 08 18 16" src="https://user-images.githubusercontent.com/30384423/92441009-b7973e00-f1ad-11ea-8a5a-9613d31e813a.png">

### Version information

* OS: MacOS
* Hosted 3Bot through deploy3bot-2.grid.tf
* Browser: Chrome 85

**Comment by xmonader** [comment]
It's using self-signed certificates for mac users they probably need to do 
```
open -n -a /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --args --user-data-dir="/tmp/chrome_dev_test" --disable-web-security --ignore-certificate-errors :)
```
on production, you will get certificates issued from let's encrypt
