### ISSUE TITLE
Update T&C on Navbar to pull directly from new t&c on github

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#1055]
<img width="319" alt="Screenshot 2020-09-08 at 11 22 41" src="https://user-images.githubusercontent.com/43240801/92458422-a823ef00-f1c5-11ea-9a4b-dd9093d7687b.png">
https://github.com/threefoldfoundation/legal/blob/master/src/terms_conditions_all.md

**Comment by xmonader** [comment]
It was like that, but someone changed that link https://raw.githubusercontent.com/threefoldfoundation/legal/master/src/termsconditions.md

![image](https://user-images.githubusercontent.com/64129/92463038-8f1e3c80-f1cb-11ea-9cc9-53aed9cde400.png)

**Comment by xmonader** [comment]
should be fixed in fa556a0f995271d7e153408646f4efa7a0d7e20d
