### ISSUE TITLE
Use dedent in multi-line md_show messages

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#1059]
### Description

md multi-line strings can be misbehave due to indentation and doesn't look pretty
example:

![Screenshot from 2020-09-08 11-58-43](https://user-images.githubusercontent.com/10658229/92462386-b32d4e00-f1ca-11ea-9ddb-40211ff29b8c.png)

### Example Implementation

```
from textwrap import dedent

res = """\
Please create a `CNAME` record in your DNS manager for domain: `{{domain}}` pointing to:
{% for dns in gateway.dns_nameserver -%}
- {{dns}}
{% endfor %}
"""
self.md_show(dedent(res), md=True)
```

![Screenshot from 2020-09-08 12-01-44](https://user-images.githubusercontent.com/10658229/92462698-161ee500-f1cb-11ea-8a65-3e5b3af58634.png)

# TODO

## solutions

- [x] 4to6
- [x] delegation
- [x] exposed
- [x] flist
- [x] gollum
- [x] kubernetes
- [x] minio
- [x] monitroing
- [x] network
- [x] pools
- [x] ubuntu
- [x] reservation_chatflow
- [x] deployer

## apps

- [x] blog
- [x] cryptpad
- [x] discourse
- [x] gitea
- [x] gollum
- [x] mattermost
- [x] peertube
- [x] publisher
- [x] taiga
- [x] website
- [x] wiki
- [x] appschatflow base
- [x] deployer

## misc

- [x]  polls
- [x] trader

**Comment by Pishoy** [comment]
verified 
- ubuntu 
![image](https://user-images.githubusercontent.com/21987477/92491318-62c9e680-f1f2-11ea-8cb6-fad76c25751c.png)

![image](https://user-images.githubusercontent.com/21987477/92491375-71b09900-f1f2-11ea-83bb-f5480cc1b607.png)
