### ISSUE TITLE
threebot start reports threebot started too quick

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#106]
```
✅ Threebot server started

Visit admin dashboard at: http://localhost/

```

It should wait until nginx + gedis port is taken

**Comment by m-motawea** [comment]
`threebot start` command waits for each port of (80, 443, 16000, 8999) of services before success message.
if a port of the above is not ready within 15 seconds the command will exit and you should stop the server then try again

![image](https://user-images.githubusercontent.com/32568986/85697115-cbb4be80-b6d9-11ea-9fa0-2362cca8fd4a.png)

**Comment by grimpy** [comment]
In my case it does not even bother to start anything tmux stays empty startupcommand does not look like its being run.

Altough when  running 
`jsng 'j.servers.threebot.start_default(wait=True)'` it works fine

**Comment by grimpy** [comment]
Fixed in https://github.com/threefoldtech/js-sdk/commit/575de3ef98af98f6a1bce721c832e02d7bd07864

**Comment by hossnys** [comment]
Verified
