### ISSUE TITLE
Hoster 3bot - update links of wikis on 'wikis' section

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#1062]
<img width="367" alt="Screenshot 2020-09-08 at 13 35 12" src="https://user-images.githubusercontent.com/43240801/92471446-3f923d80-f1d8-11ea-9ba1-39373fa50c7a.png">

edit:

- [x] Sidebar / section title should be Threefold Wikis

- [x] sdk should be 'Threefold Manual' - manual.threefold.io

- [x] Threefold should be 'Threefold Wiki' - wiki.threefold.io

**Comment by xmonader** [comment]
I think section should be named "Threefold Wikis" instead of repeating it?
Also, what is the point of referencing threefold now in a hosted 3bot?

**Comment by sasha-astiadi** [comment]
@xmonader agreed. changed my issue description thank you

**Comment by BolaNasr** [comment]
PR : https://github.com/threefoldtech/js-sdk/pull/1068

![image](https://user-images.githubusercontent.com/10259267/92484197-d74c5780-f1e9-11ea-91af-9f6f3c69797b.png)

**Comment by Pishoy** [comment]
verified 

- sdk
```
commit 3c805c29d2e3f7336dff97a43e2c328d693b178d (HEAD -> development, origin/development, origin/HEAD)
Merge: f059173f d4ed67e9
Author: Waleed <waleed.hammam@gmail.com>
Date:   Tue Sep 8 15:56:07 2020 +0200

    Merge pull request #1060 from threefoldtech/development_mdfixes
    
    Update md messages for chatflows

```
