### ISSUE TITLE
hosted 3bot - change 'capacity' into 'Capacity Explorer' on side bar

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#1064]
because we have :
capacity pools on sidebar, 
so we shouldnt name it just 'capacity' 
so people wont be confused

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-09-08 15-20-36](https://user-images.githubusercontent.com/26298009/92481235-563f9100-f1e6-11ea-87e4-286e36c58d4c.png)
