### ISSUE TITLE
3bot deployer: add more info regarding recovery seed

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/js-sdk#1065]
Right now, when reading the text, it kinda feels like the user is expected to already have a secret key. There could probably be some more clarification that this is just something the user can choose right now
![image](https://user-images.githubusercontent.com/22023708/92476614-87689300-f1df-11ea-817d-f77a4652d4b6.png)

**Comment by gmachtel** [comment]
Can't you simply say 'choose a recovery secret' ? Or maybe use the word password/passphrase. These terms are known to the user, and he knows he has to choose one himself.

**Comment by sasha-astiadi** [comment]
to answer @gmachtel and @LeeSmet 

i do agree that we should differentiate in between a recovery 'password' and 'seed phrase' . 

password are typically characters, short (8-15 characters) and user-generated.

seed phrase  is usually long, unique words auto generated by system. for example, the one on 3bot connect.

which one is this? @xmonader @LeeSmet . i do not want user to confuse the 2, and ending up with users typing their 3bot connect seed phrase to recover their 3bot.

if it's a password, then we say password.

correction:

Recovery Password

Please create a secure password for your new 3Bot. Your password is an important information used to recover your hosted 3Bot.

**Comment by LeeSmet** [comment]
Well it turns out to be a password (afaik)

That being said, right now, we say **the** recovery secret (-> password), which to me indicates that the password was already chosen in a prior step (by the user or for the user). This is not the case here, a user chooses a password here in this step. So imo this should also be a bit more clear

**Comment by xmonader** [comment]
It's a password and used to be defined as password #807 

It's used to
- that password we create user repos on the backup servers (in the first time)
- allows restoring the last snapshot matching the combo of the solution name + username when the right password is used.

**Comment by sasha-astiadi** [comment]
then it should be written as:

Recovery Password

Please create a secure password for your new 3Bot. This password is an important information used to recover your hosted 3Bot.

**Comment by Dina-Abd-Elrahman** [comment]
- create -> name deployed (The specified 3Bot name already exists)

![ff](https://user-images.githubusercontent.com/21218053/92748101-1c58c100-f385-11ea-8b6f-08e7681c7a74.png)

- create -> not deployed but exists before (The specified 3Bot name was deployed before

![ff](https://user-images.githubusercontent.com/21218053/92748253-3eeada00-f385-11ea-8d28-0c6b318339e6.png)

**Comment by Dina-Abd-Elrahman** [comment]
- recover -> name deployed (The specified 3Bot name already exists)
![ff](https://user-images.githubusercontent.com/21218053/92748711-b456aa80-f385-11ea-954d-da06f6e29d7a.png)

- recover -> not deployed and doesn't exist
![ff](https://user-images.githubusercontent.com/21218053/92748922-e962fd00-f385-11ea-9340-7d3117bfee30.png)

**Comment by Dina-Abd-Elrahman** [comment]
![ff](https://user-images.githubusercontent.com/21218053/92749626-92a9f300-f386-11ea-8adb-40d467255aa0.png)
