### ISSUE TITLE
new loader regressions

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#107]
# regressions

- can't create a wallet #96 
- can't call j.clients.explorer.get_default #97 
- network solutions count is still zero after creation #99 

more to be listed if needed

**Comment by abom** [comment]
The new loader should be fixed (https://github.com/threefoldtech/js-ng/pull/370).

Now we have an open PR that replaces the old loader here and at core:

https://github.com/threefoldtech/js-sdk/pull/116
https://github.com/threefoldtech/js-ng/pull/376


Once they're verified, I will update the docs about the loader too, then merge all.

**Comment by hossnys** [comment]
all mentioned sub-issues verified

**Comment by abom** [comment]
Need to re-verify this again, as the new loader is re-merged.

**Comment by hossnys** [comment]
verified again
