### ISSUE TITLE
Delete reservation button in details in 3bot deploy package doesn't do anything

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#1072]
### Description

when I click delete reservation nothing happens. the delete button shown in the previous table works fine 

![image](https://user-images.githubusercontent.com/32568986/92495956-d02c4600-f1f7-11ea-9303-c896fc34a88e.png)

**Comment by Dina-Abd-Elrahman** [comment]
![ff](https://user-images.githubusercontent.com/21218053/92599397-7fc1f080-f2aa-11ea-9264-68b1d9c9a8c9.png)
