### ISSUE TITLE
If insufficient funds during capacity pool reservation, no clear error message

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#1077]
### Description

When creating or extending a capacity pool, if there is insufficient funding on the account, the wallet can be selected but there is an error generated 'something went wrong'. Can this error be more specific ? (insufficient funding, ...) 

### Version information

* OS: MacOS
* on Hosted 3Bot
* Chrome 85

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 01ac08bc8051698b0478d22baa876fd2d4a4bef9, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/96590309-23f57900-12e6-11eb-81ec-694ac595d053.png)
