### ISSUE TITLE
For demos, run them on testnet only and use an implicit wallet 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1084]
For demos
- run them on testnet only
- use an implicit wallet (with TFT) `demos_wallet` (make sure it exists or created in package.py of marketplace)
- don't show payment step at all for demos.
- limit the life of the demo instance to max 3 hours

**Comment by xmonader** [comment]
check https://github.com/threefoldtech/js-sdk/blob/development/jumpscale/packages/polls/package.py

**Comment by BolaNasr** [comment]
Commit : 14a13cb32d6c9ab9e6f3a5fbaf2776763cbf8210

**Comment by Pishoy** [comment]
verified by creating a wiki and no payments appear 
as https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/tutorials/add_funds_to_wallet.md

- SDK version 
```
(js-sdk-NQNSzBV5-py3.8) root@tfwallet-prod:/opt/js-sdk# git log -1
commit 24e1b953b5b2d1dc80c320840c47200ea7f5cb4d (HEAD -> development, origin/development, origin/HEAD)
Author: xmonader <xmonader@gmail.com>
Date:   Thu Sep 10 10:52:39 2020 +0200

    changed message of pool chatflow (#1081)

```
