### ISSUE TITLE
Broken text on network success page

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/js-sdk#1089]
After successfully deploying a network, I end up at a screen with a wireguard config, an option to download it, and instructions to set up the wireguard (by navigating to the location of the downloaded config file, and performing `wg-quick up ${CONFIG_NAME}`. If I then click next, I arrive on the following screen:

![image](https://user-images.githubusercontent.com/22023708/92602524-894d5780-f2ae-11ea-94ca-731991761ddd.png)

The text here does not make sense, and also the command is wrong, since I (the user) was never instructed to move the config file I downloaded to the `/etc/wireguard` folder

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID**  9a849202e01f9e01844d813e93aa4cf9cc4c1a1c , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/92696325-fb26af00-f349-11ea-9763-37ee85dd0a57.png)
