### ISSUE TITLE
Wrong instructions to start wireguard after creating a network

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/js-sdk#1090]
After a network is deployed, you receive a screen with a wireguard config, and a download button:

![image](https://user-images.githubusercontent.com/22023708/92603254-5f486500-f2af-11ea-8be2-ae9fbd9d58c2.png)
The instructions to bring up the wg-interface are wrong (at least on linux). For instance, I press download, and allow firefox to save the config in the default location (`~/Downloads`). After navigating to this directory in the terminal, and executing the command, I get an error saying `wg-quick: `/etc/wireguard/wg-477825.conf.conf' does not exist`. In order for this to work, the command should be `wg-quick up ./wg-477825.conf` instead (note the explicit local path before the filename). Otherwise wireguard will look for a config by that name in the default config directory

PS: the config also seems to bleed through the edges of the card a bit :)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID**  9a849202e01f9e01844d813e93aa4cf9cc4c1a1c , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/92696546-50fb5700-f34a-11ea-8057-0e31ec108e3e.png)
