### ISSUE TITLE
Unable to deploy ubuntu container on freefarm

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/js-sdk#1091]
Even when using the default (minimal) values for cpu/memory/root disk size, all attempts to deploy a ubuntu container on freefarm (testnet) eventually lead to the following screen:

![image](https://user-images.githubusercontent.com/22023708/92613399-3af28580-f2bb-11ea-8710-937a39ad33c4.png)

Both when letting the system choose a node for me, as when attempting to choose myself.

While I understand that all freefarm nodes currently have more than 100% cpu/mem utilization, these values _are_ overprovisioned, and enough ssd space is available, so in theory my deployment should succeed.

Also, should it be the case that the error is caused by the reason above, then the error message could probably use some clarification. "Failed to find resource..." is a bit abstract. A new user might not imediatly understand all nodes in the pool are completely full.

**Comment by xmonader** [comment]
@LeeSmet the same happens when you go to developer settings and enable overprovisioning?

**Comment by LeeSmet** [comment]
Indeed it works if I enable this setting, though I did not know it existed, and it was never clarified anywhere that this was an option. Perhaps there could be a check to see if this would allow the deployment to succeed, and if so, also add this in the error (so the user at least knows its possible)?

**Comment by xmonader** [comment]
Zaibon added that section yesterday https://manual2.threefold.io/#/3bot_settings?id=developers-options. I agree on appending on the error message :ok_hand:

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** bd546540e3930ce038ab925ef8c20011a65818fd, **Branch**  development

![ff](https://user-images.githubusercontent.com/21218053/93194331-4117b480-f748-11ea-9903-154c8a690231.png)
