### ISSUE TITLE
enable showing the words of the identities in the admin dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1099]
Right now it's something like 
![image](https://user-images.githubusercontent.com/64129/92700697-658e1e00-f34f-11ea-9101-e9000eff7e13.png)

While it should be more of the way we do in stellar wallets with secret field

![image](https://user-images.githubusercontent.com/64129/92700763-7e96cf00-f34f-11ea-89cf-a6aea5c1b44d.png)

**Comment by ranatrk** [comment]
We remove the words from the data returned to the frontend because any admin added in the admins list can access the identities from the dashboard and in many cases they aren't the identity owners and shouldn't have access to the words.

**Comment by xmonader** [comment]
I see, for the case of 3bots they will be using a generated identity so that doesn't compromise their 3bot words no?and only them added as admin by default.

another point is the data still accessible from the shell too if they open the code server terminal they can move around and see the stored data?

**Comment by xmonader** [comment]
@zaibon what do you think?

**Comment by zaibon** [comment]
Any admins are already using the private key of the 3bot anyhow. So allow them to actually see the words doesn't really change anything to me. But backing up your seed is always good practice, so I would still go forwards with this.

It's up to the first 3bot admin to make sure he doesn't allow access to it to the wrong people. On this side it's like any other system.

**Comment by rkhamis** [comment]
I guess at the end of the day, the 3bot administrator is responsible for who has access and as such, who can see their words.

**Comment by Pishoy** [comment]
verified 
![image](https://user-images.githubusercontent.com/21987477/93013624-56ef7300-f5aa-11ea-9d97-9382bfc2979f.png)
- sdk version
```commit fa58de7bd1aded271fd77c5245d33572c6ea38e1 (HEAD -> development, origin/development, origin/HEAD)
Merge: 76b76960 3781e6e2
Author: xmonader <xmonader@gmail.com>
Date:   Thu Sep 10 16:00:50 2020 +0200

    Merge pull request #1104 from threefoldtech/development_dashboard_show_words
    
    Enable showing the words of the identities in the admin dashboard



```
