### ISSUE TITLE
Deployed 3Bot instances to start with a funded wallet

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#1102]
### Description

After deploying 3Bot creat a wallet for testnet and a wallet for mainnet and fund the testnet with the new facuet

### Implementation

should be in entrypoint.py

**Comment by xmonader** [comment]
- Shouldn't fail if the faucet service is down or stellar was down
- Let's have it abstracted somewhere so the user can click a button to retry that on the dashboard? maybe Get TFT button?

**Comment by waleedhammam** [comment]
- Added in 3Bot entrypont

- Added in admin dashboard

![Screenshot from 2020-09-10 16-40-29](https://user-images.githubusercontent.com/10658229/92747605-a6ecf080-f384-11ea-9274-e2a4096f038f.png)
![Screenshot from 2020-09-10 16-40-25](https://user-images.githubusercontent.com/10658229/92747612-a81e1d80-f384-11ea-9b25-d85d67a2a8e9.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 5fe56fe06a4de4534e17128573a5e545ab5dbc97 , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/93016222-dd627f80-f5bf-11ea-924c-e29abbd79a87.png)
