### ISSUE TITLE
ubuntu end 2 end script

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1105]
create ubuntu end 2 end script 

- wallet name should be "wallet"

consult the manual page for provisioning ubuntu

**Comment by Pishoy** [comment]
verified
1 - create a wallet named "wallet" with enough funds.
2 - run ubuntu.py inside examplescripts, the result should be a deployed ubuntu.
```
root@tfwallet-prod:/opt/js-sdk# cd examplescripts/
root@tfwallet-prod:/opt/js-sdk/examplescripts# python3 ubuntu.py 
solution-expose-ubuntu-demo-bishoy.tfgw-testnet-01.gateway.tf
```
