### ISSUE TITLE
Farm Management: Cannot change owner of a farm

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#1109]
See screenshot
![Screenshot from 2020-09-10 16-58-28](https://user-images.githubusercontent.com/17138347/92750098-448cf380-f376-11ea-97f9-02f123a0a906.png)

**Comment by m-motawea** [comment]
I tried this on a local installation and worked ok but fails with the mentioned error on hosted 3bot

**Comment by DylanVerstraete** [comment]
Yes I was testing on a hosted 3bot.

**Comment by Dina-Abd-Elrahman** [comment]
![ff](https://user-images.githubusercontent.com/21218053/93077293-e2d7cc80-f688-11ea-86b5-5448ac587460.png)
