### ISSUE TITLE
UX: pools list is empty but I can see my pools if I try to do an extend

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/js-sdk#1111]
List view of the pools is empty (while I do have pools)

![image](https://user-images.githubusercontent.com/10920323/92751021-e701a280-f387-11ea-8110-a05506f4822c.png)

If i try to extend pools I get this

![image](https://user-images.githubusercontent.com/10920323/92751138-026cad80-f388-11ea-8a00-0fc12bf40240.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 9dfa6a3a1b507ff4703ef348ea3d9956a02a1fcf , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/93015312-c8362280-f5b8-11ea-9f71-bbbf40c53a57.png)
