### ISSUE TITLE
3bot deployer - new homepage text for deployer

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#1112]
<img width="1132" alt="Screenshot 2020-09-10 at 17 03 27" src="https://user-images.githubusercontent.com/43240801/92750915-cd605b00-f387-11ea-8fa9-95f34ea9bf64.png">

Welcome to 3Bot Deployer

3Bot is the system administrator that helps you to maintain project deployments and activities on top of the TF Grid. 
' Deploy a new 3Bot' 'View my existing 3Bots'

**Comment by xmonader** [comment]
done in 93a5d83ee2c5a4aa22e84870da74e2ef1e8bf6b0

**Comment by Dina-Abd-Elrahman** [comment]
![ff](https://user-images.githubusercontent.com/21218053/93014155-f0208880-f5ae-11ea-836c-c2a455207091.png)
