### ISSUE TITLE
threebot clean

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1119]
subcommand clean would help in 

1- cleaning the active running 3bot config + nginx main instance and all of that previous data
2- `clean -a`  maybe to clean everything in jsng?

probably clean -a should be part of jsctl config, but we want the user to know the least number of commands so my suggestion is having that on threebot directly?

**Comment by xmonader** [comment]
it was implemented in https://github.com/threefoldtech/js-sdk/pull/1121

**Comment by Pishoy** [comment]
![image](https://user-images.githubusercontent.com/21987477/93455561-caf88680-f8dc-11ea-9f08-fa0bf0ff9365.png)
```
(js-sdk-NQNSzBV5-py3.8) root@tfwallet-prod:/opt/js-sdk# threebot clean --all
cleaning alerts...
Do you want to remove /root/.config/jumpscale ? n
(js-sdk-NQNSzBV5-py3.8) root@tfwallet-prod:/opt/js-sdk# 
(js-sdk-NQNSzBV5-py3.8) root@tfwallet-prod:/opt/js-sdk# 

```
![image](https://user-images.githubusercontent.com/21987477/93455829-288cd300-f8dd-11ea-8ba9-d430ba152eaf.png)
```
(js-sdk-NQNSzBV5-py3.8) root@tfwallet-prod:/opt/js-sdk# threebot clean --all
cleaning alerts...
Do you want to remove /root/.config/jumpscale ? y
Previous configuration is deleted.
```
- will revoke your 3bot account and need to re-create the account again
