### ISSUE TITLE
Ability to add 3bot packages in a subfolder of a github repo 

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#1120]
### Description

Currently it is only possible to add a package in the root of a github repo using the giturl parameter in the packagemanafer add method. using a giturl like `git_url="https://github.com/threefoldfoundation/tft-stellar/tree/master/ThreeBotPackages/activation-service"` would be nice since we can keep functionally related packages together in a single repo. Repo explosion makes things unclear and hard to mamage.

**Comment by ashraffouda** [comment]
should be solved after merging this https://github.com/threefoldtech/js-sdk/pull/1394

**Comment by robvanmieghem** [comment]
@Dina-Abd-Elrahman Is this also documented?
