### ISSUE TITLE
use container logs feature for demo marketplace for debugging

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1126]
Use that feature to aggregate logs, it's very hard to debug atm

**Comment by ranatrk** [comment]
The initial intent was to direct all the logs to redis, but based on input from @zaibon  and @muhamadazmy the only way this could be done is if the containers used zinit which isn't the current scenario with the marketplace apps and so will postpone this until the flists are updated.

**Comment by zaibon** [comment]
To be clear. Only the entrypoint process logs of the container can be streamed.

If you are using some sort of process manager to run multiple processes in the container. It's up to the process manager to deal with logs of all child processes.

Zinit allows exactly that so it's a viable solution indeed.

**Comment by rkhamis** [comment]
already done for 3bot. this is to track the rest of the apps

**Comment by xmonader** [comment]
done for 3bot + nginx + trc, rest to be in a separate issue
