### ISSUE TITLE
Cannot deploy minio solution (Master/Slave) on admin dashboard 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/js-sdk#1129]
- Cannot deploy minio solution (Master/Slave) on admin dashboard 

![ff](https://user-images.githubusercontent.com/21218053/93014134-b0f23780-f5ae-11ea-977d-99ac0c82dd7b.png)

**Commit_ID** e46b1d867c5b5dc37b985f4c1ce1317e03af8a06 , **Branch** Development

**Comment by xmonader** [comment]
should be fixed in https://github.com/threefoldtech/js-sdk/pull/1117

**Comment by Dina-Abd-Elrahman** [comment]
it works fine now.
