### ISSUE TITLE
Changing default identity and explorer dont change

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/js-sdk#113]
- with having 2 instances of explorer clients one for testnet and mainnet saved. When changing default explorer using `j.clients.explorer.default_addr_set(url='https://explorer.grid.tf/explorer') ` then getting the default explorer doesn't get a different instance 

- having 2 identities created and saved and reistered, one on testnet and the other on mainnet. When switching the default identity using `j.core.identity.set_default(NEW_INSTANCE_NAME)` and then retrieving it using j.core.identity.me gets the old instance
![Screenshot from 2020-06-25 14-31-51](https://user-images.githubusercontent.com/17128393/85722062-38d44e00-b6f2-11ea-9b4d-a2ef5602ebaf.png)

**Comment by ranatrk** [comment]
changing identity:

![Screenshot from 2020-06-25 15-32-48](https://user-images.githubusercontent.com/17128393/85759378-595fd080-b711-11ea-8992-f27cc63747d1.png)

changing explorer url:
![Screenshot from 2020-06-25 15-36-18](https://user-images.githubusercontent.com/17128393/85759490-6086de80-b711-11ea-8547-727a54ce3914.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
