### ISSUE TITLE
4to6 gateway chatflows is starting with the second step

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#1144]
### Version information

* OS: docker Ubuntu 20.04
* Branch: development
* commit: 5e1d62a8949b9e93b7700614a1ff58906d4eddfa
* Browser: Version 84.0.4147.125 (Official Build) (64-bit)
* explorer: testnet

![image](https://user-images.githubusercontent.com/41957921/93076393-8fb14a00-f687-11ea-9850-dc92c00233de.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 3fb43399683fe291a1ad56b2ec07ba5fef8e7eeb , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/93099112-f0507f00-f6a7-11ea-9ff1-7d5325a69efb.png)
