### ISSUE TITLE
Inconsistent between network and 4to6GW in wireguard configuration

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#1145]
### Version information

* OS: docker Ubuntu 20.04
* Branch: development
* commit: 5e1d62a8949b9e93b7700614a1ff58906d4eddfa
* Browser: Version 84.0.4147.125 (Official Build) (64-bit)
* explorer: testnet

### Network
![image](https://user-images.githubusercontent.com/41957921/93077008-84125300-f688-11ea-8569-b4463b1952ac.png)

### 4to6GW
![image](https://user-images.githubusercontent.com/41957921/93077045-92f90580-f688-11ea-9e50-2a35cae9bebc.png)

![image](https://user-images.githubusercontent.com/41957921/93077060-9ab8aa00-f688-11ea-9501-e5bfcb46cae5.png)

![image](https://user-images.githubusercontent.com/41957921/93077067-9e4c3100-f688-11ea-9383-233d9035df9e.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** bd546540e3930ce038ab925ef8c20011a65818fd , **Branch**  development

![ff](https://user-images.githubusercontent.com/21218053/93178855-225bf280-f735-11ea-86b6-d56ab35b0f6e.png)
