### ISSUE TITLE
Four to Six gateway doesn't ask for wireguard private key

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#1146]
### Description

when the wg public key is provided it breaks the chatflow and the generated config doesn't include the private key instead a hardcoded text "enter your privatekey here"

maybe we can remove the question and always generate the key pair? or this is the intended behavior to avoid having the user enter his private key?

![image](https://user-images.githubusercontent.com/32568986/93079460-752d9f80-f68c-11ea-8928-6994acd305b7.png)

**Comment by m-motawea** [comment]
@xmonader @zaibon can you please provide your input on this. whether it should be changed or now is ok.

**Comment by zaibon** [comment]
The expected flow is the user specify the public key when creating the reservation. 
So indeed you need to generate a new key pair and send the public side in the reservation or ask it to the user.

**Comment by m-motawea** [comment]
now the step will look like this

![image](https://user-images.githubusercontent.com/32568986/93083229-942f3000-f692-11ea-8b03-1f3d55adc3df.png)

if the user chose to specify

![image](https://user-images.githubusercontent.com/32568986/93083436-e4a68d80-f692-11ea-90f1-80baa4d60ce1.png)

**Comment by zaibon** [comment]
heuuu I wouldn't ask to send the private key, this is a big werid. Private key are private and should not be shared.

**Comment by m-motawea** [comment]
we'll have it back as before. if a public key is not specified it will auto generate as before
![image](https://user-images.githubusercontent.com/32568986/93089258-5551a800-f69b-11ea-903e-54dd7158402f.png)
