### ISSUE TITLE
Inconsistent between discourse and taiga in smtp server config

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#1147]
### Version information

* OS: docker Ubuntu 20.04
* Branch: development
* commit: 5e1d62a8949b9e93b7700614a1ff58906d4eddfa
* Browser: Version 84.0.4147.125 (Official Build) (64-bit)
* explorer: testnet

### Taiga
![image](https://user-images.githubusercontent.com/41957921/93077922-db64f300-f689-11ea-8ee1-2e13c1c3e1ea.png)

### Discourse
![image](https://user-images.githubusercontent.com/41957921/93077984-f9325800-f689-11ea-9226-a02ef30e8a86.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 3fb43399683fe291a1ad56b2ec07ba5fef8e7eeb , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/93094460-3acefd00-f6a2-11ea-9479-a7ba31352cce.png)

![ff1](https://user-images.githubusercontent.com/21218053/93098286-fbef7600-f6a6-11ea-98d4-65f8b754e086.png)
