### ISSUE TITLE
check deployment on kristoftest farm

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1155]
@despiegk created a farm with 4 nodes and failing to deploy anything on them https://explorer.testnet.grid.tf

**Comment by xmonader** [comment]
on zero-os tech channel

Zaibon, [14.09.20 14:43]
This farm is not ready yet

Zaibon, [14.09.20 14:43]
None of the node in there are ready to process reservation



@zaibon can you please specify how to get these nodes ready?

**Comment by despiegk** [comment]
?

**Comment by zaibon** [comment]
> @zaibon can you please specify how to get these nodes ready?

As soon as we know I can tell yes. But at the moment we need at least on of the node to be rebooted. A direct access to the hardware could make us make faster progress too.

**Comment by zaibon** [comment]
I see 2 nodes has been rebooted:
`CS4jpDv1jZHVyvh5kjXcdVNE3zMFdUbobKT3BvEy9yyP` looks fine
`HWXeXnaa76NoTYxY75kwwnEDwe7KSuCXtich3pj37RSM` seems to still have an issue.

**Comment by rkhamis** [comment]
this is no longer relevant. wrong farm config
