### ISSUE TITLE
Failed to find Gateway

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/js-sdk#1156]
commit: 1b42f2eb488f3733520aa147c9c1778d387c0dd8
branch: development
explorer : testnet

- Listing gateways fails although there are some local pools have gateways in it as below.
- Creating a new pool resulted in adding a gateway

![image](https://user-images.githubusercontent.com/31102305/93087636-21758300-f699-11ea-9c3b-b46a3e20bfb4.png)

![image](https://user-images.githubusercontent.com/31102305/93086743-dc048600-f697-11ea-9754-17048fc799f1.png)

**Comment by m-motawea** [comment]
can't reproduce on development latest
![image](https://user-images.githubusercontent.com/32568986/93321679-bcde3380-f812-11ea-9daf-4fc3dd06fdde.png)

**Comment by waleedhammam** [comment]
can't reproduce

on a deployed 3Bot instance with no pool

![Screenshot from 2020-09-16 11-50-12](https://user-images.githubusercontent.com/10658229/93321937-0cbcfa80-f813-11ea-960b-bbe932465c49.png)

![Screenshot from 2020-09-16 11-50-06](https://user-images.githubusercontent.com/10658229/93321924-09297380-f813-11ea-96ed-d23263eb4b70.png)

after creating a very small pool

![Screenshot from 2020-09-16 11-51-47](https://user-images.githubusercontent.com/10658229/93321965-15adcc00-f813-11ea-916d-90197013a136.png)

**Comment by Pishoy** [comment]
verified 
![image](https://user-images.githubusercontent.com/21987477/93454627-87e9e380-f8db-11ea-9225-121fe214ec5d.png)

```
(js-sdk-NQNSzBV5-py3.8) root@tfwallet-prod:/opt/js-sdk# git log -1
commit 21bfa54881c733b7d7480f3c76fe9bbbed3293d2 (HEAD -> development, origin/development, origin/HEAD)
Author: Mahmoud Ayoub <36021484+dmahmouali@users.noreply.github.com>
Date:   Thu Sep 17 09:24:39 2020 +0200

    added demo label in marketplace app bar (#1200)
```
