### ISSUE TITLE
For agreement when using threebot, marketplace, threebot deployer use the full terms and conditions 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1161]
https://github.com/threefoldfoundation/legal/blob/master/src/terms_conditions_all.md

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** bd546540e3930ce038ab925ef8c20011a65818fd , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/93185004-3146a300-f73d-11ea-96dc-27dc2707ec64.png)

![ff](https://user-images.githubusercontent.com/21218053/93185102-51766200-f73d-11ea-8c2a-3964ba5869c3.png)
