### ISSUE TITLE
failed to add node to a network

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1164]
when trying to deploy peertube
```
Failed to add node A7FmQZ72h7FzjkJMGXmzLDFyfyxzitDZYuernGG97nv7 to network 481084. The resources you paid for will be re-used in your upcoming deployments.. Please use the refresh button on the upper right to restart the chatflow
```

**Comment by BolaNasr** [comment]
I can't reproduce it , it works fine.

https://explorer.testnet.grid.tf/api/v1/reservations/workloads/482332
![photo_2020-09-16_11-46-51](https://user-images.githubusercontent.com/10259267/93321356-5e18ba00-f812-11ea-9faf-e614bccfe83a.jpg)

**Comment by RafyAmgadBenjamin** [comment]
I can't reproduce it.


![image](https://user-images.githubusercontent.com/46320202/93323051-61ad4080-f814-11ea-88c5-1c013a6a5802.png)
![image](https://user-images.githubusercontent.com/46320202/93323137-81dcff80-f814-11ea-9b1a-0f9e4990eab8.png)
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/482346

**Comment by AhmedHanafy725** [comment]
**branch:** development
**commit:** 2f95e212f72faee2b95b7e15b2fce0ef56db1534
Can't reproduce too 

![image](https://user-images.githubusercontent.com/41957921/93496382-6b679e80-f90f-11ea-82b4-9951af28d4d3.png)
