### ISSUE TITLE
Error creating testnet funded wallet

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#1165]
Jsng and js-sdk on latest development:

![Screenshot from 2020-09-15 09-34-40](https://user-images.githubusercontent.com/17138347/93180007-069d2000-f726-11ea-927b-7aba4516f4ff.png)

**Comment by DylanVerstraete** [comment]
After clicking submit again:

![Screenshot from 2020-09-15 09-36-08](https://user-images.githubusercontent.com/17138347/93180078-246a8500-f726-11ea-9f89-48b6fae34965.png)

**Comment by DylanVerstraete** [comment]
I had to close this popup and switch to another page and come back to see my wallet. But no Testnet TFT was added unfortunatly.

![Screenshot from 2020-09-15 09-37-07](https://user-images.githubusercontent.com/17138347/93180151-449a4400-f726-11ea-987d-88deb265adeb.png)

**Comment by rkhamis** [comment]
we can harden indeed by always first checking the stellar and token services before continuing

this should be done on all chatflows and levels

**Comment by Pishoy** [comment]
verified
![image](https://user-images.githubusercontent.com/21987477/93457976-fd57b300-f8df-11ea-9579-63a09119e2e2.png)

```
(js-sdk-NQNSzBV5-py3.8) root@tfwallet-prod:/opt/js-sdk# git log -1
commit 21bfa54881c733b7d7480f3c76fe9bbbed3293d2 (HEAD -> development, origin/development, origin/HEAD)
Author: Mahmoud Ayoub <36021484+dmahmouali@users.noreply.github.com>
Date:   Thu Sep 17 09:24:39 2020 +0200

    added demo label in marketplace app bar (#1200)
```
