### ISSUE TITLE
Failed to create a pool

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#1166]
Jsng and js-sdk on latest development.

Tried to create a pool with 1 CU and 1 SU for 1 day. It fails on the selected currency but I did not select a currency?
![Screenshot from 2020-09-15 09-41-51](https://user-images.githubusercontent.com/17138347/93180633-ff2a4680-f726-11ea-8ba9-2619ba6aa54f.png)

**Comment by ashraffouda** [comment]
can not reproduce

**Comment by DylanVerstraete** [comment]
@ashraffouda are you trying this on a hosted 3bot or local?

**Comment by ashraffouda** [comment]
on local with latest code

**Comment by Dina-Abd-Elrahman** [comment]
- I tested it on hosted 3bot instance and local instance and both are working fine with me.
