### ISSUE TITLE
Payment for 3bot deployer

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#1167]
In case of failure developments for 3bot, and the user decides to remove the deployment as it is not working, he will lose his money.
 
### Option A
- any pool will be created for 3bot should be named `<3bot name>-<instance name>`
- in case of failure, it should search for pools that starts his `3bot name`, then get the deployed instance for this pool
- if the instance is exist, then keep it and create a new pool for the new development. If it is not exist, then take this pool and extend it to complete the expiration time, then rename the pool to the new instance.

**Problem:** in case of creating a new instance with less expiration time than that in the pool, we can't stop the deployment in time and the user will lose some money. 

### Option B
- we have a funded wallet
- when the user wants to create an instance, we can create a pool for this instance from this wallet for an hour 
- then he can extend it later 

**Problem:** users can abuse this , also complex for users 

### Option C
- we have a funded wallet 
- when the user wants to create an instance, we can transfer his tokens to this wallet, then creates a pool and an instance from this wallet 
- can be refunded in case of failure from this wallet 

**Problem:** we will lose some tokens for every failure, too many transactions

### Enhancement can be done for A, C options
- use scheduler to handle the expiration.
- it will introduce more complexity in the design.

## TL, DR
- we have a funded wallet with 3bot deployer
- when the user wants to create an instance, we can create a pool for this instance from this wallet for 15 mins from this wallet.
- then in success case, it will be asked for extending in the same chatflow. And in case of failure, he will be refunded from the explorer for the failure from extending the pool.
- also in case of later failure, 3bot can be removed and reuse its pool.

**Comment by waleedhammam** [comment]
will be implemented according this adr: https://github.com/threefoldtech/js-sdk/blob/development/docs/architecture/decisions/0007-payment-for-3bot-deployer.md

**Comment by waleedhammam** [comment]
- initializing

![image](https://user-images.githubusercontent.com/10658229/93319930-c6ff3280-f810-11ea-9c22-74f9a0399e9b.png)

- payment & finishing

![image](https://user-images.githubusercontent.com/10658229/93320019-dbdbc600-f810-11ea-8444-0db89f29769f.png)

- final expiration

![image](https://user-images.githubusercontent.com/10658229/93320041-e302d400-f810-11ea-85e0-82c088eb8460.png)

**Comment by AhmedHanafy725** [comment]
**Verified**

commit: 1418d60220a01fdb7045d51f30f0ed385d1c17f2
branch: development


+ Still in deploying steps, and deployed for 15 mins.

![image](https://user-images.githubusercontent.com/41957921/93468758-c093b800-f8ef-11ea-8668-b77f5099f8c4.png)

+ Extending in the same deploying steps.

![image](https://user-images.githubusercontent.com/41957921/93468977-1bc5aa80-f8f0-11ea-949d-792769628abb.png)

+ After extending and payment.

![image](https://user-images.githubusercontent.com/41957921/93469230-82e35f00-f8f0-11ea-8087-e4920df4ea62.png)

![image](https://user-images.githubusercontent.com/41957921/93469190-6f37f880-f8f0-11ea-8d87-c4526ebd6891.png)
