### ISSUE TITLE
fail in chatflow redirect to the first page in Alert 

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/js-sdk#1168]
branch: development

![image](https://user-images.githubusercontent.com/31102305/93198850-dcf7ef00-f74d-11ea-977e-5b6463786f1f.png)
![image](https://user-images.githubusercontent.com/31102305/93198897-e7b28400-f74d-11ea-8f59-6ff343bb73e3.png)

**Comment by AhmedHanafy725** [comment]
Verified
commit: 940d873ea361eec1331b43d64dbeee260292e14a
branch: development

![image](https://user-images.githubusercontent.com/41957921/93364781-427cd600-f849-11ea-9111-ce3c66f6a357.png)

After the redirect 

![image](https://user-images.githubusercontent.com/41957921/93364800-47da2080-f849-11ea-8927-f2966ade055e.png)
