### ISSUE TITLE
Use zinit in 3Bot deployer package

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#1174]
### Description

- Use zinit in 3Bot deployer package
- Make use of it into streaming logs

**Comment by waleedhammam** [comment]
![Screenshot from 2020-09-15 15-29-42](https://user-images.githubusercontent.com/10658229/93227194-67ebe000-f774-11ea-8a6b-b64e031f313b.png)

**Comment by waleedhammam** [comment]
https://deploy3bot2.testnet.grid.tf/ is now updated too
machine redis-logs: redis-cli -h 165.22.17.128 -p 6378

**Comment by AhmedHanafy725** [comment]
Verified 
on https://deploy3bot2.testnet.grid.tf/

+ zinit
![image](https://user-images.githubusercontent.com/41957921/93354951-d8126880-f83d-11ea-8050-83bc2a373c79.png)


+ Redis logs 
![image](https://user-images.githubusercontent.com/41957921/93354697-941f6380-f83d-11ea-9dfd-088e1f12415b.png)
