### ISSUE TITLE
disclaimer banner on marketplace.threefold.me/demo/...

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/js-sdk#1177]
### Description

add a banner (always showing) on our demo site that clearly states

"This is for demo purposes to showcase grid usage. We're running on testnet which means it's always on latest testing code. Forgive any instability you might encounter while our developers work out the kinks"

or shorter version: "this is for demo purposes and running on testnet, which might cause some instability while our engineers test their latest code"

**Comment by Pishoy** [comment]
verified 
![image](https://user-images.githubusercontent.com/21987477/93454093-c6cb6980-f8da-11ea-9e74-1f30fbc35b8b.png)
```
(js-sdk-NQNSzBV5-py3.8) root@tfwallet-prod:/opt/js-sdk# git log -1
commit 21bfa54881c733b7d7480f3c76fe9bbbed3293d2 (HEAD -> development, origin/development, origin/HEAD)
Author: Mahmoud Ayoub <36021484+dmahmouali@users.noreply.github.com>
Date:   Thu Sep 17 09:24:39 2020 +0200

    added demo label in marketplace app bar (#1200)
```
