### ISSUE TITLE
update base url for apps howto link to the info-now wiki

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1184]
https://info-now.threefold.io/ instead of manual-testnet.threefold.io for the commercial content

**Comment by xmonader** [comment]
done in 4d82fd256d1fb5bc6dcc47d2d44e8388f2c1a0b6

**Comment by AhmedHanafy725** [comment]
**Verified**
**commit:** 2f95e212f72faee2b95b7e15b2fce0ef56db1534
**branch:** development
Marketplace is redirecting to https://now.threefold.io/ , and links will be checked in this issue #1203
