### ISSUE TITLE
deploy the marketplace on marketplace.threefold.me/io

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1185]

**Comment by m-motawea** [comment]
marketplace is now on (formerly demo.testnet.grid.tf)
https://marketplace.threefold.me/

**Comment by mhost39** [comment]
Verified 

![image](https://user-images.githubusercontent.com/31102305/93333741-100cb200-f824-11ea-877e-14dc69354370.png)
![image](https://user-images.githubusercontent.com/31102305/93333766-1a2eb080-f824-11ea-8539-80d3d2a932be.png)
