### ISSUE TITLE
demo: deploying peertube issue

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/js-sdk#1195]
I was trying to deploy a demo peertube solution as follows:
- I visited https://demo2.testnet.grid.tf/
- I logged in
- Clicked on the peertube `NEW`
- After choosing the solution size, it start deploying my workload (showing the reservation id)
- Suddenly it jumped to the Solution list view 

![image](https://user-images.githubusercontent.com/10920323/93337511-85c74c80-f829-11ea-9c6c-bb613e41a33c.png)

With no solutions listed. 

Then I had to press New again (in that view) for my demo solution to be created.

**Comment by rkhamis** [comment]
already fixed. putting in verification

**Comment by OmarElawady** [comment]
Tried now, got an error and it didn't redirect to the listing page. Can you please recheck if the issue still exists?
![Screenshot from 2020-09-16 16-27-52](https://user-images.githubusercontent.com/13040543/93351398-fbd3af80-f839-11ea-94e4-b9ec18cf88fb.png)

**Comment by muhamadazmy** [comment]
It has been on this screen for a really long time

![image](https://user-images.githubusercontent.com/10920323/93357747-f332a780-f840-11ea-9d52-01088bcadc4a.png)

If i check (in another tab) the solution is listed, and i can see the reservations IDs. I checked all the reservation and they all seem successful but i can't access the solution.

**Comment by Pishoy** [comment]
verified as per https://github.com/threefoldtech/js-sdk/issues/1195

![image](https://user-images.githubusercontent.com/21987477/93448547-05a9f100-f8d4-11ea-8f17-02c5b91938c1.png)
