### ISSUE TITLE
Wrong calculation for the expiration date in 3bot deployer 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#1198]
On https://deploy3bot2.testnet.grid.tf/

### Steps
1- Deploy 3bot and give it a time for expiration.
![image](https://user-images.githubusercontent.com/41957921/93359812-4f96c680-f843-11ea-8263-a01fae87faf8.png)

2- After deploying it, I found another expiration date
![image](https://user-images.githubusercontent.com/41957921/93361180-dd26e600-f844-11ea-98b0-fd1cb5a9d3f8.png)

3- Extend your 3bot 
![image](https://user-images.githubusercontent.com/41957921/93361255-f4fe6a00-f844-11ea-87f1-446e4108164b.png)

4- Check it after the extension 
![image](https://user-images.githubusercontent.com/41957921/93361349-0fd0de80-f845-11ea-90c9-917b5644697e.png)

### Result
1- For the time in the deploying was 12:01 AM ---> after deploying is 5:45 AM
2- For the extension was 9:00 AM ---> after the extension 9:38 PM

**Comment by xmonader** [comment]
huh? you should be prompted immediately to extend the 3bot in the chatflow @waleedhammam please check

**Comment by waleedhammam** [comment]
> huh? you should be prompted immediately to extend the 3bot in the chatflow @waleedhammam please check

you are prompted immediately to extend the 3bot in the chatflow. the thing is when using a reused pool, somthing fishy happens

**Comment by waleedhammam** [comment]
15 mins at the begining
![Screenshot from 2020-09-17 13-26-01](https://user-images.githubusercontent.com/10658229/93472233-af00df00-f8f4-11ea-889a-1a9ea335ddd3.png)

extend
![Screenshot from 2020-09-17 13-27-19](https://user-images.githubusercontent.com/10658229/93472242-b32cfc80-f8f4-11ea-8fab-4517f343b86b.png)

new extension
![Screenshot from 2020-09-17 13-32-59](https://user-images.githubusercontent.com/10658229/93472252-b58f5680-f8f4-11ea-91cf-2e7ac2f580f6.png)

**Comment by mhost39** [comment]
Verified
commit: f6f8aa3943c98b5b4aaaec9d30e2f71668c381cd
branch: development 

![image](https://user-images.githubusercontent.com/31102305/93707902-9aaa2580-fb32-11ea-9689-acf75978160c.png)
![image](https://user-images.githubusercontent.com/31102305/93708065-9599a600-fb33-11ea-8735-f934e640953a.png)
