### ISSUE TITLE
Packages URLs issues

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/js-sdk#12]
- [x] have to use `/` after `/admin` to work

- [x] have to remove `/` from the end of `tfgrid_solutions/chats/<chat>/` to work

**Comment by abom** [comment]
https://github.com/threefoldtech/js-sdk/pull/6/commits/2ba9eedcb6097d7a2894ef976bfef6cfe96b3183

**Comment by dmahmouali** [comment]
verifying
