### ISSUE TITLE
solutions and apps info links are broken

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#1203]
**Branch:** development
**commit:** 1418d60220a01fdb7045d51f30f0ed385d1c17f2

- All solutions in admin dashboard should redirect to https://manual.threefold.io with the endpoint of the solution name
- All apps in marketplace should redirect to https://now.threefold.io with the endpoint of app name

![image](https://user-images.githubusercontent.com/41957921/93471031-161d9400-f8f3-11ea-8e3e-ed480a5018c6.png)

![image](https://user-images.githubusercontent.com/41957921/93471584-d5724a80-f8f3-11ea-8909-14f0b4aa3ea2.png)

**Comment by xmonader** [comment]
- links are now using manual.threefold.io (because that's how it's going to be on monday) if link doesn't work check if replacing manual with manual2 in the url fixes it
- apps should be linking to now repo (if broken links they will be fixed in the now repo)

**Comment by waleedhammam** [comment]
verified
