### ISSUE TITLE
Deleting deployed 3bot with backup doesn't delete the created 3bot name from explorer

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/js-sdk#1204]
### Description

for the 3bot backup flow, When deleting a deployed 3bot with its backup, and then trying to create a new one with the same name the check only checks if the name exists in the explorer and so says that it exists go try to recover even though the backup is deleted. 
When following the recover path with using the same name, a new 3bot is created with no reference to any previous backup which means the backup was deleted successfully and the issue is just in the check for the existence of the specific 3bot name

https://github.com/threefoldtech/js-sdk/blob/4b5a2aea883517b620936088c689076118c48db3/jumpscale/packages/threebot_deployer/chats/threebot.py#L87-L93

### Version information

* OS: e.g. Ubuntu 19.04
* project commit/version: e.g. js-ng 11.0.0a1
* Browser: e.g. chrome 79
*

### Steps to reproduce
- deploy 3bot on https://deploy3bot2.testnet.grid.tf/ with nameX
- delete the deployed nameX 3bot with its backup
- try to deploy a new 3bot by creating a new one not recovery with nameX

**Comment by waleedhammam** [comment]
Recover includes two things (Backups and identity), We can delete backups but
- We cannot delete users from explorer, and we use the secret to generate the identity mnemonics.
- If the user wants to create the the solution with the same name he has to remember the secret (which means recover)

So if the user forgot his secret then the identity for this solution with this name is lost.
