### ISSUE TITLE
Limit testnet deployments to 2 days.

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#1210]
@despiegk  requested the max expirary date for deployments on testnet would be 2 days. To make sure ppl don't reserve for weeks / months so other ppl can deploy stuff as well.

**Comment by xmonader** [comment]
demos are limited for 3 hours, do you mean for 3bot expiration?

**Comment by DylanVerstraete** [comment]
The demos are limited yes, but he spoke about other stuff that you reserve with the 3Bot admin panel. For exampe an ubuntu

**Comment by xmonader** [comment]
there's no expiration for solution or Apps, we invented that for Apps as we create a pool for each and tied the expected expiration  to the CUs and SUs in the pool we create per app. (and the estimate isn't guaranteed if there is no actual consumption of the pool resources via the workloads. That being said, we can't fix the deployment of e.g ubuntu, k8s, minio to 2 days, as the pool resources used by each of them are different without having an upper limit for pool creation/extension, which will definitely affect too many parts of the code
