### ISSUE TITLE
improve error message for identifiers names

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1211]
for the check of isIdentifier (make sure to state it needs a valid identifier, starting with a lowercase alphabet letter)

**Comment by xmonader** [comment]
done in f6f8aa3943c98b5b4aaaec9d30e2f71668c381cd

**Comment by mhost39** [comment]
Verified 
branch: development 
commit: f6f8aa3943c98b5b4aaaec9d30e2f71668c381cd
![image](https://user-images.githubusercontent.com/31102305/93709233-fb3e6000-fb3c-11ea-9e6e-f6966238bd9f.png)
