### ISSUE TITLE
Solution Name Accept Special Char

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/js-sdk#1212]
branch: development 
commit: f6f8aa3943c98b5b4aaaec9d30e2f71668c381cd

solution name accept special char like : $test, $$$$

![image](https://user-images.githubusercontent.com/31102305/93708686-78b3a180-fb38-11ea-982b-bbf284f7d82e.png)
![image](https://user-images.githubusercontent.com/31102305/93708761-1d35e380-fb39-11ea-84d7-efcadf5f2990.png)

**Comment by Pishoy** [comment]
verified 
![image](https://user-images.githubusercontent.com/21987477/93743358-38aff580-fbf0-11ea-9f93-58133518527b.png)
