### ISSUE TITLE
3bot deployer to deploy with 30 mins

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/js-sdk#1213]
in 3bot deployer, instead of deploying with 15 mins and asking the user to extend, make it 30 mins

**Comment by mhost39** [comment]
Verified 
commit: 46522ab3455067d1d896598f2bf00134422e58f8
branch: development 

![image](https://user-images.githubusercontent.com/31102305/93710340-24afb980-fb46-11ea-878e-f5961fb27145.png)
