### ISSUE TITLE
title in documentation is js-ng not js-sdk

### ISSUE THREAD

**Issue by MElborolossy** [threefoldtech/js-sdk#1219]
### Description
In the documentation, the title is js-ng not js-sdk

### Steps to reproduce
- Open [Wiki](https://threefoldtech.github.io/js-sdk/wiki/#/)
- title (header) is js-ng
![js-sdk_Wiki_issue](https://user-images.githubusercontent.com/11272864/93716805-fe077800-fb71-11ea-9b53-5addd3b42ae3.png)

**Comment by xmonader** [comment]
fixed in https://github.com/threefoldtech/js-sdk/commit/522c799dc9c741c62667ae0db957cfde3417b2e7

**Comment by Pishoy** [comment]
verified 
![image](https://user-images.githubusercontent.com/21987477/93742462-727ffc80-fbee-11ea-895f-b77fb05055b4.png)
