### ISSUE TITLE
Create tests for the automated chatflows

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#1226]
- Tests should cover all solutions.
  - marketplace
    - [x] wiki
    - [x] website
    - [x] blog
    - [x] mattermost
    - [x] discourse
    - [x] taiga
    - [x] peertube
    - [x] gitea
    - [x] cryptpad
  - solutions
    - [x] network
    - [x] pools
    - [x] ubuntu
    - [x] kubernetes
    - [x] minio
    - [x] expose solutions
    - [x] generic flist
    - [x] monitoring 
   ~- [ ] domain delegation~
  - 3bot deployer
    - [x] create
    - [x] extend
    - [x] recover
- [x] Tests should be run nightly on github actions.
- [x] All tests should take `integration` marker.

**Comment by mhost39** [comment]
i can't create ns record in the test
![image](https://user-images.githubusercontent.com/31102305/94363292-7bc30a80-00c1-11eb-8881-81d496ac4fb5.png)

**Comment by mhost39** [comment]
extend threebot work fine in frontend but get this error when try by script 
![image](https://user-images.githubusercontent.com/31102305/94461492-7eedf180-01ba-11eb-97e9-44c88cbba5ed.png)
