### ISSUE TITLE
allow backup for ~/sandbox/var/downloaded_packages and user developement space a for hosted 3bot

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1228]
in case the owner of that 3Bot was doing some coding or edited a package in ~/sandbox/var/downloaded_packages

**Comment by waleedhammam** [comment]
Directory `playground` under `~/sandbox/` for user to develop/script in

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 01ac08bc8051698b0478d22baa876fd2d4a4bef9, **Branch** development

Verified, Tested threebot backup and restore.
