### ISSUE TITLE
restore ssh access in 3bots

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1238]
restore ssh access in 3bots

**Comment by AhmedHanafy725** [comment]
**Verified**
**Branch:** development
**Commit:** 75ab1bc3e5adb7b021d90d9705f4a072450c4643

After deploying threebot 
![image](https://user-images.githubusercontent.com/41957921/94364432-6eaa1980-00c9-11eb-86ea-65faf369547d.png)

![image](https://user-images.githubusercontent.com/41957921/94364443-8386ad00-00c9-11eb-9a0f-f3d9665d540a.png)
