### ISSUE TITLE
when deploying 3bot networking issues happening

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1239]
```
3) "fatal: unable to access 'https://github.com/threefoldtech/js-sdk.git/': Could not resolve host: github.com\n"
1) "message"
2) "my2-stderr"
3) "error: Could not fetch origin\n"
1) "message"
2) "my2-stdout"
3) "HEAD is now at 90446f0 Merge pull request #1142 from threefoldtech/development_fix_workloads_ui_epoch\n"
1) "message"
2) "my2-stdout"
2) "my2-stdout"
3) "[ConnectionError]\n"
1) "message"
2) "my2-stdout"
3) "HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/protobuf/json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb1e8647d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n"
1) "message"
2) "my2-stdout"

```

and more errors like 
```
3) "    self, \"Failed to establish a new connection: %s\" % e\n"
1) "message"
2) "my2-stderr"
3) "    \xe2\x94\x94 <urllib3.connection.HTTPSConnection object at 0x7f822f5eaa90>\n"
1) "message"
2) "my2-stderr"
3) "\n"
1) "message"
2) "my2-stderr"
3) "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f822f5eaa90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\n"
1) "message"

3) "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='explorer.grid.tf', port=443): Max retries exceeded with url: /explorer/users?name=ahmedthabet_my2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f822f5eaa90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n"

```

workloads ids 485755, 485757, 485756, 485758 
ip4: 10.100.7.4
ip6: fd48:4673:6750:7::4
node: 72CP8QPhMSpF7MbSvNR1TYZFbTnbRiuyvq5xwcoRNAib
farm: freefarm
pool id: 2956

**Comment by xmonader** [comment]
and on another node 

```
2) "my3-stdout"
3) "Fetching origin\n"
1) "message"
2) "my3-stdout"
3) "HEAD is now at 90446f0 Merge pull request #1142 from threefoldtech/development_fix_workloads_ui_epoch\n"
1) "message"
2) "my3-stdout"
3) "Skipping virtualenv creation, as specified in config file.\n"
1) "message"
2) "my3-stdout"
3) "Updating dependencies\n"
1) "message"
2) "my3-stdout"
3) "Resolving dependencies...\n"
1) "message"
2) "my3-stdout"
3) "\n"
1) "message"
2) "my3-stdout"
3) "[ConnectionError]\n"
1) "message"
2) "my3-stdout"
3) "HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/protobuf/json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7fa18bed50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n"
1) "message"

3) "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='explorer.grid.tf', port=443): Max retries exceeded with url: /explorer/users?name=ahmedthabet_my3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fadf4c1c9d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n"

```

wids: 485759, 485761, 485760, 485762
ip4: 10.100.0.4
ip6: fd48:4673:6750::4
node: A7FmQZ72h7FzjkJMGXmzLDFyfyxzitDZYuernGG97nv7
farm: freefarm
pool id: 2957

**Comment by zaibon** [comment]
I've inspected the container create by [485756](https://explorer.testnet.grid.tf/api/v1/reservations/workloads/485756). It turns out that the network resource for this container does not exist anymore on this node. So it seems that the for some reason the network resource used by the container has been remove/decomission from the node.

Do you have any flow where you delete network resources ? A user should always be very careful when deleting a network that there are no more container using it, cause that can lead to situation like these where the container lives, but without network.

**Comment by xmonader** [comment]
For marketplace and for threebot deployer (we create a network per app to connect the user solutions on).
We don't really delete anything we leave the cleaning for the explorer when pools expire, but probably 0 resources workloads shouldn't be removed like networks). 

What we can do is
- Create empty pools and have the networks there (but then it doesn't make sense for expired pools to cancel 0 resources workloads and empty pools that allows having 0 resources workloads) -the most realistic option for me-
- Extend the network pool before it expires
- create a new network resource per app and for each threebot, won't be per user, but per app -but if so we will be consuming subnets-


cc @m-motawea @waleedhammam
