### ISSUE TITLE
Format Expiration date in marketplace app info view

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/js-sdk#1242]
- In marketplace package, the expiration date in details view need formatting
![image_2020-09-21_15-10-36](https://user-images.githubusercontent.com/36021484/93864373-176d0900-fcc5-11ea-9702-4118766e220e.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 092358e26dfb12dbe8395fd7da00a93cb90a8ec5 , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/98678248-f04ac380-2366-11eb-82cb-b9d4a05006a2.png)
