### ISSUE TITLE
Add button to generate mnemonics in Add Identity view

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1243]
When creating a new identity -not necessarily one from 3Bot connect words- , I'd like to click a button to valid mnemonics in the add identity form. 
- should validate if the user exist already

**Comment by mhost39** [comment]
branch: development
commit: 01779a3a1f2de1ca409eb6044c5963a2ddcda7b4
![image](https://user-images.githubusercontent.com/31102305/97463453-6e12d600-1948-11eb-8b50-1e5bce164fde.png)
