### ISSUE TITLE
adding a courrpted package  (non exists)  will courrpt the  threebot server

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/js-sdk#1246]
- in threebot server when I added non exist package EX: `blabla` it prints an error for you that there is package.toml file for this package and cannot add it, But if you try to list a packages with them using this command `j.servers.threebot.default.packages.list_all()` you will find all wrong packages you add.

![ff1](https://user-images.githubusercontent.com/21218053/93869465-1db2b380-fccc-11ea-80f6-ff49c035d087.png)

and if you stop the threebot server and try to start it again you got this error

![ff](https://user-images.githubusercontent.com/21218053/93869301-e93ef780-fccb-11ea-85bb-a25d217e4633.png)

**Commit_ID** a3239ed343ad62283f049ce65f2ca564684cc8f4 , **Branch** development

**Comment by RafyAmgadBenjamin** [comment]
### fixed on branch 
`development_add_package_issue`
### commit id 
90c100d9d26cb3f18ee2993453bc4ff0131248a9

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 69ef97d8e49fb62fb6b7b41bbcbc86cc32faff0f , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/93988077-9a0acc80-fd88-11ea-9e5f-1d7a9c00961c.png)
