### ISSUE TITLE
no gateways available in your pools. Please use the refresh button on the upper right to restart the chatflow

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1254]
in  marketplace i got: no gateways available in your pools. Please use the refresh button on the upper right to restart the chatflow

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** a1b57396c977ac25d566d340405a9f9a177ddeb8 , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/96365697-ca087e00-1142-11eb-9aba-144650d30311.png)
