### ISSUE TITLE
the node was down and selected 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#1256]
I was trying to deploy ubuntu 
![image](https://user-images.githubusercontent.com/46320202/93986361-8c544780-fd86-11ea-9b78-767573202ab7.png)

**Comment by OmarElawady** [comment]
Happened again while exposing a solution:
`Workload 490346 failed to deploy because the node is down 3dAnxcykEDgKVQdTRKmktggL2MZbm3CPSdS9Tdoy4HAF. Please use the refresh button on the upper right to restart the chatflow`
