### ISSUE TITLE
Test coverage for js-sdk 11.1alpha

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#1265]
- Create automation test for all the following modules.
- Some of them has tests already, please check the coverage, and complete it if needed.
### clients
  - [x] digitalocean
  - [x] github 
  - [x] sendgrid 

### core 
  - [x] identity (high priority)

### sals
  - [x] nginx (high priority)

### servers
  - [x] threebot (high priority)

### tools
  - [x] nginx (high priority)
  - [x] redis (high priority)
  - [x] restic (high prio)

**Comment by BolaNasr** [comment]
### redis tool : https://github.com/threefoldtech/js-sdk/issues/1266

**Comment by Dina-Abd-Elrahman** [comment]
### threebot server: https://github.com/threefoldtech/js-sdk/issues/1267

**Comment by BolaNasr** [comment]
NGINX server tool : https://github.com/threefoldtech/js-sdk/issues/1276

**Comment by OmarElawady** [comment]
restic: #1282

**Comment by RafyAmgadBenjamin** [comment]
working on Digital Ocean

**Comment by Dina-Abd-Elrahman** [comment]
### identity https://github.com/threefoldtech/js-sdk/issues/1305

**Comment by Dina-Abd-Elrahman** [comment]
### explorer https://github.com/threefoldtech/js-sdk/issues/1308

**Comment by RafyAmgadBenjamin** [comment]
### Reservation chatflow https://github.com/threefoldtech/js-sdk/issues/1309

**Comment by mhost39** [comment]
### Github https://github.com/threefoldtech/js-sdk/issues/1314

**Comment by BolaNasr** [comment]
## Identity https://github.com/threefoldtech/js-sdk/issues/1305

**Comment by RafyAmgadBenjamin** [comment]
### sendgird

**Comment by OmarElawady** [comment]
nginx sal #1363

**Comment by xmonader** [comment]
I'm good with the issue as is, let's do the explorer in a later phase

**Comment by AhmedHanafy725** [comment]
explorer will be addressed in https://github.com/threefoldtech/js-sdk/issues/1480
