### ISSUE TITLE
stellar client get_balance doesn't work with address in jsng

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#127]
Getting the balance for a different address only brings the balance of current wallet.

Note: works in jsx

![Screenshot from 2020-06-29 10-30-29](https://user-images.githubusercontent.com/10658229/85991375-9ff44a00-b9f3-11ea-817e-a4a317239bd1.png)

**Comment by hossnys** [comment]
verified
![Screenshot from 2020-07-01 12-15-59](https://user-images.githubusercontent.com/26298009/86232651-8fc7a080-bb94-11ea-96d6-4f2417bdd9a5.png)
