### ISSUE TITLE
failed to deploy volume on node

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1273]
Failed to deploy volume on node A7FmQZ72h7FzjkJMGXmzLDFyfyxzitDZYuernGG97nv7 487198. The resources you paid for will be re-used in your upcoming deployments

**Comment by waleedhammam** [comment]
This node has a lot of trouble, it will be blocked after this check and pool will be reused

**Comment by waleedhammam** [comment]
also here

this node: 4TksThCbMYo8THcsADEckaCwurHSbn6EvDapfXvga97r
message": "Not enough space left in pools of this type ssd",
https://explorer.grid.tf/api/v1/reservations/workloads/14003

**Comment by m-motawea** [comment]
this is tracked in https://github.com/threefoldtech/zos/issues/910
