### ISSUE TITLE
NGINX test coverage 

### ISSUE THREAD

**Issue by BolaNasr** [threefoldtech/js-sdk#1276]

**Comment by BolaNasr** [comment]
## PR: https://github.com/threefoldtech/js-sdk/pull/1289

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** a1b57396c977ac25d566d340405a9f9a177ddeb8, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/96368100-3179fa00-1152-11eb-8af9-feaa7850132c.png)
