### ISSUE TITLE
generating certificate fails after last update

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#128]
tested on machine: 192.241.158.21

current setup:
on the machine you will find the container named `3bot-ng`
`docker exec -it 3bot-ng bash`
inside the container
jsng and start the server

![Screenshot from 2020-06-29 10-52-12](https://user-images.githubusercontent.com/10658229/85993464-b059f400-b9f6-11ea-9970-b85b73db0d6b.png)

**Comment by waleedhammam** [comment]
https://github.com/threefoldtech/js-sdk/blob/3b7b875373ca1d60e2f156797e5899f8a7696b11/jumpscale/sals/nginx/templates/website.conf#L3

certbot throws this error as it doesn't find `ssl` and creates its own so it will duplicate the location, nginx will skip this config, the well-known challenge will fail

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
