### ISSUE TITLE
option to enable explorer logs in developer options

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1281]
option to enable explorer logs in developer options, and the hook should be configurable using `ENABLE_EXPLORER_LOGS` flag with default value of false

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** a1b57396c977ac25d566d340405a9f9a177ddeb8, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/96372510-78261f00-1167-11eb-8019-7eac7eb21a17.png)
