### ISSUE TITLE
Test coverage for restic tools

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/js-sdk#1282]
Add tests for `j.tools.restic`.

**Comment by OmarElawady** [comment]
In the 0.9 release of restic the restore command restores the files using their absolute path. Before this release, they used relative pathes. On ubuntu:20.04, 0.9 release is installed. On ubuntu:18.04, 0.8.3 is installed, so the tests fails on the github actions. It can be fixed if we set the ubuntu version in the github action to 20.04.

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** a1b57396c977ac25d566d340405a9f9a177ddeb8 , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/96369630-79e9e580-115b-11eb-8bdd-f841c47d3078.png)
