### ISSUE TITLE
Allow use to get wireguard config for their network in 3bot deployer

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1290]
Allow use to get wireguard config for their network in 3bot deployer

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** a1b57396c977ac25d566d340405a9f9a177ddeb8, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/96372123-c0444200-1165-11eb-99b0-97d43ef2ad7c.png)

![ff](https://user-images.githubusercontent.com/21218053/96372303-8f184180-1166-11eb-99e7-97fce2d97775.png)
