### ISSUE TITLE
Provide an easy way to more categories / apps in the marketplace

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1292]
with having more apps coming we need to be able to categorize them we can maybe do tags on them too?

```
categories = {
{ category_name: ... 
  apps_list:...,
},


}

```

- allow option to deactivate  solution so it looks disabled in the ui (will be used to show the upcoming solutions that we didn't implement yet)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 95bdc98e5e111086860aeb4af8031a2953f08541, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/96447436-31d9ca00-1212-11eb-9927-5f111ceee0d4.png)
