### ISSUE TITLE
Allow predefined public keys to be used  in admin dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1294]
In the 3bot we should have a view where we can add public keys to be used where public keys are required

**Comment by mhost39** [comment]
branch: development
commit: b61246caa8b623bd3db2ce8ebe57d6bf27866300
![image](https://user-images.githubusercontent.com/31102305/97472056-137e7780-1952-11eb-892f-7aacb64af820.png)
![image](https://user-images.githubusercontent.com/31102305/97472260-50e30500-1952-11eb-8af0-518718a036b5.png)
