### ISSUE TITLE
Bring back authentication using 3bot connect with oauth_proxy

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#13]
goal: create oauth using https://github.com/threefoldtech/oauth-proxy and secure nginx locations for mainly admin package and chatflows

**Comment by waleedhammam** [comment]
current progress: played around the package and deployed a simple server example


![Uploading Screenshot from 2020-06-15 19-39-55.png…]()


TODO: find best solution to integrate it with packages eco-system in jsng

**Comment by waleedhammam** [comment]
auth is back, to do decent template from redirection

![Screenshot from 2020-06-16 17-04-01](https://user-images.githubusercontent.com/10658229/84791892-87e3fa00-aff3-11ea-8330-c68480362fe0.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
