### ISSUE TITLE
Could not deploy a Pool with latest code

### ISSUE THREAD

**Issue by maxux** [threefoldtech/js-sdk#1302]
Using latest code, I could not deploy a Pool anymore:
![image](https://user-images.githubusercontent.com/4141584/94477024-94224a80-01d1-11eb-9c96-0ffd1c8d52ce.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** a1b57396c977ac25d566d340405a9f9a177ddeb8, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/96368406-05f80f00-1154-11eb-8dba-4fb267630133.png)
