### ISSUE TITLE
identity test coverage 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/js-sdk#1305]

**Comment by BolaNasr** [comment]
PR : https://github.com/threefoldtech/js-sdk/pull/1315

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID**  a1b57396c977ac25d566d340405a9f9a177ddeb8, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/96366025-3edcb780-1145-11eb-945e-0d86679b880c.png)
