### ISSUE TITLE
Clean Up Gateway Workloads for Expired Pool

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#1307]
# Description

when this issue is fixed https://github.com/threefoldtech/tfexplorer/issues/172, free workloads will not be cleaned anymore so we need to clean at least subdomains ourselves (ideally reverse proxies as well) in both apps and solution expose when the trc container expires

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 40b40ba2abc7dfbd4e82fdfd9e498cc14cc446a1, **Branch** development

## Verification steps:

1- create a pool. 
2- deploy a solution on it.
3- let it expire it should delete these type of workloads.
