### ISSUE TITLE
tests specs to be included in the repo

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1316]
make sure to include the test specs and functionality covered in proper dir structure

handover to @AhmedHanafy725 to properly make  the issue and the requirements

**Comment by mhost39** [comment]
branch: development 
commit: cd47d39af06c4e133ab669379c5d0b298a282d68

https://github.com/threefoldtech/js-sdk/tree/development/docs/tests

Generate tests docs:
https://github.com/threefoldtech/js-sdk/blob/development/tests/README.md#generate-tests-docs-from-scratch
