### ISSUE TITLE
sendgrid got error while creating new object

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#1318]
Can't instantiate an object from sendgird 
![image](https://user-images.githubusercontent.com/46320202/94570125-c635ba00-026e-11eb-9ff0-2df80e47de0e.png)

**Comment by RafyAmgadBenjamin** [comment]
Fixed 
### branch
development_issue_sendgrid

### commit id
88b31a20090c852ec52a79984ed267c1712e8f9e

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 95bdc98e5e111086860aeb4af8031a2953f08541, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/96450479-90a14280-1216-11eb-8866-9b1b84019931.png)
