### ISSUE TITLE
sendgird coverage test 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#1329]

**Comment by RafyAmgadBenjamin** [comment]
![image](https://user-images.githubusercontent.com/46320202/94682133-cd1f0400-0324-11eb-9d35-97cdd4f4b40f.png)

### Branch 
`development_coverage_test_sandgrid`

### Commit
`0059a16ae242ab140d7e458ac301f022837c49e3`

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 95bdc98e5e111086860aeb4af8031a2953f08541, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/96431726-36978180-1204-11eb-8c31-3bceaba561e0.png)
