### ISSUE TITLE
Import CoreX client from JSX

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/js-sdk#1332]
### Description

The client for corex is nowhere to be found.
It used to be located at `j.clients.corex`

### Version information

* project commit/version: b1806bf214b5058910ac0ecc14aa046d4b61e968

### Installation method

local

### Steps to reproduce

open jsng shell and try to find corex client

**Comment by xmonader** [comment]
I don't recall we added it when we started sdk, but can convert to feature request, client seems to be easy to port

**Comment by zaibon** [comment]
So that was still JSX when I last saw it? Hum could be. Then we can indeed port it. I can prepare the PR 😊
