### ISSUE TITLE
allow 3bot user to auto extend the capacity pools if about to extend

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1337]
for 3bot maintenance of capacity pools can be annoying

- in settings we can have auto extend pools options or in pools view we track auto extend property
- if not able to extend we should notify the user by email
- extension threshold is 2 weeks
- if option is enabled we should check all of available wallets configured in the system to extend

more to be spec'd

**Comment by RafyAmgadBenjamin** [comment]
#### we have done:
- Add enable the auto-extend option and handle the logic in front and back end
- Add the logic required to auto extend the pools
#### working on a branch 
`development_3botdeployer_autoextend_pool`

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 18f55e2f75ca3ea90759761f5f8f030816d6dccf, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/98007864-91cc9500-1dfc-11eb-99f7-21ef593b6c3b.png)
