### ISSUE TITLE
3bot user notifications via mail

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1340]
allow 3bot user to get notified using email

e.g
- for expiring pools
- for empty wallets

**Comment by waleedhammam** [comment]
- Requires RQ, event bus

**Comment by xmonader** [comment]
check https://github.com/threefoldtech/js-sdk/issues/1335

**Comment by xmonader** [comment]
should have  https://github.com/threefoldtech/js-sdk/issues/1413

**Comment by waleedhammam** [comment]
escalations mails are configured but There's no service running to send/check pools & wallets

**Comment by RafyAmgadBenjamin** [comment]
I have tested this service and can't reproduce the issue
The service default setting that it runs every 24 hours so I have changed it to run every single min and it worked and registered as normal 
 
![image](https://user-images.githubusercontent.com/46320202/109129369-40ecfd80-7759-11eb-8995-b970eeaa65e6.png)
![image](https://user-images.githubusercontent.com/46320202/109129699-9a552c80-7759-11eb-9ad4-6510567f0cad.png)

I have configured `SMTP` mail server and test sending mail using our method and it indeed sent the mail

![image](https://user-images.githubusercontent.com/46320202/109129567-7265c900-7759-11eb-9346-d12fe6ebf789.png)

Note:
the mails sent in case of failure to extend the pool

**Comment by waleedhammam** [comment]
verified with @ranatrk 
![Screenshot from 2021-02-28 14-36-40](https://user-images.githubusercontent.com/10658229/109418701-81a37b80-79d2-11eb-8573-2a4fe2671a48.png)
![Screenshot from 2021-02-28 14-33-33](https://user-images.githubusercontent.com/10658229/109418703-823c1200-79d2-11eb-8c38-62b021c5e562.png)
![Screenshot from 2021-02-28 14-33-29](https://user-images.githubusercontent.com/10658229/109418704-82d4a880-79d2-11eb-9f49-902366efba6d.png)
