### ISSUE TITLE
allow plan option for threebot

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1341]
threebot should have different sizes

- Silver 1 CRU 2 MRU 2 SRU
- Gold 2 CRU 4 MRU 4 SRU
- Platinum  4 CRU 8 MRU 8 SRU

**Comment by RafyAmgadBenjamin** [comment]
#### branch 
`development_deployer_flavors`

#### commit Id
aa7992bd9c37270fc072ea88082ee09d7b456970

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 930e6a0f6d9888a3ff9fd744cb75ebe78bc79713, **Branch** development_3botdeployer

![ff](https://user-images.githubusercontent.com/21218053/96364074-c7089000-1138-11eb-99cd-812d9e1ad0b0.png)
