### ISSUE TITLE
generic container info in dashboard doesn't show volumes information

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#1347]
### Description

volume information isn't shown in the admin dashboard in generic containers

![image](https://user-images.githubusercontent.com/32568986/94826247-658db500-0407-11eb-8a62-338764f31728.png)

**Comment by RafyAmgadBenjamin** [comment]
#### fixed 
![image](https://user-images.githubusercontent.com/46320202/95750469-7ce95f80-0c9d-11eb-9df5-ae7b46ff2c63.png)

#### Branch 
development_flist_volumes_info_main_net
#### Commit
5a29541f9f02810c4b8b0361448ab06393a60834
18a220f517e5e4887a980b7bd6a0518979d6fc9c

**Comment by Dina-Abd-Elrahman** [comment]
**Comiit_ID** 94acba287f46ff0f2c3a4d49d076b1c9fb1f1e54, **Branch** development_flist_volumes_info_main_net

![ff](https://user-images.githubusercontent.com/21218053/95856603-8e447180-0d5a-11eb-919b-d5544d8abc11.png)
