### ISSUE TITLE
minio chatflow is broken after reserving ZDB

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#135]
there seems to be an update to the results of zdb in reservations
jsx updated in commit https://github.com/threefoldtech/jumpscaleX_threebot/commit/3a90ad22ad437a0a4113ab1dcd9b95e9c2d5f2c8

```
  File "/home/maged/Code/js-sdk/jumpscale/packages/tfgrid_solutions/chats/minio_deploy.py", line 265, in minio_reservation
    cfg = f"{data['Namespace']}:{self.password}@[{data['IP']}]:{data['Port']}"

KeyError: 'IP'
```

**Comment by BolaNasr** [comment]
Verified
![image](https://user-images.githubusercontent.com/10259267/86144919-96073f80-baf6-11ea-96b3-1f31f9df7b7f.png)
