### ISSUE TITLE
threebot server will crash if one of the package not found

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#136]
![Screenshot from 2020-06-29 19-33-08](https://user-images.githubusercontent.com/10658229/86037366-8f69c100-ba3f-11ea-8343-a00dd4732ac3.png)

also when trying to delete it 
![Screenshot from 2020-06-29 19-33-39](https://user-images.githubusercontent.com/10658229/86037408-a27c9100-ba3f-11ea-9453-acadca1e0233.png)

**Comment by AhmedSa-mir** [comment]
I tried to add/delete non-existent package and it didn't crash. It just raises exception.

**Comment by waleedhammam** [comment]
> I tried to add/delete non-existent package and it didn't crash. It just raises exception.

Add an existing package, then delete its files from the disk

**Comment by RafyAmgadBenjamin** [comment]
I have stopped the threebot server in case there is an error that happened during loading or installing the packages and raised an exception
#### PR
https://github.com/threefoldtech/js-sdk/pull/181

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
