### ISSUE TITLE
Test coverage for nginx sal

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/js-sdk#1363]

**Comment by Dina-Abd-Elrahman** [comment]
**Comiit_ID** 01ac08bc8051698b0478d22baa876fd2d4a4bef9, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/96599017-c36b3980-12ef-11eb-9d6e-e732d00f63a5.png)
![ff1](https://user-images.githubusercontent.com/21218053/96599027-c49c6680-12ef-11eb-8e79-eef77c010f0e.png)
