### ISSUE TITLE
Issue creating a capacity pool

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#1366]
Summary: I want to deploy a pool on my own farm: Dylan farm
![Screenshot from 2020-10-06 11-47-57](https://user-images.githubusercontent.com/17138347/95186037-ccc1b580-07c9-11eb-8b47-c19afa0068aa.png)

But when In the chatflows trying to create a pool on my farm I get an error and it points me to an alert which says nothing!
After that I check capacity pools and it created a pool with the information I filled in but it points to the wrong farmer! 
It is pointing to `lochristi_dev_lab` while it should point to dylan-farm..

Now when I inspect this pool it did get deployed on my 3 nodes on my farm but it is displaying the wrong farm name.. 

This is super confusing...

![Screenshot from 2020-10-06 11-42-18](https://user-images.githubusercontent.com/17138347/95185887-9ab05380-07c9-11eb-9e84-6d0259d084fe.png)
![Screenshot from 2020-10-06 11-42-32](https://user-images.githubusercontent.com/17138347/95185892-9c7a1700-07c9-11eb-92f4-3a78c097706b.png)
![Screenshot from 2020-10-06 11-42-56](https://user-images.githubusercontent.com/17138347/95185896-9e43da80-07c9-11eb-90f2-c0c78f125ac3.png)
![Screenshot from 2020-10-06 11-43-06](https://user-images.githubusercontent.com/17138347/95185900-9f750780-07c9-11eb-9980-1c3618d7af2e.png)
![Screenshot from 2020-10-06 11-43-14](https://user-images.githubusercontent.com/17138347/95185901-a0a63480-07c9-11eb-87c1-b0f5b803e4f2.png)
![Screenshot from 2020-10-06 11-43-25](https://user-images.githubusercontent.com/17138347/95185908-a13ecb00-07c9-11eb-8c05-498447e87af5.png)
![Screenshot from 2020-10-06 11-43-33](https://user-images.githubusercontent.com/17138347/95185912-a26ff800-07c9-11eb-8178-f5bc2cce7bfc.png)

**Comment by waleedhammam** [comment]
can you provide us with the logs/errors from shell at this part ?

**Comment by DylanVerstraete** [comment]
@waleedhammam 

```
2020-10-06 13:40:35.420 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method report from actor chatflows_chatbot to client ('127.0.0.1', 53748)
2020-10-06 13:40:35.421 | ERROR    | jumpscale.sals.chatflows.chatflows:wrapper:161 - error
Traceback (most recent call last):

  File "/home/dylan/Projects/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 185, in wrapper
    self._execute_current_step(spawn=False)
    │    └ <function GedisChatBot._execute_current_step at 0x7fb47c1d7c10>
    └ <tfgrid_solutions.chats.pools.PoolReservation object at 0x7fb47693b310>

  File "/home/dylan/Projects/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 193, in _execute_current_step
    wrapper(step_name)
    │       └ 'reserve_pool'
    └ <function GedisChatBot._execute_current_step.<locals>.wrapper at 0x7fb4773b50d0>

> File "/home/dylan/Projects/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 146, in wrapper
    getattr(self, step_name)()
            │     └ 'reserve_pool'
            └ <tfgrid_solutions.chats.pools.PoolReservation object at 0x7fb47693b310>

  File "/home/dylan/Projects/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 651, in wrapper
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<tfgrid_solutions.chats.pools.PoolReservation object at 0x7fb47693b310>,)
           └ <function PoolReservation.reserve_pool at 0x7fb4774108b0>

  File "/home/dylan/Projects/js-sdk/jumpscale/packages/tfgrid_solutions/chats/pools.py", line 47, in reserve_pool
    self.pool_data = deployer.create_pool(self)
    │                │        │           └ <tfgrid_solutions.chats.pools.PoolReservation object at 0x7fb47693b310>
    │                │        └ <function ChatflowDeployer.create_pool at 0x7fb4773eae50>
    │                └ <jumpscale.sals.reservation_chatflow.deployer.ChatflowDeployer object at 0x7fb477456f70>
    └ <tfgrid_solutions.chats.pools.PoolReservation object at 0x7fb47693b310>

  File "/home/dylan/Projects/js-sdk/jumpscale/sals/reservation_chatflow/deployer.py", line 400, in create_pool
    qr_code = self.show_payment(pool_info, bot)
              │    │            │          └ <tfgrid_solutions.chats.pools.PoolReservation object at 0x7fb47693b310>
              │    │            └ PoolCreated(
              │    │                reservation_id=81,
              │    │                escrow_information=PoolEscrow(
              │    │                address='',
              │    │                asset='',
              │    │                amount=0
              │    │              )
              │    │              )
              │    └ <function ChatflowDeployer.show_payment at 0x7fb4773eb040>
              └ <jumpscale.sals.reservation_chatflow.deployer.ChatflowDeployer object at 0x7fb477456f70>

  File "/home/dylan/Projects/js-sdk/jumpscale/sals/reservation_chatflow/deployer.py", line 497, in show_payment
    wallet = wallets[result]
             │       └ None
             └ {}

KeyError: None
127.0.0.1 - - [2020-10-06 13:40:3
```

**Comment by m-motawea** [comment]
looks like you don't have test wallets configured. needs to show a proper error message

also trying to create a pool on this Farm it returned 0 amount

![image](https://user-images.githubusercontent.com/32568986/95197405-d94e0a00-07d9-11eb-9e0f-a2fc9a9b1675.png)

**Comment by DylanVerstraete** [comment]
This is on devnet by the way

**Comment by m-motawea** [comment]
> This is on devnet by the way

yes I know. I'm using devnet now. devnet does not charge anymore?

**Comment by zaibon** [comment]
> yes I know. I'm using devnet now. devnet does not charge anymore?

Indeed, the escrow is not enabled on devnet, so pool creation is free on devnet

**Comment by m-motawea** [comment]
the incorrect farm name is because this node_id `2CBouXMr24TfNxxTs2i4ZqHgbpEagV1c14BnnjrZYdr7` is part of an old pool on `lochristi_dev_lab` farm. listing pools code tries to reduce the number of requests to the explorer so if the node_id was already matched with another farm (part of a pool on a specific farm), it doesnot fetch it's info again from the explorer

![image](https://user-images.githubusercontent.com/32568986/95198968-6003e680-07dc-11eb-9a36-162b66aa1545.png)
![image](https://user-images.githubusercontent.com/32568986/95199009-6e520280-07dc-11eb-934a-6cffbce6e5e9.png)

are node_ids not unique?

**Comment by DylanVerstraete** [comment]
Seems like we don't support chaning nodes between farms. I will delete this duplicate node from my farm and try again.

**Comment by DylanVerstraete** [comment]
Seems like the chatflow still fails with `none`, but I can see my new created pool with my farm name in the list

**Comment by DylanVerstraete** [comment]
![Screenshot from 2020-10-06 14-21-58](https://user-images.githubusercontent.com/17138347/95200836-516afe80-07df-11eb-9fdc-ea1246c2fa86.png)

**Comment by xmonader** [comment]
not an issue any longer
