### ISSUE TITLE
Error setting developer options

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#1368]
On commithash: 94f8ff24556e69d1c3047fdbf7623f033465c480

Failed to set developer options..

![Screenshot from 2020-10-06 13-29-50](https://user-images.githubusercontent.com/17138347/95196183-06012200-07d8-11eb-8436-1780abce7f52.png)

**Comment by m-motawea** [comment]
from the colors of the dark mode, it seems the frontend code is not updated up to the mentioned commit. not sure why.
can you try a hard refresh?
![image](https://user-images.githubusercontent.com/32568986/95306679-00fbab80-0888-11eb-9d0d-e63d1e658284.png)

**Comment by DylanVerstraete** [comment]
@m-motawea that fixes it indeed! Thank you
