### ISSUE TITLE
No network config after creating solution through marketplace

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/js-sdk#1371]
## Description
When creating a solution through the marketplace a network is generated ({username}.3bot_apps). When debugging there is no way to access the config file for the network. The only way now is to add the network to another node and then download the config file.

### Implementation

Either be able to download the config once the network is already deployed or show the config when creating (possibly least favorite)

**Comment by xmonader** [comment]
should be in ~/sandbox/cfg/ or ~/sandbox/cfg/wireguard, and you can add access to the network from the admin panel when debugging
