### ISSUE TITLE
Backup ~/.ssh dir in hosted 3bot

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1376]
Backup ~/.ssh dir in hosted 3bot

**Comment by RafyAmgadBenjamin** [comment]
done on branch
`development_3botdeployer_status`

**Comment by mhost39** [comment]
branch: development_3botdeployer
commit: 76e220ed6d43b496e7614fd7f98778ab631a65d4
![image](https://user-images.githubusercontent.com/31102305/98098695-592dc980-1e97-11eb-87dc-8efb9b2ff86c.png)
