### ISSUE TITLE
deleting multiple workload isn't working correctly

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1378]
- select all 5 zdbs I have from deployed solution

![image](https://user-images.githubusercontent.com/64129/95264881-691ea300-0830-11eb-8033-2622c2b05966.png)

first `Patch` that's wrong should be (Cancel workloads) only or (Cancel selected workloads)

then when I click confirm I get into this 2nd screen
![image](https://user-images.githubusercontent.com/64129/95264934-818ebd80-0830-11eb-8595-76dcd07021c6.png)

Which doesn't make much sense?

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 01ac08bc8051698b0478d22baa876fd2d4a4bef9, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/96583774-85651a00-12dd-11eb-8e9d-1b342b0cacc8.png)

![ff1](https://user-images.githubusercontent.com/21218053/96583789-89913780-12dd-11eb-9071-75dd21676f89.png)

![ff2](https://user-images.githubusercontent.com/21218053/96583891-b5acb880-12dd-11eb-9730-36698bb41cd2.png)
