### ISSUE TITLE
sdk docs review

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#14]
- [x] 3bot, gedis, packages, auth, ..etc
- [x] sal zos
- [x] explorer client 
- [x] stellar
- [x] chatflow engine
- [x] reservation chatflow
- [x] nginx tool
- [x] identities/encryption
- [x] wiki update

**Comment by waleedhammam** [comment]
reservation chatflow: https://github.com/threefoldtech/js-sdk/blob/7190bd94e18a37996361614abb12556c1793cd8e/jumpscale/sals/reservation_chatflow/README.md

**Comment by BolaNasr** [comment]
Identity & chatflow engine: https://github.com/threefoldtech/js-ng/pull/328

**Comment by BolaNasr** [comment]
explorer_client : https://github.com/threefoldtech/js-ng/pull/328/commits/82208108157ec0da973e503fd789d8f81dfaeb60

**Comment by BolaNasr** [comment]
sal zos: https://github.com/threefoldtech/js-ng/blob/b13ad37d0c76ce26d40fe66ec477907469296818/docs/wiki/zos_sal.md

**Comment by waleedhammam** [comment]
Stellar client docs are here already: https://github.com/threefoldtech/js-sdk/blob/28b83d4a556a8429fdc0b5271e0078f1cec68524/jumpscale/clients/stellar/readme.md

**Comment by waleedhammam** [comment]
there are docs for stellar client here: https://github.com/threefoldtech/js-sdk/blob/596217a4cccb56d325c4f28a549c0a2f40cbb68b/jumpscale/clients/stellar/readme.md

**Comment by ranatrk** [comment]
threebot,packages : https://github.com/threefoldtech/js-sdk/blob/3b199d05bc4e13d0aca21e104254d7f4933b83df/docs/wiki/threebot.md

gedis: https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/rpc.md
