### ISSUE TITLE
stellar client: handle timeout errros

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#140]
should be better handling exception and errors

![Screenshot from 2020-06-30 10-36-59](https://user-images.githubusercontent.com/10658229/86113516-a3f29b80-bac9-11ea-897d-8b7f28a206bc.png)

![Screenshot from 2020-06-30 10-37-36](https://user-images.githubusercontent.com/10658229/86113509-a2c16e80-bac9-11ea-8dba-da91591f96a5.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
