### ISSUE TITLE
Threefold NOW Marketplace - small upgrades

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#1400]
# preview: 
![demo1](https://user-images.githubusercontent.com/43240801/95470191-c9bcf580-0980-11eb-9976-c48d06a1eb85.png)

# Video preview on how it should look like:
[tfnow-demo-v2.zip](https://github.com/threefoldtech/home/files/5348538/tfnow-demo-v2.zip)

# TF Now Marketplace Upgrade Specs

### all **CSS and HTML** codes found at: 
https://app.zeplin.io/project/5f7f1bec89de1ab386edd2b8/screen/5f7f1c0ae4c19b1204909cf1

### **prototype / design** at: 
https://invis.io/AZZ0LG8BH6V

###  **SPECS**

- [x] add new logo
[TFNOW.png.zip](https://github.com/threefoldtech/home/files/5348414/TFNOW.png.zip)

- [x]  add search bar

- [x] change the top navigation red note to 'Demo on Testnet'

- [x] add categories sidebar 

Default view: **All Solutions**

**Collaboration Tools**

- Mattermost 
- Cryptpad 
- Taiga

**Web & Social**

- Website 
- Wiki 
- Blog 
- Peertube 
- Discourse 

**Developer Tools**

- Gitea

**Comment by mhost39** [comment]
branch: development 
commit: 40b40ba2abc7dfbd4e82fdfd9e498cc14cc446a1

![image](https://user-images.githubusercontent.com/31102305/96722134-5322ed80-13ad-11eb-8ad6-f07d4d75350a.png)
