### ISSUE TITLE
3bot website overview

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1412]
Should show the following

In 1 Table or in 3 Tables
- Running (Active) 3bots with actions related (stop, destroy =remove backup and stop, go to 3bot)
- Stopped (Inactive) 3bots with actions related (start, destroy = remove backup)
- Deleted  (Expired) 3bots (the ones without backup) with actions related (start again)

**Comment by RafyAmgadBenjamin** [comment]
to check started:
1- has a backup
2- user on the explorer
3- the workload is still in the state running

**Comment by RafyAmgadBenjamin** [comment]
We have updated the back-end and the front-end  to list all the 3bot with the new status (Running, Stopped, and Deployed)

**Comment by ashraffouda** [comment]
listing is done stop/destroy actions are now aligned with the new behavior 
![Screenshot from 2020-10-21 18-36-00](https://user-images.githubusercontent.com/1689456/96750624-74df9d00-13cc-11eb-9919-70d0bc826d06.png)
![Screenshot from 2020-10-21 18-36-06](https://user-images.githubusercontent.com/1689456/96750628-7610ca00-13cc-11eb-8b80-d9e83f907ce9.png)

**Comment by m-motawea** [comment]
final implementation to be merged in one table with an option for filtration by status https://github.com/threefoldtech/js-sdk/issues/1500
