### ISSUE TITLE
escalation emails configuration

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1413]
Allow from the dashboard configuring escalations emails list (Adding more emails), should contain the  logged in 3bot user email and active identity email

**Comment by RafyAmgadBenjamin** [comment]
done on branch 
`development_3botdeployer_escalation_emails`

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** a899019210baddae1173f9c36a3cf764a7a9245f, **Branch** development_3botdeployer

![ff](https://user-images.githubusercontent.com/21218053/96745699-b4a38600-13c6-11eb-9026-a1dcc5b661c6.png)
