### ISSUE TITLE
3bot to have a main wallet and ask user to fund it 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1414]
when UI starts for user it should have a main net wallet

- if wallet for mainnet with > 1000 TFT
  - ask if user wants to add more tokens to 3bot wallet
    - if yes: ask for TFT, min 400 TFT, max 20000 TFT

**Comment by OmarElawady** [comment]
Whenever `threebot start` is executed. A test wallet is created if there're no test wallets. And a main wallet is created if there're no main wallets. An announcement is shown at the first time the user opens the browser to show him a quick start guide.

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 18f55e2f75ca3ea90759761f5f8f030816d6dccf, **Branch** development

![ff1](https://user-images.githubusercontent.com/21218053/98008821-90e83300-1dfd-11eb-8d99-f6f3ba9c3f6c.png)

![ff](https://user-images.githubusercontent.com/21218053/98009301-0eac3e80-1dfe-11eb-909e-d76601c875d5.jpg)
