### ISSUE TITLE
deployment location:  SAL functionality

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1415]
- Automatic (best we can find)
- By Region: 
  - ask Europe/Asia/MiddleEast
  - check there is capacity, find a node
  - tell the node which will be used and where and confirm there was enough capacity
  - ask for ok, if not ok restart choose location

- By Farm:
  - choose a farm
  - check there is capacity, find a mode
  - tell the node which will be used and where 
  - ask for ok, if not ok restart choose location

- By Node:
  - specific node
  - check if enough capacity
  - tell something about the node: its life since, capacity is X,Y ..., name...
  - ask for ok, if not ok restart choose location

**Comment by mhost39** [comment]
branch: development_3botdeployer
commit: e33878915e08cffe07f2a739d25f8b45c08ca040
![image](https://user-images.githubusercontent.com/31102305/97108248-ecffd880-16d4-11eb-813b-c55dcb2d01c8.png)
![image](https://user-images.githubusercontent.com/31102305/97108237-dc4f6280-16d4-11eb-90fc-7ef53928cf4a.png)

![image](https://user-images.githubusercontent.com/31102305/97108262-03a62f80-16d5-11eb-838d-45ec99d335b3.png)
![image](https://user-images.githubusercontent.com/31102305/97108267-102a8800-16d5-11eb-8c8a-14433a7ff6d5.png)
