### ISSUE TITLE
Handle tcp test ping in gedis server at the start at threebot start

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#142]
at `threebot start` we do port check to make sure the server is up. 
but this exception should be handled in gedis server with better log

![Screenshot from 2020-06-30 12-50-03](https://user-images.githubusercontent.com/10658229/86117974-4877dc00-bad0-11ea-9c06-ebf356bc7da6.png)

**Comment by Dina-Abd-Elrahman** [comment]
I got this error while trying to start threebot. 

![error](https://user-images.githubusercontent.com/21218053/86251750-8fd69900-bbb2-11ea-8e7a-e3ac5a71461c.png)
![error](https://user-images.githubusercontent.com/21218053/86251852-b399df00-bbb2-11ea-9ba2-29280baa500e.png)

**Comment by alichaddad** [comment]
This is due to a to a change in the threebot server. Need to delete old threebot isntance `j.servers.threebot.delete('default')`

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
