### ISSUE TITLE
Export of reserved workloads in csv format

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/js-sdk#1422]
In JSX we used to have a page in the threebot dashboard which allowed to export all the workload reserved under the csv format. 
This was usefull for people wanting to implement some kind of billing mechanism on top of the grid.

Was there a reason this was removed in JS-NG ? If not could we re-introduce something similar ?

**Comment by joefoxton** [comment]
It would make our accounting (and the other farmers') much easier if we were able to export all transactions as a CSV file, along with all the invoice details. It should include the following columns:
- Transaction ID
- Transaction Datetime (CET) (When did the transaction take place?)
- Description (Short description of the transaction / services rendered, eg. Xcu Ysu added to pool XXXXX)
- Farmer (so we can see whether its GE or GEA)
- Name (customer's Official Business Name or Fullname for individuals)
- Address (Registered Address of the business or individual)
- Country (Country of Residnece)
- Type ("Business" or "Consumer")
- Company Registration Number
- EU VAT number
- Net price (in TFT, after fees withdrawn - ie. the amount deposited in our wallet)
- VAT (if charged, in TFT)
- VAT Reverse Charge (Yes or No)

Also, here are our full requirements for invoicing:
[Specimen EU VAT Invoice requirements.pdf](https://github.com/threefoldtech/js-sdk/files/5445560/Specimen.EU.VAT.Invoice.requirements.pdf)

**Comment by joefoxton** [comment]
If its possible to also include a URL to the entry on the blockchain that corresponds to the transaction, that would be awesome. Would be really helpful in case of audit.

**Comment by joefoxton** [comment]
Please note that there should be three invoices for each transaction:
- One for the TF Foundation Fee (between TF and customer)
- One for the TF Tech Fee (between TF Tech and customer, according to whatever rate was negotiated for that farmer)
- One for the Farmer -> Customer transaction
