### ISSUE TITLE
Can't import 4to6gw.py chatflow as it starts with number

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#1434]
It's needed for automated chatflows.
location: [4to6gw](https://github.com/threefoldtech/js-sdk/blob/development/jumpscale/packages/tfgrid_solutions/chats/4to6gw.py)

**Comment by mhost39** [comment]
branch: development
commit: 0e212803995e0795956adfda13606dff48c3e2d8
https://github.com/threefoldtech/js-sdk/blob/development/jumpscale/packages/tfgrid_solutions/chats/gw4to6.py
