### ISSUE TITLE
Add color to the current used identity

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#1438]
Couldn't know which of them is used.
![image](https://user-images.githubusercontent.com/41957921/96128226-60476480-0ef5-11eb-8bdc-cdb50e4f55df.png)

**Comment by AhmedHanafy725** [comment]
branch: development
commit: 01ac08bc8051698b0478d22baa876fd2d4a4bef9

In case of the logged in user is different than the identity one, can't see which identity used.
logged in with hanafy.3bot and identity used ahanafi.3bot

![image](https://user-images.githubusercontent.com/41957921/96580772-15549500-12d9-11eb-8838-3753298e0795.png)

**Comment by mhost39** [comment]
branch: development
commit: 0f30d244e01d6a884383adebd3441151baf62096
![image](https://user-images.githubusercontent.com/31102305/97980363-52408180-1dd9-11eb-8875-c6c9a8118ec2.png)
