### ISSUE TITLE
Use "Display name" instead of "Identity name" and add a tooltip

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1445]
![image](https://user-images.githubusercontent.com/64129/96339845-5c534800-1097-11eb-8308-5649e4362e8c.png)

As identity name is used within js config, it should be a valid python identifier.
and there's also a typo in the error message (om instead of on)

- should be called `Display name`
- should be unique
- should be valid python identifier
- Should have a tooltip next to it

**Comment by waleedhammam** [comment]
Should be a valid python identifier aswell

**Comment by mhost39** [comment]
branch: development
commit: 8e343adb664db071a46153e0c0b3f31e0376aef5
![image](https://user-images.githubusercontent.com/31102305/98223867-61e7d380-1f5b-11eb-83af-5e97c9750fe7.png)
