### ISSUE TITLE
not found /None

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1446]
when adding a new identity and making it the default and forgetting to set admins

![image](https://user-images.githubusercontent.com/64129/96348068-57e25b80-10a6-11eb-82d3-2af018670d8a.png)

and on clicking on the link on try again `https://localhost:8443/auth/None`

![image](https://user-images.githubusercontent.com/64129/96339936-f9ae7c00-1097-11eb-8ae8-21a70ae3b567.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 69d653a33e9248bb043271aa70aebab936812b19, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/96728142-18708380-13b4-11eb-876c-ab1753616767.png)

![ff1](https://user-images.githubusercontent.com/21218053/96728267-3a6a0600-13b4-11eb-972d-a5878917ca1e.png)
