### ISSUE TITLE
when adding a new identity make explorer mainnet the default in the form

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1453]
when adding a new identity make explorer mainnet the default in the form

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 8bf080fe6dbbbc9554bae39a8d7257fcc14e5b66, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/96699747-ec8ed700-138e-11eb-90f7-438456bb8b18.png)
