### ISSUE TITLE
failed to decrypt secret env var 'BACKUP_TOKEN': decryption error

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/js-sdk#1462]
### Description

3Bot deployer failed to create container with `failed to decrypt secret env var 'BACKUP_TOKEN': decryption error` error`

### Version information
Tried with: `https://deploy3bot.testnet.grid.tf/`

### Steps to reproduce

Try to deploy a hosted 3bot

### Traceback/Logs/Alerts

https://explorer.testnet.grid.tf/api/v1/reservations/workloads/491944

**Comment by waleedhammam** [comment]
The machines aren't updated yet with the latest development
