### ISSUE TITLE
use more proper listing for farms when creating a capacity pool

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1463]
use more proper listing for farms when creating a capacity pool instead of listing all of them like that

![image](https://user-images.githubusercontent.com/64129/96554711-2f7d7b80-12b7-11eb-995b-f11024525112.png)

**Comment by waleedhammam** [comment]
![Screenshot from 2020-10-20 13-43-41](https://user-images.githubusercontent.com/10658229/96581809-ae37e000-12da-11eb-9009-0aa7598ea688.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 20f8b701e75a953b1c304d6afff79a1a92fa5d23, **Branch**  development

![ff](https://user-images.githubusercontent.com/21218053/96615532-ab041a80-1301-11eb-84fa-447743f9c817.png)
