### ISSUE TITLE
TF NOW: Add new widgets to Marketplace

### ISSUE THREAD

**Issue by Vilnite** [threefoldtech/js-sdk#1466]
### Description

We need Marketplace to be in line with TF Now Wiki and vice versa, meaning we need to add on Marketplace widgets for all tools that are on TF Now wiki.
To make it distinguishable and clear each widget should have Deploy button instead of New button, or Coming soon button if tools is not deployable yet.
Deploy button leads to 3Bot Connect login and deployment process (current flow).
Coming soon button is inactive, for now.

### Implementation

For Deploy/Coming Soon buttons:
- [x] make Deploy button with green font (non active), when hovered over/highlighted - white font, add green background
- [x] make Coming Soon button with red font (non active), when hovered over/highlighted - white font, add red background 

Please add widgets for these tools:
- [x] Video Chat
category: Web & Social
description: P2P alternative to centralised video conferencing solution such as Zoom.
button: Coming Soon

- [x] Virtual Spaces
category: Web & Social
description: Meetup experiences and collaboration in virtual reality.
button: Coming Soon

- [x] Knowledge Base
category: Web & Social
description: A simple, self-hosted, easy-to-use platform for organising and storing information.
button: Coming Soon

- [x] CRM 
category: Collaboration Tools
description: Full featured Customer Relationship Management system.
button: Coming Soon

- [x] ZeroCI
category: Developer Tools
description: Continuous integration system useful for all programming languages.
button: Coming Soon

- [x] Commento
category: Collaboration Tools
description: Collaborate on online content without giving up your privacy.
button: Coming Soon

- [x] Serverless
category: Developer Tools
description: Architectures & workflow tool to build and operate serverless applications.
button: Coming Soon

- [x] Gridsome
category: Developer Tools
description: Gridsome makes it easy to build Jamstack websites using data from multiple sources.
button: Coming Soon

- [x] Dash
category: Blockchain Solutions (new category)
description: Open source peer-to-peer cryptocurrency with a strong focus on the payments industry.
button: Coming Soon

- [x] Digibyte
category: Blockchain Solutions (new category)
description: Safest, fastest, longest and most decentralised UTXO blockchains in existence.
button: Coming Soon

- [x] Elrond
category: Blockchain Solutions (new category)
description: The internet-scale blockchain, designed from scratch to bring a 1000-fold cumulative improvement in throughput and execution speed.
button: Coming Soon

- [x] Harmony
category: Blockchain Solutions (new category)
description: Fast and open blockchain for decentralised applications.
button: Coming Soon

- [x] Matic
category: Blockchain Solutions (new category)
description: Decentralised scalability platform solution using an adapted version of the Plasma framework that empowers Ethereum-based DApps.
button: Coming Soon

- [x] Neo
category: Blockchain Solutions (new category)
description: Scalable, fast, and ultra-secure Blockchain driven by a global community of developers and node operators.
button: Coming Soon

- [x] Scale
category: Blockchain Solutions (new category)
description: An elastic blockchain network that gives developers the ability to easily provision highly configurable chains compatible with Ethereum.
button: Coming Soon

- [x] TomoChain
category: Blockchain Solutions (new category)
description: Scalable blockchain-powered via Proof-of-Stake Voting consensus and used commercially by companies globally.
button: Coming Soon

- [x] WaykiChain
category: Blockchain Solutions (new category)
description: Prominent blockchain platform based in China with a global community.
button: Coming Soon

Make sure each widget links to the respective tool page on TF Now wiki (now.threefold.io)
- [x] widgets linked to the TF Now wiki pages
- [x] Blog / Website / Wiki widget links to the same Publishing Tool page on TF Now wiki

**Comment by sasha-astiadi** [comment]
@rkhamis Can you put it on a project so we can track it @xmonader

**Comment by Vilnite** [comment]
Wiki is updated, @rkhamis you can link each tool to respective section now: https://now.threefold.io/now/docs/
Thank you.

**Comment by Vilnite** [comment]
Where I can see a progress of this issue? @rkhamis

**Comment by rkhamis** [comment]
@Vilnite 

as sent on the group, temporarily we have it on https://waleed.threefold.io/marketplace/#/

or you can check out the attached PR

**Comment by sasha-astiadi** [comment]
@rkhamis why on waleed and not on marketplace2.threefold.io?

**Comment by rkhamis** [comment]
@sasha-astiadi only to demo it before updating. it will be updated on marketplace as soon as the PR is merged. we do not update marketplace before reviewing

**Comment by samtaggart** [comment]
Hi @rkhamis I don't see the Office Tools on the marketplace. Will they be added? Thanks!

**Comment by rkhamis** [comment]
@samtaggart it wasn't one of the requested solutions afaik

**Comment by samtaggart** [comment]
@Vilnite @sasha-astiadi Please advise re: the last two comments! Thank you

**Comment by mhost39** [comment]
branch: development
commit: b0546566798aa2a3c39cf2c14206625fe6bc7073
![image](https://user-images.githubusercontent.com/31102305/97211060-2749a280-17c7-11eb-848d-5589fc50e4d7.png)
![image](https://user-images.githubusercontent.com/31102305/97211113-3892af00-17c7-11eb-9551-a2ba2b75d5fc.png)
![image](https://user-images.githubusercontent.com/31102305/97211149-46483480-17c7-11eb-816b-7064a919a0bf.png)
![image](https://user-images.githubusercontent.com/31102305/97211194-57914100-17c7-11eb-88bd-7e307be31a8b.png)
