### ISSUE TITLE
TF NOW: Minor UI update

### ISSUE THREAD

**Issue by Vilnite** [threefoldtech/js-sdk#1467]
### Description

As a user I want to see what's available in marketplace without having to first sign up / sign in with 3bot Connect.
For that we need to remove 3Bot Connect login landing page from Marketplace.

### Implementation

- [x] Remove 3bot Connect login from landing page
- [x] Move 3Bot Connect login when user clicks on Deploy (instead New) button on the widget (see issue #1466)

**Comment by sasha-astiadi** [comment]
@xmonader @rkhamis Can user now sees all solutions without having to login to 3bot?

**Comment by xmonader** [comment]
> @xmonader @rkhamis Can user now sees all solutions without having to login to 3bot?

yes. It was shown in the other PR.

**Comment by mhost39** [comment]
branch: development 
commit: b0546566798aa2a3c39cf2c14206625fe6bc7073

![image](https://user-images.githubusercontent.com/31102305/97962039-0849a280-1dbd-11eb-95aa-79ed5436c919.png)
