### ISSUE TITLE
Message when a 3bot creation fails is too technical

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/js-sdk#1469]
"Please use the refresh button on the upper right to restart the chatflow"

Technically it is a chatflow but from a user perspective it is a deployment process.
I would say:" "Use the refresh button on the upper right to restart the 3bot creation"

**Comment by xmonader** [comment]
this error is part of standard error handling in chatflowengine itself, probably can be linked to the chatflow title https://github.com/threefoldtech/js-sdk/blob/9fc257715808a9cde69daa4bcbfa204897d86a0b/jumpscale/sals/chatflows/chatflows.py#L84

**Comment by mhost39** [comment]
branch: development 
commit: f0aa7a4148b39b3ad1c8f7700454485215f2a366
![image](https://user-images.githubusercontent.com/31102305/96857944-eae11400-145f-11eb-9366-171665d7236b.png)
