### ISSUE TITLE
Error while adding package through the admin  board 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#147]
![image](https://user-images.githubusercontent.com/46320202/86130922-381e2c00-bae5-11ea-9bc2-3a3c84cd4bc8.png)

#### I have added foo package from the admin dashboard and it is not listed there 

![image](https://user-images.githubusercontent.com/46320202/86130965-479d7500-bae5-11ea-97fa-ef685550952e.png)

**Comment by dmahmouali** [comment]
reproduced the issue, but after restart shell it shown.
![image](https://user-images.githubusercontent.com/36021484/86132378-17ef6c80-bae7-11ea-871e-ce2a3779b3e0.png)

**Comment by abom** [comment]
Well, where is the error?
Also, trying from another shell is not the best option here, but it should reflect all the packages anyway.

Please make sure it's not the-other-process problem, it might be the implementation of how packages are handled and threebot server itself.

**Comment by abom** [comment]
After debugging with Maged, it's the old loader used, so there're two versions of the factory, the one loaded by the older loader and the one you try to access in the shell.

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
