### ISSUE TITLE
wrong count number in the workloads message seems  it doesn't reset in workloads deleted message

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/js-sdk#1470]
## scenario:

1-  If I select 10 workloads, like this:

![ff](https://user-images.githubusercontent.com/21218053/96584855-1983b100-12df-11eb-8604-ebbfcd9f874f.png)

2- clear the selected workloads, Like this:

![ff1](https://user-images.githubusercontent.com/21218053/96585957-95cac400-12e0-11eb-8b50-36815d35073b.png)

3- Select another workloads with another category. 

![ff2](https://user-images.githubusercontent.com/21218053/96586031-ac711b00-12e0-11eb-8e45-d5bc7b18ceff.png)

4- Try to remove them, You will get the message with the old selected workloads and the new selected ones. 

![ff3](https://user-images.githubusercontent.com/21218053/96586084-c1e64500-12e0-11eb-91f9-6a8c78d26ef1.png)

**Comment by dmahmouali** [comment]
Switching filters don't affect selected items. should it? 
@rkhamis what do you think?

**Comment by rkhamis** [comment]
I'm not sure. it makes sense to keep the previously selected workloads, but I understand that it's potentially confusing for someone who forgot they have previously selected them

i vote that we leave it as is
