### ISSUE TITLE
taiga client: circle creation

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1484]
We don't want to create circles manually on the tool. The idea is we have the circles well defined & created from code, that way we know the circle is always consistent with the structure we need

see the different types of circles (projects in taiga nomenclature)

- team
- project
- funnel

https://github.com/threefoldtech/circles_reporting_tool/blob/master/specs/circle_creation.md

**Comment by MElborolossy** [comment]
Branch: development_vdc
commit: bf2418235471c891bda34b70da9ff1eed0665f1a

## Steps:
### Common steps:
1. Open jsng shell
2. Create a taiga client instance on staging threefold circles. `t_staging`

### Team circle
- Create a team circle
`team_circle = t_staging.create_new_team_circle('test_1', 'This circle to verify that all things is correct in team circle')`
- Add userstory and issue from frontend
- Result
![image](https://user-images.githubusercontent.com/11272864/104286504-cd9b6f00-54bd-11eb-9493-af67fe022e90.png)

### Funnel Circle
- Create a funnel circle
`funnel_circle = t_staging.create_new_funnel_circle('test_1', 'This circle to verify that all things is correct in funnel circle')`
- Add userstory and issue from frontend
- Result
![image](https://user-images.githubusercontent.com/11272864/104286659-020f2b00-54be-11eb-8a38-95e1d6579d6a.png)

- Custom fields
![image](https://user-images.githubusercontent.com/11272864/104286794-384caa80-54be-11eb-954b-8697756157b8.png)


### Project circle
- Create a team circle
`project_circle = t_staging.create_new_project_circle('test_1', 'This circle to verify that all things is correct in project circle')`
- Add userstory and issue from frontend
- Result
![image](https://user-images.githubusercontent.com/11272864/104286016-24547900-54bd-11eb-8f25-190acf5bffbc.png)

Verifed
