### ISSUE TITLE
3bot deployer: don't show recover / create option anymore

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1494]
![image](https://user-images.githubusercontent.com/64129/96897113-930dd180-148e-11eb-93eb-21f6422f9db7.png)

clearly, if the user clicked on new action he wants to create a new one if he wants to recover or start a stopped one should do so from the appropriate action button

**Comment by m-motawea** [comment]
need to explain what recove means now. deploys a 3bot on a different explorer than it was originally created on

**Comment by m-motawea** [comment]
fixed in 
https://github.com/threefoldtech/js-sdk/commit/86fed738b981a3d91e32d7656c52f5c14e5b4c56
https://github.com/threefoldtech/js-sdk/commit/75fdeb3e58df098e60bdf78da7b6124e4a8e64cc

**Comment by mhost39** [comment]
branch: development_3botdeployer 
commit: 75fdeb3e58df098e60bdf78da7b6124e4a8e64cc
![image](https://user-images.githubusercontent.com/31102305/97175078-9ad5ba80-179b-11eb-8023-6f4d2e1d5fb1.png)
![image](https://user-images.githubusercontent.com/31102305/97175014-87c2ea80-179b-11eb-8234-7b3c6b5c0026.png)
