### ISSUE TITLE
ux: 3bot deployer: the deployed 3bot active identity should be on the same network as the 3bot deployer

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1498]
when I deploy a 3bot from 3bot deployer, it has the mainnet identity active, while the pool and  the network the 3bot is running  on are on testnet. so let's make the active one is the same as the one  that has the 3bot pool

**Comment by m-motawea** [comment]
added in container entrypoint and environment
https://github.com/threefoldtech/js-sdk/commit/8127da6358ff375144439d1b5f9b7041aa3ee2db

**Comment by mhost39** [comment]
branch: development_3botdeployer
commit: 8127da6358ff375144439d1b5f9b7041aa3ee2db
![image](https://user-images.githubusercontent.com/31102305/98042540-68c3f880-1e2c-11eb-99e8-e49c9ba88523.png)
