### ISSUE TITLE
ux: 3bot deployer: update quickstart message

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1499]
![image](https://user-images.githubusercontent.com/64129/96898724-5ba02480-1490-11eb-856d-973e0f230c04.png)

`a test wallet and  a main wallet` doesn't really mean anything to the user, it's a wallet named main that can be used for mainnet deployments, and wallet named test that can be used for testnet deployments 

@rkhamis any idea on better phrasing?

**Comment by rkhamis** [comment]
how about:

we've created two wallets for you; `main` and `test`. These are to be used for mainnet and testnet respectively. Make sure your wallets are funded to extend your 3Bots before they expire.
for more information...

**Comment by m-motawea** [comment]
commit 
https://github.com/threefoldtech/js-sdk/commit/a8e8d04c67a05f910c723a2942f2a9fabc6e797d

**Comment by Dina-Abd-Elrahman** [comment]
![ff](https://user-images.githubusercontent.com/21218053/97970926-efe08480-1dca-11eb-99a1-13b0e5eb5581.png)
