### ISSUE TITLE
3bot deployer: all of my 3bots to be in the same table

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1500]
please merge into one table

![image](https://user-images.githubusercontent.com/64129/96899109-ca7d7d80-1490-11eb-8096-7e5c13212b1a.png)

- add status column
- remove url column and leave the browse action instead 
- make sure they are filterable too by status

**Comment by ranatrk** [comment]
https://github.com/threefoldtech/js-sdk/commit/e11f802237d4ae33d201e2de4625956a8bcec66f
![Screenshot from 2020-10-25 13-41-58](https://user-images.githubusercontent.com/17128393/97107795-12d7ae00-16d2-11eb-84fe-4c16185f47aa.png)

![Screenshot from 2020-10-25 13-42-17](https://user-images.githubusercontent.com/17128393/97107796-1408db00-16d2-11eb-87ff-0af8615e064b.png)

**Comment by mhost39** [comment]
branch: development 
commit: e11f802237d4ae33d201e2de4625956a8bcec66f
![image](https://user-images.githubusercontent.com/31102305/97978394-2c65ad80-1dd6-11eb-9222-490c83ff2363.png)
