### ISSUE TITLE
3bot deployer: after deploying 3bot there're no wallets created (testnet or mainnet)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1501]
![image](https://user-images.githubusercontent.com/64129/96901821-082fd580-1494-11eb-902f-e057b2907b73.png)

and list_all on stellar client doesn't show anything 
![image](https://user-images.githubusercontent.com/64129/96902217-88eed180-1494-11eb-9420-a9233656d194.png)

I think maybe the instances were created but  not saved?

**Comment by ranatrk** [comment]
branch: development_3botdeployer
Fix : https://github.com/threefoldtech/js-sdk/commit/fbd9048aca978197ea6eb391bf936ebc89883aab
call method to create testnet wallet and mainet wallet when deploying new 3bot
![Screenshot from 2020-10-25 17-49-45](https://user-images.githubusercontent.com/17128393/97111985-7cfc4d00-16ea-11eb-96a7-41c2132b1b67.png)

**Comment by mhost39** [comment]
branch: development_3botdeployer
commit: fbd9048aca978197ea6eb391bf936ebc89883aab

![image](https://user-images.githubusercontent.com/31102305/97161455-86d38e00-1786-11eb-8ee0-4a7c768fd052.png)
