### ISSUE TITLE
Internal server errors are not visible

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#1504]
### Description

I clicked on a wallet in the admin dashboard to see the details. This generated an internal server server error.
This is not visible in the alerts and in the logs only shown as info showing the method it executed on which actor.
Ot he console it shows it is indeed a 500:
```
2020-10-23 10:10:58.053 | INFO     | jumpscale.servers.gedis.server:_on_connection:268 - Executing method get_wallet_info from actor admin_wallet to client ('127.0.0.1', 55627)
127.0.0.1 - - [2020-10-23 10:10:58] "POST /admin/wallet/get_wallet_info HTTP/1.0" 500 501 0.485935
```
To get the actual error, I had to look at the response in the browser:
```json
{
    "error": "{\n  \"type\": \"https://stellar.org/horizon-errors/not_found\",\n  \"title\": \"Resource Missing\",\n  \"status\": 404,\n  \"detail\": \"The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided.\"\n}"
}
```

I think unhandled actor exceptions should be visible in some way

### Version information

v11.0-b9

**Comment by xmonader** [comment]
@abom can you take a look at this please

**Comment by abom** [comment]
Should be resolved by https://github.com/threefoldtech/js-ng/pull/501, as gedis errors will be logged.

**Comment by robvanmieghem** [comment]
@xmonader will this be part of grid 2.3 or grid 2.4?
