### ISSUE TITLE
TF NOW: Cryptad is failing deployment

### ISSUE THREAD

**Issue by Vilnite** [threefoldtech/js-sdk#1507]
### Description

Couldn't deploy Cryptad on Marketplace. Process took longer than 10min and was terminated:

<img width="1082" alt="Screenshot 2020-10-25 at 15 18 53" src="https://user-images.githubusercontent.com/20182572/97108340-9cd54600-16d5-11eb-828c-8503ee5a2be6.png">

**Comment by xmonader** [comment]
No available resources on testnet

**Comment by xmonader** [comment]
related https://github.com/threefoldtech/zos/issues/1008

**Comment by mhost39** [comment]
branch: master
commit: 01f046f672b90adcb3726773bd204b77fb30283c
![image](https://user-images.githubusercontent.com/31102305/97876999-41363880-1d25-11eb-9224-4a911098f817.png)
