### ISSUE TITLE
TF NOW: Gitea is failing deployment

### ISSUE THREAD

**Issue by Vilnite** [threefoldtech/js-sdk#1508]
### Description

Couldn't deploy Gitea on marketplace:

<img width="1094" alt="Screenshot 2020-10-25 at 15 25 47" src="https://user-images.githubusercontent.com/20182572/97108460-56ccb200-16d6-11eb-9a2e-28e4d4425301.png">

**Comment by xmonader** [comment]
No available resources on testnet
