### ISSUE TITLE
creating wallet: The url requested is not valid, or no data in our database could be found with the parameters provided.

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1511]
![image](https://user-images.githubusercontent.com/64129/97111595-6c4ad780-16e8-11eb-99c6-24a40c8b9172.png)

received this error 

```json
{ "type": "https://stellar.org/horizon-errors/not_found", "title": "Resource Missing", "status": 404, "detail": "The resource at the url requested was not found. This usually occurs for one of two reasons: The url requested is not valid, or no data in our database could be found with the parameters provided." }
```

**Comment by waleedhammam** [comment]
resolved by: https://github.com/threefoldtech/js-sdk/issues/1425

**Comment by mhost39** [comment]
branch: development 
commit: 20f8b701e75a953b1c304d6afff79a1a92fa5d23

![image](https://user-images.githubusercontent.com/31102305/97288402-7850a980-184e-11eb-8d87-6ea764b8aef6.png)
![image](https://user-images.githubusercontent.com/31102305/97288716-ee551080-184e-11eb-9fc9-afbc6a9a9298.png)
