### ISSUE TITLE
Creating wallet: name already exists 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1512]
![image](https://user-images.githubusercontent.com/64129/97111635-a3b98400-16e8-11eb-9681-51fbac5b2a18.png)

After failing to create a wallet in #1511 I click submit again and I get `name already exists` error

**Comment by mhost39** [comment]
branch: development 
commit: 10de5a5341261669d46b42800d586f82f6871437
![image](https://user-images.githubusercontent.com/31102305/97162319-b8992480-1787-11eb-91e8-64963d76eabc.png)
![image](https://user-images.githubusercontent.com/31102305/97162370-c9e23100-1787-11eb-98e5-665704a43833.png)
