### ISSUE TITLE
TF Now: Add message that TF Now will only be live for 3 hours

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/js-sdk#1517]
Poeple who test TF Now are suprised that it disapears after 3 hours. 

Need a message that pops up once TF Now is live which states that it will only be available for 3 hours.

**Comment by waleedhammam** [comment]
added for first time and in the red banner 

![Screenshot from 2020-10-26 14-22-04](https://user-images.githubusercontent.com/10658229/97173093-b095b080-1798-11eb-9e3c-1ffaba8f65c1.png)

![Screenshot from 2020-10-26 14-21-37](https://user-images.githubusercontent.com/10658229/97173141-c014f980-1798-11eb-9866-b8e5b31a5535.png)

**Comment by mhost39** [comment]
branch: development 
commit: 8bf83e66ce00df7fbf887d292cddac43ab40e5b7
![image](https://user-images.githubusercontent.com/31102305/97289506-f3ff2600-184f-11eb-91d0-f7483501d741.png)

**Comment by samtaggart** [comment]
@waleedhammam @mhost39 We have updated text, please update!

Welcome! This marketplace is a showcase of open source peer-to-peer apps built on top of the TF Grid. We are in demo mode & running on testnet. Note your deployment will be cancelled automatically after three hours. Forgive any instability you might encounter while our developers work out the kinks. Please enjoy, and visit the [manual](https://manual.threefold.io/#/threefold_now) or [wiki](https://now.threefold.io/) for more info.

**Comment by m-motawea** [comment]
> @waleedhammam @mhost39 We have updated text, please update!
> 
> Welcome! This marketplace is a showcase of open source peer-to-peer apps built on top of the TF Grid. We are in demo mode & running on testnet. Note your deployment will be cancelled automatically after three hours. Forgive any instability you might encounter while our developers work out the kinks. Please enjoy, and visit the [manual](https://manual.threefold.io/#/threefold_now) or [wiki](https://now.threefold.io/) for more info.

please create a new feature request
