### ISSUE TITLE
update repos links examples used in the chatflows

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1523]
update repos links examples used in the chatflows to the following 

- wiki : https://github.com/threefoldfoundation/wiki_example
- blog : https://github.com/threefoldfoundation/blog_example
- website : https://github.com/threefoldfoundation/website_example

**Comment by mhost39** [comment]
branch: development
commit: c8f20dbdc3c98ed1e1622bd3715faf6c5dddd40e
![image](https://user-images.githubusercontent.com/31102305/97199106-4b51b780-17b8-11eb-888f-14645bb8508d.png)
![image](https://user-images.githubusercontent.com/31102305/97199190-691f1c80-17b8-11eb-999a-78df21f8aab1.png)
![image](https://user-images.githubusercontent.com/31102305/97198931-16ddfb80-17b8-11eb-9432-762b74eaf8e8.png)
