### ISSUE TITLE
Broken link on (i) sign on marketplace.threefold.io

### ISSUE THREAD

**Issue by nbabenko** [threefoldtech/js-sdk#1528]
### Description

1. Go to https://marketplace.threefold.io/marketplace/#/
2. Press on (i) sign (Go to How-To Manual) on any of the marketplace deployments (see attachment)
<img width="419" alt="Screenshot 2020-10-26 at 19 25 42" src="https://user-images.githubusercontent.com/4426772/97206206-16962e00-17c1-11eb-8152-e4938cfcd3d2.png">
3. Broken link opens: https://now10.threefold.io/docs/dmcircles/. Now10.threefold.io is not functioning.  Should be https://now.threefold.io/

### Version information

* OS: Any
* project commit/version: As of 26 Oct 2020 available on https://marketplace.threefold.io/marketplace/#/
* Browser: Any

**Comment by xmonader** [comment]
not an issue anymore
