### ISSUE TITLE
Wiki Deployment failed to deploy in time

### ISSUE THREAD

**Issue by maximilianrang** [threefoldtech/js-sdk#1530]
### Description

Error msg
"Workload 493733 failed to deploy in time. Please use the refresh button on the upper right to restart the chatflow"

### Version information

Win 10, Chrome
https://marketplace.threefold.io/

### Steps to reproduce

Tried to deploy this wiki: https://github.com/maximilianrang/wiki_example

**Comment by xmonader** [comment]
related to https://github.com/threefoldtech/zos/issues/1008

**Comment by mhost39** [comment]
branch: master
commit: 01f046f672b90adcb3726773bd204b77fb30283c
![image](https://user-images.githubusercontent.com/31102305/97965466-10a4dc00-1dc3-11eb-9442-0b5a63ac6506.png)
