### ISSUE TITLE
Add test for 4to6gw chatflow

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#1532]
- Fix importing in gedis patch [4to6gw](https://github.com/threefoldtech/js-sdk/blob/development/solutions_automation/dashboard_solutions/four_to6gw.py) and also in [deployer](https://github.com/threefoldtech/js-sdk/blob/development/solutions_automation/deployer.py). 
- Add a test in [automation chatflows](https://github.com/threefoldtech/js-sdk/blob/development/tests/sals/automated_chatflows/test_solutions.py)

**Comment by mhost39** [comment]
4to6gw added and skipped for this issue https://github.com/threefoldtech/tfgateway/issues/60
