### ISSUE TITLE
UX: email configuration

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1540]
![image](https://user-images.githubusercontent.com/64129/97302149-5876b100-1861-11eb-9b5a-b3a690297ade.png)

- should be configurations not config
- property/ value should be removed
- add a tooltip to tell the user where to get these data from

**Comment by mhost39** [comment]
branch: development_3botdeployer
commit: 036a5a236ca797aa5d1f41e586965113ec597749
![image](https://user-images.githubusercontent.com/31102305/97464998-402e9100-194a-11eb-8ff9-c581a0f05e3d.png)
