### ISSUE TITLE
3bot started with two wallets on TEST network?

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1541]
![image](https://user-images.githubusercontent.com/64129/97302304-8b20a980-1861-11eb-9345-42d0a3fc9f25.png)

**Comment by mhost39** [comment]
branch: development_3botdeployer
commit: 68231d286438b22d367a192fdd88dfb3d393754c
![image](https://user-images.githubusercontent.com/31102305/97979198-6c796000-1dd7-11eb-8720-6550bb9b7a2d.png)
