### ISSUE TITLE
Automated Tests for the New Threebot Deployer

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#1543]
### Description

Add automated tests for the new chatflows and the new scenarios introduced by threebot deployer

### Implementation

1- Deploy a new threebot
2- Start a stopped threebot
3- Change threebot size
4- Change threebot location

**Comment by mhost39** [comment]
branch: development
commit 776dcb37d95c4781d36fe65c83a58870ef10f4b8
