### ISSUE TITLE
Service manager discussion thread

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/js-sdk#1547]
Here are some notes, some of them already mentioned in the code, that may make the service manager more awesome than it already is.

1. Interval specified in the job represents the time between a stop and the next start, not successive start. This might be an issue if we used it for something like running nightly tests when the grid load is light. If it takes half an hour to perform the test, after about 10 times, it won't be nightly anymore.
Suggestion: Maybe we can add a field (day of the week, month, day of the month, hour, minute) like cron jobs to enable something like this?
2. Error handling is done and printed by gevent. Maybe it should be caught and logged somewhere else?
3. When stopping 3Bot, it doesn't wait for services to finish, which might cause leaked resources for something like chatflow tests.
Suggestion: Wait for them or add for the services an optional signal handler that they can override to clear its stuff before terminating.
4. If I start a service that runs every day and then stop it immediately after registering. It'll run the first one. (Will not appear since the stoppage is done just before stopping 3Bot so the service won't run anyway).
Suggestion: Add a level of indirection for greenlets to call a function that checks for the status, then calls the job method if the status is not "stopped".
5. Checking services duplicates means it doesn't allow inheritance. Maybe it would be resolved by the redesign discussed below.

Refactoring: Create a ServiceGroup which behaves almost the same as ServiceManager but contains only a list of strings which represents the names of instances of another factory called Service and all the logic of starting, stopping and scheduling is delegated to the Service factory instance. Also the service file doesn't have to contain an object of the service. The Service factory instance can import the module and instantiate an object from it. This facilitates creating more than one service of the same type and checking for duplicates won't be an issue anymore.

**Comment by xmonader** [comment]
@OmarElawady please feel free to pick any remaining features to be discussed in a future thread
