### ISSUE TITLE
3bot: identity list in settings fails if one of the identity explorer URL is not reachable

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/js-sdk#1551]
sometimes i create identities that points to explorer instance that don't exist anymore (for example when i am testing against an explorer that is running on my laptop)

once this explorer is down, the identity list in 3bot settings does not show any of my identities

so may be a broken identity should be ignored, or even show in red or something

**Comment by mhost39** [comment]
Verified
commit: c9586457a0eeeed3c7bd5175eed931182416f353
branch: development
