### ISSUE TITLE
Add Multiple Nodes to a Network in one Deployment in Chatflows

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#1557]
### Description

Currently the chatflows update the network by adding only one node at a time. This is ok for most of the solutions except for k8s when it can add much more nodes to the network.

**Comment by mhost39** [comment]
branch: development
commit: 33a7ba0303ed4f225f35ee38b16c1d1746599869
![image](https://user-images.githubusercontent.com/31102305/97969163-544e1480-1dc8-11eb-8352-e2febe9b87f6.png)
