### ISSUE TITLE
TF NOW: Update categories on Marketplace

### ISSUE THREAD

**Issue by Vilnite** [threefoldtech/js-sdk#1564]
### Description

Please update categories on Marketplace according to now2.threefold.io sidebar, so both marketplace and wiki are in-line.

### Implementation

- [x] Web & Social = Decentralised WE 
- [x] Collaboration Tools = Decentralised Office
- [x] Developer Tools = Decentralised Developer

**Comment by mhost39** [comment]
branch: development
commit: e278134d5c1ff49a3bc7bc13d4941ddc8f892a85

![image](https://user-images.githubusercontent.com/31102305/97873166-e1895e80-1d1f-11eb-9655-f61fe416af50.png)
