### ISSUE TITLE
TF Now: Remove Secret Key from Taiga Setup

### ISSUE THREAD

**Issue by samtaggart** [threefoldtech/js-sdk#1565]
Please remove Secret Key from Taiga Setup.

I spoke to @xmonader today and we discussed that Secret Key is probably not needed for testnet purposes and/or we can generate a secret key automatically.

Please let me know what you decide so I can include it in the tutorial.

**Comment by mhost39** [comment]
branch: development 
commit: c81ac9a3ad1f277802767ee1bb22aaf6276193e9
![image](https://user-images.githubusercontent.com/31102305/98106129-a7e06100-1ea1-11eb-9eca-54be0108bd30.png)
