### ISSUE TITLE
3Bot deployment using 3bot deployer failed on mainnet with not enough space left in pools

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/js-sdk#1569]
tried to install a 3bot using 3bot installer failed. got the following message:

<img width="1668" alt="image" src="https://user-images.githubusercontent.com/18591016/97736997-b8c55700-1adc-11eb-898c-68583a9888be.png">

Was never asked in the process to pay tft for the deployment.

Tried to create a new 3bot with the name 'edina'

**Comment by xmonader** [comment]
it was related to https://github.com/threefoldtech/zos/issues/1037
