### ISSUE TITLE
Video chat solution is not available in the marketplace

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#1571]
### Description
One of the main features of grid 2.3 is the video chat solution as stated in the grid 2.3 releasenotes.
I deployed a new 3bot on testnet but that solution is not available:
![Screenshot 2020-11-01 at 11 17 10](https://user-images.githubusercontent.com/3511318/97800851-d1e31a80-1c38-11eb-857b-c2575db756b3.png)

**Comment by xmonader** [comment]
Video chat is part of the marketplace not 3bot admin solutions 
https://marketplace2.threefold.io/
