### ISSUE TITLE
A testnet 3bot creates and initialises a mainnet wallet

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#1572]
### Description

When a 3bot is deployed on testnet, it creates and initialises both a testnet and a mainnet wallet.
This drains the mainnet activation service from xlm and is not required since testnet 3bots run on testnet with testnet TFT's

![Screenshot 2020-11-01 at 11 13 06](https://user-images.githubusercontent.com/3511318/97801276-ba596100-1c3b-11eb-8863-bb305bc54978.png)

**Comment by waleedhammam** [comment]
It was a feature request https://github.com/threefoldtech/js-sdk/issues/1227

**Comment by robvanmieghem** [comment]
@waleedhammam Ok, on testnet, a testnet wallet and on mainnet, a mainnet wallet. I'm constantly funding our mainnet activation service with real xlm and it get's constantly drained due to testnet deployments

**Comment by xmonader** [comment]
agreed on having only testnet wallet for 3bot running on testnet, and on mainnet a mainnet wallet
