### ISSUE TITLE
ux: 3bot deployer action dialog

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1575]
![image](https://user-images.githubusercontent.com/64129/97812838-ed781080-1c8c-11eb-807e-7d35039316f3.png)
there we ask for the password, but we allow clicking confirm without specifying anything, the dialog should remain open with the error message instead of closing with a flash

**Comment by mhost39** [comment]
branch: 3bot_sort_actions
commit: 80aa5ec761b6599058d83d21273a8492b2b91ead
![image](https://user-images.githubusercontent.com/31102305/97994239-c422c600-1ded-11eb-9ef7-644705c96f79.png)
