### ISSUE TITLE
ux: 3bot actions consistency

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1576]
![image](https://user-images.githubusercontent.com/64129/97812868-26b08080-1c8d-11eb-8ece-94d2822b26ec.png)

let's sort the actions out so we don't have such a weird-looking different rows

**Comment by mhost39** [comment]
branch:development
commit: 93387d4fca14d391c912dcc86261ee29e548dc13
![image](https://user-images.githubusercontent.com/31102305/97992518-72793c00-1deb-11eb-92e5-1e8001badbf9.png)
