### ISSUE TITLE
Failed to find resources should give more info

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1577]
Right now the message show is `Failed to find resources for this reservation. If you are using a low resources environment like testnet, please make sure to allow over provisioning from the settings tab in dashboard`

I'd like to have more info e.g the query and any more relevant information

**Comment by mhost39** [comment]
branch: development
commit: ccaa99b53dcaaf084fb01371623bcbe81b8c6dcb
![image](https://user-images.githubusercontent.com/31102305/97875995-df290380-1d23-11eb-8aac-d5c87f950bc0.png)
