### ISSUE TITLE
Update Example Scripts to use the management network or create it if it doesn't exist

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#1578]
### Description

Currently all example scripts create a new network and use it for deployment. 
we need to update these scripts to use the management network if it exists or create it if it doesn't with subnet `10.100.0.0/16`

### Scripts:
- [x] k8s (@m-motawea & @waleedhammam)
- [x] minio (@m-motawea & @waleedhammam)
- [x] ubuntu (@RafyAmgadBenjamin )
- [x] ubuntu deploy (@AhmedSa-mir & @dmahmouali )
- [x] ubuntu server (@m-motawea )

**Comment by RafyAmgadBenjamin** [comment]
Ubuntu PR:
https://github.com/threefoldtech/js-sdk/pull/1590
