### ISSUE TITLE
Unable to set the expiration time in the 3bot deployment flow

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#1581]
### Description
When changing the date:
![Screenshot 2020-11-01 at 10 59 09](https://user-images.githubusercontent.com/3511318/97851285-788cf100-1cf5-11eb-8899-74c1669de008.png)

When only changing the time, the datetime is not modified

### Version information
grid 2.3 on testnet
Using Safari on osx

**Comment by ranatrk** [comment]
On Safari:
Issue is with Safari only
Was able to reproduce when choosing an old date then choosing any time or date in teh future where the date shows Invalid date. Works fine if choosing a date in the future from the begining.
<img width="640" alt="image" src="https://user-images.githubusercontent.com/17128393/97982222-1eb32680-1ddc-11eb-8afd-c853f07d28f0.png">

On firefox and chrome works fine
<img width="640" alt="image" src="https://user-images.githubusercontent.com/17128393/97982236-2377da80-1ddc-11eb-92ef-281abb5f1db2.png">

**Comment by robvanmieghem** [comment]
I'll retest

**Comment by xmonader** [comment]
@ranatrk and @dmahmouali is it possible to use min field to prevent using dates earlier than today?

**Comment by mhost39** [comment]
branch: development
commit: 4aaa9d3ffa666daea94ac2f0181196fdfe0ed78c
![image](https://user-images.githubusercontent.com/31102305/98258931-1ef12480-1f8a-11eb-9ba6-b44545d0390a.png)
![image](https://user-images.githubusercontent.com/31102305/98259341-ab9be280-1f8a-11eb-8628-851baef56c4d.png)
