### ISSUE TITLE
marketplace package required server restart , can not access admin portal by domain 

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/js-sdk#1582]
### Description

I followed these docs https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/marketplace/deployment.md

1 - i have start threebot by `threebot restart` then I have added marketpalce as manaul step 

`
j.servers.threebot.default.packages.add("/root/js-sdk/jumpscale/packages/marketplace/")
j.servers.threebot.default.save()
`
2 - when i refresh the page that showes the packages installed on threebot , marketpalce shown as not installed 

3 - i  restart threebot by `threebot restart` , then i can access marketpalce by domain https://marketplace.freeflowpages.com

4 - i can not access admin portal by domain name with `https://marketplace.freeflowpages.com/admin` , it redirect me to marketplace page 

### Version information
```
root@marketplace:~/js-sdk# git log -1
commit d3c4653e5d18e2acfd2a4eea4c3106622c314f76 (HEAD -> development, tag: 11.0-b11, origin/development, origin/HEAD)
Author: xmonader <xmonader@gmail.com>
Date:   Thu Oct 29 18:03:58 2020 +0200

    Development 3botdeployer (#1441)

```

**Comment by xmonader** [comment]
admin package isn't bound to domain should be accessible via IP

**Comment by Pishoy** [comment]
got this error when trying IP 
![image](https://user-images.githubusercontent.com/21987477/97857284-26a09700-1d06-11eb-91b4-f3745d4c03c3.png)

**Comment by Pishoy** [comment]
ok, closed then

**Comment by Pishoy** [comment]
but on that point when got error like below , we need to access admin portal which is not ok with domain ?
![image](https://user-images.githubusercontent.com/21987477/97858582-0671d780-1d08-11eb-9db2-41ca0140e3d7.png)

**Comment by xmonader** [comment]
can you please open this in a different issue that alert link when on domain should use the admin url instead?

**Comment by Pishoy** [comment]
sure
