### ISSUE TITLE
The 3bot solution summaries are too long to fit in the foreseen space

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#1587]
![Screenshot 2020-11-01 at 11 17 10](https://user-images.githubusercontent.com/3511318/97859617-2b168100-1d01-11eb-87b4-34592a4dfa4b.png)

**Comment by xmonader** [comment]
I think it's ok, Digital ocean is doing the same in their marketplace 
![image](https://user-images.githubusercontent.com/64129/97859937-f6f38e00-1d09-11eb-9264-377178a67125.png)

**Comment by robvanmieghem** [comment]
Yes but there you can see the details:
![Screenshot 2020-11-03 at 10 14 43](https://user-images.githubusercontent.com/3511318/97967505-96be2400-1dbd-11eb-98b3-632fddbab904.png)
Some texts are easy to be shortened without loosing any information

**Comment by xmonader** [comment]
If this to be included please provide short description and long description to be used in the solutions home page and one to be used in full details page.

**Comment by xmonader** [comment]
dragging this issue since nov 3rd: @sasha-astiadi, what is the plan here?
