### ISSUE TITLE
Failed to initialize wiki

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/js-sdk#1594]
after a lot of time i get :
![image](https://user-images.githubusercontent.com/31102305/97888582-f7088380-1d33-11eb-97c9-3af0067db90d.png)
 
and in my workloads:
![image](https://user-images.githubusercontent.com/31102305/97888998-7c8c3380-1d34-11eb-9179-1b5ae552a86c.png)

when try to access website: 
![image](https://user-images.githubusercontent.com/31102305/97889151-ae9d9580-1d34-11eb-8226-9d8151b9f86b.png)

application details:
![image](https://user-images.githubusercontent.com/31102305/97889650-469b7f00-1d35-11eb-9d99-1cc6c6ddd3f3.png)

Tried to deploy this wiki: https://github.com/maximilianrang/wiki_example

**Comment by waleedhammam** [comment]
It's due to a courrpted wiki package, not related to deployment

**Comment by mhost39** [comment]
![image](https://user-images.githubusercontent.com/31102305/97965425-0256c000-1dc3-11eb-884e-38991fb7e6bc.png)
