### ISSUE TITLE
Docker build hangs in the codeserver installation step in github actions

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/js-sdk#1599]
### Description

A lot of [github actions](https://github.com/threefoldtech/js-sdk/actions?query=workflow%3A%22Build+docker+image%22) times out at the codeserver installation step when building the docker image.

I added the codeserver compressed file in [this](https://github.com/threefoldtech/js-sdk/runs/1346863329?check_suite_focus=true) commit to bypass wget and it worked. So it seems wget hangs and doesn't return the control.

**Comment by OmarElawady** [comment]
works with curl:
https://github.com/threefoldtech/js-sdk/actions/runs/347021217

**Comment by xmonader** [comment]
Probably it was  related to https://gist.github.com/jwebcat/5122366
