### ISSUE TITLE
Email we show is a fake address

### ISSUE THREAD

**Issue by VonSub** [threefoldtech/js-sdk#1616]
The email address shown in the UI underneath the 3Bot name and ID is a "fake one" which I don't really understand where it comes from. It's confusing to show this information when it's unclear what it's used for.

<img width="244" alt="Screenshot 2020-11-05 at 10 49 01" src="https://user-images.githubusercontent.com/29431263/98225040-84c2b980-1f54-11eb-97ee-38101120ddd4.png">

**Comment by xmonader** [comment]
resolved in https://github.com/threefoldtech/js-sdk/pull/1629

**Comment by mhost39** [comment]
branch: development
commit: 7d0cc8c4195724b93633992b753149ee3c540337
![image](https://user-images.githubusercontent.com/31102305/98258430-8bb7ef00-1f89-11eb-9cf1-ba9a0304996c.png)
