### ISSUE TITLE
Should stellar client be updated ?

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#163]
should we have the latest stellar client , cause at sometime using latest was causing some issues, but now actually not using the latest is causing issues

- Latest
![Screenshot from 2020-07-01 19-43-33](https://user-images.githubusercontent.com/10658229/86286612-15743c00-bbe7-11ea-924d-65555d158b74.png)

- Current
![Screenshot from 2020-07-01 19-37-27](https://user-images.githubusercontent.com/10658229/86286624-19a05980-bbe7-11ea-9328-e3fc8dfafcf3.png)

_ Note: Everything should be tested if updated

**Comment by xmonader** [comment]
I think @robvanmieghem is the go to person for this decision

**Comment by waleedhammam** [comment]
not relevant anymore
