### ISSUE TITLE
as a user I'd like to copy workload info in more detail view

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1632]
![image](https://user-images.githubusercontent.com/64129/98252366-81debd80-1f82-11eb-977b-b0111f497e07.png)

Here I can't copy and paste the json data easily

same problem in 3bot settings -> js configurations

![image](https://user-images.githubusercontent.com/64129/98252451-a20e7c80-1f82-11eb-8b10-01a45706fa03.png)

**Comment by AhmedHanafy725** [comment]
**Verified**
**Branch:** development_vdc
**Commit:** da50148a76d6e9a94699c00311e004cf50c1d878

![image](https://user-images.githubusercontent.com/41957921/107518335-905af780-6bb7-11eb-9a3e-e198068b9196.png)

![image](https://user-images.githubusercontent.com/41957921/107518348-92bd5180-6bb7-11eb-90a1-d6be63adc28a.png)
