### ISSUE TITLE
Cannot change the location for stopped 3bot instances on deploy3bot.testnet.grid.tf/

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/js-sdk#1638]
Try to change the location for stopped 3bot instance, I got this error 

![ff](https://user-images.githubusercontent.com/21218053/98276706-09d2c080-1f9f-11eb-8c00-bc8890087804.png)

after refresh I changed it normally

**Comment by m-motawea** [comment]
I checked the alert. `list index out of range`.
but can't reproduce it. if you encounter it again can you add the complete url of the chatflow? perhaps the 3bot name was not passed properly to the chatflow.
