### ISSUE TITLE
alert_raise should always have the traceback

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1639]
noticed in [deployer](https://github.com/threefoldtech/js-sdk/blob/dd8b788aa89ecd92044c2c2b68ab37aec8556bc7/jumpscale/sals/reservation_chatflow/deployer.py#L867) and [chatflows](https://github.com/threefoldtech/js-sdk/blob/f0aa7a4148b39b3ad1c8f7700454485215f2a366/jumpscale/sals/chatflows/chatflows.py#L169) that we raise alerts without having tracebacks

**Comment by ranatrk** [comment]
Merge waiting on next release for js-ng changes to be able to use the changes in js-sdk chatflows

**Comment by hossnys** [comment]
verified on development branch , traceback is now included in the alerts raised .

![Screenshot from 2020-11-15 16-53-39](https://user-images.githubusercontent.com/26298009/99188064-bd3b7200-2762-11eb-8912-ff2a5ddd7032.png)
