### ISSUE TITLE
New Wallet in production

### ISSUE THREAD

**Issue by majjihari** [threefoldtech/js-sdk#1641]
### Description

Error creating new wallet in production environment.

### Version information

* OS: e.g. Ubuntu 18.04.5
![photo5852672718338634791](https://user-images.githubusercontent.com/2501864/98460267-e16fdf80-21b3-11eb-9428-61f6d9ceda2a.jpg)

### Steps to reproduce

Click on Create in Wallets Menu from 3bot admin in production environment.
3bot admin is installed locally in ubuntu
Chrome browser is used to access interface

**Comment by robvanmieghem** [comment]
solved it (again) by topping up the activation service wallet
