### ISSUE TITLE
Remove extension flow from 3botdeployer and have one path for extension using the 3bot

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1648]
When we deploy a 3bot we provision for 1h and ask user once the 3bot initialized successfully to extend it with their own money, 
now that 3bot owner actually owns the 3bot, they can go to the 3bot and extend from there admin dashboard. So  probably its best to remove extension flow from 3botdeployer and have one path for extension using the 3bot dashboard

**Comment by robvanmieghem** [comment]
On mainnet they should already pay in advance, or not?

**Comment by waleedhammam** [comment]
But this means he should have a locally installed sdk, in the current state, he doesn't have to ?
