### ISSUE TITLE
55% of my capacity was already in use while firing up

### ISSUE THREAD

**Issue by VonSub** [threefoldtech/js-sdk#1656]
The First thing I see after my 3Bot was launched I see that 55% of my capacity is already in use.
I could not find out how/what caused it but it feels weird, and wouldn't like that as a capacity users to be very honest.

<img width="529" alt="Screenshot 2020-11-10 at 11 43 05" src="https://user-images.githubusercontent.com/29431263/98697509-4de60c80-2375-11eb-8090-30eb8ce1f1c2.png">

**Comment by xmonader** [comment]
this is the disk usage of the node itself (probably should call it node disk usage) not the 3bot container usage

**Comment by weynandkuijpers** [comment]
I had the same experience.  we need a bit clearer description what those numbers mean because for most deployments people will not select the node - people will let the system select the node.  Therefore it is unclear what these numbers are.

Just replace "Disk Usage" with "Host 3node disk usage".

**Comment by waleedhammam** [comment]
Branch: **development_vdc**
commit: 
```
commit a3b3e84efc89af97679556b30c48ecf0308baa73 (HEAD -> development_vdc, origin/development_vdc)
Merge: 8f7cb61c c0905e12
Author: Waleed <waleed.hammam@gmail.com>
Date:   Tue Feb 23 14:21:34 2021 +0200

    Merge pull request #2613 from threefoldtech/development_vdc_merge
    
    Development vdc merge
```
![Screenshot from 2021-02-23 16-16-12](https://user-images.githubusercontent.com/10658229/108856205-7b885600-75f2-11eb-82db-6450960f4eb5.png)

Verified
