### ISSUE TITLE
Random empty pool fired up after deployment

### ISSUE THREAD

**Issue by VonSub** [threefoldtech/js-sdk#1657]
There was a random empty pool fired up after my 3bot deployment.
It had no workloads, capacity, or expiration set.

<img width="528" alt="Screenshot 2020-11-10 at 11 45 47" src="https://user-images.githubusercontent.com/29431263/98697796-98678900-2375-11eb-9004-6173eb52daf7.png">

**Comment by xmonader** [comment]
@m-motawea is that the gateway pool?

**Comment by xmonader** [comment]
that's the gateway pool providing public access to the 3bot
