### ISSUE TITLE
3Bot Deployer on testnet: can not destroy 3Bot 

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/js-sdk#1659]
A stopped 3Bot can not be destroyed.

URL: https://deploy3bot.testnet.grid.tf/threebot_deployer/#/workloads

<img width="2245" alt="Pasted Graphic 11" src="https://user-images.githubusercontent.com/18591016/98704333-d1efc280-237c-11eb-9a88-f379b10a8648.png">

**Comment by xmonader** [comment]
@andhartl are you sure of the password you used? @dmahmouali will be hardening the error message in the dialog asking for the  password

**Comment by xmonader** [comment]
Problem was the password wasn't entered at all hardening been done in https://github.com/threefoldtech/js-sdk/pull/1673

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 4e9f2d4fbe6e3da089e48ac26297cfe7a87c0d7d, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/99241698-e1508f00-2806-11eb-8676-01a3c3c6e402.png)
