### ISSUE TITLE
Allow changing the chatflow title

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#166]
Allow changing the title of a chatflow maybe by setting a class variable on the chatflow and if not let's leave the current default "Zero Chat Bot" as is

**Comment by AhmedSa-mir** [comment]
Changed title here: https://github.com/threefoldtech/js-sdk/commit/9122fdcf0ed1f0ec511414cb73d75108d1b41871

**Comment by xmonader** [comment]
```pythonn

class TheChatflow(Chatflow):
    TITLE = ....
```
Please make it similar to this

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
