### ISSUE TITLE
3bot deployer login screeen and 3bot login screen should state "ThreeFold Connect"

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#1661]
### Search first

Search for similar issues first, if not complete the following template

### Description

3bot Connect app is being rebranded to Threefold Connect.  So to make that clear replace the icon/graphic with a ThreeFold one, not a 3bot one.  Also - change the log in button to reflect "ThreeFold connect".

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/13766992/98788071-c43c4a80-2419-11eb-94a0-f1342782f8e2.png">

### Implementation

Jsut change the name / naming

### More

Not needed - simple request.

**Comment by xmonader** [comment]
The icon shouldn't get replaced (it's a message coming from the 3bot server) and should use the 3bot logo
