### ISSUE TITLE
Rotating circle (wait screen) stays on forever while deployment process continuous

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#1662]
### Search first

No similar issue(s) found

### Description

At various (non related) places in deployments process and in wait screens in general the screen does not progress to the next chat screen untill you do a manual "page refresh" in the browser. 

I have not been able to pinpoint what, where of when this bug is triggered.

### Version information

3bot online on testnet.

### Installation method

Online ployer for 3bots on testnet.  Maybe important to mention that I am mostly using Firefox as a browser

### Steps to reproduce

Like stated above, it happens, but unpredictable and in a number of places.

### Traceback/Logs/Alerts

Just visuals, nothing other in terms of output.

**Comment by xmonader** [comment]
using trc as part of the 3bot flist should have improved since https://github.com/threefoldtech/js-sdk/pull/1947
