### ISSUE TITLE
Message when you first login to 3bot on testnet still mantions "mainnet wallet"

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#1663]
### Search first

No similar issue found

### Description

Simple: the message when you first login to a new 3bot says that a testnet _and_ mainnet wallet will be opened.  No need for a mainnet wallet (I think this is addressed elsewhere - just remove the message notification of the mainnet wallet).

### Version information

New 3bot deployed on testnet

### Installation method

3bot deployer

### Steps to reproduce

new 3bot - log in - message appears.

### Traceback/Logs/Alerts

Just visual.

**Comment by Dina-Abd-Elrahman** [comment]
**Commit** fe1bfec885b51dfb78a2cc1038d1e98d7348df79, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/99253014-a3f4fd00-2818-11eb-9778-38b44b7ee71c.png)
