### ISSUE TITLE
Updating trustlines in testnet wallet results in "freeTFT's to appear as a supported currency.

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#1664]
### Search first
No similar issue found

### Description

When you go to a newly created test wallet in 3bot on testnet and you update the trustlines a former currency (but no longer supported) appears in the wallet.

<img width="569" alt="image" src="https://user-images.githubusercontent.com/13766992/98789139-54c75a80-241b-11eb-9094-b0521860341f.png">

### Version information

3bot on testnet

### Installation method

3bot deployer on testnet

Better to specify the installation method

### Steps to reproduce

Create new wallet on testnet 3bot and pdate trustlines.

### Traceback/Logs/Alerts

Just visual

**Comment by xmonader** [comment]
What about TFTA?

**Comment by xmonader** [comment]
Only TFT trustline is used now

**Comment by hossnys** [comment]
verified on development branch , only TFT appears now .

![Screenshot from 2020-11-15 16-57-57](https://user-images.githubusercontent.com/26298009/99188164-3cc94100-2763-11eb-83e3-90e05e092066.png)
