### ISSUE TITLE
TF Now Video chat: typo on flavour select screen

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/js-sdk#1668]
should say 'to use' 
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/18591016/98805146-71fa2a00-2417-11eb-90ca-50747100b6f0.png">

**Comment by hossnys** [comment]
verified on development branch :

![Screenshot from 2020-11-15 16-43-14](https://user-images.githubusercontent.com/26298009/99187763-1f937300-2761-11eb-9d90-e65b65779bd2.png)
