### ISSUE TITLE
Automate chatflows tests are failing

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#1672]
Please check the tests https://github.com/threefoldtech/js-sdk/runs/1382823533?check_suite_focus=true
- If the failure in (test, gedispatch, or workflow), please fix it.
- If the failure in chatflow, please report the issue and skip the test.

**Comment by mhost39** [comment]
related issue https://github.com/threefoldtech/js-sdk/issues/1678

**Comment by mhost39** [comment]
https://github.com/threefoldtech/js-sdk/runs/1415085572?check_suite_focus=true

sometime when deploy solution get low resource error
and sometime solution is deployed but can't access it like (k8s, minio, ubuntu)
and threeboy work fine in local machine but in CI git this error

![image](https://user-images.githubusercontent.com/31102305/99547004-b65d6b00-29bf-11eb-90d8-6974b3a4de99.png)

**Comment by m-motawea** [comment]
@mhost39 the attribute error in the screenshot is because threebot_deployer package is not installed.
you need  to install the package before you run the test

**Comment by AhmedHanafy725** [comment]
This error happens with cert check even with setting `TEST_CERT`
![image](https://user-images.githubusercontent.com/41957921/99903434-08a6d080-2ccd-11eb-9360-fe3dad6058b2.png)

**Comment by mhost39** [comment]
https://github.com/threefoldtech/js-sdk/issues/1945
