### ISSUE TITLE
Change text on button to TF Connect

### ISSUE THREAD

**Issue by VonSub** [threefoldtech/js-sdk#1689]
The app has been rebranded to ThreeFold Connect on Android as of today, and the Apple App Store will follow soon so we need to change the button to reflect this and counter confusion.
![Screenshot 2020-11-16 at 12 07 47](https://user-images.githubusercontent.com/29431263/99245797-7dc56200-2804-11eb-97b4-90b88e0e368c.png)

**Comment by xmonader** [comment]
It's TF Connect now..
