### ISSUE TITLE
simple way to get TFT price in fiat currency (EUR USD)

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#1700]
### Description

need a simple way to convert between TFT and other fiat currencies

note: we have a kraken client in js-sdk and currency layer

**Comment by robvanmieghem** [comment]
@m-motawea  there is also a liquid client to get the tft/btc pair price, if you combine that with the btc/eur or btc/usd price, you already have it so I don't think there is a new feature needed
