### ISSUE TITLE
3bot deployer requires farms to have ip4 and ip6 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1708]
this narrows the results to freefarm only, should use ip4

**Comment by ranatrk** [comment]
verified, when deploying on `https://deploy3bot.grid.tf/threebot_deployer/#/` farms include both not just ipv4
![Screenshot from 2021-01-13 18-50-27](https://user-images.githubusercontent.com/17128393/104483229-8fdb3b00-55d0-11eb-9869-6da129fd7723.png)
