### ISSUE TITLE
error saving stellar client on mac

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#171]
Operation not permitted on `/Users/rob/.config/jumpscale...`

- new issue to track the saving stellar client on mac. that happened with @robvanmieghem

**Comment by xmonader** [comment]
@waleedhammam probably fixable by `chown` on `/Users/rob/.config/jumpscale`

**Comment by robvanmieghem** [comment]
I checked the entire path and it was rob:staff

**Comment by xmonader** [comment]
should be fixed by https://github.com/threefoldtech/js-ng/issues/182

**Comment by robvanmieghem** [comment]
works like a charm now
