### ISSUE TITLE
Cannot start 3bot

### ISSUE THREAD

**Issue by nbabenko** [threefoldtech/js-sdk#1720]
### Description

I cannot restrart my 3bot on https://deploy3bot.grid.tf/threebot_deployer/#/chats/restart_threebot/admin3botnickolay

it says

"Failed to find resources (cru=0, sru=2.25, mru=0 and hru=None in pool with id=976) for this reservation. If you are using a low resources environment like testnet, please make sure to allow over provisioning from the settings tab in dashboard. For more info visit our manual . Use the refresh button on the upper right to restart 3Bot creation."

when I try to press refresh button, it asks for password and then shows the same message again

Ive tried to delete the bot and restart again, getting the same issue. Tried to create another new 3bot but after deployment. Says: "server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN"

Tried to restart the second bot - but getting the same "Failed to find resources"

My ThreeFold Connect name:  nickolay.3bot

**Comment by waleedhammam** [comment]
> ### Description
> I cannot restrart my 3bot on https://deploy3bot.grid.tf/threebot_deployer/#/chats/restart_threebot/admin3botnickolay
> 
> it says
> 
> "Failed to find resources (cru=0, sru=2.25, mru=0 and hru=None in pool with id=976) for this reservation. If you are using a low resources environment like testnet, please make sure to allow over provisioning from the settings tab in dashboard. For more info visit our manual . Use the refresh button on the upper right to restart 3Bot creation."
> 
> when I try to press refresh button, it asks for password and then shows the same message again
> 
> Ive tried to delete the bot and restart again, getting the same issue. Tried to create another new 3bot but after deployment. Says: "server IP address could not be found.
> DNS_PROBE_FINISHED_NXDOMAIN"
> 
> Tried to restart the second bot - but getting the same "Failed to find resources"
> 
> My ThreeFold Connect name: nickolay.3bot

@nbabenko Which farm are you trying to install on ? can you add more information how did you install that 3Bot in the first time ? or the workload ids ?

**Comment by ranatrk** [comment]
couldn't reproduce, successfully deployed 3bot on  https://deploy3bot.grid.tf/threebot_deployer
![Screenshot from 2021-01-19 13-12-01](https://user-images.githubusercontent.com/17128393/105027134-102df000-5a58-11eb-84f7-0af23c972a80.png)

![Screenshot from 2021-01-19 13-11-27](https://user-images.githubusercontent.com/17128393/105027105-099f7880-5a58-11eb-8ac8-ce2dee74b629.png)
