### ISSUE TITLE
Management network configuration file is overwritten in saving

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#1721]
# Description

1 - Saving the network is hardcoded to the name managment, and written to the filesystem with the same name, that could lead in conflict in network configs in case of parallel deployments
https://github.com/threefoldtech/js-sdk/blob/development/jumpscale/sals/marketplace/deployer.py#L444

2- Saving the network wg files should be in wireguard dir not cfg, the dir is created but it saved outside
https://github.com/threefoldtech/js-sdk/blob/development/jumpscale/sals/reservation_chatflow/reservation_chatflow.py#L1217

**Comment by mhost39** [comment]
Verified 
commit: 24149b9b92e1db95dfacf4fc117813e59c3573f5
branch: development
