### ISSUE TITLE
TF Now: Rename Apps on Marketplace

### ISSUE THREAD

**Issue by samtaggart** [threefoldtech/js-sdk#1723]
Please rename apps in marketplace to coincide with now.threefold.io:

- [ ] Taiga --> Project Management
- [ ] CryptPad --> Collaborative Docs
- [ ] Mattermost --> Team Collaboration
- [ ] Discourse --> Community Forum
- [ ] Peertube --> Video Sharing
- [ ] Gitea --> Git Service
- [ ] ZeroCI --> Continuous Integration Tools
- [ ] Commento --> Comments Widget
- [ ] Serverless --> Serverless App Framework
- [ ] Gridsome --> Modern Site Generator

_Note: Needs to be changed in the title and in the description._

**Comment by xmonader** [comment]
if needed for the vdc marketplace please open a new issue
