### ISSUE TITLE
TF Now: Add Office Tools to Marketplace (Coming Soon)

### ISSUE THREAD

**Issue by samtaggart** [threefoldtech/js-sdk#1727]
Mark as Coming Soon! I'm not asking for the widget to be added to the marketplace, just for the frontend UI widget to be added.

**Title**
Office Tools

**Description**
Office Tools is an online office suite integrated with a collaboration platform to manage documents, projects, team and customer relations in one place.

**WIki Link**
https://now.threefold.io/now/docs/onlyoffice/

**Icon**
![fb_icon_325x325](https://user-images.githubusercontent.com/50134479/99994238-091c9580-2db9-11eb-9ebc-b86bb323019e.jpg)

**Label**
Decentralized Office

**Comment by sasha-astiadi** [comment]
@rkhamis KDS demand a new widget ASAP for office. can u prioritize this?

**Comment by xmonader** [comment]
Is that for tfnow or the vdc marketplace? Either way that's  blocked still.

**Comment by xmonader** [comment]
That issue was for marketplace.threefold.io, closing

**Comment by Vilnite** [comment]
TF Now marketplace = VDC marketplace (same thing)
Need to add:
- [ ] office tools (based on onlyoffice)
- [ ] file browser aka dropbox alternative (see issue #1834)
