### ISSUE TITLE
user was asked for tft payment on testnet 3bot deployer

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#1730]
<img width="1136" alt="Screenshot 2020-11-24 at 15 18 01" src="https://user-images.githubusercontent.com/43240801/100106061-5d328300-2e68-11eb-9f58-db6280459c0a.png">

it should not have asked me for payment

**Comment by xmonader** [comment]
duplicated of https://github.com/threefoldtech/js-sdk/issues/1648
