### ISSUE TITLE
Farm Management not showing nodes 

### ISSUE THREAD

**Issue by majjihari** [threefoldtech/js-sdk#1732]
### Description

Though the nodes exist in farm (Capacity Explorer is showing) the 3bot Farm Management is not showing them.
Farm 13673 has nodes

![photo5902154886231995963](https://user-images.githubusercontent.com/2501864/100114365-6af50200-2e82-11eb-903c-39baf9c2bf74.jpg)

**Comment by muhamadazmy** [comment]
@DylanVerstraete any progress ?

**Comment by xmonader** [comment]
doesn't seem to be an issue I already managed to create a farm with nodes today
![image](https://user-images.githubusercontent.com/64129/103174545-baf12b00-486b-11eb-8e4b-aefafe74b144.png)
