### ISSUE TITLE
trying to access chatflow after connection loss on my local machine 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1745]
![image](https://user-images.githubusercontent.com/64129/100523543-de1bb280-31b9-11eb-9faf-db9e52e9c6e7.png)

I tried to remove the values in local storage, but didn't help, i removed the cookies too as well

**Comment by xmonader** [comment]
probably not related to the connection, found the new call erroring with `package None not found`

![image](https://user-images.githubusercontent.com/64129/100523660-c0028200-31ba-11eb-8d73-3dd6a2f5f42c.png)

**Comment by MElborolossy** [comment]
Branch: development
Commit: d0da777e8aea3ce9deded8dcb371c2e70c8365c9

### Steps:
- Run `threebot start` locally
- Go to Solutions
- Disconnect threebot
- Run `threebot start` again
- Go to Solutions again, It works fine

Verified
