### ISSUE TITLE
proper reloading of services

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1748]
Tried to reload tfgrid_solutions and theit failed on add_package call with ` {"error": "Service with name threebot_deployer_auto_extend_pools already exists"}`, luckily it reloaded the package but didn't mange to reload the service, but it should all work

**Comment by waleedhammam** [comment]
Verified on latest development, packages reloaded successfully


![Screenshot from 2021-02-24 11-20-35](https://user-images.githubusercontent.com/10658229/108978523-577c5180-7692-11eb-9f12-4e91894201e9.png)
