### ISSUE TITLE
restore authorizing sshkeys for ssh accessing the 3bot

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1750]
#1537

**Comment by waleedhammam** [comment]
Verifying

**Comment by waleedhammam** [comment]
Feature is done, to be implemented in chatflows here https://github.com/threefoldtech/js-sdk/issues/1538

![Screenshot from 2021-01-11 11-07-39](https://user-images.githubusercontent.com/10658229/104162596-96658900-53fd-11eb-948b-e48975de94b1.png)
