### ISSUE TITLE
increase disk sizes for 3bot

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1751]
![image](https://user-images.githubusercontent.com/64129/100525727-ad447900-31cb-11eb-8f8a-463e91186739.png)

these are the available sizes, let's review and see what's feasible

**Comment by despiegk** [comment]
lets do min 4GB for all, and last one 8 GB

**Comment by waleedhammam** [comment]
continue in https://github.com/threefoldtech/js-sdk/issues/1827
