### ISSUE TITLE
testing required on 3bot deployer

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/js-sdk#1752]
- [x] let capacity pool which is used for 3bot expire, can we still import and continue?
- [x] do automatic backup, check after X days that the backup indeed was there and we got 3bot back after deleting it
- [ ] 

complete this test plan, let kristof see

**Comment by hossnys** [comment]
3bot deploying is blocked in both mainnet and testnet due to these two issues :
- mainnet : https://github.com/threefoldtech/js-sdk/issues/2150

![Screenshot from 2021-01-11 14-32-03](https://user-images.githubusercontent.com/26298009/104182927-db97b400-5419-11eb-8afe-a50d784c00ca.png)

- testnet : https://github.com/threefoldtech/tfexplorer/issues/272

![Screenshot from 2021-01-11 14-32-22](https://user-images.githubusercontent.com/26298009/104182938-e0f4fe80-5419-11eb-99a1-111e52349fdd.png)

**Comment by hossnys** [comment]
as deploying 3bot on mainnet still blocked , so i created since 2 days threebot on testnet but all the setup there gone due to testnet reset action , and when trying to create again on testnet i got an error reported here https://github.com/threefoldtech/js-sdk/issues/2211

**Comment by hossnys** [comment]
new 3bot deployed now after funding the wallet of testnet 3bot deployer machine .

![Screenshot from 2021-01-13 13-57-36](https://user-images.githubusercontent.com/26298009/104450068-38c17000-55a8-11eb-9f6f-31da971208bc.png)

**Comment by hossnys** [comment]
restoring the 3bot after expired is not working fine , reported here https://github.com/threefoldtech/js-sdk/issues/2233

**Comment by hossnys** [comment]
test scenario done successfully, the backup restored and 3bot back to work smoothly with all configuration, wallets, packages , workloads, added admins .
for more info screenshots added here https://github.com/threefoldtech/js-sdk/issues/2233#issuecomment-760202943 .

**Comment by hossnys** [comment]
>     * [ ]  do automatic backup, check after X days that the backup indeed was there and we got 3bot back after deleting it

P.S : 
- destroying the 3bot instance is going to delete all its backup snapshots , so no way to get it back with the previous state .
- so i just wait till it's pool expired so it's stopped automatically , then start it and the backup restored successfully.

**Comment by hossnys** [comment]
@despiegk  the backup test scenario done here and it's working fine after the pool expired and renewed .
