### ISSUE TITLE
default 3bot image seems to be not ideal

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/js-sdk#1754]
- make default 4GB image, I had issues with 2 GB, why is that? it should be much smaller no?

**Comment by waleedhammam** [comment]
removed rust build tools, new image size is aroung 1.5 GB

**Comment by ranatrk** [comment]
image is less than 2GB 
![image](https://user-images.githubusercontent.com/17128393/105054322-880d1200-5a7a-11eb-9704-06f8e3c6079a.png)
