### ISSUE TITLE
deployed 3bot, but then could not load it

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/js-sdk#1755]
![image](https://user-images.githubusercontent.com/6021844/100537883-65a20980-322c-11eb-9e8a-296f4928b459.png)

something wrong with network gateways?

how reliable is our system?

**Comment by despiegk** [comment]
I tried to restore from an old 3bot that could be the issue as well,
maybe the versions are incompatible?

**Comment by xmonader** [comment]
the login service login.threefold.me is down
