### ISSUE TITLE
create QR code for topping up a wallet in 3Bot admin

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/js-sdk#1756]
would be nice user can also scan the toppup feature for a wallet.

**Comment by xmonader** [comment]
User in their 3Bot wallets list should see a button to show up a dialog with QR code encoding the address and maybe fixed 100 TFT that use can change after scanning in the threefold connect app

**Comment by weynandkuijpers** [comment]
![screenshot_20210315_113057](https://user-images.githubusercontent.com/13766992/111118208-ee497900-8581-11eb-8a6b-145d4905106f.png)

Done
