### ISSUE TITLE
Failed To Create Reverse Proxy 

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/js-sdk#1766]
i get this error when try to deploy wiki, blog, website, mattermost, cryptpad and gitea 
![image](https://user-images.githubusercontent.com/31102305/100731678-64134580-33d4-11eb-9fc8-e569ba6e482f.png)

**Comment by xmonader** [comment]
https://github.com/threefoldtech/tfgateway/issues/48

**Comment by xmonader** [comment]
closing in favor of the other issues
