### ISSUE TITLE
chat has ended shows up if you don't press next in the last step when you come back to the chatflow

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#177]
chat has ended shows up if you don't press next in the last step when you come back to the chatflow, because the session still exists and the last step "chat has ended" is still to be show

![image](https://user-images.githubusercontent.com/64129/86529103-2bffe900-beae-11ea-88ec-995cad529cf8.png)

**Comment by grimpy** [comment]
@xmonader any suggestion how to solve this? Cause the chatflow engine does not know when the last step is the last step. unless we enforce the chatflows to indicate this somehow.

**Comment by xmonader** [comment]
Hmm I think the chatflow_step decorator we can have last=True maybe and if we are that point we invalidate the session?

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
