### ISSUE TITLE
Unkown network in navigation header

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#1779]
I am on devnet network but it does not recognise this. Is this intended?

![Screenshot from 2020-12-03 09-52-23](https://user-images.githubusercontent.com/17138347/100986325-559c6980-354d-11eb-95c8-d5fef002f195.png)

**Comment by xmonader** [comment]
Probably should support it too

**Comment by xmonader** [comment]
there you go 
![image](https://user-images.githubusercontent.com/64129/103024568-c6d1aa00-4558-11eb-971d-3037f4536632.png)

f29eb1707a75648b733e41b928eea896dc674f9c
