### ISSUE TITLE
polls: if user already voted show an option to just see the results

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#178]
polls: if user already voted show an option to just see the results instead of having to go through the whole thing all over again

**Comment by ashraffouda** [comment]
verifying

**Comment by ashraffouda** [comment]
Not working at all 
![Screenshot from 2020-07-06 18-47-42](https://user-images.githubusercontent.com/1689456/86618808-d153b380-bfb9-11ea-9314-e707fa9da93a.png)
![Screenshot from 2020-07-06 18-52-40](https://user-images.githubusercontent.com/1689456/86618883-ef211880-bfb9-11ea-90b1-72e573c3e34c.png)

**Comment by xmonader** [comment]
i think that's because you don't have a polls_receive wallet 

can you check this document please? https://github.com/threefoldfoundation/tfta-trader/blob/master/docs/quickstart.md

**Comment by ashraffouda** [comment]
yes, turned out I don't have this wallet
