### ISSUE TITLE
failed to verify customer signature

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/js-sdk#1789]
i get this error when i try to deploy Kubernetes

![image](https://user-images.githubusercontent.com/31102305/101287052-aa164200-37f6-11eb-945e-f7a4bda82909.png)

![image](https://user-images.githubusercontent.com/31102305/101287024-88b55600-37f6-11eb-8b8e-d4c0b56f79f6.png)

 health checks
![image](https://user-images.githubusercontent.com/31102305/101287082-cdd98800-37f6-11eb-93da-9b95f2284597.png)

**Comment by xmonader** [comment]
on which branch?

**Comment by mhost39** [comment]
In development branch

**Comment by xmonader** [comment]
should be fixed after this merge please retry https://github.com/threefoldtech/js-sdk/pull/1852

**Comment by mhost39** [comment]
branch: development
commit: c86d0d9edbcb08d93aab473afefb58d529a3f644
![image](https://user-images.githubusercontent.com/31102305/102345708-77aed680-3fa6-11eb-8e81-d2d31b2a2859.png)
