### ISSUE TITLE
stop threebot server doesn't kill the redis server in tmux

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#179]
I tried to stop the running threebot server but it didn't stop the redis server and it hangs for a while then crash 
![image](https://user-images.githubusercontent.com/46320202/86530004-4db09e80-beb5-11ea-8a45-d3471aa57a89.png)

I have to kill it manually from tmux

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
