### ISSUE TITLE
Change 3bot deployer text

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#1790]
When you want to deploy a 3Bot on mainnet a user might confuse it with deploying on testnet because of the following text:
https://deploy3bot.grid.tf/threebot_deployer/#/

`Would you like to create a new 3Bot instance, or import one from testnet?`

I suggest we change to: 

`Would you like to create a new 3Bot instance? You can also choose to import a previously created 3Bot from the testnet network`

Or something similar :)

SAME for testnet deployer: https://deploy3bot.testnet.grid.tf/threebot_deployer/#/

from

`Would you like to create a new 3Bot instance, or import one from mainnet?`

to 

`Would you like to create a new 3Bot instance? You can also choose to import a previously created 3Bot from the mainnet network`

**Comment by robvanmieghem** [comment]
I suggest to drop the import from another network functionality. Testnet is testnet and not a staging environment
