### ISSUE TITLE
Cannot pay for 3bot: destination account does not exists

### ISSUE THREAD

**Issue by nbabenko** [threefoldtech/js-sdk#1791]
### Description

Reproduce steps:
- Find existing non-active 3bot.
- Try to restart it.
- Get to payment step
- Try to pay for the capacity
Result: Destination account does not exists error. 
See attached screenshots

### Version information

* 3bot name: nick3bot
* payment details:
Destination Wallet Address:
GCJUGKDDHJ2XQAZNT5R2YN7QCBXUQ4SWA526G36XVSGEEGWHNI5RFXH4
Currency:
TFT
Memo Text (Reservation ID):
p-6686
Total Amount:
47.329758 TFT

![photo_2020-12-08_11-25-20](https://user-images.githubusercontent.com/4426772/101465181-4dc33780-3948-11eb-8e60-6c19e0c7fb8d.jpg)
<img width="1040" alt="Screenshot 2020-12-08 at 11 20 50" src="https://user-images.githubusercontent.com/4426772/101465186-4ef46480-3948-11eb-81cd-0640dbec2dcb.png">

**Comment by xmonader** [comment]
you're paying for a testnet address with mainnet wallet

**Comment by nbabenko** [comment]
sorry, closing the bug
