### ISSUE TITLE
Duplicate network solution after deployed a network and go to deploy ubuntu solution

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/js-sdk#18]
network I created reservation id: `461551`
the duplicated one id: `461552`

![image](https://user-images.githubusercontent.com/36021484/84807392-74db2500-b007-11ea-9f84-585f4a2fc04a.png)

**Comment by m-motawea** [comment]
fixed in commit: https://github.com/threefoldtech/js-sdk/commit/471d5d340c71c54b4f8cdcb535ba74d10da713d3

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
