### ISSUE TITLE
Drop the "Create testnet funded wallet" from the dashboard

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#1800]
### Description

1. It's available on mainnet and it does not make sense there
2. Let's keep testnet and mainnet functionality in sync
![Screenshot 2020-12-08 at 09 30 03](https://user-images.githubusercontent.com/3511318/101602755-def4e580-39fe-11eb-9d93-c1493731a735.png)

**Comment by xmonader** [comment]
3bot can be used to target testnet if needed, there's nothing preventing creating, e.g from my development 3bot which is on mainnet I can run test scripts that executes against testnet tokens

**Comment by robvanmieghem** [comment]
Ok but this does not mean that a big button should be there for every user, KeepIt Simple, normal users don't need this. 
A second reason is that testnet has limited  capacity, there are thoughts ( there was a  story on the circles tool) to prevent users from getting too much testnet TFT's in order t keep testnet functional.

**Comment by despiegk** [comment]
@xmonader please keep it simple,
if I am on prod net, I do not have to know anything about testnet
if I am on testnet, I do not have to know anything about prodnet

should be that simple

**Comment by despiegk** [comment]
I agree with rob, needs to be more easy
