### ISSUE TITLE
Deployed workloads page loading takes verry long time

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#1814]
In case you have many workloads it takes around 5 mins

**Comment by waleedhammam** [comment]
explorer dependent: https://github.com/threefoldtech/js-sdk/blob/eaea15f5b889248a1f6b0380568deb068422d167/jumpscale%2Fpackages%2Ftfgrid_solutions%2Factors%2Fsolutions.py#L15

**Comment by waleedhammam** [comment]
we can use: https://dev.to/instantwebtoolsnet/datatables-with-vuejs-vuetify-pagination-rest-api-3jji

pagination in explorer can be done using the list function

example:

curl -vvvv https://explorer.grid.tf/api/v1/reservations/workloads\?customer_tid\=151\&page\=1

no of pages are in the headers

**Comment by MElborolossy** [comment]
Verified
Load all workloads and the UI around 11 sec 
![Screenshot from 2021-01-14 09-29-40](https://user-images.githubusercontent.com/11272864/104559630-53015980-564d-11eb-9e11-e6678421a508.png)
