### ISSUE TITLE
Billing Service

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#1816]
### Description

we need to have a separate billing service that other packages and chatflows can use.

### Implementation

1- it has one background service
2- a payment is submitted to it with the memo text and the wallet that expects the payment and the amount and represented by an id (stored in the billing service) and return a payment id
3- chatflows can wait on a payment using its id
4- billing service refunds incomplete, diff and timedout payments

**Comment by m-motawea** [comment]
PR: https://github.com/threefoldtech/js-sdk/pull/1828

**Comment by waleedhammam** [comment]
verified on devnet/testnet
works like expected

some logs from payments

![Screenshot from 2021-01-20 10-53-23](https://user-images.githubusercontent.com/10658229/105150689-c1db2880-5b0d-11eb-8c32-727f8a6aef94.png)
