### ISSUE TITLE
Secret appear in chatflow with Kubernetes and S3 solutions

### ISSUE THREAD

**Issue by MElborolossy** [threefoldtech/js-sdk#1819]
### Description

At Kubernetes and S3 solutions
While deployment, Chatflow ask for secret, this field must be hidden as password, but It appears as a normal text.

### Screenshots
![Kubernetes_secret](https://user-images.githubusercontent.com/11272864/101792240-26699780-3b0d-11eb-9ae7-4c1ee08edf7d.png)
![S3_Secret](https://user-images.githubusercontent.com/11272864/101792244-28335b00-3b0d-11eb-9d8e-e7518f4f373a.png)

**Comment by AhmedHanafy725** [comment]
**Verified**
**Branch:** development
**Commit:** 15b1315e09297446a4cdada8a3a181c24db45d39

![image](https://user-images.githubusercontent.com/41957921/107244482-ba38e080-6a36-11eb-832d-ec5fe7d5e02c.png)

![image](https://user-images.githubusercontent.com/41957921/107244502-befd9480-6a36-11eb-92d9-5d643446bcb7.png)
