### ISSUE TITLE
A 3bot name of a failed deployment is not reusable

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#1820]
### Description

When creating a 3bot and the deployment fails, the name chosen first is not reusable.
I suggest to initiate the identity first with a short time to live and it is confirmed by the 3bot itself.

**Comment by xmonader** [comment]
> ### Description
> When creating a 3bot and the deployment fails, the name chosen first is not reusable.
> I suggest to initiate the identity first with a short time to live and it is confirmed by the 3bot itself.

I'm not sure I'm familiar with a short-living identity, 3bot needs an identity that is used to sign the workloads e.g the network, the pools for the 3bot to own them, and there's no ownership transfer of workloads nor pools. so having that identity is definitely needed.

I think it's a different bug, the record of that solution of the USER_THREEBOT model should have been deleted if you're facing that situation and not able to use the same name for the failing deployment

**Comment by robvanmieghem** [comment]
>'m not sure I'm familiar with a short-living identity

That does not exist yet. Of course we can delete the identity if the process fails but if something unforeseen happens we end up in the same situation.

**Comment by xmonader** [comment]
> > 'm not sure I'm familiar with a short-living identity
> 
> That does not exist yet. Of course we can delete the identity if the process fails but if something unforeseen happens we end up in the same situation.

We can't delete identities from the explorer https://github.com/threefoldtech/tfexplorer/blob/master/pkg/phonebook/user.go

**Comment by robvanmieghem** [comment]
reopening since it the problem is not solved, putting it on the later milestone

**Comment by ramezsaeed** [comment]
![Screenshot from 2021-05-19 15-38-59](https://user-images.githubusercontent.com/16083592/118824289-05765100-b8ba-11eb-984b-8ad34fd12711.png)

I was creating a new 3bot with name "ramez" via https://deploy3bot.testnet.grid.tf
and it failed with this screenshot

![Screenshot from 2021-05-19 15-43-29](https://user-images.githubusercontent.com/16083592/118824311-0ad39b80-b8ba-11eb-96a0-04234055ea44.png)

now when I try to refresh and create again
it says that there is a 3bot with name "ramez" already exists and I cant use the same name again !!

![Screenshot from 2021-05-19 15-46-10](https://user-images.githubusercontent.com/16083592/118824345-12934000-b8ba-11eb-991f-f89881db3ad5.png)
And nothing shown in 3bot list
