### ISSUE TITLE
New wallet should not be available on the main 3bot dashboard page

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#1823]
Wallets are not even shown there so just remove that New Wallet button there
![Screenshot 2020-12-08 at 09 52 15](https://user-images.githubusercontent.com/3511318/101882867-c1f31a80-3b96-11eb-8d84-4f542a6d4e24.png)

**Comment by xmonader** [comment]
These are shortcuts to the most common functionality in the dashboard, e.g going to settings, adding new admin, creating a wallet

**Comment by robvanmieghem** [comment]
Creating a wallet is not a common or everyday thing to do, this way we invite people to just click on it without actually knowing what they do( this is how humans work).
As mentioned above you don't even see the existing wallets there so how can someone decide if he/she needs another one?
On top of that, deleting a wallet just removes it from the model, no decent cleanup is done and we are funding everything and it is an operational issue if the activation wallet is drained.
