### ISSUE TITLE
Farm mgmt in main 3bot menu while irrelevant for non farmers

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#1824]
### Description
![Screenshot 2020-12-08 at 09 50 46](https://user-images.githubusercontent.com/3511318/101883657-d7b50f80-3b97-11eb-81fd-93fd3cc3516a.png)

If the farm mgmt package is not installed, the "Farm management" menu item in the sidebar should not be visible, this only confuses normal 3bot users

**Comment by xmonader** [comment]
As a virtual system administrator, one of the main jobs on the grid is farm operations. Probably the farm mgmt should be installed by default, not removed from the mainmenu :)

**Comment by robvanmieghem** [comment]
This is only relevant for farm owners, a 3bot can do a lot more that managing a farm it, not just for farm owners, that would be the farmer 3bot

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/102718389-8cfe6a80-42f0-11eb-85d0-111f0cfeb1b0.png)

people will be able to go to it from the packages -> farm management -> the earth icon, however if they do so, it won't be `iframed` and will be opened away from the admin dashboard view, if that's the desired behavior -which imo no becaue all administrative packages should be seen from the dashboard- will remove it from the admin sidebar.

**Comment by robvanmieghem** [comment]
As discussed with Ahmed over zoom, Let's not show the menu-item if the package is not installed ( make the sidebar a bit more dynamic)

**Comment by xmonader** [comment]
On a fresh 3bot 
![image](https://user-images.githubusercontent.com/64129/103201681-2b925900-48f9-11eb-90ba-9ca32b8b5a12.png)


after installing farmmgmt
![image](https://user-images.githubusercontent.com/64129/103201736-4b298180-48f9-11eb-80a3-c547c68c81e3.png)
