### ISSUE TITLE
Extending a capacity pool  in a 3bot is too complex

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#1825]
When creating you have plans. If I just want to extend the pool to keep my 3bot alive for a while longer, I have no clue whatsoever what to put in those fields. It my be appropriate for power users but currently having this detailed form is just too complex for normal users.

![Screenshot 2020-12-08 at 09 47 17](https://user-images.githubusercontent.com/3511318/101886148-637c6b00-3b9b-11eb-9593-13f39a79ca09.png)

**Comment by xmonader** [comment]
for extending the 3bot as long as you have money in your wallets the auto-extend service will take care of it without the user intervention. 
This is not related to the 3bot, the capacity pool concept isn't related to the 3bot or any specific solutions, it happens the 3bot as a solution runs on a capacity pool, the user needs to make
sure there's CUs, SUs in the pool to keep the resources deployed on the pool (3bot or not) alive.
