### ISSUE TITLE
typo in 3bot deployer

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#1826]
![Screenshot 2020-12-08 at 09 20 25](https://user-images.githubusercontent.com/3511318/101887177-c8849080-3b9c-11eb-95ed-1f3874ce9ee4.png)
Please change it in "Waiting for provisioning of resources" or "Waiting for resource provisioning"

**Comment by waleedhammam** [comment]
>  or "Waiting for resource provisioning"

but they are actually more than a resource, specially in network resources

**Comment by rkhamis** [comment]
waiting on resource provisioning works better
