### ISSUE TITLE
Update Threebot Deployer to calculate cloud units from explorer client

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#1827]
example calculation

```python
cont1 = Container()
cont1.capacity.cpu = MINIO_CPU
cont1.capacity.memory = MINIO_MEMORY
cont1.capacity.disk_size = 256
cont1.capacity.disk_type = DiskType.SSD
cloud_units = cont1.resource_units().cloud_units()
print(w.id, w.info.workload_type, "cu: ", cloud_units.cu, "su: ", cloud_units.su, "ipv4u: ", cloud_units.ipv4u)
```

**Comment by waleedhammam** [comment]
check https://github.com/threefoldtech/js-sdk/issues/1751

**Comment by waleedhammam** [comment]
making use of container methods gives 0 values, investigating why

**Comment by AhmedHanafy725** [comment]
![image](https://user-images.githubusercontent.com/41957921/105058525-fc49b480-5a7e-11eb-875b-7240c31c5e97.png)

![image](https://user-images.githubusercontent.com/41957921/105058552-0370c280-5a7f-11eb-8437-08ba4f8b60ce.png)

![image](https://user-images.githubusercontent.com/41957921/105058678-23a08180-5a7f-11eb-8fce-6fe6e8f3c76f.png)


**verified**
