### ISSUE TITLE
3bot admin: Allow more sizes for kubernetes solution 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1836]
right now the allowed sizes are just 

```
        sizes = ["1 vCPU 2 GiB ram 50GiB disk space", "2 vCPUs 4 GiB ram 100GiB disk space"]

```
https://github.com/threefoldtech/js-sdk/blob/29173f54bd5b1844c1c7954e48917a576aab4697/jumpscale%2Fpackages%2Ftfgrid_solutions%2Fchats%2Fkubernetes.py#L45

while we have 17 different sizes for  k8s

**Comment by RafyAmgadBenjamin** [comment]
![Uploading image.png…]()

**Comment by RafyAmgadBenjamin** [comment]
Done 
### Branch 
`development_vdc_kube`
### PR
https://github.com/threefoldtech/js-sdk/pull/2447

**Comment by hossnys** [comment]
verified 

![Screenshot from 2021-02-23 19-24-44](https://user-images.githubusercontent.com/26298009/108882295-e8104e80-760c-11eb-9a86-d2fdb2f15421.png)
![Screenshot from 2021-02-23 19-24-59](https://user-images.githubusercontent.com/26298009/108882304-eba3d580-760c-11eb-80cb-8e7b612ee652.png)
