### ISSUE TITLE
Can't add another identity

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#1837]
https://youtu.be/hEVynYG1r8A

**Comment by xmonader** [comment]
To create a new identity it requires 
1- the display name (that will get used in the dashboard)
2- threebot name 
3- email 
4- words (that you can generate) if you don't a have a record already.

**Comment by mhost39** [comment]
the first time i add a identity it work fine but when i close and try to add again can't access input filed for 3bot name, email and words
https://user-images.githubusercontent.com/31102305/103554374-8149a100-4eb7-11eb-85d5-f1f07aec1078.mp4

**Comment by waleedhammam** [comment]
verified

![Screenshot from 2021-01-12 11-13-25](https://user-images.githubusercontent.com/10658229/104293875-34715600-54c7-11eb-9478-e80d05190f5f.png)
