### ISSUE TITLE
Seeing farms from different networks

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#1838]
My 3bot connected to testnet, seeing a farm from another user on another network!

![Screenshot from 2020-12-15 10-59-23](https://user-images.githubusercontent.com/17138347/102200080-aa809e00-3ec4-11eb-9984-303babc39ac2.png)

farm shown: https://explorer.grid.tf/explorer/farms/173667
user linked: https://explorer.grid.tf/explorer/users/197

**Comment by DylanVerstraete** [comment]
this is after you switch identities from mainnet to testnet. The thing here is that my identity on testnet is ID 197 and this other guys MAINNET ID is 197. So that is why I see his farms, but I should see my farm from testnet.

**Comment by xmonader** [comment]
It's caused by the _explorer attribute in the farmmgmt actor, moved it to a property to get reflected everytime
