### ISSUE TITLE
failed in extent pool

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/js-sdk#1846]
I created a capacity pool with:
CU = 1, SU = 1, duration unit = Day and Time to live = 1
![image](https://user-images.githubusercontent.com/31102305/102216674-2d652100-3ee4-11eb-946f-adc9aa02057e.png)

it's created with this resource:
CU = 86400 and SU = 86400

after that i try to extend this pool with:
CU = 1, SU = 2, duration unit = Day and Time to live = 2
![image](https://user-images.githubusercontent.com/31102305/102216989-9ea4d400-3ee4-11eb-9a9f-69b33cc967dd.png)

calculate cu and su after extent should be:
        calculated_cu = (1 + 1) * 2 * 60 * 60 * 24 = 345600
        calculated_su = (2 + 1) * 2 * 60 * 60 * 24 = 518400

but i get:
CU = 259200
SU = 432000

pool ID: 7000

**Comment by m-motawea** [comment]
your calculation is incorrect

extension should be
cu = (1 * 1 * 60 * 60 * 24) + (2 * 1 * 60 * 60 * 24) 
su = (1 * 1 * 60 * 60 * 24) + (2 * 2 * 60 * 60 * 24)
