### ISSUE TITLE
chatflow icon doesn't show on firefox browser in the installed packages in packages page 

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/js-sdk#1847]
![Screenshot from 2020-12-15 16-26-53](https://user-images.githubusercontent.com/26298009/102227568-63a99d00-3ef2-11eb-9a0c-352c23045853.png)

![Screenshot from 2020-12-15 16-21-54](https://user-images.githubusercontent.com/26298009/102227632-77550380-3ef2-11eb-85b4-7ca561e7879c.png)

**Comment by waleedhammam** [comment]
blocked on: https://github.com/threefoldtech/3Bot_connect/issues/178

**Comment by xmonader** [comment]
same on vivaldi/chrome
![image](https://user-images.githubusercontent.com/64129/103099137-f0044000-4615-11eb-86a7-fbb9872307d2.png)
