### ISSUE TITLE
Capacity Pool not extended after payment made 

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/js-sdk#1855]
We extended our capacity pool and also made the payment and got the chatflow success message , but when we see on the Dashboard it is not extended and also when making a Kubernetes Cluster , it does not appear in the Pools Available list:

This is the capacity pool:

![image](https://user-images.githubusercontent.com/25789724/102322389-6e1e7200-3f98-11eb-97b4-fc4f364e1289.png)

As you see there is no expiration time here or compute units  , we had specified 1 month.

In Kubernetes Solutions , our extended Pool does not appear also

![image](https://user-images.githubusercontent.com/25789724/102322543-a920a580-3f98-11eb-8894-7158bccc0ad6.png)

In the logs there is no ERROR reported.

In the Deployed workloads we see that the required Network Resources were indeed being deployed:

![image](https://user-images.githubusercontent.com/25789724/102322864-2cda9200-3f99-11eb-805c-9f4858412797.png)

**Comment by OmarElawady** [comment]
I can see the mentioned pool [here](https://explorer.grid.tf/api/v1/reservations/pools/929). It indeed doesn't have any cus but it has sus.

Can you please add more info to help investigate the issue regarding:
1. How many CUs and SUs did you choose when extending?
2. What is the amount of money you paid to extend it? You can see the transaction of you wallet in jsng using `j.clients.stellar.YOURWALLETNAME.list_transactions()`

**Comment by siddiquagig** [comment]
@OmarElawady , i chose 4 CUs and 4 SUs when extending  and i paid 1488 :


![image](https://user-images.githubusercontent.com/25789724/102467776-1ea87680-406a-11eb-8227-69f84051fecd.png)


I  also choose duration unit as 1 Month but i cannot see any expiry time in the dashboard too.

**Comment by OmarElawady** [comment]
The transaction succeeded with the same amount and it can be listed [here](https://stellarchain.io/tx/3c4c49f9ec73967f8a0244025dfa654bf7cb465e7a31c977bee7b5d9659e4b6a), but the money is still in this [wallet](https://stellarchain.io/address/GDEVKJUMTBNDPOD3B4TOKU5TTNVAG3F7362HKFIBES52W3FQEXG5TFCS), which means it didn't get transferred to the farmer's wallet.

**Comment by muhamadazmy** [comment]
is it possible that you waited for a long time before making the transaction ? Like u went to have lunch or coffee ? just wondering.

I am asking because the only way your transaction to get marked as 'canceled' on the system without a refund is that the transaction has been already set to canceled THEN you made the transaction.

**Comment by muhamadazmy** [comment]
I set "manually" the expiration date of your reservation to 1 more hour in the future and the payment got processed. Can u please check that the pool has been updated with correct capacity ?

**Comment by xmonader** [comment]
@siddiquagig close please if your problem is resolved.

**Comment by siddiquagig** [comment]
Yes indeed , it is solved now , and i waited for like an hour on the payment screen , was waiting for the tokens to be sent to my wallet and then make the payment.

![image](https://user-images.githubusercontent.com/25789724/102746206-36883f00-4377-11eb-8863-8d3500933171.png)
