### ISSUE TITLE
Error message when deploying flists (ubuntu) while flist does get deployed and operates as expected

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#1875]
## Description
Used online 3bot to deploy ubuntu flist (version 20) and manually selected node to deploy on.  Deployment is functional (see screenshot) but does present an error message.  repeated the process twice (same everything, including farm etc) and got the same response.

![image](https://user-images.githubusercontent.com/13766992/102170642-43f08580-3eae-11eb-807c-df9551bb8744.png)

**Comment by waleedhammam** [comment]
@muhamadazmy seems it's the same here

**Comment by waleedhammam** [comment]
Verified after merging the TRC container with 3Bot flist
