### ISSUE TITLE
Wizard does not progress to the next step

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#1876]
Wizard (deploy ubuntu) dos now progress to the best step.  Keep on waiting but if you do a forced page reload it already is at the next step.

![image](https://user-images.githubusercontent.com/13766992/102171157-561ef380-3eaf-11eb-83ca-d99a82879d15.png)

After forced page reload:

![image](https://user-images.githubusercontent.com/13766992/102171262-8e263680-3eaf-11eb-8b0f-0c1faab2e43d.png)

**Comment by waleedhammam** [comment]
@weynandkuijpers The chatflow didn't lose it's state, so maybe your network connection had a lag at that time ?

**Comment by m-motawea** [comment]
verified
