### ISSUE TITLE
Couldn't register new identities with given name Friedger_friedger

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1877]
the UI just froze didn't kept stuck on the location policy and when I got into the server I found out 

![image](https://user-images.githubusercontent.com/64129/102708706-18eea300-42ad-11eb-981e-969e63888488.png)

and the UI didn't show any relevant errors.

**Comment by waleedhammam** [comment]
did you register on TF connect app with capital case username ? 
i see: https://explorer.testnet.grid.tf/api/v1/users?name=Friedger.3bot
but it should be: https://explorer.testnet.grid.tf/api/v1/users?name=friedger.3bot
can you show us screenshot from your TF connect app, settings pane ?

**Comment by xmonader** [comment]
https://github.com/threefoldtech/js-sdk/pull/1886
