### ISSUE TITLE
3botdeployer on testnet: no date accepted 

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#1878]
Whatever date/hour I introduce to deploy a 3bot on testnet, I always get an error that date must be at least 19 minutes in the future. 
![C7A90C0B-77AA-444B-A56C-D48C6B1D8798](https://user-images.githubusercontent.com/30384423/102661017-51db2a80-417c-11eb-8a34-3536e0e23f89.png)

**Comment by waleedhammam** [comment]
> Whatever date/hour I introduce to deploy a 3bot on testnet, I always get an error that date must be at least 19 minutes in the future.
> ![C7A90C0B-77AA-444B-A56C-D48C6B1D8798](https://user-images.githubusercontent.com/30384423/102661017-51db2a80-417c-11eb-8a34-3536e0e23f89.png)

What browser version are you using ?

**Comment by gmachtel** [comment]
This one was on Safari. I'll try with another browser.

**Comment by waleedhammam** [comment]
related to: https://github.com/threefoldtech/js-sdk/issues/1581
