### ISSUE TITLE
No available farms with enough resources

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/js-sdk#1896]
in branch development 
can't create a 3bot
![image](https://user-images.githubusercontent.com/31102305/102802231-02d10780-43bf-11eb-9e78-d418716e38e2.png)

**Comment by waleedhammam** [comment]
Can you try again ? :')

**Comment by mhost39** [comment]
![image](https://user-images.githubusercontent.com/31102305/103038008-f0e59500-4575-11eb-973b-b183c5b9e623.png)
