### ISSUE TITLE
if you delete a corrupted package or doesn't exist, it'll fail

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#19]
if you delete a corrupted package or doesn't exist, it'll fail

![Screenshot from 2020-06-08 10-44-41](https://user-images.githubusercontent.com/10658229/84010584-25e12000-a975-11ea-9573-473685dce0fb.png)

**Comment by BolaNasr** [comment]
PR: https://github.com/threefoldtech/js-sdk/pull/378

**Comment by BolaNasr** [comment]
Commit: https://github.com/threefoldtech/js-sdk/commit/48c92eb9f591672e3e4976e921022235e8ccdd56

**Comment by Dina-Abd-Elrahman** [comment]
- verified
