### ISSUE TITLE
3bot restore (mainnet) fails and 3bot deploy on testnet unreachable

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#1907]
My 3bot has timed out (end of october) and when I try to restore (I remember 3bot name and password)

## Maininet
- in the whole process the chatwizard does not progress at places, and when I reload the page steps have completed and succeeded.
- refunded the mainnet 3bot successfully but cannot access it through the public URL:
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/13766992/97798468-d19a4d80-1c3f-11eb-9664-493470af24e9.png">
- Mainnet 3bot [URL](https://weynandkuijpers-threebot-webbotje01.tfgw-prod-06.ava.tf/admin)

## Testnet
- same issue with chatwizard no progressing on testnet and when reloaded page process is finished (successful?)
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/13766992/97798509-21791480-1c40-11eb-8868-4993df87740b.png">
- same issue as on mainnet -> cannot connect / access the 3bot.
- Testnet [URL](https://weynandkuijpers01-threebot-webbotjetoo.tfgw-testnet-01.3x0.me/admin)

Not sure but seems to be an access issue.

**Comment by waleedhammam** [comment]
there shouldn't be networking issues after :https://github.com/threefoldtech/js-sdk/pull/1947

**Comment by waleedhammam** [comment]
Verified
