### ISSUE TITLE
vdc backup flow

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1919]
should work on 
- the user 3bot we deploy on the private k8s
- on the kube controller (there're no data to actually backup, it is stateless)

# questions:
How will the user restore k8s controller backup and what is actually backup on the controller? note: can't deploy the controller on a different node because it's ip is already configured in workers) auto backup of 3bot & kubernetes controller config to our backup destination

**Comment by waleedhammam** [comment]
blocked on: https://github.com/threefoldtech/zos/issues/1161

**Comment by xmonader** [comment]
## velero option
currently using velero to backup & restore the resources but below are some points to discuss:
- backup all deployments or the marketplace solutions only (requires a selector on each) 
- should we backup the volumes or not? (NOTE: hostPath volumes are not supported but local volumes can be restored) 
- for the backup storage should  the user get an external S3 or we should deploy one for them. (NOTE: velero shares the S3 creds with the VDC) so it we can't have a global s3 for all of them, and  the user can also with some experience abuse it and where to host the S3? 

## k3s snapshots still blocked

**Comment by m-motawea** [comment]
normally the storage class used in k8s running on cloud providers is integrated with volumes and storage services of that cloud. which makes volumes backup and restoration using the backup services of the provider

**Comment by m-motawea** [comment]
Proposal (already have an implemntation in branch `development_vdc_backup`):
1- label all marketplace deployments with a specific label to be recognized by velero `backupType=vdc`

2- get s3 config to use with velero on deployment (either passed by a user or managed by us)

3- install velero on container startup, restore latest backup on the specified s3 config (if exists)

4- add a backup schedule for marketplace deployments every 24 hours (on container startup as well)

5- a service running in the background (every 5 minutes) that validates the subdomains of marketplace are actually deployed and point to the vdc public ip. this will recreate the subdomains that were used in the deployments that were restored

**Comment by m-motawea** [comment]
went with s3 based backup as a required form (for now) as per the above proposal for vdc marketplace solutions + ALL configmaps and secrets

**Comment by waleedhammam** [comment]
closed in favor of etcd backup
