### ISSUE TITLE
monitoring vdcs using prometheus and grafana

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#1921]
prometheus helm chart: https://github.com/threefoldtech/vdc/issues/21

deploy a monitoring stack to monitor k8s and s3 in each vdc

**Comment by RafyAmgadBenjamin** [comment]
we are working on the chat flow 
we have done:
- Issue master node size (tested tainted then change size)
- we have tested Prometheus and Grafana
-  We got an issue related to `tls` scope, it needs to be global to work with sub-charts
- Minor fixes in the chart

we need to do:
- disable Grafana to test https on promethious to make sure if related to gateway timeout or not 
- find a way if we can monitor minio
- Document the monitor stack

**Comment by sasha-astiadi** [comment]
i need estimation as this is one of the last issues @xmonader how many hours / day of work ? @xmonader @RafyAmgadBenjamin

**Comment by RafyAmgadBenjamin** [comment]
Done on `development_vdc_monitorstack`
#### PR
https://github.com/threefoldtech/js-sdk/pull/2114

**Comment by xmonader** [comment]
verified :)
