### ISSUE TITLE
VDC logo

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1922]
![image](https://user-images.githubusercontent.com/64129/101491325-4877e400-396c-11eb-9063-18b446377299.png)

![image](https://user-images.githubusercontent.com/64129/101491478-79f0af80-396c-11eb-96ae-6abdddf55fd4.png)

the logo looks like a 3bot logo? we need to have a more appropriate one

**Comment by ehab-hassan** [comment]
![vdc](https://user-images.githubusercontent.com/10484295/103378100-e123fe80-4ae9-11eb-92d9-2f31db82114d.png)
![vdc-white](https://user-images.githubusercontent.com/10484295/103378149-0b75bc00-4aea-11eb-94cb-07686ae00bad.png)
