### ISSUE TITLE
 VDC technical documentation on repo

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1924]
should cover
- [x] [deployment](https://github.com/threefoldtech/js-sdk/pull/2830) @m-motawea @waleedhammam @AhmedHanafy725 
- [x] what's need on the grid network to be VDC capacity provider (resources, ips.. etc) @m-motawea @AhmedHanafy725 
- [x] billing @dmahmouali @MElborolossy @OmarElawady 
- [x] marketplace/vdc-dashboard @ranatrk @dmahmouali @samaradel 
- [x] solutions development: how to develop a new solution for the vdc, should cover all aspets including repo, forking, pipeline, threefold connect, vdc integration @ashraffouda @RafyAmgadBenjamin @sameh-farouk 
- [x] ingress related info @OmarElawady @AhmedHanafy725 @everyone

**Comment by waleedhammam** [comment]
Working on deployment

**Comment by xmonader** [comment]
the special info about traefik ingress (tcp forwarding) is documented here https://github.com/threefoldtech/js-sdk/blob/development/docs/vdc/tcpforwarding.md

**Comment by RafyAmgadBenjamin** [comment]
we have done this part

> solutions development: how to develop a new solution for the vdc, should cover all aspets including repo, forking, pipeline, threefold connect, vdc integration

PR
https://github.com/threefoldtech/js-sdk/pull/2864

**Comment by xmonader** [comment]
let's make sure to continuously improve it. thank you everyone
