### ISSUE TITLE
VDC Pricing Does Not Match Resource

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#1925]
the smallest flavor of the vdc `Silver` which costs 10 EUR ~= 364 TFT consumes much more resources than what can be bought with this price.

the initial deployment includes the below workloads:
```python
JS-NG> for w in workloads:
     2     cloud_units = w.resource_units().cloud_units()
     3     print(w.id, w.info.workload_type, "cu: ", cloud_units.cu, "su: ", cloud_units.su, "ipv4u: ", c
...    loud_units.ipv4u)
516768 WorkloadType.Zdb cu:  0.0 su:  0.008 ipv4u:  0.0
516769 WorkloadType.Zdb cu:  0.0 su:  0.008 ipv4u:  0.0
516765 WorkloadType.Zdb cu:  0.0 su:  0.008 ipv4u:  0.0
516764 WorkloadType.Zdb cu:  0.0 su:  0.008 ipv4u:  0.0
516763 WorkloadType.Zdb cu:  0.0 su:  0.008 ipv4u:  0.0
516771 WorkloadType.Zdb cu:  0.0 su:  0.008 ipv4u:  0.0
516770 WorkloadType.Zdb cu:  0.0 su:  0.008 ipv4u:  0.0
516762 WorkloadType.Zdb cu:  0.0 su:  0.008 ipv4u:  0.0
516767 WorkloadType.Zdb cu:  0.0 su:  0.008 ipv4u:  0.0
516766 WorkloadType.Zdb cu:  0.0 su:  0.008 ipv4u:  0.0
516807 WorkloadType.Public_IP cu:  0.0 su:  0.0 ipv4u:  1.0
516810 WorkloadType.Kubernetes cu:  0.5 su:  0.083 ipv4u:  0.0
516836 WorkloadType.Kubernetes cu:  0.5 su:  0.083 ipv4u:  0.0
516837 WorkloadType.Volume cu:  0.0 su:  0.007 ipv4u:  0.0
516838 WorkloadType.Container cu:  0.5 su:  0.0 ipv4u:  0.0
516853 WorkloadType.Container cu:  0.5 su:  0.0 ipv4u:  0.0
JS-NG> 

```

these workloads consume resource with cost ~= 780 TFT per month

Note: all zdbs are using HDD and the initial deployment gives the user 60 GB of usable S3 storage (6 + 4) which means it can scale up to use 140 GB total storage when it reaches the 100 GB specified in the plan

**Comment by xmonader** [comment]
@weynandkuijpers

we made plans info dynamic to be easily updated: 
plans: https://github.com/threefoldfoundation/vdc_pricing/blob/master/plans.json
workloads https://github.com/threefoldfoundation/vdc_pricing/blob/master/workload_sizes.json

+  a 3bot container  cru=1, mru=1, disk=2GB  SSD

**Comment by weynandkuijpers** [comment]
Issue resolved.

**Comment by despiegk** [comment]
this was all wrong, we had 5 realities,

**Comment by xmonader** [comment]
## each plan has
1 kubernetes controller (1GB mem)
1 ingres network controller (1 IP address) = co-hosted with the kubernetes controller
eVDC controller (1GB mem) = your private 3bot for your management of your kubernetes env
X chosen CPU capacity (depending chosen package)
Y chosen STORAGE capacity

## plans

silver: 15 USD per month for 100GB storage + max 1 CU compute capacity (1 worker)
gold: 30 USD per month for max 2TB storage + max 2 CU compute capacity (1 worker)
platimum: 80 USD per month for max 10TB storage + max 4 CU compute capacity (2 workers)
diamond: 200 USD per month for max 10TB storage + max 16 CU compute capacity (4 workers)





##CALCULATIONS

CU = 2cpu, 4GB, 50GB storage 10USD
SU = 1TB storage  8 USD

0.00332 SU 1GB ssd  
0.0008   SU 1GB HDD

1 TB HDD = 0.82 SU
1 TB SSD =   3.4 SU

### k8s
0.25CU  = size 18 wokrer    -> {"cru": 1, "mru": 1, "sru": 25}
1 CU    = size 16 worker    -> {"cru": 2, "mru": 4, "sru": 50}
2 CU    = size 17 worker    -> {"cru": 4, "mru": 8, "sru": 50}
4 CU    = size 9 worker     -> {"cru": 8, "mru": 32, "sru": 100}



### BASE COST

controller: 0.25 cu 
3bot: 0.25 cu + 
1 ip: 1 ipu


### silver

- base: 0.5 cu + 1 ipu
- 100GB zdb = 0.08 su
- 1 worker = 1 CU
- worker +controller storage = 0.25su

min: 1.5 cu + 0.08+0.25su + 1pu  = 1.5 CU + 0.33 SU + 1ip
max: 1.5 cu + 0.08+0.25su + 1pu  = 1.5 CU + 0.33 SU + 1ip


### gold
- base: 0.5 cu + 1 ipu
- minzdb 100GB zdb = 0.08 su
- maxzdb 2TB = 1.65 su  
- 1 worker = 2 CU
- worker +controller storage = 0.25su

min: 2.5 cu + 0.08+0.25su + 1pu = 2.5 CU + 0.33 SU + 1ip
max: 2.5 cu + 1.65+0.25su + 1pu = 2.5 CU + 1.9 SU  + 1ip

### platinum
- base: 0.5 cu + 1 ipu
- minzdb 100GB zdb = 0.08 su
- maxzdb 10TB = 8 su
- 2  2CU worker => 4CU  
- worker + controller storage = 0.415 SU 

min: 4.5 cu + 0.08 su +0.415su + 1pu  = 4.5 CU + 0.495 SU + 1 ipu
max: 4.5 cu + 8 su +0.415su + 1pu     = 4.5 CU + 8.415 SU + 1 ipu

### diamond

### platinum
- base: 0.5 cu + 1 ipu
- minzdb 100GB zdb = 0.08 su
- maxzdb 10TB = 8 su
- 4  4CU worker => 16CU  
- worker + controller storage = 1.42 SU

min: 16.5 cu + 0.08 su +1.43 su + 1pu = 16.5 CU + 1.51 SU + 1pu
max: 16.5 cu + 8 su + 1.43 su  + 1pu = 16.5 CU + 9.43 SU + 1 ipu



silver:        0.08 SU zdb     + 1 CU + (75*0.00332 ) su  :  1.5 cu   + 0.25su k8s + 0.08su zdb
gold:         (0.82*2) SU  2TB zdb     + 2 CU   + (75*0.00332)su :  2.5 cu   + 0.25su k8s + 1.65su zdb 
platinum: ( 0.82*10 )SU zdb + 2 * 2 CU + (125*0.00332)su : 4.5 cu  + 0.415su k8s su + 8.2su zdb 
diamond: (0.82*10) SU zdb + 4 * 4 CU + (425*0.00332)su :  16.5 cu  + 1.42 k8s su  + 8.2su zdb

**Comment by xmonader** [comment]
won
