### ISSUE TITLE
as a user i want other users to login to my vdc solutions using 3bot id / tf connect

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#1928]
as a user i want other users to login to my vdc solutions using 3bot id / tf connect.

when I deploy a cryptpad, for example, as a user / admin, I would like to invite people to use my cryptpad as new users, but instead of signing up for cryptpad using cryptpad 'sign up' feature, user should just be asked to sign up with their 3bot connect authentication.

**Comment by xmonader** [comment]
closing in favor of https://github.com/threefoldtech/home/issues/1015
