### ISSUE TITLE
Diamond plan should come after Platinum plan

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#1930]
For normal prices of diamond and platinum, Diamond is more expensive than Platinum.

So I don't know why the Platinum comes after Diamond here

![image](https://user-images.githubusercontent.com/41957921/102357384-eb58df80-3fb6-11eb-9587-ae859a7fddb3.png)

**Comment by rkhamis** [comment]
agreed


however, i much prefer "Bronze, Silver, Gold, Platinum"

**Comment by ranatrk** [comment]
verifying
