### ISSUE TITLE
Add VDC wallet info to the VDC dashboard and the deployer

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/js-sdk#1931]
Allow the user to see the info of the prepaid wallet

**Comment by waleedhammam** [comment]
Verified on development_vdc

![Screenshot from 2021-01-12 11-08-21](https://user-images.githubusercontent.com/10658229/104293283-85347f00-54c6-11eb-9c87-dfd4374331e7.png)

![Screenshot from 2021-01-12 11-08-42](https://user-images.githubusercontent.com/10658229/104293308-8c5b8d00-54c6-11eb-93a5-6117e8fb998e.png)
