### ISSUE TITLE
Add monitoring stack to marketplace vdc

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#1933]
- Disable stack to be installed by default
-  Add it as a solution in marketplace

**Comment by m-motawea** [comment]
verified on development_vdc commit: https://github.com/threefoldtech/js-sdk/commit/825b0046f91dd4b43683fe21fc2f4fd900397f94

![image](https://user-images.githubusercontent.com/32568986/104325985-df970500-54f1-11eb-8102-e8e0acf13f69.png)


![image](https://user-images.githubusercontent.com/32568986/104326068-f50c2f00-54f1-11eb-9573-c6c305689937.png)


![image](https://user-images.githubusercontent.com/32568986/104326121-035a4b00-54f2-11eb-988c-4de7550f1cfb.png)
