### ISSUE TITLE
Get kubeapps.com to work with network nodes

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#1938]

**Comment by RafyAmgadBenjamin** [comment]
Done on branch `development_vdc_kubeapps`

- we deployed `kubeapps` on our gird
- we used `kubeapps` to install `MySQL chart` and it worked great

we are using the latest version of `kubernetes` so it is not totally compatible with all the charts in the `kubeapps`

**Comment by MElborolossy** [comment]
Verified

- Success Deployment
![image](https://user-images.githubusercontent.com/11272864/104457247-73c8a100-55b2-11eb-9854-a69c2020ff21.png)

- Kubeapp
![image](https://user-images.githubusercontent.com/11272864/104457192-601d3a80-55b2-11eb-9503-6a2f5be766f7.png)
