### ISSUE TITLE
typo in vdc storage nodes screen

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#1939]
### Description

Small type in the Storage node list. 
Title mentions "Expose Storgae Controller" i.o. "Expose Storage Controller"

<img width="1253" alt="Screenshot 2020-12-23 at 16 05 33" src="https://user-images.githubusercontent.com/30384423/103011862-ef4aab80-453a-11eb-8f6c-75370ce2aeed.png">

### Version information

* Browser: Chrome

**Comment by xmonader** [comment]
should be fixed in b2a8ddce4cd7ceecbe95eca10ebfadc9c1b117d0
