### ISSUE TITLE
s3 domain names

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#1959]
how is s3 going to be exposed?
options:
1- public IP (no valid cert)
2- expose using gateway (managed domains)

note aws uses this for s3 urls:
`https://s3.Region.amazonaws.com/bucket-name/key name`

**Comment by robvanmieghem** [comment]
@xmonader This is a won't fix probably, not a "Done" since S3 is no longer a required part of the vdc MVP

**Comment by xmonader** [comment]
> @xmonader This is a won't fix probably, not a "Done" since S3 is no longer a required part of the vdc MVP

Indeed, i'm cleaning up old/settled issues (y)
