### ISSUE TITLE
port admin panel [js-ng development_threebot_admin] [js-sdk development_adminpanel]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2]
- [x] system info, disk spaces, network 
 - [x] processes, memory usage, ports
 - [x] packages docs (docsify), opend as a single issue https://github.com/threefoldtech/js-sdk/issues/58
 - [x] alerts/logs 
 - [x] tfkwikis port (iframe)
 - [x] packages manager
 - [x] solutions framework (don't port jsx code yet) 
 - [x] wallet manager
 - [x] capacity (iframe)
 - [x] farmmanagment (full package)
 - [x] sdk examples? (no)
 - [x] codeserver iframe for codeserver proxy location (Defined in codeserver package)
 - [x] settings  (changing explorer net, add admins)

**Comment by hossnys** [comment]
verified
