### ISSUE TITLE
Poll package to setup the required wallet

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/js-sdk#200]
In poll package it crashes if there is no wallet called `polls_receive`
the package should create it in install step

**Comment by ashraffouda** [comment]
https://github.com/threefoldtech/js-sdk/commit/4d014e89d9ba40ba81722174ff9bfd40fa7565fb

**Comment by hossnys** [comment]
verified 
wallets before adding polls package :
![Screenshot from 2020-07-08 20-42-32](https://user-images.githubusercontent.com/26298009/86958044-dd777680-c15b-11ea-995c-f704f5873814.png)

wallets after adding polls package : 
![Screenshot from 2020-07-08 20-46-24](https://user-images.githubusercontent.com/26298009/86958096-eec08300-c15b-11ea-9d72-e748139806c8.png)
![Screenshot from 2020-07-08 20-46-38](https://user-images.githubusercontent.com/26298009/86958102-f122dd00-c15b-11ea-9925-fdb68b73ed9b.png)
