### ISSUE TITLE
VDC: Add price of each plan

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2014]
Allow the user to see the price beforehand

**Comment by RafyAmgadBenjamin** [comment]
verifying

**Comment by RafyAmgadBenjamin** [comment]
verified on branch `development_vdc`
commit d43ed870201532d469823abb410fab9263e607cc
![image](https://user-images.githubusercontent.com/46320202/104310051-c5522c80-54db-11eb-8b8c-392b82fec4bc.png)
