### ISSUE TITLE
UI: update vdc icons

### ISSUE THREAD

**Issue by abom** [threefoldtech/js-sdk#2020]
### Description

Update "Compute nodes" and "Storage nodes" VDC menu icons to be more meaningful, currently, storage icon is like a CPU and compute node is not relevant.

### Screenshots

![image_2020-12-28_11-11-04](https://user-images.githubusercontent.com/511438/103214219-87b8a580-4918-11eb-9e53-4cb13973a938.png)

**Comment by waleedhammam** [comment]
Verified
![Screenshot from 2021-01-12 11-09-38](https://user-images.githubusercontent.com/10658229/104293437-ac8b4c00-54c6-11eb-90b7-93d6cc83cdc7.png)
