### ISSUE TITLE
Update zeroci logo in marketplace 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#2025]
Replace the current logo with a better quality one

![image](https://user-images.githubusercontent.com/41957921/103221308-fc94db00-492a-11eb-80a1-2f624eb02435.png)

**Comment by waleedhammam** [comment]
Will be updated with new logo, as the the square one is too small

![Screenshot from 2021-01-27 11-49-42](https://user-images.githubusercontent.com/10658229/105975077-39bdcb80-6097-11eb-8f74-983d8b311b57.png)
![Screenshot from 2021-01-27 11-49-37](https://user-images.githubusercontent.com/10658229/105975087-3d515280-6097-11eb-9803-98202fb4cda7.png)

**Comment by ehab-hassan** [comment]
[ZeroCI_logos.pdf](https://github.com/threefoldtech/js-sdk/files/5918222/ZeroCI_logos.pdf)

3 logos at black & white Background

**Comment by ehab-hassan** [comment]
![icone_white](https://user-images.githubusercontent.com/10484295/107144501-2edf2280-6944-11eb-8fc6-ec3616257b6e.png)
![icone_black](https://user-images.githubusercontent.com/10484295/107144502-30a8e600-6944-11eb-8287-80c8d24bb153.png)
![zero-ci-white-0١](https://user-images.githubusercontent.com/10484295/107144503-31417c80-6944-11eb-90c3-620c9e953cce.png)
![zero-ci-black-0١](https://user-images.githubusercontent.com/10484295/107144504-31da1300-6944-11eb-9b8f-dde3affc7734.png)

according o vote at telegram this the logo black and white

**Comment by hossnys** [comment]
verified 

![Screenshot from 2021-02-23 17-41-40](https://user-images.githubusercontent.com/26298009/108868075-85b05180-75fe-11eb-99f4-720ffbae7ae6.png)
![Screenshot from 2021-02-23 17-41-48](https://user-images.githubusercontent.com/26298009/108868088-86e17e80-75fe-11eb-8d63-eb1f53b9b2fe.png)
