### ISSUE TITLE
VDC: allow custom domains not managed by the gateway

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2028]
As a user I'd like to have solutions on the VDC on my own domain e.g mattermost.myfancydomain.com or even directly on `myfancydomain.com` for this to work 
1- we need to allow option to ask for custom domain
2- we need to validate the domain before attempting to deploy
3- we need to allow letsencrypt for the user as the preferred method for resolving the certs

**Comment by OmarElawady** [comment]
Allowed the choice of a custom domain with a check that its DNS A record points to the cluster public ip in the linked PR.

**Comment by hossnys** [comment]
verified :
![Screenshot from 2021-02-23 17-15-55](https://user-images.githubusercontent.com/26298009/108865585-0f125480-75fc-11eb-84e6-382bfdebdb00.png)
![Screenshot from 2021-02-23 17-17-33](https://user-images.githubusercontent.com/26298009/108865591-10dc1800-75fc-11eb-87cd-c14a28e37b97.png)
![Screenshot from 2021-02-23 17-19-20](https://user-images.githubusercontent.com/26298009/108865597-12a5db80-75fc-11eb-861e-81247e91bf27.png)
![Screenshot from 2021-02-23 17-19-50](https://user-images.githubusercontent.com/26298009/108865611-15083580-75fc-11eb-9067-a68192fb672b.png)
![Screenshot from 2021-02-23 17-22-01](https://user-images.githubusercontent.com/26298009/108865614-15a0cc00-75fc-11eb-9103-13aab99ae491.png)
![Screenshot from 2021-02-23 17-23-14](https://user-images.githubusercontent.com/26298009/108865622-16d1f900-75fc-11eb-8c1d-3f3d99aadc8a.png)
