### ISSUE TITLE
VDC deploy fails due to insufficient memory resources

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2042]
Insufficient memory when deploying a VDC. 
Unclear in the message what type of resource is missing. 

<img width="848" alt="Screenshot 2020-12-29 at 15 12 24" src="https://user-images.githubusercontent.com/30384423/103290542-177a5480-49ea-11eb-8aca-226535689069.png">

**Comment by xmonader** [comment]
I don't think this is any relevant to the user, also the silver package is already defined in the beginning of the chatflow
