### ISSUE TITLE
VDC: deploy monitoring from marketplace doesn't generate anything

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2044]
Nothing happens when deploying a monitoring stack
<img width="979" alt="Screenshot 2020-12-29 at 15 49 58" src="https://user-images.githubusercontent.com/30384423/103292240-bb193400-49ed-11eb-9af9-9c6fc4711286.png">

<img width="1253" alt="Screenshot 2020-12-29 at 15 50 21" src="https://user-images.githubusercontent.com/30384423/103292262-c1a7ab80-49ed-11eb-98d2-df0b8844ccb5.png">

**Comment by xmonader** [comment]
duplicate https://github.com/threefoldtech/js-sdk/issues/1921
