### ISSUE TITLE
PeerTube: was able to install it but I don't get to run it

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2045]
PeerTube generates plenty of errors within the application when trying to create an acount and then logging in:
- bad gateway
- client is invalid
<img width="967" alt="Screenshot 2020-12-29 at 16 06 34" src="https://user-images.githubusercontent.com/30384423/103293306-e69d1e00-49ef-11eb-97b6-5c433f8267b2.png">

<img width="1271" alt="Screenshot 2020-12-29 at 16 04 02" src="https://user-images.githubusercontent.com/30384423/103293321-ef8def80-49ef-11eb-8ca3-e00e248b2fd4.png">

Linked to configuration ?

On MacOS, Safari web browser.

**Comment by xmonader** [comment]
We don't support safari, and we don't specific apps beyond the normal installation
