### ISSUE TITLE
blank page in chatflow after restarting 3bot server

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/js-sdk#205]
** Steps to reproduce **

- Start 3bot server. 

```
server = j.servers.threebot.get("default")
server.start() 
```

- Go to chatflow and in the middle of a chatflow.

- Restart the 3bot server. 
```
server.stop() 
```

- Go to chatflow at any solution and we will find blank page, Like this.

![ff](https://user-images.githubusercontent.com/21218053/86808193-ee9c8680-c07a-11ea-9022-04395838d036.png)

**Comment by AhmedSa-mir** [comment]
Should be fixed by https://github.com/threefoldtech/js-sdk/pull/207

**Comment by Dina-Abd-Elrahman** [comment]
- verified
