### ISSUE TITLE
prepare testnet vdc to work with private TFT testnet

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2050]
in the payment part for testnet case, we can fund it directly and use the faucet to send money so we can skip the payment step, but yet we still keep the billing flow undertest

## to happen

- [ ] when on testnet, don't ask for payment
- [ ] when on testnet show commercial message see below
- [ ] when on testnet deploy wallet for user with 5k TFT
- [ ] when on production: current flow of wallet...

## commercial message

Welcome to our ....

**Comment by xmonader** [comment]
requires: https://github.com/threefoldtech/tfexplorer/issues/258

**Comment by despiegk** [comment]
sacha can deliver commercial message

**Comment by sasha-astiadi** [comment]
obsolete, closing.

**Comment by sasha-astiadi** [comment]
using  tft production to pay, instead of auto send 5k testnet tft
