### ISSUE TITLE
VDC: show value in USD of the vdc plans

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2052]
Make sure to show the USD fixed value coming from github

**Comment by xmonader** [comment]
222aa1d3f2305981bec4a9b4302d006327ec2d67 ![image](https://user-images.githubusercontent.com/64129/103518398-60178f00-4e7c-11eb-9415-c1d038b3961f.png)

**Comment by RafyAmgadBenjamin** [comment]
verified  
branch : `development_vdc`
commit Id: d43ed870201532d469823abb410fab9263e607cc
![image](https://user-images.githubusercontent.com/46320202/104312833-d69d3800-54df-11eb-9b3b-8ba26f165f09.png)
