### ISSUE TITLE
Update docs to remove any TEST wallets info related

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#2066]
- In js-ng, js-sdk repos

**Comment by MElborolossy** [comment]
@waleedhammam 
I think after the last update the docs need to be updated with the last approach (Use real TFT for all main, test and devnet), FreeTFT is no longer used.

**Comment by MElborolossy** [comment]
Comments:
### [add_funds_to_wallet.md](https://github.com/threefoldtech/js-sdk/blob/6aaf3f86087e75689515db6935b6bb3e80cae1b8/docs/wiki/tutorials/add_funds_to_wallet.md)
- Under [tokens-available](https://github.com/threefoldtech/js-sdk/blob/6aaf3f86087e75689515db6935b6bb3e80cae1b8/docs/wiki/tutorials/add_funds_to_wallet.md#tokens-available) freeTFT no longer used
- Under [getting-some-tokens](https://github.com/threefoldtech/js-sdk/blob/6aaf3f86087e75689515db6935b6bb3e80cae1b8/docs/wiki/tutorials/add_funds_to_wallet.md#getting-some-tokens) also freeTFT is no longer used, so no need to mention it
- Under [from-the-admin-dashboard](https://github.com/threefoldtech/js-sdk/blob/6aaf3f86087e75689515db6935b6bb3e80cae1b8/docs/wiki/tutorials/add_funds_to_wallet.md#from-the-admin-dashboard) this part is not needed _(will be test if you are using identity against testnet)_

###  [add_funds_to_wallet_dashboard.md](https://github.com/threefoldtech/js-sdk/blob/6aaf3f8608/docs/wiki/tutorials/add_funds_to_wallet_dashboard.md)
- Same as pervious

**Comment by waleedhammam** [comment]
> Comments:
> 
> ### [add_funds_to_wallet.md](https://github.com/threefoldtech/js-sdk/blob/6aaf3f86087e75689515db6935b6bb3e80cae1b8/docs/wiki/tutorials/add_funds_to_wallet.md)
> * Under [tokens-available](https://github.com/threefoldtech/js-sdk/blob/6aaf3f86087e75689515db6935b6bb3e80cae1b8/docs/wiki/tutorials/add_funds_to_wallet.md#tokens-available) freeTFT no longer used
> * Under [getting-some-tokens](https://github.com/threefoldtech/js-sdk/blob/6aaf3f86087e75689515db6935b6bb3e80cae1b8/docs/wiki/tutorials/add_funds_to_wallet.md#getting-some-tokens) also freeTFT is no longer used, so no need to mention it
> * Under [from-the-admin-dashboard](https://github.com/threefoldtech/js-sdk/blob/6aaf3f86087e75689515db6935b6bb3e80cae1b8/docs/wiki/tutorials/add_funds_to_wallet.md#from-the-admin-dashboard) this part is not needed _(will be test if you are using identity against testnet)_
> 
> ### [add_funds_to_wallet_dashboard.md](https://github.com/threefoldtech/js-sdk/blob/6aaf3f8608/docs/wiki/tutorials/add_funds_to_wallet_dashboard.md)
> * Same as pervious

we can remove the whole file then :D

**Comment by MElborolossy** [comment]
Branch: development
commit: a28f428c116fa168964148f5d2f40fdd13721973

Verified
