### ISSUE TITLE
VDC: update publisher chatflows to use the new publishingtools chart

### ISSUE THREAD

**Issue by abom** [threefoldtech/js-sdk#2084]
Publishingtools chart https://github.com/threefoldtech/vdc-solutions-charts/issues/16

**Comment by ranatrk** [comment]
verified deployed using `<domain>/vdc_dashboard/#/solutions/wiki`
![Screenshot from 2021-01-19 12-23-44](https://user-images.githubusercontent.com/17128393/105021858-b9251c80-5a51-11eb-849a-66a3bda8097f.png)
![Screenshot from 2021-01-19 12-24-09](https://user-images.githubusercontent.com/17128393/105021861-baeee000-5a51-11eb-845b-d6f0fa9e343b.png)
