### ISSUE TITLE
discount should show 90% and 99% instead of 0.9  and 0.99 in the UI

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2107]
discount should show 90% and 99% instead of 0.9  and 0.99 in the UI

**Comment by waleedhammam** [comment]
Verified

![Screenshot from 2021-01-13 14-35-24](https://user-images.githubusercontent.com/10658229/104453112-98ba1580-55ac-11eb-947c-5616f58e001b.png)
