### ISSUE TITLE
polls typo

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#211]
![image](https://user-images.githubusercontent.com/64129/87022599-fe30e200-c1d6-11ea-991b-683ae4c84e4f.png)

**Comment by BolaNasr** [comment]
The same nothing change .
https://github.com/threefoldtech/js-sdk/blob/development/jumpscale/packages/polls/chats/threefold.py#L104

**Comment by BolaNasr** [comment]
Verified
