### ISSUE TITLE
Incorrect VDC Expiration time

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#2116]
### Description

vdc expiration is not matching between the deployer and the vdc threebot

![image](https://user-images.githubusercontent.com/32568986/103516636-8851be80-4e79-11eb-8187-edd1d877c89e.png)

![image](https://user-images.githubusercontent.com/32568986/103516672-943d8080-4e79-11eb-8728-a84aa56e46cc.png)

**Comment by m-motawea** [comment]
fixed on branch development_vdc

![image](https://user-images.githubusercontent.com/32568986/103526981-5432c980-4e8a-11eb-9138-0c4f2f82afd6.png)

![image](https://user-images.githubusercontent.com/32568986/103527012-614fb880-4e8a-11eb-81d9-68c1cb5bd051.png)

**Comment by waleedhammam** [comment]
verified on vdc.devnet.grid.tf
![Screenshot from 2021-01-13 18-36-51](https://user-images.githubusercontent.com/10658229/104481324-53a6db00-55ce-11eb-9b53-92a9375ee829.png)
![Screenshot from 2021-01-13 18-35-47](https://user-images.githubusercontent.com/10658229/104481328-55709e80-55ce-11eb-87c0-60e3306e8ca1.png)
