### ISSUE TITLE
VDC: expand master node memory

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/js-sdk#2120]
Currently deployed VDCs has master node of 1G RAM which has free mem of less than 100M which make the master node hangs every now and then and it takes too long to respond 
I tried it on different VDC all has the same issue 
when deploying the monitoring-stack for example the cluster keeps hanging all the time
I suggest that we increase it a bit 
![Screenshot from 2021-01-04 12-36-19](https://user-images.githubusercontent.com/1689456/103526663-eb4b5180-4e89-11eb-87ae-f8dc8c6971f4.png)
and `kubectl describe node <master> ` returns this
![Screenshot from 2021-01-04 12-39-52](https://user-images.githubusercontent.com/1689456/103526721-00c07b80-4e8a-11eb-8be1-d7e3b2e7308e.png)

update: 
   - tested with tainting master and all pods on workers and the issue still happening 
   - tested with tainting master and all pods on workers BUT increased master size and every thing was working properly

**Comment by xmonader** [comment]
okay k8s size 15 seems to be more appropriate for a controller (1 cpu, 2 GB ram, 25 disk)

**Comment by xmonader** [comment]
I increased the size if an issue please comment with what needs to be done @despiegk

**Comment by RafyAmgadBenjamin** [comment]
verifying this
