### ISSUE TITLE
Error on wallet activation

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/js-sdk#2122]
when i try to create a wallet i get this error
![image](https://user-images.githubusercontent.com/31102305/103533048-15eed780-4e95-11eb-9f26-e2e8bb7f7b1c.png)

logs
![image](https://user-images.githubusercontent.com/31102305/103532522-0e7afe80-4e94-11eb-9238-c11c3c35af84.png)
![image](https://user-images.githubusercontent.com/31102305/103532534-1470df80-4e94-11eb-88bf-c4d0cb68792e.png)

**Comment by mhost39** [comment]
also this make vdc creation not working 
![image](https://user-images.githubusercontent.com/31102305/103532616-42eeba80-4e94-11eb-9f07-ed48b38f5b17.png)

**Comment by xmonader** [comment]
not valid anymore, there's API change
