### ISSUE TITLE
VDC: list and deploy buttons in main page are barely visiable especially list button

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/js-sdk#2136]
![Screenshot from 2021-01-06 11-12-15](https://user-images.githubusercontent.com/26298009/103751331-cc2afc00-5010-11eb-85ec-c954cc4cbbb3.png)

**Comment by hossnys** [comment]
seems that it was something with the browser when loading page 
![Screenshot from 2021-01-06 23-02-45](https://user-images.githubusercontent.com/26298009/103819628-75a2d980-5073-11eb-9729-4f525e24860a.png)

**Comment by xmonader** [comment]
There was an update yesterday to the underlying framework the we use for the UI vuetify, now pinned to specific version
