### ISSUE TITLE
VDC: all resources disappeared, including wallet

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2138]
Created a VDC on testnet 2 days ago, when I look now, I see the VDC is still there, but all K8S nodes have disappeared and the wallet screen is empty. 

<img width="1248" alt="Screenshot 2021-01-06 at 10 42 00" src="https://user-images.githubusercontent.com/30384423/103756009-08f5f380-500f-11eb-946b-764ef3b00ccd.png">

<img width="1248" alt="Screenshot 2021-01-06 at 10 52 39" src="https://user-images.githubusercontent.com/30384423/103756022-0d221100-500f-11eb-879a-c20de75e02a3.png">

**Comment by OmarElawady** [comment]
There was a breaking-change update that affected the vdc listing. We did a manual update to fix it but it should work for newly created VDCs as expected.

![Screenshot from 2021-01-06 13-53-47](https://user-images.githubusercontent.com/13040543/103766229-21720800-5027-11eb-926a-c7bda118cb6f.png)

**Comment by gmachtel** [comment]
It works now
