### ISSUE TITLE
VDC SALs testsuite coverage

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/js-sdk#2140]
### Description

- Add test coverage for all SALs in VDC.

- Include tests to run in github actions: for now will run once per day to avoid spend a lot of TFTs on testnet.

#### 1- vdc sal
- [x] deploy vdc
  - [x] silver
  - [x] gold
  - [x] platinum
  - [x] diamond
- [x] calculate_expiration_value
- [x] renew the plan
- [x] add kubernetes node
- [x] delete kubernetes node
- [x] apply grace period action
- [x] undo the grace period action
- [x] load_info
- [x] is_empty
- [x] list vdcs
- [x] find a vdc
- [x] transfer_to_provisioning_wallet
- [x] zdb auto extend

#### 2- kubernetes sal
- [x] update repos
- [x] add helm repo
- [x] install chart
- [x] delete deployed chart
- [x] is helm installed
- [x] execute native cmd
- [x] get_helm_chart_user_values
- [x] upgrade_release

#### 3- billing

- [x] submit_payment
- [x] wait_payment
- [x] refund_failed_payments
- [x] issue_refund
- [x] issue_refund_with_specific_amount
- [x] check_refund
- [x] check_refund_raise_error
- [x] process_refunds
- [x] process_payments
- [x] refund_extra
- [x] refund_extra_set_false

see examples for billing [here](https://github.com/threefoldtech/js-sdk/blob/development_vdc/jumpscale/sals/billing/test_billing.py)

**Comment by ramezsaeed** [comment]
First test done by @AhmedHanafy725 

https://github.com/threefoldtech/js-sdk/pull/2206

![photo_2021-01-14_11-14-07](https://user-images.githubusercontent.com/16083592/104569529-a5487780-5659-11eb-98f5-31904087a3e2.jpg)

**Comment by mhost39** [comment]
working on vdc sal

**Comment by MElborolossy** [comment]
Working on billing

**Comment by AhmedHanafy725** [comment]
For the current tests in this issue, it needs about 30 TFT/run, and we will run them once a day

**Comment by xmonader** [comment]
let's close with the workflow run result once happens please.

**Comment by AhmedHanafy725** [comment]
All tests passing in this [run](https://github.com/threefoldtech/js-sdk/runs/1875934607?check_suite_focus=true)
