### ISSUE TITLE
VDC: succeessfull deployment of new VDC but does not  show up in listing

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2144]
### Description
Went through a complete deployment cycle of a VDC gold - paid 30TFT for it and end up with an empty VDC overview screen.

![image](https://user-images.githubusercontent.com/13766992/103991486-2b714380-51ac-11eb-996b-077f701358f3.png)
![image](https://user-images.githubusercontent.com/13766992/103991901-c9fda480-51ac-11eb-85b9-776fc2b5a37a.png)

A clear description of the bug

### Version information

Current version of the VDDC deployer on testnet

### Installation method
Online VDC deployer, used the Firefox browser

### Traceback/Logs/Alerts
Not availanble, did not get an errror.

**Comment by xmonader** [comment]
proper flavor migration has been done https://github.com/threefoldtech/js-sdk/commit/b2302149a58ec48e0fb0eb23c423d739130bbaa3

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/104005838-5f4d6880-51ae-11eb-80e4-4cd4555c8d4c.png)
