### ISSUE TITLE
3bot online cannot deploy ubuntu workload and ended up using another pool

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2146]
### Description
Cannot deploy standard ubuntu (demo) deployment on the gridl  Results in the following error:
```
failed to deploy workload on node BSusuRh6qFzheQFwNPe1S5FA5pdSZVJwVLhpNS6GN4XD due to error 402 Client Error: pool needs additional capacity to support this workload for url: https://explorer.grid.tf/api/v1/reservations/workloads. Use the refresh button on the upper right to restart Ubuntu creation
```

![image](https://user-images.githubusercontent.com/13766992/104082753-0f27e200-5252-11eb-9306-b6dbaeaaf23e.png)

Log sohw:
![image](https://user-images.githubusercontent.com/13766992/104082789-57470480-5252-11eb-8b13-91742f9a2836.png)

And had many more of these lasrt night:
![image](https://user-images.githubusercontent.com/13766992/104082801-76de2d00-5252-11eb-9123-605a8e855d29.png)

3bot identity: weynandkuijpers.3bot
capacity pool: 
![image](https://user-images.githubusercontent.com/13766992/104082842-efdd8480-5252-11eb-8c3a-c6cf9ed5d829.png)

So I am using the capacity pool named "caleb" which is on vienna1.  It has plenty of funds (they paid for their tokens) in CU and SU but I am getting the error that the pool does not have sufficient funds.  Which is clearly does have.

Secondly the pool is for vienna1 and the server reported ```BSusuRh6qFzheQFwNPe1S5FA5pdSZVJwVLhpNS6GN4XD``` is in salzburg.  So I am not sure why it tries to deploy in salzburh when you clearly specify a vienna1 capacity pool and hand pick a vienna1 server

**Comment by xmonader** [comment]
blocked on https://github.com/threefoldtech/tf_operations/issues/83

**Comment by xmonader** [comment]
I created two pools myself one on freefarm and one on GreenEdge-vienna1

![image](https://user-images.githubusercontent.com/64129/104093189-9c3e5b80-5291-11eb-9eb0-cf7ec77e9e66.png)

the one on freefarm
https://explorer.grid.tf/api/v1/reservations/workloads/83431 pool id 1505

the one on GreenEdge-vienna1
https://explorer.grid.tf/api/v1/reservations/workloads/83438

please make sure you specified the pool correctly in the chatflow

**Comment by xmonader** [comment]
I created two pools myself one on freefarm and one on GreenEdge-vienna1

![image](https://user-images.githubusercontent.com/64129/104093189-9c3e5b80-5291-11eb-9eb0-cf7ec77e9e66.png)

the one on freefarm
https://explorer.grid.tf/api/v1/reservations/workloads/83431 pool id 1505

the one on GreenEdge-vienna1
https://explorer.grid.tf/api/v1/reservations/workloads/83438

please make sure you specified the pool correctly in the chatflow

**Comment by m-motawea** [comment]
verified
