### ISSUE TITLE
restarting a 3bot which ran out of funding results in error

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2148]
Restarting a "stranded" 3bot by wanting to top up result in error:

![image](https://user-images.githubusercontent.com/13766992/104083226-6760e300-5256-11eb-950e-9042b8da1062.png)

The 3bot is hosten in farm ```979``` in Hong Kong (dragon Edge Cloud) which has funds and is not out of capacity:
![image](https://user-images.githubusercontent.com/13766992/104083263-a7c06100-5256-11eb-991f-86a81005a378.png)

Assuming that the resource pool it lives on is out of capacity (which it is not)
![image](https://user-images.githubusercontent.com/13766992/104083460-22d64700-5258-11eb-9965-1cafc0daf131.png)

I want to push it to another farm.  Relocating the online 3bot allow me only to psuh it to one lcoation:
![image](https://user-images.githubusercontent.com/13766992/104083404-ab081c80-5257-11eb-92bc-da534be02711.png)

and I don;t want it on freefarm (becasue I have a drained capacity pool there and there is maintenance today....).

**Comment by xmonader** [comment]
matching criteria for the farms (cpu, mem, ipv4) been relaxed on testnet, I updated the code on mainnet 
![image](https://user-images.githubusercontent.com/64129/104087621-d6940280-5269-11eb-9af6-e3466543ae05.png)
