### ISSUE TITLE
inline 3bot name validation in the 3bot deployer

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2149]
![image](https://user-images.githubusercontent.com/64129/104087581-8026c400-5269-11eb-9e85-e53a01273efa.png)

![image](https://user-images.githubusercontent.com/64129/104087586-874dd200-5269-11eb-96e3-4be37c6b6ca2.png)

It should do the validation in the first screen

**Comment by dmahmouali** [comment]
We can use `not_exist` validator like [here](https://github.com/threefoldtech/js-sdk/blob/development_vdc/jumpscale/packages/vdc/chats/new_vdc.py#L46:L51)
https://github.com/threefoldtech/js-sdk/blob/development_vdc/jumpscale/packages/chatflows/frontend/mixins/field.js#L38

**Comment by waleedhammam** [comment]
It redirected me to that page instead

![Screenshot from 2021-01-12 11-17-58](https://user-images.githubusercontent.com/10658229/104294456-dc871f00-54c7-11eb-800e-b6df3537b39c.png)

**Comment by dmahmouali** [comment]
We will show this message if there is an identity with the same name and format we use to build the identity name 
`f"{self.threebot_name}_{self.solution_name}"`

so it rais an error
@waleedhammam 
https://github.com/threefoldtech/js-sdk/blob/e21c53e2fafb47bfc790fc5e3eed74569097d79f/jumpscale/packages/threebot_deployer/chats/threebot.py#L195

**Comment by m-motawea** [comment]
verified on development commit: e21c53e2fafb47bfc790fc5e3eed74569097d79f

![image](https://user-images.githubusercontent.com/32568986/104328852-ef641880-54f4-11eb-93d1-9825f21fab92.png)
