### ISSUE TITLE
stellar: failed to submit in time 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2152]
we need to introduce the retries code we have for the 3bot 

```
127.0.0.1 - - [2021-01-09 14:35:21] "GET /admin/admin/get_notifications_count HTTP/1.0" 200 330 0.002870
2021-01-09 14:35:28.143 | ERROR    | jumpscale.sals.chatflows.chatflows:wrapper:173 - error
Traceback (most recent call last): 

  File "/root/js-sdk/jumpscale/clients/stellar/wrapped.py", line 34, in submit_transaction
    return super().submit_transaction(transaction_envelope)
                                      └ <stellar_sdk.transaction_envelope.TransactionEnvelope object at 0x7f7f119c7460>

  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/stellar_sdk/server.py", line 110, in submit_
transaction
    return self.__submit_transaction_sync(
           └ <jumpscale.clients.stellar.wrapped.Server object at 0x7f7f11349df0>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/stellar_sdk/server.py", line 129, in __submi
t_transaction_sync
    raise_request_exception(resp)
    │                       └ <stellar_sdk.client.response.Response object at 0x7f7f112ee160>
    └ <function raise_request_exception at 0x7f7f1bc4c4c0>
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.8/lib/python3.8/site-packages/stellar_sdk/exceptions.py", line 209, in rai
se_request_exception
    raise BadRequestError(response)
          │               └ <stellar_sdk.client.response.Response object at 0x7f7f112ee160>
          └ <class 'stellar_sdk.exceptions.BadRequestError'>

stellar_sdk.exceptions.BadRequestError: {
  "type": "https://stellar.org/horizon-errors/transaction_failed",
  "title": "Transaction Failed",
  "status": 400,
  "detail": "The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains fur
ther details.  Descriptions of each code can be found at: https://www.stellar.org/developers/guides/concepts/list-of-operations.html",
  "extras": {
    "envelope_xdr": "AAAAAgAAAAB3KjhciJhemd9/G8G4qkn40Vf6Q2OvX/D18Sf1J4CHJwAAAMgBwCu1AAABEQAAAAEAAAAAAAAAAAAAAABf+b7jAAAAAQAAAAZwLTE1MTA
AAAAAAAIAAAABAAAAAPRuqyTfxT5uK8JX68uprT6Xu+SqrLGYW/GnbrWLqjZZAAAAAQAAAAB1zfaCLGwKo/GOPYZe3B9H7lNqHB1nDsAkGKdynGUp3wAAAAFURlQAAAAAAF1YKTg
94x2O/muvqMcFiKjJAGYZJTG0I5eEOqzVJKMwAAAAAAAKkwgAAAABAAAAAPRuqyTfxT5uK8JX68uprT6Xu+SqrLGYW/GnbrWLqjZZAAAAAQAAAAAA3RKgkT+uNjmw1Pt37ayMhOT
1IOUgJ+9WES0PXnEpiwAAAAFURlQAAAAAAF1YKTg94x2O/muvqMcFiKjJAGYZJTG0I5eEOqzVJKMwAAAAAAAPQkAAAAAAAAAAAieAhycAAABAY7A1mk7MJae5JJypzAyjyScoBp5
6osvNd86fzKBthNUAtS8V6A/m+nDLSFU56ONgOKj2mTmIINyVvgpMM9SfAouqNlkAAABAkBGpYYCxqSrRxSVkjydLvwuV5aARIV1oBPA4c9zLNGMZmC+ve3dK9QSSNiKc9e1qNCt
irdoyse0oUiCQ+wBvDQ==",
    "result_codes": {
      "transaction": "tx_too_late" 
    },
    "result_xdr": "AAAAAAAAAMj////9AAAAAA=="
  }
}


During handling of the above exception, another exception occurred:

```
  File "/root/js-sdk/jumpscale/sals/marketplace/deployer.py", line 77, in pay_for_pool                                                  
    wallet.transfer(                                                                                                                    
    │      └ <function Stellar.transfer at 0x7f7f19080280>                                                                              
    └ Stellar(                                                                                                                          
        instance_name='demos_wallet',
        network=<Network.STD: 'STD'>,
        address='GD2G5KZE37CT43RLYJL6XS5JVU7JPO7EVKWLDGC36...

  File "/root/js-sdk/jumpscale/clients/stellar/stellar.py", line 472, in transfer
    response = horizon_server.submit_transaction(transaction)
               │              │                  └ <stellar_sdk.transaction_envelope.TransactionEnvelope object at 0x7f7f119c7460>
               │              └ <function Server.submit_transaction at 0x7f7f19075280>
               └ <jumpscale.clients.stellar.wrapped.Server object at 0x7f7f11349df0>

  File "/root/js-sdk/jumpscale/clients/stellar/wrapped.py", line 39, in submit_transaction
    raise TooLate()
          └ <class 'jumpscale.clients.stellar.exceptions.TooLate'>

jumpscale.clients.stellar.exceptions.TooLate: The transaction failed to be submitted to the network in time

```

**Comment by xmonader** [comment]
another error with bad sequence
stellar_sdk.exceptions.BadRequestError: {                                                                            
  "type": "https://stellar.org/horizon-errors/transaction_failed",                                                   
  "title": "Transaction Failed",                                                                                     
  "status": 400,                                                                                                     
  "detail": "The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this re
sponse contains further details.  Descriptions of each code can be found at: https://www.stellar.org/developers/guide
s/concepts/list-of-operations.html",                                                                                 
  "extras": {                                                                                                        
    "envelope_xdr": "AAAAAgAAAAAwxI3uKpvsuRWLcaYLFQrgi0YsSKCInlBF8oGNZ5SHFwAAAMgBwCu3AAAAjAAAAAEAAAAAAAAAAAAAAABf+fg8
AAAAAQAAAAZwLTE1MjYAAAAAAAIAAAABAAAAAPRuqyTfxT5uK8JX68uprT6Xu+SqrLGYW/GnbrWLqjZZAAAAAQAAAAA30raoXAKOuA3rVDCPgo3+oTS7I
DkX7+QGRrsPyBPmZwAAAAFURlQAAAAAAF1YKTg94x2O/muvqMcFiKjJAGYZJTG0I5eEOqzVJKMwAAAAAAAKkwgAAAABAAAAAPRuqyTfxT5uK8JX68uprT
6Xu+SqrLGYW/GnbrWLqjZZAAAAAQAAAAAA3RKgkT+uNjmw1Pt37ayMhOT1IOUgJ+9WES0PXnEpiwAAAAFURlQAAAAAAF1YKTg94x2O/muvqMcFiKjJAGY
ZJTG0I5eEOqzVJKMwAAAAAAAPQkAAAAAAAAAAAmeUhxcAAABAQv2WGwTZJRcM4wjRTdy9EH27L1xLzz1LObd8PjGRDIDoV5PppoUhfaP9DsFrjgZQrNaN
ykBOiVOh4MJ+suG9AouqNlkAAABAU7Zcc2kaDF1frZoFvhq7TFR4GFWhuYwcdncZCQGleZuHuQ8gD3eDnX8/zKnGVw8/rGt8VaqGpIKNkL3EJHCDCA=="
,                                                                                                                    
    "result_codes": {                                                                                                
      "transaction": "tx_bad_seq"                                                                                    
    },                                                                                                               
    "result_xdr": "AAAAAAAAAMj////7AAAAAA=="                                                                         
  }                                                                                                                  
}

**Comment by scottyeager** [comment]
I'm seeing "failed to submit payment to stellar in time for PoolCreated" today while trying to deploy VDC on testnet. Each time, the payment is deducted from my wallet and then later refunded. See logs:
http://explorer.testnet.grid.tf/api/v1/reservations/pools/payment/79
http://explorer.testnet.grid.tf/api/v1/reservations/pools/payment/80
http://explorer.testnet.grid.tf/api/v1/reservations/pools/payment/81

**Comment by xmonader** [comment]
@scottyeager thanks for reporting, latest code is on devnet atm and testing on testnet is blocked on https://github.com/threefoldtech/zos/issues/1150  https://github.com/threefoldtech/zos/issues/1149

**Comment by ranatrk** [comment]
retires added and shown in logs
```
2021-01-19 11:06:37.005 | WARNING  | jumpscale.clients.stellar.stellar:transfer:456 - The transaction failed to be submitted to the network in time                                                           
2021-01-19 11:06:37.011 | INFO     | jumpscale.clients.stellar.stellar:_transfer:475 - Sending 0.0693 TFT:GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47 to GB73GS7UFSWOITNQNMBLZIWWKDA5GIRFF7LG6BNL
HG5ATT7CXJ33OMXA
```
