### ISSUE TITLE
improve the gateways error message: Letsencrypt limit has been reached on all gateways.

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2153]
```
Letsencrypt limit has been reached on all gateways. The resources you paid for will be re-used in your upcoming deployments.. Use the refresh button on the upper right to restart 3Bot creation
```

I got this message which actually has nothing to do with letsencrypt limit, it was caused by the csfarmer gateway being down

**Comment by ranatrk** [comment]
LetsIncrypt errors shouldn't be an issue as zerossl is now used instead. The final error should be because of misconfigured gateways or gateways not correctly functioning

**Comment by waleedhammam** [comment]
verified
