### ISSUE TITLE
3bot started without a wallet on deploy3bot.grid.tf

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2155]
![image](https://user-images.githubusercontent.com/64129/104106098-c147c400-52bb-11eb-912c-5f346b6c7761.png)

creating a wallet may fail on the token services, maybe we should create/activate the wallet ourselves from the 3bot deployer using yet another activation wallet? 

note: the user can always try to create a wallet from the dashboard -but again most likely will faill-

**Comment by robvanmieghem** [comment]
It can always fail for a variety of reasons (can have nothing to do with the tokenservices) .
Constructing too many wallets and services complicate things even more imho.
Can't  a small healthcheck with a fix-it solve it when the services ( and the ones they rely upon) are all functional again.?

**Comment by xmonader** [comment]
resolved in https://github.com/threefoldtech/js-sdk/pull/2184
