### ISSUE TITLE
VDC : add apps page where user can find all installed apps on vdc 

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/js-sdk#2162]
### Description

- need to add applications page where user can find and reach easily all his installed applications with it's info (expiration date , solution URL , status )

- this is like the page of workloads for each solution in the marketplace , but the difference that it'll list all solutions instances that installed on the VDC .

- this page will make the user life easier and help him to handle all installed app through one page , and not forget renewing them in time .

![Screenshot from 2021-01-10 14-57-59](https://user-images.githubusercontent.com/26298009/104123578-a7a68b00-5354-11eb-878e-de3c4b061feb.png)

**Comment by MElborolossy** [comment]
Verified
- Button in MarketPlace
![image](https://user-images.githubusercontent.com/11272864/104476711-37546f80-55c9-11eb-89a4-ca90461a0176.png)

- List all workloads
![image](https://user-images.githubusercontent.com/11272864/104476557-0d02b200-55c9-11eb-93cb-0541bb5d66b5.png)
