### ISSUE TITLE
Amount of active compute and storage units 

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2167]
Number presented in the capacity pool overview in 3bot do not make sense.  The pool in the image has 4 containers live of 64 cores each. This number (0.0000247 - active compute units) does not reflect that.

![image](https://user-images.githubusercontent.com/13766992/104127808-99209980-537d-11eb-8564-1251d8a1a641.png)

Plus the number representing the number of available CU and SU's is going down much faster than the small number.  suggestion would be to make the numbers of equal dimension.

**Comment by waleedhammam** [comment]
According to this issue https://github.com/threefoldtech/js-sdk/issues/1744 it was to be shown per month.

fixed in here https://github.com/threefoldtech/js-sdk/pull/2169

**Comment by MElborolossy** [comment]
- Branch: development
- Commit: ad352f9514112a6a1c639328dfe18c97dbaab3a5

Result:
![image](https://user-images.githubusercontent.com/11272864/104180437-c6b92180-5415-11eb-98af-be45a4df5052.png)

Verified
