### ISSUE TITLE
3BOT Deployer times out and gives error

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/js-sdk#2190]
We have one of our partners , trying to deploy his 3bot ( https://deploy3bot.grid.tf/ )  first and then move ahead with deploying the solution.

He gets error after this step :

![image](https://user-images.githubusercontent.com/25789724/104306982-18ca7780-54e8-11eb-9139-7eeb04767e9a.png)

![image](https://user-images.githubusercontent.com/25789724/104307005-1d8f2b80-54e8-11eb-8dbf-fa1cfad771b9.png)

and when trying again , we get this error : 

![image](https://user-images.githubusercontent.com/25789724/104307051-2e3fa180-54e8-11eb-9aaa-5845384adfd6.png)

**Comment by m-motawea** [comment]
looking at the logs, there seems to have been problems with stellar in payment and in explorer. you can try again now it should be a bit better with more retries.
```
{'type': 'BadRequestError', 'value': '{\n  "type": "https://stellar.org/horizon-errors/transaction_failed",\n  "title": "Transaction Failed",\n  "status": 400,\n  "detail": "The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://www.stellar.org/developers/guides/concepts/list-of-operations.html",\n  "extras": {\n    "envelope_xdr": "AAAAAgAAAAAwxI3uKpvsuRWLcaYLFQrgi0YsSKCInlBF8oGNZ5SHFwAAAMgBwCu3AAAAjAAAAAEAAAAAAAAAAAAAAABf+fg8AAAAAQAAAAZwLTE1MjYAAAAAAAIAAAABAAAAAPRuqyTfxT5uK8JX68uprT6Xu+SqrLGYW/GnbrWLqjZZAAAAAQAAAAA30raoXAKOuA3rVDCPgo3+oTS7IDkX7+QGRrsPyBPmZwAAAAFURlQAAAAAAF1YKTg94x2O/muvqMcFiKjJAGYZJTG0I5eEOqzVJKMwAAAAAAAKkwgAAAABAAAAAPRuqyTfxT5uK8JX68uprT6Xu+SqrLGYW/GnbrWLqjZZAAAAAQAAAAAA3RKgkT+uNjmw1Pt37ayMhOT1IOUgJ+9WES0PXnEpiwAAAAFURlQAAAAAAF1YKTg94x2O/muvqMcFiKjJAGYZJTG0I5eEOqzVJKMwAAAAAAAPQkAAAAAAAAAAAmeUhxcAAABAQv2WGwTZJRcM4wjRTdy9EH27L1xLzz1LObd8PjGRDIDoV5PppoUhfaP9DsFrjgZQrNaNykBOiVOh4MJ+suG9AouqNlkAAABAU7Zcc2kaDF1frZoFvhq7TFR4GFWhuYwcdncZCQGleZuHuQ8gD3eDnX8/zKnGVw8/rGt8VaqGpIKNkL3EJHCDCA==",\n    "result_codes": {\n      "transaction": "tx_bad_seq"\n    },\n    "result_xdr": "AAAAAAAAAMj////7AAAAAA=="\n  }\n}', 'traceback': True}
```

```
exception: {'type': 'HTTPError', 'value': '500 Server Error: could not set up capacity escrow: failed to get escrow address for customer: failed to create a new account for customer 1504: failed to activate escrow account GC4IB33NNYICLS3APIRDEY673KFIAN2XAPMCTTPJYPF4CBB6RL4BG2HW: horizon error: "Transaction Failed" - check horizon.Error.Problem for more information for url: https://explorer.grid.tf/api/v1/reservations/pools', 'traceback': True}
```

**Comment by siddiquagig** [comment]
Just tried again , after making the payment , it took a long time time at "Waiting for Payment" Step and finally then got the error :


![image](https://user-images.githubusercontent.com/25789724/104423371-74077300-5597-11eb-87af-f6c9ce32efff.png)

**Comment by waleedhammam** [comment]
Verified and deployed successfully 

![Screenshot from 2021-01-13 18-26-00](https://user-images.githubusercontent.com/10658229/104480062-cfa02380-55cc-11eb-9002-7afe22fdd289.png)


![Screenshot from 2021-01-13 18-23-12](https://user-images.githubusercontent.com/10658229/104479708-6ae4c900-55cc-11eb-88ac-bc5c10266d7a.png)
