### ISSUE TITLE
Payment screen refers to previous payment screeen which is not in the chatflow

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2192]
eVDC deployment flow after you have put in all the required data (name, secret, type of eVDC then comes the payment screen:
![image](https://user-images.githubusercontent.com/13766992/104274968-67155180-54bb-11eb-9e97-b796d6be39af.png)

First line it sais: ```Please scan the QR Code below for the payment details if you missed it from the previous screen```

There is no previous screen so change to: ```Please scan the QR Code below for the payment```

**Comment by xmonader** [comment]
9751f7318bf6f40419272af192a9f8c253a11df4

**Comment by waleedhammam** [comment]
verified on vdc.testnet.grid.tf

![Screenshot from 2021-01-13 18-14-16](https://user-images.githubusercontent.com/10658229/104478597-2ad11680-55cb-11eb-9874-d6832e164aa0.png)
