### ISSUE TITLE
eVDC payment screen has ```next``` and ```back``` button which cannot be pressed

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2193]
Also the payment screen contains a ```Next``` and ```Back``` button which cannot be pressed
- successful payment it auto advances to "VDC deployment" screen
- if time out occurs - error message with a restart button to restart the eVDC provisioning process

Why keep the next / back button?

**Comment by xmonader** [comment]
It's perfectly normal to use disabled buttons in web applications / desktop applications indicating that there's an action happening and you won't be able to use that button until it's done e.g during payments or preparing infrastructure during a deployment, but will be enabled at a certain point once deployed or when getting extra configurations.

1- Keeping showing/hiding the buttons is too distracting
2- the user understands what is expected much better and the points of no returns as well
3- the user already got exposed to the functionality of next/prev so hiding that will be confusing 
4- These buttons should only be hidden if the user isn't allowed to use them at all (which isn't the case) 

## example on 3Bot

Here telling the user after some clicks on next that we are preparing the infrastructure and you can't now skip to the future or go back, but you will be able once some action is done
![image](https://user-images.githubusercontent.com/64129/104420559-ba9ea280-5582-11eb-8fbd-0f369a7f421b.png)

Here telling the user we are in the initialization step of the 3bot 

![image](https://user-images.githubusercontent.com/64129/104420683-ede13180-5582-11eb-934f-8eb7517295e2.png)


![image](https://user-images.githubusercontent.com/64129/104420645-db66f800-5582-11eb-8e2f-4b725896d783.png)

Here telling the user they can continue now 

![image](https://user-images.githubusercontent.com/64129/104420721-fb96b700-5582-11eb-961a-f5d1f96cbb22.png)


## example on the vdc 
checking on the payment service and telling the user they can't interact until this step is done

![image](https://user-images.githubusercontent.com/64129/104420820-21bc5700-5583-11eb-8e31-b7883872be4b.png)

once that payment service check is done the user is prompted to selecting the plan with one single actionable item, and a clear message they can't go to the previous
![image](https://user-images.githubusercontent.com/64129/104421802-82985f00-5584-11eb-9c1b-6deba76ca79a.png)


payment step
![image](https://user-images.githubusercontent.com/64129/104421686-60064600-5584-11eb-8e0f-5c229e3bb3da.png)

**Comment by waleedhammam** [comment]
verified as a ux wise
