### ISSUE TITLE
inconsistent titles in solution info

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#2197]
### Description

![image](https://user-images.githubusercontent.com/32568986/104326608-94c9bd00-54f2-11eb-9e09-1076e0e4f20f.png)

all fields should start with uppercase (i.e: creation field)

it should also show a time value not epoch

solution is monitoring

(note: it doesn't show the username/password to login to grafana)

**Comment by hossnys** [comment]
verified 
![Screenshot from 2021-02-23 20-25-41](https://user-images.githubusercontent.com/26298009/108889809-75f03780-7615-11eb-9c5a-81f091422c78.png)
