### ISSUE TITLE
VDC chatflows testsuite coverage

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/js-sdk#2201]
### Description

A full test-suite coverage for VDC chatflows

#### 1- vdc package
- [x] deploy vdc

#### 2- vdc_dashboard package
- [x] Blog
- [x] Cryptpad
- [x] Digibyte
- [x] Discourse
- [x] ETCD
- [x] Extend kubernetes
- [x] Gitea
- [x] Kubeapps
- [x] Mattermost
- [x] Monitoring
- [x] Peertube
- [x] Taiga
- [x] Website
- [x] Wiki
- [x] ZeroCI

**Comment by AhmedHanafy725** [comment]
- Solutions tests need to deploy the solution twice in the same cluster to make sure this feature available
- VDC deploy test are failing
- Some of the solution tests fail 

Please check this [run](https://github.com/threefoldtech/js-sdk/runs/1875934607?check_suite_focus=true)
