### ISSUE TITLE
3bot deployer on testnet fails to deploy

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2208]
Testnet reset last night, tries to get a 3bot back up and it failed (twice)

![image](https://user-images.githubusercontent.com/13766992/104401951-aa7cc800-556e-11eb-93b1-9536148b7ead.png)

Don't get much more feedback / insight than the error and alert in the screenshot.

**Comment by weynandkuijpers** [comment]
Tried it a third time.  Now by selecting a specific server to deploy on  Same result:
![image](https://user-images.githubusercontent.com/13766992/104407167-70192800-557a-11eb-9cfa-fa4d3be9c916.png)

Server selected is" ```85J3zEvcqDoPaN7qQHRQ2QgPVcYdCvp8JmRY5qAwzxfm```

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/104419741-9098b080-5581-11eb-8682-028505130d7c.png)


Testnet reset doesn't clean up our local data, I resetted the data around the pools and just deployed a 3bot successfully 

![image](https://user-images.githubusercontent.com/64129/104419677-79f25980-5581-11eb-9671-0a8ac91cd587.png)
