### ISSUE TITLE
Create VDC chatflows for the blockchain solutions

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/js-sdk#2209]
### Description

- [x] DigiByte
- [ ] Dash

**Comment by xmonader** [comment]
this is blocked and to be continued once  https://github.com/threefoldtech/vdc-solutions-charts/issues/49 and https://github.com/threefoldtech/vdc-solutions-charts/issues/13 are done

**Comment by sasha-astiadi** [comment]
move to project sdk 11.2 / grid 2.5

**Comment by sasha-astiadi** [comment]
new issue on digibyte helm chart only for 2.4 #66

**Comment by sasha-astiadi** [comment]
close this issue 
we make 1 issue per 1 blockchain node solution from now on. 

new issue on next bc widget:
https://github.com/threefoldtech/js-sdk/issues/2566
