### ISSUE TITLE
A button to update the VDC dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2210]
right now it's on https://vdc_url/vdc_dashboard/api/update and invoked manually, would be much better if the user can have a clickable button

**Comment by xmonader** [comment]
might a good idea to support query param to specify the branch to start the 3bot on

**Comment by waleedhammam** [comment]
![Screenshot from 2021-02-23 17-51-40](https://user-images.githubusercontent.com/10658229/108869370-ce1c3f00-75ff-11eb-8ebc-f2941a9a8823.png)

Verified
