### ISSUE TITLE
failed to deploy new threebot on testnet 

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/js-sdk#2211]
![Screenshot from 2021-01-13 10-50-16](https://user-images.githubusercontent.com/26298009/104428811-92687100-558d-11eb-9b09-53f03ce40aec.png)

**Comment by xmonader** [comment]
error is 
![image](https://user-images.githubusercontent.com/64129/104433592-f2154b00-5592-11eb-8197-ea71e34c05c6.png)


testnet explorer wallet is was out of xlms

**Comment by hossnys** [comment]
working fine now.

![Screenshot from 2021-01-13 13-57-36](https://user-images.githubusercontent.com/26298009/104449782-d0728e80-55a7-11eb-9330-d43ef002c645.png)
