### ISSUE TITLE
VDC: Add chatflows for Jimber charts

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/js-sdk#2212]
Add chat flow for the following charts
- [x] Document Server https://github.com/threefoldtech/js-sdk/issues/2229
- [x] Meetings https://github.com/threefoldtech/js-sdk/issues/2230
- [x] File Browser https://github.com/threefoldtech/js-sdk/issues/2231

**Comment by xmonader** [comment]
@ashraffouda please create issue for each item and set this one as type_story and link them here, otherwise all sub tasks won't go to verification until the whole story is done

**Comment by RafyAmgadBenjamin** [comment]
Fixed on branch `development_vdc_jimber_chatflows`
PR 
https://github.com/threefoldtech/js-sdk/pull/2282

**Comment by waleedhammam** [comment]
Can't verify, not yet in the dashboard
latest development_vdc

**Comment by sasha-astiadi** [comment]
@ashraffouda whats the progress? still blocked?

**Comment by ashraffouda** [comment]
the chatflows are ready and working correctly but the chart has some issues here 
https://github.com/threefoldtech/vdc-solutions-charts/issues/55
https://github.com/threefoldtech/vdc-solutions-charts/issues/56

**Comment by sasha-astiadi** [comment]
@tobiaschielens please take a look of this matter

**Comment by ken-de-moor** [comment]
Tasks themselves are done, bugs are already tracked in seperate tickets assigned.
