### ISSUE TITLE
VDC: error in creating new VDC, devnet explorer wallet is underfunded

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/js-sdk#2213]
- On devnet VDC deployer 

![image](https://user-images.githubusercontent.com/36021484/104432679-ed03cc00-5591-11eb-84d8-4ead5908cec9.png)

**Comment by xmonader** [comment]
but that's not the error, the error isn't related to vdc at all, it's the devnet explorer out money

**Comment by MElborolossy** [comment]
This error happen to me, I try again and it works fine and deployed now

**Comment by dmahmouali** [comment]
> but that's not the error, the error isn't related to VDC at all, it's the devnet explorer out money

should close this issue? @xmonader

**Comment by xmonader** [comment]
blocked on https://github.com/threefoldtech/tf_operations/issues/88

**Comment by xmonader** [comment]
should be resolved now

**Comment by waleedhammam** [comment]
Deployed successfully
verified on vdc.devnet.grid.tf

![Screenshot from 2021-01-13 18-26-36](https://user-images.githubusercontent.com/10658229/104480127-e6df1100-55cc-11eb-868c-a997548625e7.png)
