### ISSUE TITLE
admin can be duplicated in the admins list in the dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#222]
![image](https://user-images.githubusercontent.com/64129/87280226-33e50c00-c4f2-11ea-85ed-bcce7ec49888.png)

**Comment by AhmedHanafy725** [comment]
**Branch:** development
**commit:** 6e00872722f199910de8e4e1d71e72f249f95016

I have duplicate in admin names
![image](https://user-images.githubusercontent.com/41957921/87295518-a01d3b00-c505-11ea-9340-e563f65ebb42.png)

It needs to be handle also in `add_admin` actor

**Comment by AhmedHanafy725** [comment]
**Verified**

**Branch:** development
**Commit:** 44c902e63830c1298e9bac47bc0f25e699022b7c

When trying to add exist admin.
![image](https://user-images.githubusercontent.com/41957921/87300161-ad3e2800-c50d-11ea-80fc-bb6e3605e801.png)
