### ISSUE TITLE
split the capacitypool chatflow to two (create and extend)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2220]
Now that we support starting chatflows with arguments, i think it makes much more sense to split capacitypool chatflow into 
1- chatflow to create a capacity pool
2- chatflow to extend an existing capacitypool (by an action link in the capacity pools list)

**Comment by AhmedHanafy725** [comment]
### create pool button only 
![image](https://user-images.githubusercontent.com/41957921/107513787-6acaef80-6bb1-11eb-8125-0b6e08e1d2fd.png)


### after creating the pool, there an extend action
![image](https://user-images.githubusercontent.com/41957921/107513943-a2d23280-6bb1-11eb-9591-37180023a1da.png)


**Verified**

**Comment by AhmedHanafy725** [comment]
The create/extend pool button needs to be changed also in the dashboard
![image](https://user-images.githubusercontent.com/41957921/107536499-81ca0b80-6bca-11eb-8baf-f89bc993729d.png)

**Comment by AhmedHanafy725** [comment]
**Verified**
**Branch:** development
**Commit:** a4e3f07612731938ac67cdc855fb725e7a6b2505
![image](https://user-images.githubusercontent.com/41957921/107541538-e8055d00-6bcf-11eb-8095-2b6b6c4be0f9.png)

**Comment by scottyeager** [comment]
I went to extend a pool after this update and wasn't able to find the new widget without referencing here. To make this more obvious for users, I'd propose placing the action column on the far left rather than the far right. Alternatively/additionally, add a way to access the extend chatflow from the pool details page.

**Comment by ranatrk** [comment]
@scottyeager A suggested fix is addressed here https://github.com/threefoldtech/js-sdk/issues/2588 to have the view more compact and hence no need for the scrolling in the first place
