### ISSUE TITLE
3bot admin: split the network chatflow to two (create and add access)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2221]
should be split into two 
1- chatflow to create a network
2- chatflow to add access to an existing network

**Comment by MElborolossy** [comment]
Reduce chatflow to just print success message with WG config.

**Comment by AhmedHanafy725** [comment]
**Verified**
**Branch:** development_vdc
**Commit:** da50148a76d6e9a94699c00311e004cf50c1d878

### Create a new network
![image](https://user-images.githubusercontent.com/41957921/107516274-d2cf0500-6bb4-11eb-9047-a2caef6b3f4c.png)

### Network has an action for adding access
![image](https://user-images.githubusercontent.com/41957921/107516260-cd71ba80-6bb4-11eb-8d01-ab9d314dd20c.png)

### Add access to a network
![image](https://user-images.githubusercontent.com/41957921/107516246-c9459d00-6bb4-11eb-9899-89cfc9700250.png)
