### ISSUE TITLE
3bot admin: kubernetes support for public ips

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2223]
Right now the feature is available in the SALs only and the admin dashboard needs to reflect that for k8s solution

**Comment by m-motawea** [comment]
[ ] pool chatflows to support ipv4us
[ ] public ipv4 reservation chatflow
[ ] add optional public ip to k8s chatflow

**Comment by RafyAmgadBenjamin** [comment]
working on it on branch `development_vdc_extending_k8s_nodes_enable_ip`
- it is done but need to rebase this on the `development` branch as I need to extend the pool with `ipv4us` which is not possible on my branch now
- Update the chat flow with the `public_ip`
- Need to do full scenario testing

**Comment by RafyAmgadBenjamin** [comment]
Done 
### Branch 
`development_vdc_kube`
### PR
https://github.com/threefoldtech/js-sdk/pull/2447

**Comment by AhmedHanafy725** [comment]
If there is an empty pool (doesn't have `cu` or `su`), it wouldn't appear in the pool selection, but in case the pool doesn't have `ipv4u`,  it will appear in the pool selection normally. So if we select a pool without `ipv4u`, then enable public IP, this chat will be ended with error `pool needs additional capacity to support this workload`.

### Suggest
we can ask for enabling public IP first, then filter the pools and take into consideration `ipv4u`.

**Comment by waleedhammam** [comment]
moved back to in-progress in favor of https://github.com/threefoldtech/js-sdk/issues/2223#issuecomment-778744825

**Comment by RafyAmgadBenjamin** [comment]
### Fixed
### Commit
ae89ae1cf740b654b1cca21e197860f1c73ca243
### Branch
`development_vdc_k8s_pool_selection`

created two pools one with `ipv4u` and the other without
![image](https://user-images.githubusercontent.com/46320202/109007147-7e4b7f80-76b4-11eb-842d-0ea264be35bd.png)

In case no public IP the two pools appeared
![image](https://user-images.githubusercontent.com/46320202/109007168-83a8ca00-76b4-11eb-91bc-37274e220511.png)
![image](https://user-images.githubusercontent.com/46320202/109007177-860b2400-76b4-11eb-9657-6f90d9d381ad.png)

In case public IP only the pool with `ipv4u` appeared
![image](https://user-images.githubusercontent.com/46320202/109007186-8acfd800-76b4-11eb-83c7-fa796548c4c3.png)
![image](https://user-images.githubusercontent.com/46320202/109007201-8e635f00-76b4-11eb-88d9-46d8f39d140d.png)

### PR
https://github.com/threefoldtech/js-sdk/pull/2625

**Comment by waleedhammam** [comment]
Verified
with pub ip
![Screenshot from 2021-02-24 15-59-49](https://user-images.githubusercontent.com/10658229/109011262-60cce480-76b9-11eb-8d9b-3298e503e55f.png)

without pub ip
![Screenshot from 2021-02-24 15-59-58](https://user-images.githubusercontent.com/10658229/109011278-64f90200-76b9-11eb-97c9-b2f4832aef21.png)


deployed
![Screenshot from 2021-02-24 15-59-58](https://user-images.githubusercontent.com/10658229/109012256-7c84ba80-76ba-11eb-9500-6664d8c40d56.png)
