### ISSUE TITLE
Add chat flow for Document Server

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#2229]
back end for file manager.
this should not be valid once jimber is informed that this method should not be needed. @ken-de-moor

**Comment by RafyAmgadBenjamin** [comment]
worked on branch `development_vdc_jimber_chatflows`
![image](https://user-images.githubusercontent.com/46320202/104902563-8f9fbe80-5987-11eb-8aa7-e1e44f56b33f.png)

**Comment by waleedhammam** [comment]
Chatflow is not added to dashboard

**Comment by waleedhammam** [comment]
I shouldn't hit empty page, should be implicit inside the filebrowser chatflow
![Screenshot from 2021-01-20 12-34-41](https://user-images.githubusercontent.com/10658229/105163585-c65b0d80-5b1c-11eb-8f21-184b6eb6e3e2.png)

**Comment by waleedhammam** [comment]
blocked on: https://github.com/threefoldtech/vdc-solutions-charts/issues/56

**Comment by xmonader** [comment]
there should be no chatflow for document server.
