### ISSUE TITLE
Add chat flow for Meetings

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#2230]

**Comment by RafyAmgadBenjamin** [comment]
worked on branch `development_vdc_jimber_chatflows`

![image](https://user-images.githubusercontent.com/46320202/104606358-58c86080-5688-11eb-9722-fdb7b3c1c73a.png)

**Comment by waleedhammam** [comment]
It's still `Coming soon` in the dashboard

and when i went manually 
![Screenshot from 2021-01-20 10-57-40](https://user-images.githubusercontent.com/10658229/105151249-6a898800-5b0e-11eb-96ab-28b81319279b.png)

**Comment by waleedhammam** [comment]
Verified
![Screenshot from 2021-01-20 11-55-53](https://user-images.githubusercontent.com/10658229/105158281-78dba200-5b16-11eb-80f6-873f32c2eef4.png)

**Comment by waleedhammam** [comment]
Cert is invalid

**Comment by waleedhammam** [comment]
blocked on: https://github.com/threefoldtech/vdc-solutions-charts/issues/36

**Comment by waleedhammam** [comment]
blocked on: https://github.com/threefoldtech/vdc-solutions-charts/issues/57

**Comment by weynandkuijpers** [comment]
@tobiaschielens Can we please clos this if solved or solve and put in verification?

**Comment by weynandkuijpers** [comment]
Any update?
