### ISSUE TITLE
Add chat flow for file browser 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#2231]

**Comment by RafyAmgadBenjamin** [comment]
worked branch `development_vdc_jimber_chatflows`

![image](https://user-images.githubusercontent.com/46320202/104902652-a7774280-5987-11eb-8af6-481f24150c54.png)

**Comment by waleedhammam** [comment]
deployed vdc on latest development_vdc can't find the chatflow
![Screenshot from 2021-01-20 11-16-04](https://user-images.githubusercontent.com/10658229/105153263-e7b5fc80-5b10-11eb-82fc-86bfa15f7967.png)

**Comment by waleedhammam** [comment]
blocked on: https://github.com/threefoldtech/vdc-solutions-charts/issues/55
