### ISSUE TITLE
3bot deployer : failed to restore workloads and packages after renewing expired 3bot

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/js-sdk#2233]
### how to reproduce : 
- deployed 3bot on testnet , installed some packages on it and ubuntu container ,also created wallet there.
- did manual backup there two times . 
- wait till it expire then start it again and paid for renewing pool .
- logged again into the 3bot but nothing restored there from the manually created wallet or packages or Ubuntu solution

![Screenshot from 2021-01-13 14-50-00](https://user-images.githubusercontent.com/26298009/104486952-23af0600-55d5-11eb-9fde-d3e500e8995a.png)
![Screenshot from 2021-01-13 14-51-05](https://user-images.githubusercontent.com/26298009/104487033-417c6b00-55d5-11eb-844d-91fb8a8ab229.png)
![Screenshot from 2021-01-13 14-51-20](https://user-images.githubusercontent.com/26298009/104487043-450ff200-55d5-11eb-9015-2eefd503f035.png)
![Screenshot from 2021-01-13 14-51-41](https://user-images.githubusercontent.com/26298009/104487061-4c370000-55d5-11eb-8c63-e7afcb428222.png)

### after restoring 3bot : 
just found the backups listed nothing else 

![Screenshot from 2021-01-13 19-16-35](https://user-images.githubusercontent.com/26298009/104487739-25c59480-55d6-11eb-82c5-2a1831bab51d.png)

![Screenshot from 2021-01-13 19-31-03](https://user-images.githubusercontent.com/26298009/104487573-f31b9c00-55d5-11eb-893f-e18e73d3fa3f.png)

### pool :
https://explorer.testnet.grid.tf/api/v1/reservations/pools/39
### workloads:
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/82
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/83
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/84

**Comment by xmonader** [comment]
logs of the first deployment 

```
3) "[*] Starting threebot in background ...\n"
1) "message"
2) "ahmedthabet-threebot-ohno-stderr"
3) "2021-01-13 20:11:30.882 | INFO     | __main__:main:32 - Generating guest identity ...\n"
1) "message"
2) "ahmedthabet-threebot-ohno-stderr"
3) "2021-01-13 20:11:33.218 | WARNING  | __main__:main:79 - can not create user with name:ahmedthabet_ohno, error={\"error\": \"3Bot name or password is incorrect\"}: Reinitalizing backup for new user\n"
1) "message"
2) "ahmedthabet-threebot-ohno-stderr"
3) "2021-01-13 20:11:43.219 | INFO     | __main__:main:89 - Taking backup ...\n"
1) "message"
2) "ahmedthabet-threebot-ohno-stderr"
3) "2021-01-13 20:12:00.776 | INFO     | __main__:main:95 - Initalizing main wallet ...\n"
1) "message"
2) "ahmedthabet-threebot-ohno-stderr"
3) "2021-01-13 20:12:01.029 | INFO     | __main__:main:103 - Starting threebot ...\n"
1) "message"

```

and on the first backup server .htpasswd updated correctly and snapshot been taken
```
root@testnet-backupserver-1:~/backup# cat .htpasswd 
ahmedthabet_ohno:$2y$05REDACTED..........
root@testnet-backupserver-1:~/backup# ls
ahmedthabet_ohno
root@testnet-backupserver-1:~/backup# ls ahmedthabet_ohno/
config  data  index  keys  locks  snapshots
root@testnet-backupserver-1:~/backup# ls ahmedthabet_ohno/snapshots/
0e43c940d0c57b09f7f40c70af9a7606486546ba7caefffbce423e94058bffdb  31b9403fdf68e9fd677d636b38f98a1cea48ddd9f58c317a4896a478f369398b
259c5dfbe8d188b9f6fde38c67e1c8b5dda955df0497cc46a939d7e09b086085  add999c820e529303b5f940114b52a2ade70708d1bf42192630766c2c5a0e248


```

**Comment by xmonader** [comment]
Debugging using codeserver 

```
JS-NG> snapshots = j.data.serializers.json.loads(BACKUP_ACTOR.snapshots())                                      
JS-NG> snapshots                                                                                                
{'data': [{'time': '2021-01-13T20:39:30.270368098Z', 'tree': '54e571f2254c63c6087e56a1afc8595f650cf568bfaf417a2a
d5512bec65ba5b', 'paths': ['/root/.ssh'], 'hostname': 'zosv2tst-7', 'username': 'root', 'tags': ['init', '161057
0361'], 'id': '42ce38d9441e1b5bda4850b727737868c595418531197c1f043cf6c419ec519d', 'short_id': '42ce38d9'}, {'tim
e': '2021-01-13T20:35:31.657364335Z', 'parent': '93ac3e6cae6ec0d29d30711054ee9bb5ac527be976f70116f4dcea34db0da6b
f', 'tree': 'ae80cf6d1cb539df189c33fb5a96fc3a51a3c3812bb117c0c9991b01fb0326f2', 'paths': ['/root/.ssh'], 'hostna
me': 'zosv2tst-3', 'username': 'root', 'tags': ['mashi', '1610570124'], 'id': 'df1dc1e20d4f7e5aaba82ad4d86fc8dcd8fb43fc792a534532fa92bff746e1ba', 'short_id': 'df1dc1e2'}, {'time': '2021-01-13T20:27:40.235603427Z', 'tree': '252f635673278e0a6e29df59fd3e2ad3f9aa13dffa4e295c3b9956258a228b47', 'paths': ['/root/.ssh'], 'hostname': 'zosv2tst-3', 'username': 'root', 'tags': ['init', '1610569652'], 'id': '93ac3e6cae6ec0d29d30711054ee9bb5ac527be976f70116f4dcea34db0da6bf', 'short_id': '93ac3e6c'}]}
```


and when recovered the snapshot manually it worked, so the problem is coming from 

![image](https://user-images.githubusercontent.com/64129/104510839-75b35400-55f4-11eb-844d-ff89b713a996.png)

**Comment by xmonader** [comment]
last backup is `isaworks`

![image](https://user-images.githubusercontent.com/64129/104519089-8d450980-5601-11eb-8c09-5f05ef1db452.png)

`aa.3bot` still in the admins
![image](https://user-images.githubusercontent.com/64129/104519100-903ffa00-5601-11eb-9311-47e64b46cffd.png)

farm mgmt recovered
![image](https://user-images.githubusercontent.com/64129/104519108-946c1780-5601-11eb-8257-e15e5f7eb227.png)

wallets recovered too
![image](https://user-images.githubusercontent.com/64129/104519183-b1084f80-5601-11eb-900b-74ed671220b5.png)

**Comment by hossnys** [comment]
verified  : 
 - before expired : 

![Screenshot from 2021-01-14 10-52-02](https://user-images.githubusercontent.com/26298009/104597738-5eb94400-567e-11eb-8f22-4957a491f9a8.png)
![Screenshot from 2021-01-14 10-52-52](https://user-images.githubusercontent.com/26298009/104597740-5f51da80-567e-11eb-8094-242998af9fe9.png)
![Screenshot from 2021-01-14 14-42-04](https://user-images.githubusercontent.com/26298009/104597745-5fea7100-567e-11eb-8fc6-0507ebaf4191.png)
![Screenshot from 2021-01-14 14-42-45](https://user-images.githubusercontent.com/26298009/104597747-60830780-567e-11eb-8769-1fc3c062256b.png)
![Screenshot from 2021-01-14 10-48-55](https://user-images.githubusercontent.com/26298009/104597729-5cef8080-567e-11eb-926c-c47491d795a7.png)


- after starting 3bot again :

![Screenshot from 2021-01-14 15-38-29](https://user-images.githubusercontent.com/26298009/104597960-a9d35700-567e-11eb-9a9e-235d259d61fc.png)
![Screenshot from 2021-01-14 15-38-44](https://user-images.githubusercontent.com/26298009/104597963-ab048400-567e-11eb-839f-16f31252e03b.png)
![Screenshot from 2021-01-14 15-38-54](https://user-images.githubusercontent.com/26298009/104597965-ab9d1a80-567e-11eb-97e1-761986300440.png)
![Screenshot from 2021-01-14 15-39-54](https://user-images.githubusercontent.com/26298009/104598065-ca9bac80-567e-11eb-8dcb-0cdcd4426698.png)
