### ISSUE TITLE
3bot deployer stop button claims it will delete all backups

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2234]
![image](https://user-images.githubusercontent.com/64129/104506105-9a57fd80-55ed-11eb-87f2-7507660a2522.png)

While this is clearly not true, as it goes to threebot/stop api endpoint not threebot/destroy, but caused by reusing hardcoded message in the ActionConfirmation.vue https://github.com/threefoldtech/js-sdk/blob/d4639cc4a5db5ab40b04e9add743999c5b2a27d6/jumpscale/packages/threebot_deployer/frontend/components/solutions/ActionConfirmation.vue#L13

- make the dialog configurable in a message instead of sharing false message between the two actions 
- also the confirmation flash said `3bot destroyed` while it should have been `3bot stopped`

**Comment by ranatrk** [comment]
verified on https://deploy3bot.devnet.grid.tf/:
![Screenshot from 2021-01-18 11-56-04](https://user-images.githubusercontent.com/17128393/104900090-4ef27600-5984-11eb-9490-42ed16d58610.png)
![Screenshot from 2021-01-18 11-56-24](https://user-images.githubusercontent.com/17128393/104900094-4f8b0c80-5984-11eb-9571-3481abb4bd09.png)
