### ISSUE TITLE
inconsistent log channels for 3bot creation and 3bot restoration

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2235]
https://github.com/threefoldtech/js-sdk/blob/development/jumpscale/packages/threebot_deployer/bottle/utils.py#L405

- in creation: it's username-threebot-solutioname-stdout, username-threebot-solutioname-stderr
- in restore:  it's username-solutioname-stdout, username-solutioname-stderr

**Comment by xmonader** [comment]
done in https://github.com/threefoldtech/js-sdk/commit/b6ff3f0c7cec8225f5bba015a5ab741a8c5ddc94

**Comment by ranatrk** [comment]
verified
steps:
- subscribe to stream for 3bot with name `test008` and user `ranatarek.3bot` on redis channel `ranatarek-threebot-test008-stdout` and `ranatarek-threebot-test008-stderr`
- deploy 3bot with name `test008` using dashboard 
- check logs in the subscribed channel
- Destroy the 3bot from dashboard with name `test008`
- subscribe to stream for 3bot with name `test008` and user `ranatarek.3bot` on channel `ranatarek-threebot-test008-stdout` and `ranatarek-threebot-test008-stderr`
- Start 3bot with name `test008` again with providing the same password as initial deployment
- logs are available in subscribed channels
