### ISSUE TITLE
3Bot: name entry chat screen:  add description of name can only be lowercase letter.

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2237]
You only find out that you cannot use number, special characters and spaces after you have put on of them in the name and press ```NEXT```.  Add in the description a guideline of what is accepted

"A 3bot name can only consist of lowercase letter, no special character, numbers or spaces allowed"

**Comment by xmonader** [comment]
as soon as I leave the textbox I get the validation immediately 
![image](https://user-images.githubusercontent.com/64129/108053960-bb7d9500-7056-11eb-8728-226038e01771.png)

and the description is already quite long to the point it's dismissable :S what do you suggest?

**Comment by weynandkuijpers** [comment]
I guess I was expecting that you could show the warning when I typed a number or capital letter. Some "active" input areas give you direct feedback when you type about the validity (or not) of your input.  Not sure if this is possible.  With regards to the text:

"Just like humans, each 3Bot needs its own unique identity. Please enter a name for your new 3Bot. This name can only consist of lower case letters and no special characters."

**Comment by hossnys** [comment]
verified
![Screenshot from 2021-02-23 23-33-40](https://user-images.githubusercontent.com/26298009/108911185-9e852b00-762f-11eb-82fe-f517a8925f9d.png)
