### ISSUE TITLE
include zdb password in the zdbs json file

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2239]
zstor config file includes the passwords for each zdb, please have it in the zdb info json file as well

**Comment by ranatrk** [comment]
verified on vdc deployment using https://vdc.testnet.grid.tf/
![Screenshot from 2021-01-18 17-19-46](https://user-images.githubusercontent.com/17128393/104933376-80356b00-59b1-11eb-9db9-ce08df5b9086.png)
