### ISSUE TITLE
j.clients.sshkey.delete() is not deleting the generated keys on file system

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/js-sdk#2240]
I tried to create and delete an ssh key using 
```
cl = j.clients.sshkey.get("instance")
cl.generate_keys()
```
the keys are generated on file system 
then after I did 
```
j.clients.sshkey.delete("instance")
```
the instance got deleted but on file system level it didn't delete the files
![Screenshot from 2021-01-14 09-57-31](https://user-images.githubusercontent.com/1689456/104561046-6dd4cd80-564f-11eb-850d-cc5d79b96a8c.png)
![Screenshot from 2021-01-14 10-04-11](https://user-images.githubusercontent.com/1689456/104561345-ef2c6000-564f-11eb-9138-918f970bde4b.png)

**Comment by ashraffouda** [comment]
turned out this is the default behaviour

**Comment by xmonader** [comment]
delete will delete the instance configurations only, but won't delete the generated key (or the key it got set to use) I think that's safer, because if the sshkey existed on the system and you created a client to it and wanted to delete the client you don't want to delete the sshkey
