### ISSUE TITLE
The deployment message and initialization check are tightly coupled with a specific solution type

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/js-sdk#2242]
### Description

The solution assumes that there's a domain name assigned in the initialization step to check if it's reachable. Which is not the case for the blockchain solution

**Comment by xmonader** [comment]
maybe better to define REQUIRES_DOMAIN = True as the default and for solutions that don't have domain we set it to False and skip the whole flow for domains

**Comment by MElborolossy** [comment]
Verified
Digibyte (Blockchain solution) deployed successfully
![image](https://user-images.githubusercontent.com/11272864/109139385-25d3bb00-7764-11eb-95f8-5349db2661ed.png)
