### ISSUE TITLE
don't show kubeconfig in the deployment flow for the vdc deployer

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2245]
let's keep the option from the vdc dashboard only

**Comment by AhmedHanafy725** [comment]
**Verified**

![image](https://user-images.githubusercontent.com/41957921/107245881-531c2b80-6a38-11eb-94a0-677ca1852dad.png)

![image](https://user-images.githubusercontent.com/41957921/107245947-65966500-6a38-11eb-993f-03a6a673eab6.png)
