### ISSUE TITLE
VDC threebot update endpoint stops the server and doesn't start it

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/js-sdk#2246]
### Description

After deploying a vdc i opened the update endpoint `https://3boturl/vdc_dashboard/api/update`. The site became unreachable and it didn't start again. My guess is that some service catches the SIGTERM and doesn't terminate.

Accessing the website doesn't produce any logs which means the server probably stopped. But there're logs printed every now and then from `k8s_auto_extend` service.

Logs:
![Screenshot from 2021-01-14 13-52-08](https://user-images.githubusercontent.com/13040543/104587709-fa8f8380-566f-11eb-9cdd-9288381107ae.png)

**Comment by abom** [comment]
The same here, it never came back again.

**Comment by OmarElawady** [comment]
It appears that some service blocks the stopping, logs for starting and stopping the service is added. if happened again, please add the vdc name.

**Comment by OmarElawady** [comment]
Happened again with a new vdc and from the logs it appears that gedis or gedis_http doesn't return the stop method because the services don't get stopped. After some investigations, the SIGTERM is handled twice by the rack and also by the gedis server itself, which causes the stop method to get called twice, maybe that's the reason for blocking. For now, the process is killed with SIGKILL if it didn't stop after two minutes gracefully.
https://github.com/threefoldtech/js-sdk/pull/2364

**Comment by hossnys** [comment]
verified and the server is reachable again after running it .

![Screenshot from 2021-02-24 02-39-46](https://user-images.githubusercontent.com/26298009/108973881-8f34ca80-768d-11eb-8fce-312d0da3546a.png)
