### ISSUE TITLE
the displayed message is not accurate when extending an existing pool

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/js-sdk#2249]
when extending an existing capacity pool from the 3bot UI it gives an identical message to one displayed when you create a new pool > `you just created a new capacity pool`
 
should be something like you `you have successfully extended your capacity pool` when the user selects to extend an existing one. (maybe also take into consideration if the user have extended or reduced his pool - as the chat flow already accepting lower values than the initial values previously entered - )

![Screenshot from 2021-01-14 13-00-30](https://user-images.githubusercontent.com/42457449/104589047-fa908300-5671-11eb-8181-7e502988f17f.png)

### Steps to reproduce

- from Capacity Pools page, click create/extend pool
- select extend
- select an existing pool
- choose a new Capacity Pool values
- continue to succeed message that displays the inaccurate message.

**Comment by ranatrk** [comment]
The change was already done when splitting the pools chatflows to seperate extend and create chatflows in d02f2bbd77f99fa739714be0b54e2aa2293b3aac
![Screenshot from 2021-01-26 12-00-41](https://user-images.githubusercontent.com/17128393/105830407-23980880-5fce-11eb-9375-f14af5b430bc.png)

**Comment by AhmedHanafy725** [comment]
**Verified**
**Branch:** development_vdc
**Commit:** da50148a76d6e9a94699c00311e004cf50c1d878


### After creating
![image](https://user-images.githubusercontent.com/41957921/107514329-30158700-6bb2-11eb-888a-b6221c89fb21.png)


### After extending
![image](https://user-images.githubusercontent.com/41957921/107514312-2c820000-6bb2-11eb-8350-be644260bd19.png)
