### ISSUE TITLE
extend capacity pool dialogue accepts lower values than the currently reserved capacity

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/js-sdk#2250]
### Description

when extending an existing capacity pool the dialogue will accept lower values than the currently reserved capacity and I am not sure if that is intended (reduce the capacity).

- it should be clear if that intended by making the name obvious like 'extend/reduce' or 'change capacity'
- if that intended, in the process we should give the user clear insight into what will happen. like you 'will be extended... from .. to ..' or you will 'will be reduced ... from .. to ..'
- its important to show the initial values (current capacity) when prompt the user to enter the new values instead of the empty fields that show in the screenshot. so the process will be less error-prone for the user, and the user will know what he actually doing by increasing or decreasing his old values.

![Screenshot from 2021-01-14 13-01-49](https://user-images.githubusercontent.com/42457449/104594343-b0ab9b00-5679-11eb-97b4-64fb58441e60.png)

**Comment by waleedhammam** [comment]
we only extend the pools, the amount we enter is the extra units.

for example i've a pool with 1 cu and 1 su for a day, and i want it to last for one more day, i'll only add the extra quota, it's completely new reservation will be appended to the old one

**Comment by sameh-farouk** [comment]
> we only extend the pools, the amount we enter is the extra units.
> 
> 
> 
> for example i've a pool with 1 cu and 1 su for a day, and i want it to last for one more day, i'll only add the extra quota, it's completely new reservation will be appended to the old one

I understand now. But it needs to be more clear I think to the user. More explicit instructions should solve this confusion.

**Comment by waleedhammam** [comment]
> I understand now. But it needs to be more clear I think to the user. More explicit chatflow instructions should solve this confusion.

it's divided into 2 chatflows now

**Comment by AhmedHanafy725** [comment]
Verified in #2220
