### ISSUE TITLE
VDC: mastodon solution 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2251]
would be great to have mastodon as solution in the VDC as alternative to twitter https://joinmastodon.org 

- requires:  https://github.com/threefoldtech/vdc-solutions-charts/issues/46

**Comment by abom** [comment]
Working on Theefold connect support.

**Comment by RafyAmgadBenjamin** [comment]
### fixed
### branch
`development_mastodon`

### PR
https://github.com/threefoldtech/vdc-solutions-charts/pull/136
https://github.com/threefoldtech/js-sdk/pull/2891
