### ISSUE TITLE
3bot: Farm management: should allow farmer to set custom prices for specific customer

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2252]
once [this](https://github.com/threefoldtech/tfexplorer/issues/277) is accepted it's safe to extend the farm management to allow setting custom pricing for a specific 3bot user

suggestion is: 
![image](https://user-images.githubusercontent.com/64129/107208736-ab3c3900-6a0a-11eb-848b-64e2017b9be5.png)

- In My Farms table we have (Set default farm prices) action button to set default farm prices (dialog asking for CU, SU prices)
- A new table has (custom prices list) 
  - threebot id
  - threebot name
  - custom prices info joined string (CU: X, SU: Y)
  - action button to edit custom price

**Comment by sasha-astiadi** [comment]
@muhamadazmy could you verify on explorer if it works

**Comment by waleedhammam** [comment]
works as expected, to be continued in https://github.com/threefoldtech/js-sdk/issues/2624
