### ISSUE TITLE
Extend chatflows testsuite

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/js-sdk#2253]
### Description

currently only basic scenarios are implemented for 3bot deploy-er test coverage.
Need to extend test suite with unhappy path scenarios

### Implementation

current test coverage:

https://github.com/threefoldtech/js-sdk/tree/development/docs/tests/sals/automated_chatflows

#### 1- pools
- create/extend a pool with 0 units, should success
- create/extend a pool with negative units, should fail 
- create/extend a pool with a non-existing farm, should fail
- create/extend a pool with an empty wallet, should fail

#### 2- threebot deployer
- deploy a threebot with an expiration on the past, should fail to extend.
- deploy a threebot then try to create another one with the same name, should fail
- change the location of a running threebot, should fail
- change the size of a running threebot, should fail
- start a running threebot, should fails
- deploy a threebot and check its expiration time should be as the exipration has been set while deploying
- deploy a threebot and set ssh key, then ssh to it

#### 3- admin dashboard solutions
- deploy an ubuntu container with different versions
- deploy an ubuntu with a specific node.
- deploy a kubernetes with different sizes
- deploy a s3 minio with master/slave setup
- deploy a network then add access to it
- deploy a network with ipv6 
- deploy  a network with a specific IP range
- create a generic container with a non-exist flist, should fail

**Comment by mhost39** [comment]
1- Pools Done
2- Threebot deployer in progress 
3- deploy an ubuntu container with different versions Done

**Comment by mhost39** [comment]
more test scenarios:
1- deploy a container with 0 unit pool.
2- deploy an ubuntu and push the container logs onto an external redis channel.
3- deploy a kubernetes with enable public IP.
4- deploy a container then ssh to it.
5- deploy a s3 minio with SSD and HDD.
6- deploy a s3 minio with a global IPv6 address.
7- expose solution with TRC and NGINX.
8- expose solution with custom domain.
9- deploy virtual machine (happy path).
10- deploy a container with attach an extra volume to the container.
11- deploy a container with environment variables.
