### ISSUE TITLE
allow the vdc dashboard user to view/download their last month transactions and their plan billing items

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2254]
as a user, I should be able to see what the billing service is charging me for and how often too

## Downloading transactions history
the suggestion is export all transactions from stellar client on the prepaid wallet to the user in csv file, can be for as long as needed

## UI
- maybe in the wallet UI we can also link the prepaid wallet account to stellar expert to be able to view (should be the easiest) 
- another option is showing small cards representing the transaction in a popup

**Comment by waleedhammam** [comment]
Suggestion:

![Screenshot from 2021-01-27 11-39-39](https://user-images.githubusercontent.com/10658229/105972539-64f2eb80-6094-11eb-9a00-c14b88973c39.png)

In the wallet info pane, we add a button to go to stellar expert.
example: https://stellar.expert/explorer/public/account/GCKLGWHEYT2V63HC2VDJRDWEY3G54YSHHPOA6Q3HAPQUGA5OZDWZL7KW

and from there user can see histroy, download, .. etc

button will be in that location
![Screenshot from 2021-01-27 11-39-44](https://user-images.githubusercontent.com/10658229/105972664-87850480-6094-11eb-99a0-ca39d5330625.png)

**Comment by xmonader** [comment]
@gmachtel agrees with the current implementation
