### ISSUE TITLE
vdc 3bot controller backup

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2257]
- should be the same like we do for 3bots in 3bot deployer

**Comment by waleedhammam** [comment]
- Users don't have access to admin dashboard
- It's only view the vdc info/solutions/wallet, that info we pass to the 3bot on deployment.
- If the vdc is expired it will be redeployed with new identity so nothing to do with the backup

**Comment by waleedhammam** [comment]
duplicate
