### ISSUE TITLE
VDC: allow adding multiple traefik entrypoints in the same call

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2261]
![image](https://user-images.githubusercontent.com/64129/104710037-47369580-5728-11eb-85fb-f48bc3558da0.png)

Right now if you know the traefik entrypoints you need ahead of time for the solution and in case they were more than one you will execute the add_traefik_entrypoint twice at least which isn't really practical to keep redeploying traefik while you know the full information already about the entrypoints. Suggestion is to make another function `add_traefik_entrypoints` that supports adding multiple entrypoints in the same time

**Comment by MElborolossy** [comment]
Verified
commit df0928483709b0d1366ee0588565a9ba55ce83d2

- List traefik endpoint before adding

![image](https://user-images.githubusercontent.com/11272864/108998610-d761e600-76a9-11eb-9817-d929a3961e3c.png)

- Add 2 entrypoints

![image](https://user-images.githubusercontent.com/11272864/108998733-00827680-76aa-11eb-832a-2bd6c3b98116.png)

- List traefik endpoint after adding

![image](https://user-images.githubusercontent.com/11272864/108998810-1c861800-76aa-11eb-8e87-3df184e0e15e.png)
