### ISSUE TITLE
Prepare master branch / master flist for threebot

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#2274]
- To use master branch / flist to use with mainnet deployers instead of development

**Comment by waleedhammam** [comment]
in https://github.com/threefoldtech/js-sdk/pull/2281 it'll use the current branch for deployment and entrypoint

**Comment by ranatrk** [comment]
verified
By adding pdb in the threebot deployer, and checking the `self.branch` after switching branches and restarting threebotserver the branch change was reflected
![Screenshot from 2021-01-20 11-45-36](https://user-images.githubusercontent.com/17128393/105157393-99efc300-5b15-11eb-88a2-ad10dc9321d2.png)
![Screenshot from 2021-01-20 11-48-05](https://user-images.githubusercontent.com/17128393/105157398-9b20f000-5b15-11eb-95eb-83c5029e1c7c.png)
