### ISSUE TITLE
Error message in charts not displayed properly  

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#2275]
`Release name already exists` Error message should be displayed differently as an error, ex. with red color
![image](https://user-images.githubusercontent.com/46320202/104894988-02a43780-597e-11eb-912c-f80a5f226704.png)
![image](https://user-images.githubusercontent.com/46320202/104895324-675f9200-597e-11eb-95f7-ed37b0d70444.png)

**Comment by dmahmouali** [comment]
I think we should use the frontend validator `not_exixt` here
https://github.com/threefoldtech/js-sdk/blob/development_vdc/jumpscale/packages/chatflows/frontend/mixins/field.js#L38

**Comment by ranatrk** [comment]
verified
![Screenshot from 2021-01-19 12-11-29](https://user-images.githubusercontent.com/17128393/105020073-837f3400-5a4f-11eb-977d-28101e34726f.png)
