### ISSUE TITLE
Issue in string_ask with argument is_identifier

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#2277]
In string_ask method passing, `is_identifier` is `True` same as passing it `False`
In both cases, it validates that it is an identifier 

To prevent this don't send is_identifier 
![image](https://user-images.githubusercontent.com/46320202/104898007-c377e580-5981-11eb-8a70-246c1e5d7bf5.png)

![image](https://user-images.githubusercontent.com/46320202/104898791-b9a2b200-5982-11eb-8a49-0900537913a6.png)

**Comment by xmonader** [comment]
Should be resolved now

**Comment by m-motawea** [comment]
for now just remove the kwarg of `is_identitifier`

**Comment by RafyAmgadBenjamin** [comment]
fixed on branch `development_vdc_chatflow_questions_issue`

**Comment by waleedhammam** [comment]
Verified on development_vdc latest
