### ISSUE TITLE
Conflicting timelines for VDC expiration

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/js-sdk#2295]
While testing VDC on devnet a few days ago on Friday, I noticed that the expiration warning pop up on the main page showed a different time than what I saw on the wallet screen. In this case, the pop up said 14 hours until expiration on a newly deployed VDC, while the wallet page says that it expires on 30/01/2021, 09:15:45 when today is 15/01/2021 at 19:50 local time (PST).

**Comment by m-motawea** [comment]
since the current prices are not sufficient to do the actual deployment on the grid, whenever the vdc is changed (node added, pools extended, ... etc) the wallet funds are decreased more than expected so the overall expiration is reduecd.

how we calculate the expiration shown in the dashboard:
```python
def calculate_expiration_value(self, load_info=True):
        funded_period = self.calculate_funded_period(load_info)
        pools_expiration = self.get_pools_expiration()
        return pools_expiration + funded_period * 24 * 60 * 60
```
in which funded period is always reduced

**Comment by scottyeager** [comment]
This is what I'm seeing with a fresh VDC on testnet, with no changes made yet. I didn't get screenshots before, so maybe this will help to make it clearer:

![image](https://user-images.githubusercontent.com/17682591/106191973-6ab60300-6160-11eb-9ac6-e79ecc7b11c9.png)

![image](https://user-images.githubusercontent.com/17682591/106192028-80c3c380-6160-11eb-8745-8c192e575bbe.png)

**Comment by xmonader** [comment]
I added this to 2.4 as blocked. the problem as mentioned before is the explorer prices are higher than the fixed plan prices #1925 and one way to address that is allowing #2252 which is blocked on this https://github.com/threefoldtech/tfexplorer/issues/277, another solution would be that we keep sending money to the user (which can and will be abused spepcially that we share the wallet secret with the user), another reason is the [cost of TFT transactions ](https://github.com/threefoldfoundation/tft-stellar/issues/269)

**Comment by weynandkuijpers** [comment]
Newly deployed VDC presents two different expiration times in the same screen (time/date of the screenshot is 10:05- GST - 05/02/2021):
![image](https://user-images.githubusercontent.com/13766992/106996456-79bd3680-679a-11eb-8da2-432973f1c14f.png)

Even though we have the issue as labour described we cannot present them to the end user at the same time.  We have to decide which calculation method we will use and use that one for every presentation expiration time everywhere.

**Comment by weynandkuijpers** [comment]
Any update?

**Comment by xmonader** [comment]
@weynandkuijpers 2 PRs are ready to merge on explorer and farmmgmt side, all what is left is coming up with deals of the CU/month, SU/month that makes the plan correct.

**Comment by weynandkuijpers** [comment]
Sounds great.  What deals do you refer to -> price per CU/SU of the farms that will participate in the VDC service deployment

**Comment by xmonader** [comment]
@weynandkuijpers  Yup indeed also the https://github.com/threefoldfoundation/tft-stellar/issues/269 should be addressed, otherwise it will cost 72 TFT extra every month

**Comment by xmonader** [comment]
for the 72TFT differencce we will implement as a separate service https://github.com/threefoldtech/js-sdk/issues/2600 ... would have preferred that to be fixed on the tft-stellar level.

**Comment by weynandkuijpers** [comment]
@xmonader plnn the stellar fix as a feature for one of the future releases. Is this something you can put on now for the 3.0 release?

**Comment by robvanmieghem** [comment]
@xmonader @weynandkuijpers The mobile wallet change is currently being tested on the stellar testnet, as the change to 0.01 TFT is deployed on the testnet.threefold.io.

**Comment by sasha-astiadi** [comment]
link to issue : TFConnect: Allow tft fee of less than 0.1 if the tx funding service requires less #207

**Comment by weynandkuijpers** [comment]
@sasha-astiadi link 207 does not make any sense.  Please remove.

As discussed - changes have been implemented, backend service put into production. So this issue is  done / putting it into verification.

**Comment by hossnys** [comment]
verified :
the expiration date of VDC in the wallet info page = VDC validity remaining days +14 days grace period
![Screenshot from 2021-02-24 14-42-54](https://user-images.githubusercontent.com/26298009/109002932-83f29680-76af-11eb-97ff-f97b9c1c697a.png)
![Screenshot from 2021-02-24 14-43-07](https://user-images.githubusercontent.com/26298009/109002937-8523c380-76af-11eb-95ed-cf70e197a141.png)
