### ISSUE TITLE
hard coded  config in Taiga chart

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#2296]
there are lots of staff hardcoded in taiga chart 
so when I  tried to deploy twice it crashed as it found the name of the service and `configmap`  is already there 
![image](https://user-images.githubusercontent.com/46320202/105176924-9583d400-5b2e-11eb-99db-c7d1c518cb77.png)
![image](https://user-images.githubusercontent.com/46320202/105177070-cfed7100-5b2e-11eb-9d01-e5f22eeb89da.png)

also 
all the configuration for the chart must be centralized in the `values` file to make use of the advantage of using helm charts

**Comment by xmonader** [comment]
Let's move it to next and @RafyAmgadBenjamin please prepare a PR for it if possible

**Comment by MElborolossy** [comment]
After the last updates that mentioned [here](https://github.com/threefoldtech/js-sdk/issues/2523#issuecomment-778776466)
Taiga can deploy twice successfully as it is two different namespaces
