### ISSUE TITLE
failed to find zdb after added it

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/js-sdk#2299]
i try to add zdb by:
 ```
zdb_monitor = vdc.get_zdb_monitor()
zdb_monitor.extend(10, ["lochristi_dev_lab"])
```
and don't find them after load_info

wids: [20178]

**Comment by waleedhammam** [comment]
verified
![Screenshot from 2021-01-25 14-44-41](https://user-images.githubusercontent.com/10658229/105707611-e1ae8a00-5f1b-11eb-9d1a-05af5bbca4c9.png)
![Screenshot from 2021-01-25 14-45-17](https://user-images.githubusercontent.com/10658229/105707666-f723b400-5f1b-11eb-964e-7c508037e478.png)
