### ISSUE TITLE
The headers or library files could not be found for zlib while installing js-ng with macOs Catalina 10.15.7

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/js-sdk#2307]
####  requirements  
- macOS Catalina 10.15.7 
-  js-sdk  development 
- python 3.9

while run 
```
cd js-sdk
poetry install
```
we got the attached logs [poetry_install_log.txt](https://github.com/threefoldtech/js-sdk/files/5849854/poetry_install_log.txt)

problem with
• Installing gevent (1.4.0)
 • Installing pillow (7.2.0)

**Comment by waleedhammam** [comment]
python 3.9 is not supported yet, we can go with 3.8

**Comment by rkhamis** [comment]
@Pishoy can you test with python 3.8?

**Comment by ramezsaeed** [comment]
docs need to updated with the python supported versions

**Comment by Pishoy** [comment]
yes works with version 3.8, plz update the document
