### ISSUE TITLE
module name containing character not allowed in Python identifiers.

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/js-sdk#2313]
Rename this module to remove the offending character '-', or changing it to an underscore '_'.

**jumpscale/install/codeserver-install.py**

Reasons:
- Python module with an invalid name cannot be imported unless using a special syntax (hack)
- Nobody expects a module name with a dash
- It's against the recommendations of the Python Style Guide

**Comment by abom** [comment]
This can be renamed for sure, it was not intended to be a part of "jumpscale" library. Another option to it move it to scripts directory or so outside of "jumpscale" namespace.

**Comment by sameh-farouk** [comment]
great, I'm with renaming it, whether it moved or not.
