### ISSUE TITLE
[Errno None]  Error received when deploying eVDC

### ISSUE THREAD

**Issue by BenjellounO** [threefoldtech/js-sdk#2315]
After I submitted the payment, and while loading the VDC, I received this error message.

Note that I received my TFTs back. any ideas on how to solve this issue? 

![vdc test error](https://user-images.githubusercontent.com/51067842/105469357-8711f580-5cb1-11eb-9e86-69ba47db12b5.PNG)

**Comment by xmonader** [comment]
duplicate of https://github.com/threefoldtech/zos/issues/1150

**Comment by waleedhammam** [comment]
verified
