### ISSUE TITLE
Restart a 3bot which ran out of time (finding) results in error

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2316]
Restarting an existing 3bot that ran out of gas results in the following error

![image](https://user-images.githubusercontent.com/13766992/105626685-c9226f00-5e4a-11eb-9ce9-03e08fa20df4.png)

3bot name:
mainjetser

**Comment by weynandkuijpers** [comment]
Tried two existing (but stopped) 3bots.  Both failed to restart

**Comment by m-motawea** [comment]
please add which network. mainnet, testnet, devnet?

**Comment by weynandkuijpers** [comment]
testnet - forgot to mention it.

**Comment by m-motawea** [comment]
@weynandkuijpers is it a duplicate of https://github.com/threefoldtech/js-sdk/issues/2319? same alert id is shown in both screenshots.
