### ISSUE TITLE
Cannnot ssh into a new deployed 3bot

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2317]
Deployed a 3bot on testnet (jetsetter). after deploying it and saving / activating the wireguard tunnel it does not respond to the presented IP address.

![image](https://user-images.githubusercontent.com/13766992/105627000-5797f000-5e4d-11eb-8fe8-1d244280289d.png)

```
john@RescuedMac:~/opt/wireguard$ sudo wg-quick up ./jetsetter.conf 
[sudo] password for john: 
Warning: `/home/john/opt/wireguard/jetsetter.conf' is world accessible
[#] ip link add jetsetter type wireguard
[#] wg setconf jetsetter /dev/fd/63
[#] ip -4 address add 100.64.100.1/32 dev jetsetter
[#] ip link set mtu 1420 up dev jetsetter
[#] ip -4 route add 100.64.100.0/32 dev jetsetter
[#] ip -4 route add 10.100.0.0/16 dev jetsetter
john@RescuedMac:~/opt/wireguard$ ssh root@10.100.0.2
^C
john@RescuedMac:~/opt/wireguard$ ping 10.100.0.2
PING 10.100.0.2 (10.100.0.2) 56(84) bytes of data.
```

**Comment by m-motawea** [comment]
please add relevant workload ids for the network

**Comment by weynandkuijpers** [comment]
Bug is a different one:  See information from the 3bot deployer

![image](https://user-images.githubusercontent.com/13766992/105704693-9f3f7a00-5f28-11eb-9a59-01e3c384672e.png)

So the IP is not 10.100.0.2 but 10.100.2.2

**Comment by m-motawea** [comment]
@weynandkuijpers was the container redeployed?

from the explorer, I can see 
- https://explorer.testnet.grid.tf/api/v1/reservations/workloads/2632
in which the container had the ip address 10.200.0.2 which matches the ip address in the screenshot so I assume it was the first deployment.
and then
- https://explorer.testnet.grid.tf/api/v1/reservations/workloads/2756
in which the container had the ip address 10.200.2.2
and now
- https://explorer.testnet.grid.tf/api/v1/reservations/workloads/3012
in which the container has ip address 10.200.3.2

**Comment by weynandkuijpers** [comment]
maybe - I deleted everything and did a new one:
- network: testnet
- 3bot name: jetserjetuno


![Screenshot_20210125_172627](https://user-images.githubusercontent.com/13766992/105712364-1b3ebf80-5f33-11eb-9da9-2c3bfc821fab.png)

and I downloaded and activated the wireguard config
```
john@RescuedMac:~/opt/wireguard$ sudo wg
john@RescuedMac:~/opt/wireguard$ sudo wg-quick up ./latest.conf 
Warning: `/home/john/opt/wireguard/latest.conf' is world accessible
[#] ip link add latest type wireguard
[#] wg setconf latest /dev/fd/63
[#] ip -4 address add 100.64.100.1/32 dev latest
[#] ip link set mtu 1420 up dev latest
[#] ip -4 route add 100.64.100.0/32 dev latest
[#] ip -4 route add 10.100.0.0/16 dev latest
john@RescuedMac:~/opt/wireguard$ sudo wg
interface: latest
  public key: 6sNCwS84iwHZCMFG2FmW3krcjCtYckJiXGa4NswtICQ=
  private key: (hidden)
  listening port: 44763

peer: c8XxVdzwkfJ94tIp2k10sHArhzDYsRU6qRtWICVJU1E=
  endpoint: 185.69.166.59:5062
  allowed ips: 10.100.0.0/16, 100.64.100.0/32
  transfer: 0 B received, 148 B sent
  persistent keepalive: every 25 seconds
john@RescuedMac:~/opt/wireguard$ ping 10.100.2.2
PING 10.100.2.2 (10.100.2.2) 56(84) bytes of data.
^C
--- 10.100.2.2 ping statistics ---
6 packets transmitted, 0 received, 100% packet loss, time 5101ms

john@RescuedMac:~/opt/wireguard$ ssh root@10.100.2.2
^C
john@RescuedMac:~/opt/wireguard$ 
```
![image](https://user-images.githubusercontent.com/13766992/105712645-88525500-5f33-11eb-889c-eac573d49c67.png)

Same result....  no connection.

**Comment by weynandkuijpers** [comment]
wireguard config:
```
john@RescuedMac:~/opt/wireguard$ more latest.conf 

[Interface]
Address = 100.64.100.1/32
PrivateKey = pMD+SrFAU5WaXGSTJ2XK4/Kw7mwOdTTnDHy/Ul7CUpM=
[Peer]
PublicKey = c8XxVdzwkfJ94tIp2k10sHArhzDYsRU6qRtWICVJU1E=
AllowedIPs = 10.100.0.0/16, 100.64.100.0/32
PersistentKeepalive = 25
Endpoint = 185.69.166.59:5062
```

**Comment by m-motawea** [comment]
there is a problem with the access node. I can't reach its public ip `185.69.166.59`

**Comment by m-motawea** [comment]
continue in https://github.com/threefoldtech/zos/issues/1166
