### ISSUE TITLE
Moving a stopped container to a new location shows empty location box.

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2318]
Taking a stopped 3bot (on testnet, 3bot name "jetsetter") and wanting to move it to a new location.  The list of options where to move it to is empty.

![image](https://user-images.githubusercontent.com/13766992/105627312-ae9ec480-5e4f-11eb-876b-0a98e0c3709f.png)

**Comment by m-motawea** [comment]
seems it was caused by blocked nodes.
nodes available after clearing blocked nodes
![image](https://user-images.githubusercontent.com/32568986/105632609-c0d32f80-5e5c-11eb-95d7-9f08f4a70db9.png)

**Comment by ranatrk** [comment]
verified
![Screenshot from 2021-01-25 14-49-59](https://user-images.githubusercontent.com/17128393/105709262-21767100-5f1e-11eb-9dc5-fe7821b7be01.png)


![Screenshot from 2021-01-25 14-57-55](https://user-images.githubusercontent.com/17128393/105708944-c0e73400-5f1d-11eb-8237-66865cc22b2c.png)
