### ISSUE TITLE
Starting a stopped 3bot results in error.

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2319]
Starting a stopped 3bot results in error:

![image](https://user-images.githubusercontent.com/13766992/105627554-0f7acc80-5e51-11eb-96e8-c0bbb85d6f54.png)

Testnet - 3bot name: jetsetter.

**Comment by ranatrk** [comment]
verified, starting a stopped 3bot succeeds
![Screenshot from 2021-01-25 14-20-39](https://user-images.githubusercontent.com/17128393/105705343-c1c99700-5f18-11eb-8336-49c9112f2bb0.png)
