### ISSUE TITLE
solutions chatflow username is not correct

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#2320]
https://github.com/threefoldtech/js-sdk/blob/development_vdc/jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py#L32

instead of getting the username from the environment which is not saved or using the incorrect tname used in the identity,
it should either use the logged in username (3bot name) or the owner_tname in the vdc instance

**Comment by waleedhammam** [comment]
server works ok
![Screenshot from 2021-01-25 14-24-00](https://user-images.githubusercontent.com/10658229/105705513-ffc6bb00-5f18-11eb-93be-4111aec7d81f.png)
