### ISSUE TITLE
Adding a worker node to an existing cluster resulted in failure while capacity is available in testnet.

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2325]
Adding a worker node failed:
![image](https://user-images.githubusercontent.com/13766992/105664426-0e4bad00-5eee-11eb-8ae1-770beabbbfab.png)

However, in freefarm there is an empty server.

![image](https://user-images.githubusercontent.com/13766992/105664491-39360100-5eee-11eb-97ad-e2bd59c1648a.png)

So my guess is that the node selection algorithm does not take into account all available nodes/capacity.

**Comment by xmonader** [comment]
@m-motawea is it possible there's a lack of IPs?

**Comment by m-motawea** [comment]
these nodes may be excluded because they are already hosting k8s machines which are part of the vdc.

**Comment by m-motawea** [comment]
@weynandkuijpers please add your current k8s nodes info and vdc info

**Comment by m-motawea** [comment]
looking again at the server mentioned, there is no SSD storage in this server (SRU). so ofcourse it won't be used.
