### ISSUE TITLE
Cannot deploy a new VDC on testnet -  couldn't get the balance for vdc_init wallet error

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/js-sdk#2339]
When trying to deploy a new VDC on testnet , getting the following error:

![image](https://user-images.githubusercontent.com/25789724/105742478-feb37f00-5f54-11eb-98a4-1b504d9a6aeb.png)

**Comment by waleedhammam** [comment]
From the initialization wallet that funds the difference of prices, its balance was less than 50 TFT, we've funded it

**Comment by siddiquagig** [comment]
Successfully Deployed now
