### ISSUE TITLE
Not Enough Resources On testnet VDC after Making payment

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/js-sdk#2342]
Was trying to deploy a VDC , after payment , it gave me the error "No resources available" :  

![image](https://user-images.githubusercontent.com/25789724/105821891-ca7fa300-5fd4-11eb-9816-21653e275163.png)

Should we not verify first for the resources and then ask for payment ?

**Comment by m-motawea** [comment]
deployed on devnet machine
