### ISSUE TITLE
Not enough resource to deploy testnet vdc after payment

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#2348]
<img width="1107" alt="Screenshot 2021-01-26 at 12 46 34" src="https://user-images.githubusercontent.com/43240801/105846948-3c5bea80-5fdd-11eb-9619-aee43e418a40.png">

**Comment by sasha-astiadi** [comment]
same as issue #2342

**Comment by m-motawea** [comment]
duplicate https://github.com/threefoldtech/js-sdk/issues/2342
