### ISSUE TITLE
failed to add a worker node

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#2349]
failed to add nodes to your cluster. due to error not enough capacity in farm freefarm for 1 kubernetes nodes of flavor K8SNodeFlavor.MEDIUM. Use the refresh button on the upper right to restart Extend Kubernetes Cluster creation

<img width="1098" alt="Screenshot 2021-01-26 at 14 37 10" src="https://user-images.githubusercontent.com/43240801/105851990-200f7c00-5fe4-11eb-879b-26c690f680fa.png">

**Comment by m-motawea** [comment]
the error is very clear. no resources available to deploy. for k8s workloads, the same node can't host more than one VM in the same vdc so, even if you think there are enough free resources in the explorer, they can be already used

**Comment by sasha-astiadi** [comment]
still happens today  @m-motawea 
<img width="1155" alt="Screenshot 2021-01-27 at 11 13 18" src="https://user-images.githubusercontent.com/43240801/105976626-b26d5980-6090-11eb-8d98-587aabc17f14.png">

**Comment by m-motawea** [comment]
@sasha-astiadi  there is not a single with enough free resources to deploy in freefarm. this has nothing to do with the vdc deployer or sdk.

```python
JS-NG> from jumpscale.sals.vdc.scheduler import Scheduler, CapacityChecker                               
JS-NG> s = Scheduler("freefarm")                                                                         
JS-NG> nodes = s.nodes_by_capacity(cru=4, mru=4, sru=50)                                                 
JS-NG> list(nodes)                                                                                       
[]

JS-NG> 
JS-NG> for node in nodes: 
     2     if not zos.nodes_finder.filter_is_up(node): 
     3         continue 
     4     print(node.node_id, "cru:", node.total_resources.cru - node.reserved_resources.cru, "mru:", node.total_resources.mru - node.reserved_resources.mru, "sru:", node.total_resources.sru - node.reserved_res
...    ources.sru)                                                                                                                                                                                                 
26ZATmd3K1fjeQKQsi8Dr7bm9iSRa3ePsV8ubMcbZEuY cru: 2 mru: 0.0 sru: 121.75
8zPYak76CXcoZxRoJBjdU69kVjo7XYU1SFE2NEK4UMqn cru: -1 mru: 1.0 sru: 241.0
85J3zEvcqDoPaN7qQHRQ2QgPVcYdCvp8JmRY5qAwzxfm cru: 0 mru: 1.046875 sru: 258.796875
3ksZcDF1yNH5S4ndEDXH3Jnp5cowh4ko8888jKepAD4a cru: 2 mru: 2.0 sru: 251.0
FED1ZsfbUz3jcJzzqJWyGaoGC61bdN8coKJNte96Fo7k cru: 0 mru: 0.0 sru: 197.0
DJoL9ZV53K5YQurmxor2BLWTPf3WA9dT3RsFWeDeAx1z cru: 1 mru: 0.0 sru: 218.0
Hx4B6B8s8yQ5ABLStma1kZ33kCuprSxzU8tY4totKbWH cru: 0 mru: 0.0 sru: 222.0
8YLrviP78Msue8ptejusq7xxxAgD4ZHNDXXF9KXVGYWr cru: -1 mru: 0.0 sru: 243.0
APxTCEYX2YjF9dgDGwRrGsi6gNmQ1a1rzgXaHrAAdbST cru: 24 mru: 187.0 sru: 0.0
EECgb24XqKaX5Y6EJJxLczxj9nzCqbq8FKgDwusp9R2A cru: 24 mru: 187.0 sru: 0.0
GB56HUBP2NwGWdJ3EaE7wR7UeJ8M7XAk1SjTurGXGSdZ cru: 24 mru: 187.0 sru: 0.0
3VBKrSTVieFzJ9Bv9MSzvQBQcTwnxgPhC9tMNsUsv5BH cru: 24 mru: 187.0 sru: 0.0
DHjz97zzNY1BxpVZ1mmv3gwwmPRN9oB91pSjeRVDZe6A cru: 24 mru: 187.0 sru: 0.0
EMg1z3up8UcYNK5Rbfya7kKkKsuyqhNWrv15JKHERbuW cru: 24 mru: 187.0 sru: 0.0
3xhQQssbgsUxJtsGoDmnF77SyogsC71Q8UFMkAAUi3ki cru: 24 mru: 187.0 sru: 0.0
3pRRo2s6h1XPSiNY5W98nPUUmWYN5NzrvyUCkpFugfL7 cru: 24 mru: 187.0 sru: 0.0
HC1WPUg8GMsbcYakHbHZxeWB1dGhwyvdjGr59dfk7vwE cru: 24 mru: 187.0 sru: 0.0
FzWp4mhvC6xutRebE8JRv9bMjquioQbdBJoSXgNxtzSG cru: 24 mru: 187.0 sru: 0.0
7e8iFD2inToLQzqTp855SpYf8LfVt9K3MUzrTWoqtvov cru: 3 mru: 148.0 sru: 17.5
JS-NG>  
```

**Comment by delandtj** [comment]
for testnet ?
I mean... no matter how many nodes we add, you guys are like a gas, instantly filling any volume. I can add 100 nodes and it will still be filled in 14 days.
if you do tests, and they are conclusive, delete the things. 
There is no reason to keep workloads on testnet, that is not it's purpose.

**Comment by sasha-astiadi** [comment]
its my first time ever testing and its my first vdc i built @delandtj

**Comment by delandtj** [comment]
wasn't talking to anyone in particular ;-)
Don't get me wrong, testing is exactly what we need, but we need to get a li'll bit more ... err... disciplined to clean up after ourselves... (me , myself, and I included)

**Comment by delandtj** [comment]
for i in {11..34} ; do if ping -c1 10.5.0.${i} > /dev/null 2>&1 ; then echo "$i -> Up" ; else echo "$i ->   NOTNOTNOT" ; fi ; done  99%   866.7 Mbps  ─╯
11 -> Up
12 -> Up
13 -> Up
14 -> Up
15 -> Up
16 -> Up
17 -> Up
18 -> Up
19 -> Up
20 -> Up
21 -> Up
22 -> Up
23 -> Up
24 -> Up
25 -> Up
26 -> Up
27 -> Up
28 -> Up
29 -> Up
30 -> Up
31 -> Up
32 -> Up
33 -> Up
34 -> Up


So all nodes in testnet are now up, 24 of them... that should be largely sufficient
