### ISSUE TITLE
3bot solution backup

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#235]
### Backup 
 - each user gets an account on 2 central linux servers (ssh non shell access), login = 3bot name
 - user has secret (passwd of non shell access on the 2 linux servers)
 - backup/restor using restic (same secret used for encryption)
 - backup to home folder on the 2 linux servers (so always 2 backups)
- in admin pannel 3bot user can do following
 - stop 3bot (means gets deleted, container gone, backup done first)
 - backup (manual backup action) ? possible via public actor
 - check last time backup was done ? possible via public actor

**Comment by alichaddad** [comment]
The following is needed to use SFTP:
- Creating a new group and limiting the ssh access to that group
- Creating a new user
- Setting up its home directory and make sure that the user's key is in the authorized hosts
- A mechanism to limit the amount of repos a user can create

Alternatively we can use an HTTP server as a backend:
- User and password for basic authentication need to be provided for the threebot
- Each user is limited to only one repo
- Will require running the HTTP server on the central linux machines

**Comment by xmonader** [comment]
backup supports rest server & a custom minio endpoint.
