### ISSUE TITLE
Add delete button for k8s solutions

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#2350]
Add delete button for k8s solutions
![image](https://user-images.githubusercontent.com/46320202/105866651-ded79600-5ffc-11eb-96c5-230f09e33ed2.png)

**Comment by RafyAmgadBenjamin** [comment]
done
![image](https://user-images.githubusercontent.com/46320202/105973763-ca93a780-6095-11eb-8a22-395c83266b79.png)
![image](https://user-images.githubusercontent.com/46320202/105973799-d67f6980-6095-11eb-92bf-0abd2fd599e2.png)
![image](https://user-images.githubusercontent.com/46320202/105973857-e8610c80-6095-11eb-8f2a-1204445efd44.png)

**Comment by RafyAmgadBenjamin** [comment]
Done 
### Branch 
`development_vdc_kube`
### PR
https://github.com/threefoldtech/js-sdk/pull/2447

**Comment by MElborolossy** [comment]
Verified in #2225
