### ISSUE TITLE
List nodes for deployed K8s solution

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#2351]
List nodes for deployed K8s solution

**Comment by RafyAmgadBenjamin** [comment]
![image](https://user-images.githubusercontent.com/46320202/105867255-8f459a00-5ffd-11eb-98ca-b1f7443e15a6.png)

**Comment by RafyAmgadBenjamin** [comment]
Done 
we just need to handle the actions

**Comment by RafyAmgadBenjamin** [comment]
Info Action
![image](https://user-images.githubusercontent.com/46320202/105989525-ed2fbb80-60a9-11eb-8bcb-e47a7e4154f2.png)
Delete Action
![image](https://user-images.githubusercontent.com/46320202/105989609-0afd2080-60aa-11eb-9d98-72d1bc35d6e2.png)
![image](https://user-images.githubusercontent.com/46320202/105989685-22d4a480-60aa-11eb-94af-c2ed4624aa56.png)

**Comment by RafyAmgadBenjamin** [comment]
Done 
### Branch 
`development_vdc_kube`
### PR
https://github.com/threefoldtech/js-sdk/pull/2447

**Comment by MElborolossy** [comment]
Verified in #2225
