### ISSUE TITLE
Weird size indications

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2353]
In some (did not check all yet, but saw it in mattermost and zero-ci) the size selection chat window has weird sizing number for cores and memory

![image](https://user-images.githubusercontent.com/13766992/105954088-a0d68280-608d-11eb-8baf-b7ab348dbe54.png)

**Comment by waleedhammam** [comment]
This is the official resource units for kubernetes : https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-units-in-kubernetes

**Comment by weynandkuijpers** [comment]
okay - understand.  Then questions is ->  we specify when we launch the VDC the sizing in TF CU, SU and IPv4. When we use the marketplace we switch to the Kubernetes way of specifying how much an application can consume.  We have to somehow explain and describe how the two are related.  Otherwise, it is impossible to assess how much more capacity I have to deploy applications (and as you have seen in the issues I ran out of capacity at some point in time).  Is there a simple mapping?

**Comment by xmonader** [comment]
Should go to next, I think maybe the confusing part is using the same sizes as the VDC package name, but these sizes are fine to the VM users

**Comment by weynandkuijpers** [comment]
Yes - the confusion but is that I purchase a VDC I choose:
![image](https://user-images.githubusercontent.com/13766992/106564828-33bc6480-6547-11eb-825c-052406435971.png)
 number of vCPU, Memory (GB) and storage (GB).  The kubernetes way of specifying is different numbers which are 100,000x / 1,000,000x larger.  Maybe translation table?

**Comment by weynandkuijpers** [comment]
Okay - I'll close this issue with the remark that I will spend time to go through all screens/text and take an "end-user view" of things being understandable.  I understand we want to service/attract Kubernetes sysadmins / DevOps for this product but they know anyway (and will monitoring / control their VDC consumption through kubectl or tools like kontena-lens.  So for them this information is not important and non-devops people don't understand it.  So I'll close and will make a proposal to change language (here and there  ;-))
