### ISSUE TITLE
Deplot of Marketplace blog failed.

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2354]
In my VDC (weynandkuijpers.3bot) I wanted to deploy a blog.  I used the following GitHub repo is input: https://github.com/weynandkuijpers/mytrunk (not an empty repo)

![image](https://user-images.githubusercontent.com/13766992/105955242-679f1200-608f-11eb-9a84-88cf3e244550.png)

![image](https://user-images.githubusercontent.com/13766992/105955358-96b58380-608f-11eb-9170-3b5e89f194ae.png)

**Comment by abom** [comment]
As noted in the chatflow, this uses publishingtools, which requires the blog to be in a certain format, see example blog:

https://github.com/threefoldfoundation/blog_example, or the more complete example of our current tf-blog at https://github.com/threefoldfoundation/www_tfblog

**Comment by weynandkuijpers** [comment]
Did not read the manual entry.  It is well documented, thank you.https://now.threefold.io/now/docs/publishing-tool/#tutorial-how-to-deploy
