### ISSUE TITLE
Existing VDCs Page Stuck on Loading when trying to access it

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/js-sdk#2355]
I Have 3 testnet VDCs deployed 2 days ago and when i try to access them through the button "Go to my VDC " , the page gets stuck on loading :

Steps : 

Click on Go to my VDC .

i first get this : 

![image](https://user-images.githubusercontent.com/25789724/105956514-5ce57c80-6091-11eb-8cc1-d269226554c8.png)

Then after clicking Ok , the page is stuck , i tried on multiple browsers also :  

![image](https://user-images.githubusercontent.com/25789724/105956607-7dadd200-6091-11eb-8a5a-ed55a43a7d25.png)

3bot : ```masid.3bot```

VDCs affected : 
https://masid-vdctest26.vdctest.grid.tf
https://masid-evdctesnetimp.vdctest.grid.tf
https://masid-bcnodes21.vdctest.grid.tf

**Comment by waleedhammam** [comment]
Can you hard reload ?, if it's up for 2 days, then it will require a login, you didn't get that means caching problem

you can disable cache for chrome or go incognito and check again

![Screenshot from 2021-01-27 10-30-26](https://user-images.githubusercontent.com/10658229/105964320-b0080100-608a-11eb-90ca-0e7315592b80.png)

**Comment by waleedhammam** [comment]
investigating a little

![image](https://user-images.githubusercontent.com/10658229/105968123-56ee9c00-608f-11eb-9eab-96bdc03cfaa2.png)

![Screenshot from 2021-01-27 11-01-54](https://user-images.githubusercontent.com/10658229/105968174-6a016c00-608f-11eb-9fcf-8bdf0bde672c.png)

was working ok with, seems like a network connection problem

**Comment by siddiquagig** [comment]
Cleaned up github.com cookies and it works now, thanks @waleedhammam
