### ISSUE TITLE
Deployed workload page not updated after workload is deleted.

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2357]
In the VDC 'Show deployed workloads' when you delete a workload the page is not updated.  You need to do a manual reload of the page to display the new VDC deployed workloads.
![image](https://user-images.githubusercontent.com/13766992/105968571-af7a6500-60a0-11eb-8a37-7db002650e07.png)

**Comment by waleedhammam** [comment]
@weynandkuijpers what's the vdc name ?

**Comment by weynandkuijpers** [comment]
name is "newvdctoo" and it was deployed a couple of days ago.

**Comment by waleedhammam** [comment]
> name is "newvdctoo" and it was deployed a couple of days ago.

An update (breaking change) here: https://github.com/threefoldtech/js-sdk/pull/2298  has happened that provides new data in environmental variables, the `newvdctoo` doesn't have it which causes that error, you can deploy a new vdc, this error won't be there

**Comment by weynandkuijpers** [comment]
ok
