### ISSUE TITLE
Deployed document server and it displays an error

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2359]
Deployed a document server and the presented URL does not display anything (but an error).

![image](https://user-images.githubusercontent.com/13766992/105975454-67f7d700-60a8-11eb-90aa-7bf6836dc500.png)

![image](https://user-images.githubusercontent.com/13766992/105975501-76de8980-60a8-11eb-89bc-1d4fcc0d9f90.png)

**Comment by weynandkuijpers** [comment]
Maybe you cannot access it with a browser, but the the text needs to chenge when the server is deployed.

**Comment by weynandkuijpers** [comment]
Filebrowser needs that URL as input -> We need to describe then when document server is deployed.

**Comment by waleedhammam** [comment]
duplicate of https://github.com/threefoldtech/vdc-solutions-charts/issues/56

**Comment by xmonader** [comment]
There won't be a separate deployment of document server
