### ISSUE TITLE
update quickstart do to include --local option for the users

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#236]
https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/quick_start.md

make sure --local is referenced and update the docs with least minimum effort for the reader

**Comment by RafyAmgadBenjamin** [comment]
I will verify this

**Comment by RafyAmgadBenjamin** [comment]
#### Verified
##### The docs updated
https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/quick_start.md

![image](https://user-images.githubusercontent.com/46320202/87421637-8e0bcd00-c5d7-11ea-8101-aa9e1e229d55.png)
