### ISSUE TITLE
3bot sdk - TFT-related Error when creating a capacity pool

### ISSUE THREAD

**Issue by BenjellounO** [threefoldtech/js-sdk#2360]
I receive the error notif below whenever I want to create a capacity pool, with different CU unit settings.
the error emerges after the CU unit settings page 
Ps: a small typo here, "That the support TFT currency" -> "That supports TFT" 
![capacity error](https://user-images.githubusercontent.com/51067842/105975728-bad18e80-60a8-11eb-9cd4-9d43d8d9a796.PNG)

Any ideas on how to solve this?

**Comment by BenjellounO** [comment]
this is on mainnet

**Comment by m-motawea** [comment]
I can't reproduce this on latest development branch
![image](https://user-images.githubusercontent.com/32568986/105987600-29ade800-60a7-11eb-93a4-d182f6f0d0e8.png)


probably your threebot is not updated or something? can you make sure you have the latest updates?

**Comment by xmonader** [comment]
The error is misleading it may be caused by insufficient resources 
![image](https://user-images.githubusercontent.com/64129/107498795-e2425400-6b9c-11eb-8953-72c775dee9c4.png)

**Comment by waleedhammam** [comment]
duplicate issue
