### ISSUE TITLE
cant add new vdc

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#2361]
<img width="1116" alt="Screenshot 2021-01-27 at 11 17 06" src="https://user-images.githubusercontent.com/43240801/105977277-7686c400-6091-11eb-9657-1434f5f578d1.png">

**Comment by m-motawea** [comment]
should be ok now
![image](https://user-images.githubusercontent.com/32568986/105981219-85c03e80-609e-11eb-92d4-422dc61c80d6.png)
