### ISSUE TITLE
vdc wallet ux improvement

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#2363]
<img width="1432" alt="Screenshot 2021-01-27 at 11 21 51" src="https://user-images.githubusercontent.com/43240801/105977752-09276300-6092-11eb-9a44-7a1d4294424c.png">

as a user I would like to know how I can top up my balance to avoid my vdc being taken down due to lacking of tft.

- [ ] add top up button next to the wallet tft balance 
- [ ] when clicked, pop up a qr code of the wallet address, and memo text for top up.

**Comment by xmonader** [comment]
There's no need for memo text, closing in favor of #2502
