### ISSUE TITLE
Uploading a 11MB file results in error

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2366]
uploading a 11.3MB file results in error

![image](https://user-images.githubusercontent.com/13766992/105981143-2e769a00-60af-11eb-84a6-cfaf8cf33931.png)

**Comment by waleedhammam** [comment]
duplicate of https://github.com/threefoldtech/vdc-solutions-charts/issues/55

**Comment by weynandkuijpers** [comment]
Any update - we want to do a go-nogo decision for the release later today

**Comment by weynandkuijpers** [comment]
Any update?

**Comment by weynandkuijpers** [comment]
Any update?  Release 2.4 is bound to be released end of this week (week starting 15/2/2021) and we are inviting a lot of people externally to start functional testing.  Do we really want this to go out?

**Comment by xmonader** [comment]
Afaik this is moved to 2.5 long time ago, but I agree if not fixed should be disabled.

**Comment by weynandkuijpers** [comment]
Then please disable the file browser  (and file server) deployment in the marketplace until we have had the time to fix this in the 2.5 release

**Comment by weynandkuijpers** [comment]
Issue no longer relevant.
