### ISSUE TITLE
Deployed Solutions URL should open up in a new Tab

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/js-sdk#2368]
After deploying a solution , If i click on the URL , it opens up in the same window, as a best practice can we also open the URLs to the deployed solutions in a new Tab/Window (although we do have the button "Open in Browser") , but many users would just click on the URL.

![image](https://user-images.githubusercontent.com/25789724/105981414-7b5a7080-60af-11eb-9f86-b1c5ace71431.png)

**Comment by xmonader** [comment]
In general I use middle-click almost all the time to open in a background tab.

**Comment by xmonader** [comment]
Actually the intended action, if the user clicks here, should go in the same tab.
