### ISSUE TITLE
deploy Gitea and 3 entries appear in the "deployed solutions overview

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2369]
Deploying Gitea leads to a list of 3 things that appear in the "deployed solutions page". 1 deletes all three.

![image](https://user-images.githubusercontent.com/13766992/105982874-549d3980-60b1-11eb-95ee-d00f08951174.png)

While in the Gitea specific deployed solutions overview it is only one:

![image](https://user-images.githubusercontent.com/13766992/105982946-6da5ea80-60b1-11eb-81dd-b31ee12efa4d.png)

**Comment by waleedhammam** [comment]
Deployed solutions page shows all kubernetes deployments as they have the same lables. 
to view a specific type please go to the solution page

**Comment by weynandkuijpers** [comment]
ok
