### ISSUE TITLE
including package in package.toml should be by "name"

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/js-sdk#237]
now including package in package.toml is hardcoded to specific port so when running threebot locally
```
threebot start --local
```
this will start the server with port 8443 as the ssl port while include in this case includes from 443 config 
```
includes = ["default_443.chatflows_*", "default_443.auth_*", "default_443.tfta_sales*"]
```
at this point those packages running on a different port which now default_8443.chatflows
this needs to be handled in a consistent way

**Comment by xmonader** [comment]
cc @abom
