### ISSUE TITLE
Deployed Solution (Blog) does not appear under My Workloads

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/js-sdk#2370]
Deployed a Blog and after back in Marketplace Dashboard , when i click under Blog > My Workloads , i am unable to see my Deployed Solution here : 

![image](https://user-images.githubusercontent.com/25789724/105984449-916a3000-60b3-11eb-8757-a0037b33cab9.png)

Though it appears under "Deployed Solutions" :  

![image](https://user-images.githubusercontent.com/25789724/105984544-b78fd000-60b3-11eb-8c5c-07cde07b0f26.png)

**Comment by abom** [comment]
Blog, wiki and website all have the common solution type of `publishingtools`, this need to be fixed, as listing now require solution type, while these three have a common one.


@waleedhammam @m-motawea What do you think?

**Comment by sasha-astiadi** [comment]
same with me, on wiki etc

**Comment by dmahmouali** [comment]
> Blog, wiki and website all have the common solution type of `publishingtools`, this need to be fixed, as listing now require solution type, while these three have a common one.
> 
> @waleedhammam @m-motawea What do you think?

I think we can send it as a value in the chart

**Comment by rkhamis** [comment]
closing in favor of https://github.com/threefoldtech/home/issues/1012
