### ISSUE TITLE
ux change website deployment instruction

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#2374]
Configurations
Few parameters are needed to be able to publish your website online

1. Create a github account
2. FORK this [website template repo](https://github.com/threefoldfoundation/website_example) to your github account
3. Copy your forked website template URL to the vdc deployer
4. Select the branch you want to deploy, e.g: main
5. Identify which folder the codes live on your website, e,g : html
6. You can customize the website template on your github once deployed.
--
This is important. users have no clue how to deploy if we don't do this.

**Comment by xmonader** [comment]
closing in favor of https://github.com/threefoldtech/js-sdk/issues/2375
