### ISSUE TITLE
VDC: Improve publishingtools deployment and listing

### ISSUE THREAD

**Issue by abom** [threefoldtech/js-sdk#2375]
### Description

Because deployment tend to fail because of wrong/manual input, some automatic checks should be added to reduce manual input and make it less error prone.

Other related issues too:

* Listing issue (https://github.com/threefoldtech/js-sdk/issues/2370, https://github.com/threefoldtech/home/issues/1012)
* Update instructions (https://github.com/threefoldtech/js-sdk/issues/2373 and https://github.com/threefoldtech/js-sdk/issues/2374).

### Implementation

- [x] Get rid of `Title` step if it's not really used (solution name can be used instead).
- [ ] ~Check given URl is an actual git repo~
- [ ] ~Use Github API to get branches and source directory automatically (in case it's a github URL).~
- [ ]  ~Try to return a meaningful error in case of failure (from publishingtools logs?)~
- [x] Update instructions (add separate instructions for each type of blog, website and wikis).
- [x]  Maybe separate solution type from chart name to distinguish between solutions that use the same chart.

**Comment by abom** [comment]
Github API calls would need authentication, so for simplicity, less input is required now and instructions are added, also listing should be fixed.

**Comment by xmonader** [comment]
verified
