### ISSUE TITLE
DISCOURSE deployment is shown twice on deployed solutions list with different name

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#2376]
why is it like this? 
<img width="1395" alt="Screenshot 2021-01-27 at 16 02 11" src="https://user-images.githubusercontent.com/43240801/106010166-6f73ac00-60b9-11eb-8600-6c261c23fb18.png">

**Comment by waleedhammam** [comment]
> Deployed solutions page shows all kubernetes deployments as they have the same lables.
to view a specific type please go to the solution page

it's just like: https://github.com/threefoldtech/js-sdk/issues/2369#issuecomment-768267183
