### ISSUE TITLE
failed to deploy taiga

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#2378]
Failed to initialize peertube, please contact support with this information: Domain: sashaastiadi-peertube-sasha11.webg2test.grid.tf VDC Name: vdc_vdctest4_sashaastiadi Farm name: freefarm Reason: Couldn't find resources in the cluster for the solution . Use the refresh button on the upper right to restart Peertube creation

**Comment by waleedhammam** [comment]
There's no bug here, No free resources on the cluster to deploy the solution on.

**Comment by sasha-astiadi** [comment]
@waleedhammam how do i know how many resources i have left on my cluster
