### ISSUE TITLE
Review the information stream / sequence presented to VDC owners when a VDC is deployed

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2379]
Let;s review the flow of information which is currently being presented to the VDC owner.  There is information in the sequence of screens that are presented that indicate the steps that the deployment process go through.  

Let's question the relevance and validity to show this to every consumer of a VDC.  Maybe create an option that allows you to choose what level of information is being shared with consumers.

**Comment by xmonader** [comment]
Issue didn't go anywhere since jan 28
