### ISSUE TITLE
poll21: tft transaction not being processed

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/js-sdk#238]
bbilek.3bot waits since yesterday evening for his 0.1 tfta to be sent. guy starts form o again and again. process can not be stopped.
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/18591016/87415536-7a5b6900-c5cd-11ea-946c-5cc1df64fd53.png">

**Comment by waleedhammam** [comment]
@andhartl can you please specify how did you pay ? using 3bot QR code scanner or manually using wallet ?

If you done the payment manually did you add the correct `message` or `memo_text` like instructions in payment page 

![Screenshot from 2020-07-14 14-25-03](https://user-images.githubusercontent.com/10658229/87425426-e776fa80-c5dd-11ea-8ad8-c7fcb777a700.png)

**Comment by andhartl** [comment]
opened issue on behalf of bernd Bilek. question: how can he stop the process and start fro scratch?

**Comment by waleedhammam** [comment]
> opened issue on behalf of bernd Bilek. question: how can he stop the process and start fro scratch?

just refresh the page and start again
