### ISSUE TITLE
File Browser manual on Marketplace VDC does not open

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/js-sdk#2380]
Just deployed  a fresh VDC , in marketplace the filebrowser wiki is not accessible , gives :

![image](https://user-images.githubusercontent.com/25789724/106105706-d34fb080-615d-11eb-9531-4d2b123cd7f4.png)

The correct link should be : 

https://now.threefold.io/now/docs/file-browser/#open-source-solution-file-browser

**Comment by waleedhammam** [comment]
Verified on development_vdc latest, redirects to the correct link

![image](https://user-images.githubusercontent.com/10658229/106876294-3acaaa80-66e0-11eb-9ea3-fda165767f56.png)
