### ISSUE TITLE
Failed to initialize Discourse chart in chatflow

### ISSUE THREAD

**Issue by AhmedSa-mir** [threefoldtech/js-sdk#2381]
### Description

Deploying discourse failed in initialization step with error

![Screenshot from 2021-01-28 10-51-12](https://user-images.githubusercontent.com/18093386/106113407-1fe3bd80-6157-11eb-9ba0-fb75cdc4e090.png)

While the chart is listed and the domain is reachable

![Screenshot from 2021-01-28 10-51-58](https://user-images.githubusercontent.com/18093386/106113431-25d99e80-6157-11eb-8645-d95139ca66e0.png)

![Screenshot from 2021-01-28 10-51-39](https://user-images.githubusercontent.com/18093386/106113446-296d2580-6157-11eb-851b-1c0b47441112.png)

**Comment by AhmedHanafy725** [comment]
**Verified**

![image](https://user-images.githubusercontent.com/41957921/107336828-404e3900-6ac2-11eb-8487-86ff3fa2c121.png)

![image](https://user-images.githubusercontent.com/41957921/107336795-39bfc180-6ac2-11eb-9cbe-6493ca2fdea6.png)
