### ISSUE TITLE
Filebrowser shows black screen when you doubleclick an uploaded file.

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2382]
VDC name: jetserthing

- deployed documentserver
- provided the URL to the filebrowser
- uploaded a pptx file
- doubleclicked the pptx file
![image](https://user-images.githubusercontent.com/13766992/106119045-30536280-616e-11eb-8157-47046068252f.png)

**Comment by waleedhammam** [comment]
Same as https://github.com/threefoldtech/js-sdk/issues/2367 and https://github.com/threefoldtech/vdc-solutions-charts/issues/55
