### ISSUE TITLE
Deployed documentserver does not respond to local onlyoffice desktopapp

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2383]
VDC: jetserthing

Deployed the document server marketplace chatflow and when connected to it it sais everything is okay:
![image](https://user-images.githubusercontent.com/13766992/106119797-06e70680-616f-11eb-9bd1-356b71c82ad2.png)

When I try to connect with a local installed onlyoffice desktop it give me a timout
![image](https://user-images.githubusercontent.com/13766992/106119906-29791f80-616f-11eb-9a9b-bbf4556aa154.png)

**Comment by waleedhammam** [comment]
https://github.com/threefoldtech/vdc-solutions-charts/issues/56
