### ISSUE TITLE
Typo on first visit to vdc testnet, idenitifications 

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/js-sdk#2385]
Simply navigate to https://vdc.testnet.grid.tf/ without being authenticated

idenitifications => identification

![image](https://user-images.githubusercontent.com/59569757/106120648-e90da780-6156-11eb-98c7-d8edf2099527.png)

**Comment by AhmedHanafy725** [comment]
**Verified** 
**Commit:** 74c733e3f46875fab96c0b075d4dab7fceabd31e
**Branch:** develeopment_vdc

![image](https://user-images.githubusercontent.com/41957921/106391227-f8118580-63f4-11eb-91ee-d3e2a21eb40d.png)
