### ISSUE TITLE
Error handling when email is not verified should be improved

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/js-sdk#2386]
1) When first logging in to https://vdc.testnet.grid.tf/ and selecting login via TF Connect, use an account that does not have a verified email

Results in a generic 400 error page.

Improvements needed :

1) Clear communication to the user what went wrong and how to solve it "Please verify your email in the ThreeFold Connect app"

2) After your email has been verified, please log in again => Button to restart the flow or to take you back to the original page.

Currently =>

![image](https://user-images.githubusercontent.com/59569757/106121796-3d655700-6158-11eb-8732-37375185d73d.png)

**Comment by waleedhammam** [comment]
Verified on development
```
commit b73b4d9a2944ff3787b2bb81565e02cd6345a7bc (HEAD -> development, origin/development)
Author: AhmedHanafy725 <41957921+AhmedHanafy725@users.noreply.github.com>
Date:   Thu Feb 4 11:06:01 2021 +0200

    Fix node policy when selecting automatic (#2453)
```
![image](https://user-images.githubusercontent.com/10658229/106875584-829d0200-66df-11eb-875f-1f03c3f7fd0f.png)
