### ISSUE TITLE
when kubeapps deployed, its showing triple deployments?

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#2387]
<img width="1363" alt="Screenshot 2021-01-28 at 11 12 19" src="https://user-images.githubusercontent.com/43240801/106123184-e82a4500-6159-11eb-89df-ea7a99352b4b.png">

is it because apps are deployed inside kubeapps?
<img width="1081" alt="Screenshot 2021-01-28 at 11 13 13" src="https://user-images.githubusercontent.com/43240801/106123152-dcd71980-6159-11eb-906f-2ded7013ec4d.png">

**Comment by waleedhammam** [comment]
Again same as: https://github.com/threefoldtech/js-sdk/issues/2376
deployed solutions button shows all kubernetes pods
