### ISSUE TITLE
VDC initial login, terms and conditions has a broken link.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/js-sdk#2388]
Probably quite important from a legal perspective, I Don't think any agreement to a broken link holds up.

1) Navigate to https://vdc.testnet.grid.tf/ for the first time, login
2) On the first page where you agree to the agreements ( https://vdc.testnet.grid.tf/vdc/#/license ). Click every link

The last link, Terms & Conditions TFGrid Farmers results in a 404 not found => https://legal.threefold.io/#/terms_conditions_farmer.md

**Comment by xmonader** [comment]
data fetched from github https://github.com/threefoldfoundation/legal/blob/master/src/terms_conditions_all.md, issue transferred to the legal repo

**Comment by sasha-astiadi** [comment]
fixed https://legal.threefold.io/#/terms_conditions_farmer
