### ISSUE TITLE
ux improvements on deployed solutions and node listing

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#2389]
- [ ] add 'multiselect' check box to delete multiple deployments, add / remove multiple nodes, etc.

- [ ] add confirmation message pop up after delete button is clicked. "remove x number of solutions? this cannot be undone." 

- [ ] remove / cancel button under the popup message.

<img width="1373" alt="Screenshot 2021-01-28 at 11 24 40" src="https://user-images.githubusercontent.com/43240801/106124640-9682ba00-615b-11eb-80c7-38459f98d318.png">

**Comment by xmonader** [comment]
this is not ok, this page to be used as read-only view as it "lists" all the pods not just the solutions. if anything the delete action should get removed and only place to delete to be the My Workloads page.
