### ISSUE TITLE
VDC payment step needs clearer instructions for QR code or Manual payment.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/js-sdk#2391]
Current image provided.

Main issues : 

1) Not clear that the QR code needs to be scanned with TF Connect, doing a normal QR scan results in a broken URL visit.

    => Please scan the QR Code below using the ThreeFold Connect app. The wallet QR scanner can be found by going to the wallet section and clicking the transaction button. "

-----------------------

2) Not clear that the payment can also be done manually with the details provided. It all seems part of one payment section, which confuses the user when you start talking about "make sure the memo-text is correct" since this is not relevant in the QR flow.

    => Make a clear seperation for the section after the QR code scan.

    "Alternatively, the payment can be done manually, make sure to fill in every field correctly."

-------------------------

3) On the VDC page the term used is memo-text, in the ThreeFold Connect app the term used is message.

    To avoid confusion change memo-text => memo-text(message) : 

![image](https://user-images.githubusercontent.com/59569757/106125416-70a9e500-615c-11eb-8306-5cdcf7d6af0d.png)

**Comment by AhmedHanafy725** [comment]
**Verified** 
**Branch:** development_vdc
**commit:** 49d19a52cc10578120b59a6d415802eaad6bc5b2

![image](https://user-images.githubusercontent.com/41957921/106898656-221cbd80-66fd-11eb-8a3e-fdb06cc7ace7.png)
