### ISSUE TITLE
Typo in VDC payment step

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/js-sdk#2392]
1) Deploy a VDC

2) Go to the payment step

Inserting the memo-text is an important way to identify a transaction recipient beyond a wallet address. Failure to do so will result in a failed payment. Please also keep in mind that an additional Transaction fee of 0.1 TFT will automatically occurs per transaction.

occurs => occur

**Comment by m-motawea** [comment]
fixed in https://github.com/threefoldtech/js-sdk/commit/f538e2142bed7bb5febda64707ee9b7862e68b75

**Comment by AhmedHanafy725** [comment]
**Verified** 
**Branch:** development_vdc
**commit:** 49d19a52cc10578120b59a6d415802eaad6bc5b2

![image](https://user-images.githubusercontent.com/41957921/106896040-b553f400-66f9-11eb-83cd-5fe25a8d2468.png)


![image](https://user-images.githubusercontent.com/41957921/106896060-bc7b0200-66f9-11eb-929a-b4587ac28b1d.png)
