### ISSUE TITLE
all deployment disappeared

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#2393]
deleted 1 deployment and suddenly others are gone from the list too.

<img width="1419" alt="Screenshot 2021-01-28 at 12 35 31" src="https://user-images.githubusercontent.com/43240801/106133358-6e985400-6165-11eb-9b4d-f70f97cfcc39.png">

**Comment by sasha-astiadi** [comment]
also, just deployed another solutionhttps://sashaastiadi-documentserver-sasha111.webg2test.grid.tf/
 from the marketplace successfully, but its not listed. my deployed solution list is still empty

**Comment by waleedhammam** [comment]
Please note (again): deployed solution page shows all kubernetes pods

I deployed 2 solutions and couldn't reproduce

- deployed discorse
![Screenshot from 2021-01-31 13-03-48](https://user-images.githubusercontent.com/10658229/106381953-e31cfe00-63c4-11eb-92c3-596a1558fa67.png)

- deployed taiga
![Screenshot from 2021-01-31 13-03-04](https://user-images.githubusercontent.com/10658229/106381958-efa15680-63c4-11eb-9091-9798991c37d8.png)
![Screenshot from 2021-01-31 13-03-21](https://user-images.githubusercontent.com/10658229/106381963-f3cd7400-63c4-11eb-8f63-29c9979f95e3.png)

- deleted taiga
![Screenshot from 2021-01-31 13-03-31](https://user-images.githubusercontent.com/10658229/106381967-fc25af00-63c4-11eb-990f-f049a25a3a09.png)

![Screenshot from 2021-01-31 13-03-48](https://user-images.githubusercontent.com/10658229/106381970-03e55380-63c5-11eb-8990-578d0f93fa4c.png)

duplicate https://github.com/threefoldtech/js-sdk/issues/2376

Please add clear steps to how to reproduce
