### ISSUE TITLE
Can't return to my VDC after canceling the process during deployment.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/js-sdk#2394]
1) Deploy a VDC
2) Pay for the VDC
3) During the loading spinners that deploy the VDC and tell you to wait 2-3 minutes, refresh the page

=> The deployment process is no longer visible.

When going to list VDC I can see my VDC, but visiting it returns a broken link with connection refused.

I know this is because the backend is still deploying it. But it should be made clearer to the user.

EIther of the two following options whatever is technically possible, 2 being favoured but likely more difficult to implement.

1) In the list, list it clearly as still deploying.

2) Make the user return back to the page that was giving all the deployment info and the spinners.

**Comment by waleedhammam** [comment]
The chatflow engine save the state, when you go back to "deploy vdc" (the chatflow itself), you'll find in exactly where you left it.
This won't be listed unless it's successfully deployed
