### ISSUE TITLE
No max length validation on VDC Name

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/js-sdk#2397]
1) Deploy a VDC with name wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww

2) It actually goes to deploy, and then errors.

=> It should simply have a client-sided max length with clear error. "VDC names can be maximum 28 characters long"

Be sure to look up what the ACTUAL max length is and not just fill in 28, I have no clue myself what the maximum allowed length is.

**Comment by m-motawea** [comment]
fixed in: https://github.com/threefoldtech/js-sdk/commit/ccec885cf49b60cd6681591f9e6aaa2223b89503

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/106453361-dc0ff180-6491-11eb-872c-76bf10a3358e.png)
