### ISSUE TITLE
Uncaught TypeError: Cannot read property 'naturalHeight' of undefined - On VDC list

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/js-sdk#2398]
1) I have one deployed VDC Right now

2) Browse to VDC list with console open

results in

Uncaught TypeError: Cannot read property 'naturalHeight' of undefined

Every new browse throws the error again.

Issue was logged and closed in the past for a different page.

See https://github.com/threefoldtech/js-sdk/issues/1029

**Comment by waleedhammam** [comment]
As mentioned in here: https://github.com/threefoldtech/js-sdk/issues/1029#issuecomment-688791578
problem is with vue engine, maybe it could be fixed in coming versions
