### ISSUE TITLE
newly deployed solutions are not listed on 'marketplace' deployed solutions.

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#2399]
just deployed taiga and its not listed on marketplace deployed solution
<img width="1433" alt="Screenshot 2021-01-28 at 13 42 40" src="https://user-images.githubusercontent.com/43240801/106140257-d0a98700-616e-11eb-90dd-543a786022ea.png">

although it's shown on taiga/my workloads

<img width="1404" alt="Screenshot 2021-01-28 at 13 42 34" src="https://user-images.githubusercontent.com/43240801/106140389-ffbff880-616e-11eb-8ce4-fd72aeabe6b1.png">

**Comment by AhmedSa-mir** [comment]
Can't reproduce

![image](https://user-images.githubusercontent.com/18093386/106382001-38f1a600-63c5-11eb-8962-e1d94e8c762b.png)

![Screenshot from 2021-01-31 13-06-30](https://user-images.githubusercontent.com/18093386/106382017-4444d180-63c5-11eb-81c9-e9535d5aa00a.png)
