### ISSUE TITLE
Expiration dates do not match payment plans.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/js-sdk#2400]
1) I deployed Two VDCs today, 28/01/2021

2) One with 15 TFT on testnet (  silver ) one with 30 TFT on testnet ( gold )

I would expect both these to be valid until 28/02/2021 ( or at least 30 days ) based on what was said when I picked the specific plans. 

Reality is =>

![image](https://user-images.githubusercontent.com/59569757/106148609-87ab0000-6179-11eb-9f87-a1e4a6557b4c.png)

**Comment by waleedhammam** [comment]
duplicate: https://github.com/threefoldtech/js-sdk/issues/2295
