### ISSUE TITLE
Adding a worker node to an existing cluster in a VDC takes forever

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2402]
VDC name: jetserthing

I launched a numbetr of marketsplace solutions (2) and wen I tried to launch the 3rd one, I got a message that told me that there were no more resources.
![image](https://user-images.githubusercontent.com/13766992/106233571-40238300-6210-11eb-91f2-2fcbe17f54c0.png)

Wanted to add a worker node to see of that would lead to more capacity being available in the cluster that would allow me to launch this peertube container.  The progress screen was slow to progress and got stuck at this forever:

![image](https://user-images.githubusercontent.com/13766992/106233825-cdff6e00-6210-11eb-8934-105afcb085be.png)

I pressed "Reload page" a couple of times but always got back to the same rotating page.

CLI shows a new worker node
```
john@RescuedMac:~/.kube$ kubectl get nodes 
NAME         STATUS   ROLES    AGE     VERSION
k3os-21973   Ready    <none>   8m59s   v1.19.4+k3s1
k3os-31241   Ready    <none>   22h     v1.19.4+k3s1
k3os-4283    Ready    master   22h     v1.19.4+k3s1

```

**Comment by weynandkuijpers** [comment]
After a very long time the update / addition of the worker node failed:

![image](https://user-images.githubusercontent.com/13766992/106234661-a8736400-6212-11eb-974b-c5aeaaaa27c9.png)

CLI kubectl command still shows 
```
^Cjohn@RescuedMac:~/.kube$ kubectl get nodes -w
NAME         STATUS   ROLES    AGE   VERSION
k3os-21973   Ready    <none>   23m   v1.19.4+k3s1
k3os-31241   Ready    <none>   22h   v1.19.4+k3s1
k3os-4283    Ready    master   22h   v1.19.4+k3s1
```
And then hangs.

**Comment by weynandkuijpers** [comment]
Tried to add a large kuberneted worker, and now I get a message about no capacity in the farm to deliver that:

![image](https://user-images.githubusercontent.com/13766992/106234933-1b7cda80-6213-11eb-9779-fde356a1d360.png)

**Comment by weynandkuijpers** [comment]
With the second worker node deployed, I tried to deploy the peertube container and it worked.
![image](https://user-images.githubusercontent.com/13766992/106235433-153b2e00-6214-11eb-808e-dee2bf7533e9.png)

**Comment by m-motawea** [comment]
we reserve capacity for 1 hour first for the node, then after the node is successfully deployed, we update the expiration for 2 weeks. that's why the node is shown when you list k8s nodes

this is taking long time because payments are failing and the chat keeps retrying depending on how many pools are being extended, each pool can take up to 5 minutes before it fails.

**Comment by m-motawea** [comment]
will explicitly show that payments are failing and the chat is retrying

**Comment by rkhamis** [comment]
let's add text to show that we're retrying
