### ISSUE TITLE
Error when deploying a blog on the VDC

### ISSUE THREAD

**Issue by BenjellounO** [threefoldtech/js-sdk#2403]
when deploying a blog, I do receive the error below, 

![blog error](https://user-images.githubusercontent.com/51067842/106252157-5ee54200-622f-11eb-9110-119c3820fbae.PNG)

 can someone please check out the issue and how i can solve it?

**Comment by abom** [comment]
Please provide more information about your input (blog url, branch...etc), you can check this comment https://github.com/threefoldtech/js-sdk/issues/2354#issuecomment-768208686 too.

**Comment by BenjellounO** [comment]
@abom there you go https://github.com/BenjellounO/Blog-deployment-Test-on-TF-marketplace

**Comment by abom** [comment]
Well, it seems like it's a private repository, publishingtools won't be able to clone it for sure.
