### ISSUE TITLE
jsng local 3bot setup installer , threebot does not start

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/js-sdk#2405]
Tried to setup jsng local 3bot on a new system , and in inside poetry shell , unable to start threebot :  

![image](https://user-images.githubusercontent.com/25789724/106377723-80be0080-63b8-11eb-9465-25b3d904a25f.png)

![image](https://user-images.githubusercontent.com/25789724/106377726-903d4980-63b8-11eb-92bb-c3b4ecf52bb6.png)

Tested on development and development_vdc branches

**Comment by waleedhammam** [comment]
please follow https://threefoldtech.github.io/js-sdk/wiki/#/./quick_start

**Comment by abom** [comment]
`poetry update` is not mentioned in any of our documents (except during development), it shouldn't be used during installation at all.

Also `solutions_automation/threebot/start.py` is related to automated testing of solutions, that's also not mentioned, please follow the correct documentation and suggest improvements to them if required.

**Comment by abom** [comment]
I think you followed older `js-ng` repository documentation, but also, you didn't do `poetry install`.
Please follow `js-sdk` documentation mentioned at https://github.com/threefoldtech/js-sdk/issues/2405#issuecomment-770346739.

`js-ng` documentation is updated now too at https://github.com/threefoldtech/js-ng/pull/560.
