### ISSUE TITLE
Deploying new VDC failing  - failed to fund provisioning wallet error

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/js-sdk#2408]
Was trying to deploy a new VDC , after the payment , it took a lot of time and in the end  , got the following error : 

![image](https://user-images.githubusercontent.com/25789724/106380693-79552200-63cd-11eb-88c6-6dc42a458671.png)

3bot : masid.3bot

**Comment by m-motawea** [comment]
it took a lot of time because it was retrying to do the payment but as you can see in the message, that's a problem with stellar.
