### ISSUE TITLE
threebot start issue when configuring identity

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/js-sdk#241]
startting threebot with no identity doesn't continue with creating identity flow
at first I had this issue, 
![Screenshot from 2020-07-14 12-39-40](https://user-images.githubusercontent.com/1689456/87428212-4b032700-c5e2-11ea-8790-c425960b9c46.png)

so
1- remove the default identity from threebot 
2-  and did 
```
threebot start
```
3 -I got this 
![Screenshot from 2020-07-14 13-02-52](https://user-images.githubusercontent.com/1689456/87428253-5ce4ca00-c5e2-11ea-9c32-87e3a6d55136.png)
4 - I reset/removed my identity from  db on test net
then tried again to create it with 
```
threebot start
``` 
and I got this 
![Screenshot from 2020-07-14 13-16-09](https://user-images.githubusercontent.com/1689456/87420771-243ef380-c5d6-11ea-977b-f30609edd7e0.png)

entering the identity many times doesn't continue the flow 
althoght it works fine  from jsng like this 
```
identity = j.core.identity.new("myidentity", tname, email, words)
identity.register()
identity.save()
j.core.identity.set_default("myidentity")
server = j.servers.threebot.get("default")
server.start()
```

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
