### ISSUE TITLE
explorer.testnet.grid.tf let's encrypt certificate expired, shows error in threebot start process

### ISSUE THREAD

**Issue by archit3kt** [threefoldtech/js-sdk#2411]
Here is the error :

HTTPSConnectionPool(host='explorer.testnet.grid.tf', port=443): Max retries exceeded with url: /api/v1/users/213 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')))

Certificate expired at 11:00 am, please renew it

**Comment by rkhamis** [comment]
fixed in https://github.com/threefoldtech/tfexplorer/issues/283
