### ISSUE TITLE
Cannot deploy a new VDC

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2413]
After the cert expired earlier this week I am trying to launch a new VDC (to start testing with the latest version of the code).  Cannot deploy 

3bot account: weynandkuijpers
testnet

![image](https://user-images.githubusercontent.com/13766992/106417482-9d684000-646d-11eb-9314-af9bba42b49f.png)

**Comment by AhmedHanafy725** [comment]
The `vdc_init` wallet is used to pay for the first hour in vdc, and fund the difference of the plan price.
This wallet was empty, now it is funded with 200 TFT.

**Comment by xmonader** [comment]
please for future issues include the error message in the title so easily can identify duplicates

![image](https://user-images.githubusercontent.com/64129/106435862-11a9e000-647c-11eb-9527-bc922b4b7452.png)

**Comment by weynandkuijpers** [comment]
okay.  Can we please make sure to put this wallet in the monitoring script so that this does not happen again?

**Comment by weynandkuijpers** [comment]
NOt the same issue - ran out of funds again @xmonader

**Comment by xmonader** [comment]
How do you mean not the same? in the image you attached 
![image](https://user-images.githubusercontent.com/64129/106437593-18395700-647e-11eb-82ca-21cf9d38cbe1.png)

and in the other title it says `couldn't get balance for vdc_init wallet` ?


> okay. Can we please make sure to put this wallet in the monitoring script so that this does not happen again?

Please have an issue open in tf_operations for that

**Comment by masteritua** [comment]
Hi! I got same problem on other 3bot? How to resolve it?
And how many funds need for work VDC?

**Comment by masteritua** [comment]
I use testnet

**Comment by masteritua** [comment]
Error message: Couldn't get the balance for vdc_init wallet. Use the refresh button on the upper right to restart VDC creation

**Comment by waleedhammam** [comment]
@masteritua the vdc has a specific setup if you want to use it locally and needs to define activation wallet and initialization wallet
https://github.com/threefoldtech/js-sdk/blob/79ac2571fd35e4843160028d6ca9a8c0dd6d8763/docs/wiki/vdc/vdc_deployer.md it's defined here
