### ISSUE TITLE
Stopped 3bot does not restart

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2414]
When you stop a 3bot and restart it - a payment is required to start the 3bot.

3bot account: weynandkuijpers.3bot
net: testnet
3botname:  jetserjetuno

- data and time when 3bot is stopped: 09:39 - 1 feb 2021
- start 3bot and give is a life to 00:00 8 Feb 2021
- payment as follows:

![image](https://user-images.githubusercontent.com/13766992/106419273-8f1c2300-6471-11eb-8c66-a1124dc55726.png)

- deployment failed.
- tried again (deployment 1048)
- 3bot started with new lifetime up to 8th Feb  2021

![image](https://user-images.githubusercontent.com/13766992/106419881-e40c6900-6472-11eb-9c79-18af6203c7c4.png)

**Comment by ranatrk** [comment]
verified, stopped 3bot then restarted it and payed and deployment was successful
![Screenshot from 2021-02-01 11-16-36](https://user-images.githubusercontent.com/17128393/106440917-140f3880-6482-11eb-8648-fef5bf3b6097.png)
![Screenshot from 2021-02-01 11-37-53](https://user-images.githubusercontent.com/17128393/106440930-18d3ec80-6482-11eb-94bb-f4c3354ee804.png)
