### ISSUE TITLE
Deployed blog appears in the deployed solutions page but not in the deployed blogs overview.

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2417]
In VDC: jetserthing (Gold, testnet) a deployed blog using the example blog source from the manual results in successful deployment.  But the deployed solution pages (generic and specific) display different results.

![image](https://user-images.githubusercontent.com/13766992/106102961-9ed9f580-6159-11eb-9d64-5dbccb3d0336.png)

![image](https://user-images.githubusercontent.com/13766992/106102775-5589a600-6159-11eb-9c47-b236164a2598.png)

![image](https://user-images.githubusercontent.com/13766992/106102825-6a663980-6159-11eb-8b24-241e3c9a7497.png)

**Comment by sasha-astiadi** [comment]
repetitive from other issues
