### ISSUE TITLE
Testnet: usage of all listed nodes possible?

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/js-sdk#2418]
Does the "automatic select my node to deploy on" option in the testnet chatflows cover all of the current farms and all of the current nodes in testnet.  There seems to be a lot of utilisation still happening in the original 8 nodes.?

**Comment by m-motawea** [comment]
no it doesn't utilize all farms. it selects a node within the pool(s) that was previously selected in the chatflow. which means it uses only the farm that the pool is bound to.
