### ISSUE TITLE
Deployed video conferencing facility does not show video 

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2419]
Deployed video conferencing solution in eVDC and started a meeting
- video feeds are not getting through - 2 out of the three device had a camera on and agreed to share video devices.

![image](https://user-images.githubusercontent.com/13766992/105973688-7cd36b00-60a6-11eb-9a0e-ad05b860bb6c.png)

**Comment by weynandkuijpers** [comment]
@tobiaschielens Any updates / progress with this one.  We're aiming to release 2.4 this weekend.

**Comment by tobiaschielens** [comment]
We are looking into the issue. It is probably related to udp ports.

**Comment by weynandkuijpers** [comment]
Any update, we want to make go-nogo decision for the release later today.

**Comment by weynandkuijpers** [comment]
Hi @tobiaschielens this has not progressed.  Is there something we can help you with...?

**Comment by tobiaschielens** [comment]
Will need more debugging on the flists first, then locate the issue in vdc.

**Comment by weynandkuijpers** [comment]
Any update?

**Comment by ken-de-moor** [comment]
Freeflowconnect works on [https://freeflowconnect.threefold.me/](https://freeflowconnect.threefold.me/) and on [meetings.jimber.org](meetings.jimber.org) , we've been using it for months with no issues on standups. I believe there is something going wrong specifically in the networking through VDC ( certain ports being blocked? ) I'm not entirely sure myself. We were tasked to work on digital Twin before anything else currently and don't have the resources to look more into what specifically goes wrong in the VDC for now after the initial analysis. I'll have Tobias check back on here also to report what the exact findings were.

**Comment by tobiaschielens** [comment]
Further steps to investigate the issue:
Try and get the solution running on flists again.
  ->  The marketplace chatflow for meetings is not working anymore so a manual install is required
Test if meetings still works on the flists (It used to work on flists).
Depending on the flist result: 
 -> locate the issue in vdc/meetings app

**Comment by weynandkuijpers** [comment]
@rkhamis This is a big part of what we go out with to test / release the VDC.  We need to get this up and running.  @ken-de-moor I get the tasking but we cannot leave stuff half baked in the wake of doing something new.

**Comment by xmonader** [comment]
@tobiaschielens to move this forward, You can use the old marketplace flists sal on my branch development_vdc_farmmgmt_deals

**Comment by xmonader** [comment]
Issue moved to 2.6 (at least)

**Comment by weynandkuijpers** [comment]
So we have hit a major hurdle that can't be solved.  This is part of the agreed 2.4/2.5 release and we're pushing it forward.  We cannot.

**Comment by weynandkuijpers** [comment]
Issue novlonger relevant.
