### ISSUE TITLE
deploying a new 3bot (gold) results in error

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2422]
3bot name: botcomet
user 3bot id: weynandkuijpers.3bot
net: testnet

error message:
```
An error encountered while trying to fetch certifcates information from <a href="crt.sh" target="_blank">crt.sh</a>. Please try again later.. Use the refresh button on the upper right to restart 3Bot creation
```

![image](https://user-images.githubusercontent.com/13766992/106444936-d917ff80-6497-11eb-9482-77029949887a.png)

**Comment by weynandkuijpers** [comment]
Testing if deployment works no - but the name ```botcomet``` seems not to work anymore - has been registered while 3bot did not deploy

![image](https://user-images.githubusercontent.com/13766992/106447951-893b3780-649b-11eb-8824-ba5ead5ccc64.png)

**Comment by weynandkuijpers** [comment]
For specific node deployment only 11 nodes available while testnet has 30 nodes on the network.....

![image](https://user-images.githubusercontent.com/13766992/106453359-9e679480-64a2-11eb-8324-dbf3334f6f3c.png)

**Comment by xmonader** [comment]
> Testing if deployment works no - but the name `botcomet` seems not to work anymore - has been registered while 3bot did not deploy
> 
> ![image](https://user-images.githubusercontent.com/13766992/106453160-5183be00-64a2-11eb-8809-135ecc09abba.png)

We can't delete identities from the explorer: https://github.com/threefoldtech/js-sdk/issues/1820

> For specific node deployment only 11 nodes available while testnet has 30 nodes on the network.....
> 
> ![image](https://user-images.githubusercontent.com/13766992/106453359-9e679480-64a2-11eb-8324-dbf3334f6f3c.png)
> 
> Selection algorithm does not include every node on testnet.
this is based on search criteria for a node to be suitable for deployment or not @m-motawea can add more info on that

**Comment by weynandkuijpers** [comment]
New 3bot deploys.

![image](https://user-images.githubusercontent.com/13766992/106454625-7bd67b00-64a4-11eb-8a3f-7a1a56bbbe65.png)
