### ISSUE TITLE
Everytime I stop and start a 3bot I have to pay (even when the capacity pool is funded).

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2428]
Every time I stop and start a 3bot I have to make a payment for a certain period of time

3bot:  botcomettoo
3bot id: weynandkuijpers
net: testnet

Current situation:
![image](https://user-images.githubusercontent.com/13766992/106480741-265e9600-64c5-11eb-8d58-5a858bca5000.png)

capacity pool 1112 is "funded" until 15th of march 2021

Now I stop the 3bot
![image](https://user-images.githubusercontent.com/13766992/106480919-54dc7100-64c5-11eb-8f09-2e45977a51e3.png)

And start it again on the same server I have to fund it for at least 1day+
![image](https://user-images.githubusercontent.com/13766992/106481116-8bb28700-64c5-11eb-88e5-6871c131189f.png)

The money is not lost - it's added to the capacity pool but I don;t think it's right to have a properly funded 3bot having to receive more funds to start.

![image](https://user-images.githubusercontent.com/13766992/106482107-902b6f80-64c6-11eb-9478-3a082761515f.png)

**Comment by m-motawea** [comment]
we can reuse the same pool id if the selected farm was not changed than the previous one. but if that pool contains deployed workloads, then it should create a new pool since it will affect the expiration of these workloads

**Comment by weynandkuijpers** [comment]
Not sure if I agree.  If what you say is true stopping and starting a 3bot always leads to creating a new capacity pool for a farm when there are other workloads running on that farm than the 3bot.  So if I have one container running on a farm and I stop and start the 3bot 3 times I will get a new pool every time I do so (meaning I end up with 4 capacity pools).  This is hard to manage and wasteful - how will I consume these 4 pools and make use of the available capacity?

I think it's better to stick to one pool per farms (unless manually someone creates multiple) for simplicity.  If starting and stopping a 3bot means the other workloads expiration time changes - please make a warning that this is the case.

**Comment by m-motawea** [comment]
I replied on the wrong issue instead of https://github.com/threefoldtech/js-sdk/issues/2429

yes restarting a threebot doesn't create a new pool.

**Comment by xmonader** [comment]
@m-motawea is that version available on testnet already?

**Comment by weynandkuijpers** [comment]
fixed
