### ISSUE TITLE
etcd solution shouldn't use port forward

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#2431]
### Description

at the end of the chatflow, it asks the user to use port-forward to expose the cluster. but users don't have access to the node to do that. Also, etcd should use ingress to expose the cluster since it uses http.

![image](https://user-images.githubusercontent.com/32568986/106495628-a0dae600-64c4-11eb-945c-abd4255fa286.png)

**Comment by waleedhammam** [comment]
verified
![Screenshot from 2021-02-23 18-33-44](https://user-images.githubusercontent.com/10658229/108875285-ae881500-7605-11eb-9b3d-dc94549daef8.png)
