### ISSUE TITLE
Digibyte icon not shown in the correct way

### ISSUE THREAD

**Issue by MElborolossy** [threefoldtech/js-sdk#2433]
### Description

Digibyte Icon not shown in the correct way.

![image](https://user-images.githubusercontent.com/11272864/106561284-0e246080-6531-11eb-8998-05e12916388f.png)

Closer look
![image](https://user-images.githubusercontent.com/11272864/106561362-3318d380-6531-11eb-8ee8-96ac6b6dcf7c.png)

### Suggestion 
We can take the first part of the logo "D sign" as round logo

**Comment by hossnys** [comment]
verified
![Screenshot from 2021-02-23 18-57-53](https://user-images.githubusercontent.com/26298009/108878661-299efa80-7609-11eb-810b-c0ac7c5a7281.png)
![Screenshot from 2021-02-23 18-58-09](https://user-images.githubusercontent.com/26298009/108878668-2a379100-7609-11eb-9743-f9db1a84c67e.png)
