### ISSUE TITLE
Deploy Meetings solution shouldn't ask for a flavour

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2439]
I deployed Meetings from the marketplace in the VDC. Chatflow asks me for the flavour. This is confusing, best to autoselect, as for this solution, it's not important. 

### Version information

* OS: MacOS BigSur 
* Project commit/version: VDC 2.4 testnet
* Browser: Chrome

**Comment by xmonader** [comment]
@tobiaschielens what is the lowest option for your meetings app?

```
CHART_LIMITS = {
    "Silver": {"cpu": "1000m", "memory": "1024Mi"},
    "Gold": {"cpu": "2000m", "memory": "2048Mi"},
    "Platinum": {"cpu": "4000m", "memory": "4096Mi"},
}
```

**Comment by waleedhammam** [comment]
Maybe it's needed for the growth of users, more users will need more resources ?

**Comment by ken-de-moor** [comment]
The more resources you assign, the more users it'll be able to handle at once. If you're only going to be using it with a few people at once, silver will do. If you want to do full company meetings with 30 people, platinum would be recommended.

We don't have exact stats yet on how many users would be possible to handle for each plan, as a lot of this also depends on how many people enable/disable camera, or what views they are in.

**Comment by xmonader** [comment]
> The more resources you assign, the more users it'll be able to handle at once. If you're only going to be using it with a few people at once, silver will do. If you want to do full company meetings with 30 people, platinum would be recommended.
> 
> We don't have exact stats yet on how many users would be possible to handle for each plan, as a lot of this also depends on how many people enable/disable camera, or what views they are in.

Thank you @ken-de-moor . @gmachtel I will label this as won't fix :)

**Comment by gmachtel** [comment]
OK, but wouldn't some guidance as mentioned by Ken be useful (ex. silver for up to 4 to 6 people, platinum for bigger teams ?
