### ISSUE TITLE
Message unclear when running out of capacity

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2446]
### Description

When I tried to deploy a workload in my VDC, I had an error message. 

![image](https://user-images.githubusercontent.com/30384423/106736714-1904f100-6616-11eb-9dfd-d9860f738ea1.png)

This message is not clear. Make it simple.

- [ ] Failed to deploy Mattermost. Could not find resources in the cluster, please upgrade your worker nodes with more capacity and redo the deployment after.
- [ ] add link to manual on the message. 'more info on the [manual](https://manual.threefold.io/#/evdc_upgrade)'

This will make it clearer for the user.

**Comment by xmonader** [comment]
@OmarElawady @m-motawea I know you guys hardened the precheck for resources in the cluster, can you please add the manual link to your error message and close this issue?

**Comment by xmonader** [comment]
optimistic resources check is already in place, but we can't really inspect all of kubernetes errors to send a "human" friendly information.
