### ISSUE TITLE
Allow configuring farmers in for vdc deployer

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#2449]
- Currently, we select only `freefarm` for vdc and it should be configurable for the package, maybe a json file having farms to be used per environment instead of hardcoding them in size.py file
- We should be able to Select farms for k8s clusters, zdb storage, .. for deployments 
- Option: can add weights/priority for the selected farms per user (later) to be addressed in #2338

**Comment by xmonader** [comment]
@waleedhammam @m-motawea this should be in verification already no?

**Comment by waleedhammam** [comment]
yes: implemented here: https://github.com/threefoldtech/js-sdk/commit/e5fcc415119dc2cad6efcfacbe3342faf89e44fa

**Comment by waleedhammam** [comment]
verified
