### ISSUE TITLE
Deployed wiki does not appear in My Workloads

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2451]
I deployed a wiki in my eVDC and all went well. But the wiki instance does not appear in `My workloads`. 

In the overview of `Deployed Solutions`it does appear. 

![image](https://user-images.githubusercontent.com/30384423/106776286-381a7780-6644-11eb-8d9f-46cc2e75e84a.png)

![image](https://user-images.githubusercontent.com/30384423/106776262-305ad300-6644-11eb-912f-2c1533a414e6.png)

**Comment by abom** [comment]
Duplicate of #2375, it should be fixed now, when did you create this VDC? and on which network?

@waleedhammam Can a restart/update reloads latest changes? and a "refresh" to chatflows is needed?

Note that previously deployed wikis will not be listed in "My Workloads", but they will be listed in "Deployed workloads" because they already took this name in current k8s deployment. Newer deployments should be working.

**Comment by gmachtel** [comment]
OK VDC was created yesterday. But indeed, a refresh of the VDC is needed I think. As a user has paid for a full month, he doesn't want to throw his VDC away to get the latest update. And if workloads run, you don't want to interrupt them anymore.

**Comment by waleedhammam** [comment]
@gmachtel There's a button called `Update Dashboard` under your name menu, this updates the deployed vdc dashboard to the latest verstion

![Screenshot from 2021-02-03 20-27-09](https://user-images.githubusercontent.com/10658229/106791932-3cec2500-665e-11eb-9497-23b7408499ab.png)

**Comment by gmachtel** [comment]
I pushed the 'Update Dashboard' button, but the wiki deployments still don't appear when i click on them afterwards.

**Comment by waleedhammam** [comment]
> I pushed the 'Update Dashboard' button, but the wiki deployments still don't appear when i click on them afterwards.

for old workloads, it may not appear cause the changes were in the deployment chart labels/chatflows, so it will be on the newly deployed deployments. as for now we can get it via `deployed solutions` button

**Comment by abom** [comment]
@gmachtel Yes, I mentioned this at https://github.com/threefoldtech/js-sdk/issues/2451#issuecomment-772639869

> Note that previously deployed wikis will not be listed in "My Workloads", but they will be listed in "Deployed workloads" because they already took this name in current k8s deployment. Newer deployments should be working.

If they are new deployment, please give us a screenshot from configuration (when you enter wiki URL) in the chatflow, and make sure to restart/refresh.

**Comment by gmachtel** [comment]
OK new wiki workload deployed, and that one indeed appeared in My workloads.
