### ISSUE TITLE
threebot deployer: change location fails when select deployment location policy automatic

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#2452]
**environment:** devnet

### Steps
1- create a threebot 
2- stop this threebot
3- change the location of this threebot
4- in the step of select deployment policy, select `Automatic`.

### Result

![image](https://user-images.githubusercontent.com/41957921/106865467-e9b4b980-66d3-11eb-9afe-a569ffa96b57.png)

**Comment by waleedhammam** [comment]
Verified
