### ISSUE TITLE
Deployed solutions UX questions/improvements

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2459]
![image](https://user-images.githubusercontent.com/64129/106883007-11ae1800-66e8-11eb-9426-b9dcb7d00f5b.png)

- the vdc name is already known why do we show it in the table if all are running on the same vdc?
- what is "release" in the header, what is  "deployment" ?
- why do we show urls for the pods
- why all of them aren't grouped together?
- why there's a delete button on pods? what the point? this page should be readonly.

If just for all of the pods, maybe we should rename it to be deployed pods?

**Comment by MElborolossy** [comment]
Verified
commit d0eea8f1482459bd507ba0bfcca889be09023f6a
![image](https://user-images.githubusercontent.com/11272864/108966066-665d0700-7686-11eb-877a-d195d42aa206.png)
