### ISSUE TITLE
Marketplace: Please update Digibyte to DigiByte and Scale to Skale

### ISSUE THREAD

**Issue by samtaggart** [threefoldtech/js-sdk#2460]
<img width="508" alt="Screen Shot 2021-02-04 at 1 47 50 PM" src="https://user-images.githubusercontent.com/50134479/106888697-9badaf00-66ef-11eb-9c3b-96e28603bd4d.png">

**Comment by AhmedHanafy725** [comment]
**Verified**
**Branch:** development_vdc
**Commit:** 82c66e58985d5ae57b1ac50dd8bf9822ef741c2b
### marketplace
![image](https://user-images.githubusercontent.com/41957921/106899670-4fb63680-66fe-11eb-8767-97e5afaafe1b.png)

### vdc marketplace
![image](https://user-images.githubusercontent.com/41957921/106899722-6066ac80-66fe-11eb-89d3-3cda9a91924c.png)
