### ISSUE TITLE
cant make website with custom domain

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#2464]
dont know if i did everything right.

domain name: sashaastiadi.xyz

Already made record to redirect to IP 185.69.167.167

as shown

<img width="1440" alt="Screenshot 2021-02-04 at 14 19 47" src="https://user-images.githubusercontent.com/43240801/106898611-b3d3fd00-66f4-11eb-81e8-df93026ac6f4.png">

still got this error on chatflow
<img width="1155" alt="Screenshot 2021-02-04 at 14 22 18" src="https://user-images.githubusercontent.com/43240801/106898647-bcc4ce80-66f4-11eb-8ed3-f3d41cb3fd0c.png">

**Comment by waleedhammam** [comment]
it doesn't point to anything
```
➜  js-sdk git:(development_vdc) dig sashaastiadi.xyz              

; <<>> DiG 9.16.1-Ubuntu <<>> sashaastiadi.xyz
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 20007
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;sashaastiadi.xyz.		IN	A

;; Query time: 403 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Thu Feb 04 15:42:55 EET 2021
;; MSG SIZE  rcvd: 45

➜  js-sdk git:(development) nslookup sashaastiadi.xyz               
Server:		127.0.0.53
Address:	127.0.0.53#53

** server can't find sashaastiadi.xyz: SERVFAIL

➜  js-sdk git:(development) 
```

**Comment by sasha-astiadi** [comment]
i will wait for an hour and see if i still hacve problem on it

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/106913014-40d68080-670c-11eb-873d-32df361cd826.png)

```~> dig xmonweb.grid.tf

; <<>> DiG 9.16.1-Ubuntu <<>> xmonweb.grid.tf
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36117
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;xmonweb.grid.tf.		IN	A

;; ANSWER SECTION:
xmonweb.grid.tf.	299	IN	A	185.69.167.139

```


![image](https://user-images.githubusercontent.com/64129/106912953-35835500-670c-11eb-821a-a1e84bbb51b8.png)
