### ISSUE TITLE
gather all types of error messages we have for failed deployments

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#2466]
- [ ] how many kinds of error messages do we have for every type of error deployment
- [ ] need the documentation on github of all messages of errors
- [ ] sasha needs to edit and review it to look better and readable to users

for example
<img width="674" alt="Screenshot 2021-02-04 at 15 41 00" src="https://user-images.githubusercontent.com/43240801/106908571-b556f280-66ff-11eb-9f4e-5d0b9902cf3a.png">

this is totally unacceptable
too long and confusing

**Comment by xmonader** [comment]
as discussed before, there're many errors coming from kubernetes will work on an alternative to link to a detailed alerts info in the VDC controller. #2794
