### ISSUE TITLE
as a user i want to know how much capacity i have used and i have left on every worker node.

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#2467]
- [ ] as a user i want to see a list of how much unused capacity I have on every node
- [ ] as a user i want to see a list of how much capacity I have used, on which deployed solution
- [ ] as a user I want to know how much capacity a solution deployment is going to take. for example: deploy a new cryptpad, will take minimum 240 mb for initial deployment. / required free capacity: minimum 240mb on your vdc.
- [ ] as a user I want to know how much capacity a solution deployment have taken. for example: you just deployed a new cryptpad, it consumed 240 mb out of xyz node.
- [ ] ~as a user I want to be not-allowed to deploy something new if I don't have enough capacity, so I don't get 'not enough resource' failure after spending 10 minutes trying deploying a solution.~ https://github.com/threefoldtech/js-sdk/issues/2474

**Comment by xmonader** [comment]
execute kubectl top nodes

![image](https://user-images.githubusercontent.com/64129/106913759-03262780-670d-11eb-8de6-90787d21abc0.png)

**Comment by weynandkuijpers** [comment]
Cool - can we use this to assess whether we can deploy a marketplace application before we actually have entered all the information to deploy the capacity.  Something like:
```
 if (available_capacy - needed_capacity) < 0 display_warning
 ````
 The warning is a friendly one to state that all available capacity in the VDC is being used (show output)
 ```john@RescuedMac:~/.kube$ kubectl top nodes
NAME         CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
k3os-17597   71m          7%     690Mi           34%       
k3os-23976   28m          1%     306Mi           7%        
k3os-29391   101m         1%     549Mi           1%        
john@RescuedMac:~/.kube$ kubectl get nodes
NAME         STATUS   ROLES    AGE   VERSION
k3os-17597   Ready    master   18h   v1.19.4+k3s1
k3os-23976   Ready    <none>   18h   v1.19.4+k3s1
k3os-29391   Ready    <none>   77m   v1.19.4+k3s1
```
And ask to deploy a new worker node (or kill one of the up and running applications.

**Comment by weynandkuijpers** [comment]
The information is available, as per what I learned from kontena-lens:
![image](https://user-images.githubusercontent.com/13766992/107015538-47b9cd80-67b6-11eb-8cba-b3a4db5ac72f.png)

so it's a matter of presenting the same information (used capacity, max. chunk reservable, max capacity)

**Comment by xmonader** [comment]
the issue for ahead of time check is active work https://github.com/threefoldtech/js-sdk/issues/2474, the rest of the issue is to be reviewed for 2.5

@weynandkuijpers did you install the monitoring stack solution on your cluster? because by default 
![image](https://user-images.githubusercontent.com/64129/107018417-14247680-67a9-11eb-8eda-98b9aed27cea.png)

**Comment by sasha-astiadi** [comment]
kubectl should be a ready-installed application, in my opinion.

**Comment by sasha-astiadi** [comment]
@xmonader can we use the exact same monitoring stack as DO here? https://www.digitalocean.com/community/tutorials/how-to-set-up-a-kubernetes-monitoring-stack-with-prometheus-grafana-and-alertmanager-on-digitalocean

**Comment by xmonader** [comment]
> @xmonader can we use the exact same monitoring stack as DO here? https://www.digitalocean.com/community/tutorials/how-to-set-up-a-kubernetes-monitoring-stack-with-prometheus-grafana-and-alertmanager-on-digitalocean

Why? there's a functional monitoring stack existing already.

**Comment by weynandkuijpers** [comment]
The existing stack will do and will have sufficient information to report on what we need.  It's part of the 2.5 release so we're good.
