### ISSUE TITLE
Can I recover my workload if I ran out of tokens ?

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2470]
If I run out of tokens and my grace period has ended, is there still a way to recover my workload ?

**Comment by xmonader** [comment]
in 2.4: you enter grace period for two weeks if not paid by then your workloads will be removed
in 2.5: we will have a backup feature for the resources (configs, secrets.. etc) only NOT volumes.
if the user want to backup and restore their volumes in the future they should use something like [velero](https://velero.io/) (backing up persistent volumes is out of scope for 2.4 and 2.5)

**Comment by andhartl** [comment]
can we state that user need to backup themselves for 2.4 and for 2.5 the volumes? also mark it in bold within the manual

**Comment by sasha-astiadi** [comment]
@gmachtel @xmonader we need a tutorial on how to do manual backup using velero on manual

**Comment by xmonader** [comment]
Backup is for 2.5 and we are still investigating velero usage.
