### ISSUE TITLE
What does 1000m CPU resource mean ? 

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2473]
When deploying a solution, it often asks for the flavour. Clear for memory and storage, but what does "1000m", "2000m", ... compute units mean ? 1 core, 2 cores, ... ? why put 1000 ? 

<img width="911" alt="Screenshot 2021-02-05 at 10 16 53" src="https://user-images.githubusercontent.com/30384423/107014374-cc4b2280-679b-11eb-9f14-86422a47a295.png">

**Comment by waleedhammam** [comment]
duplicate: https://github.com/threefoldtech/js-sdk/issues/2353

> This is the official resource units for kubernetes : https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-units-in-kubernetes
