### ISSUE TITLE
vdc: wrong link to manual in publisher, wiki, and blog deployer

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#2477]
- [ ] website manual should be https://wiki.cloud.threefold.io/#/evdc_website
- [ ] wiki manual should be https://wiki.cloud.threefold.io/#/evdc_wiki
- [ ] blog manual should be https://wiki.cloud.threefold.io/#/evdc_blog 

need to know which are the right links in new wikis and give to @xmonader team to be put on chatflows

**Comment by xmonader** [comment]
Where do you find the wrong link? and where does it link to?

**Comment by sasha-astiadi** [comment]
<img width="1440" alt="website_identify" src="https://user-images.githubusercontent.com/43240801/107203902-4da0f000-69fc-11eb-9300-d84a9c405275.png">
it led me to herehttps://sashaastiadi-sasha.vdctest.grid.tf/vdc_dashboard/#/solutions/website
![Uploading Screenshot 2021-02-08 at 10.58.25.png…]()

@xmonader

**Comment by abom** [comment]
I thought this would be linked to sample repositories. 

I have some remarks on the provided manual links:

1- https://manual2.threefold.io/#/evdc_wiki has outdated screenshots
2- There's no link for docs link for blogs and I couldn't find any (should also mention the blog format)

Will update the links in the deployer once these points are resolved.

**Comment by sasha-astiadi** [comment]
@abom this issue is for website. i will create another issue for blog and wiki

**Comment by abom** [comment]
@sasha-astiadi No need, will track all of them here.

**Comment by sasha-astiadi** [comment]
Yes but it will take some time waiting until everything is finished. i don't want testers start testing and going to wrong links. do it now for website, I make a checklist above.

**Comment by xmonader** [comment]
> Yes but it will take some time waiting until everything is finished. i don't want testers start testing and going to wrong links. do it now for website, I make a checklist above. @abom

Add empty pages on the wiki and send the links here. no need to do in two steps.

**Comment by sasha-astiadi** [comment]
blocked because the manual of vdc moved to info_cloud but not live yet

**Comment by gmachtel** [comment]
Completed with the links, however I don't know whether this link will stay like this, as if publishtools works correctly it should become ex. cloud.threefold.io/info/cloud/evdc_website . But that doesn't work right now.

**Comment by sasha-astiadi** [comment]
@xmonader @abom can be updated now
