### ISSUE TITLE
documentation: How to deploy website using custom domain?

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#2478]
can you create a walkthrough video tutorial on how to mirror your custom domain to the IP and deploy website on vdc using the custom domain? i tried and failed because i don't know how. its very important so I can also do this, and show it to our partners. one of the most requested features of the vdc is actually web hosting using custom domain.

- [x] video of deployment using custom domain
@xmonader 
- [ ] deploy custom website tutorial on vdc manual @gmachtel

**Comment by xmonader** [comment]
following this comment didn't work for you?

https://github.com/threefoldtech/js-sdk/issues/2464#issuecomment-773382898

**Comment by sasha-astiadi** [comment]
no it didnt work for me

**Comment by xmonader** [comment]
@sasha-astiadi did you make sure your DNS record got propagated? execute `dig DOMAIN_NAME` in your command line, if it doesn't resolve to your Kubernetes IP then it means you need to use a better DNS provider.

**Comment by xmonader** [comment]
@hossnys please provide a small video showing creation of a domain on name.com and binding that in website deployment with that domain

**Comment by hossnys** [comment]
here is a complete demo for how to deploy website using custom domain and how to create the domain on name.com account: 

https://drive.google.com/file/d/1B2LnMUHf82lz9KhtLDupmd3OCiwEgUkH/view?usp=sharing

**Comment by xmonader** [comment]
@hossnys thank you! 

@gmachtel please close the issue once done with the docs.

**Comment by gmachtel** [comment]
Nice! Docs created on https://github.com/threefoldfoundation/info_cloud/blob/development/src/evdc/evdc_marketplace_webdomain.md
