### ISSUE TITLE
using 8080 doesn't do proper redirect

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#249]
trying http://localhost:8080/admin -> http://localhost and 

```
diff --git a/jumpscale/sals/nginx/templates/location.conf b/jumpscale/sals/nginx/templates/location.conf
index b6f1c30..395921f 100644
--- a/jumpscale/sals/nginx/templates/location.conf
+++ b/jumpscale/sals/nginx/templates/location.conf
@@ -17,7 +17,7 @@ location {{ location.path_url }} {
 
     {% if location.force_https %}
         if ($scheme = http) {
-            return 301 https://$host$request_uri;
+            return 301 https://$http_host$request_uri;
         }
     {% endif %}
 
```

didn't help

**Comment by abom** [comment]
I tried redirecting to the correct port (in case of 8080, the correct port should be 8433), but also didn't work, I even removed the redirection part completely, it redirects without the correct port too.

Will check again what's the source of this redirection.

**Comment by abom** [comment]
First, the port is not correct when redirecting from 8080, which should be fixed by #784.

The other problem is browser caching 301 redirects, if you're using chrome, you can try opening developer tools and click-hold reload button and "Empty cache and Hard reload".

I used 302 redirects now , but I think we should use 301 on production?

**Comment by xmonader** [comment]
I think it should be ok for now, probably could have sent no-cache or something from nginx side? but as long as it works now i'm happy

**Comment by abom** [comment]
Verification steps:

1- Start threebot as `threebot start` then go to `http://localhost/admin` should be redirected to `https`.
2- Start local threebot as `threebot start --local` then go to `http://localhost:8080/admin` should be redirected to `https` (port 8443)

**Comment by Pishoy** [comment]
verified 
1 - redirect correctly to https as below
![image](https://user-images.githubusercontent.com/21987477/91840748-7d7be880-ec51-11ea-87b1-aa2d4c41fc3c.png)

w - redirect to https using port 8443
![image](https://user-images.githubusercontent.com/21987477/91840889-b5832b80-ec51-11ea-8d15-9d566d0dd292.png)
