### ISSUE TITLE
3BOT: Local installation of 3Bot gives errors 400 and 500

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2490]
I have deployed a local 3Bot, but unlike before, it is no longer asking me to connect through 3F Connect but there's simply an `admin dashboard` button. 

Then I introduce my credentials. it gives an error 400, and blanks out my 3bot ID. 

![image](https://user-images.githubusercontent.com/30384423/107236755-4989c800-6a26-11eb-98a1-319d628107c8.png)

I fill in 3bot ID again, now it gives an error 500. Unclear to me what it means. 

![image](https://user-images.githubusercontent.com/30384423/107236803-58707a80-6a26-11eb-9674-e611cb05c507.png)

### Version information

* OS: MacOS Big Sur
* latest version based on js-ng 11.0, set up on Feb 8 from 'install js-sdk'
* Browser: Chrome

### Installation method

Local

**Comment by waleedhammam** [comment]
This setup seems pretty old, current version:
JS-NG: 11.0b12
JS-SDK: 11.0b14

Before in early stages for deployed 3Bot, it used to start without identity `development mode`, then the user sets his identity.
This is changed.

Starting the server now should be using `threebot start`, It'll lead you to the identity manager to enter the tname, email, words.

or configuring identity manually using `j.core.identity.new("instance_name", "tname", "email", "words",  "explorer_url")

See: https://threefoldtech.github.io/js-sdk/wiki/#/./quick_start for more information

Also please make sure to have the latest code/env, or install via pip as stated in the quick start

**Comment by weynandkuijpers** [comment]
Please verify and close

**Comment by AhmedHanafy725** [comment]
**Verified**

on a fresh container, `threebot start`
 
![image](https://user-images.githubusercontent.com/41957921/111910173-f5ccbe80-8a68-11eb-846e-774fbc061dca.png)


adding identity from admin setting

![image](https://user-images.githubusercontent.com/41957921/111910462-219c7400-8a6a-11eb-9884-9ce2d82628f2.png)

![image](https://user-images.githubusercontent.com/41957921/111910437-03cf0f00-8a6a-11eb-8065-9420781c0cb2.png)
