### ISSUE TITLE
VDC: Deployed node after creating the vdc has different ssh key

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#2498]
### Steps
1- Deploy a vdc.
2- Go to vdc compute nodes
3- Add node

### Expected
the added node has the same key as the master.

### Result
the added node has a different key, although the key already on the threebot container

master's wid: https://explorer.devnet.grid.tf/api/v1/reservations/workloads/26940
worker wid: https://explorer.devnet.grid.tf/api/v1/reservations/workloads/26948
added node's wid: https://explorer.devnet.grid.tf/api/v1/reservations/workloads/26963

**Comment by RafyAmgadBenjamin** [comment]
### Fixed 
### Branch 
`development_vdc_keys`
### Commit
fc2e8a885aec6adecd9df814dd49e38d5b2db46f

**Comment by hossnys** [comment]
verified 
all three workloads have the same ssh-key 
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/11617
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/11624
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/12397

![Screenshot from 2021-02-24 10-52-19](https://user-images.githubusercontent.com/26298009/108976857-a0330b00-7690-11eb-9d93-0e07feebb965.png)

![Screenshot from 2021-02-24 10-52-01](https://user-images.githubusercontent.com/26298009/108976849-9f01de00-7690-11eb-92d1-ecb86fae26ec.png)

![Screenshot from 2021-02-24 10-53-10](https://user-images.githubusercontent.com/26298009/108976861-a1fcce80-7690-11eb-974d-fb80db09de27.png)

![Screenshot from 2021-02-24 11-11-18](https://user-images.githubusercontent.com/26298009/108977289-0fa8fa80-7691-11eb-9eef-02cb49450408.png)
