### ISSUE TITLE
Dashboard: Expected to ssh into generic container but no step to get my public key

### ISSUE THREAD

**Issue by AhmedSa-mir** [threefoldtech/js-sdk#2500]
### Description

When deploying an flist in admin dashboard, I expected to ssh into my generic container but there was no step to get my public key.

### Steps to reproduce

Go to admin dashboard -> deploy a generic container

**Comment by xmonader** [comment]
It really depends on the container image, usually, this should get passed as env var and in the container startup script it prepares everything for ssh. or am I missing something?
