### ISSUE TITLE
create QR code to topup prepaid VDC wallet

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2502]
User in their view of prepaid wallets should see a button to show up a dialog with QR code encoding the address and maybe fixed 100 TFT that use can change after scanning in the threefold connect app 
- [x] VDC deployer
- [x] VDC dashboard

**Comment by waleedhammam** [comment]
Verified, development_vdc devnet

![Screenshot from 2021-02-23 18-04-46](https://user-images.githubusercontent.com/10658229/108871264-a5954480-7601-11eb-8178-2513518dc866.png)
![Screenshot from 2021-02-23 17-59-21](https://user-images.githubusercontent.com/10658229/108871266-a62ddb00-7601-11eb-9eb2-c135d0bfcfd6.png)
