### ISSUE TITLE
marketplace category edits

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#2510]
on marketplace decentralized we:
<img width="1161" alt="Screenshot 2021-02-10 at 17 08 34" src="https://user-images.githubusercontent.com/43240801/107537155-dc5f6980-6bc2-11eb-9479-19ae9823b553.png">

- [ ] move kubeapps from decentralized we to decentralized developers
- [ ] move zeroCI from decentralized office to decentralized developers
- [ ] move document server and file browser  from decentralized we to decentralized office

**Comment by hossnys** [comment]
verified
- kubeapps & ZeroCI
![Screenshot from 2021-02-23 20-32-07](https://user-images.githubusercontent.com/26298009/108890485-51e12600-7616-11eb-992e-5f13521fbf1f.png)

- document server 
![Screenshot from 2021-02-23 20-34-30](https://user-images.githubusercontent.com/26298009/108890688-8ead1d00-7616-11eb-915b-e74b298711e8.png)
