### ISSUE TITLE
grid3.0 sal

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2516]
The idea is we prepare the reservation request to be sent to the node directly, no more interaction with the explorer, and the data of the nodes and users will be coming from GridDB (blockchain database has all of hte info of the users / nodes). 

- branch out of development_zos3
- The sal should live in sals/zos3 (otherwise it will be broken for good)
- in that version the reservation schema been simplified a lot

For every workload type we should have 
- Python class
- challenge builder to build the challenge needed in the backend 

go code: https://github.com/threefoldtech/zos/tree/provision-engine-cleanup/pkg/gridtypes
gateway types: https://github.com/threefoldtech/tfgateway/blob/feat/tfgateway-new-provision/types.go

- [x] network
- [x] volume
- [x] zdb
- [x] container
- [x] kubernetes
- [x]  ipv4

**Comment by abom** [comment]
Added initial implementation with challenge builder from grid types.

**Comment by abom** [comment]
Added capacity objects to all workload types.
