### ISSUE TITLE
provide a way for the user to securely enter the secret text when importing a wallet

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/js-sdk#2518]
![Screenshot from 2021-02-11 12-06-46](https://user-images.githubusercontent.com/42457449/107646029-29eedb80-6c82-11eb-8ac3-406c633ece6a.png)

### Description

in wallets -> import wallet screen, the text entered by the user in the secret input box should be obscured so that it cannot be read by anyone near for the purpose of privacy.

this should apply also to any similar screen when entering a wallet secret or any sensitive information.

### Implementaion
the HTML `input` element with type `password` can be used with an appended icon and callback to control the visibility.

![Screenshot from 2021-02-11 17-00-42](https://user-images.githubusercontent.com/42457449/107653907-ce751b80-6c8a-11eb-872f-45bf684411e2.png)
![Screenshot from 2021-02-11 17-00-58](https://user-images.githubusercontent.com/42457449/107653916-d03edf00-6c8a-11eb-8185-16662d4e2a22.png)

**Comment by weynandkuijpers** [comment]
Please verify and close

**Comment by MElborolossy** [comment]
Verified
Branch: development
commit: d183ed697ec0e8aaf3209aa5e586419e82502c1f
![image](https://user-images.githubusercontent.com/11272864/111139338-af1f2600-8589-11eb-9802-01b8868e49dc.png)
