### ISSUE TITLE
pools' info and pools' table don't have ipv4u information

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#2519]
![image](https://user-images.githubusercontent.com/41957921/107656300-b1d9e300-6c8c-11eb-8437-33fbe19b47d9.png)

![image](https://user-images.githubusercontent.com/41957921/107656320-b7cfc400-6c8c-11eb-832c-e92e635505d5.png)

**Comment by hossnys** [comment]
verified 

![Screenshot from 2021-02-23 20-28-56](https://user-images.githubusercontent.com/26298009/108890129-d97a6500-7615-11eb-8644-bcd1477acca9.png)
