### ISSUE TITLE
restored marketplace deployments can't be deleted

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#2523]
### Description

since we delete marketplace deployments using helm, for restored resources, they are not listed as helm releases, so deleting them using helm fails

### Suggestion:

1- listing deployments similar to how we list grid workloads using uuid and a solution type in its labels without the need to use helm

2- deploy each chart in a separate namespace. for deletion we just delete the namespace

**Comment by m-motawea** [comment]
we'll go with second suggestion. a namespace for each release

**Comment by waleedhammam** [comment]
verified namespace for each solution
