### ISSUE TITLE
Cannot deploy simple cryptpad in my VDC - VD

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2527]
While trying to deploy a cryptpad  instance to test whether certain hardware server are available for deployment (https://github.com/threefoldtech/tf_operations/issues/76) I got an error that something was wrong and deployment was impossible
![cryptpad-error](https://user-images.githubusercontent.com/13766992/107905012-e688bb80-6f66-11eb-8e11-358817296b26.png)

when going to the "My VDC's" overview page I got the error that my VDC would expire in 1 hour (my be the cause for the cryptpad deployment error) but in the VDC overview I have 10 days left to expiration.  Confusing.

![vdc-expire](https://user-images.githubusercontent.com/13766992/107904943-b17c6900-6f66-11eb-92f2-86190b106203.png)

After funding the wallet with 50 TFT's still resulted in failure to deploy
![cryptpad-error-1](https://user-images.githubusercontent.com/13766992/107905374-e806b380-6f67-11eb-810e-5567eacefb80.png)

**Comment by weynandkuijpers** [comment]
Deployed a new VDC (Diamond) -> https://github.com/threefoldtech/js-sdk/issues/2528

Here the cryptpad does deploy
![diamond-cryptpad-deployed](https://user-images.githubusercontent.com/13766992/107907354-ee4b5e80-6f6c-11eb-9e24-4c2eb5b0a177.png)

So it's has something to do with the other VDC>. (Other) VDC has been up and running for 2 weeks now, maybe updated code in the deployment?

**Comment by xmonader** [comment]
Probably your VDC has entered the grace period ( messages for the grace period improved here #2544 )

**Comment by OmarElawady** [comment]
The error is caused by the default empty value threefoldVdc.backupType in the charts. In the updated branch development_vdc it's set to "vdc". In the old ones, it's set to the default value which is an empty string causing this error:

![Screenshot from 2021-02-23 16-11-50](https://user-images.githubusercontent.com/13040543/108856832-20a32e80-75f3-11eb-88df-fb9edd12428b.png)

Should be fixed by quoting the value in the helm charts

**Comment by xmonader** [comment]
@OmarElawady to move to verification?

**Comment by weynandkuijpers** [comment]
So new deployments of VDC all have this "value" because this is now defined in the helm chart for deploying.  This means this "failure" mode should not happen anymore with new VDC deployments, existing ones still might suffer from this.

In term of validating the is not much we can do but deploying a new VDC and see if we can deploy.  Which works.  Closing the issue.
