### ISSUE TITLE
VDC: Deployed a VDC Diamond and ended up with one master and one worker node.

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2528]
### Description

Deployed a VDC diamond expecting the following assets to be deployed for me:
![diamond-vdc-deploy](https://user-images.githubusercontent.com/13766992/107906527-c78c2880-6f6a-11eb-84c5-48d6c36238f7.png)

- small controller
- 4X worker nodes, 8 core and 32GB of memory  

### Version information

Actual deployment is 1 master and 1 worker node (8vcpu, 32GB memory).  so missing 3 worker nodes LARGE (3X 8vcpu and 32GB of RAM).

For the storage part, 
![diamond-vdc-deployed](https://user-images.githubusercontent.com/13766992/107906665-19cd4980-6f6b-11eb-966e-08b4820e1a91.png)
x10GB 
For the storage part, promised is 100GB of SSD and 10TB of HDD ->  I only see 10x10GB of storage which I take is the SSD part, but no mention of the HDD part.  If it means "10TB of HDD when you use it" some reference / notice needs for be there for this.
![diamond-storage](https://user-images.githubusercontent.com/13766992/107907125-403fb480-6f6c-11eb-9319-3d7a310b16d5.png)

**Comment by xmonader** [comment]
## For kubernetes workers:
We start with 1 worker and scale up till the limit based on the usage, if you want to force add workers you can continue in the add worker flow and use the prepaid wallet (it has the money already) https://github.com/threefoldtech/js-sdk/issues/2123

## For ZDBs
we never stated anything about SSD or HDD, and it's also the same thing. we start with 6+4  = 100 GB zdbs, and scale up based on the usage

**Comment by weynandkuijpers** [comment]
okay - can we then put a link/text in the VDC overview age for this.  I like it and I expected (for storage specifically) it but we need to make people aware.

**Comment by waleedhammam** [comment]
verified

**Comment by MElborolossy** [comment]
Working on it to add a message for the user

**Comment by weynandkuijpers** [comment]
Verified.
