### ISSUE TITLE
moving 3bot to Farm with not enough capacity creates capacity pool and deployment fails

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2529]
### Description

I understand that the underlying commercial engine is changing, therefore this will not be fixed in release 2.4 / 2.5 but I do want to record the issue for testing purposes for release 3.0

Selecting a new farm to move the 3bot too that does not have sufficient capacity leads to an error (not captured) but it does accept payment and creates a capacity pool on this new (but failed) farm.

![og-farm-not-enough-capacity](https://user-images.githubusercontent.com/13766992/107915059-1d69cc00-6f7d-11eb-9eb2-0a29a98e0b0e.png)

**Comment by weynandkuijpers** [comment]
3bot ID: weynandkuijpers.3bot
js-ngg version 11.0b12
js-sdk version: 11.0b14

**Comment by waleedhammam** [comment]
@weynandkuijpers which farm that doesn't have the capacity ?

**Comment by weynandkuijpers** [comment]
ogfarm - kuwait.

**Comment by waleedhammam** [comment]
I couldn't reproduce 

- Deployed 3bot
![image](https://user-images.githubusercontent.com/10658229/107951684-616ec800-6fa1-11eb-86f3-76e952436bc7.png)

- Farm capacity (has capacity already)

![Screenshot from 2021-02-15 15-21-48](https://user-images.githubusercontent.com/10658229/107951792-8a8f5880-6fa1-11eb-906d-fbefd41f1ce8.png)
![image](https://user-images.githubusercontent.com/10658229/107952037-e1952d80-6fa1-11eb-823a-8832afee524d.png)



- Also there are sanity checks in the code to not show the farms with capacity.


Please attach the error if it happens again, to see what it is about

**Comment by weynandkuijpers** [comment]
Issue no longer relevant
