### ISSUE TITLE
zdb stuck on reservation page

### ISSUE THREAD

**Issue by everhusk** [threefoldtech/js-sdk#253]
<img width="845" alt="Screenshot 2020-07-15 at 23 25 06" src="https://user-images.githubusercontent.com/4977840/87597635-6c533880-c6f2-11ea-8943-b96d6e1dab18.png">

Trying to deploy a minio solution to mainnet but gets stuck on the reserve page.

**Comment by xmonader** [comment]
It's almost 40 days ago, and we had too many successful deployments of minio, I'll move it out of grid and @zaibon feel free to close it or move it back if needed
