### ISSUE TITLE
Deploying Kubernetes stops without explanation when capacity pool are not properly funded

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2532]
A time of deployment I have a small number of capacity pools all with CU only.  Did not get any SU capacity in any of the pools.

When I got to deploy a kubernetes cluster and arrived at the pool selection screen, none of the pool was available to choose from.  Two issues with this:
- every CU comes with 50GB of free capacity (https://wiki.threefold.io/#/cloud_units) and I am not sure this was taken into account
- there was no error - it just showed me an empty pool selection box

I think it is okay to not deploy if there is not sufficient SU ( or CU) left in the capacity pool (or any of the available capacity pools) but there has to be a message that explains this.  In this case there was no message - I had to think of it and when I funded one of my capacity pool with SU's I could continue and deploy.

**Comment by weynandkuijpers** [comment]
As we do know what we need (resources) to deploy the kubernetes cluster maybe we should specify that / those numbers at capacity selection chat window.

**Comment by m-motawea** [comment]
> every CU comes with 50GB of free capacity
this is not True. every container is given free disk space up to 50 GB. and that is for containers only not k8s.

**Comment by weynandkuijpers** [comment]
> > every CU comes with 50GB of free capacity
> 
> this is not True. every container is given free disk space up to 50 GB. and that is for containers only not k8s.

At risk of trying to outsmart you @m-motawea (;-)) every CU comes with 2vCores, 4GB of RAM and 50GB of storage - k8s also consume CU's....  Just like containers.  Anyway - mute point - pint is that when not enough CU's are available you should not be able to go forward in the deployment process.

**Comment by weynandkuijpers** [comment]
Issue no longer relevant
