### ISSUE TITLE
QA: Test Blockchain Digibyte Deployment

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#2534]
- [x] test the deployment on evdc
- [ ] report your test on testlodge
- [ ] discuss with weynand about deployment performance (good enough, bugs)
- [ ] create bugs if any
- [ ] after stable enough , get on call with digibyte (weynand-(abdul)-benje). 
- [ ] create strategy for blockchain tester promotion (digibyte first).

**Comment by weynandkuijpers** [comment]
Benje has access to the testlodge - and created the main categories for the test suite and requiremnents.
