### ISSUE TITLE
Failed to install CRD crds/traefik.yaml

### ISSUE THREAD

**Issue by MElborolossy** [threefoldtech/js-sdk#2538]
### Description

Deployment failed to install CRD crds/traefik.yaml, this happen with Wiki, Blog, Website, Kubeapps and Monitoring Stack.

### Steps to reproduce

- Deploy VDC
- Deploy one of [ Wiki - Blog - Website - Kubeapps - Monitoring Stack ]
- Deployment will fail

### Traceback/Logs/Alerts
```
2021-02-15 14:33:37.350 | ERROR    | jumpscale.sals.chatflows.chatflows:wrapper:173 - error when executing step install_chart. exception: Failed to deploy chart marketplace/publishingtools, error was WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: ~/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: ~/.kube/config
Error: failed to install CRD crds/traefik.yaml: error parsing : error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.threefoldVdc.backup":interface {}(nil)}
```

**Comment by AhmedHanafy725** [comment]
To unblock the chart deployment, crds in these charts have hardcoded backup value until we find another solution to pass it from the values file

**Comment by MElborolossy** [comment]
Wiki - Blog - Website - Kubeapps verifed
Monitoring Stack failed with the following traceback
```
jumpscale.core.exceptions.exceptions.Runtime: Failed to deploy chart marketplace/monitoringstack, error was WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/mohammed/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/mohammed/.kube/config
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in PodSecurityPolicy.metadata.labels.backupType
```

**Comment by MElborolossy** [comment]
Verified for all charts
- Wiki - Blog - Website - Kubeapps
![image](https://user-images.githubusercontent.com/11272864/108061292-c2a9a080-7060-11eb-98c1-3fa5a9a243e7.png)
- Monitoring Stack
![image](https://user-images.githubusercontent.com/11272864/108061350-d5bc7080-7060-11eb-9c82-a58727481011.png)
