### ISSUE TITLE
VDC: Error when extending the kubernetes cluster, lost payment

### ISSUE THREAD

**Issue by BenjellounO** [threefoldtech/js-sdk#2541]
I received this error message when trying to extend the k8s cluster on the vdc,  after the payment and the transaction has not been reverted ( lost payment) 
any ideas on how to solve this?  

![image](https://user-images.githubusercontent.com/51067842/107976037-626c1d80-6fd2-11eb-995b-8177e59c1e7e.png)

**Comment by waleedhammam** [comment]
@BenjellounO Can you add more information ? where did you deploy that, vdc name, the workloads ids, is the vdc in grace period or not ?

**Comment by waleedhammam** [comment]
Well, seems it's same as https://github.com/threefoldtech/js-sdk/issues/2542, vdc entered grace period

**Comment by hossnys** [comment]
verified 
extended the cluster successfully as the vdc still away of the grace period 
![Screenshot from 2021-02-24 10-52-19](https://user-images.githubusercontent.com/26298009/108979283-2a7c6e80-7693-11eb-8b1e-95dff8a967fe.png)
![Screenshot from 2021-02-24 11-24-06](https://user-images.githubusercontent.com/26298009/108979288-2c463200-7693-11eb-8f38-ba632c208cd2.png)
