### ISSUE TITLE
VDC unreachable by kubectl, won't deploy marketplace solutions

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/js-sdk#2542]
I deployed a VDC on testnet on February 8th. Today during testing, I noticed that I can no longer reach it via kubectl, which returns:
`Unable to connect to the server: dial tcp 185.69.167.185:6443: i/o timeout`

I am also unable to deploy marketplace solutions on this VDC any longer (it did work at some point). Marketplace deployments fail with alert id 2.

I am able to add and remove worker nodes on this VDC.

Here is the full info on the master node:
```
pub ip: 185.69.167.185
ip: 10.200.2.2
wid: 5736
node id: DJoL9ZV53K5YQurmxor2BLWTPf3WA9dT3RsFWeDeAx1z
pool id: 2141
size: 15
```

**Comment by waleedhammam** [comment]
That's because the vdc entered the grace period, warning message will be updated to be more clear

**Comment by scottyeager** [comment]
Okay, I now see a warning about the grace period. However, even after funding the VDC's wallet, the warning remains and I'm still unable to access via kubectl.

**Comment by waleedhammam** [comment]
@scottyeager can you add the vdc name & where it's deployed ?

**Comment by scottyeager** [comment]
Yes, the VDC is named "scott-kubie" and the master node is on TF node DJoL9ZV53K5YQurmxor2BLWTPf3WA9dT3RsFWeDeAx1z. I added 10 TFT to the wallet, which is being consumed as seen on the [Stellar explorer](https://stellar.expert/explorer/public/account/GCWBJXPCWPBRRSIMMFL5E4A2GCNW54RJT74AV3CKTLTT3GDXZUCMFY3X).

**Comment by xmonader** [comment]
@m-motawea correct me if I'm wrong, but 10 TFT aren't enough to get out of grace period, probably would have been better if we tell the user they need to pay HALF of what is in their user plan because that what we did to keep their workloads alive for 2 more weeks?

**Comment by waleedhammam** [comment]
@scottyeager 10 TFT is not enough to get of grace period but enough to keep the workloads live, the VDC needs to be funded with  the plan's price which is 15 in silver added clear message

![Screenshot from 2021-02-25 18-02-25](https://user-images.githubusercontent.com/10658229/109180636-becdfa80-7793-11eb-9e4b-6ded9edea463.png)

**Comment by scottyeager** [comment]
Okay, that makes sense. I thought that 10 would be enough for another week or two, especially considering that this VDC no longer has a worker node.

I've tried funding with another 15 TFT, then an additional 5 after that. Still no response from kubectl.

**Comment by waleedhammam** [comment]
After investigation, the vdc has gone out of grace period
![Screenshot from 2021-02-28 10-52-16](https://user-images.githubusercontent.com/10658229/109412864-19916d00-79b3-11eb-8dfc-e92e8d59ffac.png)

Yet I can't reach the public IP
```
(js-sdk-vpmH-Z_5-py3.8) root@vdc-testnet:~/js-sdk# ping 185.69.167.185
PING 185.69.167.185 (185.69.167.185) 56(84) bytes of data.
^C
--- 185.69.167.185 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1017ms
```

Kubernetes workloads: https://explorer.testnet.grid.tf/api/v1/reservations/workloads/5736
Pool already has ipv4 units: https://explorer.testnet.grid.tf/api/v1/reservations/pools/2141

This issue should be moved to ZOS repo for further investigation

**Comment by waleedhammam** [comment]
to be continued in https://github.com/threefoldtech/zos/issues/1202
