### ISSUE TITLE
error when adding a new vdc

### ISSUE THREAD

**Issue by BenjellounO** [threefoldtech/js-sdk#2545]
I receive this error when deploying a new VDC.  The same error happens with every package (either silver or gold etc..)

![image](https://user-images.githubusercontent.com/51067842/108043472-9559f400-705a-11eb-81f6-5b69c6001e04.png)

3bot name: benjelloun.3bot
VDC name: myevdc

**Comment by BenjellounO** [comment]
i reckon it is a wallet issue, when trying again, I receive this 

![image](https://user-images.githubusercontent.com/51067842/108046137-ba9c3180-705d-11eb-95af-2ad8361abc7e.png)

**Comment by xmonader** [comment]
@mhost39 why isn't the activation wallet not reporting the the grid monitoring?

**Comment by sasha-astiadi** [comment]
<img width="1129" alt="Screenshot 2021-02-19 at 11 15 25" src="https://user-images.githubusercontent.com/43240801/108491177-dc86f580-72a3-11eb-8716-81edd7f936d2.png">

**Comment by sasha-astiadi** [comment]
@robvanmieghem  can you please topup your activation service

**Comment by xmonader** [comment]
@sasha-astiadi weynand just deployed a new one will close this, but still definitely don't like how the flow is with the activation service atm

**Comment by robvanmieghem** [comment]
I assume we just drain the accounts by testing and they the newly created accounts are not cleaned up properly

**Comment by sasha-astiadi** [comment]
i no longer have this issue but I need @BenjellounO to verify

**Comment by BenjellounO** [comment]
The error no longer persists for me, I had to use another browser or the private window to be able to deploy a new VDC.  ( I'm still having the issue when using the normal window but probably because of a cache issue, but all good on other browsers/windows.)
