### ISSUE TITLE
Hosted 3BOT Deployer has no default packages listed

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/js-sdk#2547]
I recently deployed a new 3BOT with https://deploy3bot.testnet.grid.tf/  and i am unable to see the default packages listed under the Packages page like farm , marketplace etc : 

![image](https://user-images.githubusercontent.com/25789724/108049468-bc67f400-7061-11eb-87f3-f89af7937e1e.png)

In the console i see this : 

![image](https://user-images.githubusercontent.com/25789724/108049533-d275b480-7061-11eb-9cb4-f70c1087e1be.png)

**Comment by waleedhammam** [comment]
@siddiquagig I just deployed one and worked without problems
![image](https://user-images.githubusercontent.com/10658229/108051004-05fd1280-7053-11eb-84b4-1bf00af8d14f.png)

Can you state any steps you made, and show the request information/response ?

**Comment by siddiquagig** [comment]
Thanks @waleedhammam, worked now after ```git clean -xfd``` and restarting server

**Comment by waleedhammam** [comment]
Verified locally too
![Screenshot from 2021-02-16 12-53-04](https://user-images.githubusercontent.com/10658229/108060906-38613c80-7060-11eb-8219-47a4db10dab8.png)
