### ISSUE TITLE
VDC: Wallet creation issue on latest vdc_development js-sdk build

### ISSUE THREAD

**Issue by archit3kt** [threefoldtech/js-sdk#2549]
This issue is following my tests from #2303 

I'm running latest vdc_development js-sdk on fresh dedicated ubuntu 20.04

Wallet creation fails with the following error :

![image](https://user-images.githubusercontent.com/32200831/108051403-25903d00-704b-11eb-89f2-a0612646364f.png)

js-sdk logs :

https://pastebin.com/y2benpNL

This error relates to the VDC creation issue I will post afterwards

**Comment by xmonader** [comment]
The activation can happen in one of two ways

1- using the threefold activation service 
2- providing `activation_wallet` on your system that has enough XLMs to be able to activate the wallets on stellar network and adding trustlines. 

We handle that flow in our systems by providing the `activation_wallet` as a backup in case the activation service was down for any reason.

In your logs I see the failure coming from threefold activation service. @robvanmieghem any ideas?

**Comment by robvanmieghem** [comment]
The wallet is indeed underfunded since it is sponsoring the xlm stays on the account and it's not immediastely obvious.

**Comment by robvanmieghem** [comment]
I topped it up but the monitoring script should take the sponsered reserves into account

**Comment by MElborolossy** [comment]
Verified
As @xmonader explain the activation ways and wallet topped up
