### ISSUE TITLE
VDC creation issue on latest vdc_development js-sdk build

### ISSUE THREAD

**Issue by archit3kt** [threefoldtech/js-sdk#2550]
This issue is following my tests from #2303

I'm running latest vdc_development js-sdk on fresh dedicated ubuntu 20.04

vdc creation fails with the following error :

![image](https://user-images.githubusercontent.com/32200831/108054694-4490ce00-704f-11eb-806e-a5d63d70509c.png)

js-sdk logs :

https://pastebin.com/CDSDpvbb

We can see the vdc_init wallet is not correctly created :

![image](https://user-images.githubusercontent.com/32200831/108054855-7e61d480-704f-11eb-98ae-6983ce205b3d.png)

This error probably relates to the wallet creation issue I posted earlier : #2549

**Comment by xmonader** [comment]
Hi! can you tell me what exactly are you trying to do? do you plan to host the VDC on-premise? we don't have any documentation regarding that. The current testing phase is around the VDC functionality https://vdc.testnet.grid.tf

**Comment by archit3kt** [comment]
Hi @xmonader yes my idea is to host it on premise, I will soon add my node to the main network. I'd like most of my infra to run on it.

So for now I wanted to see how it works on testnet, especially the deployment phase, waiting for VDC to come in mainnet in the next release. I believed I could do that right now by selecting some testnet nodes during the workflow, but I'm stuck at the first phrase of the workflow. If I understood correctly from #2549 , funding the wallet from threefold activation service will allow the creation if vdc_init ?

**Comment by xmonader** [comment]
Right now, our main focus is helping people to test the technology on our hosted platform, not on-premise. 

With activation service topped up again, it'd be able to sponsor new wallets creations indeed.
