### ISSUE TITLE
VDC: dashboard tell the user if there's an upgrade

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2557]
should see if we are to update based on commits on based on tags?

**Comment by MElborolossy** [comment]
Verified
Commit: d0eea8f1482459bd507ba0bfcca889be09023f6a
![Update_Notifications](https://user-images.githubusercontent.com/11272864/108862055-8d6cf780-75f8-11eb-8923-373c1b822f3d.png)

**Comment by hossnys** [comment]
it should check on new release tag not on every new commit as this may cause that a fix's commit which is not tested well to be on user side directly after update , which may cause something to stop working on user side , so IMHO the update message should appear after every new release when there is a new tag .

**Comment by weynandkuijpers** [comment]
Please verify and close or push back to in progress

**Comment by MElborolossy** [comment]
Verified
- Create a new tag on the repo locally
- Go to VDC Dashboard
- Dialog appears for update
![image](https://user-images.githubusercontent.com/11272864/111165628-f0263300-85a7-11eb-8e57-f0b0445cc223.png)
