### ISSUE TITLE
Add check for activation service wallet before deploying vdc

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#2560]
### Description

- Activation service wallet has reserved balance for the sponsored accounts
- Need to check the wallet balance before deploying to make sure it has enough XLMS for activating more wallets

**Comment by waleedhammam** [comment]
needs: https://github.com/threefoldtech/js-sdk/issues/2561

**Comment by xmonader** [comment]
Not needed anymore, we now ignore the activation service completely for VDCs and use activation wallets only.
