### ISSUE TITLE
Console error in open creating pool chatflow

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/js-sdk#2563]
### Description

![image](https://user-images.githubusercontent.com/36021484/108206771-87c26e00-712f-11eb-9505-df86dc7f4f4d.png)

### Version information

* OS: e.g. Ubuntu 20
* Project commit/version: e.g. JS-SDK: 11.0b13
* Browser: e.g. vivaldi

### Steps to reproduce

- Open the admin dashboard
- Open new chatflow

**Comment by xmonader** [comment]
Please make sure all your reports against chrome browser, and the other thing does it affect any functionality? It might be thrown from the underlying vueitfy?

**Comment by dmahmouali** [comment]
Can't reproduce via chrome browser, so I will close.
![image](https://user-images.githubusercontent.com/36021484/108697572-b4013480-750b-11eb-9acb-f648473addcd.png)
