### ISSUE TITLE
Create UI widget and chatflow for Presearch (blockchain)

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#2566]
replacing issue https://github.com/threefoldtech/js-sdk/issues/2209

will create 1 issue per blockchain node widget from now on.
digibyte was completed, we create presearch for 2.5

start when  helm chart is completed.
link to the helm chart issue for presearch:
https://github.com/threefoldtech/vdc-solutions-charts/issues/78

**Comment by abdulgig** [comment]
Adding widgets is part of the chatflow so we can close this as this already under verification under the ticket https://github.com/threefoldtech/vdc-solutions-charts/issues/78

@BenjellounO will test with the community
