### ISSUE TITLE
3BOT: Why do I see every time I action something from the 3bot deployer page (new, start, move) I get "checking payment service"

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2567]
Each time I action something with a 3bot from the 3bot deployer page the first screen I see is "Checking payment service".  I understand we need "check" the payment service but I do not see why we need to present this information to the end user.  He has not done anything yet and we're already considering having to charge him.

Sounds greedy... :-) !  Let's to the check but write something like:

- [ ] "Waking up all 3bots and making sure they pay attention...."
- [ ] "Calling all 3bots required to help you...."
- [ ] "It will take a few seconds to be ready to help you ..."
- [ ] "Let's get ready to do this for you"
- [ ] ......

**Comment by waleedhammam** [comment]
Sounds OK

will take `It will take a few seconds to be ready to help you ...` as this check happens in all chatflows to be generic

**Comment by weynandkuijpers** [comment]
Beautiful
