### ISSUE TITLE
Moving a 3bot to a smaller node results in same resource error adter downsizing the 3bot 

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2569]
identtity:  weynandkuijpers.bot
3bot name: cometjetser
original size: gold
new size: silver (2GB of memory)
![screenshot_20210218_080051](https://user-images.githubusercontent.com/13766992/108303500-75901080-71bf-11eb-8bc1-e48122b55962.png)

old farm: freefarm
new farm OGfarm
available size on of Farm (3GB and plenty of cores)
![screenshot_20210218_075903](https://user-images.githubusercontent.com/13766992/108303346-306bde80-71bf-11eb-9927-762dd8540b3f.png)
![screenshot_20210218_080000](https://user-images.githubusercontent.com/13766992/108303417-52656100-71bf-11eb-89b4-f5b816a33f53.png)

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/108585980-5aa2d500-7354-11eb-8bb1-cf87a8619501.png)

https://github.com/threefoldtech/js-sdk/blob/73fd5da200a465443f3d6fc21b8fdd38ee1fa5dc/jumpscale/sals/reservation_chatflow/reservation_chatflow.py#L1422-L1426

there're multiple checks happening on resources then filtering out based on the ip version and then filtering out the nodes we failed to deploy on recently

**Comment by weynandkuijpers** [comment]
As we are moving towards a testnet build by multiple farms (small, medium and large) people will select farmers (and nodes) that might have limited capacity but still enough to deploy. Therefore this has to be rock solid and working well.  I understand that there are multiple things to check and which determine the suitability of a node for deployment but we need to keep in mind that people will want to select their own, small node for testing purposes.

**Comment by waleedhammam** [comment]
The problem is that `ogfarm` once has a `public ipv4 config`, now that node was removed, so we can't choose this pool anymore  for deployment

![image](https://user-images.githubusercontent.com/10658229/108823106-ad84c280-75c8-11eb-8be9-da58f6052a88.png)

**Comment by weynandkuijpers** [comment]
Closing this issue as we cannot verify.  Might come back when we have multi-farm testnet setup but will manage through a new issue,
