### ISSUE TITLE
3BOT: custom prices documentation 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2577]
follow up of #2252

**Comment by xmonader** [comment]
docs added here https://github.com/threefoldfoundation/info_cloud/commit/f6d14ba6f05f0c295f1629948c80712f8211e3d0

**Comment by waleedhammam** [comment]
Docs are good enough here https://github.com/threefoldfoundation/info_cloud/blob/development/src/farming_tech/3bot_farm_custom_prices.md
