### ISSUE TITLE
Handling multiple users in vdc_dashboard

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#2580]
### Description

now we only allow the creator of the vdc to access the vdc dashboard. but in future it makes sense for multiple users to be able to manage the vdc from the dashboard similar to multiple threebot admins.
currently a user can be added from the backend to manage the package using 

``` python
JS-NG> from jumpscale.packages.auth.bottle.auth import add_package_user
JS-NG> add_package_user("vdc_dashboard", "uuser.3bot")
```

but when this is done, the vdc_dashboard becomes broken since it fetches the vdc info using the username in the session while there is only one vdc instance on that container.

**Comment by waleedhammam** [comment]
![Screenshot from 2021-03-31 16-44-53](https://user-images.githubusercontent.com/10658229/113163405-6f6e6480-9240-11eb-848a-2abe557b66c4.png)

works ok
