### ISSUE TITLE
VDC: discourse to support threefold connect

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2583]
- [ ] discourse https://github.com/threefoldtech/tf-discourse/issues/1

**Comment by AhmedHanafy725** [comment]
**Branch:** development
**Commit:** c19232ed8b78a03fb1765664afdeb120e8b48f2d
**Verified**

![image](https://user-images.githubusercontent.com/41957921/111901916-6cef5c00-8a43-11eb-9699-4460f730f7f8.png)

![image](https://user-images.githubusercontent.com/41957921/111901918-6fea4c80-8a43-11eb-8f62-4e633223e693.png)

![image](https://user-images.githubusercontent.com/41957921/111901922-737dd380-8a43-11eb-909e-bed59a83267c.png)
