### ISSUE TITLE
Capacity Pools view in admin dashboard is too big

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/js-sdk#2588]
### Description

In admin dashboard ,the capacity pools' table view can be scrolled right and left, which can be not noticed and hence disregarding items on the far right.

Current state:
![Screenshot from 2021-02-21 12-59-13](https://user-images.githubusercontent.com/17128393/108623240-99b15300-7446-11eb-9680-fcff75baa76f.png)

**Suggestion 1** : Decrease the width of the table headers to have long items on multiple lies as shown in the image below and hence everything fits in the default display without the need to scroll
Suggested edit:
![Screenshot from 2021-02-21 13-07-13](https://user-images.githubusercontent.com/17128393/108623244-9fa73400-7446-11eb-8f6a-e18d3871ccca.png)

**Suggestion 2** :  Remove some columns existing in the current pools details pop up (or move from table to pop up)
![Screenshot from 2021-02-21 13-27-45](https://user-images.githubusercontent.com/17128393/108623644-b2226d00-7448-11eb-8ac4-54472468e706.png)

### Installation method
Deployed 3bot on testnet

**Comment by AhmedSa-mir** [comment]
Suggestion 1 is fine :+1:

**Comment by weynandkuijpers** [comment]
Smaller view for the capacity pools:
![screenshot_20210315_143209](https://user-images.githubusercontent.com/13766992/111140218-86079100-859b-11eb-9d19-e881e5a7e375.png)

Issue done.
