### ISSUE TITLE
activation_wallet drained.  Not able to deploy new VDC's

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2590]
I have had this now a few times - were the activation wallet is drained and no new deployments are possible.  We need to do one of two things:
- find a way to monitor this and make sure it stays funded
- automatic top-up (with escalation to 24*7 support) to make sure this facility stays online.

We cannot go out and all people to test while we cannot provide them with a working deployment mechanism. WE have people in a lot of different time zones.

![screenshot_20210222_083933](https://user-images.githubusercontent.com/13766992/108663279-a044d680-74e9-11eb-8b5d-284be51e343f.png)

**Comment by xmonader** [comment]
I agree, but that's not the root cause. This wallet `activation_wallet` is the backup option if the activation service is down, and that service is down for a long time making the backup option always in place and getting drained.

**Comment by weynandkuijpers** [comment]
Okay - thank you for explaining this.  I Guess the backup wallet is funded.  Can deploy VDC again.,
