### ISSUE TITLE
Check that pod starting not working as expected

### ISSUE THREAD

**Issue by MElborolossy** [threefoldtech/js-sdk#2592]
### Description

Check that pod starting in the deployment process is not working as expected, it checks the status not _Pending_, but sometimes it is running but still **not ready**.
https://github.com/threefoldtech/js-sdk/blob/9c0c560b16761920d5657ecae0601cd7a18a202f/jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py#L417

**Comment by waleedhammam** [comment]
tested with mattermost worked ok
![image](https://user-images.githubusercontent.com/10658229/109003127-b8665280-76af-11eb-8f44-c89647136fdf.png)
