### ISSUE TITLE
Can not deploy 3bot on dev net ( no available farms with enough resources

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/js-sdk#2595]
### Description

deploying 3bot on devnet failed due to no available farms with enough resources
### Installation method
using https://deploy3bot.devnet.grid.tf/
### Steps to reproduce

try deploying a new 3bot and go over with the chatflow and choose silver flavor 
### Traceback/Logs/Alerts

![Screenshot from 2021-02-22 11-28-42](https://user-images.githubusercontent.com/1689456/108689434-bbbbdb80-7501-11eb-9721-954a30b6a2fe.png)

**Comment by waleedhammam** [comment]
Checking nodes: 
![Screenshot from 2021-02-22 11-36-17](https://user-images.githubusercontent.com/10658229/108689802-35ec6000-7502-11eb-8989-e58f6bcc7dce.png)

devnet doesn't have a node with pub ipv4

requires:

**Comment by waleedhammam** [comment]
blocked on: https://github.com/threefoldtech/zos/issues/1195

**Comment by sasha-astiadi** [comment]
you shouldnt run test from devnet. we specifically said on zos that devnet is unstable.
on #1195 the node is up but @delandtj will need to replace it. will close .
