### ISSUE TITLE
Deployment of Presearch node done but gives CrashLoopBackOff event

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2606]
I deployed a Presearch node using the widget. 

In my dashboard I see an 'error': 
![image](https://user-images.githubusercontent.com/30384423/108735052-5f23e500-7530-11eb-96c8-4141ac8429d8.png)

Detail in Lens gives a CrashLoopBackOff event. 

![image](https://user-images.githubusercontent.com/30384423/108735163-7bc01d00-7530-11eb-88bf-6586ad1532e3.png)

**Comment by abdulgig** [comment]
There was an issue with the underlying image that has been resolved. Could you please redeploy and test ?

We have tested and it is working fine

**Comment by gmachtel** [comment]
New Presearch deployment worked fine!
However, we need to find the root cause for this error, as the container will update regularly and a too old version won't run anymore (which is what happened). Expected to have rolling update activated in Kubernetes.

**Comment by xmonader** [comment]
@gmachtel I'll move it to 2.6 at least, no one has presearch nodes anyhow on the system

**Comment by gmachtel** [comment]
I agree, Docker has been renewed and now works anyway. 

But before making publicity to the Presearch community, I’d like this to be resolved, as the Presearch team intends to make regular updates to their workloads. As it’s one of the first things to go out with, needs then to be solved in 2.6.

**Comment by gmachtel** [comment]
The original issue is solved (crashloopbackoff event with deployment of a new solution). 
Keeping the image aligned with latest version is another 'feature' that I will open a separate issue for.
