### ISSUE TITLE
VDC: backup and restore using external etcd

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2615]
requires #2553 
- [x] backup
- [ ] restore

**Comment by AhmedHanafy725** [comment]
After restoring the cluster from external etcd, the cluster controller becomes corrupted.
The cluster still sees the old cluster's nodes, and the new controller (the first node in the following image) is not a master.
![image](https://user-images.githubusercontent.com/41957921/109004843-f19fc200-76b1-11eb-970b-7799e791d7db.png)

**Comment by xmonader** [comment]
@despiegk @robvanmieghem @delandtj we need input here to proceed with external etcd suggestion

**Comment by sasha-astiadi** [comment]
@xmonader can we move it back to in progress since we decided to use velero

**Comment by xmonader** [comment]
not needed anymore
