### ISSUE TITLE
Deployment of ETCD in eVDC leads to 'alert 238'

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2622]
I try to deploy a ETCD instance in my eVDC, but I get an 'alert 238'. 
Unclear what it means (user-unfriendly), and deployment failed. 

![image](https://user-images.githubusercontent.com/30384423/108993514-fdcc5500-769a-11eb-9827-d4ad79a549cd.png)

**Comment by xmonader** [comment]
can you make sure your dashboard is updated?and please attach vdc information as well.

**Comment by waleedhammam** [comment]
@gmachtel can you confirm working after update ?
I've tested it and working for me 
![Screenshot from 2021-02-24 15-48-31](https://user-images.githubusercontent.com/10658229/109009867-c3bd7c00-76b7-11eb-8c49-fbaa9bc65daf.png)

**Comment by gmachtel** [comment]
Yes, works now. Thanks !
