### ISSUE TITLE
Add an endpoint in the vdc package to redirect the user to direct him towards a specific solution

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/js-sdk#2623]
### Description

- If the user is not authenticated redirect him to the login page
- Otherwise, if he doesn't have a deployed VDC redirect him to "Create new VDC chatflow"
- If he has at least one deployed VDC, redirect him to the solution page where he can create a new solution

**Comment by xmonader** [comment]
tried these two scenarios
- not logged in in the vdc.devnet.grid.tf and going to `https://vdc.devnet.grid.tf/vdc/api/vdc_refer/peertube` I got redirect to my vdc on peertube chat (y) 
- logged on the vdc.devnet.grid.tf I got prompted to threefoldconnect login and afterwards I got redirect to myvdc login page and after that I got into the peertube deployment chat.

**Comment by MElborolossy** [comment]
verifying

**Comment by sasha-astiadi** [comment]
@xmonader

**Comment by sasha-astiadi** [comment]
when on testnet? https://vdc.devnet.grid.tf/vdc/api/vdc_refer/peertube
