### ISSUE TITLE
Creating a deal for a 3bot in farmmanagement causes an error if user is not existed

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#2624]
### Description

- Adding a deal for a wrong user should raise a message not an error

![Screenshot from 2021-02-24 14-58-57](https://user-images.githubusercontent.com/10658229/109004126-02036d00-76b1-11eb-8ed9-c4933369d9a1.png)

**Comment by Pishoy** [comment]
- i have installed by jsng threebot server with 3bot name `bishoy2.3bot`
- install frammanagment package

### first bug 

1. go to `SET FARM PRICES`  tab , then I set the is to 10 8 6  as shown on below picture 
2. issue: got empty rows with edit and delete options , I can not do any of them ( edit or delete) using firefox 
![image](https://user-images.githubusercontent.com/21987477/109818271-7d2dcb80-7c3b-11eb-8940-0c17d6efdcd2.png)

### second bug 
1. go to `ADD A DEAL` tab, when try to set a deal to bishoy.3bot account got below error 
![image](https://user-images.githubusercontent.com/21987477/109818292-8323ac80-7c3b-11eb-82ed-6fe497c0a4be.png)

- code
```
root@testing:~/js-sdk# git log -1
commit b4f36cfd9588c597f70bfee0f61d28881c8d3e8a (HEAD -> development, origin/development, origin/HEAD)
Merge: 187ec85a 42d0b061
Author: Abdul Rehman <a.rehmans@gmail.com>
Date:   Wed Mar 3 13:17:57 2021 +0400

    Merge pull request #2692 from threefoldtech/development_presearch_chart
    
    presearch node - lower chart limits
```

**Comment by Pishoy** [comment]
### Thrid bug 
1. go to farm settings 
2. press on + `IP Address management`
3. delete added IP address
4. got error as below picture 
![image](https://user-images.githubusercontent.com/21987477/109822375-8e78d700-7c3f-11eb-86f7-cc65aab17ea9.png)

### feature request 
to validated the walllet address on  adding a wallet address
steps:
1. go to farm settings 
2. add a new wallet, put the invalid address as below :
3. the wallet address added depiste validation 
![image](https://user-images.githubusercontent.com/21987477/109821392-9a17ce00-7c3e-11eb-9599-0de4015298d5.png)

**Comment by xmonader** [comment]
@Pishoy please make sure to test against testnet or devnet explorer, there're no custom prices available on mainnet.

**Comment by weynandkuijpers** [comment]
verified and closed
![screenshot_20210315_124311](https://user-images.githubusercontent.com/13766992/111126381-13db8000-858c-11eb-8b1f-76ca806db97a.png)
