### ISSUE TITLE
Taigo fails to deploy in new VDC on testnet

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2629]
New deployed VDC (this morning) and first application deployed result in error:
![screenshot_20210225_112654](https://user-images.githubusercontent.com/13766992/109118412-ba3a1f80-775c-11eb-9faf-e538c4226fb9.png)

VDC details:
![screenshot_20210225_112947](https://user-images.githubusercontent.com/13766992/109118463-caea9580-775c-11eb-8c4d-62899c6fadde.png)

3bot name of the owner: weyanndkuijpers.3bot

**Comment by weynandkuijpers** [comment]
![screenshot_20210225_113150](https://user-images.githubusercontent.com/13766992/109118683-10a75e00-775d-11eb-9b44-64085c75690a.png)

Taiga is deployed.... :-(  Don't get it....

**Comment by weynandkuijpers** [comment]
Is it the name ^^^ See namespace name  "taiga-taiganew".  I was allowed to enter a dash - is that causing issues?

**Comment by weynandkuijpers** [comment]
Second deployment try - same outcome - same error.

**Comment by xmonader** [comment]
It seems to be an SSL certificate problem, will add to the next milestone (taiga, and discourse should be disabled in 2.5)

**Comment by xmonader** [comment]
taiga will be revisited after the tf connect integration (it will be based on a fully new codebase)
