### ISSUE TITLE
VDC: backup/restore using velero

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2633]
- [x] Backup
- [x] Restore

**Comment by AhmedHanafy725** [comment]
restore resource using velero
![image](https://user-images.githubusercontent.com/41957921/109300386-1b3a2400-783f-11eb-8e32-8e856392407a.png)

restore domain names
![image](https://user-images.githubusercontent.com/41957921/109300398-1ffed800-783f-11eb-9575-45c68316db21.png)

**Comment by waleedhammam** [comment]
I am verifying this

**Comment by waleedhammam** [comment]
verification steps

- deploy vdc
- deploy cryptpad
- after an hour
- delete the vdc
- redeploy with the same name & password
- you'll find your cryptpad like you left it after 5 mins
