### ISSUE TITLE
Presearch deployment not using unique master node IPv4

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/js-sdk#2642]
Presearch nodes require a unique IPv4. When I deployed mine today, I got a duplicate IP error, indicating that there is another PS node using the same IP address. Since VDCs are assigned a unique IPv4, this should not be an issue. On inspection, I see that the pod is seen on a different external IP than the unique one assigned to the master node.

```
$ kubectl exec -n presearch-pre -it pre-presearch-c6df58b5b-j689h -- bash
# wget -qO- http://ipecho.net/plain | xargs echo
185.69.166.2
```

![image](https://user-images.githubusercontent.com/17682591/109220054-4eac7e00-776d-11eb-996a-69c1f98f54e5.png)

**Comment by abdulgig** [comment]
This has to be investigated at the VDC/networking layer. 

The pods in the VDC seem to have a different outgoing public IP rather than the one assigned to the VDC itself

**Comment by scottyeager** [comment]
It seems that egress routing is generally provided by cloud providers as part of their solution, or as part of Kubernetes addons like Istio, which is apparently using Envoy to accomplish this. Some other references:

https://github.com/steven-sheehy/kube-egress (routes all traffic from cluster)
https://github.com/nirmata/kube-static-egress-ip (allows per pod basis)

I'd say that per pod routing would be preferable to routing the whole VDC by default. These are special cases, for IP uniqueness in the case of Presearch or as a security measure in other cases, and routing all outbound traffic through the master node could have a performance cost when there's no reason for it.

Who might be able to help with adding egress routing to the VDC? This is an essential feature for our Presearch solution.

**Comment by scottyeager** [comment]
In the meantime, we could just run it on the master node as a workaround. I've had success with this today by first labeling my master node:

`kubectl label nodes name_of_your_node dedicated=master`

Then adding a node selector to the `values.yaml`:

```
nodeSelector: 
  dedicated: master

tolerations:
 - key: dedicated
   operator: Equal
   value: master
   effect: NoSchedule
```

While I understand that running pods on the master node is not generally recommended, I think it's okay in this case. The Presearch node is pretty lightweight and most users who are running it won't be placing high demand on their master node for managing worker jobs anyway. In fact, users who get a VDC solely for the purpose of running a Presearch node might want to remove their worker to reduce cost anyway.

**Comment by xmonader** [comment]
Hi @scottyeager thanks for the fine investigation. Indeed master isn't meant to be a target for any of the applications, but also the other suggestion requires changing lots of things of only one specific use case (presearch). I think there's a middle ground if the resources of the presearch charts become much lower.

**Comment by scottyeager** [comment]
Hey @xmonader, thanks for your input here. This should be fine, as the Presearch node is very lightweight at the moment. In the future, they'll be delegating more tasks to their nodes so being able to allocate more capacity on our end could become useful (but I guess they are planning a structure where nodes are assigned tasks according to their capacity, so there'll always be a place for lighter weight nodes).

I'm wondering if we can log egress routing somewhere as a low priority to keep in mind. Aside from this case, I understand that it's used to enforce security controls in general, when nodes from inside a cluster need to access some outside service where restriction based on inbound IP is desired. IPv4s are coming at a premium and at least a few of the corporate cloud providers offer this functionality, so I doubt this is the last time it will come up :wink:

**Comment by abdulgig** [comment]
@scottyeager , for now, the PR here https://github.com/threefoldtech/vdc-solutions-charts/pull/105 should resolve this issue.

The node with the master role is always selected to deploy the node

```
nodeSelector:
  node-role.kubernetes.io/master: "true"

tolerations:
 - key: node-role.kubernetes.io/master
   operator: Equal
   value: "true"
   effect: NoSchedule
```

**Comment by abdulgig** [comment]
@scottyeager and @gmachtel , the following has been verified from my end. Please proceed with the testing,

- [x] Restart button for auto upgrade https://github.com/threefoldtech/js-sdk/issues/2626
- [x] Node identity is preserved
- [x] The node gets deployed on the master node, thus advertising the correct public IPv4
- [x] Show node version on the status page

**Comment by weynandkuijpers** [comment]
@scottyeager and @gmachtel Please verify and close

**Comment by gmachtel** [comment]
Is OK, works.
