### ISSUE TITLE
as a user I'd like to be able to trigger backup at any point from my dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2646]
Right now we do scheduled backups (every 24h), but as a user I might want to force a backup at any specific moment

- [x] list backups
- [x] create backup
- [x] restore
- [x] delete

**Comment by AhmedHanafy725** [comment]
```bash
velero backup create XYZ --selector backupType=vdc
```

**Comment by weynandkuijpers** [comment]
create backup my asking to create one now.
![screenshot_20210315_132754](https://user-images.githubusercontent.com/13766992/111131993-44beb380-8592-11eb-995b-5fc782396fad.png)

Restored a state before deploying a Taiga deployment.  After restoring the Taiga deployment is still in place?  If this expected / correct.  If so - how do I test a restore to a previous state of a VDC?
![Uploading screenshot_20210315_140700.png…]()

**Comment by AhmedHanafy725** [comment]
This is not a snapshot that can restore the cluster state, it is restoring the apps that were deployed and currently deleted.

**Comment by AhmedHanafy725** [comment]
This already verified on https://github.com/threefoldtech/js-sdk/issues/2769
