### ISSUE TITLE
VDC: external etcd used for kubernetes disk quota exceeded

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#2649]
After deploying vdc suddenly kubernetes api become unreachable.

### Reason
![image](https://user-images.githubusercontent.com/41957921/109412878-3463e180-79b3-11eb-962d-7a7067edb4e6.png)

**Comment by weynandkuijpers** [comment]
Please verify and close

**Comment by waleedhammam** [comment]
External etcd is not deployed anymore
