### ISSUE TITLE
can't delete a worker from VDC dashboard

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/js-sdk#2652]
### Description
![Screenshot from 2021-02-28 11-42-40](https://user-images.githubusercontent.com/42457449/109414169-24033500-79ba-11eb-8b23-11eb81f534eb.png)

pressing Confirm does nothing in the UI, and gives Server Error in the browser dev console as shown in the screenshot.

### Traceback/Logs/Alerts

Traceback/Logs/Alerts if available

**Comment by MElborolossy** [comment]
Is this issue still happen? I try to delete a node on testnet and works fine

**Comment by sameh-farouk** [comment]
I can't reproduce the issue on fresh VDC, the VDC with this issue was outdated,
