### ISSUE TITLE
failed to deploy VDC on testnet

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/js-sdk#2653]
### Description

when trying to deploy a VDC from https://vdc.testnet.grid.tf/vdc/ it failed with this message

![Screenshot from 2021-02-28 11-48-05](https://user-images.githubusercontent.com/42457449/109414289-dd620a80-79ba-11eb-80c5-f0499e338db2.png)

**Comment by xmonader** [comment]
It was a signature issue, fixed on testnet already.
