### ISSUE TITLE
after deleting a deployed solution the page needs to update automatically

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/js-sdk#2656]
### Description

after deleting a deployed solution (from the VDC dashboard -> deployed solution page) the page not refreshed automatically to reflect the changes that just happened to the deployed solutions list. the changes show after the user refreshes the page manually.

### Implementation

the page needs to update the list automatically after the solution deleted successfully, a good example is to replicate the behavior when the user deletes a VDC, the page refreshes automatically.

**Comment by MElborolossy** [comment]
Close this issue as it is been verified before, update dashboard was needed to reflect the fix.
