### ISSUE TITLE
Couldn't deploy Cryptpad in my VDC

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#2661]
### Description

tried to deploy `Cryptpad` but I couldn't 

![image](https://user-images.githubusercontent.com/46320202/109417396-325a4c80-79cc-11eb-9c61-9d2cfee4614f.png)
![image](https://user-images.githubusercontent.com/46320202/109417441-65044500-79cc-11eb-8b7a-d162101f6061.png)
![image](https://user-images.githubusercontent.com/46320202/109417398-3a19f100-79cc-11eb-8144-f13f7e0b4e0b.png)

**Comment by dmahmouali** [comment]
please can u verify now?
@RafyAmgadBenjamin  
![image](https://user-images.githubusercontent.com/36021484/109419011-e1e6ed00-79d3-11eb-9b75-c6eb13910cba.png)

**Comment by MElborolossy** [comment]
Verified on testnet
![image](https://user-images.githubusercontent.com/11272864/109419550-b0bbec00-79d6-11eb-9083-9f41d4ad0a86.png)
