### ISSUE TITLE
can't update my VDC from UI

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/js-sdk#2668]
### Description

attempting to update my VDC dashboard would cause different errors on the console, with no indication in the UI if the process was succeeded or failed.

### Steps to reproduce

on my VDC dashboard, when I click on UPDATE  DASHBOARD from the user dropdown menu.

### Traceback/Logs/Alerts

isAxiosError.js:10 GET https://samehabouelsaad-test282.vdcdev.grid.tf/vdc_dashboard/api/update net::ERR_CERT_AUTHORITY_INVALID
(anonymous) @ isAxiosError.js:10
e.exports @ isAxiosError.js:10
e.exports @ isAxiosError.js:10
Promise.then (async)
r.request @ isAxiosError.js:10
(anonymous) @ isAxiosError.js:10
update @ api.js:97
updateDashboard @ VM154:27
click @ VM168:3
invokeWithErrorHandling @ vue:1863
invoker @ vue:2188
invokeWithErrorHandling @ vue:1863
Vue.$emit @ vue:3889
click @ vuetify@2.3:2484
invokeWithErrorHandling @ vue:1863
invoker @ vue:2188
original._wrapper @ vue:7547
isAxiosError.js:10 Uncaught (in promise) Error: Network Error
    at e.exports (isAxiosError.js:10)
    at XMLHttpRequest.l.onerror (isAxiosError.js:10)

_______________________________________________________________________________

isAxiosError.js:10 GET https://samehabouelsaad-test282.vdcdev.grid.tf/vdc_dashboard/api/threebot_vdc net::ERR_EMPTY_RESPONSE
(anonymous) @ isAxiosError.js:10
e.exports @ isAxiosError.js:10
e.exports @ isAxiosError.js:10
Promise.then (async)
r.request @ isAxiosError.js:10
(anonymous) @ isAxiosError.js:10
getVdcInfo @ api.js:43
vdcInfo @ VM607:24
mounted @ VM607:45
invokeWithErrorHandling @ vue:1863
callHook @ vue:4220
insert @ vue:3146
invokeInsertHook @ vue:6341
patch @ vue:6558
Vue._update @ vue:3949
updateComponent @ vue:4067
get @ vue:4478
run @ vue:4553
flushSchedulerQueue @ vue:4311
(anonymous) @ vue:1989
flushCallbacks @ vue:1915
Promise.then (async)
timerFunc @ vue:1942
nextTick @ vue:1999
queueWatcher @ vue:4403
update @ vue:4543
notify @ vue:745
reactiveSetter @ vue:1070
(anonymous) @ vue-router.js:2995
(anonymous) @ vue-router.js:2994
updateRoute @ vue-router.js:2415
(anonymous) @ vue-router.js:2269
(anonymous) @ vue-router.js:2403
step @ vue-router.js:2007
step @ vue-router.js:2014
runQueue @ vue-router.js:2018
(anonymous) @ vue-router.js:2398
step @ vue-router.js:2007
(anonymous) @ vue-router.js:2011
(anonymous) @ vue-router.js:2385
(anonymous) @ vue-router.js:2133
(anonymous) @ vue-router.js:2209
Promise.then (async)
(anonymous) @ vue-router.js:2156
(anonymous) @ vue-router.js:2177
(anonymous) @ vue-router.js:2177
flatMapComponents @ vue-router.js:2176
(anonymous) @ vue-router.js:2112
iterator @ vue-router.js:2363
step @ vue-router.js:2010
step @ vue-router.js:2014
(anonymous) @ vue-router.js:2011
(anonymous) @ vue-router.js:2385
(anonymous) @ index.js:93
async function (async)
(anonymous) @ index.js:77
iterator @ vue-router.js:2363
step @ vue-router.js:2010
runQueue @ vue-router.js:2018
confirmTransition @ vue-router.js:2393
transitionTo @ vue-router.js:2266
init @ vue-router.js:2986
beforeCreate @ vue-router.js:1304
invokeWithErrorHandling @ vue:1863
callHook @ vue:4220
Vue._init @ vue:4998
Vue @ vue:5078
(anonymous) @ index.js:98
isAxiosError.js:10 Uncaught (in promise) Error: Network Error
    at e.exports (isAxiosError.js:10)
    at XMLHttpRequest.l.onerror (isAxiosError.js:10)

________________________________________________________________________________

/vdc_dashboard/api/threebot_vdc:1 Failed to load resource: net::ERR_TIMED_OUT
isAxiosError.js:10 Uncaught (in promise) Error: timeout of 0ms exceeded
    at e.exports (isAxiosError.js:10)
    at XMLHttpRequest.l.ontimeout (isAxiosError.js:10)

**Comment by weynandkuijpers** [comment]
Please verify and when solved, close. Otherwise bump back to in progress.

**Comment by waleedhammam** [comment]
verified, with a new UI too
