### ISSUE TITLE
update dashboard button could be better

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/js-sdk#2669]
### Description
The 'update Dashboard' on the VDC is confusing to be always there in the user drop menu.

imagine a lot of users pressing the update button multiple times with no clue if there is an update or no, too unnecessary requests send to the server.

### Implementation
- it can be shown only when there is an update. 

- or/and at least should be a message like 'there is no available update at the moment' and 'the update succeeded'
Users don't have to check the dev console or guess what happened after they press the button.

**Comment by xmonader** [comment]
It's much better now
