### ISSUE TITLE
a classical floating point precision problem shows in the chat follow.

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/js-sdk#2670]
### Description

the number is too long due to a classical floating point precision problem.
![Screenshot from 2021-02-28 20-26-44](https://user-images.githubusercontent.com/42457449/109430430-21c8c700-7a0a-11eb-93e7-feeda87811b9.png)

### Implementation
the number could be rounded, or even better to use python 'Decimal' type instead of the 'float' type.

**Comment by weynandkuijpers** [comment]
Please verify and close

**Comment by waleedhammam** [comment]
Verified with 4 decimal points, and can have up to 7 too
