### ISSUE TITLE
Discourse deployment comes without admin setup

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2680]
### Description

I deployed Discourse but it's not usable as such. It says that there is no admin that has been defined. Won't be usable as such for non-technical people. 
If not possible, need to understand how to document in info_cloud. Or will notification be set up in Digital Twin / 3fold Connect ? Can the e-mail from there be recovered ? 

![image](https://user-images.githubusercontent.com/30384423/109492736-b58ea780-7a8b-11eb-9fa7-c138b5a3ae30.png)

### Version information

* OS: MacOS BigSur
* Browser: Chrome

### Installation method

From vdc on testnet

**Comment by xmonader** [comment]
Let's see once the new discourse code is done.
