### ISSUE TITLE
3bot No Longer Accessible

### ISSUE THREAD

**Issue by VonSub** [threefoldtech/js-sdk#2682]
<img width="2032" alt="Screenshot 2021-03-01 at 14 52 00" src="https://user-images.githubusercontent.com/29431263/109506212-ae709500-7a9d-11eb-8e17-115df10f3ba0.png">
I have 2 running hosted 3Bots.
A newer one (jiujitsubot) and an older one (bettertokenbot).
I have created the newer one to see if I can still access 3Bots at all, and it seems I can as I can as I just deployed and accessed Jiujitsubot's dashboard with succes.

<img width="2032" alt="Screenshot 2021-03-01 at 14 53 45" src="https://user-images.githubusercontent.com/29431263/109506462-f099d680-7a9d-11eb-8b26-9f3b9417ec11.png">

The link for the Bettertokenbot however gives me this:

![image](https://user-images.githubusercontent.com/29431263/109506537-07d8c400-7a9e-11eb-97ac-873cfb5101b5.png)

**Comment by waleedhammam** [comment]
@VonSub My guess is that a gateway failure, can you list the workloads ids from `more information` icon to be able to debug more.
also when was it deployed and when was the last time it was working ?

we can add a state update if the 3bot is running but has error.

**Comment by VonSub** [comment]
@waleedhammam 
![image](https://user-images.githubusercontent.com/29431263/109964220-ac9d1080-7ced-11eb-968e-6842f1d274f0.png)

More info
```
 
-
 
{
 
 
-
 
 
 
"wids"
: 
[
 
 
 
 
 
 
 
 
82927
,
 
 
 
 
 
 
 
 
82928
 
 
 
 
 
 
]
,
 
 
 
 
 
 
"name"
: 
"bettertokenbot"
,
 
 
 
 
 
 
"domain"
: 
"roel-threebot-bettertokenbot.tfgw-prod-04.gateway.tf"
,
 
 
 
 
 
 
"gateway_pool"
: 
1376
,
 
 
 
 
 
 
"gateway"
: 
"EvHQfXTMAfdgJZiWzA46c2yKUyivZP8NcMtUEz2XgSpK"
,
 
 
 
 
 
 
"ipv4"
: 
"10.100.0.2"
,
 
 
 
 
 
 
"ipv6"
: 
"<nil>"
,
 
 
 
 
 
 
"flist"
: 
"https://hub.grid.tf/ahmed_hanafy_1/ahmedhanafy725-js-sdk-latest.flist"
,
 
 
 
 
 
 
"disk_size"
: 
2048
,
 
 
 
 
 
 
"cpu"
: 
1
,
 
 
 
 
 
 
"memory"
: 
2048
,
 
 
 
 
 
 
"node"
: 
"FhfuPwcPhjZNg7cp6H9uZc142eS2fHDWXzxdAz6XNCxT"
,
 
 
 
 
 
 
"compute_pool"
: 
1375
,
 
 
 
 
 
 
"network"
: 
"management"
,
 
 
 
 
 
 
"branch"
: 
"development"
,
 
 
 
 
 
 
"public_key"
: 
""
,
 
 
 
 
 
 
"solution_uuid"
: 
"d47b67ebdb9b4f55927e2496d45b990a"
,
 
 
 
 
 
 
"farm"
: 
"Vladimir_Katasov"
,
 
 
 
 
 
 
"state"
: 
"RUNNING"
,
 
 
 
 
 
 
"continent"
: 
null
,
 
 
 
 
 
 
"expiration"
: 
"26/04/2021, 19:41:10"
,
 
 
 
 
 
 
"alert"
: 
false
 
 
 
 
}
 ```

**Comment by waleedhammam** [comment]
It seems the TRC process is down
Need to investigate on the machine, and I see the public key is empty so you won't be able to provide logs or investigate further.

You can restart the 3Bot to get this machine running again

**Comment by weynandkuijpers** [comment]
Please verify and close if solved.  Otherwise, push back to "in progress"
