### ISSUE TITLE
Deployment of a Presearch node on a newly defined VDC fails

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2684]
### Description

I create a new VDC (flavour gold) and pay for it. That works fine. 
Now I try to deploy a first solution on it, but it already states 'no space available'.

New VDC : https://geertincubaid-geertvdctest.vdctest.grid.tf/

Error deploying a first solution: 
![image](https://user-images.githubusercontent.com/30384423/109518793-e205ec00-7aaa-11eb-911b-7d89fe693850.png)

### Version information

* OS: MacOS
* Browser: Chrome 88

**Comment by gmachtel** [comment]
Seems like the size of the created pod is way too big compared to what is needed. Please check to reduce.

**Comment by siddiquagig** [comment]
Just deployed a Presearch node on the Silver VDC Package  successfully ,  2000cpu /2024mem is already enough for the gold package , this issue could be related to the pod_size

**Comment by gmachtel** [comment]
Ok will try again. But I propose anyway to have a way smaller size proposed for this solution, as the current container really doesn’t require the resources proposed. It’s also a commercial argument: why should people spend so many resources if not needed. With reduced volumes, they can run more in the same VDC.

**Comment by abdulgig** [comment]
@gmachtel , the size is already low on the helm chart but we could also reduce the options in the chatflow

**Comment by weynandkuijpers** [comment]
@gmachtel Please verify and close

**Comment by gmachtel** [comment]
is ok, works.
