### ISSUE TITLE
automation test for Backup & restore feature

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/js-sdk#2695]
### Feature
https://github.com/threefoldtech/js-sdk/issues/2633

### steps

    deploy vdc
    deploy cryptpad
    trigger backup using SAL
    check that a backup has been created
    delete the vdc
    redeploy with the same name & password
    you'll find your cryptpad like you left it after 5 mins

### Implementation

please add more manual valid scenarios to be added into the testlodge for external user testing.

**Comment by mhost39** [comment]
https://github.com/threefoldtech/js-sdk/issues/2720

**Comment by mhost39** [comment]
Manual Test  Scenarios:
```
deploy vdc 
create a backup
delete the vdc
redeploy with the same name & password and restore the backup
check that deployed vdc with same domain 

deploy vdc
deploy cryptpad
create a backup
check that a backup has been created
delete the vdc
redeploy with the same name & password and restore the backup
you'll find your cryptpad like you left

deploy vdc
deploy two cryptpad
create a backup
check that a backup has been created
delete the vdc
redeploy with the same name & password and restore the backup
you'll find your 2 cryptpad like you left

deploy vdc
deploy  cryptpad
create a backup
check that a backup has been created
delete the cryptpad
restore the backup
check that cryptpad will be find

deploy vdc
deploy  cryptpad
wait one hour
delete the VDC
redeploy with the same name & password
check that cryptpad will be find
```
![image](https://user-images.githubusercontent.com/31102305/111476772-234afc80-8737-11eb-9daf-b13b02d32ebc.png)
![image](https://user-images.githubusercontent.com/31102305/111476894-407fcb00-8737-11eb-90ea-47c1bd3c32e7.png)
![image](https://user-images.githubusercontent.com/31102305/111477202-8ccb0b00-8737-11eb-8257-40d3394210f7.png)
![image](https://user-images.githubusercontent.com/31102305/111477281-9fdddb00-8737-11eb-8b82-e24d8a865acb.png)

**Comment by mhost39** [comment]
Wait to configure velero in CI

**Comment by xmonader** [comment]
this needs to be reviewed before integration.

**Comment by mhost39** [comment]
the test fail when try reaching to the cryptpad after restore (the wait time is 600 seconds)
https://github.com/threefoldtech/js-sdk/runs/2287298999?check_suite_focus=true#step:6:716

related PR https://github.com/threefoldtech/js-sdk/pull/2760

**Comment by xmonader** [comment]
this issue is taking forever @ramezsaeed what is the problem?

**Comment by rkhamis** [comment]
@mhost39 @ramezsaeed what's the status here?
