### ISSUE TITLE
Test: Farm management: should allow farmer to set custom prices for specific customer

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/js-sdk#2696]
### Feature
https://github.com/threefoldtech/js-sdk/issues/2252

https://github.com/threefoldtech/js-sdk/issues/2624

### Description
Add test scenarios for setting custom prices for specific customer, to be used in testlodge for an eternal user testing.

**Comment by Pishoy** [comment]
- i have installed by jsng threebot server with 3bot name `bishoy2.3bot`
- install frammanagment package

### first working test
1. go to `SET FARM PRICES`  tab , then I set the is to 1 1 1   as shown on below picture 
2. the editing working well

![image](https://user-images.githubusercontent.com/21987477/109836997-655f4300-7c4d-11eb-8df3-081fdd8135c8.png)




### second working test
1. go to `ADD A DEAL` tab,  set a deal to bishoy2.3bot account 

![image](https://user-images.githubusercontent.com/21987477/109836712-2204d480-7c4d-11eb-8eaf-7d6878bbfa60.png)

### Third  working test
1. go to `ADD A DEAL` tab, edit above deal for bishoy2.3bot account 

![image](https://user-images.githubusercontent.com/21987477/109836477-dbaf7580-7c4c-11eb-9b3a-d39a5af0108b.png)

### Fourth working test
1. go to `ADD A DEAL` tab, delete above deal for bishoy2.3bot account 
![image](https://user-images.githubusercontent.com/21987477/109835845-44e2b900-7c4c-11eb-954e-3a0a882f7cba.png)



### first bug 
1. go to farm settings 
2. press on + `IP Address management`
3. delete added IP address
4. got error as below picture 
![image](https://user-images.githubusercontent.com/21987477/109822375-8e78d700-7c3f-11eb-86f7-cc65aab17ea9.png)
### second bug
adding same deal does not give message like "deal already exist"
1. go to `ADD A DEAL` tab, add same deal for bishoy2.3bot account with 2 2 2 , while that deal already exist
2. the deal added normaly while it is already exist
![image](https://user-images.githubusercontent.com/21987477/109837868-4a410300-7c4e-11eb-8c3b-226bf2f34902.png)

### feature request 
to validated the walllet address on  adding a wallet address
steps:
1. go to farm settings 
2. add a new wallet, put the invalid address as below :
3. the wallet address added depiste validation 
![image](https://user-images.githubusercontent.com/21987477/109821392-9a17ce00-7c3e-11eb-9599-0de4015298d5.png)

**Comment by xmonader** [comment]
@Pishoy  please move any issue that's not related to the farm prices to a separate issue e.g (the ip mgmt bug and the address validation)

and for adding the deals (it will create or update an existing deal) the farmer can have only one deal with a specific threebot.

**Comment by Pishoy** [comment]
new issue added https://github.com/threefoldtech/js-sdk/issues/2701
