### ISSUE TITLE
Test custom domains not managed by the gateway

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/js-sdk#2697]
### Feature

https://github.com/threefoldtech/js-sdk/issues/2028

### Description

Add Test scenarios for custom domains not managed by the gateway, so it can verify feature is working as expected and to use these scenarios on testlodge for the next phase for external user testing.

**Comment by PeterNashaat** [comment]
- Tested it and it was easy few steps.
https://tobdelete.token.green/
