### ISSUE TITLE
clear any "FreeTFT" related in quick start documentaion

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/js-sdk#2698]
### Description
Need to clean up the docs from any related FreeTFT word.

https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/quick_start.md

https://threefoldtech.github.io/js-sdk/wiki/#/./quick_start?id=create-a-new-wallet

![Screenshot from 2021-03-03 17-33-41](https://user-images.githubusercontent.com/16083592/109830800-802eb900-7c47-11eb-843b-2cd45f029527.png)

**Comment by weynandkuijpers** [comment]
Checked and no longer freeTFT mentioned.  IT is still mentioned in the explorer on the "free to use" button. For now close the issue and  create a new for the explorere.
