### ISSUE TITLE
can not delete added IP Address and no wallet address validation on Farm mangement 

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/js-sdk#2701]
### first bug 
1. go to farm settings 
2. press on + `IP Address management` , add a new IP Address 
3. delete added IP address
4. got error as below picture 
![image](https://user-images.githubusercontent.com/21987477/109822375-8e78d700-7c3f-11eb-86f7-cc65aab17ea9.png)

### feature request 
to validated the walllet address on  adding a wallet address
steps:
1. go to farm settings 
2. add a new wallet, put the invalid address as below :
3. the wallet address added depiste validation 
![image](https://user-images.githubusercontent.com/21987477/109821392-9a17ce00-7c3e-11eb-9599-0de4015298d5.png)

**Comment by xmonader** [comment]
@hossnys please verify

**Comment by hossnys** [comment]
Verified on branch development :

- creating farm with wrong wallet address : it's validating wallet address and if it was wrong so process fail .
     
![Screenshot from 2021-05-30 14-31-19](https://user-images.githubusercontent.com/26298009/120104453-c2876980-c154-11eb-999a-eefb2d83ff90.png)
- creating farm with correct wallet address :  if wallet address is valid so farm created 
 
![Screenshot from 2021-05-30 14-34-56](https://user-images.githubusercontent.com/26298009/120104499-01b5ba80-c155-11eb-94dc-e823e7fd9ca3.png)

- adding ip address then try to remove it , it's removed successfully

![Screenshot from 2021-05-30 14-36-39](https://user-images.githubusercontent.com/26298009/120104520-1d20c580-c155-11eb-9387-f4d8ffbe93ac.png)
![Screenshot from 2021-05-30 14-37-21](https://user-images.githubusercontent.com/26298009/120104521-1db95c00-c155-11eb-8e04-80e25fed7985.png)
![Screenshot from 2021-05-30 14-37-32](https://user-images.githubusercontent.com/26298009/120104522-1eea8900-c155-11eb-8045-879451c367a8.png)
