### ISSUE TITLE
Restart of a deployed 3Bot fails

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2705]
### Description

I did a stop/start of my 3Bot called 'hobbestestbot' . Stop worked but restart failed. 

![image](https://user-images.githubusercontent.com/30384423/109974564-fd1a6b00-7cf9-11eb-84b0-14ecf455a034.png)

### Version information

* OS: MacOS
* Project commit/version: e.g. js-ng 11.0b3
* Browser: Chrome88

### Installation method

Deployed 3Bot

 
```-
{
-
"wids"
: 
[8494,8495,8496],
 "name": "hobbestestbot",
 "domain": "hobbestestbot.3bottest.grid.tf",
 "gateway_pool": 4224,
 "gateway": 
"9PdutHsdDSxcKUUyDg8ovS1KWh47qLT5R9h5uoFgRUH2"
,
"ipv4": "10.100.0.2",
"ipv6": "fd55:5337:796b::2",
"flist": "https://hub.grid.tf/ahmed_hanafy_1/ahmedhanafy725-js-sdk-latest_trc.flist",
"disk_size": 4096,
"cpu": 1,
"memory": 2048,
"node": "EBKTQA1A4gXVjvcJf5GE94DfA7DDE4rEGyKkfam8V1Wk",
"compute_pool": 4223,
"network": "management", 
"branch": "development",
"public_key": "ssh-rsa XXX",
"solution_uuid": "616dd55e5afd4b868321e9f614c84f22",
"farm": "ogfarm",
"state": "STOPPED",
"continent": null,
"expiration": "-",
"alert": false
}```

**Comment by m-motawea** [comment]
only one node of `ogfarm` which the pool is attached to is running. and that node doesn't have global ipv6 so that's why restarting your 3bot on the current farm will always fail. you'll need to change the 3bot location

pool: 
https://explorer.testnet.grid.tf/api/v1/reservations/pools/4223

![image](https://user-images.githubusercontent.com/32568986/109979503-a320a200-7d07-11eb-9a73-fab1b7da4750.png)


```python
JS-NG> n = zos._explorer.nodes.get("EBKTQA1A4gXVjvcJf5GE94DfA7DDE4rEGyKkfam8V1Wk")
JS-NG> zos.nodes_finder.filter_public_ip6(n)
False

JS-NG> 

```

**Comment by gmachtel** [comment]
GreenEdge has same behaviour. Same issue ? 

![image](https://user-images.githubusercontent.com/30384423/109984220-d6f9c880-7d03-11eb-93a4-eb0858e8658a.png)

**Comment by gmachtel** [comment]
It worked for me but I had to explicitly select freefarm. Automated selection gave the same error.

**Comment by gmachtel** [comment]
Will close this issue, but opened separate issue https://github.com/threefoldtech/js-sdk/issues/2708 about relocation.
