### ISSUE TITLE
Relocating a deployed 3Bot on testnet using Automatic location selection sometimes fails

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2708]
### Description
I relocated my 3Bot called 'hobbestestbot' as node it was running on was down. 
However got the same issue when choosing 'automatic location selection'. 
When choosing 'farm' and then freefarm it worked. 

Is not always, second deployment worked. Can the non-working nodes be filtered out beforehand with automatic relocation ? 

### Version information

* OS: MacOS
* Project commit/version: JS-NG: 11.0b12 - JS-SDK: 11.0b14
* Browser: Chrome 88

### Installation method

Hosted 3Bot

**Comment by waleedhammam** [comment]
We already block the non-working nodes, was the error because of no resources or what ?

**Comment by gmachtel** [comment]
No it wasn’t. Automatic selection didn’t work, selecting by farm and then freefarm right after did work. So I imagine it also searches for nodes belonging to farms that can’ t be used.

**Comment by waleedhammam** [comment]
@gmachtel what was the error happening on automatic selection ?

**Comment by xmonader** [comment]
> @gmachtel what was the error happening on automatic selection ?

I believe this one https://github.com/threefoldtech/js-sdk/issues/2705 this farm didn't have ipv6 so it was refused in manual farm selection, but apparently, it was ok for automatic farm

**Comment by waleedhammam** [comment]
won't be an issue after https://github.com/threefoldtech/js-sdk/commit/23fe341a512c06f81dc020e2a500bb8ab00be85d

**Comment by weynandkuijpers** [comment]
Could not find any "free" word on those pages.
