### ISSUE TITLE
VDC Dashboard update keeps on spinning

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2709]
### Description

I pushed on Update dashboard, but it keeps on spinning. No clue whether update has been done or not. 

![image](https://user-images.githubusercontent.com/30384423/109996957-fdbdfc00-7d0f-11eb-9baa-44bd2e9a58bb.png)

### Version information

* OS: MacOS BigSur
* Project commit/version: VDC
* Browser: Chrome 88

**Comment by weynandkuijpers** [comment]
Verified and no longer an issue.
