### ISSUE TITLE
publishingtools solution

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#271]
- [x] flist for publishingtool binary with git
- [x] Choose optional node. Otherwise we choose our capacity
- [x] name on a domain we have
- [x] URL(git/https)
- [x] deploy prepare config file 
- [x] run publishing with that config

**Comment by AhmedHanafy725** [comment]
flist created https://hub.grid.tf/ahmed_hanafy_1/ahmedhanafy725-pubtools-https.flist

**Comment by ahsayde** [comment]
Publisher solution is implemented, you can access it from the admin dashboard

**Comment by hossnys** [comment]
verified :

deploying wiki example :


![Screenshot from 2020-07-26 15-50-40](https://user-images.githubusercontent.com/26298009/88480690-abd21e00-cf57-11ea-861c-7fd2a054669c.png)

![Screenshot from 2020-07-26 15-51-27](https://user-images.githubusercontent.com/26298009/88480694-af65a500-cf57-11ea-8bd2-03bbaf1f380a.png)
