### ISSUE TITLE
VDC content unreachable - DNS error

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2710]
### Description

I deployed a new VDC, it was generated, but link to it gave an error. 

### Version information

* OS: MacOS
* Project commit/version: VDC
* Browser: Chrome 88

![image](https://user-images.githubusercontent.com/30384423/110002262-7d9a9500-7d15-11eb-9ed5-419bacefe73d.png)

**Comment by gmachtel** [comment]
Looks like I try to access it before it's ready. But url was already shown.

**Comment by xmonader** [comment]
Add the vdc name please

**Comment by gmachtel** [comment]
geertvdctest . But as said, url worked but it was already shown at a moment that it wasn't there yet.

**Comment by AhmedHanafy725** [comment]
Now it will show that the VDC is not accessible until its domain is deployed.
![image](https://user-images.githubusercontent.com/41957921/110291225-59300880-7ff4-11eb-8846-cde91d91ec7e.png)


and after it finishes
![image](https://user-images.githubusercontent.com/41957921/110291304-74027d00-7ff4-11eb-801b-22aa364091a7.png)

**Comment by weynandkuijpers** [comment]
Please verify and close if solved.  Otherwise, push back to "in progress"
