### ISSUE TITLE
VDC: Add capacity check before showing payment for extending kubernetes with an extra node

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#2711]
After paying for an extra node, got not enough resources error

![image](https://user-images.githubusercontent.com/41957921/110043061-68425c80-7d4f-11eb-8d18-fbb1b237fa71.png)

**Comment by weynandkuijpers** [comment]
Please verify and close if solved.  Otherwise, push back to "in progress"

**Comment by AhmedHanafy725** [comment]
**Branch:** development
**Commit:** c19232ed8b78a03fb1765664afdeb120e8b48f2d
**Verified**
