### ISSUE TITLE
newly deployed VDC keeps reporting new release is available + broken image at QR code to top up wallet

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2712]
bnot name: weynandkuijpers.3bot
browsers:  firefox and chrome
newly deployed VDC: (5/3/2021)
![image](https://user-images.githubusercontent.com/13766992/110071996-7f586d00-7d96-11eb-8ba1-46153bbd4a9c.png)

- pressing "update now" result in screen being reloaded and a repiition of the message "update available"
- pressing "later" make the message go away
![image](https://user-images.githubusercontent.com/13766992/110072157-ca728000-7d96-11eb-81ef-ba51c35e7a90.png)

- pressing manual "update dashboard"
![image](https://user-images.githubusercontent.com/13766992/110072272-f261e380-7d96-11eb-9d38-bc26cac3e1e1.png)
results in message about update available being presented again:
![image](https://user-images.githubusercontent.com/13766992/110072347-102f4880-7d97-11eb-8ad1-52e95b60bae3.png)

**Comment by xmonader** [comment]
Just checked on your 3bot, 

```
root@zosv2tst-2:/sandbox/code/github/threefoldtech/js-sdk# git describe --tags --abbrev=0
v11.0-b14
```
So indeed there should be no update available message also the latest release
```
 curl -s https://api.github.com/repos/threefoldtech/js-sdk/releases | jq '.[0].tag_name'
"v11.0-b14"
```

I disabled the check for update for now

**Comment by DylanVerstraete** [comment]
Same issue here

**Comment by xmonader** [comment]
@weynandkuijpers please add info from developer tools (f12) for the broken image

@weynandkuijpers @DylanVerstraete I updated your VDCs dashboard and disabled the check update for now.

**Comment by weynandkuijpers** [comment]
Please verify and close if solved.  Otherwise, push back to "in progress"

**Comment by weynandkuijpers** [comment]
I have not see this issue repeat itself.
