### ISSUE TITLE
No recovery of XLM from prepaid wallet after VDC was closed

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2714]
### Description

I deleted a VDC after transfer of remaining TFT to my wallet (even though I thought there was going to be automatic refunding). 

However, I left the XLM in place, but I copied the secret into an interstellar wallet. 

After closure of the VDC, it showed that the XLMs remained on the created wallet. If I had closed the VDC without copying the secret, the XLMs would have been lost (and no one will think about recovering it as there is no mention of it in the VDC wallet). 

![image](https://user-images.githubusercontent.com/30384423/110125434-96618400-7dc3-11eb-9daa-328aee501419.png)

### Version information

* OS: MacOS
* Project commit/version: VDC
* Browser: Chrome 88

**Comment by xmonader** [comment]
We hold the info of all the wallets in the system, and we merge them back to our activation service on the deleted VDCs every now and then.
