### ISSUE TITLE
Minio with zdbfs chatflow example

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#2715]
continue on: https://github.com/threefoldtech/js-sdk/issues/2262

create an example of chatflow to be easy to test

**Comment by waleedhammam** [comment]
- Added a WIP sal for starting quantum storage on the cluster nodes

Todo: develop a helm chart to utilize that sal

**Comment by waleedhammam** [comment]
added helm chart & chatflow at https://github.com/threefoldtech/js-sdk/pull/2722#issue-586292760

**Comment by waleedhammam** [comment]
Current state in the PR: it deploys external etcd with the cluster to be able to use it in the zstorfs

If we want to use our custom etcd, the endpoints will be with domains and zstor currently doesn't support TLS, will be followed in: https://github.com/threefoldtech/0-stor_v2/issues/16

**Comment by waleedhammam** [comment]
blocked on https://github.com/threefoldtech/0-stor_v2/issues/25

**Comment by waleedhammam** [comment]
Added enable quantum storage feature from dashboard and download the zstor config with etcd and authentiaction

https://user-images.githubusercontent.com/10658229/111310220-81a7aa80-8665-11eb-9b5c-634e50a3ccd2.mp4

**Comment by waleedhammam** [comment]
https://github.com/threefoldtech/js-sdk/pull/2722#issuecomment-800981300

**Comment by AhmedHanafy725** [comment]
**Branch:** development
**Commit:** 904582ff079aa4c37b87f7d0dfdb2c18eea0ff5c

can't verify, as the latest release of zstor is not in k3os image yet.

![image](https://user-images.githubusercontent.com/41957921/111905209-2570cc00-8a53-11eb-8613-57133180ddf7.png)

**Comment by xmonader** [comment]
Issue for zos to update: https://github.com/threefoldtech/zos/issues/1221

**Comment by waleedhammam** [comment]
blocked on https://github.com/threefoldtech/zos/issues/1224

**Comment by AhmedHanafy725** [comment]
**Verified**
![image](https://user-images.githubusercontent.com/41957921/112344766-1b5a0200-8ccd-11eb-9d6d-2a93a5100ca2.png)
