### ISSUE TITLE
marketplace to have terms/conditions before allowing the functionality for the logged in user

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#272]
as long as the user didn't agree on the terms on conditions we should show a wizard asking do you agree on the following terms (terms to be defined)

if yes, he is allowed to use the marketplace, and if not he is locked and only action he can do is seeing the wizard for terms & conditions.

**Comment by waleedhammam** [comment]
added in: https://github.com/threefoldtech/js-sdk/pull/269

**Comment by waleedhammam** [comment]
waiting for the real terms and conditions to replace the place holder
