### ISSUE TITLE
can't restore vdc backup 

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/js-sdk#2720]
on https://vdc.devnet.grid.tf/vdc/#/
i deployed a vdc with name: mostafa and tname: posix
and deployed a  cryptpad 
after more than hour i deleted this vdc then deployed anther one with the same name and password 
and after 10 minutes i can't find deployed cryptpad

![image](https://user-images.githubusercontent.com/31102305/110242493-1708b780-7f5f-11eb-8249-7193d11ecc3c.png)

**Comment by waleedhammam** [comment]
@mhost39 I tested the scenario myself and works with me, are you sure you were on the right branch ?

**Comment by waleedhammam** [comment]
also instead of waiting you can tesst using https://github.com/threefoldtech/js-sdk/pull/2706

**Comment by mhost39** [comment]
@waleedhammam  
development_vdc_storage_farms_selection this is the branch was used at that time

**Comment by waleedhammam** [comment]
maybe it wasn't updated then, we can check with latest development

**Comment by weynandkuijpers** [comment]
Did a restore, but all (new) deployed applications stayed online.  How to test restoring a previous VDC state?

**Comment by mhost39** [comment]
Verified on testnet
deployed a VDC and cryptpad and create a backup 
then deleted the cryptpad and restored a backup
i find my cryptpad and reachable 
![image](https://user-images.githubusercontent.com/31102305/111984000-7ea03480-8b13-11eb-888f-71e2051708bd.png)
