### ISSUE TITLE
Will there be automatic cancellation after 3 hours ?

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2726]
### Description

I deployed a VDC. That worked perfectly, but I got the message that my deployment will be automatically cancelled after 3 hours. Also referring to Threefold NOW. Correct ?

![image](https://user-images.githubusercontent.com/30384423/110312456-630e3780-8005-11eb-9301-c268c0a932da.png)

### Version information

* OS: MacOS
* Project commit/version: VDC
* Browser: Chrome 88

**Comment by xmonader** [comment]
it's a leftover from the flists marketplace indeed, thanks for reporting

**Comment by xmonader** [comment]
@gmachtel what are the correct links for the VDC documentation?

**Comment by gmachtel** [comment]
> @gmachtel what are the correct links for the VDC documentation?

For now all in wiki.cloud.threefold.io
Might change in the future though to  threefold.io/info/cloud

**Comment by weynandkuijpers** [comment]
Verified and closed
