### ISSUE TITLE
Show etcd connection information in the VDC dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2728]
- Private endpoints aren't needed for the user
- Requires socat proxy on the public IP
- Requires resolving authentication (etcd v3) + secure communication  https://github.com/threefoldtech/0-stor_v2/issues/16

**Comment by sasha-astiadi** [comment]
@waleedhammam could you please comment why its blocked

**Comment by xmonader** [comment]
> @waleedhammam could you please comment why its blocked so we have a documentation here

there is no support for TLS communication in 0-stor yet. https://github.com/threefoldtech/0-stor_v2/issues/16

**Comment by waleedhammam** [comment]
resolved by: https://github.com/threefoldtech/js-sdk/issues/2715#issuecomment-800224943

**Comment by AhmedHanafy725** [comment]
**Branch:** development
**Commit:** 904582ff079aa4c37b87f7d0dfdb2c18eea0ff5c
**Verified**

![image](https://user-images.githubusercontent.com/41957921/111904487-e8570a80-8a4f-11eb-9114-b33ca1e5766c.png)

![image](https://user-images.githubusercontent.com/41957921/111904467-cfe6f000-8a4f-11eb-9f27-dc819ed685b2.png)

![image](https://user-images.githubusercontent.com/41957921/111904515-0b81ba00-8a50-11eb-8e04-4e1d3a75da47.png)
