### ISSUE TITLE
Reduce etcd resources

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2729]
should be 100m mem and less disk

problems:
- when ran against 1GB 

![image](https://user-images.githubusercontent.com/64129/110330306-4cc4a380-8026-11eb-96eb-7e838e8bec79.png)

- and when the disk was 256m 
https://github.com/threefoldtech/js-sdk/issues/2649

https://etcd.io/docs/v3.4.0/op-guide/
https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/

**Comment by waleedhammam** [comment]
Lower etcd resources will lead to catastrophic failure to the whole cluster

**Comment by xmonader** [comment]
this is closed because we will go with the embedded etcd for the cluster brain and with a etcd cluster solution from the marketplace.
