### ISSUE TITLE
Deployment of Mattermost and Kubeapps give chatflow certificate error in 'create subdomain'

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2733]
Tester community started testing and encounter error in 'create subdomain' step in chatflow, both for Cryptpad and Kubeapps. What does this error mean ? Webgateway issue ?

![image](https://user-images.githubusercontent.com/30384423/110478502-b73c1900-80e4-11eb-8c51-aac2680fb0fd.png)

![image](https://user-images.githubusercontent.com/30384423/110478884-1568fc00-80e5-11eb-9879-35d03ee40b68.png)

**Comment by MElborolossy** [comment]
Already fixed here
https://github.com/threefoldtech/js-sdk/pull/2732

**Comment by weynandkuijpers** [comment]
I have had numerous people directly approach me on this. Can we have a description of what caused this and what have been done for this never to re-occur?  And please make is readable to engineers and non-engineers.

**Comment by weynandkuijpers** [comment]
Thank you @xmonader.  Thought:  do we flag to "update" the dashboard if a new version/update has been released on existing VDC's?  If not can we consider doing one of the following things:
- flag / present a message next time when a VDC owner is logging in to his VDC to update to the latest version
- do a "nightly" auto-update of the marketplace / VDC code?
- or something much smarter, which I am sure @xmonader you can think of. :-)

**Comment by weynandkuijpers** [comment]
Have deployed new solutions - Taiga and Cryptpad and both have a successful deployment of the gateway.  Closing issues
