### ISSUE TITLE
It takes 2 or more times to stop a 3bot in the 3bot deployer

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2734]
From the 3bot deployer (testnet) it takes me usually 2 to 3 times to "stop" a working 3bot.  Meaning I tell it to stop my 3bot, it asked me for the password and then it presents me the same 3bot overview pages where the 3bot is not stopped.  Repeating the process 2 (sometimes 3 times) get's the 3bot stopped.

Network: testnet
3bot name: cometjetser
Operator: weynandkuijpers.3bot

**Comment by dmahmouali** [comment]
I can't reproduce on chrome, can you update the issue with the browser name?

**Comment by weynandkuijpers** [comment]
The browser I normally use is Firefox.  Will test now with Chrome.

Agree - with the Chrome browser it stops the 3bot immediately.  Will do another test now with the Firefox browser:

Also does not take 2 times.  Not sure what caused/took the cause away but for now, I will close the issue.  If it returns - will reopen it.
