### ISSUE TITLE
can't ssh 3bot

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/js-sdk#2741]
with testnet i created a threebot with name: threebottest

![image](https://user-images.githubusercontent.com/31102305/110658919-c5646500-81ca-11eb-913f-f371442d1489.png)

and after up wireguard
![image](https://user-images.githubusercontent.com/31102305/110659142-fba1e480-81ca-11eb-872b-d88d327efb04.png)

and i try to pind and ssh to 3bot but it failed

**Comment by xmonader** [comment]
as far as I understood it's Egypt ISP blocking the traffic. If so please close the issue

**Comment by mhost39** [comment]
it worked fine now 
the problem was in internet connection
