### ISSUE TITLE
REST interface on top of the current vdc dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2743]
should do the common interactions with the dasboard 
e.g

- [x] list all nodes
- [x] add node
- [x] delete node given wid
- [x] list all zdbs <- will be needed to for zstor for monitoring and repair actions
- [x] add zdb <- will be needed for zstor for monitoring and repair actions  [parameters: farms]
- [x] get wallet information
- [x] get pools information
- [x] get alerts 

the api should be protected by a secret token (I suggest we use the cluster secret for these operations)

**Comment by weynandkuijpers** [comment]
Can we please verify and put to "Done" if all is okay?

**Comment by waleedhammam** [comment]
Verifying ..

**Comment by waleedhammam** [comment]
- Deleting the master node returns error 500, suggestion not to try and return a nice message you can't delete the master node with a 400

![Screenshot from 2021-03-21 11-48-52](https://user-images.githubusercontent.com/10658229/111900971-16335380-8a3e-11eb-8dd3-fb6823faabbf.png)

**Comment by waleedhammam** [comment]
All other points were verified successfuly 
![Screenshot from 2021-03-21 11-43-49](https://user-images.githubusercontent.com/10658229/111901161-de78db80-8a3e-11eb-93b6-db47feb07bff.png)
![Screenshot from 2021-03-21 11-42-57](https://user-images.githubusercontent.com/10658229/111901163-df117200-8a3e-11eb-80d3-bcdcba6a8e30.png)
![Screenshot from 2021-03-21 11-42-25](https://user-images.githubusercontent.com/10658229/111901164-e0429f00-8a3e-11eb-8e12-74d90fab353b.png)
