### ISSUE TITLE
gevent.signal is deprecated, use gevent.signal_handler

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#2744]
### Description
gevent 1.4.0 dependency is not supported with python 3.9 on osx

Issue in js-ng: https://github.com/threefoldtech/js-ng/issues/576

When manually upgrading gevent to '21.1.2'  and the greenlet dependency most things like starting jsng work but starting a threebot server from js-sdk( which depends on js-ng) there is an eror since  it uses `gevent.signal()`.

From the gevent docs:

>Changed in version 1.5a4: Previously there was a backwards compatibility alias gevent.signal, introduced in 1.1b4, that partly shadowed this module, confusing humans and static analysis tools alike. That alias has been removed. (See gevent.signal_handler.)

In gevent 1.4.0 the `gevent.signal_handler` is already available: https://github.com/gevent/gevent/blob/1.4.0/src/gevent/__init__.py
I propose to use the more future proof `gevent.signal_handler` instead of the deprecated `gevent.signal`

Currently the error is:

```JS-NG> j.servers.threebot.start_default()
2021-03-11 09:30:26.690 | INFO     | jumpscale.core.logging.logging:register:141 - Logging from 'jumpscale.servers.gedis' is now bound to 'gedis' app
2021-03-11 09:30:26.798 | WARNING  | jumpscale.entry_points.threebot:create_wallets_if_not_exists:269 - skipping wallets creation, identity isn't configured yet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rob/workspace/github.com/threefoldtech/js-sdk/jumpscale/servers/threebot/__init__.py", line 34, in start_default
    server.start(wait=wait)
    ?[36m│                 └ False?[m
    ?[36m└ ThreebotServer(
  instance_name='default',
  _package_manager=StoredFactory(PackageManager),
  domain=None,
  email=None,
  acme...?[m
  File "/Users/rob/workspace/github.com/threefoldtech/js-sdk/jumpscale/servers/threebot/threebot.py", line 810, in start
    gevent.signal(signal_type, self.stop)
    ?[36m│             │            └ ThreebotServer(
  instance_name='default',
  _package_manager=StoredFactory(PackageManager),
  domain=None,
  email=None,
  acme...?[m
    ?[36m│             └ <Signals.SIGTERM: 15>?[m
    ?[36m└ <module 'gevent' from '/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.9/lib/python3.9/site-packages/gevent/_...?[m
TypeError: 'module' object is not callable

'module' object is not callable
JS-NG> import gevent
JS-NG> gevent.__version__
'21.1.2'
```

**Comment by waleedhammam** [comment]
verified, server starts ok
