### ISSUE TITLE
Logout from hosted 3Bot doesn't react

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2746]
I am logged in with my 3Bot for a hosted 3Bot. I want to log out, but there's no reaction after pushing the button. 

Issue both on mainnet and testnet
![image](https://user-images.githubusercontent.com/30384423/110775785-9ba94d80-825f-11eb-9213-5f6d1cf89eb8.png)

![image](https://user-images.githubusercontent.com/30384423/110776143-035f9880-8260-11eb-87ab-973b5078cbd8.png)

### Version information

* OS: MacOS
* Project commit/version: Hosted 3Bot on testnet and mainnet
* Browser: Chrome 88 and Brave (tried both)

**Comment by waleedhammam** [comment]
Verified on devnet, testnet, mainnet
