### ISSUE TITLE
codeserver package seems to install incorrectly

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#275]
# what happens

- start 3bot
- go to /admin
- codeserver
- install package

I see 

![image](https://user-images.githubusercontent.com/64129/88053216-b8233900-cb5b-11ea-8b76-06f1b7f10627.png)

instead of codeserver ...

**Comment by dmahmouali** [comment]
Can't reproduce location error, but find anther error related to load static files

![photo_2020-07-21_14-49-22](https://user-images.githubusercontent.com/36021484/88056797-68e00700-cb61-11ea-8d58-414c753a701c.jpg)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
