### ISSUE TITLE
TC29 - create new Cryptpad account hangs after TF Connect login

### ISSUE THREAD

**Issue by Pkgraz** [threefoldtech/js-sdk#2750]
Testlodge TC29 - create new Cryptpad account - hangs after TF Connect login at check of data integrity

### Version information

* OS: Windows 10
* eVDC 2.5
* Testlodge Testrun: PK-Test5-deploy2.5-eVDC
* Browsers tried: 
 1) BRAVE (Version 1.21.74 Chromium: 89.0.4389.72), 
 2) Firefox (Version 86.0), 
 3) Chrome (Version 88.0.4324.190)

### Steps to reproduce

see screenshot log attached 
[TC29 create Cryptpad account failed 11Mar21.pdf](https://github.com/threefoldtech/js-sdk/files/6123480/TC29.create.Cryptpad.account.failed.11Mar21.pdf)

**Comment by weynandkuijpers** [comment]
Will try to recreate now.

**Comment by weynandkuijpers** [comment]
Tested and verified.  Newest release VDC on ```testnet```  does not exhibit the same behaviour

@Pkgraz please verify.

**Comment by weynandkuijpers** [comment]
For testing you can also log into my deployed cryptpad: https://weynandkuijpers-cryptpad-peterkraftpad.webg2test.grid.tf/drive/

**Comment by Pkgraz** [comment]
Hi Weynand,

Many thanks for your follow up.
I see still a strange behavior:
> While Brave and Chrome browsers still show a spinning wheel,
> the connection works fine with Firefox after maybe 10-15 seconds of a spinning wheel and a message "checking data integrity" and a green bar

***@***.***D71905.C7E58E40]

So the link hangs with Chrome and Brave, but connects with Firefox:

***@***.***D71905.C7E58E40]

Meanwhile, I have the same behavior with my test-eVDC: after 3 days (!!!) my Firefox Link to my Cryptpad works, so I can continue testing.

Many thanks,
Peter

Von: Weynand Kuijpers ***@***.***>
Gesendet: Sonntag, 14. März 2021 08:15
An: threefoldtech/js-sdk ***@***.***>
Cc: Pkgraz ***@***.***>; Mention ***@***.***>
Betreff: Re: [threefoldtech/js-sdk] TC29 - create new Cryptpad account hangs after TF Connect login (#2750)


For testing you can also log into my deployed cryptpad: https://weynandkuijpers-cryptpad-peterkraftpad.webg2test.grid.tf/drive/<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fweynandkuijpers-cryptpad-peterkraftpad.webg2test.grid.tf%2Fdrive%2F&data=04%7C01%7C%7Ce4b5b5fff4bc41bb234808d8e6b8d166%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637513028743046720%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sCYzUyvInWScOP8ccqNqiZNlmQSgWevOS8zFRUHgT6g%3D&reserved=0>

-

**Comment by Pkgraz** [comment]
> Tested and verified. Newest release VDC on `testnet` does not exhibit the same behaviour
> 
> @Pkgraz please verify.

Verified - works with Firefox only, still hangs on Chrome & Brave...
How can I determine the version of the eVDC deployed?

**Comment by dmahmouali** [comment]
> > Tested and verified. Newest release VDC on `testnet` does not exhibit the same behaviour
> > @Pkgraz please verify.
> 
> How can I determine the version of the eVDC deployed?

Opened a [new feature request issue](https://github.com/threefoldtech/js-sdk/issues/2766) to show the version in the VDC dashboard.
this issue should be closed?

**Comment by weynandkuijpers** [comment]
yes.  VDC version feature request will continue.

**Comment by Pkgraz** [comment]
Deployed a new vdc and confirm that now the Cryptpad account login works fine on Firefox, Chrome & Brave browsers.
Closing issue, many thanks for the quick fix.
