### ISSUE TITLE
Optimize layout of eVDC Back-up and Restore 

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2752]
Suggestion of elements to change in Back-up and restore section : 

![image](https://user-images.githubusercontent.com/30384423/110807741-a4ac1600-8283-11eb-8a72-bdd625285f03.png)

- [x] Replace `Start Date` by `Back-up date` (as it's the date that the back-up was taken)
- [x] Replace `Expiry Date` by `Back-up Removal date` (as it's the date that this back-up will be removed)
- [x] Put all back-up dates as timestamp: i.o. 'in 8 days' put '04/03/2021 17:21:05 CET'
- [x] Put all removal dates as timestamp: i.o. '22 days ago' put '31/03/2021 03:41:56 CET'
~- [ ] Possible to flag some back-ups as 'to be kept' ? => no removal date ?  (not possible atm, velero does the cleanup)~
- [x] Data status is always put as 'Partially Failed' but this is normal. Now it looks like the backup didn't work (partially). So I'd rename it to sthg like 'Metadata backed up' or simply mention also 'completed'
~- [ ] in the details, `errors` best to be replaced by `volumes not backed up` (as, again, it's not a real error, it's intended) ~ not needed, errors need to be the same as in the cluster otherwise we hide the errors and would be difficult to see if something goes really wrong
- [x] The 'Are you sure, this can't be undone' message when creating a backup is somewhat overkill, as there is no risk involved in creating this backup. Simply asking for the back-up name should be enough. 
- [x] A filter function would be nice to have, to find the right backup, especially the manual named back-ups -later-
- [x] List best to be sorted antichronologically, most recent ones first by default (next to the arrow sorting, which is nice)
~- [ ] Once back-up made, auto-refresh and show on top the most recent backups~ it happens but appended in the end
- [x] Typo in detail screen for restore `WARNING` i.o. `WARINING`

**Comment by gmachtel** [comment]
Not yet on testnet ?

![image](https://user-images.githubusercontent.com/30384423/111163530-7721de00-859d-11eb-9a37-943fbec9a3d1.png)

**Comment by waleedhammam** [comment]
@gmachtel the PR wasn't merged, It's updated now

**Comment by gmachtel** [comment]
Still don't see any change in my testnet VDCs, even if I pushed 'update dashboard' button

**Comment by waleedhammam** [comment]
@gmachtel Can you try hard refresh or use incognito mode ?

**Comment by gmachtel** [comment]
OK I have updated version now. I see dates now, thanks! 
thje 'PartiallyFailed' mentioned hasn't changed though ? 

![image](https://user-images.githubusercontent.com/30384423/111294659-d558ca80-864a-11eb-8dcd-90eaf07bf3f3.png)

**Comment by waleedhammam** [comment]
@gmachtel Indeed, can you update dashboard and check again now ?
Thank you

**Comment by gmachtel** [comment]
Ok now, thx!
