### ISSUE TITLE
Endless loop of "not having enough farms to deploy storage nodes"

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2756]
Network: devnet
3bot ID: weynandkuijpers.3bot

When deploying a VDC on devnet and selecting the option to select which farms to deploy the initial VDC in you end up in a loop "of not having enough nodes / farms" to deploy on.

![screenshot_20210312_094747](https://user-images.githubusercontent.com/13766992/110900779-bdb4d580-831c-11eb-8474-eb43c334b06d.png)

**Comment by AhmedHanafy725** [comment]
In case of using 1 farm to distribute the 10 zdb on, it won't work as devnet only one farm has 7 nodes, and in case of using 2 farms or more to distribute 10 zdb on, it won't work as well, as we have only one farm on devnet `lochristi_dev_lab`.
