### ISSUE TITLE
Hosted 3Bot on mainnet gives error, but can't be moved either

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2757]
I deployed a 3Bot on MAINNET and paid for it but it can be reached and gives an error. 

![image](https://user-images.githubusercontent.com/30384423/110961289-e904e800-834f-11eb-8b03-a53a0b49cfee.png)

I can't relocate it either, just restart it (but that generates the error)

![image](https://user-images.githubusercontent.com/30384423/110961548-35502800-8350-11eb-8234-dfaecf3c53f0.png)

* OS: MacOS
* Project commit/version: 3Bot on deploy3bot.grid.tf
* Browser: Chrome 88

**Comment by xmonader** [comment]
alert 411: 
![image](https://user-images.githubusercontent.com/64129/111432892-490bdd80-8706-11eb-89a8-750c0903c5a4.png)

@waleedhammam this is related to our latest change to check reachability right?

@gmachtel how come you paid any money? the 3bot deployer "pays" for your for 1 hour and if everything is provisioned and initialized your are prompted to pay :) ?

**Comment by gmachtel** [comment]
I was prompted to pay, yes

**Comment by waleedhammam** [comment]
@gmachtel Can you try again now, with hard refreshing the page ?

**Comment by gmachtel** [comment]
Now it keeps on spinning and timed out. 

![image](https://user-images.githubusercontent.com/30384423/111599835-02cf8080-87d1-11eb-8357-2f02e16c038f.png)

**Comment by waleedhammam** [comment]
Seems like it's very old 3Bot was deployed on the gateways which weren't updated.

So the solution to this https://github.com/threefoldtech/tf_operations/issues/38 to be solved
or Deploy a new 3Bot which will be against csfarmer

**Comment by sasha-astiadi** [comment]
we resolve this on 2.7

**Comment by gmachtel** [comment]
will wait before cleaning up the hosted 3Bot then, to retest (anyway, I paid tokens for it, and in the future also external people will have older hosted 3Bots, so we need to provide a solution and support different releases or a way to migrate easily).

**Comment by xmonader** [comment]
This is blocked on updating original gateways that we don't manage (freefarm gateways) https://github.com/threefoldtech/tf_operations/issues/38

**Comment by sabrinasadik** [comment]
Original gateways are updated (all 7 tf-gateway production servers that are hosted on Digital Ocean)

**Comment by gmachtel** [comment]
Issue solved, I can restart my hosted 3bot.
