### ISSUE TITLE
Failed to create backup

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/js-sdk#2759]
with devnet i deployed a VDC with name: mhassan
then deployed a cryptpad with name: test
![image](https://user-images.githubusercontent.com/31102305/111062062-59764b00-84af-11eb-8d9d-0ba9b3ebc76f.png)

then when try to create a backupwith name: cryptpad-backup
i got this error:
![image](https://user-images.githubusercontent.com/31102305/111062113-a0644080-84af-11eb-926b-8f4d024d4e9e.png)

```
{
 
    "name": "vdc-cryptpad-backup",
    "expiration":  1618301651,
    "status": "PartiallyFailed" ,
    "start_timestamp": 1615709651,
    "completion_timestamp": 1615709654,
    "errors": 1,
    "progress": {
        "totalItems": 13,
        "itemsBackedUp": 13
    }
}
```

**Comment by xmonader** [comment]
This is not an error, It backed up all of the items, and filtered out the volumes "on purpose"
