### ISSUE TITLE
Access log error: admin client

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2764]
Network: Testnet
3bot ID: <<please fill in your 3bot identity)

Description of what you were trying to achieve:
<<insert description>>

Detailed error message:
<<insert description or screen shot>>

**Comment by masteritua** [comment]
My steps:
1. Create 3Bot
2. Create new Pool
3. To try install Ubuntu 20.04
Nothing install
4. Then to try install Ubuntu 18.04 - Nothing install
5. Went to log and get this problem

PS:
Throuht default pool, also get error. 
Now when I try get page with Solutions Ubuntu, get empty page.

**Comment by masteritua** [comment]
Network: Testnet
3bot ID: masteritua.3botmain.grid.tf

Description of what you were trying to achieve:

My steps:
1. Create 3Bot
2. Create new Pool
3. To try install Ubuntu 20.04
Nothing not install
4. Then to try install Ubuntu 18.04 - Nothing not install
5. Went to log and get this problem

PS:
Throuht default pool, also get error. 
Now when I try get page with Solutions Ubuntu, get empty page.

Detailed error message:
https://drive.google.com/file/d/1AfXBKDhkzdIs2w_0SaHVcXqHG7Yp9YUE/view?usp=sharing

**Comment by xmonader** [comment]
- Please share the error in alerts view
- What does it mean (Nothing installs)? do you get an error in the chatflow, or what exactly?

**Comment by masteritua** [comment]
Send link and screens my account 3bot
https://drive.google.com/drive/folders/1zkzvWUXNAJrTAojKhEk_qWZ017zhL0d7?usp=sharing

**Comment by masteritua** [comment]
No errors on page Alerts

**Comment by masteritua** [comment]
All packages install and reload

**Comment by masteritua** [comment]
Page is empty when I try install some package (Ubuntu) etc

**Comment by xmonader** [comment]
@masteritua Hi. for the alerts you need to specify the application scope to see its alerts 

![image](https://user-images.githubusercontent.com/64129/111431129-0c3ee700-8704-11eb-8a5d-bfe65be21abe.png)

Just deployed ubuntu on a fresh 3bot 
![image](https://user-images.githubusercontent.com/64129/111431360-5b851780-8704-11eb-8b0a-bab68c9bfbeb.png)



can you check in developer tools (f12) what errors show up in the console and network tabs?

![image](https://user-images.githubusercontent.com/64129/111431533-9424f100-8704-11eb-8e76-e6489fd59b0b.png)

also please attach a screenshot for your current pools


Another thing the 3bot I just created has 3bot id of `1406` while yours 3bot you say is `1678` ?

my workloads info for that 3bot https://explorer.testnet.grid.tf/api/v1/reservations/workloads?customer_tid=1406&page=1 while for your 3bot there're 0 workloads https://explorer.testnet.grid.tf/api/v1/reservations/workloads?customer_tid=1678&page=1 too

**Comment by masteritua** [comment]
Attach link with screenshots and stack errors from console.
https://drive.google.com/drive/folders/12eCJjrisTK0xzcH8abYhp1diiJs2y1WO?usp=sharing
ADD:
That stack errors get when click this link: /admin/#/solutions/ubuntu

**Comment by masteritua** [comment]
Also I create new 3bot and get something problem.
![Screenshot_2021-03-18 3Bot Admin(3)](https://user-images.githubusercontent.com/33724112/111574038-61d2cc80-87b4-11eb-92f0-911868ce95cf.png)

**Comment by masteritua** [comment]
And also empty page, when click  /admin/#/solutions/ubuntu now.

**Comment by waleedhammam** [comment]
workloads ids:

Network Resource: https://explorer.grid.tf/api/v1/reservations/workloads/85143
Network Resource: https://explorer.grid.tf/api/v1/reservations/workloads/85146
Network Resource: https://explorer.grid.tf/api/v1/reservations/workloads/85147
Reverse Proxy: https://explorer.grid.tf/api/v1/reservations/workloads/85150
Network Resource: https://explorer.grid.tf/api/v1/reservations/workloads/85155
Network Resource: https://explorer.grid.tf/api/v1/reservations/workloads/85156
Network Resource: https://explorer.grid.tf/api/v1/reservations/workloads/85157
Subdomain: https://explorer.grid.tf/api/v1/reservations/workloads/85159
Reverse proxy: https://explorer.grid.tf/api/v1/reservations/workloads/85180
subdomain: https://explorer.grid.tf/api/v1/reservations/workloads/85181
Container: https://explorer.grid.tf/api/v1/reservations/workloads/85182
Domain Delegate: https://explorer.grid.tf/api/v1/reservations/workloads/85183

**Comment by masteritua** [comment]
Ок! But, I do not create system ubuntu and container from page "Solutions - Ubuntu" - empty page.
What to do?

**Comment by masteritua** [comment]
Today log console, when to go page create Ubuntu
[console-export-2021-3-19_6-59-50.txt](https://github.com/threefoldtech/js-sdk/files/6168731/console-export-2021-3-19_6-59-50.txt)

**Comment by masteritua** [comment]
What to do?

**Comment by xmonader** [comment]
I helped @masteritua offline, clicking reload on tfgrid solutions package was enough. also I noticed flaky network connection between me and the 3bot multiple times, I believe the node is a problem as well.
