### ISSUE TITLE
VDC backup start and expiry date do not make sense

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2765]
Network - testnet
3bot ID: weynandkuijpers
VDC name: vdctest
backup screen URL: https://weynandkuijpers-testbackup.vdctest.grid.tf/vdc_dashboard/#/settings

Name presented before and after doing a manual backup make no sense:
![screenshot_20210315_083018](https://user-images.githubusercontent.com/13766992/111103945-fcd76680-8568-11eb-9630-1c36e825bb25.png)
- start date is in the future
- expiration date is in the past:

**Comment by waleedhammam** [comment]
duplicate https://github.com/threefoldtech/js-sdk/issues/2752
