### ISSUE TITLE
Test backup and restore with marketplace apps

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#2769]
### Apps to be covered
- [x] Taiga
- [x] Cryptpad
- [x] Mattermost
- [x] Blog
- [x] Website
- [x] Wiki
- [x] Gitea
- [x] Peertube
- [x] ZeroCI
- [x] ETCD
- [x] Presearch
- [x] Discourse

### Test Steps
1- Deploy VDC
2- Deploy the app from VDC marketplace
3- Take a backup from VDC settings (this will create 2 backups (config and vdc))
4- Delete the app.
5- Restore the backups (config and vdc) that have been taken.
6- Wait about 5 mins, the app should be back.

**Comment by dmahmouali** [comment]
Taiga verified.

**Comment by mhost39** [comment]
Mattermost, Website, , Gitea, Peertube, ZeroCI, ETCD and Presearch verified

**Comment by xmonader** [comment]
We also need to test discourse

**Comment by AhmedHanafy725** [comment]
Discourse verified

**Comment by weynandkuijpers** [comment]
Test Steps conducted for issue verification


[] 1- Deploy VDC
[] 2- Deploy the app from VDC marketplace
[] 3- Take a backup from VDC settings (this will create 2 backups (config and vdc))
[] 4- Delete the app.
[] 5- Restore the backups (config and vdc) that have been taken.
[] 6- Wait about 5 mins, the app should be back.
