### ISSUE TITLE
Marketplace: Replace information

### ISSUE THREAD

**Issue by samtaggart** [threefoldtech/js-sdk#2770]
- [x] Please change Matic to Polygon

Image:
<img width="155" alt="logo-polygon" src="https://user-images.githubusercontent.com/50134479/111284840-90846200-8651-11eb-8690-6c4fd8a8d415.png">

Text:
Protocol and framework for building Ethereum-compatible blockchain networks.

- [x] Please move Commento to Decentralized We section
- [x] Please update Commento text to: "Commento lets you embed comments without giving up your privacy."

**Comment by waleedhammam** [comment]
![Screenshot from 2021-03-21 11-27-34](https://user-images.githubusercontent.com/10658229/111899976-84751780-8a38-11eb-9969-e17ff7b0f36f.png)

![Screenshot from 2021-03-21 11-27-59](https://user-images.githubusercontent.com/10658229/111899978-88089e80-8a38-11eb-8f20-02246257c557.png)

Verified
