### ISSUE TITLE
VDC: Create chatflow to add a storage node

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#2773]
Also, add a button in storage nodes to use this chatflow.

**Comment by waleedhammam** [comment]
verifying

**Comment by waleedhammam** [comment]
verified
![Screenshot from 2021-03-21 12-39-56](https://user-images.githubusercontent.com/10658229/111901768-8fcd4080-8a42-11eb-9ea1-bb4bf90f6d74.png)
