### ISSUE TITLE
VDC: Add delete action to storage nodes

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#2774]
Add delete action button to storage nodes in vdc dashboard

**Comment by ranatrk** [comment]
![Screenshot from 2021-03-17 17-44-47](https://user-images.githubusercontent.com/17128393/111495926-7ed1b600-8748-11eb-8d5c-ea256f7ceb7b.png)

**Comment by waleedhammam** [comment]
verified
![Screenshot from 2021-03-21 12-40-54](https://user-images.githubusercontent.com/10658229/111901790-b25f5980-8a42-11eb-9227-0133181455ba.png)
