### ISSUE TITLE
How do you add IPv4 IP'\s to a testnet Farm?

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2783]
Question:  Can you confirm what I need to do to add  IP addresses to a farm (in order to be able to run kubernetes clusters with controllers that need a public IP).

example:
- freefarm has IP's: https://explorer.testnet.grid.tf/api/v1/farms/1
- Vienna GEC farm has not: https://explorer.testnet.grid.tf/api/v1/farms/9

So in order to added IP's to the Vienna2 farm GE needs to:
- have a /24 (or smaller, /25. /26 all two way to 4 IP's /30) router to the inside of the farm network.
- then they go to their farm management 3bot (``` threebot_id: 451```)
- install the "farm management package"
- use the farm management package to add the network and specify the gateway.  Example shown below:
![screenshot_20210317_171304](https://user-images.githubusercontent.com/13766992/111579703-e848d780-87cf-11eb-96bf-2f689300365f.png)

Et presto, all done.

Can you confirm this is all that needs to happen?

**Comment by DylanVerstraete** [comment]
@weynandkuijpers yes, that is all! :)

**Comment by weynandkuijpers** [comment]
Thank you - this is enough for me to take it forward!
