### ISSUE TITLE
VDC: farm selection for extending kubernetes cluster

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#2786]

**Comment by AhmedHanafy725** [comment]
currently, we show any farm that has enough resources to deploy on it, but the price for these add-on nodes are fixed, so if these farms have different pricing what will be the criteria to filter them?

**Comment by waleedhammam** [comment]
Verified on testnet, development latest
![Screenshot from 2021-03-22 15-36-08](https://user-images.githubusercontent.com/10658229/111998127-61c02d00-8b24-11eb-8f95-981ec6fd4071.png)

![Screenshot from 2021-03-22 15-36-16](https://user-images.githubusercontent.com/10658229/111998115-608f0000-8b24-11eb-8d54-dd896e1b1a00.png)
