### ISSUE TITLE
As a user, I need to restore my backup from one item not two

### ISSUE THREAD

**Issue by MElborolossy** [threefoldtech/js-sdk#2789]
### Description

While I try the backup and restore, I found that to restore a backup, I have to restore `config_mybackup` and `vdc_mybackup`

It will be better if the user can restore `mybackup` and this restore both of them.

**Comment by xmonader** [comment]
I like that (y)

**Comment by ranatrk** [comment]
Unfortunately the backup is created with vdc and config in two different velero commands, and cannot be joined. This causes the backups created to be 2. In the case of automatic backups the backup is identified with timestamp and so the vdc and config are considered two different backups with nothing in common and cannot be joined.

**Comment by RafyAmgadBenjamin** [comment]
verifying it

**Comment by RafyAmgadBenjamin** [comment]
Fixed 
branch `development`
commit `a109e688ca55a4743455384358d7d1378685109d`

Now it is only one name that appears in the listing 
![image](https://user-images.githubusercontent.com/46320202/116406061-95335d00-a830-11eb-95f5-c242fe5d0296.png)
