### ISSUE TITLE
VDC: Reorder chatflow steps for marketplace apps

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#2791]
###  Deployment steps
- ask for domain 
- deploy the domain
- ask for chart's resources
- check the available resources
- in case of low resource, it will fail

### Suggest
I think it is better to check the resource at the beginning, then deploy the domain.

**Comment by dmahmouali** [comment]
and in case no resources we can check if the auto topup reach out the plan limits or not, and if not we can force topup the cluster and recheck.
