### ISSUE TITLE
As a user, I'd like to export 3bot state

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2793]
- Allow exporting the configurations (should we do full export or ignore the identity+stellar instances?)
- Allow exporting logs/alerts from the system (if easy)

**Comment by AhmedHanafy725** [comment]
**Verified** 
**Branch:** development
**Commit:** 72795defd8c1a0dfdf71f90ac6a312229b0db450

![image](https://user-images.githubusercontent.com/41957921/117577203-1c15ee80-b0e9-11eb-99f9-0e6f6751808a.png)
