### ISSUE TITLE
UX: Alerts tab for VDC

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2794]
for the VDC probably it's a good idea to allow showing alerts (vdc alerts)  in the VDC dashboard

**Comment by RafyAmgadBenjamin** [comment]
verifying

**Comment by RafyAmgadBenjamin** [comment]
### Verified
### branch 
`development`
### commit
a109e688ca55a4743455384358d7d1378685109d
![image](https://user-images.githubusercontent.com/46320202/116407383-0293bd80-a832-11eb-84d0-5817a01bd7b1.png)
![image](https://user-images.githubusercontent.com/46320202/116407445-12130680-a832-11eb-8f20-9653e3631ea3.png)
