### ISSUE TITLE
3Bot deployer: the start action gets an error

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/js-sdk#2796]
The `start` action gets an error, I expected that will restart my 3Bot or update it.

![image](https://user-images.githubusercontent.com/36021484/111899904-26483480-8a38-11eb-909f-df823bc45fa4.png)

![image](https://user-images.githubusercontent.com/36021484/111899918-3eb84f00-8a38-11eb-9679-ff931770d2ac.png)

suggestion:
- don't show the start action if the 3Bot is running

**Comment by ranatrk** [comment]
verified: start removed for running threebot
![Screenshot from 2021-04-04 11-25-12](https://user-images.githubusercontent.com/17128393/113504466-88c12a80-9538-11eb-8588-284d1a688cd8.png)
