### ISSUE TITLE
3Bot deployer: After stopping my 3Bot, the page reload and the 3Bot still with status RUNNING

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/js-sdk#2797]
After stoping my 3Bot, the page reloaded and I found the 3Bot still with the status `RUNNING` but after ~2 mins I reloaded the page again and the status changed to `STOPPED`

suggestion:
wait until the 3Bot stop before reloading the page.

**Comment by abom** [comment]
I'd the same problem, but after a quick refresh, it showed `ERROR` state (the 3bot itself is not accessible, but the deployed workload is).

**Comment by ranatrk** [comment]
couldn't verify, when stopping 3bot had to reload twice to see the stopped status

**Comment by ranatrk** [comment]
verified
