### ISSUE TITLE
Starting theeebot server on mac os raise exception

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#28]
while I was trying to execute threebot server on Mac OS it raises 
```
getProcessPid is only implemented for unix
```
![image](https://user-images.githubusercontent.com/46320202/85017988-b33e2480-b16c-11ea-9dca-f5980831e3c3.png)

This exception was raised from 
```
src/js-ng/jumpscale/sals/process/__init__.py", line 395, in get_pids
```
due to if condition related to Linux platform 
![image](https://user-images.githubusercontent.com/46320202/85018077-dff23c00-b16c-11ea-9fa5-3f3585deb57b.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
