### ISSUE TITLE
VDC farm price filter for extending kubernetes cluster

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2805]
currently, we show any farm that has enough resources to deploy on it, but the price for these add-on nodes are fixed, so if these farms have different pricing what will be the criteria to filter them?

_Originally posted by @AhmedHanafy725 in https://github.com/threefoldtech/js-sdk/issues/2786#issuecomment-801787251_

**Comment by xmonader** [comment]
Should we filter out all farms above certain price or totally up to the user?

**Comment by despiegk** [comment]
the price was not fixed? we said that all add on nodes are post billing mode?
