### ISSUE TITLE
Prompt user to send all remaining tokens to a wallet when deleting a VDC.

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2810]
Purpose: When deleting a VDC: It would be nice to have an option  "send remaining TFTs to your originating wallet" or "send remaining TFTs to your ThreeFold Connect wallet?" ... something like that, to make it more user-friendly.

Today that is a manual job, having a menu pop up in which you copy/paste the receiving wallet address for all remaining tokens.

Some thought needs to go into:
- what tokens are refundable (check the origin of the available tokens and take into account the monthly nature of the product).

**Comment by waleedhammam** [comment]
duplicate https://github.com/threefoldtech/js-sdk/issues/2809

**Comment by weynandkuijpers** [comment]
Issue solved as per #2809. I would ad a little pointer to the message that presents a wiki page on how to import a wallet into the ThreeFold Connect app.

**Comment by xmonader** [comment]
https://github.com/threefoldtech/js-sdk/commit/bc8e68676220f478892105cecffe26ec6d78f972
