### ISSUE TITLE
Extension of storage nodes systematically leads to timeouts

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2818]
I extended my VDC with storage capacity. I see the amount taken away from my balance quite immediately, but the VDC payment screen keeps on spinning, and gets a timeout. I had this a few times (and no successful try), so I imagine there is an issue. 

![image](https://user-images.githubusercontent.com/30384423/112159891-e7f27700-8be9-11eb-8360-3a5a100821d0.png)

In TF Connect app, money is returned (apart from the fee). 

Network: testnet
VDC: geertincubaid - vdcdiamondtest2

**Comment by waleedhammam** [comment]
@gmachtel Can you please add the vdc name and network ?

**Comment by gmachtel** [comment]
> @gmachtel Can you please add the vdc name and network ?

added

**Comment by waleedhammam** [comment]
@gmachtel it seems the transaction was done from TF connect wallet to the Deployer as here: https://stellar.expert/explorer/public/tx/148492184952664064#148492184952664065


But the payment service failed when trying to pay the explorer, that what caused the payment to drop and refund, and all retries were failed.

**Comment by gmachtel** [comment]
Why did it fail, that is the question ?

**Comment by waleedhammam** [comment]
@gmachtel Because of stellar service, it's kinda gets unstable most of the time, we've introduced retries, in that case it retries to pay 10 times and the 10 times were failing

**Comment by gmachtel** [comment]
Ok if that is the case I guess we can’t do anything about it. But I’m not sure, as I saw the amount debited from my wallet way before in the VDC it timed out. So problem sits in communication between stellar and the service then, not in the payment itself.
