### ISSUE TITLE
Update VDC dashboard gives error

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2821]
I don't have the buttons `Enable Quantum Storage` and `Add node` in an bit older VDC. Upgrade dashboard doesn't work. Is there a way to update this VDC or do I need to close ? 
For this one, I can close and relaunch a new one, but if later people have critical workloads running on it i guess, won't that be an issue ? 

VDC name: mysilver
3bot: geertincubaid

![image](https://user-images.githubusercontent.com/30384423/112285942-21c78a00-8c8b-11eb-8f63-0b825c1d55db.png)

Plus, in case of 'contact support', which support channel do we need to provide in the manual ?

**Comment by xmonader** [comment]
Let's fix with a manual update

**Comment by waleedhammam** [comment]
machine is updated

**Comment by gmachtel** [comment]
Great, that works. I have another one in the same situation: 
VDC name: geertvdctest
3bot: geertincubaid

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/112464622-637c3180-8d6c-11eb-8dae-0b9140cfd0b5.png)

Updating on latest works.
