### ISSUE TITLE
Test backup and restore with marketplace apps #2769

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#2828]
- [x] DigiByte
- [x] Matic

Test Steps
1- Deploy VDC
2- Deploy the app from VDC marketplace
3- Take a backup from VDC settings (this will create 2 backups (config and vdc))
4- Delete the app.
5- Restore the backups (config and vdc) that have been taken.
6- Wait about 5 mins, the app should be back.

**Comment by mhost39** [comment]
with devnet and vdc name: mostafa
i deployed a DigiByte and try to access it (worked fine)
then created a backup and deleted the DigiByte and restored it
and after more than an hour tried to access it and can't access it got "404 page not found"
https://posix-digibyte-test.webg2dev.grid.tf/

**Comment by mhost39** [comment]
same with Matic
![image](https://user-images.githubusercontent.com/31102305/113152926-e43ca100-9236-11eb-8217-ac77f3d6ad8c.png)

**Comment by xmonader** [comment]
@ashraffouda let's see what is wrong with these blockchain solutions and if they're correctly backed up or not

**Comment by ashraffouda** [comment]
will check with @mhost39

**Comment by mhost39** [comment]
Verified
