### ISSUE TITLE
Backup table shows "no vdc instances available"

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2829]
![image](https://user-images.githubusercontent.com/64129/112464937-c968b900-8d6c-11eb-947e-829de9d30424.png)

I guess that's because of copy&paste the table, we should show  something like "No backups yet" or something

**Comment by waleedhammam** [comment]
![Screenshot from 2021-03-31 16-32-41](https://user-images.githubusercontent.com/10658229/113161497-bb200e80-923e-11eb-8ad5-b8c74a7ddf9f.png)


Verified
