### ISSUE TITLE
apply a cache busting mechanism to vdc dashboard .js files

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/js-sdk#2838]
### Description
When a user update the vdc dashboard, some js changes may not get reflected in his browser and cause the dashboard to malfunction.

The user had to manually empty the browser cache or hard reload the page, but this could be not obvious for a regular user and could cause some confusion.

![image](https://user-images.githubusercontent.com/42457449/112759967-9c7b0700-8ff5-11eb-9ce2-67e8ba3911c4.jpeg)
### Implementation

I'm not a js expert, but I know there is already few approaches to implement some mechanism to force the browser to invalidate its caches and reload it without user interaction Which called Cache Busting.

This will definitely improve the user experience.

**Comment by waleedhammam** [comment]
- edited vue file, updated dashboard, works as expected
