### ISSUE TITLE
only show unique admins

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#284]
![image](https://user-images.githubusercontent.com/64129/88090463-ed487f00-cb8d-11ea-88e1-519e05e0d482.png)

**Comment by xmonader** [comment]
fixed in https://github.com/threefoldtech/js-sdk/commit/5c1b629dd73efc47fb737e74f8d37fabda42f561

**Comment by hossnys** [comment]
verified 
before :

![Screenshot from 2020-07-26 11-13-11](https://user-images.githubusercontent.com/26298009/88475653-4c154c00-cf32-11ea-9a64-6798e15036e6.png)

after it's fixed :

![Screenshot from 2020-07-26 11-26-10](https://user-images.githubusercontent.com/26298009/88475661-58010e00-cf32-11ea-99a2-3697e7e2331b.png)
