### ISSUE TITLE
In the backup information overview the naming is out of order

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2840]
![image](https://user-images.githubusercontent.com/13766992/112851657-3f965400-90bc-11eb-81c0-a763f67ecf77.png)

expiration: a month ago
starttimestamp:  in 6 minutes

**Comment by waleedhammam** [comment]
![Screenshot from 2021-03-31 16-33-42](https://user-images.githubusercontent.com/10658229/113161643-e3a80880-923e-11eb-9fe3-5b92e62f0ba7.png)


Verified
