### ISSUE TITLE
Where is my old cluster, installed Ubuntu 18.04?

### ISSUE THREAD

**Issue by masteritua** [threefoldtech/js-sdk#2841]
I bought 3bot masteritua (main net) to 30.03, date expired 23.03 for some reason.
Than, I paid 3bot(masteritua) to 6.04. And I got a new Admin panel, without my installed solution ubuntu 18.04 before
Question:
- Where is my old cluster with ip: 10.100.8.2?

**Comment by dmahmouali** [comment]
@masteritua 
please, can you update the issue with enough information: pool id, workload ids

**Comment by masteritua** [comment]
I also know current data. May be they are equal.
"wids" : 85765, 85764, 85763
"gateway_pool" :  1954
"compute_pool" : 1953

**Comment by masteritua** [comment]
Today (31.03) I got interesting alert, although will pay to 6.04. Where is 4 days?
![Screenshot from 2021-03-31 06-49-34](https://user-images.githubusercontent.com/33724112/113088445-402f0780-91ee-11eb-89f2-0eeb67f89740.png)

**Comment by xmonader** [comment]
@masteritua : From the 3bot deployer you provision a 3bot on a specific capacity pool with a network attached to it. If more solutions (other than the 3bot) get deployed on the pool it *will consume* more of the resources. if the 3bot pool reaches 0 capacity without extension, **your workloads will get deleted**.
