### ISSUE TITLE
Taiga: the login endpoint take ~2 min to work after the installation

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/js-sdk#2846]
Seems the backend container take much time to start so I have to wait for ~2:3 mins to login

**Comment by xmonader** [comment]
Can't we use a readiness probe for that?

**Comment by RafyAmgadBenjamin** [comment]
### fixed

### PR
https://github.com/threefoldtech/vdc-solutions-charts/pull/134
https://github.com/threefoldtech/js-sdk/pull/2872

**Comment by AhmedHanafy725** [comment]
**Verified**
**Branch:** development
**Commit:** 6c20a245a5ae2390f413256a05405425f8260cd1

login worked fine once the chatflow was finished.
