### ISSUE TITLE
deleting storage node redirects to compute nodes

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#2857]
after deleting a storage node it should redirect to storage nodes page not compute page

**Comment by RafyAmgadBenjamin** [comment]
verifiying this

**Comment by RafyAmgadBenjamin** [comment]
### Verified
### Branch 
`development`
### Commit
18f3c421b1e6d297060483663e16884d7d0c6257

![image](https://user-images.githubusercontent.com/46320202/116532260-565ce000-a8e0-11eb-8e54-e4475bc029cf.png)
![image](https://user-images.githubusercontent.com/46320202/116532320-65dc2900-a8e0-11eb-80b7-3b88845ebb4f.png)
