### ISSUE TITLE
VDC: Make compute farms configurable

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#2858]
Currently, if there is another farm will be added to be used as VDC capacity provider, this will need to change in the code
also, the docs need to be updated after this issue.

**Comment by xmonader** [comment]
I think I mislead you, for sure the storage needs to be configurable, but the farms the VDC deployer itself run on for (compute, storage, and the network should be configurable instead of having them hardcoded

**Comment by MElborolossy** [comment]
Verified on testnet
![choose_farms](https://user-images.githubusercontent.com/11272864/119019131-25327580-b99d-11eb-82f5-eb219548655e.gif)
