### ISSUE TITLE
Can't reach ETCD for quantum storage in VDC

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/js-sdk#2859]
I've hit the button in my VDC to enable quantum storage and download the config file. While attempting to run the latest quantum storage bootstrap against that config file, I encountered a hang. Some digging shows that the holdup is zstor running it's test.

So I tried accessing the ETCD instance with `etcdctl`:

```
etcdctl --endpoints=https://etcdqs-29108.webg1test.grid.tf:2379 --user=root:PASSWORD put test hello

{"level":"warn","ts":"2021-03-31T15:45:02.192-0700","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-6e07dcea-c654-46ba-a3ec-bfe72cec4014/etcdqs-29108.webg1test.grid.tf:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Error: context deadline exceeded
```

It seems that the ETCD instance created for my QSFS is not reachable. VDC at https://scott-kube.vdctest.grid.tf/

**Comment by AhmedHanafy725** [comment]
It is working with quantum storage, but etcd has some problems with authentication.

**Comment by MElborolossy** [comment]
This issue is related to the etcd issue with auth https://github.com/etcd-io/etcd/issues/8458

**Comment by scottyeager** [comment]
> It is working with quantum storage, but etcd has some problems with authentication.

It's actually *not* working with quantum storage. Running zstor using this config simply hangs.

> This issue is related to the etcd issue with auth etcd-io/etcd#8458

That's about etcds with Kubernetes, but aren't these QSFS etcds separate from the cluster's etcd?

I've opened an issue on the zstor repo for further tracking, as it seems that we might not be able to verify that the etcd is functioning properly with other tools due to issues with auth in etcd in general: https://github.com/threefoldtech/0-stor_v2/issues/41

**Comment by xmonader** [comment]
I'm closing this as zstor is moving towards 0-db
