### ISSUE TITLE
UX: Manual selection of VDC storage node farms fails cryptically

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/js-sdk#2861]
When selecting farms for VDC storage nodes manually, the error below may appear. It's not obvious for most users that this results from choosing the wrong farms. Can we make this error a bit more helpful, perhaps suggesting to retry with automatic selection?

![image](https://user-images.githubusercontent.com/17682591/113456581-6e654080-93c2-11eb-8681-7c7e1534afe9.png)

**Comment by xmonader** [comment]
the right balance here is always a problem because if we leak the underlying error from explorer it will be confusing for the user and can't possibly map all kinds of errors to also a human-relatable format except for -can't deploy zdb or kubernetes- with the fix merged
