### ISSUE TITLE
The button logout does not work into 3bot admin

### ISSUE THREAD

**Issue by masteritua** [threefoldtech/js-sdk#2871]
![Screenshot from 2021-04-06 07-03-47](https://user-images.githubusercontent.com/33724112/113657422-91d00a00-96a6-11eb-993b-204d6cc3ce6a.png)
Browser FF

**Comment by xmonader** [comment]
Thank you for reporting @masteritua. It's broken indeed

![image](https://user-images.githubusercontent.com/64129/113779732-71e42900-972e-11eb-98ef-8abc3ac07b76.png)

**Comment by RafyAmgadBenjamin** [comment]
I am verifying this

**Comment by RafyAmgadBenjamin** [comment]
verified
commit `38efdac6cacc5f6753659261c3c977fe1027ff5a`
branch `development`
![image](https://user-images.githubusercontent.com/46320202/116394648-7bd7e400-a823-11eb-91f3-b1d3d582e8db.png)
![image](https://user-images.githubusercontent.com/46320202/116394551-5c40bb80-a823-11eb-940b-8985a9c05563.png)
