### ISSUE TITLE
backup and restore test failed

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#2873]
3bot name: weynandkuijpers.3bot
vdc name: releasedtwodotsix

- Created a new VDC
- Launched a cryptpad instance
- Created a file and a folder (Hello)
- Deleted the cryptpad deployment
- restored the backup.  

![image](https://user-images.githubusercontent.com/13766992/113702690-e85f3780-96ea-11eb-935d-f7435071af25.png)

restore the vdc-backuptest that sais "Backed up MetadataOnly".

In the deployed solutions the cryptpad is back:

![image](https://user-images.githubusercontent.com/13766992/113702912-32481d80-96eb-11eb-9b91-2845992e3069.png)

![image](https://user-images.githubusercontent.com/13766992/113703146-7affd680-96eb-11eb-95e9-02b8fad54982.png)

New file and folder is not part of the restore.

Or is this not part of the backup functionality (as it sais metadata only.....).

**Comment by xmonader** [comment]
Indeed, that's is the expected behavior, we don't do volume backups at all as per kds request, only backing up the cluster configurations and deployments + domains related to vdcs
