### ISSUE TITLE
Implement VDC Promo codes to incentivize highly-engaged users with free capacity for limited time.

### ISSUE THREAD

**Issue by BenjellounO** [threefoldtech/js-sdk#2876]
### Context and why: 

As we're preparing for the Blockchain solutions launch for testing purposes ( starting with DigiBye, presearch and then Matic) , we want to implement an incentive campaign, where we incentivize 50 -100+ people from every Blockchain community with free VDCs for 2 or 3months so that they can deploy their Blockchain nodes and be involved in our community.  (offering it only to people who are willing to deploy stuff, via a selection process:  a form to fill, and a cross-community event along with each solution launch )

### Feature request: 

- A Prromo code structure that can configure a VDC to be deployed on certain free Farms, that will be free of all deployments for a limited amount of time. 
- Promo code to be inputted  during the first steps of vdc deployment ( could be after the vdc name) 
-  if no promo code inputted -> no free VDC and regular deployement
- If promo code inputted - > VDC to be deployed on a certain Farm that is free of charge 
Note: each blockchain node requires different vdc packages, but besides presearch, they all require platinum and above.

### Farms to be considered: 
- FreeFarm
- GreenEdge farms

### Some Questions

- How can we generate these Promo codes 
- how can these promo codes configure the vdc deployment to free farms? 
- what do the devs exactly need to implement this feature? 
- After approval by stakeholders, how long could this implementation take?

**Comment by xmonader** [comment]
as per KDS review, we won't be addressing that, it's fine to give people TFT to deploy on already discounted environments.
