### ISSUE TITLE
allow the user to have pool of ips they can set to their VDC

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2887]

**Comment by AhmedHanafy725** [comment]
- To have a public IP, it should be attached to a node which means if the VDC couldn't deploy the master VM on this node, it won't be able to use this public IP. And the only solution is removing this IP, and attaching it to another node. At this moment maybe someone else can take this IP.
- The VDC deployer creates a new identity for each VDC, how can use the IPs of another identity?  AFAIK there is no sharing in pools or workloads between users (identities)

**Comment by m-motawea** [comment]
### Proposal 1
- a single identity is created for each user
- all vdcs of the user are created using the user identity in separate pools (pool per farm for each vdc)
- workloads are distinguished using vdc uuid in workload description (same as now)
- public ips are reserved separately from vdcs and paid upfront (important)
- each public ip has its own pool
- will require atomic workload transfer between nodes (decomission and deploy the workload on a different node)
- pools can have a description field to help in filtering (optional)
