### ISSUE TITLE
VDC: Variable pricing for TFT compared to USD

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2898]
As TFT price has gone above 0.1 USD, we need variable pricing (coming from API coingecko/CMC/...) for reserving a VDC. 
If we keep fix price on mainnet, we will price ourselves out of the market (as prices on testnet are 1/10, not a high urgency, but best to have mechanism to be looked at for VDC reservation.

**Comment by xmonader** [comment]
Prices defined here https://github.com/threefoldfoundation/vdc_pricing/blob/master/prices.json can be changed accordingly -if needed-

**Comment by gmachtel** [comment]
Prices in the json file are a FIXED amount. Question is to have it dynamically changed, as fixed amount is in USD (which can't be specified in the json file).

**Comment by maximilianrang** [comment]
Chainlink will provide on-chain price oracles for Polkadot.

**Comment by despiegk** [comment]
prices in json is good enough, it not that our price changes that quickly, 10% is ok as variation
its good anyhow, if people don't want this variation they should buy more TFT in advance

**Comment by Sacha96** [comment]
Yeah but what if the price jumps to 0.2 or 0.5 we can't say we would be cheap anymore... I think going with USD standard price and TFT amounts are calculated automatically while keeping minimum tft value at 0.1 with an explanation

**Comment by samtaggart** [comment]
I agree with @gmachtel and @Sacha96 on need for variable pricing. @despiegk
