### ISSUE TITLE
in deploying minio/kubernets in marketplace it hangs a little before deployment

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#290]
![Screenshot from 2020-07-22 12-22-00](https://user-images.githubusercontent.com/10658229/88165408-f5e49800-cc15-11ea-840e-3e8d609d7e04.png)

after this screen it was hanging a bit in copying networks

**Comment by waleedhammam** [comment]
fixed in: https://github.com/threefoldtech/js-sdk/pull/269/files/20266063add01216377730bc57193557ddaea7b2..5d697656646d30b782aae9d1a912646698652dbc

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
