### ISSUE TITLE
as a VDC owner I want to allow other people to manage my VDC

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2903]
a typical scenario I can buy VDC for my company and would like to give one or more people access to manage / deploy solutions from marketplace or even extending the VDC.

A suggestion is having Admins or Settings tab in the VDC to add more admins there

**Comment by RafyAmgadBenjamin** [comment]
### Fixed 
### Branch 
`development_vdc_admins`

we have implemented it 
#### first approach
we have updated the admins list in the `j.core.identity.me.admins` but we find this is insecure 
#### Second approach 
we have updated the admins of the package, this is the one we used

**Comment by AhmedHanafy725** [comment]
**Verified**
**Branch:** development
**Commit:** 6c20a245a5ae2390f413256a05405425f8260cd1

Added Waleed as admin
![image](https://user-images.githubusercontent.com/41957921/117577433-0ead3400-b0ea-11eb-937c-684c23763504.png)

Waleed could login in my VDC
![image](https://user-images.githubusercontent.com/41957921/117577412-f5a48300-b0e9-11eb-8d3a-fe510a4e9f99.png)
