### ISSUE TITLE
Add service in vdc deployer for checking the vdc health

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#2907]
This service should check the following
- [x] threebot containers are alive (will need update dashboard)
- [x] public IPs are reachable
- [x] ipv4 units

**Comment by RafyAmgadBenjamin** [comment]
verifying this

**Comment by RafyAmgadBenjamin** [comment]
couldn't be verified due to this issue 
https://github.com/threefoldtech/js-sdk/issues/3024

**Comment by RafyAmgadBenjamin** [comment]
### Verified 
### Branch
`development`
### Comment
18f3c421b1e6d297060483663e16884d7d0c6257
![image](https://user-images.githubusercontent.com/46320202/116528853-928e4180-a8dc-11eb-9a81-f88bbdb93cf9.png)
![image](https://user-images.githubusercontent.com/46320202/116528893-9fab3080-a8dc-11eb-9805-565d28cb8101.png)
