### ISSUE TITLE
prepare a fully automated integration test

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/js-sdk#2909]
### Description

currently we don't have a fully automated integration tests for vdc's, we need to have tests that tests deploying vdc on an environment like testnet for example, and hopefully test deploying solutions on it

**Comment by ashraffouda** [comment]
it is already the case now

**Comment by AhmedHanafy725** [comment]
vdc dashboard tests are [here](https://github.com/threefoldtech/js-sdk/blob/development/tests/sals/automated_chatflows/test_vdc_dashboard.py)
marketplace apps that need to be covered
- [ ] Owncloud
- [ ] Presearch
- [ ] Polygon
- [ ] Mastodon
