### ISSUE TITLE
VDC: Cleanup after solution failure

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/js-sdk#2914]
- In the VDC solutions chatflow, if the deployment failed we should remove:
  1. the Kubernetes `namespace`
  2. the `subdomain` workload

**Comment by RafyAmgadBenjamin** [comment]
verifying this

**Comment by mhost39** [comment]
verifying...

**Comment by mhost39** [comment]
Verified 
branch: development
commit: 2bebdb21a2764becdc26bf282da3e43d071c376f

steps:
try to deploy cryptpad with invalid value 
then when deployed fail check that workload deleted
and check namespace by 
```kubectl get ns```
was deleted

**Comment by sameh-farouk** [comment]
I tried to deploy mastodon on a fresh created VDC, the deployment failed with that error

![Screenshot from 2021-05-31 14-01-25](https://user-images.githubusercontent.com/42457449/120215704-54b36e80-c236-11eb-9465-b99c3f05337e.png)

checking that, the deployment wasn't listed on the deployed solution but the release was deleted
```sh
root@zosv2-04:~# helm list -A
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/.kube/config
NAME   	NAMESPACE  	REVISION	UPDATED                                STATUS  	CHART         	APP VERSION
traefik	kube-system	1       	2021-05-31 10:13:16.576998671 +0000 UTCdeployed	traefik-9.19.1	2.4.8 
```
but the namespace left uncleared.

```sh
root@zosv2-04:~# kubectl get namespaces 
NAME                       STATUS   AGE
default                    Active   5h26m
kube-system                Active   5h26m
kube-public                Active   5h26m
kube-node-lease            Active   5h26m
k3os-system                Active   5h25m
velero                     Active   5h22m
mastodon-verify3105masto   Active   3h46m
```

describing that name space shown this details

```sh
root@zosv2-04:~# kubectl -n mastodon-verify3105masto get events --sort-by='{.lastTimestamp}'
LAST SEEN   TYPE      REASON             OBJECT                            MESSAGE
26m         Warning   FailedScheduling   pod/mastodon-post-install-74fgk   persistentvolumeclaim "verify3105masto-mastodon-web-assets" not found
```
