### ISSUE TITLE
VDC: Creating a backup doesn't update the backup table

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#2921]
After creating a backup, the page should be reloaded manually to see that the backup has been created. Although deleting backup removes the entry from the table.

**Comment by RafyAmgadBenjamin** [comment]
Verifiying this

**Comment by RafyAmgadBenjamin** [comment]
### Fixed
### Branch
`development`
### Commit
a109e688ca55a4743455384358d7d1378685109d

![image](https://user-images.githubusercontent.com/46320202/116411180-c2363e80-a835-11eb-9607-c935d1b642d7.png)
![image](https://user-images.githubusercontent.com/46320202/116411236-cf532d80-a835-11eb-95bc-63f2d3b2c5d3.png)
![image](https://user-images.githubusercontent.com/46320202/116411289-dd08b300-a835-11eb-8c7f-2870760a555d.png)
