### ISSUE TITLE
VDC deployment takes eternally

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2933]
VDC deployment gets stuck, takes eternally to deploy (way longer than 10', all steps seem to take several minutes). Trying to deploy a platinum VDC.

![image](https://user-images.githubusercontent.com/30384423/114854359-07458400-9de5-11eb-9024-af8133bfef3a.png)

* OS: MacOS Big Sur
* Browser: Chrome 88
* 3bot: geertincubaid, deploying a platinum vdc

**Comment by gmachtel** [comment]
Finally had an error 
![image](https://user-images.githubusercontent.com/30384423/114863846-93a97400-9df0-11eb-8968-bcd841f0abe7.png)

**Comment by xmonader** [comment]
issue was caused by hanging containers/ip reservation, please open a new one if that happens again
