### ISSUE TITLE
Can't create new VDC

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/js-sdk#2946]
After payment I get this message:
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/18591016/114904075-bef38980-9e17-11eb-960c-8d55a28f459e.png">
3bot name: andreaspow
VDC uuid: c7dc6baaafe944c69079f230a5c83318

**Comment by andhartl** [comment]
retried and had to pay again. then it say forever in this state: 
![Uploading image.png…]()

**Comment by andhartl** [comment]
got this message at the end
<img width="935" alt="image" src="https://user-images.githubusercontent.com/18591016/114909959-9b334200-9e1d-11eb-9224-ae9315db3686.png">

**Comment by joris19755** [comment]
When trying to deploy gold package VDC, with automatic node selection, I receive also below message
![image](https://user-images.githubusercontent.com/44951133/114930416-46032a80-9e35-11eb-88fe-21bd7e3fe5df.png)
joris.3bot
vdc uuuid: cd5156c8a30c49ec84e5ba83b88a2df9

**Comment by joris19755** [comment]
tried to deploy again, and after paying it kept waiting for couple of minutes, and then I received a payment timeout.

And I didn't get my TFT's refunded!
So I guess this non-happy path might need some finetuning.

Sorry no screen shot
joris.3bot
VDCname: jorisv1

**Comment by xmonader** [comment]
don't think this issue is valid anymore on testnet.
