### ISSUE TITLE
Considering Increase default pod initialization timeout

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/js-sdk#2951]
### Description

Now after a recently vdc chatflow fix, solutions will timeout **as expected** when its deployment time exceeded the default timeout specified in the chatflow sal if the solution didn't override that explicitly.

But it appears that the default ’pod_initialization_timeout’ value needs to reconsider as it is a bit low as 120sec.

More reasonable value would be about 600sec, and the default ’timeout’ value also need to change accordingly to ~800sec.
Note that the chatflow will stop waiting as soon as the deployment becomes ready.

**Comment by RafyAmgadBenjamin** [comment]
#### fixed
#### Branch
`development_chatflow_envvars`
#### PR
https://github.com/threefoldtech/js-sdk/pull/2966

**Comment by MElborolossy** [comment]
Verified
