### ISSUE TITLE
VDC Successfully created but not shown  on the list

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#2956]
a brand new VDC set, and 15 TFT sent, and was able to get all the way to finish, but not shown on theaccount's vdc list.
You can find the 15 TFT transaction below:
https://stellar.expert/explorer/public/account/GBBS7DOXWDZREDFBYFT5SVLMKIKPYZFDHCETZIK7S2JKHJJOJGQJN5ZR

 controller public IP was 185.206.122.17
 
 might give the 3bot ID if necessary

**Comment by xmonader** [comment]
please Add the 3bot ID and the vdc name to the issue

**Comment by xmonader** [comment]
duplicate  of https://github.com/threefoldtech/js-sdk/issues/2952
