### ISSUE TITLE
velero is failing to take backup

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2959]
From the logs, it seems there's a problem in access key/secret used?

after some investigation @AhmedHanafy725 found killing velero and starting it over again fixed it?

**Comment by despiegk** [comment]
how to make this reliable?

**Comment by AhmedHanafy725** [comment]
> after some investigation @AhmedHanafy725 found killing velero and starting it over again fixed it?

yes, but today couldn't reproduce
just 2 VDCs and worked fine

![image](https://user-images.githubusercontent.com/41957921/115140936-0a857d80-a03a-11eb-8c74-b2be2d84552a.png)

**Comment by xmonader** [comment]
it's happening again on a fresh VDC on devnet https://ahmedthabet-xmonapri280.vdcdev.grid.tf/
![image](https://user-images.githubusercontent.com/64129/116395909-ff460500-a824-11eb-8d1e-39926c0cb178.png)

**Comment by AhmedHanafy725** [comment]
There was a problem with user permission caused by `rstrip`, devnet VDC deployer is updated with this change.

**Comment by RafyAmgadBenjamin** [comment]
Verifying this

**Comment by RafyAmgadBenjamin** [comment]
Before taking a new backup 
![image](https://user-images.githubusercontent.com/46320202/117125682-27d87c80-ad9a-11eb-9e2e-6a72227a8ef7.png)
After taking a new backup 
![image](https://user-images.githubusercontent.com/46320202/117125832-57878480-ad9a-11eb-9e47-78804276555d.png)

### Verified 
### Branch 
`development`
### Commit ID
f6a2ee66c95481b450853c899dc3ac8e0ed918d4
