### ISSUE TITLE
Threebot server tests are failing

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#2962]
### Description

- It makes it hard to review PRs https://github.com/threefoldtech/js-sdk/pull/2960/checks?check_run_id=2373672629
- It runs once and fails another

**Comment by mhost39** [comment]
make these tests run nightly?

**Comment by mhost39** [comment]
i checked this the problem come from gevent 
we use gevent==1.4 and it not compatible with Python 3.8
we need to use gevent >= 1.5a2

**Comment by xmonader** [comment]
this one should be in verification now with gevent fixes of @abom

**Comment by mhost39** [comment]
Verified
https://github.com/threefoldtech/js-sdk/pull/3003 
![image](https://user-images.githubusercontent.com/31102305/118977839-e689c480-b976-11eb-90f0-6d89b230324b.png)
