### ISSUE TITLE
VDC: service to add network quota on the VDCs on testnet

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2968]
can be from the deployer or from the 3bot, preferably the deployer

**Comment by AhmedHanafy725** [comment]
After some investigation for limiting the network speed, found that the following commands drop the speed to 4Mbit/s, not 2Mbit/s
```bash
sudo tc qdisc add dev eth0 handle 1: root htb default 11
sudo tc class add dev eth0 parent 1: classid 1:1 htb rate 2mbit
sudo tc class add dev eth0 parent 1:1 classid 1:11 htb rate 2mbit
sudo tc qdisc add dev eth0 parent 1:11 handle 10: netem delay 500ms
```
Also, for https://gist.github.com/magnific0/e2a3ee492dda58f07df5984aacbea5e5, it needs `ifb0` module which not found in the k8s VM
@delandtj can you check this, and if there is a better solution to limit the speed?
