### ISSUE TITLE
Fix Node Deployment Capacity Allocation Problem #38

### ISSUE THREAD

**Issue by maximilianrang** [threefoldtech/js-sdk#2971]
### Description

When deploying a Digibyte node, the process fails unless you select at least Platinum. We should disable the lower packages so the process runs smoothly for everyone.

### Version information

currently live on testnet vdc marketplace

### Installation method

Better to specify the installation method

**Comment by MElborolossy** [comment]
Verified
Branch: development
Commit: 651486a10b2d2b1eeb64dfe580e8104989604ca8
Digibyte shows only gold and platinum flavors with the needed capacity to run smoothly
![image](https://user-images.githubusercontent.com/11272864/119015324-19dd4b00-b999-11eb-9149-852c0be89c38.png)
