### ISSUE TITLE
User reports blank screen in his VDC

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#2980]
User reports a blank screen in his VDC (same user and same VDC as the one mentioned in #2952 ). 

“When I log in to my account and I click "Go to My VDC" I then just get a blank page. I also cannot get into the Marketplace, clicking that button does nothing.”

![image](https://user-images.githubusercontent.com/30384423/115513752-ba016080-a283-11eb-8d4f-a548801674ea.png)

IP reserved: 185.206.122.17
3bot ID: sgherzi.3bot

**Comment by xmonader** [comment]
please make sure to add all of the vdc relevant information

**Comment by gmachtel** [comment]
3Bot ID added, no more info received. What else is needed ?

**Comment by xmonader** [comment]
@gmachtel e.g your 3bot Id linked to all of these VDCs
![image](https://user-images.githubusercontent.com/64129/115531590-3d777d80-a295-11eb-9e4c-30114a28a7f2.png)

 I can't guess around for every bug report, please make sure 3bot id and VDC name are always attached to any bug report
