### ISSUE TITLE
re-enable adding worker nodes with public IPs in chatflow and the rest API

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2985]

**Comment by MElborolossy** [comment]
Verified on devnet
commit 77a358016ac1f071ae21cefcd3ab895a8529c9ec
-From Chatflow
![image](https://user-images.githubusercontent.com/11272864/117823699-0d0c7900-b26e-11eb-8a69-ad570f1e4a63.png)
![image](https://user-images.githubusercontent.com/11272864/117824104-79877800-b26e-11eb-8536-b56b0dc0fd3c.png)
