### ISSUE TITLE
allow choosing SSD/HDD for ZDB nodes addons in chatflow + rest API

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2986]

**Comment by RafyAmgadBenjamin** [comment]
Verifying this

**Comment by RafyAmgadBenjamin** [comment]
### Verified 
### Branch 
`development`
### Commit
18f3c421b1e6d297060483663e16884d7d0c6257

![image](https://user-images.githubusercontent.com/46320202/116533764-0da62680-a8e2-11eb-9654-521693228096.png)
