### ISSUE TITLE
enable backup status info in the rest API

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2987]

**Comment by AhmedHanafy725** [comment]
**Verified**
**Branch:** development
**Commit:** 6c20a245a5ae2390f413256a05405425f8260cd1

![image](https://user-images.githubusercontent.com/41957921/117643615-e1639300-b188-11eb-9f95-645acb7d53ac.png)

![image](https://user-images.githubusercontent.com/41957921/117643575-d872c180-b188-11eb-8283-991edba2132a.png)
