### ISSUE TITLE
Add link to contact threefold support in VDC deployer and in the VDC controller

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#2994]

**Comment by hossnys** [comment]
Support page link https://support.grid.tf/

**Comment by sameh-farouk** [comment]
verifying this...

**Comment by sameh-farouk** [comment]
@xmonader  @samaradel this link to support added to threebot dashboard and to VDC Controller as this PR #3134. but I think this should be added to the VDC Deployer as well as mentioned in the issue but I can't spot the button there.
commit f0c115eb251c0273eab357b282242804d691ff61
![Screenshot from 2021-05-31 13-00-45](https://user-images.githubusercontent.com/42457449/120183668-481c1f80-c210-11eb-8c5f-92dfa708b177.png)

**Comment by sameh-farouk** [comment]
**verfied**
**commit b308cdf18af6a4d751440b44b7ff86dd8d9fa4ab**
