### ISSUE TITLE
Admin: solutions' info links are broken 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#2998]
what is the right info link for the solutions?
- Some of them have endpoints to `solution_<solution_name>`
https://manual.threefold.io/#/solution_network
https://manual.threefold.io/#/solution_ubuntu
https://manual.threefold.io/#/solution_kubernetes
https://manual.threefold.io/#/solution_storage
https://manual.threefold.io/#/solution_container
https://manual.threefold.io/#/solution_expose

- The others have endpoints to `<solution_name>`
https://manual.threefold.io/#/delegate_domain
https://manual.threefold.io/#/four_to_six_gateway
https://manual.threefold.io/#/monitoring

### Can we unify the info links and provide the right ones to update the Admin solutions' info links?

![image](https://user-images.githubusercontent.com/41957921/115798515-b6cab980-a3d6-11eb-8cd1-272ed775de31.png)

**Also, etcd info link is not found.**

**Comment by gmachtel** [comment]
OK, files in https://github.com/threefoldfoundation/info_sdk/tree/development/src/3bot_sysadmin/chatflows/solutions updated so that all start with solutions_

About url to be used (https://sdk.threefold.io/#/ vs. https://manual.threefold.io/#/, best to check with @Hamdy

**Comment by sasha-astiadi** [comment]
@AhmedHanafy725 please replace the links. we no longer use manua;.threefold.io

ALL sdk solution links live here https://wiki.threefold.io/info/sdk#/sdk__solution_chatflows

https://wiki.threefold.io/info/sdk#/sdk__solution_chatflows
https://wiki.threefold.io/info/sdk#/sdk__solution_network
https://wiki.threefold.io/info/sdk#/sdk__solution_container
