### ISSUE TITLE
Starting threebot server on OSX OS through timeout exception

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#30]
Starting threebot server on OSX OS
```bash 
server = j.servers.threebot.get("chats")
server.start() 

```
#### throw the below execption

![image](https://user-images.githubusercontent.com/46320202/85025931-5183b780-b178-11ea-8333-fb83a79e61ae.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
