### ISSUE TITLE
Profile VDC and 3Bot deployer

### ISSUE THREAD

**Issue by abom** [threefoldtech/js-sdk#3006]
Get some insights about where the time is consumed and what affects the performance.

**Comment by xmonader** [comment]
According to the profiling we managed to identify some of the points that improved the deployments

- creation of stellar wallets
- creation of the capacity pools and waiting on reservations https://github.com/threefoldtech/js-sdk/pull/3085/files
- load_info calls 
- some of the in-process calls that are blocking e.g checking VDCs health
