### ISSUE TITLE
improve stellar payments flow

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#3010]
TODO @robvanmieghem will spec what needs to be executed

**Comment by robvanmieghem** [comment]
https://github.com/threefoldfoundation/tft-stellar/tree/master/ThreeBotPackages/transactionfunding_service#actors
Use the second option to get a transaction funded (sending a signed transaction that gets feebumped)

**Comment by robvanmieghem** [comment]
https://github.com/threefoldfoundation/tft-stellar/releases/tag/v1.4.1
