### ISSUE TITLE
k3s.io/hostname and flannel.alpha.coreos.com/public-ip aren't always set

### ISSUE THREAD

**Issue by abdulgig** [threefoldtech/js-sdk#3013]
### Description

We are trying to add one "BIG" worker node to our VDC under the silver package. The node gets added successfully to the cluster. However, any deployments seem to be failing after that due to issues with auto extending the cluster. 

### VDC Information

VDC name = rudy2
3bot name = mazraa.3bot

### Steps to reproduce the error

1. Deploy a new VDC under "Silver" plan
2. Delete the default worker node that comes along with the plan (2 vCPU / 4GB Mem)
3. Add a new "BIG" worker node in the same farm without any public IP (8 vCPU / 32GB Mem)
4. Once the new worker node is added, try to deploy any solution from the marketplace (cryptpad, Digibyte)
5. The chatflow fails due to an exception raised

### Traceback/Logs/Alerts

![image](https://user-images.githubusercontent.com/25789764/116290208-49d36d00-a7a4-11eb-91e4-b3b24aec91a6.png)

![image](https://user-images.githubusercontent.com/25789764/116287540-98333c80-a7a1-11eb-8b5e-160853660f97.png)

![image](https://user-images.githubusercontent.com/25789764/116288069-2e676280-a7a2-11eb-9e28-c6be0798e948.png)

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/116296993-235d0400-a79b-11eb-9a1c-6655378c9e11.png)

looks like "k3s.io/hostname" wasn't set on the nodes for some reason?  I don't find a reason not to use `kubernetes.io/hostname` instead.

**Comment by abdulgig** [comment]
@xmonader , thanks for taking a quick look. I have just verified by updating the dashboard, the hostname error seems to be fixed. However, it seems to be failing here now,

```
Traceback (most recent call last):
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 148, in wrapper
    getattr(self, step_name)()
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 676, in wrapper
    return func(*args, **kwargs)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py", line 396, in choose_flavor
    self._validate_resource_limits(cpu, memory, no_nodes)
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/sals/solutions_chatflow.py", line 105, in _validate_resource_limits
    if not monitor.check_deployment_resources(queries):
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/vdc/kubernetes_auto_extend.py", line 238, in check_deployment_resources
    node_reservations = self.fetch_resource_reservations()
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/vdc/kubernetes_auto_extend.py", line 216, in fetch_resource_reservations
    if node_name not in self.node_stats:
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/vdc/kubernetes_auto_extend.py", line 68, in node_stats
    self.update_stats()
  File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/vdc/kubernetes_auto_extend.py", line 98, in update_stats
    node_ip = node["metadata"]["annotations"]["flannel.alpha.coreos.com/public-ip"]
KeyError: 'flannel.alpha.coreos.com/public-ip'

```

![image](https://user-images.githubusercontent.com/25789764/116302186-efd9a400-a7b1-11eb-9221-92fea19ec6c0.png)

**Comment by abdulgig** [comment]
@AhmedHanafy725 , as discussed with you already, there seems to be an issue. Traceback is below

```
[-] start: Traceback (most recent call last):
[-] start:   File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
[-] start:   File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/services/k8s_auto_extend.py", line 13, in job
[-] start:     monitor.update_stats()
[-] start:   File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/vdc/kubernetes_auto_extend.py", line 103, in update_stats
[-] start:     self._node_stats[node_name]["wid"] = ip_to_wid.get(node_ip)
[-] start: KeyError: 'k3os-20541'
[-] start: 2021-04-28T16:07:44Z <Greenlet at 0x7effeac749d0: <bound method KubernetesAutoExtend.job of <k8s_auto_extend.KubernetesAutoExtend object at 0x7effeac40d00>>> failed with KeyError
[-] start:

```

**Comment by AhmedHanafy725** [comment]
> @AhmedHanafy725 , as discussed with you already, there seems to be an issue. Traceback is below
> 
> ```
> [-] start: Traceback (most recent call last):
> [-] start:   File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
> [-] start:   File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/services/k8s_auto_extend.py", line 13, in job
> [-] start:     monitor.update_stats()
> [-] start:   File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/sals/vdc/kubernetes_auto_extend.py", line 103, in update_stats
> [-] start:     self._node_stats[node_name]["wid"] = ip_to_wid.get(node_ip)
> [-] start: KeyError: 'k3os-20541'
> [-] start: 2021-04-28T16:07:44Z <Greenlet at 0x7effeac749d0: <bound method KubernetesAutoExtend.job of <k8s_auto_extend.KubernetesAutoExtend object at 0x7effeac40d00>>> failed with KeyError
> [-] start:
> ```

The VDC controller wasn't updated to the latest code and it should work fine after the update

**Comment by abdulgig** [comment]
Yes, it worked as expected. Thank you
