### ISSUE TITLE
Validate and use the new backup servers with vdc

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#3016]
- We have new reliable backup servers needs to be validated and used with vdc & 3bot deployments instead of the current ones

**Comment by waleedhammam** [comment]
- VDC devnet now is on the new backup server

**Comment by waleedhammam** [comment]
After verification.

- [ ] Vdc testnet
- [ ] 3Bot deployer

**Comment by RafyAmgadBenjamin** [comment]
Verifying this

**Comment by RafyAmgadBenjamin** [comment]
- [ ] Create a new VDC on `devnet` and take a backup 
     - Created new vdc
     - Deploy a solution ex. Cryptpad 
     - Create a backup for VDC
     - Delete Cryptpad
     - Restore the backup and I got the cryptpad back running
![image](https://user-images.githubusercontent.com/46320202/117135101-c539ad80-ada6-11eb-9db9-8b5e4686688e.png)

- [ ] Create a new VDC on `testnet` and take a backup
