### ISSUE TITLE
Failed to install local 3bot with ModuleNotFoundError

### ISSUE THREAD

**Issue by friedger** [threefoldtech/js-sdk#3036]
### Description

Following the installation documentation for a local 3bot results in this error:
```
 $ poetry install
Creating virtualenv js-sdk-IALVdHpJ-py3.8 in /home/friedger/.cache/pypoetry/virtualenvs

  ModuleNotFoundError

  No module named 'virtualenv.seed.via_app_data'

  at <frozen importlib._bootstrap>:973 in _find_and_load_unlocked
```

### Version information

* OS: Ubuntu 20.04 LTS
* Project commit/version:  branch development, commit 36cd24d8c2dd1b53e5993a3ce5a845b51b51f0b5

### Installation method

via command line

### Steps to reproduce

Steps to reproduce:
1. open https://threefold.io/info/sdk#/sdk__3bot
2. follow link for local 3bot installation to https://threefoldtech.github.io/js-sdk/wiki/#/./quick_start
3. `sudo apt-get update`
4. `sudo apt-get install -y git python3-venv python3-pip redis-server tmux nginx`
5. `pip3 install poetry`
6. `git clone https://github.com/threefoldtech/js-sdk`
7. `cd js-sdk`
8. `poetry install`
9. See error message above.

### Traceback/Logs/Alerts
```
$ poetry install
Creating virtualenv js-sdk-IALVdHpJ-py3.8 in /home/friedger/.cache/pypoetry/virtualenvs

  ModuleNotFoundError

  No module named 'virtualenv.seed.via_app_data'

  at <frozen importlib._bootstrap>:973 in _find_and_load_unlocked

```

**Comment by scottyeager** [comment]
Some ideas on resolving this here: https://github.com/python-poetry/poetry/issues/2972#issuecomment-700298898

**Comment by abom** [comment]
I tried the same steps on a fresh ubuntu 20.04 container, but couldn't reproduce the same error and the installation was successful.

See https://github.com/pypa/virtualenv/issues/1873 for more information about possible root cause of having a broken `virtualenv` installation, can you also please tell us what's the output of `python3 -m virtualenv --version` it should show current version and its location.

```
virtualenv 20.4.6 from /usr/local/lib/python3.8/dist-packages/virtualenv/__init__.py
```

**Comment by friedger** [comment]
`virtualenv 20.4.4 from /home/friedger/.local/lib/python3.8/site-packages/virtualenv/__init__.py`

After pip3 uninstall virtualenv I got:

`virtualenv 20.0.17 from /usr/lib/python3/dist-packages/virtualenv/__init__.py`

After `apt remove python3-virtualenv` virtualenv is uninstalled and I could run `poetry install`.
