### ISSUE TITLE
Update VDC doesn't work

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#3037]
VDC still running well, but update of the dashboard doesn't work correctly it seems. 

3bot: geertincubaid
vdc: secondsilvernode

I saw with another 3Bot that there were new features such as add an admin etc, not available yet on this one so I wanted to update. But not possible, as the message says. 

![image](https://user-images.githubusercontent.com/30384423/116562394-66d28200-a903-11eb-92e5-0dc745f55fc1.png)

**Comment by dmahmouali** [comment]
Solved in this PR: https://github.com/threefoldtech/js-sdk/pull/3075
