### ISSUE TITLE
Strange behaviour on a running VDC

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#3041]
VDC was running since a long time, but workload on it disconnected. 

I can get to MY VDC, but 
- no kuberneters cluster shown

![image](https://user-images.githubusercontent.com/30384423/116654373-4ea54600-a989-11eb-97a2-8338870d6ce4.png)

- it seems I'm disconnected ('login' indicated instead of my 3bot id and no access possible)

![image](https://user-images.githubusercontent.com/30384423/116654530-9f1ca380-a989-11eb-98b3-6019f0781e65.png)

- in the marketplace I can't see my deployed workloads (button doesn't react, and in detail no button anymore)

![image](https://user-images.githubusercontent.com/30384423/116654265-169e0300-a989-11eb-82a5-2b3ef14dfb6e.png)

- no access to Alerts (but I couldn't upgrade already before)
- Download Kubeconfig file doesn't start

3bot: geertincubaid
VDC: secondsilvernode

**Comment by xmonader** [comment]
it's expired and its workloads are deleted and its walled don't have enough money even
![image](https://user-images.githubusercontent.com/64129/116833272-a1b11000-abb8-11eb-877d-a23180e4c9e6.png)

**Comment by gmachtel** [comment]
I transferred money elsewhere after the problems were detected, there was money on it when it was disconnected. That amount of tokens didn't even decrease.
