### ISSUE TITLE
create a service to monitor VDCs

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/js-sdk#3044]
for every vdc check Pools status, Reachable public ip, Workloads deployed and 3bot reachable
and send a telegram message with status

**Comment by xmonader** [comment]
the service already exists https://github.com/threefoldtech/js-sdk/blob/2a0ca8e9cb7caf66b830616a0bf86b7b0acad5c7/jumpscale/packages/vdc/services/check_health_service.py make sure to dump into MAIL_QUEUE and TELEGRAM_QUEUE and support that in the notifier service  https://github.com/threefoldtech/js-sdk/blob/fd153479aca24db8ff1b2c978b2a12c1fb36b1ac/jumpscale/packages/admin/services/notifier.py
