### ISSUE TITLE
wrong redirection while deploying new solution on VDC

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#3045]
### Description

Every time I try to deploy a solution, I got redirected to authenticate myself, then after that, I got redirected again to authenticate myself, and so on.

![image](https://user-images.githubusercontent.com/46320202/116991329-acf95e00-acd4-11eb-93e8-64ab099551e1.png)
![image](https://user-images.githubusercontent.com/46320202/116991272-98b56100-acd4-11eb-8f66-eebb78b2fe12.png)

**Comment by waleedhammam** [comment]
vdc devnet machine was using a wrong branch
