### ISSUE TITLE
No ipv4 assigned for kubernetes cluster

### ISSUE THREAD

**Issue by PeterNashaat** [threefoldtech/js-sdk#3059]
### Description
- choose public ip option on the chat deployer for kubernete , and didn't get any public ipv4
- while creating kubernete  from the chat on my hosted [3bot](https://storcap.3bottest.grid.tf/)

<img width="1330" alt="Screen Shot 2021-05-06 at 11 48 59 AM" src="https://user-images.githubusercontent.com/13523434/117278520-21f99e80-ae61-11eb-841a-1faf53132be3.png">

- Solution details
```{"wids":[37474,37475],"Name":"storclt","Network":"stornet","Master IP":"172.16.3.2","Slave IPs":["172.16.4.2"],"Slave Pools":[22040],"Master Pool":22040}```

### Installation method

3bot deployer
https://deploy3bot.testnet.grid.tf/

### Steps to reproduce

Try to create kubernete with public ip

**Comment by waleedhammam** [comment]
![Screenshot from 2021-05-06 13-18-41](https://user-images.githubusercontent.com/10658229/117290063-a7834b80-ae6d-11eb-9b6b-fac751370e08.png)

can't reproduce
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/37918
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/37917

185.69.167.157

**Comment by PeterNashaat** [comment]
Working fine now, Kubernetes vm can get public ipv4.
Thanks @waleedhammam .
