### ISSUE TITLE
VDC was deleted but still can not deploy one with the same name

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#3061]
### Description
while I was deploying a VDC, a glitch happened and I got a not working VDC instance, then I deleted it, after that I tried to redeploy another VDC but with the same name but I can't deploy as i got this error

![image](https://user-images.githubusercontent.com/46320202/117279796-5faaf700-ae62-11eb-9338-9ead21b592b1.png)
![image](https://user-images.githubusercontent.com/46320202/117279949-6b96b900-ae62-11eb-86e0-24c6a9a29c29.png)

**Comment by xmonader** [comment]
@MElborolossy please trace what happened.

**Comment by MElborolossy** [comment]
This Issue happens because the new vdc chatflow opened before delete the old one
In this case, refresh is required to reload the info of the deployed vdcs
> Reload button of the chatflow not from the browser

![image](https://user-images.githubusercontent.com/11272864/119691180-a630b780-be4a-11eb-814c-2abbba8d59a5.png)

**Comment by sameh-farouk** [comment]
**Verified**
**commit  23d1fcaf034788d2479afe0891c0da1059b1d6c6**
when you delete the VDC, there are about 4 seconds of delay. if you press delete then tried as soon as the delete dialogue disappears to deploy a new VDC with the same name it will not accepted, restarting the chat flow what is required then.

didn't able to reproduce the issue, other than having those few seconds of delay.
