### ISSUE TITLE
Can't assign volume to container using sal

### ISSUE THREAD

**Issue by PeterNashaat** [threefoldtech/js-sdk#3062]
### Description

Trying to assign volume to generic container while passing the same node id while creating both but it's not working :- 
- [Volume](https://explorer.testnet.grid.tf/api/v1/reservations/workloads/37512) `j.sals.reservation_chatflow.deployer.deploy_volume(pool_id=22040 , node_id='HC1WPUg8GMsbcYakHbHZxeWB1dGhwyvdjGr59dfk7vwE' , size=25 , volume_type=1 , identity_name='test' )` 

- [Container](https://explorer.testnet.grid.tf/api/v1/reservations/workloads/37564) 
`deploy_generic_flist( solution_name='etcd01' , flist=flist, vol='37512', network='stornet', pool='22040' ,node='HC1WPUg8GMsbcYakHbHZxeWB1dGhwyvdjGr59dfk7vwE' , corex='yes' , ipv4="choose_random")`
the container gets created in another node id, tried the same with 2 different nodes on freefarm created 2 new volumes and treid to attach them to container in the same node, got the same issue

### Installation method

- [same as here](https://github.com/threefoldtech/js-sdk/issues/3059)

**Comment by xmonader** [comment]
you shouldn't be using deploy_generic_flist in your case, use this https://github.com/threefoldtech/js-sdk/blob/224f02efcc/jumpscale/packages/tfgrid_solutions/chats/flist.py#L215 instead

**Comment by PeterNashaat** [comment]
- Like this ?  
```deployer.deploy_container(pool_id='22040' , network_name='stornet' , flist=flist, ip_address="choose_random" , identity_name='test' , volumes='37512')```

**Comment by PeterNashaat** [comment]
- what is the random option for ip_address ?
`deployer.deploy_container(pool_id='22040' , network_name='stornet' , flist=flist, ip_address="choose_random",identity_name='test' , volumes='37512', node_id='HC1WPUg8GMsbcYakHbHZxeWB1dGhwyvdjGr59dfk7vwE')`

`ipaddress: 'choose_random' is not a valid IP address`

**Comment by waleedhammam** [comment]
There are example here: https://threefoldtech.github.io/js-sdk/wiki/#/./tutorials/deploy_ubuntu_container
 And here
https://sdk.threefold.io/#/sdk__solution_container

**Comment by PeterNashaat** [comment]
i'm trying with this 
`deployer.deploy_container(pool_id='22040' , network_name='stornet' , flist=flist, ip_address='172.16.14.217' , identity_name='test' , volumes='37512', node_id='HC1WPUg8GMsbcYakHbHZxeWB1dGhwyvdjGr59dfk7vwE')`
got this error message for identity_name and got the same for node_id 
<img width="1440" alt="Screen Shot 2021-05-06 at 3 22 09 PM" src="https://user-images.githubusercontent.com/13523434/117305332-f2f22580-ae7e-11eb-9ad7-2432304453a0.png">

**Comment by waleedhammam** [comment]
It's in the method docstring the way we pass volumes:
https://github.com/threefoldtech/js-sdk/blob/332e4259820fa952587bf6b9527b95eaa7f1c4c4/jumpscale/sals/reservation_chatflow/deployer.py#L1069

**Comment by waleedhammam** [comment]
> * Worked https://explorer.testnet.grid.tf/api/v1/reservations/workloads/38082 , and i can ping the container ip
> 
> but got this error when i checked the workload
> `"failed to load network resource: failed to set route {Ifindex: 3 Dst: 0.0.0.0/0 Src: \u003cnil\u003e Gw: 172.16.10.1 Flags: [] Table: 0} on eth0: network is unreachable"`
> 
> * How can i get ssh access to the container ?

Did you choose an ip that's not in the subnet of the network?

**Comment by PeterNashaat** [comment]
network range is : 172.16.0.0/16
container ip : 172.16.14.217 and i can ping the ip through the wg vpn

**Comment by waleedhammam** [comment]
by checking the workload mountpoint is wrong
![Screenshot from 2021-05-06 16-11-03](https://user-images.githubusercontent.com/10658229/117312916-ba097f00-ae85-11eb-87ad-691669427327.png)

should be "/"

also for network, it seems the network resource is not deployed on that node.

Example deploying a network resource: https://threefoldtech.github.io/js-sdk/wiki/#/./tutorials/deploy_ubuntu_container?id=create-your-network

**Comment by waleedhammam** [comment]
> * i already have deployed network_name='stornet', and used it when i created the container , do i need to create a new one ?

The idea is network is shared between pools, when we need it on a specific node we check for the network resource if it's there or not, if not then we need to update the network with the new node, using add_node method
