### ISSUE TITLE
Drain the kubernetes node before deleting it

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#3065]
see https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/

**Comment by sameh-farouk** [comment]
verifying this...

**Comment by sameh-farouk** [comment]
after a discussion with @MElborolossy, we found that the logic to determine which solutions will get deleted and which will be rescheduled can be enhanced so the user could get consistent behavior with the same solutions.

![Screenshot from 2021-05-31 16-21-18](https://user-images.githubusercontent.com/42457449/120221308-787ab280-c23e-11eb-97d7-a82bba1d41af.png)

![Screenshot from 2021-05-31 16-24-16](https://user-images.githubusercontent.com/42457449/120221336-84ff0b00-c23e-11eb-8fa2-febf720b2b14.png)

**Comment by MElborolossy** [comment]
Still Working on verifying the new logic.

**Comment by MElborolossy** [comment]
### Current State
After testing, we found that most solutions use local storage, this will prevent pods from rescheduled on another node.
For now, we will delete all the releases which on/partially on that node before draining and deleting it.
### Related PR
#3181 (Ready and Waiting to reviewed)
