### ISSUE TITLE
payment timeout most of the time during node extension in testnet 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#3067]
### Description

I am getting payment timeout most of the time even so I have already done the payment and there was no problem while trying to extend my VDC with a new node on `Testnet` 

![image](https://user-images.githubusercontent.com/46320202/117303028-8c6c0800-ae7c-11eb-8312-6e3ac8e11cd1.png)

vdc_name:`backup6`

**Comment by AhmedHanafy725** [comment]
that was the reason, as the billing service would see that paid amount less than the needed amount.
![image](https://user-images.githubusercontent.com/41957921/117575023-4a430080-b0e0-11eb-9e0f-8a5450d8729b.png)

**Comment by MElborolossy** [comment]
Verified on devnet
commit 77a358016ac1f071ae21cefcd3ab895a8529c9ec
