### ISSUE TITLE
Feature request: Install the etcd cluster on 3 nodes

### ISSUE THREAD

**Issue by PeterNashaat** [threefoldtech/js-sdk#3072]
- Installing etcd from chatflow enables you to create more than one container of etcd but in the same node.
<img width="938" alt="Screen Shot 2021-05-09 at 11 02 35 AM" src="https://user-images.githubusercontent.com/13523434/117566342-78abe600-b0b6-11eb-9f8c-1e4fae1c2c63.png">
<img width="938" alt="Screen Shot 2021-05-09 at 11 03 23 AM" src="https://user-images.githubusercontent.com/13523434/117566346-83667b00-b0b6-11eb-8455-e73555d4fd81.png">

- Can we have the same but with multiple nodes, so if i am installing 3 etcd instances can install them on 3 different nodes
<img width="938" alt="Screen Shot 2021-05-09 at 11 06 13 AM" src="https://user-images.githubusercontent.com/13523434/117566368-9b3dff00-b0b6-11eb-9170-da2cde9264fc.png">

### Description

- Option to install etcd distributed system to more than one node
- It will be better if we have them distributed on more than one node , so if one node is down the rest of the etcd containers will be accessible

**Comment by xmonader** [comment]
closing, @PeterNashaat already verified.
