### ISSUE TITLE
Creating Network using sal

### ISSUE THREAD

**Issue by PeterNashaat** [threefoldtech/js-sdk#3073]
- Create your network [Here](https://threefoldtech.github.io/js-sdk/wiki/#/./tutorials/deploy_ubuntu_container?id=create-your-network)

### Description
- 1) Getting error while using `r = zos.reservation_create()`

<img width="776" alt="Screen Shot 2021-05-09 at 10 51 29 AM" src="https://user-images.githubusercontent.com/13523434/117566011-8bbdb680-b0b4-11eb-80c7-8fd83891e1b7.png">

- 2) Getting error While trying to install network on a node 
<img width="970" alt="Screen Shot 2021-05-09 at 11 13 04 AM" src="https://user-images.githubusercontent.com/13523434/117566557-93cb2580-b0b7-11eb-9233-0813e1bce505.png">

### Installation method
- 3bot deployer
https://deploy3bot.testnet.grid.tf/

**Comment by xmonader** [comment]
You need to use this documentation https://sdk.threefold.io/#/sdk__code_network , everything exists here https://sdk.threefold.io/#/sdk__develop and it was recently updated. I checked the document you referred to in the repo, and indeed it's outdated.

**Comment by xmonader** [comment]
please make sure the tutorials link to the most recent on the wiki

**Comment by RafyAmgadBenjamin** [comment]
verifying this

**Comment by RafyAmgadBenjamin** [comment]
Verifying this

**Comment by RafyAmgadBenjamin** [comment]
### Verified
The links are updated now with the correct content
