### ISSUE TITLE
nginx configurations shouldn't use StoredFactory

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#3083]
it needs to keep getting regenerated from the packages, always. we hit this issue after migration all the packages to a single bottle server, and all of the existing old, preconfigured locations still exist on the nginx locations object, meaning it will gets regenerated every time -with the old locations too-. Suggestion is make sure to delete the locations in 3bot start -as a method for an upgrade- and not use a StoredFactory for nginx SAL.

**Comment by RafyAmgadBenjamin** [comment]
verifying this

**Comment by RafyAmgadBenjamin** [comment]
### Verified
### Branch
`development`
### Commit ID
73616bac6fad9857c0f915ecba2e6a7f54307412

![image](https://user-images.githubusercontent.com/46320202/120620283-1ea40380-c45d-11eb-94d0-ebacce7dad92.png)
