### ISSUE TITLE
support generic VMs in the admin dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#3089]
TODO...

**Comment by RafyAmgadBenjamin** [comment]
verifying this

**Comment by RafyAmgadBenjamin** [comment]
### verified
### Branch
`development`
### Commit ID
73616bac6fad9857c0f915ecba2e6a7f54307412


![image](https://user-images.githubusercontent.com/46320202/120454622-598e3480-c394-11eb-8a6e-c6d2bdb93c8a.png)
![image](https://user-images.githubusercontent.com/46320202/120454868-90644a80-c394-11eb-871e-a1cd402dc926.png)
![image](https://user-images.githubusercontent.com/46320202/120454692-69a61400-c394-11eb-81e7-2a587c46d5bf.png)
