### ISSUE TITLE
Controller API requires 3bot login

### ISSUE THREAD

**Issue by abom** [threefoldtech/js-sdk#3090]
### Description

Controller API already use basic auth with vdc name and secret, but now it requires 3bot login (as a side effect from single bottle app changes).

### Version information

* OS: e.g. Ubuntu 18.04
* Project commit/version: development
* Browser: e.g. chrome 

### Installation method

Poetry

### Steps to reproduce

- Deploy a VDC
- Before login, try e.g. `/vdc_dashboard/api/controller/status`

**Comment by sameh-farouk** [comment]
**Verified** on development commit 651486a10b2d2b1eeb64dfe580e8104989604ca8

steps followed during the verifying process:
1- Deploy a VDC
2- Before login, try e.g. /vdc_dashboard/api/controller/status

Access Controller API no longer required 3bot login.
