### ISSUE TITLE
FarmMgmt: grid 3 compliant flag

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#3096]
allow the user to upgrade to grid 3 pricing: in the update request you can send `is_grid3_compliant` param with True
https://github.com/threefoldtech/tfexplorer/pull/307/files

note: don't show the button if the farm is compliant with grid 3

**Comment by RafyAmgadBenjamin** [comment]
verifying this

**Comment by RafyAmgadBenjamin** [comment]
### Verified
### Branch 
`development`
### Commit
e23494b847e44ad8fce4add28c4c8cf88585b85f

![image](https://user-images.githubusercontent.com/46320202/120987092-891ab380-c77d-11eb-99da-519721eb9b9f.png)
![image](https://user-images.githubusercontent.com/46320202/120987192-a64f8200-c77d-11eb-9a89-54cf4cad7066.png)
![image](https://user-images.githubusercontent.com/46320202/120987240-b4050780-c77d-11eb-9c77-44074de01d07.png)
