### ISSUE TITLE
3BOT : Unable to start 3bot after expiration and asked for payment again

### ISSUE THREAD

**Issue by abdulgig** [threefoldtech/js-sdk#3097]
### Description

 We have a user who is unable to start his 3bot and he is being asked for payment every time he tries to start his 3bot. He has lost around 80 TFTs during the process. The description of the issue is in quotes below from the user ,

> I am not able to start my 3bot anymore. My original solution expired last
month so I went to 3bot Deployer site and selected my existing 3bot, than I
clicked on Start button and went through the process and made a new payment
(TFT tokens are gone from my wallet). After that 3bot initialized, but
starting failed with some error message… now it’s asking me to pay again.
Can you please help with bringing my 3bot online?

### Information

3bot name =  peteruller
The wallet address would be provided by him shortly

**Comment by waleedhammam** [comment]
@abdulgig Can you state the error messages please ?

**Comment by abdulgig** [comment]
@waleedhammam , sure, I have requested the user. I ll update once he gets back to us

**Comment by abdulgig** [comment]
@waleedhammam , can we refund the lost tokens to the user ? As per the user,

> wallet address is GBHMXFVVZLNIWL6FJWTCYUQTQWAU5U5JOQCAB3DGIS52KDERPCKSMJQS
i have paid 124 TFT to address GBUSJVNRD2NPPHIMOAZGPNQUAD5NEYKUDVE23JYZVJG6TMRK22YACKQB to start 3bot and then error popped up

He is reluctant to test again and share the logs as he may lose tokens again.

**Comment by xmonader** [comment]
I think it's a different problem: on the gateway I see the error 
![image](https://user-images.githubusercontent.com/64129/121261305-db112580-c8b2-11eb-87f0-4ca4b46eb3ce.png)

**Comment by xmonader** [comment]
I refunded 124 TFT to the user https://stellar.expert/explorer/public/tx/6d1fe2b13071154cee50ab5f19a25e41e487e36ae923bacdcbef05d74ad51f0c

also, I deleted the records of peterruller from `3botmain.grid.tf`, managed_domains, and tcprouter service key in redis, the user should be able to deploy again now.

**Comment by abdulgig** [comment]
@xmonader , great ! We ll ask him to test again

**Comment by scottyeager** [comment]
User has reported that deployment failed again: https://forum.threefold.io/t/stopped-3bot-cannot-be-started-again/769/10

**Comment by morebray** [comment]
Hello,
I tried twice and paid with neuefarm2 and morebray both are "stopped" and cannot be started again!
1. When trying to start it takes a very long time bit response comes.
2. Then I am asked to pay again
3. I created my third attempt "morebray01" and it is running, but only for 2 days, I wanted to expand pool 4111, but there is a request for payment from thousands of TFTs ??
So somehow none of this works for you ...

We are very disappointed

inGerman__________
Hallo,
ich habe zwei mal versucht und bezahlt mit neuefarm2 und morebray beide sind "gestoppt"  und lassen sich nicht wieder starten !
1. Beim Versuch zu starten dauert es sehr sehr lange bit Antwort kommt.
2.  Dann werde ich wieder aufgefordert erneut zu bezahlen
3. mein dritter versuch "morebray01"  habe ich erzeugt und läuft auch, aber nur 2 tage, ich wollte den Pool 4111 erweitern, aber da kommt eine Zahlungsaufforderung von tausenden TFT's ??
Also irgendwie funktioniert das alles nicht bei euch .... 

Wir sind sehr enttäuscht

**Comment by xmonader** [comment]
@morebray Hello, can you please share your telegram handle? mine is @xmonader , and I'd love to help you.

**Comment by morebray** [comment]
Hello,

your Network or servers is very slow, i wait and wait of a answer in my Browser ...

(We have a Fiber 1 Gb Internet access…)


See pictures…

**Comment by morebray** [comment]
Hello,

i have installed the gofarmer.tar.gz  ...

and configured…

but then ??

what now ?

I can’t login

---------
https://morebray01.3botmain.grid.ft/admin

can’t open URL ...




all ist STOPPED

when i will start  morebray01 it comes … please pay 93…. TFT  so on … ?  i dont under stand this
