### ISSUE TITLE
VDC: Delay deploying storage containers

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#3118]
To speed up the VDC deployment, the deployment can start with deploying the main workloads(compute nodes and the controller), then deploying the storage containers.
where it should be done on?
- deployer in a service
- after finishing the chatflow
- VDC controller in a service

Will it speed up the deployment?
in case it is done in service what if the user deletes some storage containers?

**Comment by MElborolossy** [comment]
It takes 7.5 minutes to deploy without storage nodes

**Comment by OmarElawady** [comment]
Tried again after reordering the deployments to make the zdb, traefik upgrade, and 3bot run in parallel, and the 3bot speed up. Took 7:50 minutes.

**Comment by MElborolossy** [comment]
After improvements and measurements, we found that Zdbs don't affect the time, so it will be deployed in the chatflow as the current situation.
