### ISSUE TITLE
test vdc deployment time

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/js-sdk#3121]
deploy 3 silver vdcs on testnet.
make sure to time exactly how long it takes for a successful deployment. make sure to pay immediately to get most accurate results

**Comment by mhost39** [comment]
on testnet with silver plan 
deployed 3 VDCs:
- first one deployed in 10.20 minutes.
- second vdc deployed in 10.30 minutes.
- third vdc deployed in 10 minutes.
(with immediately payment)

**Comment by mhost39** [comment]
on devnet with silver plan
deployed 2 VDCs:
- first one deployed in 10 minutes.
- second vdc deployed in 10.7 minutes.

**Comment by rkhamis** [comment]
thanks
