### ISSUE TITLE
VDC: Minimize the time of deploying VDC threebot

### ISSUE THREAD

**Issue by abom** [threefoldtech/js-sdk#3137]
### Description

After a discussion with @xmonader and @AhmedHanafy725, we thought that reducing the time deploying the threebot server (with its initialization) will reduce the overall time of VDC deployment.

The main goal is to make the server starts early, and do the time consuming initialization after that, so the user could at least interact partially with the server and the overall deployment time will be reduced too.

### Implementation

The following options were discussed

* Use a new flist for threebot that includes all the required binaries [instead of downloading them every time](https://github.com/threefoldtech/js-sdk/blob/b1c5eaba72b1c4694f228304d663ccfa18cb6248/jumpscale/packages/tfgrid_solutions/scripts/threebot/initialize.sh#L4-L13).
* Add `on_start` method to packages to run initialization after the server is already started.
* Separate start script to multiple ones that depends on init, and don't block server starting.
* Do initialization interactively with a UI showing steps and configurations to the user

**Comment by OmarElawady** [comment]
Deploying a 3bot, these are the time taken for significant parts:
1. 20s packages installation 
2. 10s domain wait (can be removed)
3. 93s install velero
4. 22s 3bot start
with total time of 153 seconds
Preinstalling packages and separating velero installation into a separate service should bring it down to less than a minute.

**Comment by RafyAmgadBenjamin** [comment]
Verifying this

**Comment by RafyAmgadBenjamin** [comment]
### Verified 

```
2021-06-06 10:32:36  
2021-06-06 08:32:35.866 | INFO     | jumpscale.servers.threebot.threebot:start:882 - Threebot is running at http://localhost:80 and https://localhost:443\n
```

```
2021-06-06 10:31:13  
[*] Starting threebot in background ...\n
```
