### ISSUE TITLE
Test Coverage  For VDC API

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/js-sdk#3146]
### Description

test-suite coverage for VDC API

 generate api key 
- [ ]  list nodes (kubernates info), add node, delete node.
- [ ] list zdbs, add_zdb, delete_zdb.
- [ ] get wallet info.
- [ ] list pools.
- [ ] list alerts.
- [ ] list all admins, add admin, remove admin.
- [ ] create backup.
- [ ] list backups.
- [ ] delete backup.
- [ ] restore backup.

**Comment by mhost39** [comment]
for test VDC API you need to generate API Keys 
in case we used selenum for generate API Keys we need to login by connect app

**Comment by xmonader** [comment]
> for test VDC API you need to generate API Keys
> in case we used selenum for generate API Keys we need to login by connect app

No, You don't need selenium, you can generate a key using the APIKeyFactory

https://github.com/threefoldtech/js-sdk/blob/9eed06065e5f31040f35ff5696c6dc87785b3334/jumpscale/packages/vdc_dashboard/bottle/models.py
