### ISSUE TITLE
Support button appears in front of license agree button

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/js-sdk#3150]
### Description

I have to zoom out to be able to accept the license.

![Screenshot from 2021-06-01 14-07-19](https://user-images.githubusercontent.com/13040543/120474140-1f2e9280-c3a8-11eb-9161-97daa05e73e9.png)

**Comment by sameh-farouk** [comment]
**still not fixed**

the issues happen with resolutions lower than 900px.  also, it happens with higher resolutions but only when the window is not maximized.

![Screenshot from 2021-06-03 17-23-36](https://user-images.githubusercontent.com/42457449/120670352-a0615480-c490-11eb-9c32-c4f1857f1aed.png)

tested on Chrome browser Version 91.0.4472.77 (Official Build) (64-bit)

**Comment by RafyAmgadBenjamin** [comment]
verifying this

**Comment by samaradel** [comment]
produced on 720px

![image](https://user-images.githubusercontent.com/11662805/120997034-2cbc9180-c787-11eb-87ff-1e39602b7e92.png)

**Comment by waleedhammam** [comment]
works ok now, on devnet and testnet
