### ISSUE TITLE
VDC: Elements behind support bar is not clickable

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/js-sdk#3151]
### Description

Can't click on the buttons or textboxes behind the support block.

**Comment by RafyAmgadBenjamin** [comment]
verifying this

**Comment by RafyAmgadBenjamin** [comment]
### Verifed 
Branch 
`development`
![image](https://user-images.githubusercontent.com/46320202/120917622-7c7c5980-c6b0-11eb-9921-ccd29de125b3.png)
