### ISSUE TITLE
checking pid file of nginx doesn't always reflect its state

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#3160]
![image](https://user-images.githubusercontent.com/64129/120893490-e4309700-c613-11eb-9e14-b6dc56ac361d.png)

![image](https://user-images.githubusercontent.com/64129/120893495-eb57a500-c613-11eb-9827-010cf7df34cb.png)

apparently checking against the `pid` file isn't enough and at some situations it won't be even cleanup correctly, needs to be hardend with checks against nginx ports as well

**Comment by abom** [comment]
As ports are defined in config, checking for them is not the best solution IMHO.
Maybe we could harden this PID file check by checking for the PID itself (if it's already a running process).

**Comment by waleedhammam** [comment]
Nginx works ok now
