### ISSUE TITLE
User unable to restart 3Bot, reports TFT lost

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/js-sdk#3169]
User reports on ThreeFold [forum](https://forum.threefold.io/t/stopped-3bot-cannot-be-started-again/769/6) that they are unable to restart their ThreeBot, but payment was still taken during the process.

3bot name is peteruller and is using mainnet.

**Comment by abdulgig** [comment]
@scottyeager , we can close this as this issue has been reported and being looked into.

Ticket = https://github.com/threefoldtech/js-sdk/issues/3097

We have requested the user to share logs / alerts to troubleshoot
