### ISSUE TITLE
Support custom k3os VM sizes

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/js-sdk#3174]
Zero OS appears to support [custom sizing for k3os VMs](https://github.com/threefoldtech/zos/blob/70ee8619708148a504ddcac4cb79710d37555f6d/pkg/provision/primitives/vmutils.go#L189), but js-sdk does not. Is this possible to implement?

**Comment by xmonader** [comment]
the size `-1` supported in zos v2 means allocate all of the resources fo the node to this VM, it was meant for "reserving full node", but we ended up with "reserving the remaining of what is available on the node". however in zos3 the model will be completely changed to specifying the capacity 

![image](https://user-images.githubusercontent.com/64129/121804228-9c2df780-cc45-11eb-82df-39b93a25425f.png)

**Comment by scottyeager** [comment]
Good to know, thanks.
