### ISSUE TITLE
Outdated explorer URLs in wiki

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/js-sdk#3185]
On this page: https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/identity.md

None of the listed explorer URLs are currently active.

**Comment by xmonader** [comment]
These are explorer API root endpoints, not the explorer UI website

**Comment by scottyeager** [comment]
Yes, I know. I see that there shouldn't be a Swagger UI at each one. Still, mainnet is wrong... which I learned from you :wink:
