### ISSUE TITLE
VDC: REST API support for VMs

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#3216]
part of https://github.com/threefoldtech/home/issues/1091

**Comment by sameh-farouk** [comment]
### status update:
- the rest API for the virtual machine is implemented (list, add, delete) and added to the swagger open API with examples.
- there is a bug in the deployment code, https://github.com/threefoldtech/js-sdk/issues/3239 needs to be addressed.
- there are some parts of the code that need to be refactored.

**Comment by sameh-farouk** [comment]
### status update:
- the PR is ready for review.

https://github.com/threefoldtech/js-sdk/pull/3251
