### ISSUE TITLE
Cannot deploy vdc on devnet

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/js-sdk#3225]
### Description
No nodes available to deploy vdc of size SILVER on devnet using https://vdc.devnet.grid.tf

### Traceback/Logs/Alerts
error:
`log.2021-06-30_11-02-12_919926.txt:2021-06-30 11:17:38.150 | ERROR    | jumpscale.sals.vdc.deployer:_log:930 - VDC UUID: de2b5ba315d949658384f8ed20f7af57, NAME: wed30v2, OWNER: ranatarek no available nodes to deploy etcd cluster`

![image](https://user-images.githubusercontent.com/17128393/123956882-788be080-d9ab-11eb-93ad-01ed70af749a.png)

**Comment by sameh-farouk** [comment]
deployment still broken as 5/7/2021
```
fs/log.txt:2021-07-05 10:41:26.784 | ERROR    | jumpscale.sals.vdc.deployer:_log:930 - VDC UUID: 6f381501ce174cc4bfad4476df23463b, NAME: testnodevdeb, OWNER: samehabouelsaad no available nodes to deploy etcd cluster
fs/log.txt:2021-07-05 10:41:26.786 | ERROR    | jumpscale.sals.vdc.deployer:_log:930 - VDC UUID: 6f381501ce174cc4bfad4476df23463b, NAME: testnodevdeb, OWNER: samehabouelsaad failed to deploy etcd cluster
fs/log.txt:2021-07-05 10:41:26.787 | ERROR    | jumpscale.sals.vdc.deployer:_log:930 - VDC UUID: 6f381501ce174cc4bfad4476df23463b, NAME: testnodevdeb, OWNER: samehabouelsaad Failed to deploy external etcd cluster. cancelling workloads
```

**Comment by sameh-farouk** [comment]
pulled latest changes from development branch, tested and it worked.

**Comment by sameh-farouk** [comment]
closed as the issue seems to gone after updating the Devnet
