### ISSUE TITLE
VDC: check_threebot service should do more checking before decommissioning the workload

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/js-sdk#3236]
the service depends on one HTTP test that could be failed due to many reasons such as gateway problems or connection issues so we should add more checking to insure that the container is really down.
https://github.com/threefoldtech/js-sdk/blob/development/jumpscale/packages/vdc/services/check_threebot.py#L57

suggestion 1:
- we can just raise alert and send mail to the support and the admin
- provide the admin button to redeploy the 3Bot in the VDC deployer frontend

suggestion 2:
- enhance the checking like check periodically and redeploy only if failed for n times in one row
- we can disable the service on the devnet machine as it is annoying in the development process when you maybe bring your server down for any reason and the service kicked down and decided to delete the container
- we can bypass waiting for the workload deletion as the explorer sometimes can't delete the workload then the service failed to decommission.

**Comment by xmonader** [comment]
I don't think we can afford the lack of interactivity on the first suggestion, I like the second option better, and for disabling the service, that can be configurable (no need to hardcode that in the service file)

**Comment by AhmedHanafy725** [comment]
Also, this service shouldn't delete any container in VDC identity, as we have etcd containers which will be removed with the threebot container and the etcd containers will never come back.
