### ISSUE TITLE
3Bot Deployer: get alert with ID: 361 when trying to pay for 3Bot

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/js-sdk#3246]
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/18591016/125253285-8c173f80-e2f9-11eb-9b27-9cc5d41860a2.png">

get above alert when trying to pay for 3Bot extension. using google chrome as a browser.

**Comment by waleedhammam** [comment]
Should be resolved after https://github.com/threefoldtech/tfexplorer/issues/340
