### ISSUE TITLE
the same 3bots keep requesting ssl certificates

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/js-sdk#3253]
Ssl certificates are constantly requested for for
- atef3-presearch-mypre.webg1dev.grid.tf
- geertincubaid-presearch-myps90.webg2test.grid.tf
- ranatarek-cryptpad-testingggg.webg1test.grid.tf

This indicates an underlying problem like a loop in the deployment, a problem with the deployed 3bot or something else that needs investigation

**Comment by waleedhammam** [comment]
could be a possible reason https://github.com/threefoldtech/vdc-solutions-charts/issues/148

**Comment by xmonader** [comment]
resolved
