### ISSUE TITLE
switching explorers gives 500 bad request

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#326]
when switching explorer from the settings (used for capacity/farmmgmt) packages

![image](https://user-images.githubusercontent.com/64129/88389393-bb663100-cdb6-11ea-8cbf-43939aa94599.png)

![image](https://user-images.githubusercontent.com/64129/88389433-cf119780-cdb6-11ea-9d9f-daf5fd776c93.png)

**Comment by waleedhammam** [comment]
This requires the identity to be the same on testnet and mainnet

example if I have `waleedhammam.3bot` registered on testnet and mainnet with the signature it'll work okay

proper error will be shown by @ahsayde now :D

![Screenshot from 2020-07-24 14-27-13](https://user-images.githubusercontent.com/10658229/88391241-151c2a80-cdba-11ea-9f18-f1369b5b048c.png)

**Comment by waleedhammam** [comment]
I suggest to remove this part and stick to identities only, set one for testnet and one for mainnet

**Comment by waleedhammam** [comment]
removed this part and depends on identity in this pr: https://github.com/threefoldtech/js-sdk/pull/328

**Comment by hossnys** [comment]
verified : switching between explorer using identities is working fine 

![Screenshot from 2020-07-26 13-37-42](https://user-images.githubusercontent.com/26298009/88477983-e8e0e500-cf44-11ea-867f-4a38fd138183.png)

![Screenshot from 2020-07-26 13-40-18](https://user-images.githubusercontent.com/26298009/88478007-129a0c00-cf45-11ea-8f1c-83153caff3d3.png)
