### ISSUE TITLE
VDC: Invalidate cache after deploying and deleting compute and storage nodes

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#3263]
https://user-images.githubusercontent.com/41957921/127342447-5bbcd41c-6172-447b-a795-1226a3f0de17.mp4

https://user-images.githubusercontent.com/41957921/127342773-d6941472-a673-4026-886a-4aa175772ded.mp4

**Comment by MohamedElmdary** [comment]
### Fixed
### Branch
development_storage_containers_cache
### Commit
571e22fbd8a386c95286835a4bd95d70d9498dbc
### PR
