### ISSUE TITLE
Extend threebot and VDC testsuite

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/js-sdk#3268]
need to extend testsuite with more scenarios:
### threebot:
- [ ] add 3bot admin and deploy container.
- [ ] deploy an ubuntu and push the container logs onto an external redis channel.
- [ ] deploy a kubernetes with enable public IP.
- [ ] deploy a container then ssh to it.
- [ ] deploy a s3 minio with SSD and HDD.
- [ ] deploy a s3 minio with a global IPv6 address.
- [ ] expose solution with TRC and NGINX.
- [ ] expose solution with custom domain.
- [ ] deploy virtual machine.
- [ ] deploy a container with attach an extra volume to the container.
- [ ] deploy a container with environment variables.

### VDC:
- [ ]  VDC api:
    - [ ] generate api keys 
    - [ ] delete api keys
    - [ ] add admin
    - [ ] list all admins
    - [ ] remove admin
    - [ ] list alerts
    - [ ] add zdb
    - [ ] list zdbs
    - [ ] delete zdb
    - [ ] get wallet info
    - [ ] list VDCs
    - [ ] get VDC info
    - [ ] delete VDC 
- [ ] VDC backup:
    - [ ] create backup
    - [ ] restore backup
    - [ ] delete backup

**Comment by rkhamis** [comment]
@mhost39 @ramezsaeed what's the progress here? is it done?

**Comment by mhost39** [comment]
vdc API: https://github.com/threefoldtech/js-sdk/issues/3146#issuecomment-913164176
threebot done for happy path and extend unhappy path not worked on it yet

**Comment by xmonader** [comment]
there should be no issue handling two products (3bot, VDC) i'll close and let's do it properly
