### ISSUE TITLE
TFT doesn't come back after VDC failure

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/js-sdk#3273]
with testnet network
first scenario:
when i pay from TF connect app and got transferred successful
got this after waiting: 
![vdcissue](https://user-images.githubusercontent.com/31102305/127973696-bcdf4ef3-d083-4227-b375-9d7ed95ae8ea.png)
and 15 TFT has been deducted 

second scenario:
i tried again and payment worked fine but got this error
![vdcfailed](https://user-images.githubusercontent.com/31102305/127974203-37641cd9-e504-419f-ac93-1c823aeb7f2a.png)
and 15 TFT has been deducted

**Comment by waleedhammam** [comment]
Errors were fixed successfully after stellar node fix
