### ISSUE TITLE
3Bot - creating capacity pool is extremely slow

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/js-sdk#3276]
I am trying to create a new capacity pool on an up to date local 3Bot. After choosing the desired amount of capacity, the next step took many minutes to complete. Then I selected the farm and have been waiting some time to get to the next step. No errors are shown.

**Comment by xmonader** [comment]
I believe that's related to https://github.com/threefoldtech/home/issues/1102

**Comment by scottyeager** [comment]
Just checked the alerts tab on 3Bot, and see this:

![image](https://user-images.githubusercontent.com/17682591/128206356-ecfa021c-6e09-4ad9-848c-f948252219cf.png)

**Comment by xmonader** [comment]
Please guys check that tmw, seems the selected_farm ended being that weird string (1,1,0 day 1) which seems to be the capacity pool form data

**Comment by sameh-farouk** [comment]
@scottyeager  we weren't able to reproduce the issue. can you specify in which network (devnet/testnet) you face this issue and if it is reproducible with you?

**Comment by sameh-farouk** [comment]
creating pools on both testnet and devnet was successfully done in under 1 minute each time without any issues.

**Comment by xmonader** [comment]
@scottyeager please move back to in progress if it happens again
