### ISSUE TITLE
VDC: Migrate to zos3

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/js-sdk#3285]
### Scheduler (resources checker to do some queries on grid3 resources)
- Will be replaced with `graphql queries` for grid3 or use `substrate client`

  - Select node with enough resources (hru, mru, sru, hru, access node, public IP) for deployment
  - Select multiple nodes for deployment (for Kubernetes)
  - Select a farm or multiple farms with specific specs for deployment

### We will build a single deployment that contains the VDC workloads based on the chosen flavor:
- Workloads (deployed on the farms and nodes selected from the capacity checker)
    - Network 
    - Public IP
      For the Kubernetes master
    - Kubernetes
      we have 4 flavors with sizes: silver, gold, platinum, diamond 
    - 3Bot vmachine (VDC dashboard)
      Deploy vmachine with for VDC dashboard with a domain
    - Subdomain
      Deploy subdomain for the 3Bot vmachine (VDC dashboard)
    - ZDBs
      Deploy ZDBs with the required size and number
    - ETCD cluster
      Deploy etcd cluster for VDC

------

- VDC dashboard sals (Optional)
  - Kubernetes auto-extend 
    all plans start with 1 master and 1 worker and are extended according to usage. To implement it in grid3 we will need to update the deployment contract. 
   1- Network workload: to add the new worker node ( if new node) in the network
   2- Kubernetes worker VM: Add the worker VM to the deployment
   3- Connect worker to master

  - ZDB auto top-up
    ZDBs starts 10 zdbs with 10GB each and are extended according to plan, will be by updating the contract like the previous steps

  - Price diff and grace period services will be canceled ( **to be removed** ).
  - Retries and dry runs will be canceled ( ***to be removed** )
  - Quantium storage file system
    will be as before as it's related to k8s not zos
  - Redeploy master service. (**check if we can add another IP**)
    - update contract by deleting the old master, create the new one and attach it to the public IP
  - Redeploy 3Bot VM:
    - Update the contract  by deleting the old 3bot VM, create the new one, attach it to the subdomain

The VDC flavors: https://raw.githubusercontent.com/threefoldfoundation/vdc_pricing/master/plans.json

--------

### Updating deployment flow:

- Update deployment hash with the new deployment workloads and **follow the versioning policy**.
- Update contract with the new deployment hash
- Push deployment hash on the RMB using the same contract id, with calling update_deployment

**Comment by xmonader** [comment]
We didn't address identity management at all, now that we all familiar with grid3 deployments flow It's good time to revisit

**Comment by ranatrk** [comment]
as discussed with @xmonader the following scenarios are proposed for the identity management:
1. Deploy twin server for each user
   - A central twin server is deployed that can be used to deploy other twin servers for the users
   - When a twin server is deployed for the user, the user will have full access to it and it will have their rmb, mnemonics and a UI to be able to deploy)
   - The users deployed twin server will create contracts and deployments
   - price for deployment can be increased to cover the payment done to deploy the twin server of the user
2. Browser extension to sign for each user( if rmb proxy can be done)
    - The user mnemonics can be loaded in the browser and used for signing
    - if no rmb proxy can be done, the user will need to start rmb locally to be able to send and recieve
