### ISSUE TITLE
Deploy eVDC in testnet 2.8 hangs after payment

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/js-sdk#3297]
Deploy silver and gold eVDC on testnet and the deployment hangs after payment.

3botname: weynandkuijpers.3bot
URL used: https://vdc.testnet.grid.tf/vdc/#/
eVDC names()s): tarcinidc (silver), tarchinidc (gold)

Payment:
![payment-screen](https://user-images.githubusercontent.com/13766992/131999489-6a371602-29a2-4018-a7ec-172acbdf49ca.jpg)

eVDC deployer:
![image](https://user-images.githubusercontent.com/13766992/131999566-2fc513e6-66b1-45be-8c9b-832b4ec68478.png)

**Comment by weynandkuijpers** [comment]
deploying a 3bot online on testnet does work and completes after payment.

**Comment by scottyeager** [comment]
I have not been able to reproduce the error, with two successful VDC deployments today.

**Comment by weynandkuijpers** [comment]
okay - let's call it a fluke then.  Thanks for checking - will retry now and if not a problem will closer the issue.

**Comment by xmonader** [comment]
@weynandkuijpers can we close this one?
