### ISSUE TITLE
metadata problem in ubuntu chatflow

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#33]
@grimpy  @waleedhammam please define and provide the suggested solution to implement

**Comment by waleedhammam** [comment]
fixed: https://github.com/threefoldtech/js-sdk/commit/e4c5176750d332aa606170439a4b8a8e59916d54#diff-076c6afee3b57420df0dd3ed0b0dc0fe

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
