### ISSUE TITLE
Taiga chat flow Missing SMTP configuration step

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/js-sdk#3316]
### Description
Taiga chat-flow Missing SMTP configuration step.
deployed taiga from the VDC marketplace won't allow normal SMTP operation, like sending emails when register or invite members because SMTP is not configured.
this step needs to be added and the chart also needs to adjust accordingly.
[x] update the chart
[ ] update the chatflow

**Comment by xmonader** [comment]
Can't that be configured on the instance after deployment? if yes then it's ok.

**Comment by sameh-farouk** [comment]
@xmonader for Taiga, I think this is not achievable from the front end. by default, email is configured with the console backend, which means that the emails will be shown in the stdout. If the user has an SMTP service he needs to configure those environment variables:

```
EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
DEFAULT_FROM_EMAIL: "no-reply@example.com"
EMAIL_HOST: "smtp.host.example.com"
EMAIL_PORT: 587
EMAIL_HOST_USER: "user"
EMAIL_HOST_PASSWORD: "password"
EMAIL_USE_TLS: "True"
EMAIL_USE_SSL: "True"
```

after deployment, this could be only achievable through direct access to the `taiga-back` container.
