### ISSUE TITLE
vdc_dashboard_upgrade_traefik service gives JSON parse error

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/js-sdk#3332]
when checking `shiva-av` VDC on testnet I found this error

VDC: shiva-av
3Bot: shiva.3bot

logs:
```
raise JSONDecodeError("Expecting value", s, err.value) from None\n
File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode\n
└ <json.decoder.JSONDecoder object at 0x7f69bf0855e0>\n
│ └ <function JSONDecoder.raw_decode at 0x7f69bef7e3a0>\n
│ │ └ ''\n
│ │ │ └ <built-in method match of re.Pattern object at 0x7f69befc3c30>\n
│ │ │ │ └ ''\n
obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n
File "/usr/lib/python3.8/json/decoder.py", line 337, in decode\n
└ <json.decoder.JSONDecoder object at 0x7f69bf0855e0>\n
│ └ <function JSONDecoder.decode at 0x7f69bef7e310>\n
│ │ └ ''\n
return _default_decoder.decode(s)\n
File "/usr/lib/python3.8/json/__init__.py", line 357, in loads\n
└ <module 'json' from '/usr/lib/python3.8/json/__init__.py'>\n
│ └ <function loads at 0x7f69bef7e9d0>\n
│ │ └ ''\n
return json.loads(s)\n
File "/usr/local/lib/python3.8/dist-packages/jumpscale/data/serializers/json.py", line 38, in loads\n
\n
└ <jumpscale.loader.J object at 0x7f69bf8294f0>\n
│ └ <property object at 0x7f69bf839b30>\n
│ │ └ ''\n
results = j.data.serializers.json.loads(out)\n
File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/services/upgrade_traefik.py", line 24, in get_traefik_version\n
\n
└ <upgrade_traefik.UpgradeTraefik object at 0x7f69bad2a760>\n
│ └ <function UpgradeTraefik.get_traefik_version at 0x7f69bad269d0>\n
current_ver = self.get_traefik_version()\n
File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/services/upgrade_traefik.py", line 14, in job\n
\n
> File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run\n
\n
Traceback (most recent call last):\n
2021-10-18 08:19:36.154 | ERROR | jumpscale.tools.servicemanager.servicemanager:__on_exception:142 - Service vdc_dashboard_upgrade_traefik raised an exception\n
\n
2021-10-18T08:19:36Z <Greenlet at 0x7f69ba459480: <bound method UpgradeTraefik.job of <upgrade_traefik.UpgradeTraefik object at 0x7f69bad2a760>>> failed with JSONDecodeError\n
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n
raise JSONDecodeError("Expecting value", s, err.value) from None\n
File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode\n
obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n
File "/usr/lib/python3.8/json/decoder.py", line 337, in decode\n
return _default_decoder.decode(s)\n
File "/usr/lib/python3.8/json/__init__.py", line 357, in loads\n
return json.loads(s)\n
File "/usr/local/lib/python3.8/dist-packages/jumpscale/data/serializers/json.py", line 38, in loads\n
results = j.data.serializers.json.loads(out)\n
File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/services/upgrade_traefik.py", line 24, in get_traefik_version\n
current_ver = self.get_traefik_version()\n
File "/sandbox/code/github/threefoldtech/js-sdk/jumpscale/packages/vdc_dashboard/services/upgrade_traefik.py", line 14, in job\n
File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run\n
Traceback (most recent call last):\n
```

**Comment by MElborolossy** [comment]
# Reporting VDC
Creation time: 11/07/2021, 06:04:06
Expiration time: 22/04/2025, 16:57:01
Flavor: diamond
Grace Period:  No
Master IP:    --> State: Down
Threebot IP: 
Threebot Domain:   --> State Down

## Wallets
| Name                                              | Address                                                  | Balance          |
|---------------------------------------------------|----------------------------------------------------------|------------------|
| prepaid_wallet_869ff6dcaa614cdabaa65ebeb997a515   | GCJC5ES3YIRWDBGR37YRI53B4GWDMOIA2ULMRK63PNYPDTWP3EQTG4ET | 7857.7878500 TFT |
| provision_wallet_869ff6dcaa614cdabaa65ebeb997a515 | GBAVW6DR4LTCQCQL575REZYBETDAISZKEU5TTLGVZXCIQ745KI2NK54Y | 157.7834430 TFT  |


## Workloads
| Wid   | Type            | State   | Farm      | PoolID | IPv4Units | NodeID                                       | NState  | Message |
|-------|-----------------|---------|-----------|--------|-----------|----------------------------------------------|---------|---------|
| 48140 | Zdb             | DEPLOY  | freefarm  | 29116  | 3144896.0 | 26ZATmd3K1fjeQKQsi8Dr7bm9iSRa3ePsV8ubMcbZEuY | Up      |         |
| 48141 | Zdb             | DEPLOY  | freefarm  | 29116  | 3144894.0 | 85J3zEvcqDoPaN7qQHRQ2QgPVcYdCvp8JmRY5qAwzxfm | Up      |         |
| 48142 | Zdb             | DEPLOY  | freefarm  | 29116  | 3144894.0 | DJoL9ZV53K5YQurmxor2BLWTPf3WA9dT3RsFWeDeAx1z | Up      |         |
| 48143 | Zdb             | DEPLOY  | freefarm  | 29116  | 3144892.0 | 3ksZcDF1yNH5S4ndEDXH3Jnp5cowh4ko8888jKepAD4a | Up      |         |
| 48144 | Zdb             | DEPLOY  | freefarm  | 29116  | 3144892.0 | 8zPYak76CXcoZxRoJBjdU69kVjo7XYU1SFE2NEK4UMqn | Up      |         |
| 48145 | Zdb             | DEPLOY  | freefarm  | 29116  | 3144890.0 | EMg1z3up8UcYNK5Rbfya7kKkKsuyqhNWrv15JKHERbuW | Up      |         |
| 48146 | Zdb             | DEPLOY  | freefarm  | 29116  | 3144890.0 | 2imakaznKfYx3vA4CDcTKxWbw9GcW3eXX8wQfr61X1Lz | Up      |         |
| 48147 | Zdb             | DEPLOY  | freefarm  | 29116  | 3144888.0 | BhAgw6PMUUETKQmZCCGqfNF2Pt4n6FKW4D8p7yY7hWpQ | Up      |         |
| 48148 | Zdb             | DEPLOY  | freefarm  | 29116  | 3144888.0 | 93qJrfeBqYiuVC973n9kPX79uA4rZU6oHL9pdJGBegHL | Up      |         |
| 48149 | Zdb             | DEPLOY  | freefarm  | 29116  | 3144886.0 | 7e8iFD2inToLQzqTp855SpYf8LfVt9K3MUzrTWoqtvov | Up      |         |
| 48158 | Container       | DELETED | freefarm2 | 29117  | 0.0       | FbMBh3gGX5WLkcVgvxtTZ32ZiQwoAUUfcDvdMp8fLP8H | Up      |         |
| 48159 | Container       | DELETED | freefarm2 | 29117  | 0.0       | G5PZcQ64oAyRfyc5cCH9gW7XZnGorSbmCujLAou3CdJo | Up      |         |
| 48160 | Container       | DELETED | freefarm2 | 29117  | 0.0       | Gx8Lq33vothCc3WnbbNeZCMTvfTbGMDtXTdyKRSGHSkp | Up      |         |
| 48175 | Container       | DEPLOY  | freefarm2 | 29117  | 0.0       | A54PL8EPQHC1SefcFcnLKaqurw8nBNTSFsFriYowYP1a | Up      |         |
| 48176 | Container       | DEPLOY  | freefarm2 | 29117  | 0.0       | CX13eZPrZcyaUK2EaiPuyiLKoyJfL2WL5P3s2QCU5Qem | Up      |         |
| 48177 | Container       | DEPLOY  | freefarm2 | 29117  | 0.0       | BPkUGAiTMxEAJEFFpaJAQAvoy3ptKTCohEPKS3g3ANuG | Up      |         |
| 48179 | Kubernetes      | DELETED | freefarm2 | 29117  | 0.0       | FbMBh3gGX5WLkcVgvxtTZ32ZiQwoAUUfcDvdMp8fLP8H | Up      |         |
| 48180 | Kubernetes      | DELETED | freefarm2 | 29117  | 0.0       | A54PL8EPQHC1SefcFcnLKaqurw8nBNTSFsFriYowYP1a | Up      |         |
| 48182 | Subdomain       | DELETED | Gateway   | 29118  | 0.0       | 9PdutHsdDSxcKUUyDg8ovS1KWh47qLT5R9h5uoFgRUH2 | Gateway |         |
| 48183 | Reverse_proxy   | DEPLOY  | Gateway   | 29118  | 0.0       | 9PdutHsdDSxcKUUyDg8ovS1KWh47qLT5R9h5uoFgRUH2 | Gateway |         |
| 48184 | Container       | DELETED | freefarm2 | 29117  | 0.0       | FbMBh3gGX5WLkcVgvxtTZ32ZiQwoAUUfcDvdMp8fLP8H | Up      |         |
| 50451 | Subdomain       | DELETED | Gateway   | 29118  | 0.0       | 9PdutHsdDSxcKUUyDg8ovS1KWh47qLT5R9h5uoFgRUH2 | Gateway |         |
| 50452 | Reverse_proxy   | DEPLOY  | Gateway   | 29118  | 0.0       | 9PdutHsdDSxcKUUyDg8ovS1KWh47qLT5R9h5uoFgRUH2 | Gateway |         |
| 50472 | Subdomain       | DELETED | Gateway   | 29118  | 0.0       | 9PdutHsdDSxcKUUyDg8ovS1KWh47qLT5R9h5uoFgRUH2 | Gateway |         |
| 50473 | Reverse_proxy   | DEPLOY  | Gateway   | 29118  | 0.0       | 9PdutHsdDSxcKUUyDg8ovS1KWh47qLT5R9h5uoFgRUH2 | Gateway |         |
| 50496 | Subdomain       | DELETED | Gateway   | 29118  | 0.0       | 9PdutHsdDSxcKUUyDg8ovS1KWh47qLT5R9h5uoFgRUH2 | Gateway |         |
| 50497 | Reverse_proxy   | DEPLOY  | Gateway   | 29118  | 0.0       | 9PdutHsdDSxcKUUyDg8ovS1KWh47qLT5R9h5uoFgRUH2 | Gateway |         |
| 50514 | Subdomain       | DELETED | Gateway   | 29118  | 0.0       | 9PdutHsdDSxcKUUyDg8ovS1KWh47qLT5R9h5uoFgRUH2 | Gateway |         |
| 50515 | Reverse_proxy   | DEPLOY  | Gateway   | 29118  | 0.0       | 9PdutHsdDSxcKUUyDg8ovS1KWh47qLT5R9h5uoFgRUH2 | Gateway |         |
| 50760 | Subdomain       | DEPLOY  | Gateway   | 29118  | 0.0       | 9PdutHsdDSxcKUUyDg8ovS1KWh47qLT5R9h5uoFgRUH2 | Gateway |         |
| 50761 | Reverse_proxy   | DEPLOY  | Gateway   | 29118  | 0.0       | 9PdutHsdDSxcKUUyDg8ovS1KWh47qLT5R9h5uoFgRUH2 | Gateway |         |
| 50762 | Container       | DEPLOY  | freefarm2 | 29117  | 0.0       | A54PL8EPQHC1SefcFcnLKaqurw8nBNTSFsFriYowYP1a | Up      |         |
| 71324 | Virtual_Machine | DELETED | freefarm  | 29116  | 3144874.0 | Hx4B6B8s8yQ5ABLStma1kZ33kCuprSxzU8tY4totKbWH | Up      |         |
| 72974 | Virtual_Machine | DEPLOY  | freefarm  | 29116  | 3144872.0 | 93qJrfeBqYiuVC973n9kPX79uA4rZU6oHL9pdJGBegHL | Up      |         |
| 78428 | Virtual_Machine | DELETED | freefarm  | 29116  | 3144872.0 | 3VBKrSTVieFzJ9Bv9MSzvQBQcTwnxgPhC9tMNsUsv5BH | Up      |         |
| 78430 | Virtual_Machine | DELETED | freefarm  | 29116  | 3144870.0 | 3VBKrSTVieFzJ9Bv9MSzvQBQcTwnxgPhC9tMNsUsv5BH | Up      |         |
| 78454 | Virtual_Machine | DEPLOY  | freefarm  | 29116  | 3144870.0 | 9Bkf6fmWkAh4kMgawjpP8N35Ybh1AhzaRHisBawR8ef3 | Up      |         |
