### ISSUE TITLE
Failed to find resources for hosted 3Bot deployment

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/js-sdk#3342]
User saw the following error message below when attempting to restart a 3Bot. The farm has plenty of resources, and the deployment succeeded on a subsequent attempt.

![image](https://user-images.githubusercontent.com/17682591/141050914-f62b2aa1-d7a4-40f3-9d27-0e01f4c0ce3f.png)

**Comment by xmonader** [comment]
please check what is happening here

**Comment by waleedhammam** [comment]
@scottyeager Can you please state which network and which farm ?
