### ISSUE TITLE
threebot server load test

### ISSUE THREAD

**Issue by alichaddad** [threefoldtech/js-sdk#339]
There have been some problems with Threebot server performance, need to perform load and test and determine the root issue.

**Comment by RafyAmgadBenjamin** [comment]
I have used Locust python package to do Load test
#### Testing using NGINX
- with 200 users and hatch rate (number of users to spawn per second) is 10 
![200User_10H](https://user-images.githubusercontent.com/46320202/88817787-39af4280-d1be-11ea-873e-101622cd2810.jpg)
- with 2000 users and hatch rate is 20 
![2000User_20H_before_update_nginx](https://user-images.githubusercontent.com/46320202/88817834-4af84f00-d1be-11ea-8ae0-41d9b4d8ca3f.jpg)

then we update Nginx configuration 
![Screenshot from 2020-07-29 16-50-22](https://user-images.githubusercontent.com/46320202/88817865-551a4d80-d1be-11ea-8840-a2662049cb55.png)
- with 2000 users and hatch rate is 20 
![image](https://user-images.githubusercontent.com/46320202/88817918-64999680-d1be-11ea-8a29-a1c36c3c97ee.png)

**Comment by RafyAmgadBenjamin** [comment]
##### commits 
https://github.com/threefoldtech/js-ng/commit/a7327f311471849c91f905290d3d0892e542e6e3
https://github.com/threefoldtech/js-ng/commit/2ca6104e3ab368dc64aa3fdc569ff0620dbed5cb

**Comment by RafyAmgadBenjamin** [comment]
I have added the code in js-sdk, update the docs and make the path as a parameter can be passed to the bash script
#### Commit
https://github.com/threefoldtech/js-sdk/commit/5d8f01a4ff4950952610927bf5074ac5335af80a

**Comment by RafyAmgadBenjamin** [comment]
Make the port can be passed as an option 
PR 
https://github.com/threefoldtech/js-sdk/pull/400
