### ISSUE TITLE
release 12.0.0

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#3412]
major release 12.0.0
requires https://github.com/threefoldtech/js-ng/issues/625

**Comment by xmonader** [comment]
please make sure it's 12.0.0 not 12.0 @rawdaGastan

**Comment by xmonader** [comment]
I forgot to merge this PR https://github.com/threefoldtech/js-sdk/pull/3411, let's do the release also after merging the dependabot PRs

**Comment by rawdaGastan** [comment]
It will wait for 
- https://github.com/threefoldtech/js-sdk/issues/3416
- https://github.com/threefoldtech/js-sdk/issues/3417
