### ISSUE TITLE
Can't deploy 3bot on container

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#346]
- [x] can't deploy 3bot on container
<img width="967" alt="Screenshot 2020-07-27 at 11 36 19" src="https://user-images.githubusercontent.com/43240801/88527676-e393a100-cffd-11ea-9cc6-e84fbbf42dfb.png">

@xmonader please assign to people and project accordingly

**Comment by xmonader** [comment]
also happened with @abom , need to be clear that it requires a network and harden that flow

**Comment by xmonader** [comment]
related error
![image](https://user-images.githubusercontent.com/64129/88598308-538b4100-d069-11ea-95eb-1719c2d284f3.png)
apparently that check needs to be disabled no need to validate the user on the explorer, because the marketplace OWNS the reservations

**Comment by waleedhammam** [comment]
fixed in: https://github.com/threefoldtech/js-sdk/pull/349

**Comment by waleedhammam** [comment]
please press reload the chatflow https://marketplace.grid.tf/
