### ISSUE TITLE
Installing external packages from admin panel clones the repo elsewhere

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/js-sdk#347]
The code is duplicated  when installing farmmanagement and codeserver packages from admin dashboard. In development mode this could be an issue where any changes in the source code don't reflect as the actual code used is the newly cloned code.

**Comment by rkhamis** [comment]
if a user wants to add it on their filesystem, they can do so

**Comment by sasha-astiadi** [comment]
whats the status of this @rkhamis  is it still valid / will we do this for grid 2.3 project? im doing a cleanup. thank you

**Comment by rkhamis** [comment]
as you can see, @sasha-astiadi it's a feature request that we decided not to address yet. it's good to have it tracked for further discussion if needed, but it's not attached to a project because it has not been accepted

**Comment by xmonader** [comment]
@abom this is resolved now correct? if so please move to verification of 11.2
