### ISSUE TITLE
Add mattermost solution

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/js-sdk#350]
[mattermost](https://mattermost.org/)
- [x] dockerfile in https://github.com/threefoldtech/tf-images
- [x] flist
- [x] admin solution
- [x] marketplace solution

**Comment by dmahmouali** [comment]
Added:
    - Dockerfile: https://github.com/threefoldtech/tf-images/tree/master/mattermost
    - Flist: https://hub.grid.tf/ayoubm.3bot/rafyamgadbenjamin-mattermost-latest.flist

**Comment by hossnys** [comment]
verified

![Screenshot from 2020-08-24 18-19-10](https://user-images.githubusercontent.com/26298009/91069988-6710d400-e636-11ea-82b0-aacd04734df1.png)

![Screenshot from 2020-08-24 18-21-50](https://user-images.githubusercontent.com/26298009/91069990-68da9780-e636-11ea-8ba4-0eff015d5b7d.png)

![Screenshot from 2020-08-24 18-22-16](https://user-images.githubusercontent.com/26298009/91069996-69732e00-e636-11ea-843e-7161117f8ac2.png)
