### ISSUE TITLE
Adding Gollum solution chatflow

### ISSUE THREAD

**Issue by AhmedSa-mir** [threefoldtech/js-sdk#351]
[Gollum](https://github.com/gollum/gollum): A simple, Git-powered wiki with a sweet API and local frontend.
- [x] Flist
- [x] Solution chatflow
- [x] Save repo remotely to avoid losing data on container failure
- [x] Support working on https

**Comment by AhmedSa-mir** [comment]
Moved out of alpha3 and to next milestone

**Comment by sasha-astiadi** [comment]
whats the status of this @rkhamis   is it still valid / will we do this for grid 2.3 project? im doing a cleanup. thank you
