### ISSUE TITLE
Enhance admin dashboard to render readable data in workload details [development_enhance_dashboard]

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/js-sdk#354]
![image](https://user-images.githubusercontent.com/36021484/88669493-40698700-d0e4-11ea-91b9-c922e586d41f.png)

**Comment by dmahmouali** [comment]
Used new json viewer
![image](https://user-images.githubusercontent.com/36021484/88814780-d839a480-d1ba-11ea-81db-c695e13a0f3b.png)
and added new details view
![image](https://user-images.githubusercontent.com/36021484/88814877-f43d4600-d1ba-11ea-9841-79b00c95b400.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
