### ISSUE TITLE
please import PR from https://github.com/threefoldtech/jumpscaleX_threebot/pull/727

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/js-sdk#355]

**Comment by m-motawea** [comment]
@zaibon can we close this one?

**Comment by zaibon** [comment]
sorry, I'll reopen until I have time to test this properly. Last time I tried it still didn't work, but I need to test with latest code

**Comment by zaibon** [comment]
I did try the delete node feature. This is still buggy. It seems whatever node is selected to be deleted it's always the last one from the table that gets deleted. Probably a bug in the javascript code that trigger the delete.

**Comment by xmonader** [comment]
@DylanVerstraete was kind enough to help, he apparently knows where is the issue coming from :)

**Comment by DylanVerstraete** [comment]
Since we added a `deleted` field on a node instead of deleting a node from the db the UI needs to adapt. When we fetch the nodes we should filter on those that have the `deleted` fields as false.

The node deletion still works but it was the table rendering that gave issues.

**Comment by zaibon** [comment]
When you list nodes, by default node marked as deleted are not shown. So I don't think this is the problem. Or this means there is a bug and deleted node are not filtered out
