### ISSUE TITLE
feature request: import network inside deployed threebot

### ISSUE THREAD

**Issue by nbabenko** [threefoldtech/js-sdk#358]
Would be good to add ability to import networks into my deployed 3bot. 
Right now I have to create networks 2 times (one from marketplace and another one for container after 3bot is launched). 

Reproduce steps:
1. Go to a marketplace https://marketplace.grid.tf/marketplace
2. Deploy a new network
3. Deploy a threebot
4. Open threebot
5. No networks inside

Expected result:
5. Ability to import existing network inside of threebot
OR
5. Existing network that Ive deployed on marketplace is visible in threebot (if possible)

**Comment by sasha-astiadi** [comment]
whats the status of this @rkhamis   is it still valid / will we do this for grid 2.3 project? im doing a cleanup. thank you

**Comment by xmonader** [comment]
3bot is bound to a mgmt network and in case of a 3bot container hosted on the grid you won't be able to change the network
