### ISSUE TITLE
show clock with utc time for the users on the dashboard and the marketplace

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#365]
show clock with utc time for the users on the dashboard and the marketplace because I think now people expect it works against their timezone.

**Comment by abom** [comment]
https://github.com/threefoldtech/js-sdk/pull/394

**Comment by abom** [comment]
https://github.com/threefoldtech/js-sdk/pull/394

**Comment by siddiquagig** [comment]
UTC Time is there:

![image](https://user-images.githubusercontent.com/25789724/90003372-07651100-dca5-11ea-93aa-f04476e10931.png)
