### ISSUE TITLE
disable bcdb client

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#368]
it's using GRPC atm and we removed GRPC as a dependency in js-sdk

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 2d8dae1bdee0fcdc9520e64cfd011ee3ad94a209 , **Branch** development_capacitypool

![ff](https://user-images.githubusercontent.com/21218053/91032306-11bacf80-e602-11ea-9907-aeea65788578.png)
