### ISSUE TITLE
end 2 end tutorial

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#37]
End 2 End tutorial that explains the following from the very beginning

- [x] getting 3sdk
- [x] creating the environment
- [x] configuring your identity
- [x] having a wallet
- [x] making a reservation from the command line (check zos docs in the wiki)
- [x] getting into the admin panel
- [x] making a reservation from the admin panel

**Comment by BolaNasr** [comment]
making reservation from the command line: https://github.com/threefoldtech/js-sdk/pull/42

**Comment by waleedhammam** [comment]
https://github.com/threefoldtech/js-sdk/blob/development_sdk_solutions/docs/wiki/quick_start.md

**Comment by ranatrk** [comment]
getting into admin panel + making a reservation through admin panel : https://github.com/threefoldtech/js-sdk/commit/9b238ef3cff4f2cf79acb038887d9c010cdaade5#diff-e5a068848a7c5e69d633b07e9def9ef0

**Comment by RafyAmgadBenjamin** [comment]
i will verify this

**Comment by RafyAmgadBenjamin** [comment]
- [ ] getting 3sdk
- [ ]  creating the environment
- [ ] configuring your identity
- [ ]  having a wallet
- [ ]  making a reservation from the command line (check zos docs in the wiki)
- [ ] getting into the admin panel
- [ ]  making a reservation from the admin panel
