### ISSUE TITLE
Marketplace: expiration time can not be reserved for network when using Safari

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/js-sdk#372]
ether recommend chrome as the browser to use or fix the issue in safari

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/18591016/89051124-0f8f8900-d354-11ea-9b52-c5b68917762f.png">

**Comment by xmonader** [comment]
added recommendation to use chrome https://github.com/threefoldtech/js-sdk/commit/545f2dba57a5e48f7e7231ba91b311a6acc94d10
