### ISSUE TITLE
Farm Management: Users should be able to move farms to another 3bot

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/js-sdk#373]
Farmers might want to move the farm managemnt of a particular farm to another 3bot. would be great to have this feature.

**Comment by zaibon** [comment]
This is already supported by the explorer API. Farmer can change the owner of a farm. 
Not sure the farm management dashboard allows it though.

**Comment by zaibon** [comment]
https://github.com/threefoldtech/js-sdk/pull/484
