### ISSUE TITLE
Marketplace: Add text with prerequisites users need to have before they start

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/js-sdk#374]
Would be great to have a short text of what marketplace users need to hav ein place before they dive in.
Somethink like a checklist: 3bot connect installed, any form of TFT in the wallet, wireguard installed, use chrome, ...

**Comment by sasha-astiadi** [comment]
https://manual2.threefold.io/#/getting_started

**Comment by abom** [comment]
Added this link to the confirmation dialog that's shown when accepting terms:

https://manual-testnet.threefold.io/#/getting_started


![Screenshot from 2020-08-30 20-02-46](https://user-images.githubusercontent.com/511438/91666283-c91c7e00-eafb-11ea-983d-0f9f42d2dec4.png)


Please confirm the correct link and phrasing.

@xmonader

**Comment by abom** [comment]
I think we can remove this, and show the full terms and conditions instead of linking it (at least to be consistent with the terms shown inside the demo/marketplace)

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-08-31 15-18-20](https://user-images.githubusercontent.com/26298009/91724010-ec4b3a00-eb9c-11ea-98d0-031503aa303d.png)
