### ISSUE TITLE
Show somewhere on the dashboard which network the user is currently connected to

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/js-sdk#383]
At the moment, there is no really a way to know which network the dashboard is connected to.
Maybe we could add that information in the top left corner under the user name and address ?

Also there should be more guidance to show how to change identity/network. Now it is possible but hard to find.

**Comment by abom** [comment]
https://github.com/threefoldtech/js-sdk/pull/394

**Comment by zaibon** [comment]
UI wise we are ok. But when we change the identity from the setting. the network show on the top right corner is not updated.

**Comment by Dina-Abd-Elrahman** [comment]
- **Commit_ID** : d05dc04fe1bfd3f6f8f6f8a298090976e8eeac22 , **Branch** development_capacitypool.

## Verification steps:

- Check the explorer in the dashboard which I'm connected to.

![ff](https://user-images.githubusercontent.com/21218053/90641368-71476280-e231-11ea-8c0a-5ec1fe5e39a1.png)

- When I change the identity the explorer is changed based on it. 

![ff1](https://user-images.githubusercontent.com/21218053/90642049-34c83680-e232-11ea-84eb-d22255e15b12.png)
