### ISSUE TITLE
Extending a pool should not be hidden behind a new button

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/js-sdk#385]
If you want to extend an existing pool, the user have to press the `new` button. This is very intuitive and there is nothing that gives you a hint that you might be able to extend a pool clicking this new button.

**Comment by siddiquagig** [comment]
Verified
Extend Button is there now

![image](https://user-images.githubusercontent.com/25789724/90006153-6e84c480-dca9-11ea-9ca0-69c92bd46ab9.png)
