### ISSUE TITLE
update gitea flist with new one that support 3bot login

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/js-sdk#388]
we already have gitea images on solutions that using normal login but now we have a new image support 3bot login , need to create/replace exist image  in official images
new image below 
https://github.com/threefoldtech/tf-images/tree/master/gitea_3bot

**Comment by BolaNasr** [comment]
gitea flist updated : https://hub.grid.tf/tf-official-apps/gitea-latest.flist

**Comment by Pishoy** [comment]
already updated
