### ISSUE TITLE
sdk chat solutions

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#4]
Development:
- [x] network
- [x] ubuntu
- [x] flist
- [x] minio
- [x] minio with masterslave
- [x] k8s
- [x] domain with 3 thingies.
  - [x] domain delegate
  - [x] 4to6
  - [x] solution expose
- [x] monitoring
- [x] gitea

Verification:
- [x] network
- [x] ubuntu
- [x] flist
- [x] minio
- [x] minio with masterslave
- [x] k8s
- [x] domain with 3 thingies.
  - [x] domain delegate
  - [x] solution expose
      - [x] Managed Domains 
          - [x] Ubuntu
          - [x] k8s
          - [x] Minio
          - [x] Flist
          - [x] gitea
      - [x] Delegate Domains
          - [x] Ubuntu
          - [x] k8s
          - [x] Minio
          - [x] Flist
          - [x] gitea
      - [x] Custom Domains
          - [x] Ubuntu
          - [x] k8s
          - [x] Minio
          - [x] Flist
          - [x] gitea
    - [x] 4to6 
- [x] monitoring
- [x] gitea

Package: https://github.com/js-next/js-sdk/tree/development_sdk_solutions/jumpscale/packages/tfgrid_solutions

- [x] bring back validate user when auth is there: https://github.com/threefoldtech/js-sdk/issues/13

**Comment by xmonader** [comment]
blocked on reservation 

https://github.com/js-next/js-ng/issues/276

**Comment by m-motawea** [comment]
working on network chatflow

**Comment by waleedhammam** [comment]
Latest progress
- fixed explorer models and several issues
- reached the 2nd step of chatflow and got rid

![Screenshot from 2020-06-08 21-24-34](https://user-images.githubusercontent.com/10658229/84072231-2a3a2700-a9cf-11ea-9dd7-5c3161c416a9.png)

**Comment by waleedhammam** [comment]
Network chatflow is now ok

![Screenshot from 2020-06-09 12-11-28](https://user-images.githubusercontent.com/10658229/84135703-960da580-aa4a-11ea-8e88-f716b781f8c4.png)
![Screenshot from 2020-06-09 12-11-20](https://user-images.githubusercontent.com/10658229/84135738-9c9c1d00-aa4a-11ea-9ea0-ef5f3cca41a6.png)
![Screenshot from 2020-06-09 12-11-15](https://user-images.githubusercontent.com/10658229/84135754-a291fe00-aa4a-11ea-950f-8d368d2d6b59.png)
![Screenshot from 2020-06-09 12-11-10](https://user-images.githubusercontent.com/10658229/84135772-a887df00-aa4a-11ea-83e8-89f1eac9e07e.png)
![Screenshot from 2020-06-09 12-09-41](https://user-images.githubusercontent.com/10658229/84135794-ae7dc000-aa4a-11ea-82c6-9fa50dd77762.png)
![Screenshot from 2020-06-09 12-09-20](https://user-images.githubusercontent.com/10658229/84135810-b3427400-aa4a-11ea-88b2-639587c6962f.png)

**Comment by waleedhammam** [comment]
working with @m-motawea  on ubuntu chatflow now

**Comment by waleedhammam** [comment]
Ubuntu chatflow is ok

![Screenshot from 2020-06-09 14-41-59](https://user-images.githubusercontent.com/10658229/84148908-f1965e00-aa5f-11ea-81e5-308be4600d1c.png)
![Screenshot from 2020-06-09 14-35-15](https://user-images.githubusercontent.com/10658229/84148917-f4914e80-aa5f-11ea-8296-4c79a8adbb40.png)
![Screenshot from 2020-06-09 13-57-29](https://user-images.githubusercontent.com/10658229/84148924-f6f3a880-aa5f-11ea-8e7a-0a3ccb323485.png)
![Screenshot from 2020-06-09 13-35-17](https://user-images.githubusercontent.com/10658229/84148929-f8bd6c00-aa5f-11ea-9205-7f85c3ff307a.png)

**Comment by waleedhammam** [comment]
Chats package: https://github.com/js-next/js-sdk/tree/development_sdk_solutions/jumpscale/packages/tfgrid_solutions

**Comment by m-motawea** [comment]
Flist chatflow is ok
![image](https://user-images.githubusercontent.com/32568986/84157741-60c57f80-aa6b-11ea-875f-c1e39dcd247c.png)

**Comment by waleedhammam** [comment]
kubernetes
![Screenshot from 2020-06-09 17-07-16](https://user-images.githubusercontent.com/10658229/84165387-ef3dff00-aa73-11ea-88fd-99ace32d2c4d.png)
![Screenshot from 2020-06-09 16-35-37](https://user-images.githubusercontent.com/10658229/84165389-f06f2c00-aa73-11ea-9040-dab7fb2c43a9.png)

**Comment by waleedhammam** [comment]
Minio
![Screenshot from 2020-06-09 20-47-03](https://user-images.githubusercontent.com/10658229/84187845-edcfff00-aa92-11ea-93eb-8959cfdc3750.png)
![Screenshot from 2020-06-09 20-39-06](https://user-images.githubusercontent.com/10658229/84187850-ef99c280-aa92-11ea-9256-cd6d97e3e95f.png)
![Screenshot from 2020-06-09 20-38-08](https://user-images.githubusercontent.com/10658229/84187851-ef99c280-aa92-11ea-9aee-10238da4189c.png)
![Screenshot from 2020-06-09 20-37-41](https://user-images.githubusercontent.com/10658229/84187854-f0325900-aa92-11ea-90f9-733ca9e59864.png)

**Comment by waleedhammam** [comment]
gitea chatflow done
![Screenshot from 2020-06-11 16-51-30](https://user-images.githubusercontent.com/10658229/84401750-eb40e700-ac03-11ea-8bd9-fae1e062bcff.png)

**Comment by waleedhammam** [comment]
TODO: General verifications

**Comment by BolaNasr** [comment]
General verification of all chatflows

**Comment by BolaNasr** [comment]
Verified all chatflows
