### ISSUE TITLE
Missing Favicon for the Marketplace

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#401]
Please insert a  favicon for marketplace. small detail but important.
<img width="86" alt="Screenshot 2020-08-06 at 13 28 36" src="https://user-images.githubusercontent.com/43240801/89527114-18b3a680-d7e9-11ea-88de-601e72811c47.png">

**Comment by xmonader** [comment]
@sasha-astiadi please provide us with favicon
