### ISSUE TITLE
load testing: separate threebot from gedis tests

### ISSUE THREAD

**Issue by abom** [threefoldtech/js-sdk#409]
Create another script for gedis only (beside `admin.py` at https://github.com/threefoldtech/js-sdk/tree/development/tests/loadtesting

**Comment by RafyAmgadBenjamin** [comment]
PR: 
https://github.com/threefoldtech/js-sdk/pull/418

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** b9f63af370e9c8716aec220edeb487a5dd01877c , **Branch** development

## Verification steps:

as per a readme here https://github.com/threefoldtech/js-sdk/tree/development/tests/loadtesting

- Install Locust outside of js-sdk environment.

``` pip3 install locust ```

- Once Locust is installed, a locust command should be available in your shell.

``` locust --help ```

![ff](https://user-images.githubusercontent.com/21218053/91155137-b56bb480-e6c2-11ea-9932-cd96f724b032.png)

- Run load test :
 
-- in another shell start threebot `threebot start`

-- Execution:

`bash tests/loadtesting/run_locust.sh -u 200 -r 10 -h https://localhost -p tests/loadtesting/admin.py`

![ff1](https://user-images.githubusercontent.com/21218053/91155651-6b370300-e6c3-11ea-91b3-d620b3b77f8f.png)

-- for Gedis endpoint:

`bash tests/loadtesting/run_locust.sh -u 200 -r 10 -h http://localhost:8000 -p tests/loadtesting/admin_gedis.py`

![ff2](https://user-images.githubusercontent.com/21218053/91155880-b51fe900-e6c3-11ea-8aa3-b7670661ca17.png)
