### ISSUE TITLE
minio-wizard: zdb asks if which pool, and if you want automatic select node for namespace for each zdb

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/js-sdk#411]
In large setups (16/4) or even bigger, this is annoying to select the same setup for each single zdb. It's either one choice for all (automatic select, and pool) or only ask for customization if required by the user.

Also the data/parity ration doesn't have to equal the number of zdbs, I can have 10 zdbs with 3/1 data/parity ration. (but number of zdbs can't be lower than 3+1)

**Comment by zaibon** [comment]
> Also the data/parity ration doesn't have to equal the number of zdbs,

Actually this is even recommended to have more shards then required by the storage policy. Reason is, if you have a policy of 16/4 and only have 20 shards, if any of your shards goes down, you loose the write capability. So usually you want to have a little more shards the minimally required.

**Comment by m-motawea** [comment]
this was already updated. please pull the latest changes.
zdb placement is done in one step.
![image](https://user-images.githubusercontent.com/32568986/89726984-323f3300-da21-11ea-9807-cdea05bc8340.png)
