### ISSUE TITLE
mastodon solution

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#420]
https://joinmastodon.org

- [ ] flist: https://github.com/threefoldtech/tf-images/blob/master/mastodon (please review what been done there)
- [x] admin solution
- [ ] marketplace solution

**Comment by Pishoy** [comment]
flist done https://hub.grid.tf/bishoy.3bot/threefolddev-mastodon-latest.flist

entrypoint is /start_mastodon.sh as per repo

**Comment by ranatrk** [comment]
[development_mastodon]
WIP : created chatflow to deploy mastodon on a container https://github.com/threefoldtech/js-sdk/commit/4ce5309d44403007ee3835c72321c77ddee5a319

**Comment by ranatrk** [comment]
latest progress: 
https://github.com/threefoldtech/js-sdk/commit/f9da25e764bbd1243c3978a7ab32cb88c81cd389

Currently blocked on : https://github.com/threefoldtech/zos/issues/885 
The issue appears when using testnet or mainnet. Can't test on devnet as there are no gateways available on it

**Comment by ranatrk** [comment]
Blocked on flist not working correctly, emails are not sent when signing up

**Comment by sasha-astiadi** [comment]
whats the status of this @rkhamis   is it still valid / will we do this for grid 2.3 project? im doing a cleanup. thank you
