### ISSUE TITLE
discourse solution

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#424]
- [x] flist https://github.com/threefoldtech/tf-images/blob/master/discourse_3bot/README.md
- [x] admin solution
- [x] marketplace solution

**Comment by OmarElawady** [comment]
Currently, there's an admin dashboard to deploy the solution on the grid. The startup script runs successfully and the site is served but I'm currently investigating the following issues:
1. The redis server fails to initialize in the start up and the log says it can't access its config file but it runs normally using `redis-server --daemonize yes` (only on core x)
2. Same for ssh (on the docker local image and on core x).
3. The website returns an internal server error when trying to login with threebot and the error message is that it can't get a public key.
4. A bad gateway error is returned after completing the 3rd step out of 14 in setting up the admin account.

**Comment by OmarElawady** [comment]
I solved 3 of the previous issues:
1. Supervisor runs the redis server with the user `redis` but the file `/etc/redis/redis.conf` have root as the owner and permissions 644, so redis doesn't have access to it. I chmoded it to 666.
2. Still ssh doesn't get initalized. P.S. there's a branch in discourse docker repo called `sshd_fix`.
3. An issue with the threebot private key (was using uuid). I generated a new signing key for each instance using nacl.
4. Magically disappeared.

Currently, all works well and the site gets up successfully but it's accessed with an ip address. I made a new image to use certbot to issue a certificate but was unable to convert it to flist. (See [#43](https://github.com/threefoldtech/0-hub/issues/43))

**Comment by OmarElawady** [comment]
The domain and https is now working (but using --test-cert until the issuance rate limit is solved) in #472.

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-08-25 17-20-54](https://user-images.githubusercontent.com/26298009/91194285-4dd05c00-e6f8-11ea-95f8-fdd7190bcf66.png)

![Screenshot from 2020-08-25 17-24-28](https://user-images.githubusercontent.com/26298009/91194293-4f018900-e6f8-11ea-90ba-398986eb7e3a.png)

![Screenshot from 2020-08-25 17-25-06](https://user-images.githubusercontent.com/26298009/91194301-50cb4c80-e6f8-11ea-83ea-5665edc63433.png)

![Screenshot from 2020-08-25 17-28-13](https://user-images.githubusercontent.com/26298009/91194311-52951000-e6f8-11ea-8acd-7728cfb349b8.png)

![Screenshot from 2020-08-25 17-28-56](https://user-images.githubusercontent.com/26298009/91194316-532da680-e6f8-11ea-8aa1-fe1fb49fe574.png)

![Screenshot from 2020-08-25 17-30-15](https://user-images.githubusercontent.com/26298009/91194322-545ed380-e6f8-11ea-93bd-31b99351dd47.png)
