### ISSUE TITLE
taiga solution

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#427]
- [x] flist whatever works 
  - https://github.com/threefoldtech/tf-images/tree/master/taiga
  - https://github.com/threefoldtech/tf-images/tree/master/taiga_3bot

- [x] admin solution
- [x] marketplace solution
- [x] align with apps

**Comment by waleedhammam** [comment]
I'll use this one: https://github.com/threefoldtech/tf-images/tree/master/taiga_3bot (all in one)

**Comment by waleedhammam** [comment]
Flist has some issues with zos container

**Comment by waleedhammam** [comment]
Updated chatflow. restore letsencrypt and domain stuff when its back

**Comment by waleedhammam** [comment]
reopend to refactor to be aliened with other apps

**Comment by hossnys** [comment]
i've deployed taiga successfully but when going to the solution link it didn't work with https but wiht http it shows the error in last image , also do we publishing the orginal tiaga or our rebranded fork as i see this is not the original tiaga app ?

![Screenshot from 2020-08-25 17-34-56](https://user-images.githubusercontent.com/26298009/91195771-9b999400-e6f9-11ea-8bff-db4b41160127.png)

![Screenshot from 2020-08-25 17-36-17](https://user-images.githubusercontent.com/26298009/91195793-a05e4800-e6f9-11ea-9b61-2986afbc834e.png)

![Screenshot from 2020-08-25 17-37-32](https://user-images.githubusercontent.com/26298009/91195797-a18f7500-e6f9-11ea-85ba-295c68a453c4.png)

**Comment by hossnys** [comment]
the last deployment was on node in mazraa farm with reservation id : 468891 and didn't work fine , but when trying on freefarm  it works fine and logged in with 3bot login successfully , and as i got from Waleed that we are publishing our rebranded version of tiaga.

![Screenshot from 2020-08-25 18-07-29](https://user-images.githubusercontent.com/26298009/91199573-56c42c00-e6fe-11ea-84fb-e08b41f35530.png)

![Screenshot from 2020-08-25 18-02-39](https://user-images.githubusercontent.com/26298009/91199566-5592ff00-e6fe-11ea-9b41-412cdf993d2a.png)
