### ISSUE TITLE
Extending pool with X units, double the existing units + X units

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#440]
**Env:** testnet
**Branch:** development_capacitypool

![image](https://user-images.githubusercontent.com/41957921/89771590-dcda5300-db00-11ea-9985-136539ffd229.png)

### Expected Result
```
cus = 8
sus = 8
```

**Comment by AhmedHanafy725** [comment]
The extend object
![image](https://user-images.githubusercontent.com/41957921/89775134-799fef00-db07-11ea-98ea-158459def485.png)

**Comment by xmonader** [comment]
shouldn't be an issue anymore.
