### ISSUE TITLE
create nginx exposed proxy flist

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#441]
We have multiple solutions requiring a proxy to expose the solution on https and http with trusted certificates

so we need to have an nginx flist that also contains trc, initialized with additional environment variables than the trc one
* DOMAIN: used as server name in nginx config
* ENFORCE_HTTPS: check if defined then configure nginx to redirect http to https
* PORT: http port of the backend application
* IP_ADDRESS: ip address of the backend server
* TFGATEWAY: name or ip address of the tfgateway followed by the tcprouter port (eg: `localhost:9800`)

trc requires variable `TRC_SECRET`, the one used to reserve the tcp_proxy on the gateway. its format is `{tid}:{arbitary_value}`

start trc as part of the entrypoint like.
```
/trc -local 127.0.0.1:80 -local-tls 127.0.0.1:443 -remote $TFGATEWAY &
```

the entrypoint should use certbot to configure nginx certs.

the method defined in deployer exposes the given address using trc only. defined here https://github.com/threefoldtech/js-sdk/blob/development_capacitypool/jumpscale/sals/reservation_chatflow/deployer.py#L1026
we need to have a similar method that deploys using the newly created image

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 0b5ca86c064b5115f09eb0f01775e7dd479ba31d , **Branch** development_capacitypool

![ff](https://user-images.githubusercontent.com/21218053/91195143-0f876c80-e6f9-11ea-84ec-a616416a7e8e.png)
