### ISSUE TITLE
Pool is required error on devnet

### ISSUE THREAD

**Issue by maxux** [threefoldtech/js-sdk#444]
Trying to deploy a network on devnet using my 3bot. 3bot installed using `threebot start` on latest sdk available on github.
On network page, giving a name, all the rest by default (ipv6, range auto selected), end with:
```
The following error occured: pool is required
```

**Comment by waleedhammam** [comment]
Have you created a pool with your 3bot to deploy the network on ?

**Comment by rkhamis** [comment]
solutions now check for nw and pool before starting
