### ISSUE TITLE
Install packages via UI

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#46]
![Screenshot from 2020-06-19 01-18-32](https://user-images.githubusercontent.com/10658229/85080934-d0094500-b1ca-11ea-91dd-672036eefff9.png)

redirects me to the same page

**Comment by BolaNasr** [comment]
it works good
just
 ```
server = j.servers.threebot.get("default")
server.start()
```
Then press Install package in admin dashboard and then refresh 
![image](https://user-images.githubusercontent.com/10259267/85225513-3dd38d80-b3d2-11ea-9f07-104c686fc182.png)

**Comment by xmonader** [comment]
which commit fixed it?

**Comment by BolaNasr** [comment]
After pull and fix niginx problem , it works

**Comment by waleedhammam** [comment]
Indeed it worked.

I think the reason because I was using instance name different than `default` on that machine

@xmonader @BolaNasr you created an issue for that already ?

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
