### ISSUE TITLE
Chatflow of creation 3Bot in marketplace asks for branch without guidance

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#474]
I created a 3Bot in the marketplace. 
A question raised is which branch you want to use, in freetext, without guidance. 

People will get lost seeing this info, ex. will want to have a 'production version'. 
<img width="1280" alt="Schermafbeelding 2020-08-12 om 15 17 40" src="https://user-images.githubusercontent.com/30384423/90021378-72b4e000-dcb1-11ea-9fd1-1822c3623da3.png">

**Comment by gmachtel** [comment]
Maybe for now stating "If unsure, leave the prefilled text untouched" can do.
But in the longer run, I'd select a branch myself and not let the user choose. If staging threebot, then maybe also linked to a staging marketplace website.

**Comment by waleedhammam** [comment]
we don't ask for branch anymore, it uses latest development
