### ISSUE TITLE
when creating domains replace _ or any invalid domain characters

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#477]
make sure to replace _ with - and any invalid character with "" maybe.

**Comment by hossnys** [comment]
this seems to be not working well 

![Screenshot from 2020-08-23 17-51-47](https://user-images.githubusercontent.com/26298009/91055992-ad116c00-e625-11ea-9dd0-fd50f785e729.png)
![Screenshot from 2020-08-23 17-52-17](https://user-images.githubusercontent.com/26298009/91055995-ae429900-e625-11ea-90ce-3b223e7e2b57.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 3faf52c9a846f2ee6f5a64307c5afcf1f1d2468f , **Branch** development

![ff8](https://user-images.githubusercontent.com/21218053/91665452-f2d2a680-eaf5-11ea-8b67-cc5e4b832b4a.png)
![ff9](https://user-images.githubusercontent.com/21218053/91665453-f5350080-eaf5-11ea-872e-100a046ef379.png)
