### ISSUE TITLE
3Bot creation on marketplace keeps in spinning

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#479]
Chatflow keeps on spinning in initialisation phase of threebot creation, with error at the end. 

<img width="1280" alt="Schermafbeelding 2020-08-12 om 16 16 36" src="https://user-images.githubusercontent.com/30384423/90026329-7481a200-dcb7-11ea-95c3-44bf60851418.png">

<img width="647" alt="Schermafbeelding 2020-08-12 om 16 20 01" src="https://user-images.githubusercontent.com/30384423/90026618-d2ae8500-dcb7-11ea-891b-5d2e28c81142.png">

**Comment by scottyeager** [comment]
I saw this too, but the 3Bot was actually created and visible by going back to the Threebot tab.

**Comment by gmachtel** [comment]
Seems OK now. Many updates done, was probazbly part of it. Some action taken to make all more robust.
