### ISSUE TITLE
If the last network solution with the same name is canceled the other ones are irrelevant

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/js-sdk#48]
in call `get_solutions(Network)` if the last network solution with the same name is **canceled** the other ones are irrelevant, It should be ignored so.

**Comment by ranatrk** [comment]
**Approach tried:(will be disgarded)** Get all networks with this name from deleted and deployed networks and check if it was deleted then this network is not considered, if it is still deployed then it is considered. 
this approach is too slow as by time the number of total reservations will increase and considering deleted reservations is not effiecient

**Suggested approach**: After discussing with @grimpy  and @zaibon, the suggested approach to be implemented is saving the parent of the network being created in the reservation's metadata and so when checking for a network will only look at the parent reservation of it (linked list approach) and so on to know if the network is deployed or deleted

**Comment by BolaNasr** [comment]
**Verified**
create network -> create 2 ubuntu conatiner 
Delete network -> refresh multiple time and close and open server ( still deleted )
