### ISSUE TITLE
in case of multiple users, chatflows that requires payment don't recognize the user doesn't have a wallet

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#49]
you shouldn't start any chatflow without actually configuring a wallet? or be able to jump back to its history after creating a wallet to continue

**Comment by grimpy** [comment]
We also have the QR code method so people can always use a 3rd party tool to do the payment. Saying that a wallet is required seems a bit much... maybe we can add an option on this page to 'reload' wallets with a hyperlinks to the wallet manager to create/improt one?

**Comment by xmonader** [comment]
> We also have the QR code method so people can always use a 3rd party tool to do the payment. Saying that a wallet is required seems a bit much... maybe we can add an option on this page to 'reload' wallets with a hyperlinks to the wallet manager to create/improt one?

I like this one better for sure (y)
