### ISSUE TITLE
provide a little bit more of help when it comes to coreX in chatflows

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#492]
![image](https://user-images.githubusercontent.com/64129/90182128-c4dd2a80-ddb1-11ea-9d76-d0ca8e9d2408.png)

I can see the list of processes, but the information should include what is needed to start a process 
e.g `CONTAINERIP:COREX_PORT/api/process/start?arg[]=/bin/bash`

**Comment by rkhamis** [comment]
link to docs of corex during chatflow

**Comment by BolaNasr** [comment]
Commit : https://github.com/threefoldtech/js-sdk/commit/87a9105a8aa4111086e594e06ec81c56213be641

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 0b5ca86c064b5115f09eb0f01775e7dd479ba31d , **Branch** development_capacitypool

![ff](https://user-images.githubusercontent.com/21218053/91178916-1e185880-e6e6-11ea-8400-21377fbe6933.png)
