### ISSUE TITLE
update quickstart document

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#495]
- covers installation
- starting local threebot
- adding funds to wallets (From dashboard only) and link to using CLI doc

**Comment by BolaNasr** [comment]
https://github.com/threefoldtech/js-sdk/pull/499/commits/a64ef9a92fc7ecf5e81d9cd0e8a81bb0b52c1f11

**Comment by siddiquagig** [comment]
Doc here is updated : [Link](https://github.com/threefoldtech/js-sdk/blob/development_capacitypool/docs/wiki/quick_start.md)
