### ISSUE TITLE
Enhance/Refactor staging marketplace apps chatflows

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#502]
work in: [development_capacitypool_apps_refactor](https://github.com/threefoldtech/js-sdk/tree/development_capacitypool_apps_refactor)

- [x] Make a base sal/tool to gather common methods

Refactor apps
- [x] mattermost
- [x] peertube
- [x] cryptopad
- [x] taiga
- [x] publisher with 3 chats (wiki, blog, website)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 85914667d13dae8f98cae522ef1db58ebd192cea , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91415022-b0873c00-e84d-11ea-9057-69f0869d54f2.png)
