### ISSUE TITLE
Show a proper default page for 3bot

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#505]
doing `threebot start --local` can lead to the default nginx page

![Screenshot from 2020-08-17 12-37-11](https://user-images.githubusercontent.com/10658229/90387414-656b6d00-e086-11ea-9f70-ea6f26599e63.png)

- redirection to admin panel before caused some issues
- maybe we can change the default page so that it can guide users

**Comment by RafyAmgadBenjamin** [comment]
#### Fixed
branch `development_nginx_default_page`

#### Commit
a468cd813aa004a82cd8266cb5de0eadb8b06b9b
20125415b3967b2db78851415ae4c44ba90f12fc

Update Nginx configuration to load our default HTML page



![image](https://user-images.githubusercontent.com/46320202/90662247-6946ed00-e248-11ea-9fc6-8544e3d9ca37.png)

**Comment by rkhamis** [comment]
blocked on #249

**Comment by abom** [comment]
https://github.com/threefoldtech/js-sdk/issues/249 should be resolved now.

**Comment by RafyAmgadBenjamin** [comment]
#### commit 
c9191d265f05556b0e2a464c3390f5c5e0fa1098
#### HTTP
![image](https://user-images.githubusercontent.com/46320202/91853112-07cc4880-ec62-11ea-9160-614c1a47e1ac.png)
#### HTTPs
![image](https://user-images.githubusercontent.com/46320202/91853166-187cbe80-ec62-11ea-8b40-87118a86babb.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** dd8cc25d86bc6d1cf78cd7c296eb2ab6ea0b24dd , **Branch** development

It works fine for https, but doesn't work for http

**HTTPs**

![ff](https://user-images.githubusercontent.com/21218053/91871563-8c759180-ec77-11ea-8d1e-278202fcfafd.png)
![ff2](https://user-images.githubusercontent.com/21218053/91871633-90a1af00-ec77-11ea-999e-40985c3ec124.png)


**HTTP**

![ff1](https://user-images.githubusercontent.com/21218053/91871755-98f9ea00-ec77-11ea-916a-e554a24dcf33.png)

**Comment by RafyAmgadBenjamin** [comment]
I have retested it on the same ports are using
It is working on port `8443` HTTPS
![image](https://user-images.githubusercontent.com/46320202/91955262-36e6c680-ed03-11ea-83c3-789bb7b95b6a.png)

It is working on port `8081` HTTP 
![image](https://user-images.githubusercontent.com/46320202/91955397-672e6500-ed03-11ea-8c2b-4afc82a54b2b.png)

Please retest it again and make sure that nothing cached

**Comment by Dina-Abd-Elrahman** [comment]
http works fine on the new installation 

![ff](https://user-images.githubusercontent.com/21218053/91971189-16296b80-ed19-11ea-8420-76faa5f0d8a2.png)
