### ISSUE TITLE
Improve flow for new app store chatflows

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/js-sdk#506]
complimentary to: https://github.com/threefoldtech/home/issues/878

_**Proposal:**_
- Scenarios to be handled for the service payments:
  - Wrong payment(wrong amount or wrong payment id in memo text of transaction)
  - Should wait on payment that it was successful
  - Options for handling service fees
    - **Option 1**: Need to set the fees for the use of the service which will be a one time payment when they first access. The users that payed will be kept track of on the machine (similar to trader and polls voting mechanism) and the payments for the pool deployments are done from user to explorer directly no double transfer is done.
      <img src="https://user-images.githubusercontent.com/17128393/90388687-80d77780-e088-11ea-914f-d8af53ddbc9c.png" width="500" height="500" />
    - **Option 1-b**: Need to set the fees for the use of the service which will be payed everytime to the app store's wallet along with the pool creation fees. Wont need to keep track of who payed these fees as it will be obligatory with every deployment process. In case the deployment failed for any reason, the fees can be rfunded to the user.

    - **Option 2**: Fees are added to the cost of the deployment, and the tokens are transferred to the app store's wallet, and the app store deducts the fees and proceeds with the payment for the deployment (Disadvantage: not sure if multiple transactions can be done simultaneously if we have multiple deployments from different users at the same time using only 1 app store wallet) 
      <img src="https://user-images.githubusercontent.com/17128393/90388547-4241bd00-e088-11ea-94ee-a2369c980f14.png" width="500" height="500" />

   - **Option 3**: Three large pools are created by the app store machine and tokens are transferred to the app's store wallet by the user. The app store will own and be responsible in managing pools and deployments. (Disadvantage: if the pool resources finish, all deployments on that pool are cancelled)

**_To be done_**

- Deployment scenarios to be handled:
  - when someone pays for a pool and deploys network,but by the time they create a container the resources finished and the deployment fails, then their money is lost. The failed deployments can be saved for that user where they can list them in the UI and have an option to deploy later or cancel that attempt in the first place. This will ensure the pool they paid for is not lost but doesn't guarantee that resources will free up.

**Comment by BolaNasr** [comment]
I agree with **Option 1**

**Comment by rkhamis** [comment]
I think the first suggestion has less edge cases and less complicated

**Comment by ranatrk** [comment]
After discussing with @waleedhammam @ashraffouda ,and @rkhamis : **Option 1-b** will be approached. 
1. Initially will go with letting the user make 2 payments in the flow, one for the fees to the app store's wallet and another to the explorer for the deployment itself. 
2. A feature request has been suggested to be able to create multiple payments by scanning one bardcode through the 3bot app. Where a list of payments would be saved in the QR code instead of info for only 1 payment. This will save the hassle for the user to have to deal with 2 payments where they only scan once. Each payment will be processed separately in sequence.

**Comment by ranatrk** [comment]
WIP added fees payment scenario
![Screenshot from 2020-08-17 18-03-59](https://user-images.githubusercontent.com/17128393/90422347-0a07a200-e0bb-11ea-9fcc-b2d7ed6e246a.png)

![image](https://user-images.githubusercontent.com/17128393/90422249-e3496b80-e0ba-11ea-86c0-e9b684761441.png)

![Screenshot from 2020-08-17 18-14-03](https://user-images.githubusercontent.com/17128393/90422358-0e33bf80-e0bb-11ea-9014-10791d2f4b32.png)



in case of wrong transaction amount, it will be refunded
![image](https://user-images.githubusercontent.com/17128393/90422282-f0fef100-e0ba-11ea-99b2-c878becdf8e3.png)

**Comment by waleedhammam** [comment]
Part of: https://github.com/threefoldtech/home/issues/878

**Comment by waleedhammam** [comment]
not relevant anymore
