### ISSUE TITLE
gitea chatflow problem

### ISSUE THREAD

**Issue by BolaNasr** [threefoldtech/js-sdk#507]
It works good with https and 3bot login branch( **development_capacitypool_apps** ) : 
using this flist : https://hub.grid.tf/bishoy.3bot/threefolddev-http_gitea_all_in_one-latest.flist
![image](https://user-images.githubusercontent.com/10259267/90397190-c5b6da80-e097-11ea-8eab-d29c81df15c2.png)

but we have 1 problem:
 1- redirect after login using  3bot login ( using localhost instead of domain)

![image](https://user-images.githubusercontent.com/10259267/90397140-addf5680-e097-11ea-868b-97458abae8c7.png)

**Comment by BolaNasr** [comment]
Fixed at ```development_capacitypool_apps``` branch
![image](https://user-images.githubusercontent.com/10259267/90539393-0a1da580-e180-11ea-8749-37ef9cad452a.png)

**Comment by Pishoy** [comment]
verified , need to use /gitea as it is not enabled yet 

![image](https://user-images.githubusercontent.com/21987477/91858746-ecfdd200-ec69-11ea-9864-670de6b68f28.png)
