### ISSUE TITLE
Can't list the packages through the admin panel 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#512]
![image](https://user-images.githubusercontent.com/46320202/90499414-d32c9d00-e149-11ea-840f-23df34e55ee6.png)

#### chorme inspector 
![image](https://user-images.githubusercontent.com/46320202/90499482-e8a1c700-e149-11ea-8426-0cd70745810b.png)

#### the shell 
![image](https://user-images.githubusercontent.com/46320202/90501055-0b34df80-e14c-11ea-905d-e495054a1b4e.png)

#### request response 
![image](https://user-images.githubusercontent.com/46320202/90503858-71bbfc80-e150-11ea-9dcc-171423c3f4d8.png)

**Comment by xmonader** [comment]
@RafyAmgadBenjamin please list the versions, commit you're using, what are the errors shown in the shell?

**Comment by RafyAmgadBenjamin** [comment]
on `development` branch
This is the commit id 32c5f7a65279dc677151a0e987e9e8a376b7fb5b

**Comment by xmonader** [comment]
repo was tainted, resolved with git clean -xfd

**Comment by AhmedHanafy725** [comment]
**Verified**
**branch:** development
**commit:** e3ec9421d17960f3b1d6fe48c2ecf14d50b5d17a


![image](https://user-images.githubusercontent.com/41957921/90520789-172f9a00-e16a-11ea-842a-effbc68acefa.png)
