### ISSUE TITLE
misleading information in the listed packages in the dashboard  [development_capacitypool]

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#514]
on branch `development`
commit 32c5f7a65279dc677151a0e987e9e8a376b7fb5b
List of packages in the dashboard
![image](https://user-images.githubusercontent.com/46320202/90505885-ac736400-e153-11ea-8131-d21e75b3fb64.png)
List of packages in my shell
![image](https://user-images.githubusercontent.com/46320202/90505920-bb5a1680-e153-11ea-8474-c27d617c8470.png)
when I tried to delete a package
![image](https://user-images.githubusercontent.com/46320202/90505943-c90f9c00-e153-11ea-9ea1-bcf90b3b0309.png)

After discussion with @AhmedSa-mir, we found that in the dashboard, we list all the packages not only the installed ones and it is a bug related to the frontend, we need to remove the `junk` icon from the not installed packages .

**Comment by rkhamis** [comment]
needs verification

**Comment by RafyAmgadBenjamin** [comment]
#### verified
on branch `capacitypool`
#### commit
2d8dae1bdee0fcdc9520e64cfd011ee3ad94a209

Packages now in the shell and dashboard are consistant
![image](https://user-images.githubusercontent.com/46320202/91038728-8cd4b380-e60b-11ea-8317-4484af92d26b.png)
![image](https://user-images.githubusercontent.com/46320202/91038744-93632b00-e60b-11ea-9391-649029d33b58.png)

there is no Junk icon next to the not installed packages
![image](https://user-images.githubusercontent.com/46320202/91038806-b1309000-e60b-11ea-8c3a-a5a84f5c60a4.png)

**Comment by Dina-Abd-Elrahman** [comment]
** Commit_ID** 45faa13faac137431eb634cc8d73553a5d125cc6 , **Branch** development_capacitypool

![ff](https://user-images.githubusercontent.com/21218053/91040910-56009c80-e60f-11ea-9e42-20e387b3ce95.png)

![ff1](https://user-images.githubusercontent.com/21218053/91040979-7d576980-e60f-11ea-8dbe-7b016c269c80.png)

**Comment by Dina-Abd-Elrahman** [comment]
When I tried to install a package from the dashboard. 

![ff](https://user-images.githubusercontent.com/21218053/91041142-cad3d680-e60f-11ea-951f-85e3bc7266bf.png)


but I got this error in `jsng` shell 

![ff1](https://user-images.githubusercontent.com/21218053/91041181-dc1ce300-e60f-11ea-90f6-7a13e259fcd5.png)

But It has been added to the package list 

![ff2](https://user-images.githubusercontent.com/21218053/91041405-4b92d280-e610-11ea-87d8-98d1636d196b.png)

**Comment by Dina-Abd-Elrahman** [comment]
when I tried to delete the package, It has been deleted correctly.

![ff](https://user-images.githubusercontent.com/21218053/91041599-9f052080-e610-11ea-908e-8c59767c3c89.png)

![ff1](https://user-images.githubusercontent.com/21218053/91041675-bb08c200-e610-11ea-8967-9464a20784d9.png)

**Comment by Dina-Abd-Elrahman** [comment]
- As per @RafyAmgadBenjamin the error not related to this issue, so I created a separate issue https://github.com/threefoldtech/js-sdk/issues/581 , and will close this one as the error on it has been solved.
