### ISSUE TITLE
admin landing page has mix of fonts with different sizes inconsistently 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#52]
![image](https://user-images.githubusercontent.com/64129/85108366-e4bbfc00-b20f-11ea-9018-cbd5f1a6eb9c.png)

**Comment by waleedhammam** [comment]
also what does this chart do
![image](https://user-images.githubusercontent.com/10658229/85123619-de864980-b228-11ea-9016-13d4ce0115b4.png)

and typo
![image](https://user-images.githubusercontent.com/10658229/85123665-f067ec80-b228-11ea-9df7-dcf4883db6c7.png)

found not find, and change it's color if there's alerts to red and underline to show that is a hyperlink

**Comment by dmahmouali** [comment]
fix admin landing page and added static data to bottom chart, https://github.com/threefoldtech/js-sdk/commit/ad311435d4978b5c1f9a13df883eb0aba056e1e2

if chart will replaced, please suggest something to replace.

**Comment by dmahmouali** [comment]
set the chart for TFT to USD data and create issue for make it get data from api : https://github.com/threefoldtech/js-sdk/issues/122

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
