### ISSUE TITLE
alerts view should show a different pointer

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#535]
Alerts view doesn't show the rows as clickables

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 9821a780024b4323c4a61f4b5818574f20990236 , **Branch** development_capacitypool

![ff](https://user-images.githubusercontent.com/21218053/91063663-915e9380-e62e-11ea-96b8-39bd29d7bdb6.png)
