### ISSUE TITLE
end user solutions should not be like this on marketplace

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/js-sdk#543]
### Description

![image](https://user-images.githubusercontent.com/6021844/90755280-431e5d00-e2db-11ea-8d3b-9758370de9ca.png)

- needs to be moved to more logical location (basically switch top & bottom, bottom gets demo label and a popup or so they need to answer once that this are demo deployment flows and for production they need to use the own 3bot)
- primitives need to be on the top

## requirements enduser solutions

- need to be clear these are demo's how to deploy end user usable solutions on grid
- separate section as 3bot admin (so it comes in as section, also show demo solutions)

**Comment by dmahmouali** [comment]
The new Marketplace view:
![image](https://user-images.githubusercontent.com/36021484/91283133-7d2fa900-e78a-11ea-960c-2e855b9de1ea.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** cbe9df702e66b7e894abccf3127b93f649564093 , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91296517-09e36280-e79d-11ea-93f4-a9ed49cc2502.png)
