### ISSUE TITLE
Track the solution domain

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/js-sdk#547]
### Description

After creating the app instance should show the domain in the instance details.

- [x] Mattermost
- [x] cryptpad
- [x] peertube
- [x] publisher
- [x] discourse

**Comment by hossnys** [comment]
verified

![Screenshot from 2020-08-24 19-20-35](https://user-images.githubusercontent.com/26298009/91189424-b87e9900-e6f2-11ea-8844-56e0d8cab1a4.png)

![Screenshot from 2020-08-24 20-59-38](https://user-images.githubusercontent.com/26298009/91189431-b9afc600-e6f2-11ea-9448-a6f935683d35.png)

![Screenshot from 2020-08-25 17-25-19](https://user-images.githubusercontent.com/26298009/91193525-7b68d580-e6f7-11ea-9992-a5cd907cfb30.png)

![Screenshot from 2020-08-25 17-20-09](https://user-images.githubusercontent.com/26298009/91193551-815eb680-e6f7-11ea-9dc4-329aaceb8d53.png)
