### ISSUE TITLE
a sal to find the issued certs for a gateway and whether we reached the rate limit or not 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#549]
we need a sal to find the issued certs for a gateway and whether we reached the rate limit or not to help of distributing solutions over gateways

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-08-24 16-19-55](https://user-images.githubusercontent.com/26298009/91055664-4724e480-e625-11ea-8bfe-65e9265ef4b7.png)
