### ISSUE TITLE
authenticated user wrong information in the admin

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#55]
@waleedhammam  describe 

possibly fixed in https://github.com/threefoldtech/js-sdk/commit/2222fa06149353cec9def973aa297d333d9f56b0

**Comment by AhmedSa-mir** [comment]
Yes fixed in https://github.com/threefoldtech/js-sdk/commit/2222fa06149353cec9def973aa297d333d9f56b0

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
