### ISSUE TITLE
 installing gitea solution give an alert after choosing container IP

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/js-sdk#553]
### Description

when installing gitea solution i got this error in the alert.

### Version information

* OS: Ubuntu 18.04
* project commit/version:  js-ng  , branch  development_capacitypool : 205e0a3
* Browser: chrome Version 84.0.4147.89 (Official Build) (64-bit)

### Steps to reproduce

try to install gitea solution using same branch on testnet

### Traceback/Logs/Alerts

![Screenshot from 2020-08-23 16-23-13](https://user-images.githubusercontent.com/26298009/90980658-019ce480-e55d-11ea-8249-697b3c571d25.png)

**Comment by xmonader** [comment]
Why is this closed?

**Comment by hossnys** [comment]
This was closed because I was testing installation on development_capacitypool , but Bola fixes was on development_capacitypool_apps , so I closed it till I get a working installation , if found there will post here again.

**Comment by xmonader** [comment]
I see, I moved it to the right project. let's leave the issue open.
