### ISSUE TITLE
better description for the solutions

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#556]
examples

![image](https://user-images.githubusercontent.com/64129/90985427-408e6280-e57c-11ea-9dc6-8af9e0745e53.png)

![image](https://user-images.githubusercontent.com/64129/90985432-4ab06100-e57c-11ea-9ccd-e66f5cf89aa8.png)

![image](https://user-images.githubusercontent.com/64129/90985446-59971380-e57c-11ea-9af9-7d974985a393.png)

![image](https://user-images.githubusercontent.com/64129/90985457-6b78b680-e57c-11ea-958a-1cfafcd43c9d.png)

**Comment by rkhamis** [comment]
needs to be validated that no solutions are missing a description

**Comment by Dina-Abd-Elrahman** [comment]
** Commit_ID** 3bd6e807d4d0c63a34768059dfc038a33a991571 , **Branch** 


![ff](https://user-images.githubusercontent.com/21218053/91051767-d976b980-e620-11ea-933b-5d6075c01d9c.png)

![ff1](https://user-images.githubusercontent.com/21218053/91051781-ded40400-e620-11ea-8f86-9c93a10dd744.png)
