### ISSUE TITLE
remove the intro page of solution chatflows or provide better descriptions

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#558]
Example

![image](https://user-images.githubusercontent.com/64129/90985516-beeb0480-e57c-11ea-94ad-347ea6d51c87.png)

That info should be already clear when choosing the solution from the marketplace

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** cbe9df702e66b7e894abccf3127b93f649564093 , **Branch** development

![ff1](https://user-images.githubusercontent.com/21218053/91296313-b53fe780-e79c-11ea-9526-8cdce20c6065.png)

![ff](https://user-images.githubusercontent.com/21218053/91296332-bbce5f00-e79c-11ea-97af-16ca404fc692.png)
