### ISSUE TITLE
why do I need to fill in the solution name?

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#559]
![image](https://user-images.githubusercontent.com/64129/90985531-e80b9500-e57c-11ea-960f-694b8c4c9526.png)

Should be stated why e.g to be used in domains or to create metadata for the solution on the grid

**Comment by rkhamis** [comment]
add some help about how the name will be used.

**Comment by BolaNasr** [comment]
Commit : https://github.com/threefoldtech/js-sdk/commit/e63b0c067653210da75b5c562a1985bf540a319b

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/91060709-9241f600-e62b-11ea-9516-f1c7ce1d8126.png)

It doesn't seem to work? I'm on latest marketplace commit

**Comment by BolaNasr** [comment]
@xmonader  Done on https://github.com/threefoldtech/js-sdk/commit/6cfb78c31a4f407111ba132b895ff4222cdec92c

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** d057d69d22c806ee6e2cd63879c4e59f927378ea , **Branch** development_capacitypool

![ff](https://user-images.githubusercontent.com/21218053/91287579-32189480-e790-11ea-908c-5163713292a3.png)
