### ISSUE TITLE
reduce the visual noise in the payment step

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#561]
![image](https://user-images.githubusercontent.com/64129/90985581-45074b00-e57d-11ea-9857-2abd97f83c93.png)

- we show `reservation id` with spaces and we tell the user to use `reservation_id` with underscore in the memo hash (not as the value for the memo hash), the explanation needs to be provided there
- in currency we show (asset/issuer) can be confusing to the reader either remove the issuer or show some info indicating its usage
-

**Comment by m-motawea** [comment]
![image](https://user-images.githubusercontent.com/32568986/91021626-50498d80-e5f4-11ea-9981-5ee9acd6c28c.png)

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-08-24 16-46-30](https://user-images.githubusercontent.com/26298009/91058628-f6af8600-e628-11ea-914e-1a5a4091acff.png)
