### ISSUE TITLE
preparing app resources message and waiting for payment

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#562]
![image](https://user-images.githubusercontent.com/64129/90985701-ec847d80-e57d-11ea-894b-5411ef36767a.png)

whether I paid or not, I get this message, and should be improved to maybe `Provisioning resources on the threefold grid`?

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID**  45c12e93fc703ccbaf902c05bf5faa011913b669 , **Branch** development_capacitypool

![ff](https://user-images.githubusercontent.com/21218053/91167664-a261e000-e6d4-11ea-9721-3569770d6c59.png)


![ff2](https://user-images.githubusercontent.com/21218053/91168377-d4c00d00-e6d5-11ea-9620-edf4ffe69531.png)


![ff3](https://user-images.githubusercontent.com/21218053/91168175-78f58400-e6d5-11ea-8c78-209024866774.png)
