### ISSUE TITLE
solution confirmation asking me for more than I choosed

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#563]
![image](https://user-images.githubusercontent.com/64129/90985741-29e90b00-e57e-11ea-9ee4-de5c1f6a83f5.png)

Here I choose only the solution name only and the disk size, and it asking to confirm pools, nodes, .. ips, .. etc

**Comment by rkhamis** [comment]
`Deployment Information` instead of `confirmation`

**Comment by hossnys** [comment]
i just deployed mattermost from marketplace but it's now shows deployment information : 

![Screenshot from 2020-08-24 19-29-08](https://user-images.githubusercontent.com/26298009/91076349-a7288480-e63f-11ea-815e-13ed53d14efc.png)

![Screenshot from 2020-08-24 19-20-35](https://user-images.githubusercontent.com/26298009/91075784-df7b9300-e63e-11ea-8d72-3c4b2e0c0d1c.png)
