### ISSUE TITLE
improve wireguard step message

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#564]
![image](https://user-images.githubusercontent.com/64129/90985778-6a488900-e57e-11ea-953f-3ee74e1e4c45.png)

Here it says `Success` ?

**Comment by rkhamis** [comment]
can we merge both wireguard screens in one?

and message of how to do wg-up needs to include changing path of downloaded config

**Comment by m-motawea** [comment]
![image](https://user-images.githubusercontent.com/32568986/91048354-d88f5900-e61b-11ea-85d1-ea551ebd9438.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID**  45c12e93fc703ccbaf902c05bf5faa011913b669 , **Branch** development_capacitypool 

![ff2](https://user-images.githubusercontent.com/21218053/91167916-008ec300-e6d5-11ea-81f9-860c4b9e72df.png)
