### ISSUE TITLE
Deployed message needs to improve

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#565]
![image](https://user-images.githubusercontent.com/64129/90986094-aa107000-e580-11ea-9dcb-4f5a670af69d.png)

- reservation id why is that info useful? how to use it?

**Comment by rkhamis** [comment]
remove reservation id

**Comment by rkhamis** [comment]
development_capacitypool

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 85914667d13dae8f98cae522ef1db58ebd192cea , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91417991-d7e00800-e851-11ea-9ab2-2fcc9bccb0c8.png)
