### ISSUE TITLE
Deployed solutions count doesn't update after a creation

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#566]
![image](https://user-images.githubusercontent.com/64129/90986161-e9d75780-e580-11ea-8c08-1fc8c6072c8f.png)

It's resolved with a refresh

![image](https://user-images.githubusercontent.com/64129/90986175-01aedb80-e581-11ea-8a09-8e34a0a93635.png)

**Comment by rkhamis** [comment]
needs to be verified after marketplace refactor

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 59f7e8439f7ed73b6095aed077895861c8c96eb8 , **Branch** development_capacitypool_new_marketplace_view

![ff](https://user-images.githubusercontent.com/21218053/91057589-af74c580-e627-11ea-80ce-610cbf5c4872.png)

**Comment by Dina-Abd-Elrahman** [comment]
- when I tested this issue before I tested it on the admin dashboard, but  when I tested again today in the marketplace dashboard 
I found that the bug still exists. I had to reload the page to update the count of the solution.

**Comment by Dina-Abd-Elrahman** [comment]
- as per @dmahmouali after testing on branch `development_capacitypool_new_marketplace_view` it works fine now we can close the issue.
