### ISSUE TITLE
Probably should try http check on deployed solution instead of telling ppl it will take a few mins?

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#567]
![image](https://user-images.githubusercontent.com/64129/90986453-36bc2d80-e583-11ea-8dba-11069b5d9819.png)

I think we probably should try http check on deployed solution instead of telling ppl it will take a few mins?

**Comment by RafyAmgadBenjamin** [comment]
I Have updated 
- `Mattermost solution`
- `peertube` and I have found an issue and reported it to @OmarElawady

**Comment by RafyAmgadBenjamin** [comment]
Solutions to do
- [ ] Wiki
- [ ] website
- [ ] Blog
- [ ] Mattermost
- [ ] Peetube
- [ ] Discourse
- [ ] Cryptpad
- [ ] Taiga
- [ ] Wiki
- [ ] Ubuntu
- [ ] Kubernetes
- [ ] Minio
- [ ] Gittea
- [ ] Network
- [ ] 3Bot
- [ ] Solution expose
- [ ] Generic container
- [ ] Monitoring
- [ ] Domain delegation
- [ ] 4 to 6 Gateway

**Comment by RafyAmgadBenjamin** [comment]
draft PR
https://github.com/threefoldtech/js-sdk/pull/639

**Comment by RafyAmgadBenjamin** [comment]
#### Fixed branch
 `development_http_check_marketplace `
#### commits
bebf652ccb9937b32330965e47bf5b59874d1281

I have updated our market place apps to use http check

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** bebf652ccb9937b32330965e47bf5b59874d1281 , **Branch** development_http_check_marketplace

Website in the admin dashboard doesn't work fine 

![ff](https://user-images.githubusercontent.com/21218053/91467603-15b05100-e891-11ea-95ad-c7051f0b71ca.png)

![ff1](https://user-images.githubusercontent.com/21218053/91467607-16e17e00-e891-11ea-8372-a22625a269c8.png)
