### ISSUE TITLE
testnet marketplace seems to be down

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#568]
<img width="1440" alt="Screenshot 2020-08-24 at 08 58 23" src="https://user-images.githubusercontent.com/43240801/91013512-17a3b700-e5e8-11ea-84fd-5a525065fcd9.png">

**Comment by xmonader** [comment]
also https://marketplace-testnet2.grid.tf/marketplace/#/ (staging testnet for devs)
