### ISSUE TITLE
disk sizes don't match the confirmation for mattermost

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#569]
![image](https://user-images.githubusercontent.com/64129/91013931-cb0cab80-e5e8-11ea-86ed-3021fb968267.png)
disk sizes (2, 5, 10)

while in confirmation (1 GB disk)

![image](https://user-images.githubusercontent.com/64129/91013986-e5468980-e5e8-11ea-9563-8ce757b2de78.png)

**Comment by dmahmouali** [comment]
Fix in commit: https://github.com/threefoldtech/js-sdk/commit/42631008176880fc38fd062b5c207299e5c831de
and added the Domain Name.

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID**  45c12e93fc703ccbaf902c05bf5faa011913b669 , **Branch** development_capacitypool

![ff1](https://user-images.githubusercontent.com/21218053/91167701-b279bf80-e6d4-11ea-978d-6fb457c14706.png)
