### ISSUE TITLE
edit the marketplace sidebar

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#570]
<img width="570" alt="Screenshot 2020-08-24 at 08 54 23" src="https://user-images.githubusercontent.com/43240801/91013854-a7496580-e5e8-11ea-963b-6f5ff5fd7560.png">

- [ ] rename pools into Capacity Pools

- [ ] 3Bot should comes after Network

**Comment by rkhamis** [comment]
work done here: https://github.com/threefoldtech/js-sdk/pull/546

**Comment by siddiquagig** [comment]
3bot is now after Networks:

![image](https://user-images.githubusercontent.com/25789724/91155252-a5100580-e6d3-11ea-8975-f7a7ee0568c5.png)




Capacity Pools is still Pools:

![image](https://user-images.githubusercontent.com/25789724/91155388-d688d100-e6d3-11ea-8e73-fe8e671bf203.png)


Verified on branch : development_capacitypool_apps_marketplace

**Comment by BolaNasr** [comment]
@siddiquagig  it's in marketplace not admin.

**Comment by sasha-astiadi** [comment]
please get it all live on testnet today @BolaNasr @siddiquagig our time is running out we would like to test it on monday

**Comment by sasha-astiadi** [comment]
repetition from 634, https://github.com/threefoldtech/js-sdk/issues/634 i close this one.
