### ISSUE TITLE
Marketplace app chatflow can't go back to solution name step

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#579]
trying to go back to solution name step fails because the method name was overridden by a string attribute 

![image](https://user-images.githubusercontent.com/32568986/91041811-f1ded800-e610-11ea-9712-aaf21f5dfe19.png)
![image](https://user-images.githubusercontent.com/32568986/91041875-16d34b00-e611-11ea-9596-5b8ddfd87da0.png)

**Comment by AhmedSa-mir** [comment]
Merged on development_capacitypool

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** d3f125d21f50d40665a0b4af76f8730fd7555a79 , **Branch** development_capacitypool

## Verification steps : 

- enter the name in any solution in chatflow, then next, then previous. You shouldn't get an error. 

![ff](https://user-images.githubusercontent.com/21218053/91199716-8b37e800-e6fe-11ea-991b-80d5c918384e.png)

![ff1](https://user-images.githubusercontent.com/21218053/91199729-8ffc9c00-e6fe-11ea-99ce-1b652298742c.png)

![ff](https://user-images.githubusercontent.com/21218053/91199739-94c15000-e6fe-11ea-954c-101ec4baf13f.png)
