### ISSUE TITLE
The cards for packages  are not aligned well on the same line

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#580]
![image](https://user-images.githubusercontent.com/46320202/91042138-95c88380-e611-11ea-9dc4-b47955630e36.png)

This is due to the long path mentioned in the card

**Comment by AhmedSa-mir** [comment]
Merged on: development_capacitypool

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID**  a2e04be4a07396481766ef83a63929a491285d9a , **Branch** development_capacitypool

![ff](https://user-images.githubusercontent.com/21218053/91173746-9a0ea280-e6de-11ea-896d-361634decc58.png)
