### ISSUE TITLE
clean workloads on failure

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#602]
App chatflows don't cancel the deployed workloads when it fails

**Comment by RafyAmgadBenjamin** [comment]
- I have created in the `/sals/chatflows/chatflow.py` a class to handle an exception and clean the` workerload_is`
- I have refactored the `cryptopad` to use the new exception handler 

#### commit
125dd37554f3cc249e2f00f8da776bae943781d5

**Comment by RafyAmgadBenjamin** [comment]
I have checked other solutions but I can see that they don't have `workerload_ids` list to be used. 
The solutions in the admin solution and market place must be revisited to see if it need to be refactored to have `workerload_ids` list or not, and if so it must use our new exception handler to clean 
```python
raise StopChatFlowCleanWorkloads(
                f"Failed to create container on node {self.selected_node.node_id} {self.workload_ids[1]}",
                getattr(self, "workload_ids", None),
            )
```

**Comment by m-motawea** [comment]
it is much simpler than that. current chatflows add a solution uuid into metadata of all workloads of the solution. canceling one workload using
```python
j.sals.marketplace.solution.cancel_solution(username, [workload_id])
```
 or 
```python
j.sals.reservation_chatflow.solutions.cancel_solution([workload_id])
```
will cancel all workloads with the same uuid (all workloads deployed during the chatflow)

**Comment by RafyAmgadBenjamin** [comment]
draft PR:
https://github.com/threefoldtech/js-sdk/pull/641

**Comment by RafyAmgadBenjamin** [comment]
-  cancel_solution_uuid method to cancel the work load using UUID
- Change the raise of exception with StopChatFlowCleanWorkloads exception
- Clean workloads for admin solutions using the new exception handler

**Comment by waleedhammam** [comment]
done with deployment context
