### ISSUE TITLE
make solution url hyperlink to open directly , and add better line spacing between lines

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/js-sdk#604]
make the solution link clickable in a new tab and add better line spacing between lines

![Screenshot from 2020-08-24 18-27-14](https://user-images.githubusercontent.com/26298009/91070749-7cd2c900-e637-11ea-940f-a894fc92ea19.png)

![Screenshot from 2020-08-23 12-13-38](https://user-images.githubusercontent.com/26298009/91071504-8c064680-e638-11ea-8f68-58d297545a5f.png)

**Comment by dmahmouali** [comment]
duplicated with: https://github.com/threefoldtech/js-sdk/issues/607
