### ISSUE TITLE
improve solutions success message

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#607]
![image](https://user-images.githubusercontent.com/64129/91137636-f2c64700-e6ae-11ea-8fb1-ed7f8c8c709b.png)

- move to hyperlink (opens in a new tab)
- increase spaces

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 85914667d13dae8f98cae522ef1db58ebd192cea , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91419592-e3343300-e853-11ea-881f-78155e47a255.png)
