### ISSUE TITLE
prepare all apps/flists for testcerts

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#608]
Right now some apps work with self signed certs as a fallback (e.g threebot), some fail without them (e.g publisher*)

suggest 
- config param that can be configured on env e.g production `marketplace-testnet.grid.tf` (testcert=False) and on staging `marketplace-testnet2.grid.tf` (testcert=True) 
- this gets passed to all solutions in env vars
- all apps based on nginx reverse proxy container switch the let's encrypt dest to the staging 
- all apps the working with caddy should respect that env var as well
- threebot solution should support test_cert https://github.com/threefoldtech/js-sdk/issues/627

**Comment by xmonader** [comment]
should use https://marketplace-testnet2.grid.tf/ for verification @Dina-Abd-Elrahman

**Comment by Dina-Abd-Elrahman** [comment]
**3bot** 

![ff](https://user-images.githubusercontent.com/21218053/91433736-0961cf00-e864-11ea-901f-865a79e71c33.png)

![ff1](https://user-images.githubusercontent.com/21218053/91433982-6d849300-e864-11ea-9aad-34e26205dda4.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Taiga**

![ff](https://user-images.githubusercontent.com/21218053/91437313-fce07500-e869-11ea-9b37-8c0202e6c248.png)

![ff1](https://user-images.githubusercontent.com/21218053/91438885-5fd30b80-e86c-11ea-8415-a36f23d1b89e.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Wiki**

![ff](https://user-images.githubusercontent.com/21218053/91439795-e50af000-e86d-11ea-8a46-790b85a8b0b5.png)

![ff1](https://user-images.githubusercontent.com/21218053/91439810-ecca9480-e86d-11ea-989b-40b2cab8afb5.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Website**

![ff](https://user-images.githubusercontent.com/21218053/91440362-c6f1bf80-e86e-11ea-98b6-a07e3d8f612d.png)

![ff1](https://user-images.githubusercontent.com/21218053/91440442-e5f05180-e86e-11ea-973d-6e816f114858.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Mattermost**

![ff](https://user-images.githubusercontent.com/21218053/91441721-002b2f00-e871-11ea-8e88-f2f9ea4de362.png)

![ff1](https://user-images.githubusercontent.com/21218053/91441803-205aee00-e871-11ea-8353-641eac3a527f.png)
