### ISSUE TITLE
need to remove the drop down button from the capacity pool in the dashboard 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/js-sdk#609]
need to remove the drop-down button, as it's not clickable. 

![ff](https://user-images.githubusercontent.com/21218053/91148575-235fae00-e6ba-11ea-8f90-d0d4dc581bf0.png)

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/104447234-2e9d7280-55a4-11eb-8a8b-a12704fdb477.png)
