### ISSUE TITLE
can't start threebot server

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/js-sdk#61]
```python3
server = j.servers.threebot.get("default") 
server.start() 
```
![image](https://user-images.githubusercontent.com/46320202/85226950-6bbcd000-b3da-11ea-82c6-d3dc78254c82.png)

**Comment by BolaNasr** [comment]
It works good
![image](https://user-images.githubusercontent.com/10259267/85268324-a70cdc80-b476-11ea-96d8-03e1352b3e01.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
