### ISSUE TITLE
Disable "previous step" button after payment step

### ISSUE THREAD

**Issue by AhmedSa-mir** [threefoldtech/js-sdk#620]
#### On deploying an app from marketplace, after payment, the `previous step` button is enabled, so I can click on it and go back to the qr code payment step again. It should be disabled after payment step

![image](https://user-images.githubusercontent.com/18093386/91176919-43579780-e6e3-11ea-921a-7591d7bfba63.png)

**Comment by AhmedSa-mir** [comment]
Merged on branch: development_capacitypool

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 6cfb78c31a4f407111ba132b895ff4222cdec92c , **Branch** development_capacitypool

![ff](https://user-images.githubusercontent.com/21218053/91204609-9db52000-e704-11ea-9c32-0ecad41271d2.png)

![ff1](https://user-images.githubusercontent.com/21218053/91205083-49f70680-e705-11ea-82f7-267a079a25d2.png)
