### ISSUE TITLE
Allow provisioning 3bot solution on latest development branch

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#621]
Now that branch is getting stabilized the entry point should be fixed to allow provisioning

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 41445c9ffddc758dbe1d3eeb0281dcbbef75a9d3 , **Branch** development

threebot solution is deployed and starts ok. but the initialization step fails
It took 15 mins here in this step, then give timeout error, but it increments my 3bot workload with 1, and if the access the URL in the workload info I can log in correctly to 3bot 

![ff1](https://user-images.githubusercontent.com/21218053/91322812-7459ca00-e7c0-11ea-8ff9-c0a8c7e564c1.png)

![ff](https://user-images.githubusercontent.com/21218053/91323083-c7338180-e7c0-11ea-8f73-153f47116fca.png)

**Comment by m-motawea** [comment]
should be ok now. already deployed on staging and production testnet marketplace

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 85914667d13dae8f98cae522ef1db58ebd192cea , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91413107-f1ca1c80-e84a-11ea-9f39-ab8ad8ea19d7.png)
