### ISSUE TITLE
Add label on:hover the package view icons

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/js-sdk#624]
### Implementation

we can use the `v-tooltip` component to show a label about what icon do.

![photo_2020-08-25_15-37-17](https://user-images.githubusercontent.com/36021484/91181715-8e74a900-e6e9-11ea-96f4-d9d926b244f5.jpg)

**Comment by AhmedSa-mir** [comment]
Merged on branch: development_capacitypool

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** d057d69d22c806ee6e2cd63879c4e59f927378ea , **Branch** development_capacitypool

![ff](https://user-images.githubusercontent.com/21218053/91284639-786bf480-e78c-11ea-9ba2-bb26488ca3ac.png)
