### ISSUE TITLE
Test Cert support in 3bot solution

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#627]
currently threebot solution starts with the defailt server that uses certbot to generate a verified certificate for the server. we need to support test_cert option to create self-signed certs for testing and staging environments.

**Comment by OmarElawady** [comment]
#631

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** ad576c65600cb7319ed7a93625c3ad986303074c , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91430722-9c4c3a80-e85f-11ea-9e52-5e9922bed50c.png)
