### ISSUE TITLE
Release Acceptance Test

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#632]
This will be used to test the release candidate before the final release.

### Automated
unittests on js-ng and js-sdk in github actions
https://github.com/threefoldtech/js-ng/tree/development/tests
https://github.com/threefoldtech/js-sdk/tree/development/tests

#### From scratch
  - [x] [ubuntu 20.04](https://github.com/threefoldtech/js-sdk/issues/934)
  - [x] [ubuntu 18.04](https://github.com/threefoldtech/js-sdk/issues/934)
  - [x] mac
  - [x] windows

#### On a previous installation
  - [x] [ubuntu](https://github.com/threefoldtech/js-sdk/issues/934)
  - [x] mac
  - [x] windows

### Wallets
  - [x] create
  - [x] [import](https://github.com/threefoldtech/js-sdk/issues/920)
  - [x] delete

### Admin Dashboard
  - [x] network (#972)
  - [x] ubuntu (#971)
  - [x] kubernetes
  - [x] minio
  - [x] master/slave minio
  - [x] expose solutions
  - [x] generic flist
  - [x] monitoring 
  - [x] domain delegation
  - [x] 4 to 6 gateway (#978)

### Marketplace
  - [x] wiki
  - [x] [website](https://github.com/threefoldtech/js-sdk/issues/1004)
  - [x] blog
  - [x] Mattermost
  - [x] Peertube
  - [x] Discourse
  - [x] Cryptpad
  - [x] Taiga
  - [x] gitea

### Reservations and payments:
 - [x] create capacity pool (#884, #924)
 - [x] extend capacity pool (#440)
 - [x] canceling reservations

### Other functionality
 - [x] adding administrators
 - [x] removing admins from dashboard 
 - [x] switching identities (#1011)
 - [x] logs
 - [x] alerts 
 - [x] add package https://github.com/threefoldtech/js-sdk/issues/927  https://github.com/threefoldtech/js-sdk/issues/940
 - [x] [remove package](https://github.com/threefoldtech/js-sdk/issues/940)
 - [x] Developer options (#921)

**Comment by Dina-Abd-Elrahman** [comment]
working on fresh manual installation in ubuntu 18.04

**Comment by Dina-Abd-Elrahman** [comment]
- Testing wallet ( Create, Delete, and import )

**Comment by Dina-Abd-Elrahman** [comment]
- testing add and remove package.

**Comment by AhmedHanafy725** [comment]
- Installation on mac
![image](https://user-images.githubusercontent.com/41957921/92088154-c6a47780-edcc-11ea-87d7-d552861ccc86.png)

**Comment by AhmedHanafy725** [comment]
- Installation on windows
![image](https://user-images.githubusercontent.com/41957921/92098712-decec380-edd9-11ea-8d3c-17d708a9d62e.png)

**Comment by Dina-Abd-Elrahman** [comment]
- working on Marketplace

**Comment by AhmedHanafy725** [comment]
@ramezsaeed  @rkhamis 
yesterday, creating and extending capacity pools was tested, I thought it is done. Today I found that it's is changed https://github.com/threefoldtech/js-sdk/pull/874 , So I have to test it again.

**Comment by Dina-Abd-Elrahman** [comment]
**WIKI** 

![ff](https://user-images.githubusercontent.com/21218053/92124482-21a29280-edfe-11ea-8965-04baeca47ec1.png)

![ff1](https://user-images.githubusercontent.com/21218053/92124908-a7264280-edfe-11ea-85fe-0daa6b2edf75.png)

**Comment by AhmedHanafy725** [comment]
- network
![image](https://user-images.githubusercontent.com/41957921/92126884-02f1cb00-ee01-11ea-936a-da854940bb32.png)


- Ubuntu 18.04
wid: 473923
![image](https://user-images.githubusercontent.com/41957921/92121621-c622d580-edfa-11ea-842b-0394340d076f.png)

![image](https://user-images.githubusercontent.com/41957921/92121766-f0749300-edfa-11ea-9fe2-76007e89206e.png)

- Ubuntu 20
![image](https://user-images.githubusercontent.com/41957921/92122388-a63fe180-edfb-11ea-97c9-d66478e52911.png)

![image](https://user-images.githubusercontent.com/41957921/92122533-d5eee980-edfb-11ea-89b0-0072688a58ff.png)

- kubernetets
![image](https://user-images.githubusercontent.com/41957921/92126829-f1a8be80-ee00-11ea-8a32-99ec8c25934d.png)
![image](https://user-images.githubusercontent.com/41957921/92128585-d50d8600-ee02-11ea-96ff-86d3fca47b1e.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Website**

![ff](https://user-images.githubusercontent.com/21218053/92129023-4baa8380-ee03-11ea-92e9-6a7b5a29786f.png)

**Comment by Dina-Abd-Elrahman** [comment]
**BLOG** 

![ff](https://user-images.githubusercontent.com/21218053/92139472-0fc9eb00-ee10-11ea-89bb-d53ee98ffc79.png)

![ff](https://user-images.githubusercontent.com/21218053/92139533-27a16f00-ee10-11ea-8402-623c67b08511.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Mattermost**

![ff](https://user-images.githubusercontent.com/21218053/92142963-e65f8e00-ee14-11ea-86c9-b06e8a8f0b5c.png)

![ff1](https://user-images.githubusercontent.com/21218053/92144007-5f131a00-ee16-11ea-95fb-b2f59bc358a0.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Peertube**

![ff](https://user-images.githubusercontent.com/21218053/92322850-25b7f580-f034-11ea-8f33-2c424edbddfb.png)

![ff1](https://user-images.githubusercontent.com/21218053/92322860-43855a80-f034-11ea-8617-30b1832d6d2e.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Gitea**

![ff](https://user-images.githubusercontent.com/21218053/92323016-885dc100-f035-11ea-9763-3eb737e3b2fc.png)
![ff1](https://user-images.githubusercontent.com/21218053/92323018-898eee00-f035-11ea-811a-7c3b0ff852f1.png)
![ff2](https://user-images.githubusercontent.com/21218053/92323019-8ac01b00-f035-11ea-9d08-efafd5712acf.png)
![ff3](https://user-images.githubusercontent.com/21218053/92323044-c0fd9a80-f035-11ea-9320-072061643d08.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Discourse**

![ff1](https://user-images.githubusercontent.com/21218053/92323277-bd6b1300-f037-11ea-8dbf-7f11392bce09.png)
![ff2](https://user-images.githubusercontent.com/21218053/92323279-bfcd6d00-f037-11ea-94bf-f0b35f365db9.png)

**Cryptpad**

![ff](https://user-images.githubusercontent.com/21218053/92323229-46ce1580-f037-11ea-834d-9c5500c94d87.png)
![ff4](https://user-images.githubusercontent.com/21218053/92323322-15097e80-f038-11ea-82d0-7b8ce3bfbdac.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Taiga**

![ff](https://user-images.githubusercontent.com/21218053/92323574-29e71180-f03a-11ea-9f42-183d68fc42d1.png)
![ff1](https://user-images.githubusercontent.com/21218053/92323578-2e132f00-f03a-11ea-92d5-e4e5144ee476.png)

**Comment by AhmedHanafy725** [comment]
- domain delegation 
![image](https://user-images.githubusercontent.com/41957921/92327556-cae5c480-f05a-11ea-961b-daedbae8fef2.png)

![image](https://user-images.githubusercontent.com/41957921/92327572-dafda400-f05a-11ea-9ebb-3a98a0b70abb.png)

**Comment by AhmedHanafy725** [comment]
- solution expose with custom domain 

![image](https://user-images.githubusercontent.com/41957921/92393680-891f5180-f120-11ea-9594-d72ff14c1813.png)


![image](https://user-images.githubusercontent.com/41957921/92393634-760c8180-f120-11ea-96ed-0228a9f8cf3c.png)


![image](https://user-images.githubusercontent.com/41957921/92393589-6725cf00-f120-11ea-9031-a8ee167febcb.png)

**Comment by AhmedHanafy725** [comment]
- master/salve minio
![image](https://user-images.githubusercontent.com/41957921/93014760-109f1180-f5b4-11ea-8b61-42e0966f5a66.png)
