### ISSUE TITLE
2.2 - hosted 3bot - no available pool

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#633]
tried to deploy a hosted 3bot
<img width="1440" alt="Screenshot 2020-08-25 at 17 05 21" src="https://user-images.githubusercontent.com/43240801/91191657-54a99f80-e6f5-11ea-8f85-4472dde463aa.png">

**Comment by xmonader** [comment]
@waleedhammam @m-motawea Should we convert that to an enduser app? where network, pools are all done behind the user? and what is your estimate if so?

**Comment by sasha-astiadi** [comment]
i just realized that, but that couldnt be, because i built 3 pools already before. could it be that sometims it doesnt detect my pools?

**Comment by waleedhammam** [comment]
> @waleedhammam @m-motawea Should we convert that to an enduser app? where network, pools are all done behind the user? and what is your estimate if so?

Seems doable, may take a couple of hours for extra testing AFAIK

**Comment by waleedhammam** [comment]
> i just realized that, but that couldnt be, because i built 3 pools already before. could it be that sometims it doesnt detect my pools?

Could you provide us with these Pools ids please ?

**Comment by sasha-astiadi** [comment]
281, 286, 385

now it shows again

**Comment by waleedhammam** [comment]
> 281, 286, 385
> 
> now it shows again

yes It just minute or two to charge/complete the payment.

from what i see is 281 is empty. you will be able to use 286 and 385

**Comment by sasha-astiadi** [comment]
ok thanks. 
so lets say i create a pool also on staging marketplace-testnet2.grid.tf, would it also show on testner production marketplace-testnet.grid.tf,?

**Comment by xmonader** [comment]
> ok thanks.
> so lets say i create a pool also on staging marketplace-testnet2.grid.tf, would it also show on testner production marketplace-testnet.grid.tf,?

Pools created on `marketplace-testnet2.grid.tf` "are owned by the marketplace identity" that's completely different than  `marketplace-testnet.grid.tf` because it's owned by another marketplace identity. Both shouldn't be confused or "shared"
