### ISSUE TITLE
2.2 - sidebar flow changes 

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#634]
- [ ] move 3Bot on top, rename as __3Bot Server__. its too confusing for the users

<img width="710" alt="Screenshot 2020-08-25 at 16 55 04" src="https://user-images.githubusercontent.com/43240801/91201442-b9b6c280-e700-11ea-8b6a-1ac26f708161.png">

- [ ] rename pools into 'Capacity Pools' , also on the wizards

<img width="1164" alt="Screenshot 2020-08-25 at 16 54 57" src="https://user-images.githubusercontent.com/43240801/91201558-deab3580-e700-11ea-9a3b-aae2b5dcacb3.png">

- [ ] remove the subsection of advance deployment, move the section on top.

- [ ] end-user solutions should be below advanced solutions. should be grouped as 'End-user Solutions'

**Comment by xmonader** [comment]
3Bot Sys-Ad doesn't sound like a good name either IMO

**Comment by sasha-astiadi** [comment]
how about 3Bot Admin

**Comment by sasha-astiadi** [comment]
we have 3Bot connect, 3Bot ID, 3Bot Admin. because to just name everything 3Bot is too confusing

**Comment by xmonader** [comment]
I think SDK online or 3Bot Online are better options because It literally starts a "threebot server" on the grid, but anyhow that still needs agreement

**Comment by sasha-astiadi** [comment]
if it starts as 3Bot Server, how about we rename it as '3Bot Server'? i think thats better

**Comment by sasha-astiadi** [comment]
please get it all live on testnet today @BolaNasr @siddiquagig our time is running out we would like to test it on monday
