### ISSUE TITLE
add solution location to the soltution details for both admin panel and markerplace solutions 

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/js-sdk#636]
need to add solution location at any these two windows of solution details , as many users are not familiar with how to get the farm name using explorer or explorer endpoints.  

![Screenshot from 2020-08-25 19-00-35](https://user-images.githubusercontent.com/26298009/91204728-c9380a80-e704-11ea-87b1-ba44b24d885e.png)

![Screenshot from 2020-08-25 19-00-51](https://user-images.githubusercontent.com/26298009/91204736-cb01ce00-e704-11ea-886a-075294ba1be2.png)

**Comment by xmonader** [comment]
Do you mean hyperlink for node id to link to explorer node info?

**Comment by waleedhammam** [comment]
> Do you mean hyperlink for node id to link to explorer node info?

I think the deployment location example: Belgium, Freefarm

**Comment by hossnys** [comment]
I'm with Waleed opinion plus adding the farm name

**Comment by OmarElawady** [comment]
Sometimes the node contains location and the farm doesn't like (node)[https://explorer.testnet.grid.tf/api/v1/nodes/3BwDVNRigau8Zk6BQkJt5PLxrHQnJ5NTfNvAtuubC1eS] and (farm)[https://explorer.testnet.grid.tf/api/v1/farms/71]. Is this a normal behaviour and is it okay to add only the farm info?
![Screenshot from 2020-08-27 11-38-26](https://user-images.githubusercontent.com/13040543/91654715-8632ba00-eaab-11ea-9a5f-676229085dfe.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 1fcd8eec02bc4e39794e0ab22b722106e05ce7c4 , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91865632-e2473b00-ec71-11ea-9452-d798b04d6806.png)

![ff1](https://user-images.githubusercontent.com/21218053/91865719-f854fb80-ec71-11ea-98f4-fe875f5e34e6.png)
