### ISSUE TITLE
2.2 Change 'New' into 'Start' on all wizards

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#644]
For example,

as a user, i would like to 'extend' my pool, not making a 'new' pool. I know it is offered on the 2nd step of the 'pool' wizards, but to start the wizard with 'new' is misleading to me, because as a user i thought 'wait a minute, i dont wanna create a new pool, i just wanna extend the old one but there's no option of that on 'pool'....
so please change 'new' into 'start'

<img width="1440" alt="Screenshot 2020-08-26 at 11 06 26" src="https://user-images.githubusercontent.com/43240801/91286050-3e035700-e78e-11ea-876f-fa72de9cf438.png">

should be implemented today.

**Comment by xmonader** [comment]
Start doesn't feel the right word. Added to `New`

**Comment by sasha-astiadi** [comment]
'new' is misleading... because extending a pool is not new...
