### ISSUE TITLE
Package kyc error during installation from frontend

### ISSUE THREAD

**Issue by AhmedSa-mir** [threefoldtech/js-sdk#645]
### Description

Package kyc raises an error on installation from frontend, but afterthat it's added in the packages list.

**Comment by AhmedSa-mir** [comment]
development branch: removed kyc package from js-sdk to https://github.com/threefoldtech/kyc_package

**Comment by hossnys** [comment]
verified on development kyc package removed .

![Screenshot from 2020-08-27 12-10-49](https://user-images.githubusercontent.com/26298009/91427215-dae0f580-e85d-11ea-90bd-1e5843e196d9.png)
