### ISSUE TITLE
2.2 error in getting a hosted 3bot

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#646]
<img width="1440" alt="Screenshot 2020-08-26 at 11 35 24" src="https://user-images.githubusercontent.com/43240801/91287897-9fc4c080-e790-11ea-9cff-34c49e0ab04d.png">

could this be more specific everytime, could we actually tell user what is wrong with their installation?
e.g not enough capacity on the pool
network not deployed successfully

as a user its quite frustrating to always want to deploy something, went through a long walkthrough, only to get this notification at the end and not knowing whats wrong, then i have to contact support and wait for them to reply.

I deployed a network, i used capacity 286

**Comment by xmonader** [comment]
https://marketplace-testnet2.grid.tf/
