### ISSUE TITLE
Can't install packages Through Admin UI  if threebot server name is not default

### ISSUE THREAD

**Issue by BolaNasr** [threefoldtech/js-sdk#65]
![photo_2020-06-21_15-22-34](https://user-images.githubusercontent.com/10259267/85266824-b7bc5300-b474-11ea-8783-10ea5bf24380.jpg)
![photo_2020-06-22_10-39-30](https://user-images.githubusercontent.com/10259267/85266827-b8ed8000-b474-11ea-869a-fdbe5e31326a.jpg)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
