### ISSUE TITLE
update marketplace-testnet.grid.tf

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#651]
upgrade requires

- [x] two s3 backups #650 
- [x] generic checklist
   - [x] network
   - [x] ubuntu
   - [x] k8s
   - [x] minio
   - [x] pools
   - [x] threebot
   - [x] peertube
   - [x] mattermost
   - [x] wiki
   - [x] blog
   - [x] website
   - [x] cryptpad
   - [x] taiga
   - [x] generic container
- [x] upgrade on the marketplace-testnet2.grid.tf
- [x] upgrade marketplace-testnet.grid.tf

**Comment by sasha-astiadi** [comment]
thank you @xmonader lets put it as main priority for the day

**Comment by waleedhammam** [comment]
will test wiki, blog, website

**Comment by OmarElawady** [comment]
will verify peertube, discourse, and threebot.

**Comment by AhmedSa-mir** [comment]
will verify cryptpad, ubuntu

**Comment by dmahmouali** [comment]
will verify mattermost, generic container

**Comment by waleedhammam** [comment]
wikis:
![Screenshot from 2020-08-26 14-30-27](https://user-images.githubusercontent.com/10658229/91303754-c1ca3d00-e7a8-11ea-883a-1fc9e0d1822c.png)
![Screenshot from 2020-08-26 14-39-13](https://user-images.githubusercontent.com/10658229/91304693-318cf780-e7aa-11ea-8f88-3b9e4e9819b9.png)

**Comment by dmahmouali** [comment]
- generic container
![image](https://user-images.githubusercontent.com/36021484/91304463-cfcc8d80-e7a9-11ea-8b33-7bd88288edd5.png)

![image](https://user-images.githubusercontent.com/36021484/91304543-f25ea680-e7a9-11ea-8e80-4e25cb645cac.png)

**Comment by AhmedSa-mir** [comment]
Ubuntu working

![Screenshot from 2020-08-26 14-46-25](https://user-images.githubusercontent.com/18093386/91305232-0a82f580-e7ab-11ea-8836-fc869316d9eb.png)
![Screenshot from 2020-08-26 14-46-57](https://user-images.githubusercontent.com/18093386/91305236-0c4cb900-e7ab-11ea-91a2-d2b9ef85b974.png)

**Comment by waleedhammam** [comment]
blog
![Screenshot from 2020-08-26 14-48-47](https://user-images.githubusercontent.com/10658229/91305375-46b65600-e7ab-11ea-9011-998b38939c18.png)
![Uploading Screenshot from 2020-08-26 14-47-55.png…]()

**Comment by AhmedSa-mir** [comment]
Cryptpad working on testnet2

![Screenshot from 2020-08-26 14-52-32](https://user-images.githubusercontent.com/18093386/91305778-d825c800-e7ab-11ea-9acd-89df20356a89.png)
![Screenshot from 2020-08-26 14-52-21](https://user-images.githubusercontent.com/18093386/91305754-ca704280-e7ab-11ea-9c87-46fee6e73c98.png)

**Comment by dmahmouali** [comment]
- Mattermost on testnet2
![image](https://user-images.githubusercontent.com/36021484/91305157-e7584600-e7aa-11ea-99c3-8b3d40a13b3f.png)
![image](https://user-images.githubusercontent.com/36021484/91305373-461dbf80-e7ab-11ea-9e4e-e64608057e37.png)

**Comment by waleedhammam** [comment]
website
![Screenshot from 2020-08-26 14-55-18](https://user-images.githubusercontent.com/10658229/91305981-2f2b9d00-e7ac-11ea-9b89-cfb613875e09.png)
![Screenshot from 2020-08-26 14-55-12](https://user-images.githubusercontent.com/10658229/91305986-30f56080-e7ac-11ea-895a-8d9410545209.png)

**Comment by OmarElawady** [comment]
Peertube
![Screenshot from 2020-08-26 14-54-32](https://user-images.githubusercontent.com/13040543/91307015-b3325480-e7ad-11ea-9d5b-5b5b66689ba1.png)
![Screenshot from 2020-08-26 14-53-47](https://user-images.githubusercontent.com/13040543/91307024-b594ae80-e7ad-11ea-8ceb-cba762bb62eb.png)

**Comment by OmarElawady** [comment]
discourse
![Screenshot from 2020-08-26 15-01-32](https://user-images.githubusercontent.com/13040543/91307056-c0e7da00-e7ad-11ea-8390-4050e1b701f8.png)
![Screenshot from 2020-08-26 15-01-50](https://user-images.githubusercontent.com/13040543/91307063-c1807080-e7ad-11ea-870e-bb4ad2293aaa.png)

**Comment by OmarElawady** [comment]
Threebot is initialized successfully but the chatflow gets stuck on "Initializing your 3Bot ..." step.
![Screenshot from 2020-08-26 15-18-50](https://user-images.githubusercontent.com/13040543/91308718-fee5fd80-e7af-11ea-9212-35caf80d1566.png)

**Comment by m-motawea** [comment]
k8s
![image](https://user-images.githubusercontent.com/32568986/91311862-dc55e380-e7b3-11ea-8a0f-43d822690684.png)

**Comment by m-motawea** [comment]
minio
![image](https://user-images.githubusercontent.com/32568986/91312388-7ae24480-e7b4-11ea-8eb9-d415d19f8392.png)
![image](https://user-images.githubusercontent.com/32568986/91312417-846bac80-e7b4-11ea-9f07-2c0af8c2d425.png)
![image](https://user-images.githubusercontent.com/32568986/91312454-8d5c7e00-e7b4-11ea-93d1-8b0dd17aa7bf.png)

**Comment by sasha-astiadi** [comment]
i need a summary of state, which one works well on testnet and which one works well on testnet2? @xmonader @rkhamis @waleedhammam @BolaNasr @abom 

please make sure very important we get as many working on testnet as possible today and tomorrow. especially __hosted 3bot__

**Comment by waleedhammam** [comment]
Taiga 
![Screenshot from 2020-08-26 18-43-35](https://user-images.githubusercontent.com/10658229/91332190-16cb7a80-e7cc-11ea-8c69-9da425aba172.png)
![Screenshot from 2020-08-26 18-42-56](https://user-images.githubusercontent.com/10658229/91332192-18953e00-e7cc-11ea-9c0b-b5edcc1fa533.png)
![Screenshot from 2020-08-26 18-41-16](https://user-images.githubusercontent.com/10658229/91332195-192dd480-e7cc-11ea-98c1-101a7cbf5eca.png)
