### ISSUE TITLE
After merging capacitypool branch marketplace solution info don't work

### ISSUE THREAD

**Issue by AhmedSa-mir** [threefoldtech/js-sdk#652]
Clicking on workloads does not show info in marketplace page

![image](https://user-images.githubusercontent.com/18093386/91296902-a73e9680-e79d-11ea-961c-2905c69a1d06.png)

**Comment by AhmedSa-mir** [comment]
Merged on branch: development

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** bc194af0a83371ba74376daa351ebcb4e099f233 , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91304480-d65b0500-e7a9-11ea-8d6e-d4b4e234c82a.png)

![ff1](https://user-images.githubusercontent.com/21218053/91304497-dc50e600-e7a9-11ea-93bd-08a8aae2285a.png)
