### ISSUE TITLE
In dashboard main view console error, Error in render: "TypeError: Cannot read property

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#654]
### Description

Error appears in the console while opening the mainview

### Version information

* OS: Ubuntu 20.04
* project commit/version: latest development branch
* Browser: chrome 84.0.4147.105 

### Steps to reproduce

- Just go to https://localhost/admin

### Traceback/Logs/Alerts

![Screenshot from 2020-08-26 13-16-02](https://user-images.githubusercontent.com/10658229/91297618-ed482a00-e79e-11ea-99d8-662c4569b601.png)

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-08-27 11-40-26](https://user-images.githubusercontent.com/26298009/91424071-a23f1d00-e859-11ea-98ec-b6fcaf9cbe8b.png)
