### ISSUE TITLE
rename advanced solutions -> Infrastructure solutions

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#668]
Let's rename Advanced solutions to Infrastructure solutions maybe with a tooltip (threefold grid primitives)?

**Comment by sasha-astiadi** [comment]
make sure it goes above the end-user solutions

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/91366908-51053e00-e805-11ea-88d8-87e9e31b7660.png)
verified
