### ISSUE TITLE
Can't delete networks on marketplace

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#674]
# Description

Can't delete networks on production testnet marketplace with reservations:

- https://explorer.testnet.grid.tf/api/v1/reservations/workloads/464398
- https://explorer.testnet.grid.tf/api/v1/reservations/workloads/464477
- https://explorer.testnet.grid.tf/api/v1/reservations/workloads/464551

### Version information

* OS: Marketplace
* Browser:  chrome 84

![Screenshot from 2020-08-26 21-34-57](https://user-images.githubusercontent.com/10658229/91348461-15a64780-e7e4-11ea-8c3e-e2e701c2fd8c.png)

**Comment by m-motawea** [comment]
the metadata is missing the owner key in one of these workloads
![image](https://user-images.githubusercontent.com/32568986/91409834-4c14ae80-e846-11ea-81c1-b6c43df95d0e.png)
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/465974
This workload has been created on 08/12/2020

probably something was wrong with metadata back then
