### ISSUE TITLE
harden all string `name` inputs

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#675]
All inputs everywhere for names need to be valid python identifiers not just "not empty"

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 8ac038121caabd81c0d119e8544132015d045917 , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91474634-c2430080-e89a-11ea-860f-5660cd1ea12a.png)

![ff1](https://user-images.githubusercontent.com/21218053/91474716-e272bf80-e89a-11ea-9e84-db7741defeae.png)
