### ISSUE TITLE
Gitea should be part of Apps

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#676]
Gitea requires me to create a network, while I expect it to be easy-install thing

**Comment by OmarElawady** [comment]
I converted it into an App but the PR is still in draft because it doesn't support https from letsencrypt.
#706

**Comment by hossnys** [comment]
verified : Gitea now in Apps and with easy install and supporting https 

![Screenshot from 2020-09-02 10-55-26](https://user-images.githubusercontent.com/26298009/91960836-aca26080-ed0a-11ea-9dbf-36985c3ebaf9.png)

![Screenshot from 2020-09-02 10-56-13](https://user-images.githubusercontent.com/26298009/91960843-af04ba80-ed0a-11ea-881a-bb60b72bdf2e.png)
