### ISSUE TITLE
update kubernetes description in admin and marketplace

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#677]
![image](https://user-images.githubusercontent.com/64129/91410694-934f6f00-e847-11ea-8a4a-d3269b4ca933.png)

zdb isn't related

**Comment by m-motawea** [comment]
![image](https://user-images.githubusercontent.com/32568986/91436510-8f801480-e868-11ea-878f-ab1348c98890.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 519c894c87b0feeb5ac05381df99ce0bd022d989, **Branch** development

**Admin dashboard**

![ff](https://user-images.githubusercontent.com/21218053/91441411-70858080-e870-11ea-9bf3-2c9cd8d56081.png)

**Marketplace dashboard**

![ff1](https://user-images.githubusercontent.com/21218053/91441491-9743b700-e870-11ea-8bff-4f68980a339a.png)
