### ISSUE TITLE
quickstart doc for how to use the TF Grid

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/js-sdk#68]
- [x] register 3bot
- [x] create wallet
- [x] add money
- [x] script to deploy an ubuntu (alpine would even be better):  [here](https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/tutorials/deploy_ubuntu_container.md)
- [x] connect the container to web over https
- [x] use wireguard to connect to it
- [x] make remote ssh connection to deploy something

**Comment by waleedhammam** [comment]
https://github.com/threefoldtech/js-sdk/blob/9b238ef3cff4f2cf79acb038887d9c010cdaade5/docs/wiki/quick_start.md

**Comment by ranatrk** [comment]
add money: https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/tutorials/add_funds_to_wallet.md which is linked in the quick_start doc

**Comment by hossnys** [comment]
verified
