### ISSUE TITLE
rename Threefold Marketplace to be TF Grid Marketplace

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#680]
<img width="354" alt="Screenshot 2020-08-27 at 10 11 05" src="https://user-images.githubusercontent.com/43240801/91415366-3efbbd80-e84e-11ea-86b7-e8e44cb83374.png">

agreed by marketing as well

**Comment by m-motawea** [comment]
![image](https://user-images.githubusercontent.com/32568986/91436430-62336680-e868-11ea-9453-ae5d3b9674b3.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 519c894c87b0feeb5ac05381df99ce0bd022d989 , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91441156-ffde6400-e86f-11ea-8d98-7ff0581f839f.png)
