### ISSUE TITLE
Use better icons for (solution expose, generic containner, monitoring) solutions

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#682]
![image](https://user-images.githubusercontent.com/64129/91422898-17a9ee00-e858-11ea-874c-6fbaba8a0695.png)

**Comment by ehab-hassan** [comment]
![generic containner](https://user-images.githubusercontent.com/10484295/91718772-54e1e900-eb94-11ea-9d0a-332180a93d20.png)
![solution-expose](https://user-images.githubusercontent.com/10484295/91718776-557a7f80-eb94-11ea-8a99-7db5bc4de441.png)
![monitoring](https://user-images.githubusercontent.com/10484295/91718778-56131600-eb94-11ea-9a91-77c22f530da6.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** db38a89e80fd13e999ce8508a9ed62b5bddac4c5 , **Branch** development . 

![ff1](https://user-images.githubusercontent.com/21218053/91838543-f8430480-ec4d-11ea-8205-495a6c5ec0bb.png)
