### ISSUE TITLE
Remove 19.10 release from ubuntu solution

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/js-sdk#684]
# Description

Remove the 19.10 ubuntu release from ubuntu solutions as it reached its end of life date last month and is no longer supported.

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-08-27 18-57-59](https://user-images.githubusercontent.com/26298009/91471729-bbb28a00-e896-11ea-8f2c-351409c1c323.png)
