### ISSUE TITLE
Infrastructure solutions updates

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#688]
- 'S' should be big on 'Solutions', all titles should have first letter on Caps.
-  'Capacity Pools' 'Network' should be on the first top 3 on infrastructure (more logical ordering of the primitives)

**Comment by m-motawea** [comment]
![image](https://user-images.githubusercontent.com/32568986/91436577-ad4d7980-e868-11ea-950d-198827b74d1d.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 519c894c87b0feeb5ac05381df99ce0bd022d989 , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91457640-dc71e400-e884-11ea-856b-2810b6c6cd0a.png)
