### ISSUE TITLE
3Bot success message says "threebot instance"

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#689]
![image](https://user-images.githubusercontent.com/64129/91433911-4af27a00-e864-11ea-9460-9733e3f891da.png)

should be 3Bot instead and should be `has been deployed`

**Comment by m-motawea** [comment]
![image](https://user-images.githubusercontent.com/32568986/91436408-521b8700-e868-11ea-80fe-641d0fb96940.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 519c894c87b0feeb5ac05381df99ce0bd022d989, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91443033-0cb08700-e873-11ea-92d7-fdcdbe7624b6.png)
