### ISSUE TITLE
Use capacity pool / pools instead of just pool/pools

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#691]
Use capacity pool / pools instead of just pool/pools in the marketplace/ admin for the cards shown

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** ab53524b6e0acf87be12805bf76d18c18a9e37d2 , **Branch** development

**Admin dashboard** 

![ff](https://user-images.githubusercontent.com/21218053/91655962-090c4280-eab5-11ea-8d5f-bc9c8fedee96.png)

![ff1](https://user-images.githubusercontent.com/21218053/91655975-250fe400-eab5-11ea-9c50-a21dae322e92.png)

**marketplace dashboard**

![ff2](https://user-images.githubusercontent.com/21218053/91655992-58eb0980-eab5-11ea-9b5d-1a86553efcc8.png)
