### ISSUE TITLE
3bot - what is an expiration date?

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#692]
when we name it 'expiration date', as a user i thought that after this date, i will not be able to access this solution anymore. can we explain 'insert your expiration date to calculate the capacity you need'

<img width="750" alt="Screenshot 2020-08-27 at 13 11 15" src="https://user-images.githubusercontent.com/43240801/91435585-d40ab080-e866-11ea-8a47-8b31f550fcba.png">

- [ ] what if it expires, can i extend the expiration date

**Comment by rkhamis** [comment]
addressed in #815
