### ISSUE TITLE
Flist URL check in Generic container shouldn't 

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#695]
### Search first

Search for similar issues first, if not complete the following template

### Description

when validating the the flist url in generic container chatflow, it shouldn't raise an error but allow the user to retry

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 519c894c87b0feeb5ac05381df99ce0bd022d989 , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91453191-bb5ac480-e87f-11ea-8ee5-299d0084d894.png)

![ff1](https://user-images.githubusercontent.com/21218053/91453253-cc0b3a80-e87f-11ea-9782-7d64ed2bebb2.png)
