### ISSUE TITLE
Generic Flist Always Shows CoreX url even when not interactive

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#696]
### Description

Generic Flist Always Shows CoreX url even when not interactive

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 519c894c87b0feeb5ac05381df99ce0bd022d989 , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91452944-7c2c7380-e87f-11ea-8ea6-76c1e23f6bda.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 519c894c87b0feeb5ac05381df99ce0bd022d989 , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91454165-ee518800-e880-11ea-9417-1c053e00b4ae.png)
