### ISSUE TITLE
admin panel: table showing all reservations ever made by a user.

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/js-sdk#71]
I think it would be nice to have a page where a user can see all the reservation he ever made on the grid.
At the moment only the "know" solution can be found and I often find myself missing a global view on all my reservations.

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-06-29 11-12-47](https://user-images.githubusercontent.com/26298009/86017202-0b561000-ba24-11ea-8597-fd53a90db96a.png)

**Comment by zaibon** [comment]
I'm reopening. I still need to test what has been produce, but from the screentshot only I can tell this is not what I had in mind.
There is no "solution" anymore for this table. We are just showing raw reservations. So the column solution and name doesn't make sense.

Also is there a detail view when the user click on a line of the table ?

**Comment by dmahmouali** [comment]
Yes, threre's a detail view and I will get the raw reservation data.

**Comment by dmahmouali** [comment]
Added in new dashboard :
![image](https://user-images.githubusercontent.com/36021484/86787029-f4876d00-c064-11ea-9238-cf6db81c9227.png)
![image](https://user-images.githubusercontent.com/36021484/86789628-cbb4a700-c067-11ea-840f-784a6cf560e7.png)

**Comment by Pishoy** [comment]
i had issue that I got a blank screen when show the reservation tab while I have network reservations exist 
![image](https://user-images.githubusercontent.com/21987477/86907643-aaaa8f80-c115-11ea-9ba2-6e7062a45f92.png)

after dubbing, we found a reservation which gives an error when listing reservation, not sure why 

the reservation is, http://explorer.testnet.grid.tf/explorer/reservations/460707


![image](https://user-images.githubusercontent.com/21987477/86907512-73d47980-c115-11ea-9307-02311e14c700.png)

**Comment by hossnys** [comment]
This is verified again.

![Screenshot from 2020-07-08 20-40-36](https://user-images.githubusercontent.com/26298009/86957404-f6335c80-c15a-11ea-9b5a-020973f4c273.png)
![Screenshot from 2020-07-08 20-40-54](https://user-images.githubusercontent.com/26298009/86957412-f7fd2000-c15a-11ea-87cb-eb118af1f10f.png)
![Screenshot from 2020-07-08 20-41-01](https://user-images.githubusercontent.com/26298009/86957417-f9c6e380-c15a-11ea-8cf5-dfba7cdc34ac.png)
