### ISSUE TITLE
TF NOW New Disclaimer

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#717]
- an updated Disclaimers

https://github.com/threefoldfoundation/legal/blob/master/src/tf_grid_testnet_disclaimer.md

- put it right after the 3bot login , before showing the dashboard, users have to accept it.
- add one 'disclaimers' section under the t&c on your profile sidebar
<img width="356" alt="Screenshot 2020-08-29 at 16 22 08" src="https://user-images.githubusercontent.com/43240801/91639019-d5c5a700-ea13-11ea-9e4f-3076b4fdaebc.png">

**Comment by abom** [comment]
"This link does not give you access to the document" when opening the cryptpad link.

**Comment by sasha-astiadi** [comment]
@xmonader @abom https://github.com/threefoldfoundation/legal/blob/master/src/TF_Grid_Testnet_Disclaimer.md

**Comment by xmonader** [comment]
correct file: https://github.com/threefoldfoundation/legal/blob/master/src/tf_grid_testnet_disclaimer.md

**Comment by abom** [comment]
Disclaimer is pulled and rendered directly from github:

![Screenshot from 2020-08-30 20-05-54](https://user-images.githubusercontent.com/511438/91666345-39c39a80-eafc-11ea-80bf-2bd3c91414a5.png)

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-08-31 11-42-45](https://user-images.githubusercontent.com/26298009/91706338-8e0f5e80-eb7e-11ea-8dc9-9484e5a84556.png)
