### ISSUE TITLE
Terms and Conditions to be part of all Headers (demo, admin panel.. etc)

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#718]
- pull t&c directly from https://raw.githubusercontent.com/threefoldfoundation/legal/master/src/termsconditions.md

**Comment by abom** [comment]
Terms and conditioned are pulled and rendered directly from github:

![Screenshot from 2020-08-30 20-04-48](https://user-images.githubusercontent.com/511438/91666330-1b5d9f00-eafc-11ea-9a8d-f80c89f87d05.png)

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-08-31 11-40-32](https://user-images.githubusercontent.com/26298009/91706193-57394880-eb7e-11ea-900e-87f5e6a1ae9d.png)
