### ISSUE TITLE
Add a spinner in the time of loading in workloads view and pools view

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#719]
# Description

Add a spinner in the time of loading in workloads view and pools view

### More

![Screenshot from 2020-08-30 11-26-00](https://user-images.githubusercontent.com/10658229/91655794-c1d18200-eab3-11ea-89c1-25175dce1a5b.png)

It takes sometime to load, it would be great for users to know that data are coming

**Comment by abom** [comment]
I think this can be added to base component with configurable options.

**Comment by hossnys** [comment]
verified
- pools

![Screenshot from 2020-08-31 11-45-37](https://user-images.githubusercontent.com/26298009/91706689-0118d500-eb7f-11ea-9629-ea5b14acf5fe.png)

- workloads 

![Screenshot from 2020-08-31 11-46-44](https://user-images.githubusercontent.com/26298009/91706792-2dccec80-eb7f-11ea-9372-1331f3c8f0e7.png)
