### ISSUE TITLE
Rename minio to S3 Storage

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#721]
rename minio solution to S3 Storage

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 438c93ec11e014904f800d21d42019f807e000bc, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91663257-142c9600-eae8-11ea-8251-89b4fb23c13e.png)

**Comment by xmonader** [comment]
Why does it say S3 storage and description is minio :D ?
