### ISSUE TITLE
If chatflow was in error auto restarts when you get back to it

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#723]
Scenario: 
chatflow shows an error and you got to check the alert, then when going back to the chatflow you see the same (go to alert X msg), the chatflow needs to restart over of show a message that the user needs to click on the reload button of the wizard

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 3efb0741dea5f55c83e10da1a285adc1b7d2129a, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91698445-07a14f80-eb73-11ea-8ef0-d3b8211e9319.png)
