### ISSUE TITLE
3bot deployer package (deploy3bot.grid.tf)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#725]
- allows deployment/deletions of 3bots only
- host a staging one on deploy3bot-2.grid.tf (TEST CERT)

**Comment by ranatrk** [comment]
- threebot_deployer package added
- deployed on `deploy3bot.grid.tf ` 

![Screenshot from 2020-08-30 18-28-05](https://user-images.githubusercontent.com/17128393/91669815-4524bf00-eb18-11ea-8019-663738e4e4e7.png)

**Comment by ranatrk** [comment]
staging deployed on `https://deploy3bot-2.grid.tf/`

**Comment by Dina-Abd-Elrahman** [comment]
I tried it the staging https://deploy3bot-2.grid.tf/threebot_deployer/#/ .
## Verification steps:

1- Create 3bot. 
2- Create a new wallet on this 3bot and add packages. 
3- Take a backup. 
4- Delete the 3bot. 
5- Create a new 3bot with the same name as the old one. 
6- Check that the wallet and packages exist in the new 3bot.
