### ISSUE TITLE
Remove 3bot from infra solutions

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#727]
The only way to get a 3bot is from deploy3bot.grid.tf

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 438c93ec11e014904f800d21d42019f807e000bc, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91663222-dd568000-eae7-11ea-82f5-3539bbff9cb1.png)
