### ISSUE TITLE
Admin panel to use testnet identity by default

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#728]
Admin panel to use testnet identity by default because the provisioned has the mainnet one activated and no where in the system it says it needs to use testnet.

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 5ac1425a7c9124978de85eaf15f40f35e9522dba , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91660131-a2971c80-ead4-11ea-8a72-e9924968d4f1.png)
