### ISSUE TITLE
Solution expose when you don't have solutions it should show an error not an empty message

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#729]
Solution expose when you don't have solutions it should show an error not an empty message with 

```
expose solutions:

EMPTY LIST
```

![image](https://user-images.githubusercontent.com/64129/91657766-d3bb2100-eac3-11ea-80d0-7628842a5943.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Comiit_ID** b6c2403cad6086756451c025dba8df700b82a644 , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91663614-3de6bc80-eaea-11ea-9906-314eaf60de51.png)
