### ISSUE TITLE
Add about solution to solutions card

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#731]
Reference solution in the wikis as they have more description

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 3efb0741dea5f55c83e10da1a285adc1b7d2129a , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91703263-32db6d00-eb7a-11ea-8344-2c60e3bd6a3a.png)
![ff1](https://user-images.githubusercontent.com/21218053/91703269-34a53080-eb7a-11ea-9903-5a1c9b9b9288.png)
