### ISSUE TITLE
make sure domains are less confusing and consistent

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#735]
we need to create all domains in a consistent format

$3botuser-$soltype-$instancename.....

```
ahmedthabet-website-w1-tfgw-test01.gateway.tf  (website1) 
ahmedthabet-wiki-w1-tfgw-test01.gateway.tf  ( wiki1)
```

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 1ef7edd7ea95962389d3a071c094fc50cbb0eafb , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91740062-0c85f380-ebb3-11ea-871c-242f1d81d09d.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** db38a89e80fd13e999ce8508a9ed62b5bddac4c5 , **Brnahc** development .

![ff](https://user-images.githubusercontent.com/21218053/91841180-2fb3b000-ec52-11ea-98af-070222a42545.png)

![ff1](https://user-images.githubusercontent.com/21218053/91842817-fe88af00-ec54-11ea-8018-d839c9eb2a3d.png)
