### ISSUE TITLE
show gateway locations when choosing

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#736]
show gateway locations when choosing

**Comment by xmonader** [comment]
@waleedhammam @m-motawea add your remarks please

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 3efb0741dea5f55c83e10da1a285adc1b7d2129a , **Branch** development

![ff1](https://user-images.githubusercontent.com/21218053/91701787-10485480-eb78-11ea-8bd5-c161c4b7f0f9.png)
