### ISSUE TITLE
demo.grid.tf , demo2.grid.tf instead of marketplace

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#738]
instead of marketplace.grid.tf as we want to position them as demo only apps atm until we are fully committed (e.g with backup/restore) #614 
- demo.grid.tf 
- demo2.grid.tf

**Comment by waleedhammam** [comment]
deployed
production: https://demo.grid.tf/
staging: https://demo2.grid.tf/

**Comment by Dina-Abd-Elrahman** [comment]
![ff](https://user-images.githubusercontent.com/21218053/91660743-c27c0f80-ead7-11ea-9af0-84673adf2080.png)

![ff1](https://user-images.githubusercontent.com/21218053/91660748-cad44a80-ead7-11ea-8805-67dcbd524469.png)
