### ISSUE TITLE
over provisioning & test cert to be configured from settings page

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#739]
over provisioning & test cert to be configured from settings page

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 3faf52c9a846f2ee6f5a64307c5afcf1f1d2468f , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91665507-670d4a00-eaf6-11ea-9e0a-c15f9e2dddcd.png)

![ff1](https://user-images.githubusercontent.com/21218053/91665524-81472800-eaf6-11ea-914b-87a25f7ad80e.png)
