### ISSUE TITLE
enforce https doesn't work on demo2.grid.tf

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#741]
enforce https doesn't work on demo2.grid.tf 
![image](https://user-images.githubusercontent.com/64129/91660726-b3955d00-ead7-11ea-9bda-5d7e2510b868.png)
but it does on demo.grid.tf

**Comment by Dina-Abd-Elrahman** [comment]
![ff](https://user-images.githubusercontent.com/21218053/91718136-1ac41780-eb93-11ea-9a6b-a3eb1013621b.png)

![ff1](https://user-images.githubusercontent.com/21218053/91718143-1c8ddb00-eb93-11ea-8a8c-89850c4985ac.png)
