### ISSUE TITLE
As a user I want to view js-ng config (weight=2)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#743]
As a user I want to view/edit js-ng config

**Comment by rkhamis** [comment]
not all fields can be editable to protect the 3Bot deployment.

allow certain fields to be editable and the rest to be read-only


whoever picks this task, please make a list of fields that you consider to be editable before implementing

**Comment by dmahmouali** [comment]
Now we show:
    - `EXPLORER_LOGS`
    - `OVER_PROVISIONING`
    - `OVER_PROVISIONING`
Any suggestion else ?
![image](https://user-images.githubusercontent.com/36021484/95189294-f67cdb80-07cd-11eb-83bb-e971ad34da1e.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 8bf080fe6dbbbc9554bae39a8d7257fcc14e5b66, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/96705057-16e39300-1395-11eb-918e-548875484f3e.png)

![ff](https://user-images.githubusercontent.com/21218053/96705127-2c58bd00-1395-11eb-9cee-24deddeefbb6.png)
