### ISSUE TITLE
threefold demo: should redirect to login after showing Terms & Conditions

### ISSUE THREAD

**Issue by abom** [threefoldtech/js-sdk#746]
### Description

If you're not logged in, It'll show the T&C page, but after pressing "Agree", nothing changes.

### Version information

* OS: ubuntu 18.04
* project commit/version: development
* Browser: chrome
*
### Installation method

Locally using poetry.

### Steps to reproduce

1- Make sure you're not logged in
2- Go to `/marketplace`
3- Press "Agree"

### Traceback/Logs/Alerts

![Screenshot from 2020-08-30 17-01-31](https://user-images.githubusercontent.com/511438/91662430-a92c9080-eae2-11ea-9288-729f31fc5380.png)

**Comment by rkhamis** [comment]
is this still the case?

**Comment by abom** [comment]
I think it's just caching, and it's only reproducible in case of logout, then going to `/marketplace` manually, and once you do a refresh, it works (and the user is already logged out).

Will close this issue, it's not a problem IMHO, as the user already got redirected to login page again normally.
