### ISSUE TITLE
link the manual in the header info

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#752]
along with the t&c, disclaimer let's link the manual-testnet.threefold.io

**Comment by abom** [comment]
Added with "Manual" as label, do you thing e.g. Documentation would be a better?

![Screenshot from 2020-08-30 20-06-48](https://user-images.githubusercontent.com/511438/91666361-58299600-eafc-11ea-9164-eac9768d59c1.png)

**Comment by hossnys** [comment]
verified

![Screenshot from 2020-08-31 11-43-42](https://user-images.githubusercontent.com/26298009/91706548-d29afa00-eb7e-11ea-8ba1-a7d8cc12ca3e.png)
