### ISSUE TITLE
auto backup error in threebot deployer

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#763]
### Description

![Screenshot from 2020-08-30 23-38-01](https://user-images.githubusercontent.com/10658229/91670019-eceebc80-eb19-11ea-827c-a58a91f77795.png)

### Version information

* project commit/version: development

**Comment by waleedhammam** [comment]
fixed at: https://github.com/threefoldtech/js-sdk/pull/764

**Comment by Dina-Abd-Elrahman** [comment]
![ff1](https://user-images.githubusercontent.com/21218053/91718382-873f1680-eb93-11ea-830a-59e14520f62b.png)
