### ISSUE TITLE
Review backup/restore in threebot deployer 

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/js-sdk#765]
### Description

- In **threebot_deployer** package
- Verify backup/restore working ok
- Test against https://deploy3bot.grid.tf/ 
- Check if more than snapshots scenarios

**Comment by ranatrk** [comment]
**Verification steps:**
- Deployed 3bot with name `ranatest` that was added as a subdomain through the deployer `https://deploy3bot.grid.tf/`
- Created a wallet with the name `ranaWallet` through admin panel of 3bot deployed
- Created a backup snapshot through the admin panel of 3bot deployed
- Deleted the 3bot with the name `ranatest` deployed through `https://deploy3bot.grid.tf/` 
- Created a new 3bot deployment with the same name of `ranatest` which was added to another domain
- Accessed the admin of the new deployed and found the wallet I created previously in the wallets (hence restore was successfull)

Restored 3bot :
![Screenshot from 2020-08-31 12-24-14](https://user-images.githubusercontent.com/17128393/91710701-fa8d5c00-eb84-11ea-93c1-499aa6ca1f68.png)

![Screenshot from 2020-08-31 12-24-23](https://user-images.githubusercontent.com/17128393/91710721-0416c400-eb85-11ea-9301-6be62c0f269f.png)

**Comment by Pishoy** [comment]
- as above steps i create a 3bot called `bishoy2` and i create a wallet called `testwallet ` then take a backup as below then i delete  the 3bot 
![image](https://user-images.githubusercontent.com/21987477/91843947-e31ea380-ec56-11ea-9764-c3fd6c91c4cc.png)

![image](https://user-images.githubusercontent.com/21987477/91844133-3133a700-ec57-11ea-9859-9d5741b2b9e5.png)
- resoring done successfully as below 
![image](https://user-images.githubusercontent.com/21987477/91849237-05ff8680-ec5c-11ea-832a-c48a810d927a.png)
