### ISSUE TITLE
don't show wireguard configs at all or make it an optional screen in the end of the solution

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#768]
![image](https://user-images.githubusercontent.com/64129/91709012-6e7a3500-eb82-11ea-8f8c-304e3251075c.png)

![image](https://user-images.githubusercontent.com/64129/91709039-75a14300-eb82-11ea-9fa9-29d9c93c165f.png)

Should show an optional screen in the end do you want to see network information (or debug information) 
https://github.com/threefoldtech/js-sdk/issues/768

**Comment by Pishoy** [comment]
verified on marketplace 
![image](https://user-images.githubusercontent.com/21987477/91878499-afa43f00-ec7f-11ea-8121-1e6be8c4c92b.png)



```
root@tfwallet-prod:/opt/js-sdk# git log -1
commit 1fcd8eec02bc4e39794e0ab22b722106e05ce7c4 (HEAD -> development, origin/development, origin/HEAD)
Merge: 0516bbf 2222cf0
Author: Abdelrahman Ghanem <abom.jdev@gmail.com>
Date:   Tue Sep 1 15:24:42 2020 +0200

    Merge pull request #539 from threefoldtech/development_nginx_default_page
    
    Development nginx default page

```
