### ISSUE TITLE
there should be a way to route on hostname or flist name

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/js-sdk#772]
### Description

We really need a way to route on hostname. As far as we know, right now this is only on IP. This means when updating a container, there is no certainty the IP will stay the same and a reverse proxy will keep on working.

### Implementation

It should be possible to internally route on host/flist names

**Comment by xmonader** [comment]
What does routing on flist name mean? What are you trying to accomplish? are you talking about load balancing?

**Comment by tobiaschielens** [comment]
If we deploy a solution using multiple flists we put a reverse proxy in front so we don't have to worry about https and certs in the solutions. It would be handy to be able to call the deployed flists by name in the reverse proxy's nginx like you can with docker.

**Comment by xmonader** [comment]
I guess what you're seeking is "reconfiguring" the reverse proxy against the new backend IP. removing your workloads and redeploying them again will delete the prev domain on the gateway and you will manage to have it against the new IP
