### ISSUE TITLE
Pool reservation name is not mandatory

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/js-sdk#773]
### Description

Pool reservation name is not mandatory. You can exit the flow without entering a name. The other chat flows ask the name first. Doing this for the pool reservation would align all the solutions

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 38e429f9e1071e0cde795c99824018059cf031fa **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91853673-d607b180-ec62-11ea-9282-db53e6f0d81a.png)
