### ISSUE TITLE
use the word recovery secret instead of password for 3bot deployment

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#774]
use the word recovery secret instead of password for 3bot deployment

**Comment by BolaNasr** [comment]
PR: https://github.com/threefoldtech/js-sdk/pull/785

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-09-01 15-21-36](https://user-images.githubusercontent.com/26298009/91856150-73b0b000-ec66-11ea-8db2-8007bc927ee3.png)
