### ISSUE TITLE
Pasting of env vars in GUI should be smart

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/js-sdk#775]
### Description

Copying env vars takes quite some time now, especially when you have 8 or 10 env vars.

### Implementation

One smart input field that processes the input to env vars. The formatting can be JSON for example.

**Comment by xmonader** [comment]
It used to be 
input of `KEY1=VALUE1;KEY2=VALUE2` and we received a request to upgrade

**Comment by tobiaschielens** [comment]
Maybe give the user both possibilities then?

**Comment by despiegk** [comment]
should use scripts, not through UI

**Comment by tobiaschielens** [comment]
Ok, was sent to ui by the tf team several times
