### ISSUE TITLE
When creating a generic container that is hosted on http it shows https in the end of the flow

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/js-sdk#776]
### Description

The links to the CoreX port and start shell command are starting with https. However, they are listening on HTTP.

### Steps to reproduce

Deploy a flist with CoreX enabled

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/91720611-b6f01d80-eb97-11ea-99ab-50246b9c3a75.png)


Thank for reporting

**Comment by xmonader** [comment]
fixed in #786

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 38e429f9e1071e0cde795c99824018059cf031fa , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91853222-2cc0bb80-ec62-11ea-8d71-f2a652e49fcf.png)
