### ISSUE TITLE
Through the UI you cannot specify the reservation time on networks

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/js-sdk#777]
### Description

Through the UI you cannot specify the time you want to reserve the network. It is also not clear when the network will disappear.

### Version information

* OS: e.g. Ubuntu 20.04, Windows 10
* project commit/version: commit 519c894c87b0feeb5ac05381df99ce0bd022d989
* Browser: chrome 84.0.4147.135
*
### Installation method

Via poetry

### Steps to reproduce

Go into solutions and reserve a network

**Comment by xmonader** [comment]
Which network (mainnet/testnet)? networks don't expire

**Comment by tobiaschielens** [comment]
It was on testnet, it used to expire on the old SDK, thereby probably the misconception

**Comment by hossnys** [comment]
networks are not subject to expiration limits , so no need to select time there ,  this is also shown on any deployed network details , no expiration dates there.

![Screenshot from 2020-09-01 16-49-10](https://user-images.githubusercontent.com/26298009/91866730-1d963980-ec73-11ea-9e26-f2962a8c811a.png)

![Screenshot from 2020-09-01 16-54-10](https://user-images.githubusercontent.com/26298009/91866854-41597f80-ec73-11ea-9ddf-59ad8e818b96.png)
