### ISSUE TITLE
reorder the admin panel sidebar

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#778]
logical ordering

e.g 
logs, alerts -> pushed to the back
actionable items e.g wallet -> go higher

watcher @rkhamis

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 1ef7edd7ea95962389d3a071c094fc50cbb0eafb , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/91739125-c54b3300-ebb1-11ea-905c-dd5873ef21c0.png)
