### ISSUE TITLE
workloads show in 3bot deployer should directly go the domain not showing the workload page

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#779]
workloads show in 3bot deployer should directly go the domain not showing the workload page
have the detailed info in a different view mabye in the same page

**Comment by rkhamis** [comment]
perhaps an "advanced" tab that has the rest of the deployment information?

**Comment by rkhamis** [comment]
pretty sure we should do this for any solution, not just 3Bot. first how to reach it (if it has a domain or over ip) and then the rest of the info in an advanced tab

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-09-01 18-09-51](https://user-images.githubusercontent.com/26298009/91877163-f002bd80-ec7d-11ea-9211-7a5549d7b22c.png)

![Screenshot from 2020-09-01 18-12-53](https://user-images.githubusercontent.com/26298009/91877449-4839bf80-ec7e-11ea-9c1a-5373daaf8c90.png)

![Screenshot from 2020-09-01 18-13-09](https://user-images.githubusercontent.com/26298009/91877451-48d25600-ec7e-11ea-9c58-67011a5631c4.png)
