### ISSUE TITLE
3Bot Deployer wizard improvements

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/js-sdk#783]
- [x] intro to what a 3Bot is ("a virtual System Administrator. It will help you manage your workloads on TF Grid")
     - [x] make sure "solution name" is explained after what a 3Bot is
     - [ ] after asking for name, give following options:
         - [ ] if name already exists, do you want to recover/restore?
         - [ ] delete 3Bot + add warning and confirmation (all data will be lost. cannot be recovered)
         - [ ] reinstall (delete + new install)
         - [ ] if doesn't already exist, then deploy new option
         - [ ] extend reservation

 - [x]  branch is confusing. remove
 - [x] password page. See #774 
 - [x] "solution expiration time" should be "3Bot expiration time" and put by default in 6 months + message about "you can always extend your reservation" #815

 - [x] payment. you cannot go back if you didn't pay. Every two minutes show message "Your payment didn't arrive yet, please pay with [QR CODE]" in case they missed the screen (Added QR code message in the waiting payment page)

contribution from Sasha for the workflow
1. [Start](https://github.com/threefoldtech/js-sdk/issues/802)

3. [Create a new name](https://github.com/threefoldtech/js-sdk/issues/804)
4. [Create a recovery keyd](https://github.com/threefoldtech/js-sdk/issues/807)
5. [Select Expiration time](https://github.com/threefoldtech/js-sdk/issues/815)
6. [Confirm deployment](https://github.com/threefoldtech/js-sdk/issues/814) [ name, password (show button), domain, expiration time)]
7. [Currency](https://github.com/threefoldtech/js-sdk/issues/816)
8. [Pay](https://github.com/threefoldtech/js-sdk/issues/817). if not yet paid, not allowed to go to next step
9. [Deploy](https://github.com/threefoldtech/js-sdk/issues/818)
10. [Wireguard config](https://github.com/threefoldtech/js-sdk/issues/820)
11. [Deployment successful,](https://github.com/threefoldtech/js-sdk/issues/821) go to solution or go back home

other issues / suggestion:

new section for [3bot deployment list](https://github.com/threefoldtech/js-sdk/issues/801) on home

[delete restart button](https://github.com/threefoldtech/js-sdk/issues/808)

**Comment by despiegk** [comment]
another suggestion was to start with the question

what do you want to do

- new 3bot
- delete 3bot
- re-install 3bot
- extend 3bot reservation
- restore 3bot

then go with right questions from there e.g. when last 3 questions, allow user to select the 3bot

**Comment by despiegk** [comment]
ask confirmation when needed e.g. delete, reinstall, restore (just to make sure)

**Comment by xmonader** [comment]
Actions
- Delete (ask also if he wants to remove backups)
- New -> chatflow
- Extend  -> separate chatflow? -check if query params working or list all and the user choose from-

**Comment by waleedhammam** [comment]
work at: https://github.com/threefoldtech/js-sdk/pull/883

Blocked on actor authentication.

**Comment by waleedhammam** [comment]
unblocked using bottle server

**Comment by Pishoy** [comment]
verified 

 -   delete 3bot
 -   re-install 3bot
  -  extend 3bot reservation
  - restore 3bot

 sdk version  
```
root@tfwallet-prod:/opt/js-sdk# git log -1
commit b4e797edde034886342740b966857951faeb6afb (HEAD -> development, origin/development, origin/HEAD)
Author: xmonader <xmonader@gmail.com>
Date:   Sun Sep 6 15:02:35 2020 +0200

    improve error messages for threebot failure and non-reachable websites (#1007)
```
