### ISSUE TITLE
mattermost solution review

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#788]
![image](https://user-images.githubusercontent.com/64129/91724011-ec4b3a00-eb9c-11ea-908f-c87646a87b4a.png)

- Please enter a name for your solution (Can be used to prepare domain for you and needed to track your solution on the grid ) -> Choose a unique name for your mattermost instance (will be used in listing and deletions in the future and in having a unique url)

![image](https://user-images.githubusercontent.com/64129/91724152-2ae0f480-eb9d-11ea-9959-93ea77b2b682.png)
- Disk size info is too level
we should ask for resources in form of  `Silver, Gold, Platinum` or whatever form that maps to underlying mapping to mru, cru and disk space

- Expiration 
![image](https://user-images.githubusercontent.com/64129/91724284-5d8aed00-eb9d-11ea-8a3b-fed8fc78383c.png)

Let's make the default 2 months or 6 month

- Waiting for payment should keep showing the qrcode in case it was missed
![image](https://user-images.githubusercontent.com/64129/91724408-92973f80-eb9d-11ea-8e6e-64fbd7cabc26.png)

- Deployment information should be removed (I can't do anything and already paid)

![image](https://user-images.githubusercontent.com/64129/91724561-c2464780-eb9d-11ea-9059-d120a46c7419.png)

- Improve deployment message 
![image](https://user-images.githubusercontent.com/64129/91724612-d722db00-eb9d-11ea-9993-3b7efc1e662b.png)

- Mention the deployment should take around 2 3 minutes, but might take longer (better phrasing needed @rkhamis  )

- Success phrasing is wrong
![image](https://user-images.githubusercontent.com/64129/91724709-ffaad500-eb9d-11ea-9318-d1df3e8ac7be.png)
`Congratulations! Your own instance from mattermost deployed successfully` should be `you deployed a new instance (solution name) of mattermost`
- remove container ip info

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** db38a89e80fd13e999ce8508a9ed62b5bddac4c5 , **Branch**  development.

![ff](https://user-images.githubusercontent.com/21218053/91835458-b2843d00-ec49-11ea-9c38-c2f91f03d872.png)

![ff](https://user-images.githubusercontent.com/21218053/91835512-ca5bc100-ec49-11ea-895e-fdc69a4146cf.png)

![ff2](https://user-images.githubusercontent.com/21218053/91835628-ebbcad00-ec49-11ea-8e06-5f646b55dca0.png)

![ff2](https://user-images.githubusercontent.com/21218053/91836799-92557d80-ec4b-11ea-9491-928bfb102812.png)

![ff3](https://user-images.githubusercontent.com/21218053/91836805-9386aa80-ec4b-11ea-87c8-656e64e90b61.png)

**Comment by Dina-Abd-Elrahman** [comment]
![ff](https://user-images.githubusercontent.com/21218053/91850836-80310a80-ec5e-11ea-9042-e2f49046c3df.png)
