### ISSUE TITLE
Better solutions listing

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#789]
![image](https://user-images.githubusercontent.com/64129/91724945-4b5d7e80-eb9e-11ea-9d53-fc389093a0bd.png)

Right now clicking on solution name shows the following
![image](https://user-images.githubusercontent.com/64129/91724984-57494080-eb9e-11ea-8ccf-f7873d0a57a6.png)
Which is too much for the enduser, It should show the deployed instances as cards where each card has
- mattermost logo
- instance name
- button to go to the deployed solution
- button to get the workload details

**Comment by dmahmouali** [comment]
should we make solutions listing like this ?
![image](https://user-images.githubusercontent.com/36021484/91833717-59b3a500-ec47-11ea-99d2-16349c38aa52.png)
![image](https://user-images.githubusercontent.com/36021484/91833854-8962ad00-ec47-11ea-81a2-0f167936dd35.png)

**Comment by xmonader** [comment]
@ashraffouda please move it to data table instead

**Comment by xmonader** [comment]
Here's a comment from @sasha-astiadi 


how it should look like:

My Deployed Wiki
Here is the list of your successfully deployed wiki solutions.  Click on the address link to access your wiki. Click 'extend 'to expand your wiki's lifetime, or click 'delete' to remove your wiki off of the TF Grid.
s
![photo_2020-09-01_14-17-55](https://user-images.githubusercontent.com/43240801/91850605-19abec80-ec5e-11ea-8432-a6e052abf171.jpg)

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-09-02 14-08-23](https://user-images.githubusercontent.com/26298009/91978933-41b25300-ed25-11ea-89da-40c1ef73100a.png)

![Screenshot from 2020-09-02 14-08-33](https://user-images.githubusercontent.com/26298009/91979096-850cc180-ed25-11ea-874e-a2cdcf6a49c8.png)
