### ISSUE TITLE
sanity checks for solutions are too late

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#792]
![image](https://user-images.githubusercontent.com/64129/91732954-3e925800-eba9-11ea-957c-884d528816d1.png)

Here, after asking for solution name, resources needed, the pool it got surprised i don't have a netowork

Checks for pools and networks should be done very early before even asking for solution name

**Comment by Pishoy** [comment]
verified before set name of soultion give below of 
![image](https://user-images.githubusercontent.com/21987477/91861183-d311be80-ec6c-11ea-94c6-8365b1712725.png)
