### ISSUE TITLE
3bot default landing page should go to admin if not deployed with any other package with domains

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#794]
![image](https://user-images.githubusercontent.com/64129/91736331-c8dcbb00-ebad-11ea-8961-73ac5cd7db4d.png)

if the system is deployed only for 3bot usage it should redirect / to -> /admin

**Comment by waleedhammam** [comment]
duplicate of https://github.com/threefoldtech/js-sdk/issues/505 ?
