### ISSUE TITLE
Review billing details page

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#795]
![image](https://user-images.githubusercontent.com/64129/91736507-10fbdd80-ebae-11ea-9a11-7fd3253d0fca.png)

remove the word `billing details` it's not in the right size or make sure it standsout in the page

- 3bot app should be clear it's payment using (QR code)

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-09-01 16-35-51](https://user-images.githubusercontent.com/26298009/91864647-becfc080-ec70-11ea-86ab-865997e92355.png)
