### ISSUE TITLE
errors while interacting with explorer should be logged and raised as alerts

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#798]
![image](https://user-images.githubusercontent.com/64129/91746039-3f80b500-ebbc-11ea-9e6a-3dace5592884.png)
e.g this should be seen in alerts and maybe even in the error message we add the correct link in explorer to check the workload

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 38e429f9e1071e0cde795c99824018059cf031fa ,  **Branch** development.

![ff](https://user-images.githubusercontent.com/21218053/91861182-d2792800-ec6c-11ea-85be-8911f9fb69fa.png)

![ff1](https://user-images.githubusercontent.com/21218053/91861240-e15fda80-ec6c-11ea-8d4c-af9f81d94b70.jpg)
