### ISSUE TITLE
3bot deployment:  new screen for deployment list. where can i see my deployed 3bot?

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#801]
**3bot deployment user flow**

Big issue: I have deployed a 3bot but now i totally forgot my domain address.. There is no info of anywhere where i could see the address again on the deploy3bot.grid.tf
there is no info about my existing workload.

suggestion:
create a section below new 3bot called
"My 3Bot Deployment" listing all the 3bot i deployed and link of how to access the admin panel....

![photo_2020-09-01_10-29-39](https://user-images.githubusercontent.com/43240801/91826601-1acd2180-ec3e-11ea-879b-127cd771958b.jpg)

Show "You have deployed 0 3Bot. Deploy a 3Bot now" if users never deployed a 3Bot before.

show also 3bot deployment that are still in progress, with the choice of continue deploying, or delete deployment process.

all deployment should be tracked, when ;'continue' is clicked, user should be brought back to the step where they left the last time.

**Comment by rkhamis** [comment]
we have an overview of deployed workloads where you can see your previously deployed 3bots. and in the details you can find their domains already.

the inprogress ones is not going to be a quick thing, so i say let's skip it for now

**Comment by sasha-astiadi** [comment]
@rkhamis where can I  see the overview

**Comment by rkhamis** [comment]
each solution has a listing of all the deployed workloads of its type. check it out on http://deploy3bot.grid.tf/
also, there's now a "view instances" at the home screen where you can check all your deployed solutions.
we also now redirect to the overview page after chat ends
