### ISSUE TITLE
3bot deployment: screen #1 feedback

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#802]
# Screen 1

<img width="1369" alt="Screenshot 2020-08-31 at 15 54 37" src="https://user-images.githubusercontent.com/43240801/91822037-8069df80-ec37-11ea-8e8c-18b41f7d8a59.png">

- 
“Deploy a new 3Bot” button
Button should be in the box under the description, not in the right top corner.

New Description:

“Hi! This is 3Bot! 3Bot is your digital identity on top of the TF Grid. It comes with a system administrator panel, which is a powerful tool that helps you deploy, maintain and monitor solutions built on top of the Threefold Grid. 

Click on ‘Start’ to start deploying your own 3Bot now.

**Comment by xmonader** [comment]
It looks different right now 
![image](https://user-images.githubusercontent.com/64129/91838809-5cfe5f00-ec4e-11ea-90d4-f1c048475aa9.png)


```
Hi! This is 3Bot! 3Bot is your digital identity on top of the TF Grid. It comes with a system administrator panel, which is a powerful tool that helps you deploy, maintain and monitor solutions built on top of the Threefold Grid.
```
Could be a good new description

**Comment by sasha-astiadi** [comment]
As a user I don't understand what an instance is

**Comment by sasha-astiadi** [comment]
And I don't understand what a virtual system administrator does

**Comment by despiegk** [comment]
"system administrator" is ok, this is our target market
instance is also ok
