### ISSUE TITLE
Farm management dashboard: can't see a user's farms

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#803]
My threebot ID on mainnet is 185 and my farm ID is 173655. 

When you load farm management tab on the dashboard it fails to load farms. It tries to load following url:
`https://explorer.grid.tf/api/v1/farms?owner=185`

but it should not go to `api/v1` for the farms, instead it should be:
`https://explorer.grid.tf/explorer/farms?owner=185`

This is because the capacity pools is not live on mainnet yet, so the `/api/v1` endpoint is not served there.

**Comment by sasha-astiadi** [comment]
@DylanVerstraete when you create issue maybe its better to start the title, with the platform tested / where you found the issue,
e.g. Explorer: Can't see a user's farm
