### ISSUE TITLE
3bot deployment: screen #3 feedback

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#804]
# Screen 3

<img width="1222" alt="Screenshot 2020-08-31 at 15 54 55" src="https://user-images.githubusercontent.com/43240801/91823052-f28ef400-ec38-11ea-9e92-722d56044502.png">

New title: Get a 3Bot Name

New Description: Just like humans, each 3Bot needs their own unique identity to exist on top of the Threefold Grid. Please enter a name for your new 3Bot. This name will be used to create the web address that could give you access to your 3Bot anytime, as long as it remains active.

**Comment by xmonader** [comment]
> Just like humans, each 3Bot needs their own unique identity to exist on top of the Threefold Grid. Please enter a name for your new 3Bot. This name will be used as the web address that could give you access to your 3Bot anytime

3Bot name isn't used as the webaddress, you can't go to mysolname on the internet, it's used to create a URL to access your 3Bot. and not anytime (it's for as long as 3Bot is alive)

**Comment by BolaNasr** [comment]
PR: https://github.com/threefoldtech/js-sdk/pull/830

**Comment by sasha-astiadi** [comment]
i understand URL. Users don't.
"A Uniform Resource Locator (URL), colloquially termed a web address" -> https://en.wikipedia.org/wiki/URL.

by anytime: meaning when its active.

@ xmonader i changed the text already

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-09-01 16-39-32](https://user-images.githubusercontent.com/26298009/91865085-4b7a7e80-ec71-11ea-86cd-e6f5d8322450.png)
