### ISSUE TITLE
3bot deployment: screen #3 branch name step should just be removed

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#805]
why do i have to name it? will it matter if i just deploy on development branch as default? as a user i want to know why i should create a branch. what is branch?. if its not necessary we could just use 'development' as default and remove this step

<img width="1235" alt="Screenshot 2020-08-31 at 15 55 05" src="https://user-images.githubusercontent.com/43240801/91823478-911b5500-ec39-11ea-8163-81e2b89ae6d7.png">

**Comment by rkhamis** [comment]
i still feel weird about this one. perhaps it can be an advanced option instead?

**Comment by xmonader** [comment]
addressed in https://github.com/threefoldtech/js-sdk/issues/783
