### ISSUE TITLE
3bot deployment: #screen 4 password feedback

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#807]
<img width="1440" alt="Screenshot 2020-08-31 at 15 55 43" src="https://user-images.githubusercontent.com/43240801/91823737-fa9b6380-ec39-11ea-99c5-ca2cc79ce532.png">

# Screen 4 

- [ ] New name: Create a recovery key (min. 6 characters)

- [ ] new text: Everything you own and create on top of the TF Grid is fully secured, encrypted, and private, only accessible by using your 3Bot. Please create a unique recovery key for your 3Bot. By using this recovery key, you will be able to recover any workload related to your 3Bot on top of the TF Grid.

- [ ] New Box: Confirm recovery key, no copy/paste allowed

**Comment by rkhamis** [comment]
whoever picks this, please update text here. but keep it as "recovery secret"

**Comment by sasha-astiadi** [comment]
@rkhamis recovery secret doesnt make sense. change to 'recovery key'.

**Comment by despiegk** [comment]
key, ok
confirmation box can be for next version if difficult, the copy paste we can't limit
