### ISSUE TITLE
3bot Deployment : ALL screens why do we have a restart button? 

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#808]
we should not have that restart button on the corner without explaining to users what it is.
for example,
<img width="311" alt="Screenshot 2020-09-01 at 10 13 07" src="https://user-images.githubusercontent.com/43240801/91824888-c2952000-ec3b-11ea-8f58-01963a8e9e0e.png">

i just paid for my 3bot and it was being processed but the payment took so long, i thought the restart button was a reload button for the page.
but when i clicked it, i went back to the very first starting page and all my info is gone. it is very frustrating. i dont want to do it all over again.
also what happened to the token i paid already when this happens?

suggestion: Remove the restart button

**Comment by rkhamis** [comment]
actually, without a restart button, you wouldn't be able to start anew. specially that we save the state of a chatflow if a user stops midway for any reason.

perhaps a help text explaining what would happen would be a better approach

**Comment by rkhamis** [comment]
@abom @xmonader  what do you guys think?

**Comment by xmonader** [comment]
moved to type question, what we can do is add a tooltip or have it as a button with title (restart chatflow). button removal is out of question at this point.

**Comment by sasha-astiadi** [comment]
If I wanted to start new I would just go to home button.
Why would I wanna start new, when I'm already in the middle of creating a new 3bot?this will just mess my sign up process if I accidentally click on it

**Comment by xmonader** [comment]
> If I wanted to start new I would just go to home button or deploy3bot.grid.tf.
> Why would I wanna start new, when I'm already in the middle of creating a new 3bot?this will just mess my sign up process if I accidentally click on it

In case of error we instruct the user to click on the upper right restart button.
