### ISSUE TITLE
3bot deployment: screen #6 confirmation should come before payment page.

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#814]
as a user i wanna know what im paying before pay.
what if i paid and i wanna change something? that wouldnt be possible. therefore this screen should come after expiration time screen and before payment screen.

<img width="1440" alt="Screenshot 2020-08-31 at 16 00 16" src="https://user-images.githubusercontent.com/43240801/91828167-10ac2280-ec40-11ea-9ce7-5cf5ea1b1931.png">

New Title: Confirm Your 3Bot Deployment
New description: Please read and confirm your 3Bot deployment information, or go back to the previous steps to make changes.

3Bot Name: 
3Bot Admin Address:
Expiration Date:

----
Change the ‘next’ button into ‘Confirm’

**Comment by rkhamis** [comment]
we removed this screen altogether as per yesterday's meeting
