### ISSUE TITLE
3bot deployment: screen #5 - expiration feedback

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#815]
# Screen 5 

<img width="1440" alt="Screenshot 2020-08-31 at 15 55 45" src="https://user-images.githubusercontent.com/43240801/91828509-84e6c600-ec40-11ea-9cc8-9e49e32885aa.png">

New Title: Expiration Date and Time

New description: Please enter the expiration date of your 3Bot. This will be used to calculate the amount of capacity you need to keep your 3Bot alive and build projects on top of the TF Grid. But no worries, you could always extend your 3Bot’s lifetime on 3Bot Deployer's home screen.

**Comment by xmonader** [comment]
This is not correct

```
New description: Please enter the expiration date of your 3Bot. This will be used to calculate the amount of capacity you need to keep your 3Bot alive and build projects on top of the TF Grid. But no worries, **you could always extend your 3Bot’s lifetime on the deployed 3Bot Admin Panel.**
```

you can't extend your 3Bot lifetime on the 3Bot Admin Panel

**Comment by sasha-astiadi** [comment]
So what happens when it expires?

**Comment by sasha-astiadi** [comment]
Isn't its what capacity pool supposed to do,

**Comment by xmonader** [comment]
When it expires it gets removed from the grid, then you can redeploy it again, the extending option should be visible on the 3Bot deployer website (because they're who provisioned the 3Bot) .

**Comment by sasha-astiadi** [comment]
What happens when I redeploy? All my solutions are gone on the redeployed one?

**Comment by xmonader** [comment]
1- Solution information exists on the grid/explorer, don't have anything to do about 3Bot data, when 3Bot starts it reads your data from the explorer.
2- 3Bot has backup feature if you have anything custom.

**Comment by sasha-astiadi** [comment]
so the final call, can they extend the 3bot? if yes, from which page and by clicking which button

**Comment by xmonader** [comment]
reopen for verification

**Comment by hossnys** [comment]
verified

![Screenshot from 2020-09-01 20-31-16](https://user-images.githubusercontent.com/26298009/91891684-c358a100-ec91-11ea-87cd-be9febf2b385.png)
