### ISSUE TITLE
3bot deployment: # Screen 7 - Currency feedback

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#816]
# Screen 7 - Currency
<img width="1440" alt="Screenshot 2020-08-31 at 15 55 49" src="https://user-images.githubusercontent.com/43240801/91828715-c5464400-ec40-11ea-95c7-987191f22e00.png">

New Title: Select Payment Currency
New description: Please select the currency you would like to pay your 3Bot deployment with.

**Comment by BolaNasr** [comment]
PR: https://github.com/threefoldtech/js-sdk/pull/828

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-09-01 15-23-36](https://user-images.githubusercontent.com/26298009/91856320-b5415b00-ec66-11ea-8de1-0f5f15a8e145.png)
