### ISSUE TITLE
3bot deployment : # Screen 8 - Pay

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#817]
# Screen 8 - Pay

<img width="1440" alt="Screenshot 2020-08-31 at 15 55 58" src="https://user-images.githubusercontent.com/43240801/91829164-61704b00-ec41-11ea-89cc-cada09327b44.png">

New Title: Make Your Payment

Go to your Stellar Wallet and scan the CR Code below, or enter the information on your wallet manually in order to proceed with the payment. 

IMPORTANT: Please write the reservation ID as the memo_text of your payment in order for the transaction to be processed successfully. The payment will usually take a few minutes to be processed.
Please click ‘next’ once you have made the payment.

Note:
User shouldnt be allowed to proceed until their payment is received..
- If they click on next button before paying, send a small warning / notification:
“Please make a payment in order to proceed.” or

- If they click on next button when the payment is processing, send a small warning / notification:
“Your payment is being processed. Please click again in a few minutes.”

**Comment by rkhamis** [comment]
we already show a new payment screen

**Comment by sasha-astiadi** [comment]
@rkhamis did you add the texts
