### ISSUE TITLE
3bot: screen #9 - deploying your 3Bot

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#818]
<img width="1440" alt="Screenshot 2020-08-31 at 15 59 42" src="https://user-images.githubusercontent.com/43240801/91829607-f83d0780-ec41-11ea-8429-ff5598165703.png">

new title: Deploying your 3Bot...

 It will usually take a few minutes to succeed. Please wait patiently.
You will be automatically redirected to the next step once succeeded.

**Comment by rkhamis** [comment]
done

**Comment by AhmedSa-mir** [comment]
![Screenshot from 2020-09-01 15-18-03](https://user-images.githubusercontent.com/18093386/91856864-66e08c00-ec67-11ea-94b5-2cacafa3abea.png)

**Comment by Dina-Abd-Elrahman** [comment]
![ff](https://user-images.githubusercontent.com/21218053/91962664-1b80b900-ed0d-11ea-8101-a403e17f4c97.png)
