### ISSUE TITLE
3bot deployment: screen #10 Wireguard config

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#820]
<img width="577" alt="Screenshot 2020-09-01 at 10 18 42" src="https://user-images.githubusercontent.com/43240801/91830052-84e7c580-ec42-11ea-9952-e3f24d71901d.png">

New title; Import your Network Tunnel to Wireguard

Text: download this network tunnel file and add this file to your wireguard by selecting 'Import tunnel from files'.
click (manual link) to read more instruction on setting up wireguard network tunnel.

**Comment by rkhamis** [comment]
already moved to debug information
