### ISSUE TITLE
3bot deployment: screen #11 success

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#821]
<img width="537" alt="Screenshot 2020-09-01 at 10 20 39" src="https://user-images.githubusercontent.com/43240801/91830348-f3c51e80-ec42-11ea-8a98-fa0f7d623a23.png">

NEW title: 3Bot Deployment Successful
|
Congratulations, you have just successfully deployed a 3Bot!
Please go to https://.....   To access your 3Bot.
 
Note:
~‘Next button’ should be ‘My 3Bot’ button: directing you to a page with a list of your deployed 3bot.
should be a home button too instead of back.~

**Comment by despiegk** [comment]
"Next" ok for now because too hard, 
after next redirect to the url itself

**Comment by hossnys** [comment]
success message changed , but the finish button redirect to blank page with just page header 

![Screenshot from 2020-09-01 18-30-28](https://user-images.githubusercontent.com/26298009/91882674-9d2c0480-ec83-11ea-8391-d7a7c9098856.png)

![Screenshot from 2020-09-01 19-02-09](https://user-images.githubusercontent.com/26298009/91883747-2859ca00-ec85-11ea-8025-eb4ed739379c.png)

**Comment by hossnys** [comment]
the redirection problem of finish button should be fixed by this PR #864 and it's verified now
