### ISSUE TITLE
UX: improvement to file upload step in wizard (weight=1)

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/js-sdk#825]
In wizards (like minio solution) the step it asks about file upload (ssh key) clicking on the "clip" icon doesn't do anything instead I have to click in the white space instead) 

I always try to click on the clip icon first, so I assume that's probably the more intuitive way.

![image](https://user-images.githubusercontent.com/10920323/91832099-3d166d80-ec45-11ea-8289-0bc00180b79c.png)

So I think clicking anywhere in the upload box should open the open file dialog

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 0a51ddb483321851dad61fc3ccdd1a5a99f64b07, **Branch** development_11.0.1b

![ff](https://user-images.githubusercontent.com/21218053/95867165-23e6fd80-0d69-11eb-875a-6841c01abe4e.png)
