### ISSUE TITLE
Port new updates in apps chatflow to 3Bot chatflow in 3Bot deployer

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/js-sdk#826]
We have to port the new updates in apps chatflow in 3bot chatflow.

**Comment by xmonader** [comment]
> We have to port the new updates in apps chatflow in 3bot chatflow.

what are these updates?

**Comment by dmahmouali** [comment]
> > We have to port the new updates in apps chatflow in 3bot chatflow.
> 
> what are these updates?

This changes from app chatflow review: https://github.com/threefoldtech/js-sdk/pull/797/files

**Comment by m-motawea** [comment]
I think the changes are already there since they are in the parent class

**Comment by dmahmouali** [comment]
Close because of all changes in the base.
