### ISSUE TITLE
3bot deployer: eternal loading animation after last step

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/js-sdk#829]
When trying to deploy a 3bot using the deployer (on testnet):

- Reserved for 1 day
- Paid in FreeTFT
- Payment was successful
- Pressed download button on wireguard config
- Saved wireguard config, and enabled the wireguard interface on my laptop
- A message popped up on the deployer about a `request timeout`. Pressed ok on the message box
- Press the next button on the wireguard config screen
- Text is replaced with a loading spinner, and a loading bar appears at the top of the chatbox
- Page keeps on showing these loading spinners, nothing really seems to happen

![image](https://user-images.githubusercontent.com/22023708/91838766-4eb04300-ec4e-11ea-8faa-8bc683f2f151.png)

**Comment by waleedhammam** [comment]
> A message popped up on the deployer about a request timeout. Pressed ok on the message box

I think the server is being updated at this time, this is the only time this message can appear.

**Comment by hossnys** [comment]
3bot deployment is working fine and setup done successfully

![Screenshot from 2020-09-07 11-15-35](https://user-images.githubusercontent.com/26298009/92371809-654a1480-f0fc-11ea-815c-0cbd79fec57d.png)

![Screenshot from 2020-09-07 11-16-53](https://user-images.githubusercontent.com/26298009/92371820-67ac6e80-f0fc-11ea-889c-bd31e72b941a.png)
