### ISSUE TITLE
TF GRID DEMO: Replace texts of all solutions

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#832]
- Wiki: Wiki is a versatile online encyclopedia builder, accessible via a public web address.

- Website is a P2P alternative to centralized cloud-hosted websites. Host your own website with access via a public web address.

- Peertube is an open-source video platform that uses peer-to-peer technologies to reduce load on individual servers when viewing videos.

- Discourse is an open source Internet forum and mailing list management software application built to educate members about civil community engagement.

- Mattermost is a flexible, open source messaging platform that enables secure team collaboration.

- Cryptpad is a fully-secured, encrypted alternative to popular office tools and cloud services.

- Blog is a P2P alternative to centralized blogging platforms like Tumblr or Blogspot.

- Taiga is a P2P alternative to centralized project management tool for multi-functional agile teams.

**Comment by xmonader** [comment]
all of `access via an IP` shouldn't be mentioned. As they require configurations on the enduser side. and also is "domain" something enduser understands? I think It should be "Accessible on the Public Internet"

**Comment by sasha-astiadi** [comment]
@xmonader text updated

**Comment by Pishoy** [comment]
verified not sure if we can enhance the uncompleted description as below 

![image](https://user-images.githubusercontent.com/21987477/91882053-ba140800-ec82-11ea-81e5-1783e10d4e50.png)

```
root@tfwallet-prod:/opt/js-sdk# git log -1
commit ac3b448b791d974c540a3d916e0de3ab3b3623c6 (HEAD -> development, origin/development, origin/HEAD)
Merge: 2419f07 a1d7d8d
Author: xmonader <xmonader@gmail.com>
Date:   Tue Sep 1 18:26:20 2020 +0200

    Merge pull request #863 from threefoldtech/development_adminsidebar
    
    update sidebar
```
