### ISSUE TITLE
TF GRID Demo : change chatfliow into "Go to Manual"

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#833]
as a user i dont understand what a 'chatfliow' is.
<img width="294" alt="Screenshot 2020-09-01 at 13 22 38" src="https://user-images.githubusercontent.com/43240801/91843694-760b0e00-ec56-11ea-95cb-e6288a991f3e.png">

change chatfliow into "Go to How-to Manual"

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** f7e8cf778a66de2a280feda51cdb06c41761a594 **Branch** development

![gg2](https://user-images.githubusercontent.com/21218053/91874287-51289200-ec7a-11ea-881e-77a60865e82e.png)
