### ISSUE TITLE
As a user When I click on package I want to see a list of its chats and correct links to them (weight=3)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#834]
As a user When I click on package I want to see a list of its chats and correct links to them

**Comment by rkhamis** [comment]
its package should define all the links it provides and should be viewable

**Comment by ranatrk** [comment]
- Add chatflows button in installed packages card that have chatflows that opens a popup with clickable chatflows names
- The check for the chatflows is added and passed in the package info in listing them

![Screenshot from 2020-10-21 15-07-43](https://user-images.githubusercontent.com/17128393/96727370-41444900-13b3-11eb-87ab-30f5adfbf246.png)
![Screenshot from 2020-10-21 15-07-53](https://user-images.githubusercontent.com/17128393/96727379-42757600-13b3-11eb-9182-849262cd6dd8.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** f0aa7a4148b39b3ad1c8f7700454485215f2a366, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/96846008-a2225e80-1451-11eb-9add-7ffa29f9d080.png)
![ff1](https://user-images.githubusercontent.com/21218053/96846012-a3538b80-1451-11eb-8f09-33d914b8b535.png)
