### ISSUE TITLE
UX: in the workload page, when the page is changed to higher number then change the filter type page number stays (weight=2))

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/js-sdk#835]
When filtering workloads, and then change the page number (say page 2 or 3) then change the filter (workload type for example) it stays on the other page. This sometimes result that the view doesn't show anything specially if there are few results of the new filter that fits only on the first page.

**Comment by rkhamis** [comment]
weight = 2

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** a1b57396c977ac25d566d340405a9f9a177ddeb8, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/96369296-56be3680-1159-11eb-9ba3-ca1b70129885.png)
