### ISSUE TITLE
Need to activate the previous step button in the payment step if I doesn't transfer money yet 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/js-sdk#836]
Need to activate the previous button in the payment step if I doesn't transfer money yet, Maybe I choose a wrong currency. 

![ff](https://user-images.githubusercontent.com/21218053/91844836-71475980-ec58-11ea-83cf-69a02f006a2a.png)

**Comment by xmonader** [comment]
you can do reload on the upper right too, at this point we don't know if you actually scanned or not to enable the previous step button
