### ISSUE TITLE
UX/Workloads page: date is formated as mm/dd/yyyy

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/js-sdk#838]
- It's either you use the standard dd/mm/yyyy date or use the browser locale formatting. Forcing a mm/dd/yyyy is very confusing.
- Allow sorting on the date.

**Comment by dmahmouali** [comment]
Formatted in the last PR and for the sorting `v-data-table` allow sorting by default.

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 0a51ddb483321851dad61fc3ccdd1a5a99f64b07, **Branch** development_11.0.1b

![ff](https://user-images.githubusercontent.com/21218053/95867461-76281e80-0d69-11eb-9c68-af116ca039ea.png)
