### ISSUE TITLE
TF GRID DEMO:'my workload' information display hierarchy doesnt make sense.

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#840]
if im on 'my workloads' page, the main thing i should see is the list of my workload.
name, domain name, expiration date, and how to access them.

<img width="932" alt="Screenshot 2020-09-01 at 14 07 04" src="https://user-images.githubusercontent.com/43240801/91849509-7d351a80-ec5c-11ea-8d8f-cfbd689e328f.png">

i dont wanna be asked to make a new workload. this is just a repetition from the same wizard. its confusing, i dont see the difference.

---

how it should look like:

My Deployed Wiki
Here is the list of your successfully deployed wiki solutions.  Click on the address link to access your wiki. Click 'extend 'to expand your wiki's lifetime, or click 'delete' to remove your wiki off of the TF Grid.
s
![photo_2020-09-01_14-17-55](https://user-images.githubusercontent.com/43240801/91850605-19abec80-ec5e-11ea-8432-a6e052abf171.jpg)

**Comment by xmonader** [comment]
Will put it in new, to be picked up if we could make it with the planned items we already have.
