### ISSUE TITLE
TF GRID DEMO: failed to reach peertube deployment

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#842]
created a peertube deployment, all went well until I tried to reach it. 

This should be the url: https://dylanv-peertube-test.tfgw-testnet-01.3x0.me/

Deployment information:
```
{
   "-""wids":[
      473024,
      473027,
      473025,
      473028
   ],
   "Name":"test",
   "Domain":"dylanv-peertube-test.tfgw-testnet-01.3x0.me",
   "IPv4 Address":"10.100.2.3",
   "IPv6 Address":"fd57:6a6b:7748:2::3",
   "Node":"2m3nHPSAMyZFSeg5HPozic2NGBMtrXrBkhtNcVmd5Ss6",
   "Farm":"freefarm",
   "Pool":897,
   "Network":"dylanv.3bot_apps",
   "CPU":1,
   "Memory":1024,
   "RootFS Type":"SSD",
   "RootFS Size":512
}
```

**Comment by LeeSmet** [comment]
actually this works for me, see screenshot below

using firefox browser

![image](https://user-images.githubusercontent.com/22023708/91861116-be352b00-ec6c-11ea-9776-92227a82f127.png)

**Comment by DylanVerstraete** [comment]
Reachable from my phone as well. But not on the machine where I deployed this peertube..

**Comment by LeeSmet** [comment]
Indeed, on a windows 10 google chrome its not reachable either

**Comment by xmonader** [comment]
Investigation has been done here https://github.com/threefoldtech/js-sdk/issues/960#issuecomment-688440218 mainly Accept-Language header, I'll move both issues out of the projects and see if can report that upstream
