### ISSUE TITLE
TF Grid Demo: Wiki flow , wiki setup question?

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#844]
what do we mean by title, repository url and branch?

should explain to users 
<img width="608" alt="Screenshot 2020-09-01 at 14 44 38" src="https://user-images.githubusercontent.com/43240801/91853830-1109e500-ec63-11ea-9878-9ff44fefd973.png">

what title? project title? or the wiki title itself?
where would it be deployed?  
where can i access my repo / who is the host? github?
why do i need to name a branch? what branch?
why cant i choose a domain here too?

we should give more explanation to users what this is about

**Comment by xmonader** [comment]
all of the solution info needs to be explained in here https://github.com/threefoldfoundation/info_gridmanual/issues/215

**Comment by dmahmouali** [comment]
resolved
![image](https://user-images.githubusercontent.com/36021484/95186889-ca139000-07ca-11eb-9d96-5bf04a38916a.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 01ac08bc8051698b0478d22baa876fd2d4a4bef9, **Branhc**  development

![ff](https://user-images.githubusercontent.com/21218053/96591687-cfeb9400-12e7-11eb-9b69-0394c6799dcf.png)
