### ISSUE TITLE
TF GRID DEMO: failed to initialize cryptpad

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#849]
Message: 

```
Failed to initialize Mattermost, please contact support with this information: Node:3dAnxcykEDgKVQdTRKmktggL2MZbm3CPSdS9Tdoy4HAF, Ip Address: 10.100.3.2, Reservation Id: 473143, Pool Id : 917, Domain : dylanv-cryptpad-cryptpad.tfgw-testnet-01.ava.tf . Please use the refresh button on the upper right to restart the chatflow
```

Also it says it failed to initialize mattermost but I am trying to deploy cryptpad..
![Screenshot from 2020-09-01 15-27-54](https://user-images.githubusercontent.com/17138347/91857153-d0f93100-ec67-11ea-8b42-540614acbad5.png)

**Comment by dmahmouali** [comment]
Resolved from the SDK side by applying a dry run and blocking nodes features.
And for the naming confuse, Now it's working on base code and no confusing anymore.

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** a1b57396c977ac25d566d340405a9f9a177ddeb8, **Branch**  development

![ff](https://user-images.githubusercontent.com/21218053/96372874-59288c80-1169-11eb-8dfe-4a48f207e0ec.png)
