### ISSUE TITLE
add entry point around starting 3bot

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#85]
should be as easy as `3bot start`

**Comment by waleedhammam** [comment]
Progress

- Added https://github.com/threefoldtech/js-sdk/commits/development_entry v1 has `threebot start` and `threebot stop`
- Basic identity checks

TODO:

- Add more identity checks (port from jsx sdk)

**Comment by waleedhammam** [comment]
Add more identity checks -> added

**Comment by hossnys** [comment]
verified
