### ISSUE TITLE
updates for 3bot solution

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#854]
update:
- [x] autobackup should be enabled
- [x] less expiration time for 3bot (14 days)
- [x] less resources {"cru": 1, "mru": 1, "sru": 2}

**Comment by Dina-Abd-Elrahman** [comment]
![ff](https://user-images.githubusercontent.com/21218053/92464398-5d0dda00-f1cd-11ea-8c57-dc16fda2c60f.png)

**Comment by Dina-Abd-Elrahman** [comment]
![ff](https://user-images.githubusercontent.com/21218053/92464887-166caf80-f1ce-11ea-92b9-daf892660de5.png)

**Comment by Dina-Abd-Elrahman** [comment]
![ff](https://user-images.githubusercontent.com/21218053/92465032-5895f100-f1ce-11ea-8841-3805affe6f42.png)
