### ISSUE TITLE
allow reloading a package from the UI

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#857]
Allow reloading a package (don't lose the changes)

**Comment by BolaNasr** [comment]
Approach 1 : Add package again should be reload automatically .

Approach 2 : Delete package and then add again.

**Comment by BolaNasr** [comment]
PR: https://github.com/threefoldtech/js-sdk/pull/890

Blocked on : https://github.com/threefoldtech/js-sdk/issues/888

**Comment by abom** [comment]
Moved #888 to alpha4, reloading chats is enough for now.
