### ISSUE TITLE
as a 3bot owner I want to see when my 3bot solution expires

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#858]
as a 3bot user I want to see when my 3bot solution expires

**Comment by ranatrk** [comment]
![Screenshot from 2020-09-01 19-08-38](https://user-images.githubusercontent.com/17128393/91886557-cb144780-ec89-11ea-8ba6-8be91acc6272.png)

red color if expiration is in 2 days:
![Screenshot from 2020-09-01 19-27-43](https://user-images.githubusercontent.com/17128393/91886559-cbacde00-ec89-11ea-89a0-04af867ff2eb.png)

**Comment by hossnys** [comment]
when deploying in https://deploy3bot2.grid.tf , it's now showing expiration date for all 3bot instances and with red color for less that two days expire date.

![Screenshot from 2020-09-02 00-00-05](https://user-images.githubusercontent.com/26298009/91910260-f8bfb780-ecae-11ea-835c-1a9972501c02.png)
