### ISSUE TITLE
Deploy network: connect over ipv6 results in broken config

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/js-sdk#859]
Go through the `network` chatflow

It will ask if you want to connect over ipv4 or ipv6, choose ipv6:

![image](https://user-images.githubusercontent.com/22023708/91866701-15d69500-ec73-11ea-8f6f-6745be9ba7ac.png)

On the next screen, select choose IP range for me

after the network is deployed, the following config is generated:

![image](https://user-images.githubusercontent.com/22023708/91867124-8f6e8300-ec73-11ea-9102-a3394c2eac9b.png)

instead of a valid ipv6, the access point ip is just a bracketed (`[ ]`) ipv4, which is invalid

NOTE: this result does not seem to happen all the time. Out of 4 attempts to generate a network, 2 of them led to this corrupt config, while the other 2 did generate a correct ipv6 endpoint

**Comment by Pishoy** [comment]
verified and attached ubuntu container to network ipv6 and works 
```
commit 6caa3885a87d722a3c221da60dea445ef06a3ed1 (HEAD -> development, origin/development, origin/HEAD)

```
