### ISSUE TITLE
Capacity pool reservation/extension UI/UX

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/js-sdk#860]
Currently when a user reserves a new or extends an existing capacity pool, he gets a screen like this:

![image](https://user-images.githubusercontent.com/22023708/91875506-d6f90d00-ec7b-11ea-80fc-76e06fbf3280.png)

It is not immediately clear what the units are for the values in the CU or SU field. Since there is mention of CU and SU usage of workloads, a user might (mistakenly) think that he needs to enter the CU and SU values his workload will consume here, which is wrong.

In reality the low level reservation works with cu seconds and su seconds, i.e. an amount of seconds for which 1CU/SU can be deployed with the pool. The problem is that for an end user, who is likely now familiar with the intimate details of how this works under the hood, this quickly results in large and unnatural numbers being required. For instance, deploying a workload worth 1 CU or 1 SU for an entire day already consumed 86400 CUs or SUs. 

A solution to this would be to add a "duration" field where a user can specify how long the workload should live, in a sufficiently large period such as day or even week or month. Then in the existing CU and SU field the user can just enter the estimated values of the CU and SU his workload will consume. Under the hood the chatflow can simply fill in the right reservation values using multiplication.

Example:

- CU: 20
- SU: 10
- Days: 30

This would lead to the creation of a reservation with 20 * (60 * 60 * 24 * 30) CUs and 10 * (60 * 60 * 24 * 30) SUs

To make this even more flexible, the time field could be accompanied by a dropdown where the user himself can choose if he wants to reserve for x amount of Days or weeks or months (instead of having to fill in everything as X amount of days)

**Comment by sasha-astiadi** [comment]
also, please rewrite the page's description as mentioned here 
https://github.com/threefoldtech/js-sdk/issues/893

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-09-06 14-16-26](https://user-images.githubusercontent.com/26298009/92325694-e944c380-f04c-11ea-8502-80bbe72fc36a.png)
