### ISSUE TITLE
Ubuntu solution deply: units for root filesystem are unclear

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/js-sdk#865]
When asked about the container size, there is a field for root filesystem size. It is not specified if this is KB, MB, or GB ..

![image](https://user-images.githubusercontent.com/22023708/91881542-f004bc80-ec81-11ea-9116-d0d360f5f56a.png)

**Comment by xmonader** [comment]
should be fixed by 5859c17c85b9958d160fc16b0193480e6de355d2

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-09-01 20-37-40](https://user-images.githubusercontent.com/26298009/91892189-817c2a80-ec92-11ea-9411-f53a72811933.png)
