### ISSUE TITLE
cannot start 3bot server 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/js-sdk#87]
## steps to reproduce
j.servers.threebot.get("default") 

![error](https://user-images.githubusercontent.com/21218053/85420242-3c8d9680-b573-11ea-9fa2-8c56273839be.jpg)
![error1](https://user-images.githubusercontent.com/21218053/85420258-40b9b400-b573-11ea-8527-73e1c582431c.jpg)

**Comment by hossnys** [comment]
i just got the same error when starting threebot server after following the docs here https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/quick_start.md 
and here 
https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/threebot.md#start-threebot-server

**Comment by waleedhammam** [comment]
I think it's the nsloader @abom  ?

**Comment by xmonader** [comment]
should be fixed by forcing old loader #97

**Comment by hossnys** [comment]
verified 
![Screenshot from 2020-06-25 11-16-28](https://user-images.githubusercontent.com/26298009/85691553-e59fd280-b6d4-11ea-8897-180058bebc16.png)
