### ISSUE TITLE
As a user of the marketplace I want to have the app linked to my owned domain (weight=7)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#872]
Right now, the grid infra controls the domains on demo.grid.tf and demo2.grid.tf, I'd like to be able to have these apps on $app.$mydomain or on $mydomain directly

**Comment by rkhamis** [comment]
what this will mean:
 - changes to all chatflows
 - requires more experienced end-users (chat flow to create a domain)
 - use name.com API to create new domains
 - user can choose to use a domain they already own
