### ISSUE TITLE
Workload details: change "epoch" to "creation date"

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/js-sdk#876]
When looking at a full workload detail, there is a field called "epoch", indicating when the workload was created. Although this is the term used in the api, this is rather technical and might not be easily understood by average end users. A better way of wording this would be something along the lines of "Creation Date" or similar

![image](https://user-images.githubusercontent.com/22023708/91958109-32bca800-ed07-11ea-94e4-9c692f39b5c1.png)

**Comment by ranatrk** [comment]
changed to Creation Date
![Screenshot from 2020-09-02 12-07-04](https://user-images.githubusercontent.com/17128393/91968374-dd879300-ed14-11ea-9042-5bc6dd115c2e.png)

**Comment by hossnys** [comment]
verified , creation date now shown with human readable date .

![Screenshot from 2020-09-02 13-50-18](https://user-images.githubusercontent.com/26298009/91977335-d1a2cd80-ed22-11ea-819e-c3fec9456b61.png)
