### ISSUE TITLE
Dashboard: inaccurate memory usage chart

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#878]
![Screenshot from 2020-09-02 10-55-58](https://user-images.githubusercontent.com/17138347/91961070-fbe89100-ed0a-11ea-830d-68ed8bbaee38.png)

It says 43% is used but it should be 12,5%

**Comment by AhmedHanafy725** [comment]
**Verified**
**Branch:** development_vdc
**Commit:** da50148a76d6e9a94699c00311e004cf50c1d878


![image](https://user-images.githubusercontent.com/41957921/107517277-3c034800-6bb6-11eb-84f7-f9d38ed2e93a.png)


![image](https://user-images.githubusercontent.com/41957921/107517613-a3b99300-6bb6-11eb-81db-6ff5fa7f5a10.png)
