### ISSUE TITLE
3bot deployer: 3bot solution details has weird "class" field

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/js-sdk#879]
At the bottom of the solution details pop up, there is a `class red--text` field, which seems like a misplaced css class

![image](https://user-images.githubusercontent.com/22023708/91961127-0c990700-ed0b-11ea-88ba-c69cdfe49a9b.png)

**Comment by ranatrk** [comment]
removed from view:
![Screenshot from 2020-09-02 10-33-59](https://user-images.githubusercontent.com/17128393/91958594-d73eea00-ed07-11ea-99b6-13e7e00f4af1.png)

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-09-02 13-58-09](https://user-images.githubusercontent.com/26298009/91978068-d0be6b80-ed23-11ea-8551-e288ad9d5c7b.png)
