### ISSUE TITLE
3bot deployer: extend threebot UX

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/js-sdk#880]
After having a 3bot deployed, I wanted to extend it in the deployer. As a relatively new user on this page: on opening the page, the first thing I noticed was the expiration date, and I looked for an "extend" button there. After that, I looked at the end of the line to see some action buttons. One of the is the ability to delete the threebot. Yet not extend button is present here either. I only kept looking and found the extend button at the top right of the page, because I was specifically told yesterday that it was possible to extend a 3bot.

Perhaps it would be good to also add an "extend this 3bot" button next to the expiration or with the other action buttons, which starts the chatflow and already pre selects the appropriate 3bot, as this would (imo) lead to a more intuitive UX for this feature. If "deleting" is an action, then extending it should also be

![image](https://user-images.githubusercontent.com/22023708/91962890-70243400-ed0d-11ea-8cf4-5c84368c3e4a.png)

**Comment by rkhamis** [comment]
new flow suggested in #783 covers this
