### ISSUE TITLE
Dashboard: add a terminal window pane for advanced users

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#881]
Right now if you want to access the shell and play around with `jsng` you have to go to Codeserver -> menu button -> new terminal. This is quite hard to find. I suggest to make a seperate tab in the left navigation bar that points to a terminal window. 

In this window `jsng` is started automatically and the user can play around and this way the user can also deploy primitives like zdb's / volumes / ...

This is very usefull if you are running a hosted threebot and don't have access to `poetry`

**Comment by xmonader** [comment]
Can be resolved by running a core-X process along with the 3bot, needs to be rethought
