### ISSUE TITLE
Redirect after creating a pool is broken

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#884]
### Version information

* OS: docker Ubuntu 20.04
* Branch: development
* commit: cb5480fadfc3832dacbb618b14116d58c2796d75
* Browser: Version 84.0.4147.125 (Official Build) (64-bit)
* explorer: testnet

### Steps to reproduce
1- Create a pool from admin dashboard.
2- After it finishes.
![image](https://user-images.githubusercontent.com/41957921/91971337-52f56280-ed19-11ea-8846-0efb3cf72787.png)

3- Click on next button
![image](https://user-images.githubusercontent.com/41957921/91971443-7d472000-ed19-11ea-9c13-e967ee3bfca5.png)

### Expected Result
Redirects to the same chatflow to create another pool, or go to pools table.

### Actual Result 
Redirects to no where

**Comment by hossnys** [comment]
This is reported before at #868 so closing the other one .

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-09-06 13-48-34](https://user-images.githubusercontent.com/26298009/92324990-332aab00-f047-11ea-96ad-17d8dc9aa741.png)

![Screenshot from 2020-09-06 13-48-43](https://user-images.githubusercontent.com/26298009/92324991-33c34180-f047-11ea-8ed8-700d10351cdb.png)
