### ISSUE TITLE
3BOT ADMIN : POOL - back button should navigate to previous step, not. starting page. 

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#892]
This was found on capacity pool wizard, but changes should apply on all wizards.

when 'back button' is pressed, should lead to the 1 previous screen, not start screen.
example:
When i click back button on capacity farm selection instruction, it navigated me back to start page of the capacity pool (selecting name)- this is not what i want.  i should be navigated to the previous page instead.

<img width="871" alt="Screenshot 2020-09-02 at 13 32 52" src="https://user-images.githubusercontent.com/43240801/91976218-f26a2380-ed20-11ea-8ccd-a2a52e418f36.png">

**Comment by rkhamis** [comment]
This is the intended behavior. it goes back to the start of the step we defined. in later steps, you'll find you go back to a certain screen

**Comment by sasha-astiadi** [comment]
to just make it like this is wrong, because its not user friendly. why would i go back to start page as a user. you can keep this open for later , but do not close it.
