### ISSUE TITLE
3bot admin: cant reaccess my admin panel after timed out

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#894]
<img width="1004" alt="Screenshot 2020-09-02 at 13 56 40" src="https://user-images.githubusercontent.com/43240801/91978459-6ce87280-ed24-11ea-8bea-1d9c30f5df0d.png">

**Comment by xmonader** [comment]
Looks like you didn't choose to let it live long enough (please choose a longer expiration time)
