### ISSUE TITLE
final_step parameter wasn't passed in multiple chatflows

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/js-sdk#896]
### Description

The solution chatflow component uses the final_step parameter to change the next button to finish. But this parameter wasn't passed in pools, kubernetes, minio, and monitoring solutions

### Steps to reproduce

Navigate to the last step of the chatflow of Pools. The next button is not changed to finish.

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-09-06 13-48-34](https://user-images.githubusercontent.com/26298009/92325142-83563d00-f048-11ea-88ee-0671402441c0.png)
