### ISSUE TITLE
Dashboard: rework design of index file

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#900]
Personally this does not look professional at all. It looks like boilerplate vuejs code / styling. 

Can we drop the text above the button and make the button another color with maybe a login icon inside?
Look at something in here: https://dribbble.com/search/shots/popular/web-design?q=call%20to%20action

![Screenshot from 2020-09-02 14-34-29](https://user-images.githubusercontent.com/17138347/91981950-d5861e00-ed29-11ea-877b-7ef3c1d72193.png)

**Comment by sasha-astiadi** [comment]
Welcome to 3Bot 
Click the button below to access your 3Bot Admin Panel via 3Bot Connect Authorization

Log in via 3Bot Connect

**Comment by sasha-astiadi** [comment]
this page should be deleted. instead, change the text of the existing authorization page so there should be no duplication
https://github.com/threefoldtech/js-sdk/issues/903

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/92027567-05054c80-ed63-11ea-8d51-08a56fb5dad7.png)

that's my temporary fix (i'll keep that issue in the backlog to improve) 
fedc359748ba20e2a359c7dc11f1da5e9c870176

**Comment by xmonader** [comment]
> this page should be deleted. instead, change the text of the existing authorization page so there should be no duplication
> #903

this page has nothing to do with "login page", login page is a generic page used for ALL packages requiring login, admin panel happens to be one of these package.

**Comment by DylanVerstraete** [comment]
@xmonader looks better already!
