### ISSUE TITLE
Dashboard: make threebot login page fullscreen

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#901]
It's 1/3th blank at the bottom..

![Screenshot from 2020-09-02 14-49-53](https://user-images.githubusercontent.com/17138347/91983267-b9837c00-ed2b-11ea-8977-f34bde30a71f.png)

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/106923747-11794100-6717-11eb-8bfb-02d55f901feb.png)

verifiedd
