### ISSUE TITLE
Dashboard: dark mode colors don't match

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#902]
The threebot green with the dark blue and the light green from the healthchecks really don't fit well together. 
Also the grey schema and darker colors are way to much different in contrast..

Read: https://uxplanet.org/8-tips-for-dark-theme-design-8dfc2f8f7ab6 for more info

![Screenshot from 2020-09-02 14-53-48](https://user-images.githubusercontent.com/17138347/91983587-30207980-ed2c-11ea-82a4-d97fb09baabe.png)

**Comment by DylanVerstraete** [comment]
Suggestions:

- Health checks buttons color in the green that is on our website:
![Screenshot from 2020-09-02 15-05-39](https://user-images.githubusercontent.com/17138347/91987104-e33da280-ed2d-11ea-8502-12031d0fc0b6.png)
- Left green threebot logo background in the green that is on our website as well.
- Remove line between `Dashboard` menu item and green Threebot logo

**Comment by DylanVerstraete** [comment]
@VonSub your input is welcome here!

**Comment by xmonader** [comment]
@ehab-hassan @samaradel  please check too

**Comment by DylanVerstraete** [comment]
Maybe we can use sort of gradient in the buttons or dashboard cards. An example: https://dribbble.com/shots/3177027-DI-FM

**Comment by waleedhammam** [comment]
Done on latest development
![Screenshot from 2020-10-29 08-28-00](https://user-images.githubusercontent.com/10658229/97533320-ace47280-19c0-11eb-8b77-beb922d986fe.png)

**Comment by hossnys** [comment]
verified on development branch 

![Screenshot from 2020-11-03 13-41-02](https://user-images.githubusercontent.com/26298009/97980543-9d5a9480-1dd9-11eb-8b78-9457c7132b26.png)
