### ISSUE TITLE
Change the text of 3bot authorization

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#903]
<img width="1096" alt="Screenshot 2020-09-02 at 15 41 14" src="https://user-images.githubusercontent.com/43240801/91991612-66adc280-ed33-11ea-86ac-402d55cea09e.png">

into:
Welcome to 3Bot
Use your 3Bot Connect App on your mobile phone to access your 3Bot Admin Panel

Log in via 3Bot Connect

**Comment by xmonader** [comment]
This is not quite accurate, this is the "login page with 3Bot connect" has nothing to do with Admin package. Admin is one of the packages that is protected behind that login page, you can have "multiple" packages that are "protected" behind a 3Bot login (including the admin panel)

**Comment by xmonader** [comment]
changes in 36674d58270d8ec24941c8b357a2165418fd120c

**Comment by sasha-astiadi** [comment]
OK if thats what it is, then lets say i , as a user, just deployed a 3bot.
the deployer gave me a bunch of long words as my domain , like

http://sashaastiadi-sasha.tfgw-testnet-01.gateway.tf/

and when i click this link... i dont see anything that says '3bot admin' at all... or a dashboard. all i see is this screen.

i see a protected web page sentence

i see log in via 3bot connect

im not informed that i need to check the app on my mobile phone.

where is the 3bot?
where is the home page?

at least then there should be a page that says 

Welcome to 3Bot
Use your 3Bot Connect App on your mobile phone to access your 3Bot Admin Panel

Log in via 3Bot Connect

----


its like you want to enter a house, you have the map address, you have the key. you arrived in front of the house based on the map, but youre not sure if its the right house because the house doesnt have the address or the house number in front of it... do you just come into the house and try to insert a key....

**Comment by xmonader** [comment]
We aren't on the same page. if you go to your 3Bot domain you will see what is defined here 
https://github.com/threefoldtech/js-sdk/issues/900#issuecomment-685949187

![image](https://user-images.githubusercontent.com/64129/92039140-db552100-ed74-11ea-9f88-cf6247c3ba76.png)


*any* package running on 3Bot that requires *authentication* (including the admin) when accessed will show this page is protected page.

**Comment by hossnys** [comment]
verified

![Screenshot from 2020-09-03 17-59-53](https://user-images.githubusercontent.com/26298009/92324781-10979280-f045-11ea-998b-556d46b9ef3f.png)
