### ISSUE TITLE
UI: Capacity and Farm Management have the same icon

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/js-sdk#905]
![image](https://user-images.githubusercontent.com/10920323/91992364-577b4480-ed34-11ea-8a84-b08ea824039f.png)

> pst: I am sorry

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 472d6c016a174dd5c94a2c3a2a007074a0488845, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/95988745-a3d49c80-0e29-11eb-9793-740d443489a1.png)
