### ISSUE TITLE
3BOT ADMIN: POOL - screen #5 Feedback

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#906]
<img width="911" alt="Screenshot 2020-09-02 at 16 49 30" src="https://user-images.githubusercontent.com/43240801/91999207-6d8d0300-ed3c-11ea-96bd-2b2010f99ce2.png">

New Title: Capacity Pool

Instruction title:
Make a Payment

Please complete your capacity reservation by making a payment as instructed below: -> please move to another issue if you really want this

**Destination Wallet Address**: GA35UXDDRMAAQZK3CPV5CFFWFMLEPMVJGI7YMM6YCG5L3QPCPZPFL7EV
**Currency**: FreeTFT
**Total Amount**: **0.0001297 FreeTFT**
**Memo Text (Reservation ID)**: p-1048

Important: Inserting the memo-text is an important way to identify a transaction recipient beyond a wallet address. Failure to do so will result in a failed payment. Please also keep in mind that an additional Transaction fee of 0.1 FreeTFT will automatically occurs per transaction.

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/92030913-02592600-ed68-11ea-9657-64243c060c0d.png)


changes implemented in ad0109edbea4abe4fc80875b7d8794168f39c8d4

 
> Please complete your capacity reservation by making a payment as instructed below:
That's too specific payment message, that payment message used in all of chatflows, but the rest sounds good for my side. if you still want that you can open a separate issue for it and we revisit/reconsider. thanks.

**Comment by sasha-astiadi** [comment]
or can be:

Make a Payment

Please use your wallet to scan the payment's QR Code, or send it to the address below:

Destination Wallet Address: GA35UXDDRMAAQZK3CPV5CFFWFMLEPMVJGI7YMM6YCG5L3QPCPZPFL7EV
Currency: FreeTFT
Total Amount: 0.0001297 FreeTFT
Memo Text (Reservation ID): p-1048
Additional Transaction fee of 0.1 FreeTFT (automatic)

Inserting the memo-text is Mandatory. Failure to do so will result in a failed payment.

**Comment by hossnys** [comment]
verified

![Screenshot from 2020-09-06 13-48-05](https://user-images.githubusercontent.com/26298009/92325281-87368f00-f049-11ea-8221-c74464017d12.png)
