### ISSUE TITLE
inconsistent listing of capacity pools while extending 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#911]
![image](https://user-images.githubusercontent.com/64129/92030419-4bf54100-ed67-11ea-9e8d-70f58457d115.png)

Why is the first item format is different?

**Comment by AhmedSa-mir** [comment]
![image](https://user-images.githubusercontent.com/18093386/92108349-83a3cd80-ede7-11ea-9020-e659f94147e4.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** fe6a5b98fcfcb3713fe5aca83b1631be05fe9c83 , **Branch**  development

![ff](https://user-images.githubusercontent.com/21218053/92327172-18acfd80-f058-11ea-9d03-db2abd0aa46b.png)
