### ISSUE TITLE
gitea chatflow isn't consistent with the rest of the apps

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#912]
for instance mattermost shows for the success message 
![image](https://user-images.githubusercontent.com/64129/92044147-df397100-ed7d-11ea-898e-ea06360b509c.png)
and peertube
![image](https://user-images.githubusercontent.com/64129/92044410-7a324b00-ed7e-11ea-8136-50e9885d0178.png)

but gitea shows
![image](https://user-images.githubusercontent.com/64129/92044182-f5473180-ed7d-11ea-93b3-e9de7d780dee.png)

and what's up with the that password? how is that generated? why can't the user specify it themselves? and that's for postgresql correct? they user is required to use (dbname, dbuser, db password) are the default correct?

note: i'm ok with admin url, but let's remove that container ip thing

**Comment by Pishoy** [comment]
verifed + gitea is not shown in the frontend
![image](https://user-images.githubusercontent.com/21987477/92114590-61af4880-edf1-11ea-8a3a-471eaefc4588.png)
 - sdk version 
```
# git log -1
commit 1ad73fb55d6fd551b675f1998aee1efc30778b75 (HEAD -> development, origin/development, origin/HEAD)
Merge: c2dba99 e873a6d
Author: xmonader <xmonader@gmail.com>
Date:   Thu Sep 3 13:52:03 2020 +0200

    Merge pull request #944 from threefoldtech/development_missing_attr
    
    fix missing attr
```
