### ISSUE TITLE
'Pool' object has no attribute 'unit_diff'

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#918]
'Pool' object has no attribute 'unit_diff'

when deploying a new 3Bot 
![image](https://user-images.githubusercontent.com/64129/92087984-8e049e00-edcc-11ea-8937-04829b82e272.png)
the alert is 

![image](https://user-images.githubusercontent.com/64129/92088024-9bba2380-edcc-11ea-8ce6-4df625adb98e.png)

**Comment by Pishoy** [comment]
verfied and 3bot works properly 

- sdk version 
```
root@tfwallet-prod:/opt/js-sdk# git log -1
commit 881f1904e00ba187ecf254cd8ba4857949767d38 (HEAD -> development, origin/development, origin/HEAD)
Author: xmonader <xmonader@gmail.com>
Date:   Sun Sep 6 23:59:38 2020 +0200

    regenerate docs

```
