### ISSUE TITLE
Developer options in the setting of the admin dashboard keeps loading forever

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#921]
### Version information

* OS: docker Ubuntu 20.04
* Branch: development
* commit: cb5480fadfc3832dacbb618b14116d58c2796d75
* Browser: Version 84.0.4147.125 (Official Build) (64-bit)
* explorer: testnet

### Steps to reproduce
1- After new installation, open the setting page of admin dashboard.
2- Developer options is keep loading forever.

Also it can be reproduced, by removing TEST_CERT and OVER_PROVISION from the config in ~/.config/jumpscale/config.toml

![image](https://user-images.githubusercontent.com/41957921/92091102-8e069d00-edd0-11ea-826a-0a5562617a1a.png)

**Comment by hossnys** [comment]
verified 
1- removed TEST_CERT and OVER_PROVISION from  ```~/.config/jumpscale/config.toml```.
2- checked the setting page for developer options and it loaded successfully . 

![Screenshot from 2020-09-06 14-41-17](https://user-images.githubusercontent.com/26298009/92325917-7ccac400-f04e-11ea-82b2-98cda62635c4.png)
