### ISSUE TITLE
typo: settings page title is "Setting"

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#923]
![image](https://user-images.githubusercontent.com/64129/92092227-1a658f80-edd2-11ea-9df9-54346993f98b.png)

should be Settings

**Comment by xmonader** [comment]
Fixed in a04b996d889ce81c72680b11aac46fc678e9078d

**Comment by Pishoy** [comment]
verified 
![image](https://user-images.githubusercontent.com/21987477/92116248-e1d6ad80-edf3-11ea-912c-ef8cbf82f90a.png)
