### ISSUE TITLE
capacity pools page: The head of the table should be aligned in the center of the cell

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#924]
### Version information

* OS: docker Ubuntu 20.04
* Branch: development
* commit: cb5480fadfc3832dacbb618b14116d58c2796d75
* Browser: Version 84.0.4147.125 (Official Build) (64-bit)
* explorer: testnet

### Steps to reproduce
1- Go to capacity pools in admin dashboard.
2- Click on the `show hidden pools` button

The head of the table should be aligned in the center of the cell.

![image](https://user-images.githubusercontent.com/41957921/92091851-9ca18400-edd1-11ea-8286-55fad1a5940a.png)

**Comment by xmonader** [comment]
should be resolved in #938

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-09-06 14-32-21](https://user-images.githubusercontent.com/26298009/92325757-58221c80-f04d-11ea-9481-ae14e41be800.png)
