### ISSUE TITLE
Threebot deployer: extending threebot with specific date resolves in a more future date

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#926]
So I am extending my hosted threebot

![Screenshot from 2020-09-03 10-54-33](https://user-images.githubusercontent.com/17138347/92094150-6ca7b000-edd4-11ea-8310-9d4ae52c61a8.png)
![Screenshot from 2020-09-03 10-58-13](https://user-images.githubusercontent.com/17138347/92094155-6d404680-edd4-11ea-9af5-7cc1ebbafc86.png)

I picked date: 5/2/2021 and it got extended to: 14/3/2021

Can we also switch the date notations in both screen to DD/MM/YYYY ?  Right now it's very confusing

**Comment by waleedhammam** [comment]
fixed now in https://github.com/threefoldtech/js-sdk/issues/1198
