### ISSUE TITLE
Dashboard pools: wizard "go back" is not ordered correctly

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#928]
This is the step where you fill in the units
![Screenshot from 2020-09-03 11-16-02](https://user-images.githubusercontent.com/17138347/92096279-fc4e5e00-edd6-11ea-9e42-b7eba045ae58.png)

When you click next you go to:
![Screenshot from 2020-09-03 11-16-10](https://user-images.githubusercontent.com/17138347/92096316-083a2000-edd7-11ea-9424-fb5ad950179a.png)

When you now click back you go 2 steps back!
![Screenshot from 2020-09-03 11-16-17](https://user-images.githubusercontent.com/17138347/92096371-15efa580-edd7-11ea-88d0-53302e9fcc49.png)

**Comment by xmonader** [comment]
I understand the confusion I tried to technically clear it here https://github.com/threefoldtech/js-sdk/issues/892#issuecomment-685977821

Right now, the sals to simplify that chatflow development some of them ask multiple questions could be object to change/rework in the future, but redoing the SALs would be too much work for us atm

**Comment by DylanVerstraete** [comment]
Okay sounds reasonable :)

**Comment by xmonader** [comment]
will close this one to resolve in another issue (redesign of capacity pool workflow)
