### ISSUE TITLE
Error raised when I tried to deploy 3Bot on threebot_deploy pacakge

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/js-sdk#930]
### Description

I got this error:

![image](https://user-images.githubusercontent.com/13040543/92097469-6582a100-edd8-11ea-9fff-0b6ce21e77db.png)
![image](https://user-images.githubusercontent.com/13040543/92097483-6a475500-edd8-11ea-8901-0a1d97946661.png)

### Steps to reproduce

Go through the 3bot chatflow.
Seems to happen when the user has a pool that requires an extension to deploy the solution.

**Comment by xmonader** [comment]
@m-motawea please link the pr the fixed this

**Comment by Pishoy** [comment]
verified as below steps 
```
1. Install threebot deploy
2. Create a threebot deploy instance with some expiration date
3. Delete it.
4. Create another with expiration date after the first one.
5. Make sure in the chatflow it says that it found an old pool that needs extension.
```

![image](https://user-images.githubusercontent.com/21987477/92126467-819a3880-ee00-11ea-8a8d-46c27acf1076.png)
