### ISSUE TITLE
Extending my threebot to a date prior to its expiration asks me to pay extra money.

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/js-sdk#932]
### Description

Maybe add a validation that prevents the user to do so.

**Comment by ranatrk** [comment]
When a pool has nothing consuming it, the empty_at is a max number, so if it its tht max number then the min and default are 1 hour from now. If not then they are the current pool empty_at value

![Screenshot from 2020-09-03 13-59-40](https://user-images.githubusercontent.com/17128393/92112223-c23c8680-eded-11ea-80f5-5ac1ca1cdc6b.png)

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-09-06 14-46-06](https://user-images.githubusercontent.com/26298009/92326006-388bf380-f04f-11ea-9465-bbf9773203f3.png)

![Screenshot from 2020-09-06 14-45-41](https://user-images.githubusercontent.com/26298009/92326004-375ac680-f04f-11ea-8bc7-1741975eabd8.png)
