### ISSUE TITLE
Cannot start threebot normally in new installation. 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/js-sdk#934]
### Version information

* OS:  Ubuntu 20.04, 18.04
* Branch: development
* commit: 270a4e0c8e0821ad6918273f0fd4dc4ea0f9f6ef

### Steps to reproduce:

1- Install jsng following those steps using normal user not root user. https://threefoldtech.github.io/js-sdk/wiki/#/./installation

2- Trying to start threebot server `threebot start --local`, in the first time it works fine, but I got warning at the beginning of the message like this :

![ff](https://user-images.githubusercontent.com/21218053/92102347-c44b1900-edde-11ea-8939-d368f3fd472e.jpg)

3- When I stop threebot `threebot stop`  and try to start it again, I got this error. 

![ff](https://user-images.githubusercontent.com/21218053/92102719-3de30700-eddf-11ea-8898-e1d832a1136a.png)

**Comment by xmonader** [comment]
this means nginx is running on your machine, can you check the tmux if you have nginx running and kill it?

**Comment by Dina-Abd-Elrahman** [comment]
@xmonader even I killed the nginx `pkill nginx` I got the same error, and I check usgin `ps aux | grep nginx`

**Comment by OmarElawady** [comment]
I got a similar error on a new docker ubuntu:20.04 container. 
Reproduction:
1. Create a new user. install sudo. Add the user to the sudoers.
2. switch to the created user.
3. install as in the js-ng wiki.
4. run on one tab `threebot start --local`
5. run on another tab (with the newly created user) `threebot stop` then `threebot start --local`.
6. An error appears that gedis:16000 is reserved and the initialization fails.

`ps aux` shows that the threebot process from the first tab is still running. `ss` shows that this process is using the aforementioned port.

**Comment by OmarElawady** [comment]
It works also with anything (not necessarily a clean installation) just do 4 and 5 and it'll give the error.

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** f7492f7ffaf2dad854e3d1014127d588078cafce , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/92602530-8a7e8480-f2ae-11ea-919a-9e14ecd020e0.png)
