### ISSUE TITLE
can rename pools to invalid identifiers

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-sdk#935]
# Description

pool names should be a valid identifier. but it can be edited to anything

- there is no check done on the actor side for this. it should be added to the actor and probably ui as well

![image](https://user-images.githubusercontent.com/32568986/92103850-d037da80-ede0-11ea-8f55-17dfd7c12227.png)

**Comment by AhmedHanafy725** [comment]
**Verified**
**Branch:** development_vdc
**Commit:** da50148a76d6e9a94699c00311e004cf50c1d878

![image](https://user-images.githubusercontent.com/41957921/107523421-5db3fd80-6bbd-11eb-9baa-4c40ea5ecb7e.png)
