### ISSUE TITLE
As a 3Bot user I expect to pay only for the extension period not including the period I already paid for.

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/js-sdk#936]
### Description

Extending a 3Bot instance already deployed until _9/5/2020, 1:17:45 AM_ to _9/5/2020, 1:18:00 AM_ requests me to pay  2.5746967 TFT. Creating a new 3Bot instance that expires at  _9/5/2020, 1:18:00 AM_ requests me to pay  2.5754377 TFT

**Comment by mhost39** [comment]
branch: development
commit: 7e5e699c6b4701ab37b13c63d03d5accbc2bac94
