### ISSUE TITLE
Missing options in wallet manager in admin panel

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/js-sdk#94]
- When creating a wallet from the admin panel, the network type is always TEST, it should either be chosen by the user or set according to the current identity's explorer instance (**Update**: Add option to create new identity/switch between identities)
- Can't add trust lines to existing wallets from the admin panel

**Comment by ranatrk** [comment]
The problem is when switching the explorer to main from the admin, the identity used is not switched to the identity used in explorer, and the default explorer is still testnet.
Looking into that now

**Comment by ranatrk** [comment]
Based on the comment in the PR https://github.com/threefoldtech/js-sdk/pull/118#issuecomment-650101467, will add an option to setup identities from the admin dashboard to be able to switch between identities instead of explorers in the dashboard

**Comment by ranatrk** [comment]
Based on the comment in the PR https://github.com/threefoldtech/js-sdk/pull/118#issuecomment-650101467, will add an option to setup identities from the admin dashboard to be able to switch between identities instead of explorers in the dashboard

**Comment by ranatrk** [comment]
updates : https://github.com/threefoldtech/js-sdk/pull/261

**Comment by ranatrk** [comment]
Identities
- Add/register new identity from dashboard settings
- View identities in dashboard settings
- Delete identity from dashboard
- Change default identity used from dashboard (will be set in ` j.core.identity.me`)

Wallets
- Add update known trustline option for wallets from dashboard

**Comment by hossnys** [comment]
verified :

add new identity : 

![Screenshot from 2020-07-26 12-50-43](https://user-images.githubusercontent.com/26298009/88477697-70792480-cf42-11ea-9ae2-b60214e94840.png)

view identities :
![Screenshot from 2020-07-26 13-23-17](https://user-images.githubusercontent.com/26298009/88477735-b46c2980-cf42-11ea-8449-a2ba70e07e5b.png)


delete identity :

![Screenshot from 2020-07-26 12-51-20](https://user-images.githubusercontent.com/26298009/88477699-74a54200-cf42-11ea-8b1e-1fb4a0b04a68.png)


- also changing identity from dashboard is working fine.

update trustline option :
![Screenshot from 2020-07-26 13-26-03](https://user-images.githubusercontent.com/26298009/88477775-1462d000-cf43-11ea-8ce4-47fab0fb65cd.png)
