### ISSUE TITLE
adding and removing package doesn't effect in package list in jsng shell

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/js-sdk#940]
### Version information

* OS:  Ubuntu 20.04, 18.04
* Branch: development
* commit: 270a4e0c8e0821ad6918273f0fd4dc4ea0f9f6ef

### Steps to reproduce:

1- trying to add package from the admin dashboard. 
2- check the package list from the `jsng` shell using this command `j.servers.threebot.default.packages.list_all()`

![ff](https://user-images.githubusercontent.com/21218053/92108466-bbab1080-ede7-11ea-8dc3-fbdcae2db08f.png)

3- you should logout from jsng shell and log in again to see the package if added or not. 

![ff1](https://user-images.githubusercontent.com/21218053/92108629-f9a83480-ede7-11ea-89f3-779714de6058.png)

**Comment by ranatrk** [comment]
Couldn't reproduce. Tried the following
- scenario 1: add/delete packages from admin then list packages without restarting js-ng shell
- scenario 2: add/delete packages from admin then restart js-ng shell then start threebot server then list packages
- scenario 3: add/delete packages from admin then restart js-ng shell then list packages without starting threebot server

**Comment by xmonader** [comment]
@Dina-Abd-Elrahman if you started with `threebot start` it will be running in a different memory segment, if you want to see it in the same shell, you need to start threebotserver from jsng `j.servers.threebot.start_default()`

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** fe6a5b98fcfcb3713fe5aca83b1631be05fe9c83, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/92326656-18126800-f054-11ea-8273-a4340618ad03.png)

![ff1](https://user-images.githubusercontent.com/21218053/92326682-3d06db00-f054-11ea-80d4-550b9506e7e9.png)
