### ISSUE TITLE
Clear the purpose of what is Key and Value when clicking on Add Package

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#941]
When I click on Add Package 

I see 
- path 
- git url (that's not quite right) it needs to be `git ur/tree/branch/`
- Key / Value list: I know these are the startup params for the package so you can run it with different params, but that isn't clear by anymeans to the users.
![image](https://user-images.githubusercontent.com/64129/92109036-9c60b300-ede8-11ea-8ab2-cead04af8e9c.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 472d6c016a174dd5c94a2c3a2a007074a0488845, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/95967059-1df62880-0e0c-11eb-968f-ce67167c8df0.png)
