### ISSUE TITLE
the network chatflow name question doesn't make sense for the domain part

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#945]
![image](https://user-images.githubusercontent.com/64129/92111180-37a75780-edec-11ea-975c-8303c8fe6913.png)

- we can't have a domain for network

**Comment by mhost39** [comment]
Verified
commit : 3f1666f351edca360a152a3bfb853a341c078955
branch: development 
![github](https://user-images.githubusercontent.com/31102305/92324827-813eaf00-f045-11ea-8824-c6a66e3c0bef.png)
