### ISSUE TITLE
can we make the default version to be IPv4 for network in its chatflow?

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#946]
![image](https://user-images.githubusercontent.com/64129/92111409-89e87880-edec-11ea-9352-07ecec3b051a.png)

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-09-06 16-02-34](https://user-images.githubusercontent.com/26298009/92327417-f320f380-f059-11ea-9267-27df6ab24fa9.png)
