### ISSUE TITLE
unclear description for ip range step

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#948]
![image](https://user-images.githubusercontent.com/64129/92111829-30cd1480-eded-11ea-8f0d-121760c82a14.png)

should be mentioned at least

**Comment by xmonader** [comment]
- what does the 3Bot has to do with Network chatflow?
- what is exactly needed for the ip range .. more description needed

**Comment by AhmedHanafy725** [comment]
**Branch:** development_vdc
**Commit:** e7e47eed8ba92bdc91de80127d02dd06b6c673ef

![image](https://user-images.githubusercontent.com/41957921/107533668-d61fbc00-6bc7-11eb-830c-7b2bc69d56c8.png)

**Comment by AhmedHanafy725** [comment]
**Verified**
**Branch:** development_vdc
**Commit:** bff59b97a92c04c4e5306ea36c045667d4fc2925
![image](https://user-images.githubusercontent.com/41957921/107875420-67dd4100-6ec8-11eb-9f50-a735fd4e0e3a.png)
