### ISSUE TITLE
Network chatflow: wireguard installation info and the actual config need to be in the same screen 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#949]
![image](https://user-images.githubusercontent.com/64129/92112007-6ffb6580-eded-11ea-85b4-a8961b9e7f9f.png)
![image](https://user-images.githubusercontent.com/64129/92112040-7db0eb00-eded-11ea-935d-200c85876e13.png)

Both should be in the same screen

**Comment by mhost39** [comment]
Verified
commit : 81773bf8ca5e948f05dcee61a7daf16d164c0809
branch: development
![image](https://user-images.githubusercontent.com/31102305/92448973-a7855b80-f1b9-11ea-9a8d-18606bfa6bd9.png)
