### ISSUE TITLE
Network flow: wireguard results screen is out of shape

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#950]
![image](https://user-images.githubusercontent.com/64129/92112171-af29b680-eded-11ea-92a3-41e3c0a2a22f.png)

We should remove the "Click next" thing

**Comment by xmonader** [comment]
447a7a4eda53c0421f200762fb2ae07e88fa0ca4

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-09-06 15-18-38](https://user-images.githubusercontent.com/26298009/92327648-68d98f00-f05b-11ea-9139-e3410020e9c4.png)
