### ISSUE TITLE
please select a network message update

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#952]
![image](https://user-images.githubusercontent.com/64129/92112907-ca48f600-edee-11ea-9763-b47bf766cb0b.png)

Should mention the reason for needing a network (to connect your solution to)

**Comment by AhmedHanafy725** [comment]
**Branch:** development_vdc
**Commit:** e7e47eed8ba92bdc91de80127d02dd06b6c673ef

![image](https://user-images.githubusercontent.com/41957921/107533298-7b866000-6bc7-11eb-92f2-f49dba5e53b4.png)

**Comment by AhmedHanafy725** [comment]
**Verified**
**Branch:** development_vdc
**Commit:** bff59b97a92c04c4e5306ea36c045667d4fc2925

![image](https://user-images.githubusercontent.com/41957921/107879344-f8c01680-6ee0-11eb-95aa-a7e0e0bdab98.png)

![image](https://user-images.githubusercontent.com/41957921/107879352-01b0e800-6ee1-11eb-8760-8c3d1eadd481.png)

![image](https://user-images.githubusercontent.com/41957921/107879356-08d7f600-6ee1-11eb-9c18-778de180593d.png)

![image](https://user-images.githubusercontent.com/41957921/107879364-0ecdd700-6ee1-11eb-9841-8a6855b08c31.png)

![image](https://user-images.githubusercontent.com/41957921/107879371-12f9f480-6ee1-11eb-994c-191ca66ab3c6.png)

![image](https://user-images.githubusercontent.com/41957921/107879374-18573f00-6ee1-11eb-940a-64473db4eedc.png)
