### ISSUE TITLE
how to actually use the container logs feature?

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#953]
![image](https://user-images.githubusercontent.com/64129/92113012-f795a400-edee-11ea-8b99-af35b8a62777.png)

I'm not aware of that document even or how that feature works?

**Comment by ranatrk** [comment]
A redis container is created when choosing YES, where the zos logs are directed to it according to [https://sdk.threefold.io/#/capacity_container?id=logs](https://sdk.threefold.io/#/capacity_container?id=logs)
