### ISSUE TITLE
Ubuntu chatflow: Access Keys screen

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#955]
![image](https://user-images.githubusercontent.com/64129/92113216-45121100-edef-11ea-91ac-02e88948a19e.png)

- it's just one key we support (so Access Key instead of Access Keys)
- we can validate its content? (next milestone maybe?)
- message should be something like "Please upload your public SSH key to be able to access the depolyed container via ssh" instead of `Please add your public ssh key, this will allow you to access the deployed container using ssh. Just upload the file with the key`

**Comment by xmonader** [comment]
ce1077dfae7a3dd58c21bcee97b22435d0d0fe54

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-09-06 16-07-57](https://user-images.githubusercontent.com/26298009/92327532-a2f66100-f05a-11ea-9a87-10134a7d09d0.png)
