### ISSUE TITLE
ubuntu: improve success message

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#959]
![image](https://user-images.githubusercontent.com/64129/92114019-763f1100-edf0-11ea-9479-36b706e7034c.png)

should be `your {kind} has been deployed successfully`

**Comment by RafyAmgadBenjamin** [comment]
fixed
#### Branch 
`development_update_ubuntu_succ_message`
#### Commit_id
07ee20e91a6d178f5989105919051a0242b15236

![image](https://user-images.githubusercontent.com/46320202/93318099-91f1e080-f80e-11ea-8698-40e9e4076828.png)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 8c032153405fd6307137b3024a313c25babbe6d1, **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/93325642-e483ca80-f817-11ea-8ec8-d6eccf0a0d8d.png)
