### ISSUE TITLE
Changing time without changing date is not working

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/js-sdk#961]
### Description

when deploying an app/solution when choosing the expiration date time, changing time only is not working
only works if you click on date even if you didn't change it, just click on the date and then choose time, in this case it works
### Version information

* OS:  Ubuntu 19.04
* project commit/version: e.g. js-ng 11.0.0a2
* Browser: e.g. chrome 79

### Steps to reproduce
try to deploy a solution and change the expiration time only
List of steps to reproduce the problem if it's a bug

![Screenshot from 2020-09-03 14-38-36](https://user-images.githubusercontent.com/1689456/92115749-3594c700-edf3-11ea-8e5e-6bd00088013c.png)

**Comment by Dina-Abd-Elrahman** [comment]
![ff](https://user-images.githubusercontent.com/21218053/93319798-9ae3b180-f810-11ea-9ec2-caabb0875623.png)
