### ISSUE TITLE
UI: increasing the line spacing in the deploy page of a wizard

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/js-sdk#965]
The spacing between 'Deploying' and the line of the reservation id is too small the text is overlapping

![image](https://user-images.githubusercontent.com/10920323/92118133-59a5d780-edf6-11ea-88b1-22af1c889a9d.png)

**Comment by ranatrk** [comment]
Added spacing between deploying and the workload ID:
![Screenshot from 2020-09-03 15-56-38](https://user-images.githubusercontent.com/17128393/92124920-abeaf680-edfe-11ea-8c00-9708cd8840a9.png)

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-09-06 16-24-51](https://user-images.githubusercontent.com/26298009/92327872-05e8f780-f05d-11ea-9e49-db04815a1828.png)
