### ISSUE TITLE
typo in network chat flow

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#966]
you workload --> your workload 

![image](https://user-images.githubusercontent.com/41957921/92118614-008a7380-edf7-11ea-9685-baf96da7c31d.png)

**Comment by hossnys** [comment]
typo of ```you workload``` still there 

![Screenshot from 2020-09-06 15-42-27](https://user-images.githubusercontent.com/26298009/92327188-337f7200-f058-11ea-92c2-0738fedf5c04.png)

**Comment by ranatrk** [comment]
The original screenshot is a different message than the second one. Fixed to `your workload`.

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** 881f1904e00ba187ecf254cd8ba4857949767d38 , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/92367622-f1f1d400-f0f6-11ea-98de-663416691a4e.png)
