### ISSUE TITLE
Blog/website/wiki solution is not working

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/js-sdk#968]
### Description
this issue is happening for blog/wiki/websites solutions 
Creating a wiki is not working, it keeps hanging on i`nitializing your wiki....`
### Version information

* OS: e.g. Ubuntu 19.10
* project commit/version: e.g. js-ng 11.0.0a2
* Browser: chrome 79
*

### Steps to reproduce

try deploying a new wiki
![Screenshot from 2020-09-03 14-50-52](https://user-images.githubusercontent.com/1689456/92120537-7b548e00-edf9-11ea-9f92-1986c833eaf9.png)

workload info
![Screenshot from 2020-09-03 15-41-43](https://user-images.githubusercontent.com/1689456/92123478-fec3ae80-edfc-11ea-95f9-ae5ba98ab8d5.png)

**Comment by OmarElawady** [comment]
Got the same error when deploying ubuntu
https://explorer.testnet.grid.tf/api/v1/reservations/workloads/474036

**Comment by DylanVerstraete** [comment]
Following up in: https://github.com/threefoldtech/zos/issues/920

**Comment by DylanVerstraete** [comment]
@OmarElawady @ashraffouda There was a problem with this specific node. We did some tests on it and it seems something failed. This node is now rebooted with another identity. So I will close this issue since we resolved it.

**Comment by xmonader** [comment]
Thanks @DylanVerstraete! I need to keep this issue open as part of our acceptance test to be verified.

**Comment by hossnys** [comment]
verified and it's working fine now 

![Screenshot from 2020-09-06 16-49-08](https://user-images.githubusercontent.com/26298009/92328336-73e2ee00-f060-11ea-89a7-c015670f9beb.png)

![Screenshot from 2020-09-06 16-49-31](https://user-images.githubusercontent.com/26298009/92328341-78a7a200-f060-11ea-8206-fe0cc776bc21.png)
