### ISSUE TITLE
Website deployment on demo2.grid.tf gives error

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/js-sdk#970]
### Description

Trying to deploy a website on demo2.grid.tf, it generates an error

<img width="978" alt="Schermafbeelding 2020-09-04 om 10 42 31" src="https://user-images.githubusercontent.com/30384423/92219893-7c3dfc00-ee9b-11ea-9a5d-6bc5c51d4e4e.png">

### Version information

MacOS, 
demo2.grid.tf
Browser: chrome 84

**Comment by rkhamis** [comment]
@gmachtel already done a lot of deployments since. please reopen with more details if you re-encouter this
