### ISSUE TITLE
Wrong redirect after deploying Ubuntu solution

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#971]
### Version information

* OS: docker Ubuntu 20.04
* Branch: development
* commit: de4a3ba08a14ea5c54b86abb94898210d7931e23
* Browser: Version 84.0.4147.125 (Official Build) (64-bit)
* explorer: testnet

### Steps to reproduce
1- Create a Ubuntu solution.
2- After it finishes, click on `Finish` button.
![image](https://user-images.githubusercontent.com/41957921/92123170-9bd21780-edfc-11ea-88e5-d52778870e80.png)
3- It will redirect you to network workloads, not ubuntu one.
![image](https://user-images.githubusercontent.com/41957921/92123330-cae88900-edfc-11ea-95b0-4308bf7c35dc.png)

**Comment by OmarElawady** [comment]
Couldn't reproduce. Changed status for further verification.

**Comment by AhmedHanafy725** [comment]
it can be reproduced by:
1- create a network
2- once it finishes, it will be redirected to network workloads.

![image](https://user-images.githubusercontent.com/41957921/92155362-90481600-ee27-11ea-950c-5064a6db4db8.png)

3- click on solution button in the sidebar
4- click on new button for ubuntu solution.

![image](https://user-images.githubusercontent.com/41957921/92155500-cdaca380-ee27-11ea-8190-0d6d6145960e.png)

5- continue to finish ubuntu solution
6- it will redirect to the network workload not ubuntu workloads.

**Comment by mhost39** [comment]
Verified
commit: fed04ab4455f22b6808d6ce4f0df4a6f7f52cfb3
branch: development

1- create a network
2- once it finishes, it will be redirected to network workloads.
![image](https://user-images.githubusercontent.com/31102305/92329134-b8bd5380-f065-11ea-9bae-6cf04a913c80.png)
3- click on solution button in the sidebar
4- click on new button for ubuntu solution.
5- continue to finish ubuntu solution
6- it will redirect to ubuntu workloads.
![image](https://user-images.githubusercontent.com/31102305/92329172-f0c49680-f065-11ea-8757-fb313281734b.png)
