### ISSUE TITLE
Last step in network chatflow should contain FINISH button instead of NEXT

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#972]
### Version information

* OS: docker Ubuntu 20.04
* Branch: development
* commit: de4a3ba08a14ea5c54b86abb94898210d7931e23
* Browser: Version 84.0.4147.125 (Official Build) (64-bit)
* explorer: testnet

### Steps to reproduce
1- Create network and continue till the end.

`NEXT` button at the last step should be `FINISH` button

![image](https://user-images.githubusercontent.com/41957921/92124075-9e813c80-edfd-11ea-9184-429cf08c48eb.png)

**Comment by OmarElawady** [comment]
fixed in #958

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-09-06 15-18-38](https://user-images.githubusercontent.com/26298009/92326636-f6b17c00-f053-11ea-974f-59ea0bed20f5.png)
