### ISSUE TITLE
threebot depolyer doesn't respect user currency choices and always showing that tft choosed.

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/js-sdk#974]
on https://deploy3bot-2.grid.tf/ when deploying new 3bot it ask for the currency , so when choose freetft it show in the next window paying message with tft and QR code when scanned on 3bot app it show that payment will be with tft not freetft as chosen.

![Screenshot from 2020-09-03 15-55-59](https://user-images.githubusercontent.com/26298009/92125069-d937a480-edfe-11ea-98b8-33471b1b3bad.png)

![Screenshot from 2020-09-03 15-56-20](https://user-images.githubusercontent.com/26298009/92125076-db016800-edfe-11ea-9fb2-cd4cb2c6816f.png)

![photo_2020-09-03_16-09-04](https://user-images.githubusercontent.com/26298009/92125393-4814fd80-edff-11ea-9d60-cc0d2f4f0f19.jpg)

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** fe6a5b98fcfcb3713fe5aca83b1631be05fe9c83 , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/92328782-6e3ad780-f063-11ea-8c2c-68d588a7804a.png)

![ff](https://user-images.githubusercontent.com/21218053/92328839-d25d9b80-f063-11ea-8b13-72115f513a0b.jpg)
