### ISSUE TITLE
Tf Grid Demo2: Mattermost failed

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#976]
1st time
![Screenshot from 2020-09-03 16-34-27](https://user-images.githubusercontent.com/17138347/92129130-68df5200-ee03-11ea-8113-cd0281b18b86.png)

2nd time
![Screenshot from 2020-09-03 16-36-05](https://user-images.githubusercontent.com/17138347/92129264-94623c80-ee03-11ea-8ae8-a3830496940f.png)

**Comment by rkhamis** [comment]
@DylanVerstraete we've managed to deploy mattermost multiple times since this was opened.
I'll close, but please reopen with env details if you come across any issues
