### ISSUE TITLE
More than one step in chatflows with FINISH button

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/js-sdk#978]
### Version information

* OS: docker Ubuntu 20.04
* Branch: development
* commit: 8fedc35bd592af5ea5640e32fab4f74ce956aed5
* Browser: Version 84.0.4147.125 (Official Build) (64-bit)
* explorer: testnet

### Steps to reproduce
1- Create 4 to 6 gateway.

At the end it has 2 steps with finish button
![image](https://user-images.githubusercontent.com/41957921/92132009-e6589180-ee06-11ea-9f67-a56e0edac886.png)

![image](https://user-images.githubusercontent.com/41957921/92132036-f07a9000-ee06-11ea-9793-03139c71cdd7.png)

**Comment by AhmedHanafy725** [comment]
also in network one 

![image](https://user-images.githubusercontent.com/41957921/92132192-23248880-ee07-11ea-97de-eb87d2b4c334.png)

![image](https://user-images.githubusercontent.com/41957921/92132203-2750a600-ee07-11ea-9c45-d7762c08e22e.png)

![image](https://user-images.githubusercontent.com/41957921/92132236-32a3d180-ee07-11ea-8a9e-7c0b2241afdf.png)

**Comment by hossnys** [comment]
this is stil there in network chatflow

![Screenshot from 2020-09-06 15-18-38](https://user-images.githubusercontent.com/26298009/92326804-201ed780-f055-11ea-8a26-00d6d87c13f2.png)

![Screenshot from 2020-09-06 15-18-29](https://user-images.githubusercontent.com/26298009/92326802-1e551400-f055-11ea-93ec-4452b0fc1c1d.png)


development branch 
```
root@js-ng:/sandbox/code/github/threefoldtech/js-sdk# git log
commit fe6a5b98fcfcb3713fe5aca83b1631be05fe9c83 (HEAD -> development, origin/development, origin/HEAD)
Author: Rana Tarek Hassan <rana.t.hassan@gmail.com>
Date:   Sun Sep 6 12:27:08 2020 +0200

    Update solution descriptions in admin dashboard (#1003)

```

**Comment by hossnys** [comment]
verified 

![Screenshot from 2020-09-07 10-35-46](https://user-images.githubusercontent.com/26298009/92366429-6deb1c80-f0f5-11ea-9ade-24e27ad9ac6b.png)

![Screenshot from 2020-09-07 10-35-55](https://user-images.githubusercontent.com/26298009/92366434-6fb4e000-f0f5-11ea-9db4-a5790029ff60.png)
