### ISSUE TITLE
TF Grid Demo2: Cryptpad does not function

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#983]
I managed to deploy a cryptpad instance but it does not respond to any of the functionality.
For example: opening sheets:
![Screenshot from 2020-09-03 17-26-39](https://user-images.githubusercontent.com/17138347/92135230-ca56ef00-ee0a-11ea-94fe-8d038e0558a8.png)

Deployment info:

```
{
   "-""wids":[
      474102,
      474105,
      474104,
      474106
   ],
   "Name":"cryptpad",
   "Domain":"dylanv-cryptpad-cryptpad.tfgw-testnet-01.gateway.tf",
   "IPv4 Address":"10.100.3.2",
   "IPv6 Address":"fd52:5857:5666:3::2",
   "Node":"2m3nHPSAMyZFSeg5HPozic2NGBMtrXrBkhtNcVmd5Ss6",
   "Farm":"freefarm",
   "Pool":1172,
   "Network":"dylanv.3bot_apps",
   "Expiration":1599191510,
   "CPU":1,
   "Memory":1024,
   "RootFS Type":"SSD",
   "RootFS Size":1024
}
```

**Comment by OmarElawady** [comment]
It works with me on Ubuntu using  firefox.

![Screenshot from 2020-09-03 17-44-55](https://user-images.githubusercontent.com/13040543/92137356-51a56200-ee0d-11ea-80df-01e58b7b7e51.png)

**Comment by DylanVerstraete** [comment]
Indeed, works on other browser.
