### ISSUE TITLE
Solutions detail: when you copy out json it's not formatted correctly

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/js-sdk#984]
For example if you tried copying this 
![Screenshot from 2020-09-03 17-29-12](https://user-images.githubusercontent.com/17138347/92135387-fd997e00-ee0a-11ea-8229-69a077a80fc5.png)

you will get:
```
{
 
 
-
 
 
 
"wids"
: 
[
 
 
 
 
 
 
 
 
474102
,
 
 
 
 
 
 
 
 
474105
,
 
 
 
 
 
 
 
 
474104
,
 
 
 
 
 
 
 
 
474106
 
 
 
 
 
 
]
,
 
 
 
 
 
 
"Name"
: 
"cryptpad"
,
 
 
 
 
 
 
"Domain"

..........

```

Suggestion: add a copy to clipboard function

**Comment by xmonader** [comment]
will be addressed in https://github.com/threefoldtech/js-sdk/issues/1632
