### ISSUE TITLE
Auto backup option needs to be enabled by default

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#987]
![image](https://user-images.githubusercontent.com/64129/92144731-6e469780-ee17-11ea-8573-ec83e30033d2.png)

I created a 3bot online and autobackup should be on not off

**Comment by Pishoy** [comment]
verified
![image](https://user-images.githubusercontent.com/21987477/92464631-b413af00-f1cd-11ea-98e7-811fa4cbb43a.png)
