### ISSUE TITLE
Mattermost Failed to deploy workload

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/js-sdk#989]
### Description

when deploying mattermost at the last step it showed the following 
![Screenshot from 2020-09-03 16-24-31](https://user-images.githubusercontent.com/1689456/92147139-f67a6c00-ee1a-11ea-803c-09484db21c8d.png)

and the workload info
![Screenshot from 2020-09-03 16-33-12](https://user-images.githubusercontent.com/1689456/92147202-0db95980-ee1b-11ea-8a3a-20d360b62105.png)

### Version information

* OS: Ubuntu 19.10
* project commit/version: e.g. js-ng 11.0.0a2
* Browser: chrome 79

**Comment by xmonader** [comment]
on explorer 
![image](https://user-images.githubusercontent.com/64129/92149651-98e81e80-ee1e-11ea-9fd2-c150da4eaea6.png)

**Comment by DylanVerstraete** [comment]
Following up in: https://github.com/threefoldtech/zos/issues/919

**Comment by DylanVerstraete** [comment]
@ashraffouda Same issue as https://github.com/threefoldtech/js-sdk/issues/968. Resolved now!

**Comment by hossnys** [comment]
verified and mattermost deployed successfully

![Screenshot from 2020-09-06 16-38-38](https://user-images.githubusercontent.com/26298009/92328159-126e4f80-f05f-11ea-9afc-c71c0b51f86b.png)

![Screenshot from 2020-09-06 16-39-08](https://user-images.githubusercontent.com/26298009/92328162-15694000-f05f-11ea-910d-03622565c505.png)
