### ISSUE TITLE
cant deploy a new 3bot

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/js-sdk#997]
<img width="1143" alt="Screenshot 2020-09-04 at 17 15 14" src="https://user-images.githubusercontent.com/43240801/92255550-c9899000-eed2-11ea-87aa-d327e8060bb4.png">

urgent need a new 3bot in order to update manual and dont know why cant deploy

**Comment by xmonader** [comment]
if on deploy3bot-2.grid.tf error is 
![image](https://user-images.githubusercontent.com/64129/92268594-f80f6700-eee2-11ea-8c05-3e6c0e230c1a.png)

if for deploy3bot.grid.tf

![image](https://user-images.githubusercontent.com/64129/92268715-373db800-eee3-11ea-8b48-631d82cfbfc2.png)

**Comment by xmonader** [comment]
Issue was happening because FreeFarm nodes weren't all free to use. should be fixed now

**Comment by hossnys** [comment]
verified and deploying 3bot now working fine 

![Screenshot from 2020-09-06 16-59-10](https://user-images.githubusercontent.com/26298009/92328629-6d557600-f062-11ea-9b3e-dc1b61302443.png)

![Screenshot from 2020-09-06 17-01-54](https://user-images.githubusercontent.com/26298009/92328632-6f1f3980-f062-11ea-987a-586501adb66b.png)

![Screenshot from 2020-09-06 17-03-18](https://user-images.githubusercontent.com/26298009/92328633-6fb7d000-f062-11ea-9e7e-4db9a48c81ca.png)
