### ISSUE TITLE
document how to start with an identity from generated words and how to add access to an existing 3bot user to it

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#998]
document the flow around 
e.g
```
identity_test = j.core.identity.new(
        "test", tname=tname, email=email, words=words, explorer_url="https://explorer.testnet.grid.tf/api/v1"
    )
```
- setting it as the default
- adding existing 3bot user to admins

**Comment by xmonader** [comment]
info exists/duplicated in 
- https://github.com/threefoldtech/js-ng/blob/development/docs/wiki/identity.md
- https://github.com/threefoldtech/js-sdk/blob/development/docs/wiki/identity.md

please unify in js-sdk repo and add section for adding admins

**Comment by Pishoy** [comment]
verified
