### ISSUE TITLE
When starting gedis port is taken

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#999]
![image](https://user-images.githubusercontent.com/64129/92304306-2477c180-ef7d-11ea-8573-080d2610aae7.png)

Suggest that when we check for the running services if part of them are running we kill them all and start all over again or make sure that `threebot stop`  really works fine

**Comment by OmarElawady** [comment]
fixed by #1073

**Comment by Dina-Abd-Elrahman** [comment]
**Commit_ID** f7492f7ffaf2dad854e3d1014127d588078cafce , **Branch** development

![ff](https://user-images.githubusercontent.com/21218053/92602530-8a7e8480-f2ae-11ea-919a-9e14ecd020e0.png)
